from dxctechnology.workday_user_import_v1.user_import.config import *
from dxctechnology.workday_user_import_v1.user_import.mappers.master_mapper import MAPPER

instance = "sandbox2"

version = "v2"
process_time_off_accrual_dag_version = "v1"

environment = "pre-production"
can_run_batch_task_var_name_portugal = f"dxctechnology_workday_user_import_portugal_can_run_batch_task_variable_{instance}"

company_key = "dxcsandbox2"
replicon_conn_id = "replicon_dxcsandbox2_x.workday_1"
sftp_conn_id = "sftp_dxcsandbox2_628172_Workday"

DXC_WORKDAY_USER_SYNC_USER_MAPPER = MAPPER

portugal_add_user_timeoff_assignment_dag_id = f"dxctechnology_workday_user_import_process_portugal_add_user_timeoff_child_dag_{instance}_{version}"
portugal_update_user_timeoff_assignment_dag_id = f"dxctechnology_workday_user_import_process_portugal_update_user_timeoff_child_dag_{instance}_{version}"
portugal_add_user_dag_id = f"dxctechnology_workday_user_import_process_portugal_add_user_child_dag_{instance}_{version}"
portugal_update_user_dag_id = f"dxctechnology_workday_user_import_process_portugal_update_user_child_dag_{instance}_{version}"
workday_user_import_process_portugal_users_child_dag = f"dxctechnology_workday_user_import_process_portugal_process_user_child_dag_{instance}_{version}"
workday_user_import_portugal_users_update_user_rehire_timeoff_process_child_dag = f"dxctechnology_workday_user_import_portugal_users_update_user_rehire_timeoff_assignment_process_child_{instance}_{version}"
process_time_off_accrual = f"dxctechnology_workday_user_sync_timeoff_assignment_policy_update_for_no_accrual_child_{instance}_{process_time_off_accrual_dag_version}"
workday_user_import_global_users_update_user_timeoff_process_child_dag_disable = f"dxctechnology_workday_user_import_global_users_update_user_timeoff_process_child_for_disable_user_{instance}_{version}"

ia_version = "v1"
workday_user_import_ia_zero_timeoff_assignment_child_dag = f"dxctechnology_workday_user_import_ia_zero_timeoff_assignment_child_{instance}_{ia_version}"
workday_user_import_ia_one_timeoff_assignment_child_dag = f"dxctechnology_workday_user_import_ia_one_timeoff_assignment_child_{instance}_{ia_version}"

# Cleanup child DAG ID for disabled users
delete_future_entries_child_dag_id = f"dxctechnology_workday_user_sync_delete_future_entries_child_{instance}_v2"

# Overrides: bump max_active_runs to 10 for this environment (base defaults in config.py are unchanged, so production is not affected)
global_add_user_max_active_runs = 10
process_users_max_active_runs = 10
