SOUTH_AFRICA_MAPPER = [
    {
        "country": "South Africa",
        "location": "ALL",
        "worker_type": "Employee",
        "compensation_grade": "Salary",
        "contract_type": "Full_time",
        "employee_type": [
            "Regular",
            "Fixed Term",
            "Partner",
            "Intern",
            "Non-Salaried / Self-Employed",
            "Non-Salaried / Self-Employed (Fixed Term)"
        ],
        "job_category": "Functional",
        "management_level": [
            "Partner",
            "Executive Vice President",
            "Senior Vice President",
            "Vice President",
            "Director",
            "Senior Manager",
            "Manager",
            "Senior Associate",
            "Specialist 1",
            "Specialist 2",
            "Associate",
            "Trainee/Apprentice",
            "Administrative 1",
            "Administrative 2"
        ],
        "additional_job_classification": "NA",
        "schedule_type": "Office Schedule (Assigned to user via another automation)",
        "work_week": "Sunday to Saturday",
        "timesheet_template": "South Africa TSD Agile Emp NON-OT",
        "time_entry_approval_path": "Automatic Approval",
        "timesheet_approval": "Supervisor",
        "timesheet_period": "Weekly without crossing months",
        "time_off_template": "Time Off",
        "time_off_approval": "System",
        "time_off_types": [
            "Holiday",
            "Leave of Absence"
        ],
        "payrule": "South Africa Pay Rule NON-OT",
        "time_zone": "(UTC+2:00) South Africa Standard Time",
        "holiday_calendar": "South Africa Holiday Calendar",
        "authentication_type": "SSO"
    },
    {
        "country": "South Africa",
        "location": "ALL",
        "worker_type": "Employee",
        "compensation_grade": "Salary",
        "contract_type": "Part_time",
        "employee_type": [
            "Regular",
            "Fixed Term",
            "Partner",
            "Intern",
            "Non-Salaried / Self-Employed",
            "Non-Salaried / Self-Employed (Fixed Term)"
        ],
        "job_category": "Functional",
        "management_level": [
            "Partner",
            "Executive Vice President",
            "Senior Vice President",
            "Vice President",
            "Director",
            "Senior Manager",
            "Manager",
            "Senior Associate",
            "Specialist 1",
            "Specialist 2",
            "Associate",
            "Trainee/Apprentice",
            "Administrative 1",
            "Administrative 2"
        ],
        "additional_job_classification": "NA",
        "schedule_type": "Office Schedule (Assigned to user via another automation)",
        "work_week": "Sunday to Saturday",
        "timesheet_template": "South Africa TSD Agile Emp NON-OT",
        "time_entry_approval_path": "Automatic Approval",
        "timesheet_approval": "Supervisor",
        "timesheet_period": "Weekly without crossing months",
        "time_off_template": "Time Off",
        "time_off_approval": "System",
        "time_off_types": [
            "Holiday",
            "Leave of Absence"
        ],
        "payrule": "South Africa Pay Rule NON-OT",
        "time_zone": "(UTC+2:00) South Africa Standard Time",
        "holiday_calendar": "South Africa Holiday Calendar",
        "authentication_type": "SSO"
    },
    {
        "country": "South Africa",
        "location": "ALL",
        "worker_type": "Employee",
        "compensation_grade": "Salary",
        "contract_type": "Full_time",
        "employee_type": [
            "Regular",
            "Fixed Term",
            "Partner",
            "Intern",
            "Non-Salaried / Self-Employed",
            "Non-Salaried / Self-Employed (Fixed Term)"
        ],
        "job_category": "Client Services",
        "management_level": [
            "Partner",
            "Executive Vice President",
            "Senior Vice President",
            "Vice President",
            "Director",
            "Senior Manager",
            "Manager",
            "Senior Associate",
            "Specialist 1",
            "Specialist 2",
            "Associate",
            "Trainee/Apprentice",
            "Administrative 1",
            "Administrative 2"
        ],
        "additional_job_classification": "NA",
        "schedule_type": "Office Schedule (Assigned to user via another automation)",
        "work_week": "Sunday to Saturday",
        "timesheet_template": "South Africa TSD Agile Emp NON-OT",
        "time_entry_approval_path": "Automatic Approval",
        "timesheet_approval": "Supervisor",
        "timesheet_period": "Weekly without crossing months",
        "time_off_template": "Time Off",
        "time_off_approval": "System",
        "time_off_types": [
            "Holiday",
            "Leave of Absence"
        ],
        "payrule": "South Africa Pay Rule NON-OT",
        "time_zone": "(UTC+2:00) South Africa Standard Time",
        "holiday_calendar": "South Africa Holiday Calendar",
        "authentication_type": "SSO"
    },
    {
        "country": "South Africa",
        "location": "ALL",
        "worker_type": "Employee",
        "compensation_grade": "Salary",
        "contract_type": "Part_time",
        "employee_type": [
            "Regular",
            "Fixed Term",
            "Partner",
            "Intern",
            "Non-Salaried / Self-Employed",
            "Non-Salaried / Self-Employed (Fixed Term)"
        ],
        "job_category": "Client Services",
        "management_level": [
            "Partner",
            "Executive Vice President",
            "Senior Vice President",
            "Vice President",
            "Director",
            "Senior Manager",
            "Manager",
            "Senior Associate",
            "Specialist 1",
            "Specialist 2",
            "Associate",
            "Trainee/Apprentice",
            "Administrative 1",
            "Administrative 2"
        ],
        "additional_job_classification": "NA",
        "schedule_type": "Office Schedule (Assigned to user via another automation)",
        "work_week": "Sunday to Saturday",
        "timesheet_template": "South Africa TSD Agile Emp NON-OT",
        "time_entry_approval_path": "Automatic Approval",
        "timesheet_approval": "Supervisor",
        "timesheet_period": "Weekly without crossing months",
        "time_off_template": "Time Off",
        "time_off_approval": "System",
        "time_off_types": [
            "Holiday",
            "Leave of Absence"
        ],
        "payrule": "South Africa Pay Rule NON-OT",
        "time_zone": "(UTC+2:00) South Africa Standard Time",
        "holiday_calendar": "South Africa Holiday Calendar",
        "authentication_type": "SSO"
    },
    {
        "country": "South Africa",
        "location": "ALL",
        "worker_type": "Employee",
        "compensation_grade": "Hourly",
        "contract_type": "Full_time",
        "employee_type": [
            "Regular",
            "Fixed Term",
            "Partner",
            "Intern",
            "Non-Salaried / Self-Employed",
            "Non-Salaried / Self-Employed (Fixed Term)"
        ],
        "job_category": "Functional",
        "management_level": [
            "Partner",
            "Executive Vice President",
            "Senior Vice President",
            "Vice President",
            "Director",
            "Senior Manager",
            "Manager",
            "Senior Associate",
            "Specialist 1",
            "Specialist 2",
            "Associate",
            "Trainee/Apprentice",
            "Administrative 1",
            "Administrative 2"
        ],
        "additional_job_classification": "NA",
        "schedule_type": "Office Schedule (Assigned to user via another automation)",
        "work_week": "Sunday to Saturday",
        "timesheet_template": "South Africa TSD Agile Emp NON-OT",
        "time_entry_approval_path": "Automatic Approval",
        "timesheet_approval": "Supervisor",
        "timesheet_period": "Weekly without crossing months",
        "time_off_template": "Time Off",
        "time_off_approval": "System",
        "time_off_types": [
            "Holiday",
            "Leave of Absence"
        ],
        "payrule": "South Africa Pay Rule NON-OT",
        "time_zone": "(UTC+2:00) South Africa Standard Time",
        "holiday_calendar": "South Africa Holiday Calendar",
        "authentication_type": "SSO"
    },
    {
        "country": "South Africa",
        "location": "ALL",
        "worker_type": "Employee",
        "compensation_grade": "Hourly",
        "contract_type": "Part_time",
        "employee_type": [
            "Regular",
            "Fixed Term",
            "Partner",
            "Intern",
            "Non-Salaried / Self-Employed",
            "Non-Salaried / Self-Employed (Fixed Term)"
        ],
        "job_category": "Functional",
        "management_level": [
            "Partner",
            "Executive Vice President",
            "Senior Vice President",
            "Vice President",
            "Director",
            "Senior Manager",
            "Manager",
            "Senior Associate",
            "Specialist 1",
            "Specialist 2",
            "Associate",
            "Trainee/Apprentice",
            "Administrative 1",
            "Administrative 2"
        ],
        "additional_job_classification": "NA",
        "schedule_type": "Office Schedule (Assigned to user via another automation)",
        "work_week": "Sunday to Saturday",
        "timesheet_template": "South Africa TSD Agile Emp NON-OT",
        "time_entry_approval_path": "Automatic Approval",
        "timesheet_approval": "Supervisor",
        "timesheet_period": "Weekly without crossing months",
        "time_off_template": "Time Off",
        "time_off_approval": "System",
        "time_off_types": [
            "Holiday",
            "Leave of Absence"
        ],
        "payrule": "South Africa Pay Rule NON-OT",
        "time_zone": "(UTC+2:00) South Africa Standard Time",
        "holiday_calendar": "South Africa Holiday Calendar",
        "authentication_type": "SSO"
    },
    {
        "country": "South Africa",
        "location": "ALL",
        "worker_type": "Employee",
        "compensation_grade": "Hourly",
        "contract_type": "Full_time",
        "employee_type": [
            "Regular",
            "Fixed Term",
            "Partner",
            "Intern",
            "Non-Salaried / Self-Employed",
            "Non-Salaried / Self-Employed (Fixed Term)"
        ],
        "job_category": "Client Services",
        "management_level": [
            "Partner",
            "Executive Vice President",
            "Senior Vice President",
            "Vice President",
            "Director",
            "Senior Manager",
            "Manager",
            "Senior Associate",
            "Specialist 1",
            "Specialist 2",
            "Associate",
            "Trainee/Apprentice",
            "Administrative 1",
            "Administrative 2"
        ],
        "additional_job_classification": "NA",
        "schedule_type": "Office Schedule (Assigned to user via another automation)",
        "work_week": "Sunday to Saturday",
        "timesheet_template": "South Africa TSD Agile Emp NON-OT",
        "time_entry_approval_path": "Automatic Approval",
        "timesheet_approval": "Supervisor",
        "timesheet_period": "Weekly without crossing months",
        "time_off_template": "Time Off",
        "time_off_approval": "System",
        "time_off_types": [
            "Holiday",
            "Leave of Absence"
        ],
        "payrule": "South Africa Pay Rule NON-OT",
        "time_zone": "(UTC+2:00) South Africa Standard Time",
        "holiday_calendar": "South Africa Holiday Calendar",
        "authentication_type": "SSO"
    },
    {
        "country": "South Africa",
        "location": "ALL",
        "worker_type": "Employee",
        "compensation_grade": "Hourly",
        "contract_type": "Part_time",
        "employee_type": [
            "Regular",
            "Fixed Term",
            "Partner",
            "Intern",
            "Non-Salaried / Self-Employed",
            "Non-Salaried / Self-Employed (Fixed Term)"
        ],
        "job_category": "Client Services",
        "management_level": [
            "Partner",
            "Executive Vice President",
            "Senior Vice President",
            "Vice President",
            "Director",
            "Senior Manager",
            "Manager",
            "Senior Associate",
            "Specialist 1",
            "Specialist 2",
            "Associate",
            "Trainee/Apprentice",
            "Administrative 1",
            "Administrative 2"
        ],
        "additional_job_classification": "NA",
        "schedule_type": "Office Schedule (Assigned to user via another automation)",
        "work_week": "Sunday to Saturday",
        "timesheet_template": "South Africa TSD Agile Emp NON-OT",
        "time_entry_approval_path": "Automatic Approval",
        "timesheet_approval": "Supervisor",
        "timesheet_period": "Weekly without crossing months",
        "time_off_template": "Time Off",
        "time_off_approval": "System",
        "time_off_types": [
            "Holiday",
            "Leave of Absence"
        ],
        "payrule": "South Africa Pay Rule NON-OT",
        "time_zone": "(UTC+2:00) South Africa Standard Time",
        "holiday_calendar": "South Africa Holiday Calendar",
        "authentication_type": "SSO"
    }
]
