pay_period_mapper = [
  {
    "Deltek Taxable Entity ID": "700",
    "Pay Period Code": "REG01",
    "Permissions": {"User" : "End User with Reports"},
    "Schedule Type": "Shift",
    "Timesheet Period": "Semimonthly",
    "Timesheet Template": "India TS Template",
    "Timesheet Template Approval Path": "IND Supervisor",
    "Time off Template": "Time Off",
    "Time off Approval Path": "IND Supervisor",
    "Work Week": "Sunday to Saturday",
    "Holiday Calendar": "India Holiday Calendar - General",
    "Payrule": "Custom India Payrule"
  },
  {
    "Deltek Taxable Entity ID": "700",
    "Pay Period Code": "OCWW2",
    "Permissions": {"User" : "End User with Reports"},
    "Schedule Type": "Shift",
    "Timesheet Period": "Semimonthly",
    "Timesheet Template": "India TS Template",
    "Timesheet Template Approval Path": "IND Supervisor",
    "Time off Template": "Time Off",
    "Time off Approval Path": "IND Supervisor",
    "Work Week": "Sunday to Saturday",
    "Holiday Calendar": "India Holiday Calendar - General",
    "Payrule": "Custom India Payrule"
  },
  {
    "Deltek Taxable Entity ID": "700",
    "Pay Period Code": "OCWW15",
    "Permissions": {"User" : "End User with Reports"},
    "Schedule Type": "Shift",
    "Timesheet Period": "Semimonthly",
    "Timesheet Template": "India TS Template",
    "Timesheet Template Approval Path": "IND Supervisor",
    "Time off Template": "Time Off",
    "Time off Approval Path": "IND Supervisor",
    "Work Week": "Sunday to Saturday",
    "Holiday Calendar": "India Holiday Calendar - General",
    "Payrule": "Custom India Payrule"
  },
  {
    "Deltek Taxable Entity ID": "700",
    "Pay Period Code": "OCWE1",
    "Permissions": {"User" : "End User with Reports"},
    "Schedule Type": "Shift",
    "Timesheet Period": "Semimonthly",
    "Timesheet Template": "India TS Template",
    "Timesheet Template Approval Path": "IND Supervisor",
    "Time off Template": "Time Off",
    "Time off Approval Path": "IND Supervisor",
    "Work Week": "Sunday to Saturday",
    "Holiday Calendar": "India Holiday Calendar - General",
    "Payrule": "Custom India Payrule"
  },
  {
    "Deltek Taxable Entity ID": "700",
    "Pay Period Code": "OCWW1",
    "Permissions": {"User" : "End User with Reports"},
    "Schedule Type": "Shift",
    "Timesheet Period": "Semimonthly",
    "Timesheet Template": "India TS Template",
    "Timesheet Template Approval Path": "IND Supervisor",
    "Time off Template": "Time Off",
    "Time off Approval Path": "IND Supervisor",
    "Work Week": "Sunday to Saturday",
    "Holiday Calendar": "India Holiday Calendar - General",
    "Payrule": "Custom India Payrule"
  },
  {
    "Deltek Taxable Entity ID": "700",
    "Pay Period Code": "OCWE2",
    "Permissions": {"User" : "End User with Reports"},
    "Schedule Type": "Shift",
    "Timesheet Period": "Semimonthly",
    "Timesheet Template": "India TS Template",
    "Timesheet Template Approval Path": "IND Supervisor",
    "Time off Template": "Time Off",
    "Time off Approval Path": "IND Supervisor",
    "Work Week": "Sunday to Saturday",
    "Holiday Calendar": "India Holiday Calendar - General",
    "Payrule": "Custom India Payrule"
  }
]
