personal_leave_placeholder_timeoff_types = [
  {
    "location_level_2": "All",
    "location_level_3": "All",
    "company_code": "All",
    "buisness_unit_level_1": "All",
    "functional_segment": "All",
    "functional_sub_segment": "All",
    "buisness_unit_level_2": "All",
    "cost_center": "All",
    "department": "All",
    "reg_temp": "All",
    "full_part": "All",
    "pay_type": "All",
    "activity_type": "All",
    "job_level": "All",
    "std_hrs": "37.5",
    "placeholder_policy": "[IRE] Personal Flex Hours_37.5"
  },
  {
    "location_level_2": "All",
    "location_level_3": "All",
    "company_code": "All",
    "buisness_unit_level_1": "All",
    "functional_segment": "All",
    "functional_sub_segment": "All",
    "buisness_unit_level_2": "All",
    "cost_center": "All",
    "department": "All",
    "reg_temp": "All",
    "full_part": "All",
    "pay_type": "All",
    "activity_type": "All",
    "job_level": "All",
    "std_hrs": "30",
    "placeholder_policy": "[IRE] Personal Flex Hours_30"
  },
  {
    "location_level_2": "All",
    "location_level_3": "All",
    "company_code": "All",
    "buisness_unit_level_1": "All",
    "functional_segment": "All",
    "functional_sub_segment": "All",
    "buisness_unit_level_2": "All",
    "cost_center": "All",
    "department": "All",
    "reg_temp": "All",
    "full_part": "All",
    "pay_type": "All",
    "activity_type": "All",
    "job_level": "All",
    "std_hrs": "25",
    "placeholder_policy": "[IRE] Personal Flex Hours_25"
  },
  {
    "location_level_2": "All",
    "location_level_3": "All",
    "company_code": "All",
    "buisness_unit_level_1": "All",
    "functional_segment": "All",
    "functional_sub_segment": "All",
    "buisness_unit_level_2": "All",
    "cost_center": "All",
    "department": "All",
    "reg_temp": "All",
    "full_part": "All",
    "pay_type": "All",
    "activity_type": "All",
    "job_level": "All",
    "std_hrs": "24",
    "placeholder_policy": "[IRE] Personal Flex Hours_24"
  },
  {
    "location_level_2": "All",
    "location_level_3": "All",
    "company_code": "All",
    "buisness_unit_level_1": "All",
    "functional_segment": "All",
    "functional_sub_segment": "All",
    "buisness_unit_level_2": "All",
    "cost_center": "All",
    "department": "All",
    "reg_temp": "All",
    "full_part": "All",
    "pay_type": "All",
    "activity_type": "All",
    "job_level": "All",
    "std_hrs": "21",
    "placeholder_policy": "[IRE] Personal Flex Hours_21"
  },
  {
    "location_level_2": "All",
    "location_level_3": "All",
    "company_code": "All",
    "buisness_unit_level_1": "All",
    "functional_segment": "All",
    "functional_sub_segment": "All",
    "buisness_unit_level_2": "All",
    "cost_center": "All",
    "department": "All",
    "reg_temp": "All",
    "full_part": "All",
    "pay_type": "All",
    "activity_type": "All",
    "job_level": "All",
    "std_hrs": "16",
    "placeholder_policy": "[IRE] Personal Flex Hours_16"
  },
  {
    "location_level_2": "All",
    "location_level_3": "All",
    "company_code": "All",
    "buisness_unit_level_1": "All",
    "functional_segment": "All",
    "functional_sub_segment": "All",
    "buisness_unit_level_2": "All",
    "cost_center": "All",
    "department": "All",
    "reg_temp": "All",
    "full_part": "All",
    "pay_type": "All",
    "activity_type": "All",
    "job_level": "All",
    "std_hrs": "20",
    "placeholder_policy": "[IRE] Personal Flex Hours_20"
  },
  {
    "location_level_2": "All",
    "location_level_3": "All",
    "company_code": "All",
    "buisness_unit_level_1": "All",
    "functional_segment": "All",
    "functional_sub_segment": "All",
    "buisness_unit_level_2": "All",
    "cost_center": "All",
    "department": "All",
    "reg_temp": "All",
    "full_part": "All",
    "pay_type": "All",
    "activity_type": "All",
    "job_level": "All",
    "std_hrs": "22.5",
    "placeholder_policy": "[IRE] Personal Flex Hours_22.5"
  },
  {
    "location_level_2": "All",
    "location_level_3": "All",
    "company_code": "All",
    "buisness_unit_level_1": "All",
    "functional_segment": "All",
    "functional_sub_segment": "All",
    "buisness_unit_level_2": "All",
    "cost_center": "All",
    "department": "All",
    "reg_temp": "All",
    "full_part": "All",
    "pay_type": "All",
    "activity_type": "All",
    "job_level": "All",
    "std_hrs": "32",
    "placeholder_policy": "[IRE] Personal Flex Hours_32"
  }
]
