"""
CRL Ireland User Import Mapper

This mapper defines all business rules for Ireland employee configurations
based on Location, Reg/Temp, Full/Part, and Pay Type combinations
"""


user_import_mapper = [
  {
    "location_level_1": "IRL",
    "location_level_2": "All",
    "location_level_3": "Ballina",
    "company_code": "5100",
    "business_segment_common": "All",
    "functional_segment": "All",
    "functional_sub_segment": "All",
    "business_unit": "All",
    "cost_center": "All",
    "department": "All",
    "pay_type": "Salaried",
    "reg_temp": "Regular",
    "full_part": "Part-Time",
    "activity_type": "All",
    "job_level": "All",
    "employee_type": "IRE_Salaried_Reg_PT",
    "punch_policy": "IRE_Ballina_Salaried Punch",
    "timesheet_template": "IRE_Salaried",
    "timesheet_approval_path": "Supervisor",
    "timesheet_period": "IRE - Weekly starting on Saturday",
    "time_off_template": "Time Off",
    "time_off_approver": "Supervisor",
    "timezone": "(UTC+0:00) GMT Standard Time",
    "work_week": "Saturday to Friday",
    "holiday_calendar": "IRE_Ballina_Holiday Calendar",
    "schedule_type": "Office Schedule",
    "schedule_policy": "Default Shift Schedule Policy",
    "payrule_name": "IRE_Salaried_PT"
  },
  {
    "location_level_1": "IRL",
    "location_level_2": "All",
    "location_level_3": "Ballina",
    "company_code": "5100",
    "business_segment_common": "All",
    "functional_segment": "All",
    "functional_sub_segment": "All",
    "business_unit": "All",
    "cost_center": "All",
    "department": "All",
    "pay_type": "Salaried",
    "reg_temp": "Regular",
    "full_part": "Full-Time",
    "activity_type": "All",
    "job_level": "All",
    "employee_type": "IRE_Salaried_Reg_FT",
    "punch_policy": "IRE_Ballina_Salaried Punch",
    "timesheet_template": "IRE_Salaried",
    "timesheet_approval_path": "Supervisor",
    "timesheet_period": "IRE - Weekly starting on Saturday",
    "time_off_template": "Time Off",
    "time_off_approver": "Supervisor",
    "timezone": "(UTC+0:00) GMT Standard Time",
    "work_week": "Saturday to Friday",
    "holiday_calendar": "IRE_Ballina_Holiday Calendar",
    "schedule_type": "Office Schedule",
    "schedule_policy": "Default Shift Schedule Policy",
    "payrule_name": "IRE_Salaried_FT"
  },
  {
    "location_level_1": "IRL",
    "location_level_2": "All",
    "location_level_3": "Ballina",
    "company_code": "5100",
    "business_segment_common": "All",
    "functional_segment": "All",
    "functional_sub_segment": "All",
    "business_unit": "All",
    "cost_center": "All",
    "department": "All",
    "pay_type": "Salaried",
    "reg_temp": "Temporary",
    "full_part": "Part-Time",
    "activity_type": "All",
    "job_level": "All",
    "employee_type": "IRE_Salaried_Temp_PT",
    "punch_policy": "IRE_Ballina_Salaried Punch",
    "timesheet_template": "IRE_Salaried",
    "timesheet_approval_path": "Supervisor",
    "timesheet_period": "IRE - Weekly starting on Saturday",
    "time_off_template": "Time Off",
    "time_off_approver": "Supervisor",
    "timezone": "(UTC+0:00) GMT Standard Time",
    "work_week": "Saturday to Friday",
    "holiday_calendar": "IRE_Ballina_Holiday Calendar",
    "schedule_type": "Office Schedule",
    "schedule_policy": "Default Shift Schedule Policy",
    "payrule_name": "IRE_Salaried_PT"
  },
  {
    "location_level_1": "IRL",
    "location_level_2": "All",
    "location_level_3": "Ballina",
    "company_code": "5100",
    "business_segment_common": "All",
    "functional_segment": "All",
    "functional_sub_segment": "All",
    "business_unit": "All",
    "cost_center": "All",
    "department": "All",
    "pay_type": "Salaried",
    "reg_temp": "Temporary",
    "full_part": "Full-Time",
    "activity_type": "All",
    "job_level": "All",
    "employee_type": "IRE_Salaried_Temp_FT",
    "punch_policy": "IRE_Ballina_Salaried Punch",
    "timesheet_template": "IRE_Salaried",
    "timesheet_approval_path": "Supervisor",
    "timesheet_period": "IRE - Weekly starting on Saturday",
    "time_off_template": "Time Off",
    "time_off_approver": "Supervisor",
    "timezone": "(UTC+0:00) GMT Standard Time",
    "work_week": "Saturday to Friday",
    "holiday_calendar": "IRE_Ballina_Holiday Calendar",
    "schedule_type": "Office Schedule",
    "schedule_policy": "Default Shift Schedule Policy",
    "payrule_name": "IRE_Salaried_FT"
  },
  {
    "location_level_1": "IRL",
    "location_level_2": "All",
    "location_level_3": "Ballina",
    "company_code": "5100",
    "business_segment_common": "All",
    "functional_segment": "All",
    "functional_sub_segment": "All",
    "business_unit": "All",
    "cost_center": "All",
    "department": "All",
    "pay_type": "Hourly",
    "reg_temp": "Regular",
    "full_part": "Part-Time",
    "activity_type": "All",
    "job_level": "All",
    "employee_type": "IRE_Hourly_Reg_PT",
    "punch_policy": "IRE_Ballina_Hourly Punch",
    "timesheet_template": "IRE_Hourly",
    "timesheet_approval_path": "Supervisor",
    "timesheet_period": "IRE - Weekly starting on Saturday",
    "time_off_template": "Time Off",
    "time_off_approver": "Supervisor",
    "timezone": "(UTC+0:00) GMT Standard Time",
    "work_week": "Saturday to Friday",
    "holiday_calendar": "IRE_Ballina_Holiday Calendar",
    "schedule_type": "Office Schedule",
    "schedule_policy": "Default Shift Schedule Policy",
    "payrule_name": "IRE_Hourly_PT"
  },
  {
    "location_level_1": "IRL",
    "location_level_2": "All",
    "location_level_3": "Ballina",
    "company_code": "5100",
    "business_segment_common": "All",
    "functional_segment": "All",
    "functional_sub_segment": "All",
    "business_unit": "All",
    "cost_center": "All",
    "department": "All",
    "pay_type": "Hourly",
    "reg_temp": "Regular",
    "full_part": "Full-Time",
    "activity_type": "All",
    "job_level": "All",
    "employee_type": "IRE_Hourly_Reg_FT",
    "punch_policy": "IRE_Ballina_Hourly Punch",
    "timesheet_template": "IRE_Hourly",
    "timesheet_approval_path": "Supervisor",
    "timesheet_period": "IRE - Weekly starting on Saturday",
    "time_off_template": "Time Off",
    "time_off_approver": "Supervisor",
    "timezone": "(UTC+0:00) GMT Standard Time",
    "work_week": "Saturday to Friday",
    "holiday_calendar": "IRE_Ballina_Holiday Calendar",
    "schedule_type": "Office Schedule",
    "schedule_policy": "Default Shift Schedule Policy",
    "payrule_name": "IRE_Hourly_FT"
  },
  {
    "location_level_1": "IRL",
    "location_level_2": "All",
    "location_level_3": "Ballina",
    "company_code": "5100",
    "business_segment_common": "All",
    "functional_segment": "All",
    "functional_sub_segment": "All",
    "business_unit": "All",
    "cost_center": "All",
    "department": "All",
    "pay_type": "Hourly",
    "reg_temp": "Temporary",
    "full_part": "Part-Time",
    "activity_type": "All",
    "job_level": "All",
    "employee_type": "IRE_Hourly_Temp_PT",
    "punch_policy": "IRE_Ballina_Hourly Punch",
    "timesheet_template": "IRE_Hourly",
    "timesheet_approval_path": "Supervisor",
    "timesheet_period": "IRE - Weekly starting on Saturday",
    "time_off_template": "Time Off",
    "time_off_approver": "Supervisor",
    "timezone": "(UTC+0:00) GMT Standard Time",
    "work_week": "Saturday to Friday",
    "holiday_calendar": "IRE_Ballina_Holiday Calendar",
    "schedule_type": "Office Schedule",
    "schedule_policy": "Default Shift Schedule Policy",
    "payrule_name": "IRE_Hourly_PT"
  },
  {
    "location_level_1": "IRL",
    "location_level_2": "All",
    "location_level_3": "Ballina",
    "company_code": "5100",
    "business_segment_common": "All",
    "functional_segment": "All",
    "functional_sub_segment": "All",
    "business_unit": "All",
    "cost_center": "All",
    "department": "All",
    "pay_type": "Hourly",
    "reg_temp": "Temporary",
    "full_part": "Full-Time",
    "activity_type": "All",
    "job_level": "All",
    "employee_type": "IRE_Hourly_Temp_FT",
    "punch_policy": "IRE_Ballina_Hourly Punch",
    "timesheet_template": "IRE_Hourly",
    "timesheet_approval_path": "Supervisor",
    "timesheet_period": "IRE - Weekly starting on Saturday",
    "time_off_template": "Time Off",
    "time_off_approver": "Supervisor",
    "timezone": "(UTC+0:00) GMT Standard Time",
    "work_week": "Saturday to Friday",
    "holiday_calendar": "IRE_Ballina_Holiday Calendar",
    "schedule_type": "Office Schedule",
    "schedule_policy": "Default Shift Schedule Policy",
    "payrule_name": "IRE_Hourly_FT"
  },
  {
    "location_level_1": "IRL",
    "location_level_2": "All",
    "location_level_3": "Ballina",
    "company_code": "5100",
    "business_segment_common": "All",
    "functional_segment": "All",
    "functional_sub_segment": "All",
    "business_unit": "All",
    "cost_center": "All",
    "department": "All",
    "pay_type": "Exception Hourly",
    "reg_temp": "Regular",
    "full_part": "Part-Time",
    "activity_type": "All",
    "job_level": "All",
    "employee_type": "IRE_Salaried OT Eligible_Reg_PT",
    "punch_policy": "IRE_Ballina_Salaried OT Eligible Punch",
    "timesheet_template": "IRE_Salaried OT Eligible",
    "timesheet_approval_path": "Supervisor",
    "timesheet_period": "IRE - Weekly starting on Saturday",
    "time_off_template": "Time Off",
    "time_off_approver": "Supervisor",
    "timezone": "(UTC+0:00) GMT Standard Time",
    "work_week": "Saturday to Friday",
    "holiday_calendar": "IRE_Ballina_Holiday Calendar",
    "schedule_type": "Office Schedule",
    "schedule_policy": "Default Shift Schedule Policy",
    "payrule_name": "IRE_Salaried OT Eligible_PT"
  },
  {
    "location_level_1": "IRL",
    "location_level_2": "All",
    "location_level_3": "Ballina",
    "company_code": "5100",
    "business_segment_common": "All",
    "functional_segment": "All",
    "functional_sub_segment": "All",
    "business_unit": "All",
    "cost_center": "All",
    "department": "All",
    "pay_type": "Exception Hourly",
    "reg_temp": "Regular",
    "full_part": "Full-Time",
    "activity_type": "All",
    "job_level": "All",
    "employee_type": "IRE_Salaried OT Eligible_Reg_FT",
    "punch_policy": "IRE_Ballina_Salaried OT Eligible Punch",
    "timesheet_template": "IRE_Salaried OT Eligible",
    "timesheet_approval_path": "Supervisor",
    "timesheet_period": "IRE - Weekly starting on Saturday",
    "time_off_template": "Time Off",
    "time_off_approver": "Supervisor",
    "timezone": "(UTC+0:00) GMT Standard Time",
    "work_week": "Saturday to Friday",
    "holiday_calendar": "IRE_Ballina_Holiday Calendar",
    "schedule_type": "Office Schedule",
    "schedule_policy": "Default Shift Schedule Policy",
    "payrule_name": "IRE_Salaried OT Eligible_FT"
  },
  {
    "location_level_1": "IRL",
    "location_level_2": "All",
    "location_level_3": "Ballina",
    "company_code": "5100",
    "business_segment_common": "All",
    "functional_segment": "All",
    "functional_sub_segment": "All",
    "business_unit": "All",
    "cost_center": "All",
    "department": "All",
    "pay_type": "Exception Hourly",
    "reg_temp": "Temporary",
    "full_part": "Part-Time",
    "activity_type": "All",
    "job_level": "All",
    "employee_type": "IRE_Salaried OT Eligible_Temp_PT",
    "punch_policy": "IRE_Ballina_Salaried OT Eligible Punch",
    "timesheet_template": "IRE_Salaried OT Eligible",
    "timesheet_approval_path": "Supervisor",
    "timesheet_period": "IRE - Weekly starting on Saturday",
    "time_off_template": "Time Off",
    "time_off_approver": "Supervisor",
    "timezone": "(UTC+0:00) GMT Standard Time",
    "work_week": "Saturday to Friday",
    "holiday_calendar": "IRE_Ballina_Holiday Calendar",
    "schedule_type": "Office Schedule",
    "schedule_policy": "Default Shift Schedule Policy",
    "payrule_name": "IRE_Salaried OT Eligible_PT"
  },
  {
    "location_level_1": "IRL",
    "location_level_2": "All",
    "location_level_3": "Ballina",
    "company_code": "5100",
    "business_segment_common": "All",
    "functional_segment": "All",
    "functional_sub_segment": "All",
    "business_unit": "All",
    "cost_center": "All",
    "department": "All",
    "pay_type": "Exception Hourly",
    "reg_temp": "Temporary",
    "full_part": "Full-Time",
    "activity_type": "All",
    "job_level": "All",
    "employee_type": "IRE_Salaried OT Eligible_Temp_FT",
    "punch_policy": "IRE_Ballina_Salaried OT Eligible Punch",
    "timesheet_template": "IRE_Salaried OT Eligible",
    "timesheet_approval_path": "Supervisor",
    "timesheet_period": "IRE - Weekly starting on Saturday",
    "time_off_template": "Time Off",
    "time_off_approver": "Supervisor",
    "timezone": "(UTC+0:00) GMT Standard Time",
    "work_week": "Saturday to Friday",
    "holiday_calendar": "IRE_Ballina_Holiday Calendar",
    "schedule_type": "Office Schedule",
    "schedule_policy": "Default Shift Schedule Policy",
    "payrule_name": "IRE_Salaried OT Eligible_FT"
  },
  {
    "location_level_1": "IRL",
    "location_level_2": "All",
    "location_level_3": "Dublin",
    "company_code": "5420",
    "business_segment_common": "All",
    "functional_segment": "All",
    "functional_sub_segment": "All",
    "business_unit": "All",
    "cost_center": "All",
    "department": "All",
    "pay_type": "Salaried",
    "reg_temp": "Regular",
    "full_part": "Part-Time",
    "activity_type": "All",
    "job_level": "All",
    "employee_type": "IRE_Salaried_Reg_PT",
    "punch_policy": "IRE_Dublin_Salaried Punch",
    "timesheet_template": "IRE_Salaried",
    "timesheet_approval_path": "Supervisor",
    "timesheet_period": "IRE - Weekly starting on Saturday",
    "time_off_template": "Time Off",
    "time_off_approver": "Supervisor",
    "timezone": "(UTC+0:00) GMT Standard Time",
    "work_week": "Saturday to Friday",
    "holiday_calendar": "IRE_Dublin_Holiday Calendar",
    "schedule_type": "Office Schedule",
    "schedule_policy": "Default Shift Schedule Policy",
    "payrule_name": "IRE_Salaried_PT"
  },
  {
    "location_level_1": "IRL",
    "location_level_2": "All",
    "location_level_3": "Dublin",
    "company_code": "5420",
    "business_segment_common": "All",
    "functional_segment": "All",
    "functional_sub_segment": "All",
    "business_unit": "All",
    "cost_center": "All",
    "department": "All",
    "pay_type": "Salaried",
    "reg_temp": "Regular",
    "full_part": "Full-Time",
    "activity_type": "All",
    "job_level": "All",
    "employee_type": "IRE_Salaried_Reg_FT",
    "punch_policy": "IRE_Dublin_Salaried Punch",
    "timesheet_template": "IRE_Salaried",
    "timesheet_approval_path": "Supervisor",
    "timesheet_period": "IRE - Weekly starting on Saturday",
    "time_off_template": "Time Off",
    "time_off_approver": "Supervisor",
    "timezone": "(UTC+0:00) GMT Standard Time",
    "work_week": "Saturday to Friday",
    "holiday_calendar": "IRE_Dublin_Holiday Calendar",
    "schedule_type": "Office Schedule",
    "schedule_policy": "Default Shift Schedule Policy",
    "payrule_name": "IRE_Salaried_FT"
  },
  {
    "location_level_1": "IRL",
    "location_level_2": "All",
    "location_level_3": "Dublin",
    "company_code": "5420",
    "business_segment_common": "All",
    "functional_segment": "All",
    "functional_sub_segment": "All",
    "business_unit": "All",
    "cost_center": "All",
    "department": "All",
    "pay_type": "Salaried",
    "reg_temp": "Temporary",
    "full_part": "Part-Time",
    "activity_type": "All",
    "job_level": "All",
    "employee_type": "IRE_Salaried_Temp_PT",
    "punch_policy": "IRE_Dublin_Salaried Punch",
    "timesheet_template": "IRE_Salaried",
    "timesheet_approval_path": "Supervisor",
    "timesheet_period": "IRE - Weekly starting on Saturday",
    "time_off_template": "Time Off",
    "time_off_approver": "Supervisor",
    "timezone": "(UTC+0:00) GMT Standard Time",
    "work_week": "Saturday to Friday",
    "holiday_calendar": "IRE_Dublin_Holiday Calendar",
    "schedule_type": "Office Schedule",
    "schedule_policy": "Default Shift Schedule Policy",
    "payrule_name": "IRE_Salaried_PT"
  },
  {
    "location_level_1": "IRL",
    "location_level_2": "All",
    "location_level_3": "Dublin",
    "company_code": "5420",
    "business_segment_common": "All",
    "functional_segment": "All",
    "functional_sub_segment": "All",
    "business_unit": "All",
    "cost_center": "All",
    "department": "All",
    "pay_type": "Salaried",
    "reg_temp": "Temporary",
    "full_part": "Full-Time",
    "activity_type": "All",
    "job_level": "All",
    "employee_type": "IRE_Salaried_Temp_FT",
    "punch_policy": "IRE_Dublin_Salaried Punch",
    "timesheet_template": "IRE_Salaried",
    "timesheet_approval_path": "Supervisor",
    "timesheet_period": "IRE - Weekly starting on Saturday",
    "time_off_template": "Time Off",
    "time_off_approver": "Supervisor",
    "timezone": "(UTC+0:00) GMT Standard Time",
    "work_week": "Saturday to Friday",
    "holiday_calendar": "IRE_Dublin_Holiday Calendar",
    "schedule_type": "Office Schedule",
    "schedule_policy": "Default Shift Schedule Policy",
    "payrule_name": "IRE_Salaried_FT"
  },
  {
    "location_level_1": "IRL",
    "location_level_2": "All",
    "location_level_3": "Dublin",
    "company_code": "5420",
    "business_segment_common": "All",
    "functional_segment": "All",
    "functional_sub_segment": "All",
    "business_unit": "All",
    "cost_center": "All",
    "department": "All",
    "pay_type": "Hourly",
    "reg_temp": "Regular",
    "full_part": "Part-Time",
    "activity_type": "All",
    "job_level": "All",
    "employee_type": "IRE_Hourly_Reg_PT",
    "punch_policy": "IRE_Dublin_Hourly Punch",
    "timesheet_template": "IRE_Hourly",
    "timesheet_approval_path": "Supervisor",
    "timesheet_period": "IRE - Weekly starting on Saturday",
    "time_off_template": "Time Off",
    "time_off_approver": "Supervisor",
    "timezone": "(UTC+0:00) GMT Standard Time",
    "work_week": "Saturday to Friday",
    "holiday_calendar": "IRE_Dublin_Holiday Calendar",
    "schedule_type": "Office Schedule",
    "schedule_policy": "Default Shift Schedule Policy",
    "payrule_name": "IRE_Hourly_PT"
  },
  {
    "location_level_1": "IRL",
    "location_level_2": "All",
    "location_level_3": "Dublin",
    "company_code": "5420",
    "business_segment_common": "All",
    "functional_segment": "All",
    "functional_sub_segment": "All",
    "business_unit": "All",
    "cost_center": "All",
    "department": "All",
    "pay_type": "Hourly",
    "reg_temp": "Regular",
    "full_part": "Full-Time",
    "activity_type": "All",
    "job_level": "All",
    "employee_type": "IRE_Hourly_Reg_FT",
    "punch_policy": "IRE_Dublin_Hourly Punch",
    "timesheet_template": "IRE_Hourly",
    "timesheet_approval_path": "Supervisor",
    "timesheet_period": "IRE - Weekly starting on Saturday",
    "time_off_template": "Time Off",
    "time_off_approver": "Supervisor",
    "timezone": "(UTC+0:00) GMT Standard Time",
    "work_week": "Saturday to Friday",
    "holiday_calendar": "IRE_Dublin_Holiday Calendar",
    "schedule_type": "Office Schedule",
    "schedule_policy": "Default Shift Schedule Policy",
    "payrule_name": "IRE_Hourly_FT"
  },
  {
    "location_level_1": "IRL",
    "location_level_2": "All",
    "location_level_3": "Dublin",
    "company_code": "5420",
    "business_segment_common": "All",
    "functional_segment": "All",
    "functional_sub_segment": "All",
    "business_unit": "All",
    "cost_center": "All",
    "department": "All",
    "pay_type": "Hourly",
    "reg_temp": "Temporary",
    "full_part": "Part-Time",
    "activity_type": "All",
    "job_level": "All",
    "employee_type": "IRE_Hourly_Temp_PT",
    "punch_policy": "IRE_Dublin_Hourly Punch",
    "timesheet_template": "IRE_Hourly",
    "timesheet_approval_path": "Supervisor",
    "timesheet_period": "IRE - Weekly starting on Saturday",
    "time_off_template": "Time Off",
    "time_off_approver": "Supervisor",
    "timezone": "(UTC+0:00) GMT Standard Time",
    "work_week": "Saturday to Friday",
    "holiday_calendar": "IRE_Dublin_Holiday Calendar",
    "schedule_type": "Office Schedule",
    "schedule_policy": "Default Shift Schedule Policy",
    "payrule_name": "IRE_Hourly_PT"
  },
  {
    "location_level_1": "IRL",
    "location_level_2": "All",
    "location_level_3": "Dublin",
    "company_code": "5420",
    "business_segment_common": "All",
    "functional_segment": "All",
    "functional_sub_segment": "All",
    "business_unit": "All",
    "cost_center": "All",
    "department": "All",
    "pay_type": "Hourly",
    "reg_temp": "Temporary",
    "full_part": "Full-Time",
    "activity_type": "All",
    "job_level": "All",
    "employee_type": "IRE_Hourly_Temp_FT",
    "punch_policy": "IRE_Dublin_Hourly Punch",
    "timesheet_template": "IRE_Hourly",
    "timesheet_approval_path": "Supervisor",
    "timesheet_period": "IRE - Weekly starting on Saturday",
    "time_off_template": "Time Off",
    "time_off_approver": "Supervisor",
    "timezone": "(UTC+0:00) GMT Standard Time",
    "work_week": "Saturday to Friday",
    "holiday_calendar": "IRE_Dublin_Holiday Calendar",
    "schedule_type": "Office Schedule",
    "schedule_policy": "Default Shift Schedule Policy",
    "payrule_name": "IRE_Hourly_FT"
  },
  {
    "location_level_1": "IRL",
    "location_level_2": "All",
    "location_level_3": "Dublin",
    "company_code": "5420",
    "business_segment_common": "All",
    "functional_segment": "All",
    "functional_sub_segment": "All",
    "business_unit": "All",
    "cost_center": "All",
    "department": "All",
    "pay_type": "Exception Hourly",
    "reg_temp": "Regular",
    "full_part": "Part-Time",
    "activity_type": "All",
    "job_level": "All",
    "employee_type": "IRE_Salaried OT Eligible_Reg_PT",
    "punch_policy": "IRE_Dublin_Salaried OT Eligible Punch",
    "timesheet_template": "IRE_Salaried OT Eligible",
    "timesheet_approval_path": "Supervisor",
    "timesheet_period": "IRE - Weekly starting on Saturday",
    "time_off_template": "Time Off",
    "time_off_approver": "Supervisor",
    "timezone": "(UTC+0:00) GMT Standard Time",
    "work_week": "Saturday to Friday",
    "holiday_calendar": "IRE_Dublin_Holiday Calendar",
    "schedule_type": "Office Schedule",
    "schedule_policy": "Default Shift Schedule Policy",
    "payrule_name": "IRE_Salaried OT Eligible_PT"
  },
  {
    "location_level_1": "IRL",
    "location_level_2": "All",
    "location_level_3": "Dublin",
    "company_code": "5420",
    "business_segment_common": "All",
    "functional_segment": "All",
    "functional_sub_segment": "All",
    "business_unit": "All",
    "cost_center": "All",
    "department": "All",
    "pay_type": "Exception Hourly",
    "reg_temp": "Regular",
    "full_part": "Full-Time",
    "activity_type": "All",
    "job_level": "All",
    "employee_type": "IRE_Salaried OT Eligible_Reg_FT",
    "punch_policy": "IRE_Dublin_Salaried OT Eligible Punch",
    "timesheet_template": "IRE_Salaried OT Eligible",
    "timesheet_approval_path": "Supervisor",
    "timesheet_period": "IRE - Weekly starting on Saturday",
    "time_off_template": "Time Off",
    "time_off_approver": "Supervisor",
    "timezone": "(UTC+0:00) GMT Standard Time",
    "work_week": "Saturday to Friday",
    "holiday_calendar": "IRE_Dublin_Holiday Calendar",
    "schedule_type": "Office Schedule",
    "schedule_policy": "Default Shift Schedule Policy",
    "payrule_name": "IRE_Salaried OT Eligible_FT"
  },
  {
    "location_level_1": "IRL",
    "location_level_2": "All",
    "location_level_3": "Dublin",
    "company_code": "5420",
    "business_segment_common": "All",
    "functional_segment": "All",
    "functional_sub_segment": "All",
    "business_unit": "All",
    "cost_center": "All",
    "department": "All",
    "pay_type": "Exception Hourly",
    "reg_temp": "Temporary",
    "full_part": "Part-Time",
    "activity_type": "All",
    "job_level": "All",
    "employee_type": "IRE_Salaried OT Eligible_Temp_PT",
    "punch_policy": "IRE_Dublin_Salaried OT Eligible Punch",
    "timesheet_template": "IRE_Salaried OT Eligible",
    "timesheet_approval_path": "Supervisor",
    "timesheet_period": "IRE - Weekly starting on Saturday",
    "time_off_template": "Time Off",
    "time_off_approver": "Supervisor",
    "timezone": "(UTC+0:00) GMT Standard Time",
    "work_week": "Saturday to Friday",
    "holiday_calendar": "IRE_Dublin_Holiday Calendar",
    "schedule_type": "Office Schedule",
    "schedule_policy": "Default Shift Schedule Policy",
    "payrule_name": "IRE_Salaried OT Eligible_PT"
  },
  {
    "location_level_1": "IRL",
    "location_level_2": "All",
    "location_level_3": "Dublin",
    "company_code": "5420",
    "business_segment_common": "All",
    "functional_segment": "All",
    "functional_sub_segment": "All",
    "business_unit": "All",
    "cost_center": "All",
    "department": "All",
    "pay_type": "Exception Hourly",
    "reg_temp": "Temporary",
    "full_part": "Full-Time",
    "activity_type": "All",
    "job_level": "All",
    "employee_type": "IRE_Salaried OT Eligible_Temp_FT",
    "punch_policy": "IRE_Dublin_Salaried OT Eligible Punch",
    "timesheet_template": "IRE_Salaried OT Eligible",
    "timesheet_approval_path": "Supervisor",
    "timesheet_period": "IRE - Weekly starting on Saturday",
    "time_off_template": "Time Off",
    "time_off_approver": "Supervisor",
    "timezone": "(UTC+0:00) GMT Standard Time",
    "work_week": "Saturday to Friday",
    "holiday_calendar": "IRE_Dublin_Holiday Calendar",
    "schedule_type": "Office Schedule",
    "schedule_policy": "Default Shift Schedule Policy",
    "payrule_name": "IRE_Salaried OT Eligible_FT"
  }
]
