# pylint:disable=multiple-statements
region = 'us-east-1'
environment = 'production'
instance = "MerrickandCompany"
company_key = 'MerrickandCompany'
replicon_conn_id = f'polaris_{company_key}'
deltek_cospoint_conn_id = f'deltek_costpoint_{company_key}'
last_run_date_var_name = f'{company_key}_deltek_costpoint_inital_sync_last_run_date'
get_data_in_chunk_var_name = f'{company_key}_deltek_costpoint_inital_sync_get_data_in_chunk'
tenant_email = "MPTeamReplicon@deltek.com,AvnishKhurana@deltek.com"
internal_email = "MPTeamReplicon@deltek.com"
time_zone = 'America/Denver'
execution_timeout_days = 14
child_dag_max_active_runs = 2
schedule_interval = 36000
can_run_batch_task_var_name = f'Cospoint_inital_import_can_run_batch_task_{instance}'
run_servicecenter_sync_var_name = f'Cospoint_inital_import_run_servicecenter_sync_{instance}'
run_labor_location_sync_var_name = f'Cospoint_inital_import_run_labor_location_sync_{instance}'
run_division_sync_var_name = f'Cospoint_inital_import_run_division_sync_{instance}'
run_costcenter_sync_var_name = f'Cospoint_inital_import_run_costcenter_sync_{instance}'
run_dept_glc_sync_var_name = f'Cospoint_inital_import_run_dept_glc_sync_{instance}'
costpoint_date_format = '%Y-%m-%dT%H:%M:%S'
glc = 'General labour categories'
paytype = 'Pay Type'
taxableentity = 'Taxable Entity'
empclass = 'Employee Class'
flsaexempt = 'FLSA Exempt'
flsaexempt_tags = [{"name": "Exempt", "code": "Y"},
                   {"name": "Non- Exempt", "code": "N"}]
employee_type_options = [{"name": "Part Time", "code": "P"}, {
    "name": "Regular", "code": "R"}, {"name": "Temporary", "code": "T"}]
plc = 'Project Labor Category'
deltek_cospoint_company_ids = ['100','200','500','700']
proj_purchase_order_no = 'Purchase Order No'
proj_opportunity_id = 'Opportunity ID'
proj_project_classification = 'Project Classification'
proj_user_company = 'Company'
generation_months_in_advance = 1
root_deperment = 'Company'
oef_idtype = "Id Type"
project_task_budget_type_oef = "Budget Type"
idtype_tags = [{"name": "Employee", "code": "Employee"},
               {"name": "Contractor Employee", "code": "Contractor Employee"}]
budgettype_tags = [{"name": "Bud", "code": "Bud"}]
date_time_format = "%Y-%m-%dT%H:%M:%S"
costpoint_timeoff_name = "Time Off"
use_project_id_for_timeoff_types = "false"
batch_size_var_name = f'{company_key}_deltek_costpoint_batch_size'
group_hierarchy_sync = "FLAT" # FLAT/HIERARCHICAL
