# pylint:disable=multiple-statements
region = 'us-east-1'
environment = 'pre-production'
instance = "polarisdeltekcp2"
company_key = 'polarisdeltekcp2'
replicon_conn_id = f'replicon_{company_key}'
deltek_cospoint_conn_id = f'deltek_costpoint_{company_key}'
tenant_email = "kaliya.perumal@replicon.com,nik.hristov@replicon.com"
internal_email = "MPTeamReplicon@deltek.com"
time_zone = 'US/Eastern'
execution_timeout_days = 14
child_dag_max_active_runs = 2
can_run_batch_task_var_name = f'Cospoint_inital_import_can_run_batch_task_{instance}'
costpoint_date_format = '%Y-%m-%dT%H:%M:%S'
polaris_date_format = '%Y-%m-%dT%H:%M:%S.%fZ'
deltek_cospoint_company_ids = ['1']
processing_file_directory = "CP"
sftp_conn_id = "polaris_sfp"
lookup_allocation_timestamp_var = f'deltek_costpoint_project_budget_{instance}_lookup_allocation_timestamp'
lookup_allocation_timestamp_hours = 6
cp_polaris_webhook_secret_project = "cp_rep_webhook_secret_project_polarisdeltekcp2"
cp_project_polaris_teamMember_allocation = "cp_project_polaris_teamMember_allocation_polarisdeltekcp2"
cp_polaris_webhook_secret_task = "cp_rep_webhook_secret_task_polarisdeltekcp2"
master_dag_interval = 120
project_task_budget_type_oef = "Budget Type"
