region = 'eu-central-1'
environment = 'pre-production'
company_key = 'Statestreetafmig'
user_report_name = 'User Report - For Replicon Integrations'
execution_timeout_days = 14
max_active_runs_child = 1
max_active_runs_master = 1
max_active_runs_childs = 5
master_dag_interval = 30
countsize = 1
