region = 'us-east-1'
environment = 'pre-production'
instance = "capefoxcorporationsb"
company_key = 'capefoxcorporationsb'
replicon_conn_id = f'capefoxcorporationsb_replicon_integration'
deltek_cospoint_conn_id = f'capefoxcorporationsb_deltek_costpoint_32764'
last_run_date_var_name = f'{company_key}_deltek_costpoint_project_sync_last_run_date'
get_data_in_chunk_var_name = f'{company_key}_deltek_costpoint_project_sync_get_data_in_chunk'
time_zone = 'US/Eastern'
execution_timeout_days = 14
child_dag_max_active_runs = 5
date_time_format = "%Y-%m-%dT%H:%M:%S"
can_run_batch_task_var_name = f'{company_key}_deltek_costpoint_project_sync_run_batch_task'
schedule_interval = "*/1 * * * *"
master_dag_interval = 30
tenant_email = "MPTeamReplicon@deltek.com"
internal_email = "MPTeamReplicon@deltek.com"
project_manager_permission_name = 'Project Manager'
deltek_cospoint_company_ids = ['1']
proj_purchase_order_no = 'Purchase Order No'
proj_opportunity_id = 'Opportunity ID'
proj_project_classification = 'Project Classification'
proj_user_company = 'Company'
log_generation_dag_interval = '0 * * * *'
dag_max_active_tasks = 2
lookup_log_timestamp_var = f'deltek_costpoint_project_import_{instance}_lookup_log_timestamp'
lookup_log_timestamp_hours = 1
alert_email = "MPTeamReplicon@deltek.com"
child_dag_log_generation_max_active_runs = 20
workforce_change_detection_enabled = False
