# pylint: disable=wildcard-import unused-wildcard-import
from dxctechnology.ftp_time_export_pta_v4.config import *
from dxctechnology.ftp_time_export_pta_v4.mappers.timeoff_types_mapper import timeoff_types_to_exclude
from dxctechnology.ftp_time_export_pta_v4.mappers.timetype_standby_units_mapper import timetype_standby_units_to_exclude

instance = "trial"
execution_timeout_days = 14

timeoff_types_to_exclude_mapper = timeoff_types_to_exclude
timetype_standby_units_to_exclude_mapper = timetype_standby_units_to_exclude

master_dag_id = f'dxctechnology_time_export_ftp_pta_v4_master_{instance}'
process_unackn_child_dag_id = f'dxctechnology_time_export_ftp_pta_v4_process_all_unackn_export_child_{instance}'

disabled=True
