role_approval_path_mapper = {
    "timesheet_approval_path": 'Netherlands Approval',
    "timeoff_approval_path": "Netherlands Approval",
    "l1_manager": "L1 Manager (NL)",
    "end_user_manager": "End User (Managers)",
    "project_manager": "NL- Project Manager",
    "hr_manager": "NL - Geo HR",
    "default_user_permission": "Project Resource with Reports",
    "foreign_manager_emp_type": "Foreign Managers",
    "ot_request_template": "Netherlands OT Pre-approval",
    "ot_request_approval_path": "NL-Preapproval Overtime",
    "schedule_type": "urn:replicon:schedule-type:shift",
    "payrule_for_fulltime": "Netherlands-Full Time",
    "payrule_for_parttime": "Netherlands-Part Time",
    "timesheet_for_fulltime": "Netherlands Timesheet",
    "timesheet_for_parttime": "Netherlands Timesheet Part Time",
    "time_zone": "(UTC+1:00) Central European Standard Time",
    "timesheet_system_approval_path": "System Approval",
    "timesheet_period": "Weekly starting on Monday",
    "project_supervisor_permission":"Project Manager",
    "schedule_supervisor_permission":"Schedule Manager",
    "resource_supervisor_permission":"Resource Manager",
    "annual_leave": "NL ODR-Annual leave",
    "supervisor_permission": "Supervisor"
}
