ACTIVITY_MAPPER = {
    "Direct Field": [
        "Operator (Barge / Vessel / Inst.)",
        "Foreman (Barge / Vessel / Inst.)",
        "Supervisor (Barge / Vessel / Inst.)",
        "Foreman (Cranes - Crawler)",
        "Operator (Cranes - Crawler)",
        "Supervisor (Cranes - Crawler)",
        "Foreman (Cranes - Mobile)",
        "Operator (Cranes - Mobile)",
        "Supervisor (Cranes - Mobile)",
        "Foreman (Cranes - Ring)",
        "Operator (Cranes - Ring)",
        "Supervisor (Cranes - Ring)",
        "Mechanic / Fitter - Site",
        "Employee (Yard / Warehouse)",
        "Supervisor (Yard / Warehouse)",
        "Welder / Fabricator",
        "Foreman (Rigging / Lifting)",
        "Operator (Rigging / Lifting)",
        "Supervisor (Rigging / Lifting)",
        "Operator (SD / Jack & Slide / Gantry)",
        "Foreman (SD / Jack & Slide / Gantry)",
        "Supervisor (SD / Jack & Slide / Gantry)",
        "Operator (SPMT)",
        "Foreman (SPMT)",
        "Supervisor (SPMT)",
        "Truck Driver (Transport)",
        "Operator (Transport)",
        "Foreman (Transport)",
        "Supervisor (Transport)"
    ],
    "Direct Office": [
        "Engineer",
        "Project Administrator - Site",
        "Project Coordinator - Site",
        "Site Manager / Superintendent",
        "Project Manager",
        "Project Sponsor",
        "Project Director",
        "Contracts Engineer / Manager",
        "SHEQ Advisor - Site"
    ]
}
