role_approval_path_mapper = {
    "timesheet_approval_path": "Supervisor",
    "timeoff_approval_path_group": "Poland - LT Time off Approval path",
    "timeoff_approval_path": "Poland - Time off Approval path",
    "l1_manager": "L1 Manager (Poland)",
    "end_user_manager": "End User (Managers)",
    "project_manager": "Poland Project Manager",
    "hr_manager": "Poland - GEO HR",
    "default_user_permission": "Project Resource",
    "foreign_manager_emp_type": "Foreign Managers",
    "ot_request_template": "Poland OT Pre-approval",
    "ot_request_approval_path": "Supervisor",
    "schedule_type": "Shift Schedule",
    "payrule_for_pre_populated": "Poland Pre-Populated TS Payrule",
    "payrule_for_clockin": "Poland Clockin TS Payrule",
    "timesheet_for_9hrs_prepopulated": "Poland 9 Hrs Prepopulated Timesheet",
    "timesheet_for_85hrs_prepopulated": "Poland 8.5 Hrs Prepopulated Timesheet",
    "timesheet_for_8hrs_prepopulated": "Poland 8 Hrs Prepopulated Timesheet",
    "timesheet_for_clockinout": "Poland Clock In-Out Timesheet",
    "timesheet_for_clockinout_eqiv": "Poland Clock In-Out Equivalent Timesheet",
    "time_zone": "(UTC+1:00) Central European Standard Time",
    "timesheet_system_approval_path": "System Approval",
    "timesheet_period": "Weekly without crossing months - Poland",
    "punch_entry_policy": "Poland Punch Entry",
    "schedule_policy": "Poland Schedule Policy"
}
