HONG_KONG_USER_MAPPER = [
    {
        "country": "Hong Kong",
        "location": "ALL",
        "worker_type": "Employee",
        "compensation_grade": "Salary",
        "contract_type": "Full_time",
        "employee_type": [
            "Regular",
            "Fixed Term",
            "Partner",
            "Intern",
            "Non-Salaried / Self-Employed",
            "Non-Salaried / Self-Employed (Fixed Term)"
        ],
        "job_category": "Functional",
        "management_level": [
            "Senior Associate",
            "Specialist 1",
            "Specialist 2",
            "Associate",
            "Trainee/Apprentice",
            "Administrative 1",
            "Administrative 2"
        ],
        "additional_job_classification": "NA",
        "company_code": "",
        "schedule_type": "Office Schedule (Assigned to user via another automation)",
        "work_week": "Sunday to Saturday",
        "timesheet_template": "Hong Kong TSD Agile Emp OT",
        "time_entry_approval_path": "Automatic Approval",
        "timesheet_approval": "Supervisor",
        "timesheet_period": "Weekly without crossing months",
        "time_off_template": "Time Off",
        "time_off_approval": "System",
        "time_off_types": [
            "HKG_TOIL",
            "Holiday",
            "Leave of Absence",
            "INT Partner Paid Time Off Plan",
            "INT Partner Unpaid Time Off Plan"
        ],
        "payrule": "Hong Kong Pay Rule OT",
        "time_zone": "(UTC+8:00) North Asia East Standard Time",
        "holiday_calendar": "Hong Kong Holiday Calendar",
        "authentication_type": "SSO"
    },
    {
        "country": "Hong Kong",
        "location": "ALL",
        "worker_type": "Employee",
        "compensation_grade": "Salary",
        "contract_type": "Full_time",
        "employee_type": [
            "Regular",
            "Fixed Term",
            "Partner",
            "Intern",
            "Non-Salaried / Self-Employed",
            "Non-Salaried / Self-Employed (Fixed Term)"
        ],
        "job_category": "Functional",
        "management_level": [
            "Partner",
            "Executive Vice President",
            "Senior Vice President",
            "Vice President",
            "Director",
            "Senior Manager",
            "Manager"
        ],
        "additional_job_classification": "NA",
        "company_code": "",
        "schedule_type": "Office Schedule (Assigned to user via another automation)",
        "work_week": "Sunday to Saturday",
        "timesheet_template": "Hong Kong TSD Agile Emp NON-OT",
        "time_entry_approval_path": "Automatic Approval",
        "timesheet_approval": "Supervisor",
        "timesheet_period": "Weekly without crossing months",
        "time_off_template": "Time Off",
        "time_off_approval": "System",
        "time_off_types": [
            "Holiday",
            "Leave of Absence",
            "INT Partner Paid Time Off Plan",
            "INT Partner Unpaid Time Off Plan"
        ],
        "payrule": "Hong Kong Pay Rule NON-OT",
        "time_zone": "(UTC+8:00) North Asia East Standard Time",
        "holiday_calendar": "Hong Kong Holiday Calendar",
        "authentication_type": "SSO"
    },
    {
        "country": "Hong Kong",
        "location": "ALL",
        "worker_type": "Employee",
        "compensation_grade": "Salary",
        "contract_type": "Part_time",
        "employee_type": [
            "Regular",
            "Fixed Term",
            "Partner",
            "Intern",
            "Non-Salaried / Self-Employed",
            "Non-Salaried / Self-Employed (Fixed Term)"
        ],
        "job_category": "Functional",
        "management_level": [
            "Senior Associate",
            "Specialist 1",
            "Specialist 2",
            "Associate",
            "Trainee/Apprentice",
            "Administrative 1",
            "Administrative 2"
        ],
        "additional_job_classification": "NA",
        "company_code": "",
        "schedule_type": "Office Schedule (Assigned to user via another automation)",
        "work_week": "Sunday to Saturday",
        "timesheet_template": "Hong Kong TSD Agile Emp OT",
        "time_entry_approval_path": "Automatic Approval",
        "timesheet_approval": "Supervisor",
        "timesheet_period": "Weekly without crossing months",
        "time_off_template": "Time Off",
        "time_off_approval": "System",
        "time_off_types": [
            "HKG_TOIL",
            "Holiday",
            "Leave of Absence",
            "INT Partner Paid Time Off Plan",
            "INT Partner Unpaid Time Off Plan"
        ],
        "payrule": "Hong Kong Pay Rule OT",
        "time_zone": "(UTC+8:00) North Asia East Standard Time",
        "holiday_calendar": "Hong Kong Holiday Calendar",
        "authentication_type": "SSO"
    },
    {
        "country": "Hong Kong",
        "location": "ALL",
        "worker_type": "Employee",
        "compensation_grade": "Salary",
        "contract_type": "Part_time",
        "employee_type": [
            "Regular",
            "Fixed Term",
            "Partner",
            "Intern",
            "Non-Salaried / Self-Employed",
            "Non-Salaried / Self-Employed (Fixed Term)"
        ],
        "job_category": "Functional",
        "management_level": [
            "Partner",
            "Executive Vice President",
            "Senior Vice President",
            "Vice President",
            "Director",
            "Senior Manager",
            "Manager"
        ],
        "additional_job_classification": "NA",
        "company_code": "",
        "schedule_type": "Office Schedule (Assigned to user via another automation)",
        "work_week": "Sunday to Saturday",
        "timesheet_template": "Hong Kong TSD Agile Emp NON-OT",
        "time_entry_approval_path": "Automatic Approval",
        "timesheet_approval": "Supervisor",
        "timesheet_period": "Weekly without crossing months",
        "time_off_template": "Time Off",
        "time_off_approval": "System",
        "time_off_types": [
            "Holiday",
            "Leave of Absence",
            "INT Partner Paid Time Off Plan",
            "INT Partner Unpaid Time Off Plan"
        ],
        "payrule": "Hong Kong Pay Rule NON-OT",
        "time_zone": "(UTC+8:00) North Asia East Standard Time",
        "holiday_calendar": "Hong Kong Holiday Calendar",
        "authentication_type": "SSO"
    },
    {
        "country": "Hong Kong",
        "location": "ALL",
        "worker_type": "Employee",
        "compensation_grade": "Salary",
        "contract_type": "Full_time",
        "employee_type": [
            "Regular",
            "Fixed Term",
            "Partner",
            "Intern",
            "Non-Salaried / Self-Employed",
            "Non-Salaried / Self-Employed (Fixed Term)"
        ],
        "job_category": "Client Services",
        "management_level": [
            "Senior Associate",
            "Specialist 1",
            "Specialist 2",
            "Associate",
            "Trainee/Apprentice",
            "Administrative 1",
            "Administrative 2"
        ],
        "additional_job_classification": "NA",
        "company_code": "",
        "schedule_type": "Office Schedule (Assigned to user via another automation)",
        "work_week": "Sunday to Saturday",
        "timesheet_template": "Hong Kong TSD Agile Emp OT",
        "time_entry_approval_path": "Automatic Approval",
        "timesheet_approval": "Supervisor",
        "timesheet_period": "Weekly without crossing months",
        "time_off_template": "Time Off",
        "time_off_approval": "System",
        "time_off_types": [
            "HKG_TOIL",
            "Holiday",
            "Leave of Absence",
            "INT Partner Paid Time Off Plan",
            "INT Partner Unpaid Time Off Plan"
        ],
        "payrule": "Hong Kong Pay Rule OT",
        "time_zone": "(UTC+8:00) North Asia East Standard Time",
        "holiday_calendar": "Hong Kong Holiday Calendar",
        "authentication_type": "SSO"
    },
    {
        "country": "Hong Kong",
        "location": "ALL",
        "worker_type": "Employee",
        "compensation_grade": "Salary",
        "contract_type": "Full_time",
        "employee_type": [
            "Regular",
            "Fixed Term",
            "Partner",
            "Intern",
            "Non-Salaried / Self-Employed",
            "Non-Salaried / Self-Employed (Fixed Term)"
        ],
        "job_category": "Client Services",
        "management_level": [
            "Partner",
            "Executive Vice President",
            "Senior Vice President",
            "Vice President",
            "Director",
            "Senior Manager",
            "Manager"
        ],
        "additional_job_classification": "NA",
        "company_code": "",
        "schedule_type": "Office Schedule (Assigned to user via another automation)",
        "work_week": "Sunday to Saturday",
        "timesheet_template": "Hong Kong TSD Agile Emp NON-OT",
        "time_entry_approval_path": "Automatic Approval",
        "timesheet_approval": "Supervisor",
        "timesheet_period": "Weekly without crossing months",
        "time_off_template": "Time Off",
        "time_off_approval": "System",
        "time_off_types": [
            "Holiday",
            "Leave of Absence",
            "INT Partner Paid Time Off Plan",
            "INT Partner Unpaid Time Off Plan"
        ],
        "payrule": "Hong Kong Pay Rule NON-OT",
        "time_zone": "(UTC+8:00) North Asia East Standard Time",
        "holiday_calendar": "Hong Kong Holiday Calendar",
        "authentication_type": "SSO"
    },
    {
        "country": "Hong Kong",
        "location": "ALL",
        "worker_type": "Employee",
        "compensation_grade": "Salary",
        "contract_type": "Part_time",
        "employee_type": [
            "Regular",
            "Fixed Term",
            "Partner",
            "Intern",
            "Non-Salaried / Self-Employed",
            "Non-Salaried / Self-Employed (Fixed Term)"
        ],
        "job_category": "Client Services",
        "management_level": [
            "Senior Associate",
            "Specialist 1",
            "Specialist 2",
            "Associate",
            "Trainee/Apprentice",
            "Administrative 1",
            "Administrative 2"
        ],
        "additional_job_classification": "NA",
        "company_code": "",
        "schedule_type": "Office Schedule (Assigned to user via another automation)",
        "work_week": "Sunday to Saturday",
        "timesheet_template": "Hong Kong TSD Agile Emp OT",
        "time_entry_approval_path": "Automatic Approval",
        "timesheet_approval": "Supervisor",
        "timesheet_period": "Weekly without crossing months",
        "time_off_template": "Time Off",
        "time_off_approval": "System",
        "time_off_types": [
            "HKG_TOIL",
            "Holiday",
            "Leave of Absence",
            "INT Partner Paid Time Off Plan",
            "INT Partner Unpaid Time Off Plan"
        ],
        "payrule": "Hong Kong Pay Rule OT",
        "time_zone": "(UTC+8:00) North Asia East Standard Time",
        "holiday_calendar": "Hong Kong Holiday Calendar",
        "authentication_type": "SSO"
    },
    {
        "country": "Hong Kong",
        "location": "ALL",
        "worker_type": "Employee",
        "compensation_grade": "Salary",
        "contract_type": "Part_time",
        "employee_type": [
            "Regular",
            "Fixed Term",
            "Partner",
            "Intern",
            "Non-Salaried / Self-Employed",
            "Non-Salaried / Self-Employed (Fixed Term)"
        ],
        "job_category": "Client Services",
        "management_level": [
            "Partner",
            "Executive Vice President",
            "Senior Vice President",
            "Vice President",
            "Director",
            "Senior Manager",
            "Manager"
        ],
        "additional_job_classification": "NA",
        "company_code": "",
        "schedule_type": "Office Schedule (Assigned to user via another automation)",
        "work_week": "Sunday to Saturday",
        "timesheet_template": "Hong Kong TSD Agile Emp NON-OT",
        "time_entry_approval_path": "Automatic Approval",
        "timesheet_approval": "Supervisor",
        "timesheet_period": "Weekly without crossing months",
        "time_off_template": "Time Off",
        "time_off_approval": "System",
        "time_off_types": [
            "Holiday",
            "Leave of Absence",
            "INT Partner Paid Time Off Plan",
            "INT Partner Unpaid Time Off Plan"
        ],
        "payrule": "Hong Kong Pay Rule NON-OT",
        "time_zone": "(UTC+8:00) North Asia East Standard Time",
        "holiday_calendar": "Hong Kong Holiday Calendar",
        "authentication_type": "SSO"
    },
    {
        "country": "Hong Kong",
        "location": "ALL",
        "worker_type": "Employee",
        "compensation_grade": "Hourly",
        "contract_type": "Full_time",
        "employee_type": [
            "Regular",
            "Fixed Term",
            "Partner",
            "Intern",
            "Non-Salaried / Self-Employed",
            "Non-Salaried / Self-Employed (Fixed Term)"
        ],
        "job_category": "Functional",
        "management_level": [
            "Senior Associate",
            "Specialist 1",
            "Specialist 2",
            "Associate",
            "Trainee/Apprentice",
            "Administrative 1",
            "Administrative 2"
        ],
        "additional_job_classification": "NA",
        "company_code": "",
        "schedule_type": "Office Schedule (Assigned to user via another automation)",
        "work_week": "Sunday to Saturday",
        "timesheet_template": "Hong Kong TSD Agile Emp OT",
        "time_entry_approval_path": "Automatic Approval",
        "timesheet_approval": "Supervisor",
        "timesheet_period": "Weekly without crossing months",
        "time_off_template": "Time Off",
        "time_off_approval": "System",
        "time_off_types": [
            "HKG_TOIL",
            "Holiday",
            "Leave of Absence",
            "INT Partner Paid Time Off Plan",
            "INT Partner Unpaid Time Off Plan"
        ],
        "payrule": "Hong Kong Pay Rule OT",
        "time_zone": "(UTC+8:00) North Asia East Standard Time",
        "holiday_calendar": "Hong Kong Holiday Calendar",
        "authentication_type": "SSO"
    },
    {
        "country": "Hong Kong",
        "location": "ALL",
        "worker_type": "Employee",
        "compensation_grade": "Hourly",
        "contract_type": "Full_time",
        "employee_type": [
            "Regular",
            "Fixed Term",
            "Partner",
            "Intern",
            "Non-Salaried / Self-Employed",
            "Non-Salaried / Self-Employed (Fixed Term)"
        ],
        "job_category": "Functional",
        "management_level": [
            "Partner",
            "Executive Vice President",
            "Senior Vice President",
            "Vice President",
            "Director",
            "Senior Manager",
            "Manager"
        ],
        "additional_job_classification": "NA",
        "company_code": "",
        "schedule_type": "Office Schedule (Assigned to user via another automation)",
        "work_week": "Sunday to Saturday",
        "timesheet_template": "Hong Kong TSD Agile Emp NON-OT",
        "time_entry_approval_path": "Automatic Approval",
        "timesheet_approval": "Supervisor",
        "timesheet_period": "Weekly without crossing months",
        "time_off_template": "Time Off",
        "time_off_approval": "System",
        "time_off_types": [
            "Holiday",
            "Leave of Absence",
            "INT Partner Paid Time Off Plan",
            "INT Partner Unpaid Time Off Plan"
        ],
        "payrule": "Hong Kong Pay Rule NON-OT",
        "time_zone": "(UTC+8:00) North Asia East Standard Time",
        "holiday_calendar": "Hong Kong Holiday Calendar",
        "authentication_type": "SSO"
    },
    {
        "country": "Hong Kong",
        "location": "ALL",
        "worker_type": "Employee",
        "compensation_grade": "Hourly",
        "contract_type": "Part_time",
        "employee_type": [
            "Regular",
            "Fixed Term",
            "Partner",
            "Intern",
            "Non-Salaried / Self-Employed",
            "Non-Salaried / Self-Employed (Fixed Term)"
        ],
        "job_category": "Functional",
        "management_level": [
            "Senior Associate",
            "Specialist 1",
            "Specialist 2",
            "Associate",
            "Trainee/Apprentice",
            "Administrative 1",
            "Administrative 2"
        ],
        "additional_job_classification": "NA",
        "company_code": "",
        "schedule_type": "Office Schedule (Assigned to user via another automation)",
        "work_week": "Sunday to Saturday",
        "timesheet_template": "Hong Kong TSD Agile Emp OT",
        "time_entry_approval_path": "Automatic Approval",
        "timesheet_approval": "Supervisor",
        "timesheet_period": "Weekly without crossing months",
        "time_off_template": "Time Off",
        "time_off_approval": "System",
        "time_off_types": [
            "HKG_TOIL",
            "Holiday",
            "Leave of Absence",
            "INT Partner Paid Time Off Plan",
            "INT Partner Unpaid Time Off Plan"
        ],
        "payrule": "Hong Kong Pay Rule OT",
        "time_zone": "(UTC+8:00) North Asia East Standard Time",
        "holiday_calendar": "Hong Kong Holiday Calendar",
        "authentication_type": "SSO"
    },
    {
        "country": "Hong Kong",
        "location": "ALL",
        "worker_type": "Employee",
        "compensation_grade": "Hourly",
        "contract_type": "Part_time",
        "employee_type": [
            "Regular",
            "Fixed Term",
            "Partner",
            "Intern",
            "Non-Salaried / Self-Employed",
            "Non-Salaried / Self-Employed (Fixed Term)"
        ],
        "job_category": "Functional",
        "management_level": [
            "Partner",
            "Executive Vice President",
            "Senior Vice President",
            "Vice President",
            "Director",
            "Senior Manager",
            "Manager"
        ],
        "additional_job_classification": "NA",
        "company_code": "",
        "schedule_type": "Office Schedule (Assigned to user via another automation)",
        "work_week": "Sunday to Saturday",
        "timesheet_template": "Hong Kong TSD Agile Emp NON-OT",
        "time_entry_approval_path": "Automatic Approval",
        "timesheet_approval": "Supervisor",
        "timesheet_period": "Weekly without crossing months",
        "time_off_template": "Time Off",
        "time_off_approval": "System",
        "time_off_types": [
            "Holiday",
            "Leave of Absence",
            "INT Partner Paid Time Off Plan",
            "INT Partner Unpaid Time Off Plan"
        ],
        "payrule": "Hong Kong Pay Rule NON-OT",
        "time_zone": "(UTC+8:00) North Asia East Standard Time",
        "holiday_calendar": "Hong Kong Holiday Calendar",
        "authentication_type": "SSO"
    },
    {
        "country": "Hong Kong",
        "location": "ALL",
        "worker_type": "Employee",
        "compensation_grade": "Hourly",
        "contract_type": "Full_time",
        "employee_type": [
            "Regular",
            "Fixed Term",
            "Partner",
            "Intern",
            "Non-Salaried / Self-Employed",
            "Non-Salaried / Self-Employed (Fixed Term)"
        ],
        "job_category": "Client Services",
        "management_level": [
            "Senior Associate",
            "Specialist 1",
            "Specialist 2",
            "Associate",
            "Trainee/Apprentice",
            "Administrative 1",
            "Administrative 2"
        ],
        "additional_job_classification": "NA",
        "company_code": "",
        "schedule_type": "Office Schedule (Assigned to user via another automation)",
        "work_week": "Sunday to Saturday",
        "timesheet_template": "Hong Kong TSD Agile Emp OT",
        "time_entry_approval_path": "Automatic Approval",
        "timesheet_approval": "Supervisor",
        "timesheet_period": "Weekly without crossing months",
        "time_off_template": "Time Off",
        "time_off_approval": "System",
        "time_off_types": [
            "HKG_TOIL",
            "Holiday",
            "Leave of Absence",
            "INT Partner Paid Time Off Plan",
            "INT Partner Unpaid Time Off Plan"
        ],
        "payrule": "Hong Kong Pay Rule OT",
        "time_zone": "(UTC+8:00) North Asia East Standard Time",
        "holiday_calendar": "Hong Kong Holiday Calendar",
        "authentication_type": "SSO"
    },
    {
        "country": "Hong Kong",
        "location": "ALL",
        "worker_type": "Employee",
        "compensation_grade": "Hourly",
        "contract_type": "Full_time",
        "employee_type": [
            "Regular",
            "Fixed Term",
            "Partner",
            "Intern",
            "Non-Salaried / Self-Employed",
            "Non-Salaried / Self-Employed (Fixed Term)"
        ],
        "job_category": "Client Services",
        "management_level": [
            "Partner",
            "Executive Vice President",
            "Senior Vice President",
            "Vice President",
            "Director",
            "Senior Manager",
            "Manager"
        ],
        "additional_job_classification": "NA",
        "company_code": "",
        "schedule_type": "Office Schedule (Assigned to user via another automation)",
        "work_week": "Sunday to Saturday",
        "timesheet_template": "Hong Kong TSD Agile Emp NON-OT",
        "time_entry_approval_path": "Automatic Approval",
        "timesheet_approval": "Supervisor",
        "timesheet_period": "Weekly without crossing months",
        "time_off_template": "Time Off",
        "time_off_approval": "System",
        "time_off_types": [
            "Holiday",
            "Leave of Absence",
            "INT Partner Paid Time Off Plan",
            "INT Partner Unpaid Time Off Plan"
        ],
        "payrule": "Hong Kong Pay Rule NON-OT",
        "time_zone": "(UTC+8:00) North Asia East Standard Time",
        "holiday_calendar": "Hong Kong Holiday Calendar",
        "authentication_type": "SSO"
    },
    {
        "country": "Hong Kong",
        "location": "ALL",
        "worker_type": "Employee",
        "compensation_grade": "Hourly",
        "contract_type": "Part_time",
        "employee_type": [
            "Regular",
            "Fixed Term",
            "Partner",
            "Intern",
            "Non-Salaried / Self-Employed",
            "Non-Salaried / Self-Employed (Fixed Term)"
        ],
        "job_category": "Client Services",
        "management_level": [
            "Senior Associate",
            "Specialist 1",
            "Specialist 2",
            "Associate",
            "Trainee/Apprentice",
            "Administrative 1",
            "Administrative 2"
        ],
        "additional_job_classification": "NA",
        "company_code": "",
        "schedule_type": "Office Schedule (Assigned to user via another automation)",
        "work_week": "Sunday to Saturday",
        "timesheet_template": "Hong Kong TSD Agile Emp OT",
        "time_entry_approval_path": "Automatic Approval",
        "timesheet_approval": "Supervisor",
        "timesheet_period": "Weekly without crossing months",
        "time_off_template": "Time Off",
        "time_off_approval": "System",
        "time_off_types": [
            "HKG_TOIL",
            "Holiday",
            "Leave of Absence",
            "INT Partner Paid Time Off Plan",
            "INT Partner Unpaid Time Off Plan"
        ],
        "payrule": "Hong Kong Pay Rule OT",
        "time_zone": "(UTC+8:00) North Asia East Standard Time",
        "holiday_calendar": "Hong Kong Holiday Calendar",
        "authentication_type": "SSO"
    },
    {
        "country": "Hong Kong",
        "location": "ALL",
        "worker_type": "Employee",
        "compensation_grade": "Hourly",
        "contract_type": "Part_time",
        "employee_type": [
            "Regular",
            "Fixed Term",
            "Partner",
            "Intern",
            "Non-Salaried / Self-Employed",
            "Non-Salaried / Self-Employed (Fixed Term)"
        ],
        "job_category": "Client Services",
        "management_level": [
            "Partner",
            "Executive Vice President",
            "Senior Vice President",
            "Vice President",
            "Director",
            "Senior Manager",
            "Manager"
        ],
        "additional_job_classification": "NA",
        "company_code": "",
        "schedule_type": "Office Schedule (Assigned to user via another automation)",
        "work_week": "Sunday to Saturday",
        "timesheet_template": "Hong Kong TSD Agile Emp NON-OT",
        "time_entry_approval_path": "Automatic Approval",
        "timesheet_approval": "Supervisor",
        "timesheet_period": "Weekly without crossing months",
        "time_off_template": "Time Off",
        "time_off_approval": "System",
        "time_off_types": [
            "Holiday",
            "Leave of Absence",
            "INT Partner Paid Time Off Plan",
            "INT Partner Unpaid Time Off Plan"
        ],
        "payrule": "Hong Kong Pay Rule NON-OT",
        "time_zone": "(UTC+8:00) North Asia East Standard Time",
        "holiday_calendar": "Hong Kong Holiday Calendar",
        "authentication_type": "SSO"
    },
    {
        "country": "Hong Kong",
        "location": "ALL",
        "worker_type": "Contingent Worker",
        "compensation_grade": "NA",
        "contract_type": [
            "Full_time",
            "Part_time"
        ],
        "employee_type": [
            "Agency Contractor",
            "Alliance/Perimeter Worker",
            "Direct Contractor",
            "Vendor",
            "Intern"
        ],
        "job_category": "Indirect_Labor",
        "management_level": [
            "Partner",
            "Executive Vice President",
            "Senior Vice President",
            "Vice President",
            "Director",
            "Senior Manager",
            "Manager",
            "Senior Associate",
            "Specialist 1",
            "Specialist 2",
            "Associate",
            "Trainee/Apprentice",
            "Administrative 1",
            "Administrative 2"
        ],
        "additional_job_classification": "NA",
        "company_code": "",
        "schedule_type": "Office Schedule (Assigned to user via another automation)",
        "work_week": "Sunday to Saturday",
        "timesheet_template": "Vialto TSD Agile Contingent",
        "time_entry_approval_path": "Automatic Approval",
        "timesheet_approval": "Supervisor",
        "timesheet_period": "Weekly without crossing months",
        "time_off_template": "NA",
        "time_off_approval": "NA",
        "time_off_types": "NA",
        "payrule": "Vialto Dummy Pay Rule",
        "time_zone": "(UTC+8:00) North Asia East Standard Time",
        "holiday_calendar": "NA",
        "authentication_type": "SSO"
    }
]
