from dxctechnology.workday_user_import_v1.user_import.config import *
from dxctechnology.workday_user_import_v1.user_import.mappers.master_mapper import MAPPER

instance = "sandbox2"

version = "v2"
ia_version = "v1"
process_time_off_accrual_version = "v1"

environment = "pre-production"
can_run_batch_task_var_name_canada = f"dxctechnology_workday_user_import_canada_can_run_batch_task_{instance}"

company_key = "dxcsandbox2"
replicon_conn_id = "replicon_dxcsandbox2_x.workday_1"
sftp_conn_id = "sftp_dxcsandbox2_628172_Workday"

DXC_WORKDAY_USER_SYNC_USER_MAPPER = MAPPER

process_time_off_accrual = f"dxctechnology_workday_user_sync_timeoff_assignment_policy_update_for_no_accrual_child_{instance}_{process_time_off_accrual_version}"

workday_user_import_process_canada_users_child_dag = f"dxctechnology_workday_user_import_process_canada_process_user_child_dag_{instance}_{version}"
workday_user_import_canada_users_add_user_child_dag = f"dxctechnology_workday_user_import_canada_users_add_user_child_{instance}_{version}"
workday_user_import_canada_users_add_user_timeoff_process_child_dag = f"dxctechnology_workday_user_import_canada_users_add_user_timeoff_process_child_{instance}_{version}"
workday_user_import_canada_users_update_user_timeoff_process_child_dag = f"dxctechnology_workday_user_import_canada_users_update_user_timeoff_process_child_{instance}_{version}"
workday_user_import_canada_users_add_user_timeoff_process_child_for_canada_dag = f"dxctechnology_workday_user_import_canada_users_add_user_timeoff_process_child_for_canada_{instance}_{version}"
workday_user_import_canada_users_update_user_timeoff_process_child_dag_disable = f"dxctechnology_workday_user_import_canada_users_update_user_timeoff_process_child_for_disable_user_{instance}_{version}"
workday_user_import_canada_users_update_user_child_dag = f"dxctechnology_workday_user_import_canada_users_update_user_child_{instance}_{version}"
workday_user_import_canada_users_update_user_rehire_timeoff_process_child_dag = f"dxctechnology_workday_user_import_canada_users_update_user_rehire_timeoff_assignment_process_child_{instance}_{version}"
workday_user_import_canada_users_process_canada_banked_timeoff_type_child_dag = f"dxctechnology_workday_user_import_canada_users_process_canada_banked_timeoff_type_child_{instance}_{version}"
workday_user_import_canada_users_process_canada_vacation_timeoff_type_child_dag = f"dxctechnology_workday_user_import_canada_users_process_canada_vacation_timeoff_type_child_{instance}_{version}"


workday_user_import_ia_zero_timeoff_assignment_child_dag = f"dxctechnology_workday_user_import_ia_zero_timeoff_assignment_child_{instance}_{ia_version}"
workday_user_import_ia_one_timeoff_assignment_child_dag = f"dxctechnology_workday_user_import_ia_one_timeoff_assignment_child_{instance}_{ia_version}"

# Cleanup child DAG ID for disabled users
delete_future_entries_child_dag_id = f"dxctechnology_workday_user_sync_delete_future_entries_child_{instance}_v2"

# Overrides: bump max_active_runs to 10 for this environment (base defaults in config.py are unchanged, so production is not affected)
global_add_user_max_active_runs = 10
global_add_user_timeoff_assignment_max_active_runs = 10
global_update_user_max_active_runs = 10
global_update_user_timeoff_assignment_max_active_runs = 10
process_users_max_active_runs = 10
