ACTIVITY_MAPPER = [
    {
        "additional_job_classifications": [
            "Payrule A-Reg F/T",
            "Payrule B - Reg P/T",
            "Payrule C - Reg Shift",
            "Payrule D - Shift -OT",
            "Payrule G - OT Only",
            "Payrule H - OT Exception",
            "Payrule N - Velonetic",
            "IRL-Payrule A-Reg F/T",
            "IRL-Payrule B - Reg P/T",
            "Payrule C - OT Only",
            "Payrule D - OT Exception",
            "GBR-FDS Group46"
        ],
        "company_code": [
            "IEEU",
            "IEES",
            "GBA5",
            "GBC5"
        ],
        "activity_types": [
            "300-BD Opportunity Time",
            "400-Project Attendance",
            "401-Consulting",
            "405-Rqmts Determination",
            "406-Rqmts Validation",
            "411-Design",
            "412-Implementation",
            "413-Documentation",
            "414-Testing",
            "415-Programming",
            "421-Quality Management",
            "422-Knowledge Management",
            "431-Project Management",
            "432-Project Administration",
            "433-Project Meetings",
            "434-Project Reports",
            "441-Service Management",
            "442-Network Management",
            "443-First Level Support",
            "444-Product Support",
            "445-Second Level Support",
            "446-Third Level Support",
            "451-Proposal Prep&Es",
            "452-Bid Evaluation",
            "453-General Bus Dev",
            "454-Fairs and Events",
            "457-Release Management",
            "458-Crisis Management",
            "459-Reporting for Serv Mgmt",
            "461-Incident Management",
            "462-Operations Management",
            "463-Problem Management",
            "464-Information Management",
            "465-Change Management",
            "466-Service Level Management",
            "467-Availability Management",
            "468-Capacity Management",
            "469-Configuration Management",
            "480-PO Excess (Unapprov)",
            "491-Train Prep & Dlv",
            "492-Project Training Received",
            "493-Project Travel",
            "700-General Attendance",
            "705-Meetings",
            "710-Travel",
            "715-BPO HC Admin Time",
            "720-Administration",
            "725-BPO HC Corporate Training",
            "730-Training Received",
            "735-Training Delivered",
            "740-Management",
            "750-People Management",
            "770-Counseling/Mentoring",
            "775-Unassigned",
            "776-Voluntary Service",
            "777-Union Activities",
            "760-Knowledge Management"
        ]
    },
    {
        "additional_job_classifications": [
            "Payrule E - Shift-Stdby",
            "Payrule K - Stdby Only",
            "Payrule F - Shift - OT & Stdby",
            "Payrule I - OT Exception inc Standby",
            "Payrule J - OT & Stdby",
            "Payrule L - EON",
            "Payrule M - Olympus",
            "Payrule O - AT&T",
            "Payrule Q - FCA",
            "Payrule P-RMG",
            "Payrule E - OT Exception inc Standby",
            "Payrule F - OT & Stdby",
            "IRL-Payrule K - Stdby Only",
            "IRL-FDS Group100",
            "IRL-FDS Group101",
            "IRL-FDS Group102",
            "GBR-FDS Group1",
            "GBR-FDS Group2",
            "GBR-FDS Group3",
            "GBR-FDS Group4",
            "GBR-FDS Group5",
            "GBR-FDS Group6",
            "GBR-FDS Group7",
            "GBR-FDS Group8",
            "GBR-FDS Group9",
            "GBR-FDS Group10",
            "GBR-FDS Group11",
            "GBR-FDS Group12",
            "GBR-FDS Group13",
            "GBR-FDS Group14",
            "GBR-FDS Group15",
            "GBR-FDS Group16",
            "GBR-FDS Group17",
            "GBR-FDS Group18",
            "GBR-FDS Group19",
            "GBR-FDS Group20",
            "GBR-FDS Group21",
            "GBR-FDS Group22",
            "GBR-FDS Group23",
            "GBR-FDS Group24",
            "GBR-FDS Group25",
            "GBR-FDS Group26",
            "GBR-FDS Group27",
            "GBR-FDS Group28",
            "GBR-FDS Group29",
            "GBR-FDS Group30",
            "GBR-FDS Group31",
            "GBR-FDS Group32",
            "GBR-FDS Group33",
            "GBR-FDS Group34",
            "GBR-FDS Group35",
            "GBR-FDS Group36",
            "GBR-FDS Group37",
            "GBR-FDS Group38",
            "GBR-FDS Group39",
            "GBR-FDS Group40",
            "GBR-FDS Group41",
            "GBR-FDS Group42",
            "GBR-FDS Group43",
            "GBR-FDS Group44",
            "GBR-FDS Group45",
            "GBR-FDS Group47",
            "GBR-FDS Group48",
            "GBR-FDS Group49",
            "GBR-FDS Group50",
            "GBR-FDS Group51",
            "GBR-FDS Group52",
            "GBR-FDS Group53",
            "GBR-FDS Group54",
            "GBR-FDS Group55",
            "IRL-FDS Group100",
            "IRL-FDS Group101",
            "IRL-Payrule B - Reg P/T"
        ],
        "company_code": [
            "IEEU",
            "IEES",
            "GBA5",
            "GBC5"
        ],
        "activity_types": [
            "300-BD Opportunity Time",
            "400-Project Attendance",
            "401-Consulting",
            "405-Rqmts Determination",
            "406-Rqmts Validation",
            "411-Design",
            "412-Implementation",
            "413-Documentation",
            "414-Testing",
            "415-Programming",
            "421-Quality Management",
            "422-Knowledge Management",
            "431-Project Management",
            "432-Project Administration",
            "433-Project Meetings",
            "434-Project Reports",
            "441-Service Management",
            "442-Network Management",
            "443-First Level Support",
            "444-Product Support",
            "445-Second Level Support",
            "446-Third Level Support",
            "451-Proposal Prep&Es",
            "452-Bid Evaluation",
            "453-General Bus Dev",
            "454-Fairs and Events",
            "457-Release Management",
            "458-Crisis Management",
            "459-Reporting for Serv Mgmt",
            "461-Incident Management",
            "462-Operations Management",
            "463-Problem Management",
            "464-Information Management",
            "465-Change Management",
            "466-Service Level Management",
            "467-Availability Management",
            "468-Capacity Management",
            "469-Configuration Management",
            "480-PO Excess (Unapprov)",
            "491-Train Prep & Dlv",
            "492-Project Training Received",
            "493-Project Travel",
            "499-Standby",
            "700-General Attendance",
            "705-Meetings",
            "710-Travel",
            "715-BPO HC Admin Time",
            "720-Administration",
            "725-BPO HC Corporate Training",
            "730-Training Received",
            "735-Training Delivered",
            "740-Management",
            "750-People Management",
            "770-Counseling/Mentoring",
            "775-Unassigned",
            "776-Voluntary Service",
            "777-Union Activities",
            "779-Stand By w/o WBS",
            "760-Knowledge Management"
        ]
    }
]