user_import_mapper = [
  {
    "location_level_1": "BRA",
    "location_level_2": "All",
    "location_level_3": "All",
    "activity_type": "All",
    "remote_worker": "Y",
    "company_code": "All",
    "business_segment": "All",
    "title": ["All Except", "Young Apprentice", "Intern"],
    "Department": "All",
    "pay_scale_group": "All",
    "job_level": "All",
    "reg_temp": "Regular",
    "pay_type": "Salaried",
    "full_part": "Full-Time",
    "ot_eligible": "Yes",
    "employee_type": "[BRA] Regulars OT Eligible",
    "punch_policy": "[BRA] Punch Policy",
    "timesheet_template": "BRA_Punch_Timesheet_Remote",
    "timesheet_approval_path": "Supervisor",
    "timesheet_period": "BRA - Weekly starting on Monday",
    "time_off_template": "Time Off",
    "time_off_approver": "Supervisor",
    "schedule_type": "Shift Schedule",
    "schedule_policy": "Default Shift Schedule Policy",
    "holiday_calendar": "Brazil",
    "timezone": "(UTC-3:00) E. South America Standard Time",
    "work_week": "Monday to Sunday",
    "payrule_name": "[BRA] FT OT Eligible"
  },
  {
    "location_level_1": "BRA",
    "location_level_2": "All",
    "location_level_3": "All",
    "activity_type": "All",
    "remote_worker": "All",
    "company_code": "All",
    "business_segment": "All",
    "title": ["All Except", "Young Apprentice", "Intern"],
    "Department": "All",
    "pay_scale_group": "All",
    "job_level": "All",
    "reg_temp": "Regular",
    "pay_type": "Salaried",
    "full_part": "Full-Time",
    "ot_eligible": "No",
    "employee_type": "[BRA] Regulars",
    "punch_policy": "NA",
    "timesheet_template": "BRA_Sal_Non-OT_Timesheet",
    "timesheet_approval_path": "Supervisor",
    "timesheet_period": "BRA - Weekly starting on Monday",
    "time_off_template": "Time Off",
    "time_off_approver": "Supervisor",
    "schedule_type": "Shift Schedule",
    "schedule_policy": "Default Shift Schedule Policy",
    "holiday_calendar": "Brazil",
    "timezone": "(UTC-3:00) E. South America Standard Time",
    "work_week": "Monday to Sunday",
    "payrule_name": "[BRA] FT"
  },
  {
    "location_level_1": "BRA",
    "location_level_2": "All",
    "location_level_3": "All",
    "activity_type": "All",
    "remote_worker": "All",
    "company_code": "All",
    "business_segment": "All",
    "title": ["All Except", "Young Apprentice", "Intern"],
    "Department": "All",
    "pay_scale_group": "All",
    "job_level": "All",
    "reg_temp": "Regular",
    "pay_type": "Salaried",
    "full_part": "Part-Time",
    "ot_eligible": "No",
    "employee_type": "[BRA] Regulars",
    "punch_policy": "NA",
    "timesheet_template": "BRA_Sal_Non-OT_Timesheet",
    "timesheet_approval_path": "Supervisor",
    "timesheet_period": "BRA - Weekly starting on Monday",
    "time_off_template": "Time Off",
    "time_off_approver": "Supervisor",
    "schedule_type": "Shift Schedule",
    "schedule_policy": "Default Shift Schedule Policy",
    "holiday_calendar": "Brazil",
    "timezone": "(UTC-3:00) E. South America Standard Time",
    "work_week": "Monday to Sunday",
    "payrule_name": "[BRA] PT"
  },
  {
    "location_level_1": "BRA",
    "location_level_2": "All",
    "location_level_3": "All",
    "activity_type": "All",
    "remote_worker": "Y",
    "company_code": "All",
    "business_segment": "All",
    "title": "Young Apprentice",
    "Department": "All",
    "pay_scale_group": "All",
    "job_level": "All",
    "reg_temp": "Temporary",
    "pay_type": "Salaried",
    "full_part": "Part-Time",
    "ot_eligible": "No",
    "employee_type": "[BRA] Young Apprentice",
    "punch_policy": "[BRA] Punch Policy",
    "timesheet_template": "BRA_Punch_Timesheet_Remote",
    "timesheet_approval_path": "Supervisor",
    "timesheet_period": "BRA - Weekly starting on Monday",
    "time_off_template": "Time Off",
    "time_off_approver": "Supervisor",
    "schedule_type": "Shift Schedule",
    "schedule_policy": "Default Shift Schedule Policy",
    "holiday_calendar": "Brazil",
    "timezone": "(UTC-3:00) E. South America Standard Time",
    "work_week": "Monday to Sunday",
    "payrule_name": "[BRA] PT"
  },
  {
    "location_level_1": "BRA",
    "location_level_2": "All",
    "location_level_3": "All",
    "activity_type": "All",
    "remote_worker": "Y",
    "company_code": "All",
    "business_segment": "All",
    "title": "Intern",
    "Department": "All",
    "pay_scale_group": "All",
    "job_level": "All",
    "reg_temp": "Temporary",
    "pay_type": "Salaried",
    "full_part": "Part-Time",
    "ot_eligible": "No",
    "employee_type": "[BRA] Interns",
    "punch_policy": "[BRA] Punch Policy",
    "timesheet_template": "BRA_Punch_Timesheet_Remote",
    "timesheet_approval_path": "Supervisor",
    "timesheet_period": "BRA - Weekly starting on Monday",
    "time_off_template": "Time Off",
    "time_off_approver": "Supervisor",
    "schedule_type": "Shift Schedule",
    "schedule_policy": "Default Shift Schedule Policy",
    "holiday_calendar": "Brazil",
    "timezone": "(UTC-3:00) E. South America Standard Time",
    "work_week": "Monday to Sunday",
    "payrule_name": "[BRA] PT"
  },
  {
    "location_level_1": "BRA",
    "location_level_2": "All",
    "location_level_3": "All",
    "activity_type": "All",
    "remote_worker": "N",
    "company_code": "All",
    "business_segment": "All",
    "title": ["All Except", "Young Apprentice", "Intern"],
    "Department": "All",
    "pay_scale_group": "All",
    "job_level": "All",
    "reg_temp": "Regular",
    "pay_type": "Salaried",
    "full_part": "Full-Time",
    "ot_eligible": "Yes",
    "employee_type": "[BRA] Regulars OT Eligible",
    "punch_policy": "[BRA] Punch Policy",
    "timesheet_template": "BRA_Punch_Timesheet_Office",
    "timesheet_approval_path": "Supervisor",
    "timesheet_period": "BRA - Weekly starting on Monday",
    "time_off_template": "Time Off",
    "time_off_approver": "Supervisor",
    "schedule_type": "Shift Schedule",
    "schedule_policy": "Default Shift Schedule Policy",
    "holiday_calendar": "Brazil",
    "timezone": "(UTC-3:00) E. South America Standard Time",
    "work_week": "Monday to Sunday",
    "payrule_name": "[BRA] FT OT Eligible"
  },
  {
    "location_level_1": "BRA",
    "location_level_2": "All",
    "location_level_3": "All",
    "activity_type": "All",
    "remote_worker": "N",
    "company_code": "All",
    "business_segment": "All",
    "title": "Young Apprentice",
    "Department": "All",
    "pay_scale_group": "All",
    "job_level": "All",
    "reg_temp": "Temporary",
    "pay_type": "Salaried",
    "full_part": "Part-Time",
    "ot_eligible": "No",
    "employee_type": "[BRA] Young Apprentice",
    "punch_policy": "[BRA] Punch Policy",
    "timesheet_template": "BRA_Punch_Timesheet_Office",
    "timesheet_approval_path": "Supervisor",
    "timesheet_period": "BRA - Weekly starting on Monday",
    "time_off_template": "Time Off",
    "time_off_approver": "Supervisor",
    "schedule_type": "Shift Schedule",
    "schedule_policy": "Default Shift Schedule Policy",
    "holiday_calendar": "Brazil",
    "timezone": "(UTC-3:00) E. South America Standard Time",
    "work_week": "Monday to Sunday",
    "payrule_name": "[BRA] PT"
  },
  {
    "location_level_1": "BRA",
    "location_level_2": "All",
    "location_level_3": "All",
    "activity_type": "All",
    "remote_worker": "N",
    "company_code": "All",
    "business_segment": "All",
    "title": "Intern",
    "Department": "All",
    "pay_scale_group": "All",
    "job_level": "All",
    "reg_temp": "Temporary",
    "pay_type": "Salaried",
    "full_part": "Part-Time",
    "ot_eligible": "No",
    "employee_type": "[BRA] Interns",
    "punch_policy": "[BRA] Punch Policy",
    "timesheet_template": "BRA_Punch_Timesheet_Office",
    "timesheet_approval_path": "Supervisor",
    "timesheet_period": "BRA - Weekly starting on Monday",
    "time_off_template": "Time Off",
    "time_off_approver": "Supervisor",
    "schedule_type": "Shift Schedule",
    "schedule_policy": "Default Shift Schedule Policy",
    "holiday_calendar": "Brazil",
    "timezone": "(UTC-3:00) E. South America Standard Time",
    "work_week": "Monday to Sunday",
    "payrule_name": "[BRA] PT"
  }
]