region = 'eu-central-1'
environment = 'production'
instance = "prod"
company_key = 'GEVernova'
replicon_conn_id = 'GEVernova_replicon_admin'
pgp_conn_id = 'GEVernova_User_Import_PGP'
can_run_batch_task_var_name = f'GEVernova_user_import_can_run_batch_task_{instance}'
sftp_conn_id = "GEVernova_sftp_li013214sd-REPLICON"
internal_sftp_conn_id = "GEVernova_sftp_587719"
input_filepath = "/EUROPE/GREECE/WORKDAY/PROD/FROMGE"
archive_filepath = "/EUROPE/GREECE/WORKDAY/PROD/FROMGE/ARCHIVE"
internal_archive_filepath = "/User Sync/Greece/Daily Files"
log_filepath = "/User Sync/Greece/Logs"
execution_timeout_days = 14
child_dag_max_active_runs = 2
master_dag_interval = 600
tenant_email = "Alaina.Larkin1@gevernova.com"
internal_logs_email = '{{ var.value.dagrun_internal_log_email }}'
alert_email = '{{ var.value.dagrun_failure_alert_email }}'
pacific_timezone = 'US/Pacific'
