region = 'eu-central-1'
environment = 'pre-production'
instance = "getrial01"
company_key = 'getrial01'
replicon_conn_id = 'getrial01_User_Import'
pgp_conn_id = 'getrial01_User_Import_PGP'
can_run_batch_task_var_name = f'ge_user_import_can_run_batch_task_{instance}'
sftp_conn_id = "getrial01_sftp_lg790231sd"
internal_sftp_conn_id = "getrial01_sftp_587719"
input_filepath = "/EUROPE/NETHERLANDS/WORKDAY/TEST/FROMGE"
archive_filepath = "/EUROPE/NETHERLANDS/WORKDAY/TEST/FROMGE/ARCHIVE"
internal_archive_filepath = "/TRIAL/User Sync/Netherlands/Daily Files"
log_filepath = "/TRIAL/User Sync/Netherlands/Logs"
execution_timeout_days = 14
child_dag_max_active_runs = 2
master_dag_interval = 30
tenant_email = "ashashingte@deltek.com"
internal_logs_email = '{{ var.value.dagrun_internal_testing_email }}'
alert_email = '{{ var.value.dagrun_failure_alert_email }}'
pacific_timezone = 'US/Pacific'
disabled = True