region = 'us-east-1'
environment = 'production'
instance = "genoadesign"
company_key = 'genoadesign'
replicon_conn_id = 'genoadesign-prod-admin1'
can_run_batch_task_var_name = f'GenoaDesign_user_import_can_run_batch_task_{instance}'
sftp_conn_id = "genoadesign_sftp_prod"
input_filepath = "/"
archive_filepath = "/archive"
referance_filepath = "/reference"
log_filepath = "/logs"
execution_timeout_days = 14
child_dag_max_active_runs = 2
master_dag_interval = 30
tenant_email = "mrideout@genoadesign.com"
internal_logs_email = '{{ var.value.dagrun_internal_log_email }}'
alert_email = '{{ var.value.dagrun_failure_alert_email }}'
pacific_timezone = 'US/Pacific'
