region = 'us-east-2'
environment = 'pre-production'
company_key = 'dxctrial01'
replicon_conn_id = 'dxctrial01'
sftp_conn_id = 'dxcafmig_replicon_sftp'
input_filepath = '/DXCAFMG/Inbound/COMPASSWBSMaster/PJ1/Input'
processing_file_directory = '/DXCAFMG/Inbound/COMPASSWBSMaster/PJ1/Processing'
archive_filepath = '/DXCAFMG/Inbound/COMPASSWBSMaster/PJ1/Archive'
log_filepath = '/DXCAFMG/Inbound/COMPASSWBSMaster/PJ1/Logs'
alert_email = '{{ var.value.dagrun_failure_alert_email }}'
schedule_interval_daily = '*/30 * * * *'
dag_max_active_tasks = 128
execution_timeout_days = 14
master_dag_max_active_runs = 1
child_dag_max_active_runs = 10
file_merge_count = "DXC_CompassWBS_file_merge_count"
# pylint: disable=line-too-long
error_template = '{{ get_error_message() }}'
