region = 'us-east-1'
environment = 'pre-production'
instance = "cpp"
company_key = 'cpp'
replicon_conn_id = 'polaris_cpp'
polaris_conn_id='polaris_cpp'
deltek_cospoint_conn_id = 'deltek_costpoint_cpp_basic'
last_run_date_var_name = f'{company_key}_deltek_costpoint_resource_assignment_export_sync_last_run_date'
time_zone = 'US/Eastern'
execution_timeout_days = 14
child_dag_max_active_runs = 2
can_run_batch_task_var_name = f'cospoint_resource_assignment_export_can_run_batch_task_{instance}'
group_by_project_var_name = f'cospoint_resource_assignment_export_group_by_project_{instance}'
pay_type_oef_var_name = f'cospoint_resource_assignment_export_pay_type_oef_name_{instance}'
tenant_email = 'MPTeamReplicon@deltek.com'
internal_email = 'MPTeamReplicon@deltek.com'
cp_polaris_resource_assignment_webhook_secret = 'cpp_polaris_resource_assignment_webhook_secret' #f'cp_polaris_resource_assignment_webhook_secret_{instance}'
cp_project_polaris_teamMember_allocation = "cpp_project_polaris_teamMember_allocation_ra"
schedule_interval = "*/1 * * * *"
master_dag_interval = 3000
