user_import_mapper = [
    {
        "location_level_1": "USA",
        "location_level_2": "All",
        "location_level_3": ["FRDRKPAI","DURHAMPAI","DURHAMPAIW","SKOKIEPAI"],
        "buisness_unit_level_2": ["All Except", "NA04", "NA05"],
        "department_grp_lvl_2": "All",
        "reg_temp": "Regular",
        "pay_type": "Salaried",
        "us_flsa_status": "N",
        "activity_type": "Populated",
        "timesheet_template": "US_PAI_SAL_PROJ",
        "payrule_name": "US_SAL",
        "rms_payrule_name": "US_SAL",
        "punch_policy": "NA",
        "timesheet_period": "US - Weekly starting on Sunday",
        "timesheet_approval_path": "Supervisor",
        "time_off_template": "Time Off",
        "time_off_approver": "Supervisor",
        "work_week": "Sunday to Saturday"
    },
    {
        "location_level_1": "USA",
        "location_level_2": "All",
        "location_level_3": ["All Except", "FRDRKPAI", "DURHAMPAI", "DURHAMPAIW", "SKOKIEPAI"],
        "buisness_unit_level_2": ["All Except", "NA04", "NA05"],
        "department_grp_lvl_2": "All",
        "reg_temp": "Regular",
        "pay_type": "Salaried",
        "us_flsa_status": "N",
        "activity_type": "Populated",
        "timesheet_template": "US_SAL_PROJ",
        "payrule_name": "US_SAL",
        "rms_payrule_name": "US_SAL",
        "punch_policy": "NA",
        "timesheet_period": "US - Weekly starting on Sunday",
        "timesheet_approval_path": "Supervisor",
        "time_off_template": "Time Off",
        "time_off_approver": "Supervisor",
        "work_week": "Sunday to Saturday"
    },
    {
        "location_level_1": "USA",
        "location_level_2": "All",
        "location_level_3": ["All Except", "FRDRKPAI", "DURHAMPAI", "DURHAMPAIW", "SKOKIEPAI"],
        "buisness_unit_level_2": "NA04",
        "department_grp_lvl_2": "All",
        "reg_temp": "Regular",
        "pay_type": "Exception Hourly",
        "us_flsa_status": "E",
        "activity_type": "Blank",
        "timesheet_template": "US_SAL_OT",
        "payrule_name": "US_SAL_OT_IS",
        "rms_payrule_name": "US_SAL_OT_IS",
        "punch_policy": "NA",
        "timesheet_period": "US - Weekly starting on Sunday",
        "timesheet_approval_path": "Supervisor - Exception time",
        "time_off_template": "Time Off",
        "time_off_approver": "Supervisor",
        "work_week": "Sunday to Saturday"
    },
    {
        "location_level_1": "USA",
        "location_level_2": "All",
        "location_level_3": ["FRDRKPAI","DURHAMPAI","DURHAMPAIW","SKOKIEPAI"],
        "buisness_unit_level_2": ["All Except", "NA04", "NA05"],
        "department_grp_lvl_2": "All",
        "reg_temp": "Regular",
        "pay_type": "Exception Hourly",
        "us_flsa_status": "E",
        "activity_type": "Blank",
        "timesheet_template": "US_SAL_OT",
        "payrule_name": "US_SAL_Exception HRLY",
        "rms_payrule_name": "US_SAL_Exception HRLY",
        "punch_policy": "NA",
        "timesheet_period": "US - Weekly starting on Sunday",
        "timesheet_approval_path": "Supervisor - Exception time",
        "time_off_template": "Time Off",
        "time_off_approver": "Supervisor",
        "work_week": "Sunday to Saturday"
    },
    {
        "location_level_1": "USA",
        "location_level_2": "All",
        "location_level_3": ["All Except", "FRDRKPAI", "DURHAMPAI", "DURHAMPAIW", "SKOKIEPAI"],
        "buisness_unit_level_2": ["All Except", "NA04", "NA05"],
        "department_grp_lvl_2": "All",
        "reg_temp": "Regular",
        "pay_type": "Exception Hourly",
        "us_flsa_status": "E",
        "activity_type": "Blank",
        "timesheet_template": "US_SAL_OT",
        "payrule_name": "US_SAL_Exception HRLY",
        "rms_payrule_name": "US_SAL_Exception HRLY",
        "punch_policy": "NA",
        "timesheet_period": "US - Weekly starting on Sunday",
        "timesheet_approval_path": "Supervisor - Exception time",
        "time_off_template": "Time Off",
        "time_off_approver": "Supervisor",
        "work_week": "Sunday to Saturday"
    },
    {
        "location_level_1": "USA",
        "location_level_2": "All",
        "location_level_3": ["All Except", "FRDRKPAI", "DURHAMPAI", "DURHAMPAIW", "SKOKIEPAI"],
        "buisness_unit_level_2": "NA04",
        "department_grp_lvl_2": "All",
        "reg_temp": "Regular",
        "pay_type": "Exception Hourly",
        "us_flsa_status": "E",
        "activity_type": "Populated",
        "timesheet_template": "US_SAL_OT_IS_PROJ",
        "payrule_name": "US_SAL_OT_IS",
        "rms_payrule_name": "US_SAL_OT_IS",
        "punch_policy": "NA",
        "timesheet_period": "US - Weekly starting on Sunday",
        "timesheet_approval_path": "Supervisor - Exception time",
        "time_off_template": "Time Off",
        "time_off_approver": "Supervisor",
        "work_week": "Sunday to Saturday"
    },
    {
        "location_level_1": "USA",
        "location_level_2": "All",
        "location_level_3": ["FRDRKPAI","DURHAMPAI","DURHAMPAIW","SKOKIEPAI"],
        "buisness_unit_level_2": ["All Except", "NA04", "NA05"],
        "department_grp_lvl_2": "All",
        "reg_temp": "Regular",
        "pay_type": "Exception Hourly",
        "us_flsa_status": "E",
        "activity_type": "Populated",
        "timesheet_template": "US_PAI_SAL_PROJ",
        "payrule_name": "US_SAL_Exception HRLY",
        "rms_payrule_name": "US_SAL_Exception HRLY",
        "punch_policy": "NA",
        "timesheet_period": "US - Weekly starting on Sunday",
        "timesheet_approval_path": "Supervisor - Exception time",
        "time_off_template": "Time Off",
        "time_off_approver": "Supervisor",
        "work_week": "Sunday to Saturday"
    },
    {
        "location_level_1": "USA",
        "location_level_2": "All",
        "location_level_3": ["All Except", "FRDRKPAI", "DURHAMPAI", "DURHAMPAIW", "SKOKIEPAI"],
        "buisness_unit_level_2": ["All Except", "NA04", "NA05"],
        "department_grp_lvl_2": "All",
        "reg_temp": "Regular",
        "pay_type": "Exception Hourly",
        "us_flsa_status": "E",
        "activity_type": "Populated",
        "timesheet_template": "US_SAL_PROJ",
        "payrule_name": "US_SAL_Exception HRLY",
        "rms_payrule_name": "US_SAL_Exception HRLY",
        "punch_policy": "NA",
        "timesheet_period": "US - Weekly starting on Sunday",
        "timesheet_approval_path": "Supervisor - Exception time",
        "time_off_template": "Time Off",
        "time_off_approver": "Supervisor",
        "work_week": "Sunday to Saturday"
    },
    {
        "location_level_1": "USA",
        "location_level_2": "All",
        "location_level_3": ["FRDRKPAI","DURHAMPAI","DURHAMPAIW","SKOKIEPAI"],
        "buisness_unit_level_2": "All",
        "department_grp_lvl_2": ["All Except", "LARC08", "LARC10", "LARC4", "LARC9", "LARC-CRT", "NIA",
            "NIAID", "NIAID HAMILTON", "NIAID Poolesville", "NIAID ROCKVL"],
        "reg_temp": ["Regular", "Temporary"],
        "pay_type": "Hourly",
        "us_flsa_status": "N",
        "activity_type": "Blank",
        "timesheet_template": "US_HRLY",
        "payrule_name": "US_HRLY",
        "rms_payrule_name": "US_HRLY_RMS",
        "punch_policy": "US_HRLY_Group",
        "timesheet_period": "US - Weekly starting on Sunday",
        "timesheet_approval_path": "Supervisor",
        "time_off_template": "Time Off",
        "time_off_approver": "Supervisor",
        "work_week": "Sunday to Saturday"
    },
    {
        "location_level_1": "USA",
        "location_level_2": "California",
        "location_level_3": "All",
        "buisness_unit_level_2": ["All Except", "NA06"],
        "department_grp_lvl_2": ["All Except", "LARC08", "LARC10", "LARC4", "LARC9", "LARC-CRT", "NIA",
            "NIAID", "NIAID HAMILTON", "NIAID Poolesville", "NIAID ROCKVL"],
        "reg_temp": ["Regular", "Temporary"],
        "pay_type": "Hourly",
        "us_flsa_status": "N",
        "activity_type": "Blank",
        "timesheet_template": "US_CAL_HRLY",
        "payrule_name": "US_HRLY_CAL",
        "rms_payrule_name": "US_HRLY_CAL_RMS",
        "punch_policy": "US_California_Hrly",
        "timesheet_period": "US - Weekly starting on Sunday",
        "timesheet_approval_path": "Supervisor",
        "time_off_template": "Time Off",
        "time_off_approver": "Supervisor",
        "work_week": "Sunday to Saturday"
    },
    {
        "location_level_1": "USA",
        "location_level_2": ["All Except", "California", "Colorado", "Nevada", "Rhode Island"],
        "location_level_3": "All",
        "buisness_unit_level_2": ["All Except", "NA06"],
        "department_grp_lvl_2": ["All Except", "LARC08", "LARC10", "LARC4", "LARC9", "LARC-CRT", "NIA",
            "NIAID", "NIAID HAMILTON", "NIAID Poolesville", "NIAID ROCKVL"],
        "reg_temp": ["Regular", "Temporary"],
        "pay_type": "Hourly",
        "us_flsa_status": ["N","E"],
        "activity_type": "Blank",
        "timesheet_template": "US_HRLY",
        "payrule_name": "US_HRLY",
        "rms_payrule_name": "US_HRLY_RMS",
        "punch_policy": "US_HRLY_Group",
        "timesheet_period": "US - Weekly starting on Sunday",
        "timesheet_approval_path": "Supervisor",
        "time_off_template": "Time Off",
        "time_off_approver": "Supervisor",
        "work_week": "Sunday to Saturday"
    },
    {
        "location_level_1": "USA",
        "location_level_2": "Colorado",
        "location_level_3": "All",
        "buisness_unit_level_2": ["All Except", "NA06"],
        "department_grp_lvl_2": ["All Except", "LARC08", "LARC10", "LARC4", "LARC9", "LARC-CRT", "NIA",
            "NIAID", "NIAID HAMILTON", "NIAID Poolesville", "NIAID ROCKVL"],
        "reg_temp": ["Regular", "Temporary"],
        "pay_type": "Hourly",
        "us_flsa_status": "N",
        "activity_type": "Blank",
        "timesheet_template": "US_COL_HRLY",
        "payrule_name": "US_HRLY_COL",
        "rms_payrule_name": "US_HRLY_COL_RMS",
        "punch_policy": "US_HRLY_Group",
        "timesheet_period": "US - Weekly starting on Sunday",
        "timesheet_approval_path": "Supervisor",
        "time_off_template": "Time Off",
        "time_off_approver": "Supervisor",
        "work_week": "Sunday to Saturday"
    },
    {
        "location_level_1": "USA",
        "location_level_2": "Nevada",
        "location_level_3": "All",
        "buisness_unit_level_2": ["All Except", "NA06"],
        "department_grp_lvl_2": ["All Except", "LARC08", "LARC10", "LARC4", "LARC9", "LARC-CRT", "NIA",
            "NIAID", "NIAID HAMILTON", "NIAID Poolesville", "NIAID ROCKVL"],
        "reg_temp": ["Regular", "Temporary"],
        "pay_type": "Hourly",
        "us_flsa_status": "N",
        "activity_type": "Blank",
        "timesheet_template": "US_NV_HRLY",
        "payrule_name": "US_HRLY_NV",
        "rms_payrule_name": "US_HRLY_NV_RMS",
        "punch_policy": "US_HRLY_Group",
        "timesheet_period": "US - Weekly starting on Sunday",
        "timesheet_approval_path": "Supervisor",
        "time_off_template": "Time Off",
        "time_off_approver": "Supervisor",
        "work_week": "Sunday to Saturday"
    },
    {
        "location_level_1": "USA",
        "location_level_2": "Rhode Island",
        "location_level_3": "All",
        "buisness_unit_level_2": ["All Except", "NA06"],
        "department_grp_lvl_2": ["All Except", "LARC08", "LARC10", "LARC4", "LARC9", "LARC-CRT", "NIA",
            "NIAID", "NIAID HAMILTON", "NIAID Poolesville", "NIAID ROCKVL"],
        "reg_temp": ["Regular", "Temporary"],
        "pay_type": "Hourly",
        "us_flsa_status": "N",
        "activity_type": "Blank",
        "timesheet_template": "US_RI_HRLY",
        "payrule_name": "US_HRLY_RI",
        "rms_payrule_name": "US_HRLY_RI_RMS",
        "punch_policy": "US_HRLY_Group",
        "timesheet_period": "US - Weekly starting on Sunday",
        "timesheet_approval_path": "Supervisor",
        "time_off_template": "Time Off",
        "time_off_approver": "Supervisor",
        "work_week": "Sunday to Saturday"
    },
    {
        "location_level_1": "USA",
        "location_level_2": "Colorado",
        "location_level_3": ["All Except", "FRDRKPAI", "DURHAMPAI", "DURHAMPAIW", "SKOKIEPAI"],
        "buisness_unit_level_2": "NA04",
        "department_grp_lvl_2": ["All Except", "LARC08", "LARC10", "LARC4", "LARC9", "LARC-CRT", "NIA",
            "NIAID", "NIAID HAMILTON", "NIAID Poolesville", "NIAID ROCKVL"],
        "reg_temp": ["Regular", "Temporary"],
        "pay_type": "Hourly",
        "us_flsa_status": "N",
        "activity_type": "Populated",
        "timesheet_template": "US_IS_CO_HRLY_PROJ",
        "payrule_name": "US_HRLY_COL_IS",
        "rms_payrule_name": "US_HRLY_COL_IS_RMS",
        "punch_policy": "US_HRLY_IS",
        "timesheet_period": "US - Weekly starting on Sunday",
        "timesheet_approval_path": "Supervisor",
        "time_off_template": "Time Off",
        "time_off_approver": "Supervisor",
        "work_week": "Sunday to Saturday"
    },
    {
        "location_level_1": "USA",
        "location_level_2": "Nevada",
        "location_level_3": ["All Except", "FRDRKPAI", "DURHAMPAI", "DURHAMPAIW", "SKOKIEPAI"],
        "buisness_unit_level_2": "NA04",
        "department_grp_lvl_2": ["All Except", "LARC08", "LARC10", "LARC4", "LARC9", "LARC-CRT", "NIA",
            "NIAID", "NIAID HAMILTON", "NIAID Poolesville", "NIAID ROCKVL"],
        "reg_temp": ["Regular", "Temporary"],
        "pay_type": "Hourly",
        "us_flsa_status": "N",
        "activity_type": "Populated",
        "timesheet_template": "US_IS_NV_HRLY_PROJ",
        "payrule_name": "US_HRLY_NV_IS",
        "rms_payrule_name": "US_HRLY_NV_IS_RMS",
        "punch_policy": "US_HRLY_IS",
        "timesheet_period": "US - Weekly starting on Sunday",
        "timesheet_approval_path": "Supervisor",
        "time_off_template": "Time Off",
        "time_off_approver": "Supervisor",
        "work_week": "Sunday to Saturday"
    },
    {
        "location_level_1": "USA",
        "location_level_2": "Rhode Island",
        "location_level_3": ["All Except", "FRDRKPAI", "DURHAMPAI", "DURHAMPAIW", "SKOKIEPAI"],
        "buisness_unit_level_2": "NA04",
        "department_grp_lvl_2": ["All Except", "LARC08", "LARC10", "LARC4", "LARC9", "LARC-CRT", "NIA",
            "NIAID", "NIAID HAMILTON", "NIAID Poolesville", "NIAID ROCKVL"],
        "reg_temp": ["Regular", "Temporary"],
        "pay_type": "Hourly",
        "us_flsa_status": "N",
        "activity_type": "Populated",
        "timesheet_template": "US_IS_RI_HRLY_PROJ",
        "payrule_name": "US_HRLY_RI_IS",
        "rms_payrule_name": "US_HRLY_RI_IS_RMS",
        "punch_policy": "US_HRLY_IS",
        "timesheet_period": "US - Weekly starting on Sunday",
        "timesheet_approval_path": "Supervisor",
        "time_off_template": "Time Off",
        "time_off_approver": "Supervisor",
        "work_week": "Sunday to Saturday"
    },
    {
        "location_level_1": "USA",
        "location_level_2": ["All Except", "California", "Colorado", "Nevada", "Rhode Island"],
        "location_level_3": "All",
        "buisness_unit_level_2": "NA06",
        "department_grp_lvl_2": ["All Except", "LARC08", "LARC10", "LARC4", "LARC9", "LARC-CRT", "NIA",
            "NIAID", "NIAID HAMILTON", "NIAID Poolesville", "NIAID ROCKVL"],
        "reg_temp": ["Regular", "Temporary"],
        "pay_type": "Hourly",
        "us_flsa_status": "N",
        "activity_type": "Blank",
        "timesheet_template": "US_HRLY",
        "payrule_name": "US_HRLY_NA06",
        "rms_payrule_name": "US_HRLY_NA06_RMS",
        "punch_policy": "US_HRLY_Group",
        "timesheet_period": "US - Weekly starting on Sunday",
        "timesheet_approval_path": "Supervisor",
        "time_off_template": "Time Off",
        "time_off_approver": "Supervisor",
        "work_week": "Sunday to Saturday"
    },
    {
        "location_level_1": "USA",
        "location_level_2": ["All Except", "California", "Colorado", "Nevada", "Rhode Island"],
        "location_level_3": ["FRDRKPAI","DURHAMPAI","DURHAMPAIW","SKOKIEPAI"],
        "buisness_unit_level_2": "NA05",
        "department_grp_lvl_2": ["LARC08", "LARC10", "LARC4", "LARC9", "LARC-CRT", "NIA", "NIAID", "NIAID HAMILTON", "NIAID Poolesville", "NIAID ROCKVL"],
        "reg_temp": ["Regular", "Temporary"],
        "pay_type": "Hourly",
        "us_flsa_status": "N",
        "activity_type": "Blank",
        "timesheet_template": "US_HRLY_NA05",
        "payrule_name": "US_HRLY_NA05_4%",
        "rms_payrule_name": "US_HRLY_NA05_4%_RMS",
        "punch_policy": "US_HRLY_IS",
        "timesheet_period": "US - Weekly starting on Sunday",
        "timesheet_approval_path": "Supervisor",
        "time_off_template": "Time Off",
        "time_off_approver": "Supervisor",
        "work_week": "Sunday to Saturday"
    },
    {
        "location_level_1": "USA",
        "location_level_2": ["All Except", "California", "Colorado", "Nevada", "Rhode Island"],
        "location_level_3": ["All Except", "FRDRKPAI", "DURHAMPAI", "DURHAMPAIW", "SKOKIEPAI"],
        "buisness_unit_level_2": "NA05",
        "department_grp_lvl_2": ["All Except", "LARC08", "LARC10", "LARC4", "LARC9", "LARC-CRT", "NIA",
            "NIAID", "NIAID HAMILTON", "NIAID Poolesville", "NIAID ROCKVL"],
        "reg_temp": ["Regular", "Temporary"],
        "pay_type": "Hourly",
        "us_flsa_status": "N",
        "activity_type": "Populated",
        "timesheet_template": "US_IS_NA05_HRLY_PROJ",
        "payrule_name": "US_HRLY_NA05",
        "rms_payrule_name": "US_HRLY_NA05_RMS",
        "punch_policy": "US_IS_HRLY_NA05",
        "timesheet_period": "US - Weekly starting on Sunday",
        "timesheet_approval_path": "Supervisor",
        "time_off_template": "Time Off",
        "time_off_approver": "Supervisor",
        "work_week": "Sunday to Saturday"
    },
    {
        "location_level_1": "USA",
        "location_level_2": "Colorado",
        "location_level_3": ["All Except", "FRDRKPAI", "DURHAMPAI", "DURHAMPAIW", "SKOKIEPAI"],
        "buisness_unit_level_2": "NA05",
        "department_grp_lvl_2": ["All Except", "LARC08", "LARC10", "LARC4", "LARC9", "LARC-CRT", "NIA",
            "NIAID", "NIAID HAMILTON", "NIAID Poolesville", "NIAID ROCKVL"],
        "reg_temp": ["Regular", "Temporary"],
        "pay_type": "Hourly",
        "us_flsa_status": "N",
        "activity_type": "Populated",
        "timesheet_template": "US_IS_CO_HRLY_PROJ",
        "payrule_name": "US_HRLY_COL_NA05",
        "rms_payrule_name": "US_HRLY_COL_NA05_RMS",
        "punch_policy": "US_IS_HRLY_NA05",
        "timesheet_period": "US - Weekly starting on Sunday",
        "timesheet_approval_path": "Supervisor",
        "time_off_template": "Time Off",
        "time_off_approver": "Supervisor",
        "work_week": "Sunday to Saturday"
    },
    {
        "location_level_1": "USA",
        "location_level_2": "Nevada",
        "location_level_3": ["All Except", "FRDRKPAI", "DURHAMPAI", "DURHAMPAIW", "SKOKIEPAI"],
        "buisness_unit_level_2": "NA05",
        "department_grp_lvl_2": ["All Except", "LARC08", "LARC10", "LARC4", "LARC9", "LARC-CRT", "NIA",
            "NIAID", "NIAID HAMILTON", "NIAID Poolesville", "NIAID ROCKVL"],
        "reg_temp": ["Regular", "Temporary"],
        "pay_type": "Hourly",
        "us_flsa_status": "N",
        "activity_type": "Populated",
        "timesheet_template": "US_IS_NV_HRLY_PROJ",
        "payrule_name": "US_HRLY_NV_NA05",
        "rms_payrule_name": "US_HRLY_NV_NA05_RMS",
        "punch_policy": "US_HRLY_IS",
        "timesheet_period": "US - Weekly starting on Sunday",
        "timesheet_approval_path": "Supervisor",
        "time_off_template": "Time Off",
        "time_off_approver": "Supervisor",
        "work_week": "Sunday to Saturday"
    },
    {
        "location_level_1": "USA",
        "location_level_2": "Colorado",
        "location_level_3": ["All Except", "FRDRKPAI", "DURHAMPAI", "DURHAMPAIW", "SKOKIEPAI"],
        "buisness_unit_level_2": "NA05",
        "department_grp_lvl_2": ["LARC08", "LARC10", "LARC4", "LARC9", "LARC-CRT", "NIA", "NIAID", "NIAID HAMILTON", "NIAID Poolesville", "NIAID ROCKVL"],
        "reg_temp": ["Regular", "Temporary"],
        "pay_type": "Hourly",
        "us_flsa_status": "N",
        "activity_type": "Populated",
        "timesheet_template": "US_IS_NA05_CO_HRLY_4%",
        "payrule_name": "US_HRLY_COL_NA05_4%",
        "rms_payrule_name": "US_HRLY_COL_NA05_4%_RMS",
        "punch_policy": "US_HRLY_IS",
        "timesheet_period": "US - Weekly starting on Sunday",
        "timesheet_approval_path": "Supervisor",
        "time_off_template": "Time Off",
        "time_off_approver": "Supervisor",
        "work_week": "Sunday to Saturday"
    },
    {
        "location_level_1": "USA",
        "location_level_2": "Nevada",
        "location_level_3": ["All Except", "FRDRKPAI", "DURHAMPAI", "DURHAMPAIW", "SKOKIEPAI"],
        "buisness_unit_level_2": "NA05",
        "department_grp_lvl_2": ["LARC08", "LARC10", "LARC4", "LARC9", "LARC-CRT", "NIA", "NIAID", "NIAID HAMILTON", "NIAID Poolesville", "NIAID ROCKVL"],
        "reg_temp": ["Regular", "Temporary"],
        "pay_type": "Hourly",
        "us_flsa_status": "N",
        "activity_type": "Populated",
        "timesheet_template": "US_IS_NV_HRLY_PROJ_4%",
        "payrule_name": "US_HRLY_NV_NA05_4%",
        "rms_payrule_name": "US_HRLY_NV_NA05_4%_RMS",
        "punch_policy": "US_HRLY_IS_NA05",
        "timesheet_period": "US - Weekly starting on Sunday",
        "timesheet_approval_path": "Supervisor",
        "time_off_template": "Time Off",
        "time_off_approver": "Supervisor",
        "work_week": "Sunday to Saturday"
    },
    {
        "location_level_1": "USA",
        "location_level_2": "Rhode Island",
        "location_level_3": ["All Except", "FRDRKPAI", "DURHAMPAI", "DURHAMPAIW", "SKOKIEPAI"],
        "buisness_unit_level_2": "NA05",
        "department_grp_lvl_2": ["LARC08", "LARC10", "LARC4", "LARC9", "LARC-CRT", "NIA", "NIAID", "NIAID HAMILTON", "NIAID Poolesville", "NIAID ROCKVL"],
        "reg_temp": ["Regular", "Temporary"],
        "pay_type": "Hourly",
        "us_flsa_status": "N",
        "activity_type": "Populated",
        "timesheet_template": "US_IS_NA05_RI_HRLY_PROJ_4%",
        "payrule_name": "US_HRLY_RI_NA05_4%",
        "rms_payrule_name": "US_HRLY_RI_NA05_4%_RMS",
        "punch_policy": "US_HRLY_IS_NA05",
        "timesheet_period": "US - Weekly starting on Sunday",
        "timesheet_approval_path": "Supervisor",
        "time_off_template": "Time Off",
        "time_off_approver": "Supervisor",
        "work_week": "Sunday to Saturday"
    },
    {
        "location_level_1": "USA",
        "location_level_2": "Colorado",
        "location_level_3": ["All Except", "FRDRKPAI", "DURHAMPAI", "DURHAMPAIW", "SKOKIEPAI"],
        "buisness_unit_level_2": "NA05",
        "department_grp_lvl_2": ["LARC08", "LARC10", "LARC4", "LARC9", "LARC-CRT", "NIA", "NIAID", "NIAID HAMILTON", "NIAID Poolesville", "NIAID ROCKVL"],
        "reg_temp": ["Regular", "Temporary"],
        "pay_type": "Hourly",
        "us_flsa_status": "N",
        "activity_type": "Blank",
        "timesheet_template": "US_IS_NA05_CO_HRLY_4%",
        "payrule_name": "US_HRLY_COL_NA05_4%",
        "rms_payrule_name": "US_HRLY_COL_NA05_4%_RMS",
        "punch_policy": "US_CAL_HRLY_IS",
        "timesheet_period": "US - Weekly starting on Sunday",
        "timesheet_approval_path": "Supervisor",
        "time_off_template": "Time Off",
        "time_off_approver": "Supervisor",
        "work_week": "Sunday to Saturday"
    },
    {
        "location_level_1": "USA",
        "location_level_2": "Nevada",
        "location_level_3": ["All Except", "FRDRKPAI", "DURHAMPAI", "DURHAMPAIW", "SKOKIEPAI"],
        "buisness_unit_level_2": "NA05",
        "department_grp_lvl_2": ["LARC08", "LARC10", "LARC4", "LARC9", "LARC-CRT", "NIA", "NIAID", "NIAID HAMILTON", "NIAID Poolesville", "NIAID ROCKVL"],
        "reg_temp": ["Regular", "Temporary"],
        "pay_type": "Hourly",
        "us_flsa_status": "N",
        "activity_type": "Blank",
        "timesheet_template": "US_IS_NV_HRLY",
        "payrule_name": "US_HRLY_NV_NA05_4%",
        "rms_payrule_name": "US_HRLY_NV_NA05_4%_RMS",
        "punch_policy": "US_HRLY_IS_NA05",
        "timesheet_period": "US - Weekly starting on Sunday",
        "timesheet_approval_path": "Supervisor",
        "time_off_template": "Time Off",
        "time_off_approver": "Supervisor",
        "work_week": "Sunday to Saturday"
    },
    {
        "location_level_1": "USA",
        "location_level_2": "Rhode Island",
        "location_level_3": ["All Except", "FRDRKPAI", "DURHAMPAI", "DURHAMPAIW", "SKOKIEPAI"],
        "buisness_unit_level_2": "NA05",
        "department_grp_lvl_2": ["LARC08", "LARC10", "LARC4", "LARC9", "LARC-CRT", "NIA", "NIAID", "NIAID HAMILTON", "NIAID Poolesville", "NIAID ROCKVL"],
        "reg_temp": ["Regular", "Temporary"],
        "pay_type": "Hourly",
        "us_flsa_status": "N",
        "activity_type": "Blank",
        "timesheet_template": "US_IS_NA05_RI_HRLY",
        "payrule_name": "US_HRLY_RI_NA05_4%",
        "rms_payrule_name": "US_HRLY_RI_NA05_4%_RMS",
        "punch_policy": "US_HRLY_IS_NA05",
        "timesheet_period": "US - Weekly starting on Sunday",
        "timesheet_approval_path": "Supervisor",
        "time_off_template": "Time Off",
        "time_off_approver": "Supervisor",
        "work_week": "Sunday to Saturday"
    },
    {
        "location_level_1": "USA",
        "location_level_2": "All",
        "location_level_3": ["All Except", "FRDRKPAI", "DURHAMPAI", "DURHAMPAIW", "SKOKIEPAI"],
        "buisness_unit_level_2": "NA05",
        "department_grp_lvl_2": "All",
        "reg_temp": "Regular",
        "pay_type": "Exception Hourly",
        "us_flsa_status": "E",
        "activity_type": "Blank",
        "timesheet_template": "US_SAL_OT",
        "payrule_name": "US_SAL_OT_IS",
        "rms_payrule_name": "US_SAL_OT_IS",
        "punch_policy": "NA",
        "timesheet_period": "US - Weekly starting on Sunday",
        "timesheet_approval_path": "Supervisor - Exception time",
        "time_off_template": "Time Off",
        "time_off_approver": "Supervisor",
        "work_week": "Sunday to Saturday"
    },
    {
        "location_level_1": "USA",
        "location_level_2": "All",
        "location_level_3": ["All Except", "FRDRKPAI", "DURHAMPAI", "DURHAMPAIW", "SKOKIEPAI"],
        "buisness_unit_level_2": "NA05",
        "department_grp_lvl_2": "All",
        "reg_temp": "Regular",
        "pay_type": "Exception Hourly",
        "us_flsa_status": "E",
        "activity_type": "Populated",
        "timesheet_template": "US_SAL_OT_IS_PROJ_NA05",
        "payrule_name": "US_SAL_OT_IS",
        "rms_payrule_name": "US_SAL_OT_IS",
        "punch_policy": "NA",
        "timesheet_period": "US - Weekly starting on Sunday",
        "timesheet_approval_path": "Supervisor - Exception time",
        "time_off_template": "Time Off",
        "time_off_approver": "Supervisor",
        "work_week": "Sunday to Saturday"
    },
    {
        "location_level_1": "USA",
        "location_level_2": "All",
        "location_level_3": "All",
        "buisness_unit_level_2": "All",
        "department_grp_lvl_2": "All",
        "reg_temp": "Regular",
        "pay_type": "Salaried",
        "us_flsa_status": "E",
        "activity_type": "Blank",
        "timesheet_template": "NA",
        "payrule_name": "US_SAL",
        "rms_payrule_name": "US_SAL",
        "punch_policy": "NA",
        "timesheet_period": "US - Weekly starting on Sunday",
        "timesheet_approval_path": "Supervisor",
        "time_off_template": "Time Off",
        "time_off_approver": "Supervisor",
        "work_week": "Sunday to Saturday"
    },
    {
        "location_level_1": "USA",
        "location_level_2": "All",
        "location_level_3": "All",
        "buisness_unit_level_2": "All",
        "department_grp_lvl_2": "All",
        "reg_temp": "Regular",
        "pay_type": "Salaried",
        "us_flsa_status": "N",
        "activity_type": "Blank",
        "timesheet_template": "US_SAL_OT",
        "payrule_name": "US_SAL",
        "rms_payrule_name": "US_SAL",
        "punch_policy": "NA",
        "timesheet_period": "US - Weekly starting on Sunday",
        "timesheet_approval_path": "Supervisor",
        "time_off_template": "Time Off",
        "time_off_approver": "Supervisor",
        "work_week": "Sunday to Saturday"
    },
    {
        "location_level_1": "USA",
        "location_level_2": "All",
        "location_level_3": ["All Except", "FRDRKPAI", "DURHAMPAI", "DURHAMPAIW", "SKOKIEPAI"],
        "buisness_unit_level_2": ["NA04", "NA05"],
        "department_grp_lvl_2": "All",
        "reg_temp": "Regular",
        "pay_type": "Salaried",
        "us_flsa_status": "E",
        "activity_type": "Populated",
        "timesheet_template": "US_SAL_IS_PROJ",
        "payrule_name": "US_SAL",
        "rms_payrule_name": "US_SAL",
        "punch_policy": "NA",
        "timesheet_period": "US - Weekly starting on Sunday",
        "timesheet_approval_path": "Supervisor",
        "time_off_template": "Time Off",
        "time_off_approver": "Supervisor",
        "work_week": "Sunday to Saturday"
    },
    {
        "location_level_1": "USA",
        "location_level_2": "All",
        "location_level_3": ["All Except", "FRDRKPAI", "DURHAMPAI", "DURHAMPAIW", "SKOKIEPAI"],
        "buisness_unit_level_2": ["NA04", "NA05"],
        "department_grp_lvl_2": "All",
        "reg_temp": "Regular",
        "pay_type": "Salaried",
        "us_flsa_status": "N",
        "activity_type": "Populated",
        "timesheet_template": "US_SAL_IS_PROJ",
        "payrule_name": "US_SAL",
        "rms_payrule_name": "US_SAL",
        "punch_policy": "NA",
        "timesheet_period": "US - Weekly starting on Sunday",
        "timesheet_approval_path": "Supervisor",
        "time_off_template": "Time Off",
        "time_off_approver": "Supervisor",
        "work_week": "Sunday to Saturday"
    },
    {
        "location_level_1": "USA",
        "location_level_2": "All",
        "location_level_3": ["FRDRKPAI","DURHAMPAI","DURHAMPAIW","SKOKIEPAI"],
        "buisness_unit_level_2": ["All Except", "NA04", "NA05"],
        "department_grp_lvl_2": "All",
        "reg_temp": "Regular",
        "pay_type": "Salaried",
        "us_flsa_status": "E",
        "activity_type": "Populated",
        "timesheet_template": "US_PAI_SAL_PROJ",
        "payrule_name": "US_SAL",
        "rms_payrule_name": "US_SAL",
        "punch_policy": "NA",
        "timesheet_period": "US - Weekly starting on Sunday",
        "timesheet_approval_path": "Supervisor",
        "time_off_template": "Time Off",
        "time_off_approver": "Supervisor",
        "work_week": "Sunday to Saturday"
    },
    {
        "location_level_1": "USA",
        "location_level_2": "All",
        "location_level_3": ["All Except", "FRDRKPAI", "DURHAMPAI", "DURHAMPAIW", "SKOKIEPAI"],
        "buisness_unit_level_2": ["All Except", "NA04", "NA05"],
        "department_grp_lvl_2": "All",
        "reg_temp": "Regular",
        "pay_type": "Salaried",
        "us_flsa_status": "E",
        "activity_type": "Populated",
        "timesheet_template": "US_SAL_PROJ",
        "payrule_name": "US_SAL",
        "rms_payrule_name": "US_SAL",
        "punch_policy": "NA",
        "timesheet_period": "US - Weekly starting on Sunday",
        "timesheet_approval_path": "Supervisor",
        "time_off_template": "Time Off",
        "time_off_approver": "Supervisor",
        "work_week": "Sunday to Saturday"
    },
    {
        "location_level_1": "USA",
        "location_level_2": "All",
        "location_level_3": ["FRDRKPAI","DURHAMPAI","DURHAMPAIW","SKOKIEPAI"],
        "buisness_unit_level_2": ["All Except", "NA04", "NA05", "NA06"],
        "department_grp_lvl_2": ["All Except", "LARC08", "LARC10", "LARC4", "LARC9", "LARC-CRT", "NIA",
            "NIAID", "NIAID HAMILTON", "NIAID Poolesville", "NIAID ROCKVL"],
        "reg_temp": ["Regular", "Temporary"],
        "pay_type": "Hourly",
        "us_flsa_status": "N",
        "activity_type": "Populated",
        "timesheet_template": "US_PAI_HRLY_PROJ",
        "payrule_name": "US_HRLY",
        "rms_payrule_name": "US_HRLY_RMS",
        "punch_policy": "US_HRLY_Group",
        "timesheet_period": "US - Weekly starting on Sunday",
        "timesheet_approval_path": "Supervisor",
        "time_off_template": "Time Off",
        "time_off_approver": "Supervisor",
        "work_week": "Sunday to Saturday"
    },
    {
        "location_level_1": "USA",
        "location_level_2": ["All Except", "California", "Colorado", "Nevada", "Rhode Island"],
        "location_level_3": ["All Except", "FRDRKPAI", "DURHAMPAI", "DURHAMPAIW", "SKOKIEPAI"],
        "buisness_unit_level_2": "NA04",
        "department_grp_lvl_2": "All",
        "reg_temp": ["Regular", "Temporary"],
        "pay_type": "Hourly",
        "us_flsa_status": "N",
        "activity_type": "Populated",
        "timesheet_template": "US_IS_HRLY_PROJ",
        "payrule_name": "US_HRLY_IS_No_Prem",
        "rms_payrule_name": "US_HRLY_IS_No_Prem_RMS",
        "punch_policy": "US_HRLY_IS",
        "timesheet_period": "US - Weekly starting on Sunday",
        "timesheet_approval_path": "Supervisor",
        "time_off_template": "Time Off",
        "time_off_approver": "Supervisor",
        "work_week": "Sunday to Saturday"
    },
    {
        "location_level_1": "USA",
        "location_level_2": "California",
        "location_level_3": ["All Except", "FRDRKPAI", "DURHAMPAI", "DURHAMPAIW", "SKOKIEPAI"],
        "buisness_unit_level_2": "NA04",
        "department_grp_lvl_2": "All",
        "reg_temp": ["Regular", "Temporary"],
        "pay_type": "Hourly",
        "us_flsa_status": "N",
        "activity_type": "Populated",
        "timesheet_template": "US_IS_CAL_HRLY_PROJ",
        "payrule_name": "US_HRLY_CAL_IS",
        "rms_payrule_name": "US_HRLY_CAL_IS_RMS",
        "punch_policy": "US_CAL_HRLY_IS",
        "timesheet_period": "US - Weekly starting on Sunday",
        "timesheet_approval_path": "Supervisor",
        "time_off_template": "Time Off",
        "time_off_approver": "Supervisor",
        "work_week": "Sunday to Saturday"
    },
    {
        "location_level_1": "USA",
        "location_level_2": ["All Except", "California", "Colorado", "Nevada", "Rhode Island"],
        "location_level_3": ["All Except", "FRDRKPAI", "DURHAMPAI", "DURHAMPAIW", "SKOKIEPAI"],
        "buisness_unit_level_2": ["All Except", "NA04", "NA05", "NA06"],
        "department_grp_lvl_2": ["All Except", "LARC08", "LARC10", "LARC4", "LARC9", "LARC-CRT", "NIA",
            "NIAID", "NIAID HAMILTON", "NIAID Poolesville", "NIAID ROCKVL"],
        "reg_temp": ["Regular", "Temporary"],
        "pay_type": "Hourly",
        "us_flsa_status": ["N","E"],
        "activity_type": "Populated",
        "timesheet_template": "US_HRLY_PROJ",
        "payrule_name": "US_HRLY",
        "rms_payrule_name": "US_HRLY_RMS",
        "punch_policy": "US_HRLY_Group",
        "timesheet_period": "US - Weekly starting on Sunday",
        "timesheet_approval_path": "Supervisor",
        "time_off_template": "Time Off",
        "time_off_approver": "Supervisor",
        "work_week": "Sunday to Saturday"
    },
    {
        "location_level_1": "USA",
        "location_level_2": ["All Except", "California", "Colorado", "Nevada", "Rhode Island"],
        "location_level_3": ["All Except", "FRDRKPAI", "DURHAMPAI", "DURHAMPAIW", "SKOKIEPAI"],
        "buisness_unit_level_2": "NA06",
        "department_grp_lvl_2": ["All Except", "LARC08", "LARC10", "LARC4", "LARC9", "LARC-CRT", "NIA",
            "NIAID", "NIAID HAMILTON", "NIAID Poolesville", "NIAID ROCKVL"],
        "reg_temp": ["Regular", "Temporary"],
        "pay_type": "Hourly",
        "us_flsa_status": "N",
        "activity_type": "Populated",
        "timesheet_template": "US_HRLY_PROJ",
        "payrule_name": "US_HRLY_NA06",
        "rms_payrule_name": "US_HRLY_NA06_RMS",
        "punch_policy": "US_HRLY_Group",
        "timesheet_period": "US - Weekly starting on Sunday",
        "timesheet_approval_path": "Supervisor",
        "time_off_template": "Time Off",
        "time_off_approver": "Supervisor",
        "work_week": "Sunday to Saturday"
    },
    {
        "location_level_1": "USA",
        "location_level_2": "California",
        "location_level_3": ["All Except", "FRDRKPAI", "DURHAMPAI", "DURHAMPAIW", "SKOKIEPAI"],
        "buisness_unit_level_2": ["All Except", "NA04", "NA05", "NA06"],
        "department_grp_lvl_2": ["All Except", "LARC08", "LARC10", "LARC4", "LARC9", "LARC-CRT", "NIA",
            "NIAID", "NIAID HAMILTON", "NIAID Poolesville", "NIAID ROCKVL"],
        "reg_temp": ["Regular", "Temporary"],
        "pay_type": "Hourly",
        "us_flsa_status": "N",
        "activity_type": "Populated",
        "timesheet_template": "US_HRLY_PROJ_CAL",
        "payrule_name": "US_HRLY_CAL",
        "rms_payrule_name": "US_HRLY_CAL_RMS",
        "punch_policy": "US_California_Hrly",
        "timesheet_period": "US - Weekly starting on Sunday",
        "timesheet_approval_path": "Supervisor",
        "time_off_template": "Time Off",
        "time_off_approver": "Supervisor",
        "work_week": "Sunday to Saturday"
    },
    {
        "location_level_1": "USA",
        "location_level_2": "Colorado",
        "location_level_3": ["All Except", "FRDRKPAI", "DURHAMPAI", "DURHAMPAIW", "SKOKIEPAI"],
        "buisness_unit_level_2": ["All Except", "NA04", "NA05", "NA06"],
        "department_grp_lvl_2": ["All Except", "LARC08", "LARC10", "LARC4", "LARC9", "LARC-CRT", "NIA",
            "NIAID", "NIAID HAMILTON", "NIAID Poolesville", "NIAID ROCKVL"],
        "reg_temp": ["Regular", "Temporary"],
        "pay_type": "Hourly",
        "us_flsa_status": "N",
        "activity_type": "Populated",
        "timesheet_template": "US_HRLY_PROJ_COL",
        "payrule_name": "US_HRLY_COL",
        "rms_payrule_name": "US_HRLY_COL_RMS",
        "punch_policy": "US_HRLY_Group",
        "timesheet_period": "US - Weekly starting on Sunday",
        "timesheet_approval_path": "Supervisor",
        "time_off_template": "Time Off",
        "time_off_approver": "Supervisor",
        "work_week": "Sunday to Saturday"
    },
    {
        "location_level_1": "USA",
        "location_level_2": "Nevada",
        "location_level_3": ["All Except", "FRDRKPAI", "DURHAMPAI", "DURHAMPAIW", "SKOKIEPAI"],
        "buisness_unit_level_2": ["All Except", "NA04", "NA05", "NA06"],
        "department_grp_lvl_2": ["All Except", "LARC08", "LARC10", "LARC4", "LARC9", "LARC-CRT", "NIA",
            "NIAID", "NIAID HAMILTON", "NIAID Poolesville", "NIAID ROCKVL"],
        "reg_temp": ["Regular", "Temporary"],
        "pay_type": "Hourly",
        "us_flsa_status": "N",
        "activity_type": "Populated",
        "timesheet_template": "US_HRLY_PROJ_NV",
        "payrule_name": "US_HRLY_NV",
        "rms_payrule_name": "US_HRLY_NV_RMS",
        "punch_policy": "US_HRLY_Group",
        "timesheet_period": "US - Weekly starting on Sunday",
        "timesheet_approval_path": "Supervisor",
        "time_off_template": "Time Off",
        "time_off_approver": "Supervisor",
        "work_week": "Sunday to Saturday"
    },
    {
        "location_level_1": "USA",
        "location_level_2": "Rhode Island",
        "location_level_3": ["All Except", "FRDRKPAI", "DURHAMPAI", "DURHAMPAIW", "SKOKIEPAI"],
        "buisness_unit_level_2": ["All Except", "NA04", "NA05", "NA06"],
        "department_grp_lvl_2": ["All Except", "LARC08", "LARC10", "LARC4", "LARC9", "LARC-CRT", "NIA",
            "NIAID", "NIAID HAMILTON", "NIAID Poolesville", "NIAID ROCKVL"],
        "reg_temp": ["Regular", "Temporary"],
        "pay_type": "Hourly",
        "us_flsa_status": "N",
        "activity_type": "Populated",
        "timesheet_template": "US_HRLY_PROJ_RI",
        "payrule_name": "US_HRLY_RI",
        "rms_payrule_name": "US_HRLY_RI_RMS",
        "punch_policy": "US_HRLY_Group",
        "timesheet_period": "US - Weekly starting on Sunday",
        "timesheet_approval_path": "Supervisor",
        "time_off_template": "Time Off",
        "time_off_approver": "Supervisor",
        "work_week": "Sunday to Saturday"
    },
    {
        "location_level_1": "USA",
        "location_level_2": "Rhode Island",
        "location_level_3": ["All Except", "FRDRKPAI", "DURHAMPAI", "DURHAMPAIW", "SKOKIEPAI"],
        "buisness_unit_level_2": "NA05",
        "department_grp_lvl_2": ["All Except", "LARC08", "LARC10", "LARC4", "LARC9", "LARC-CRT", "NIA",
            "NIAID", "NIAID HAMILTON", "NIAID Poolesville", "NIAID ROCKVL"],
        "reg_temp": ["Regular", "Temporary"],
        "pay_type": "Hourly",
        "us_flsa_status": "N",
        "activity_type": "Populated",
        "timesheet_template": "US_IS_NA05_RI_HRLY_PROJ",
        "payrule_name": "US_HRLY_RI",
        "rms_payrule_name": "US_HRLY_RI_RMS",
        "punch_policy": "US_HRLY_IS_NA05",
        "timesheet_period": "US - Weekly starting on Sunday",
        "timesheet_approval_path": "Supervisor",
        "time_off_template": "Time Off",
        "time_off_approver": "Supervisor",
        "work_week": "Sunday to Saturday"
    },
    {
        "location_level_1": "USA",
        "location_level_2": "California",
        "location_level_3": ["All Except", "FRDRKPAI", "DURHAMPAI", "DURHAMPAIW", "SKOKIEPAI"],
        "buisness_unit_level_2": "NA05",
        "department_grp_lvl_2": ["All Except", "LARC08", "LARC10", "LARC4", "LARC9", "LARC-CRT", "NIA",
            "NIAID", "NIAID HAMILTON", "NIAID Poolesville", "NIAID ROCKVL"],
        "reg_temp": ["Regular", "Temporary"],
        "pay_type": "Hourly",
        "us_flsa_status": "N",
        "activity_type": "Populated",
        "timesheet_template": "US_IS_CAL_HRLY_PROJ",
        "payrule_name": "US_HRLY_CAL_NA05",
        "rms_payrule_name": "US_HRLY_CAL_NA05_RMS",
        "punch_policy": "US_CAL_HRLY_IS_NA05",
        "timesheet_period": "US - Weekly starting on Sunday",
        "timesheet_approval_path": "Supervisor",
        "time_off_template": "Time Off",
        "time_off_approver": "Supervisor",
        "work_week": "Sunday to Saturday"
    },
    {
        "location_level_1": "USA",
        "location_level_2": ["All Except", "California", "Colorado", "Nevada", "Rhode Island"],
        "location_level_3": ["All Except", "FRDRKPAI", "DURHAMPAI", "DURHAMPAIW", "SKOKIEPAI"],
        "buisness_unit_level_2": "NA05",
        "department_grp_lvl_2": ["LARC08", "LARC10", "LARC4", "LARC9", "LARC-CRT", "NIA", "NIAID", "NIAID HAMILTON", "NIAID Poolesville", "NIAID ROCKVL"],
        "reg_temp": ["Regular", "Temporary"],
        "pay_type": "Hourly",
        "us_flsa_status": ["N","E"],
        "activity_type": "Populated",
        "timesheet_template": "US_IS_NA05_HRLY_PROJ_4%",
        "payrule_name": "US_HRLY_NA05_4%",
        "rms_payrule_name": "US_HRLY_NA05_4%_RMS",
        "punch_policy": "US_HRLY_IS",
        "timesheet_period": "US - Weekly starting on Sunday",
        "timesheet_approval_path": "Supervisor",
        "time_off_template": "Time Off",
        "time_off_approver": "Supervisor",
        "work_week": "Sunday to Saturday"
    },
    {
        "location_level_1": "USA",
        "location_level_2": "California",
        "location_level_3": ["All Except", "FRDRKPAI", "DURHAMPAI", "DURHAMPAIW", "SKOKIEPAI"],
        "buisness_unit_level_2": "NA05",
        "department_grp_lvl_2": ["LARC08", "LARC10", "LARC4", "LARC9", "LARC-CRT", "NIA", "NIAID", "NIAID HAMILTON", "NIAID Poolesville", "NIAID ROCKVL"],
        "reg_temp": ["Regular", "Temporary"],
        "pay_type": "Hourly",
        "us_flsa_status": "N",
        "activity_type": "Populated",
        "timesheet_template": "US_IS_CAL_HRLY_PROJ_4%",
        "payrule_name": "US_HRLY_CAL_NA05",
        "rms_payrule_name": "US_HRLY_CAL_NA05_RMS",
        "punch_policy": "US_CAL_HRLY_IS_NA05",
        "timesheet_period": "US - Weekly starting on Sunday",
        "timesheet_approval_path": "Supervisor",
        "time_off_template": "Time Off",
        "time_off_approver": "Supervisor",
        "work_week": "Sunday to Saturday"
    },
    {
        "location_level_1": "USA",
        "location_level_2": "California",
        "location_level_3": ["All Except", "FRDRKPAI", "DURHAMPAI", "DURHAMPAIW", "SKOKIEPAI"],
        "buisness_unit_level_2": "NA05",
        "department_grp_lvl_2": ["LARC08", "LARC10", "LARC4", "LARC9", "LARC-CRT", "NIA", "NIAID", "NIAID HAMILTON", "NIAID Poolesville", "NIAID ROCKVL"],
        "reg_temp": ["Regular", "Temporary"],
        "pay_type": "Hourly",
        "us_flsa_status": "N",
        "activity_type": "Blank",
        "timesheet_template": "US_IS_NA05_CAL_HRLY",
        "payrule_name": "US_HRLY_CAL_NA05",
        "rms_payrule_name": "US_HRLY_CAL_NA05_RMS",
        "punch_policy": "US_CAL_HRLY_IS_NA05",
        "timesheet_period": "US - Weekly starting on Sunday",
        "timesheet_approval_path": "Supervisor",
        "time_off_template": "Time Off",
        "time_off_approver": "Supervisor",
        "work_week": "Sunday to Saturday"
    },
    {
        "location_level_1": "USA",
        "location_level_2": ["All Except", "California", "Colorado", "Nevada", "Rhode Island"],
        "location_level_3": "All",
        "buisness_unit_level_2": ["All Except", "NA05"],
        "department_grp_lvl_2": ["LARC08", "LARC10", "LARC4", "LARC9", "LARC-CRT", "NIA",
            "NIAID", "NIAID HAMILTON", "NIAID Poolesville", "NIAID ROCKVL"],
        "reg_temp": ["Regular", "Temporary"],
        "pay_type": "Hourly",
        "us_flsa_status": ["N","E"],
        "activity_type": "Blank",
        "timesheet_template": "US_HRLY",
        "payrule_name": "US_HRLY",
        "rms_payrule_name": "US_HRLY_RMS",
        "punch_policy": "US_HRLY_Group",
        "timesheet_period": "US - Weekly starting on Sunday",
        "timesheet_approval_path": "Supervisor",
        "time_off_template": "Time Off",
        "time_off_approver": "Supervisor",
        "work_week": "Sunday to Saturday"
    },
    {
        "location_level_1": "USA",
        "location_level_2": ["All Except", "California", "Colorado", "Nevada", "Rhode Island"],
        "location_level_3": "All",
        "buisness_unit_level_2": ["All Except", "NA05"],
        "department_grp_lvl_2": ["LARC08", "LARC10", "LARC4", "LARC9", "LARC-CRT", "NIA",
            "NIAID", "NIAID HAMILTON", "NIAID Poolesville", "NIAID ROCKVL"],
        "reg_temp": ["Regular", "Temporary"],
        "pay_type": "Hourly",
        "us_flsa_status": ["N","E"],
        "activity_type": "Populated",
        "timesheet_template": "US_HRLY_PROJ",
        "payrule_name": "US_HRLY",
        "rms_payrule_name": "US_HRLY_RMS",
        "punch_policy": "US_HRLY_Group",
        "timesheet_period": "US - Weekly starting on Sunday",
        "timesheet_approval_path": "Supervisor",
        "time_off_template": "Time Off",
        "time_off_approver": "Supervisor",
        "work_week": "Sunday to Saturday"
    } 
]
