from dxctechnology.workday_user_import_v1.user_import.config import *
from dxctechnology.workday_user_import_v1.user_import.mappers.master_mapper import MAPPER

instance = "trial"

version = "v3"
process_time_off_accrual_dag_version = "v1"
ia_version = "v1"

environment = "pre-production"

company_key = "dxctrial01"
replicon_conn_id = "dxctrial01_replicon_x.replicon.workday1"
sftp_conn_id = "sftp_useast2"

DXC_WORKDAY_USER_SYNC_USER_MAPPER = MAPPER

process_time_off_accrual = f"dxctechnology_workday_user_sync_timeoff_assignment_policy_update_for_no_accrual_child_{instance}_{process_time_off_accrual_dag_version}"

# USA CSC
usa_csc_process_users_child_dag_id = f"dxctechnology_workday_user_import_us_csc_process_users_child_{instance}_{version}"
usa_csc_add_user_dag_id = f"dxctechnology_workday_user_import_us_csc_add_user_child_{instance}_{version}"
usa_csc_add_user_timeoff_assignment_dag_id = f"dxctechnology_workday_user_import_us_csc_add_timeoff_assignment_child_{instance}_{version}"
usa_csc_update_user_dag_id = f"dxctechnology_workday_user_import_us_csc_update_user_child_{instance}_{version}"
usa_csc_update_user_timeoff_assignment_dag_id = f"dxctechnology_workday_user_import_us_csc_update_timeoff_assignment_child_{instance}_{version}"
usa_csc_us_puerto_rico_user_timeoff_assignment_dag_id = f"dxctechnology_workday_user_import_us_csc_puerto_rico_timeoff_assignment_child_{instance}_{version}"
usa_csc_rehire_timeoff_assignment = f"dxctechnology_workday_user_import_usa_csc_rehire_timeoff_assignment_child_{instance}_{version}"
usa_csc_us_holiday_user_timeoff_assignment_dag_id = f"dxctechnology_workday_user_import_us_csc_holiday_timeoff_assignment_child_{instance}_{version}"
usa_csc_us_sick_leave_non_california_user_timeoff_assignment_dag_id = f"dxctechnology_workday_user_import_us_csc_non_cal_sick_timeoff_assignment_child_{instance}_{version}"

can_run_batch_task_var_name_us_csc = f"dxctechnology_workday_user_import_us_csc_can_run_batch_task_{instance}_{version}"

workday_user_import_ia_zero_timeoff_assignment_child_dag = f"dxctechnology_workday_user_import_ia_zero_timeoff_assignment_child_{instance}_{ia_version}"
workday_user_import_ia_one_timeoff_assignment_child_dag = f"dxctechnology_workday_user_import_ia_one_timeoff_assignment_child_{instance}_{ia_version}"

# Cleanup child DAG ID for disabled users
delete_future_entries_child_dag_id = f"dxctechnology_workday_user_sync_delete_future_entries_child_{instance}_v2"
usa_lse_add_user_timeoff_assignment_dag_id = f"dxctechnology_workday_user_import_process_usa_les_add_user_timeoff_child_dag_{instance}_{version}"
usa_lse_update_user_timeoff_assignment_dag_id = f"dxctechnology_workday_user_import_process_usa_les_update_user_timeoff_child_dag_{instance}_{version}"

# Overrides: bump max_active_runs to 10 for this environment (base defaults in config.py are unchanged, so production is not affected)
max_run_add_to_assignment = 10
max_run_add_user = 10
max_run_holiday_to_assignment = 10
max_run_process_each_users = 10
max_run_puerto_rico_to_assignment = 10
max_run_rehire_to_assignment = 10
max_run_sick_non_cal_to_assignment = 10
max_run_update_to_assignment = 10
max_run_update_user = 10
