from dxctechnology.workday_user_import.user_import.config import *
from dxctechnology.workday_user_import.user_import.mappers.master_mapper_v2 import MAPPER

instance = "production"

version = "v0"

environment = "production"
can_run_batch_task_var_name = f"dxctechnology_workday_user_import_can_run_batch_task_variable_{instance}"

company_key = "dxctechnology"
replicon_conn_id = "dxctechnology_replicon_x.replicon.workday1"
sftp_conn_id = "sftp_dxctechnology_628172_Workday"

DXC_WORKDAY_USER_SYNC_USER_MAPPER = MAPPER

process_time_off_accrual = f"dxctechnology_workday_user_sync_timeoff_assignment_policy_update_for_no_accrual_child_{instance}_{version}"
workday_user_import_global_users_update_user_timeoff_process_child_dag_disable = f"dxctechnology_workday_user_import_global_users_update_user_timeoff_process_child_for_disable_user_{instance}_{version}"

workday_user_import_process_canada_users_child_dag = f"dxctechnology_workday_user_import_process_canada_process_user_child_dag_{instance}_{version}"
workday_user_import_canada_users_add_user_child_dag = f"dxctechnology_workday_user_import_canada_users_add_user_child_{instance}_{version}"
workday_user_import_canada_users_add_user_timeoff_process_child_dag = f"dxctechnology_workday_user_import_canada_users_add_user_timeoff_process_child_{instance}_{version}"
workday_user_import_canada_users_update_user_timeoff_process_child_dag = f"dxctechnology_workday_user_import_canada_users_update_user_timeoff_process_child_{instance}_{version}"
workday_user_import_canada_users_add_user_timeoff_process_child_for_canada_dag = f"dxctechnology_workday_user_import_canada_users_add_user_timeoff_process_child_for_canada_{instance}_{version}"
workday_user_import_canada_users_update_user_timeoff_process_child_dag_disable = f"dxctechnology_workday_user_import_canada_users_update_user_timeoff_process_child_for_disable_user_{instance}_{version}"
workday_user_import_canada_users_update_user_child_dag = f"dxctechnology_workday_user_import_canada_users_update_user_child_{instance}_{version}"
workday_user_import_canada_users_update_user_rehire_timeoff_process_child_dag =  f"dxctechnology_workday_user_import_canada_users_update_user_rehire_timeoff_assignment_process_child_{instance}_{version}"
workday_user_import_canada_users_process_canada_banked_timeoff_type_child_dag = f"dxctechnology_workday_user_import_canada_users_process_canada_banked_timeoff_type_child_{instance}_{version}"
workday_user_import_canada_users_process_canada_vacation_timeoff_type_child_dag =f"dxctechnology_workday_user_import_canada_users_process_canada_vacation_timeoff_type_child_{instance}_{version}"

can_run_batch_task_var_name_canada = f"dxctechnology_workday_user_import_xosta_rica_can_run_batch_task_{instance}"

#US-CSC
usa_csc_process_users_child_dag_id = f"dxctechnology_workday_user_import_us_csc_process_users_child_{instance}_{version}"
usa_csc_add_user_dag_id = f"dxctechnology_workday_user_import_us_csc_add_user_child_{instance}_{version}"
usa_csc_add_user_timeoff_assignment_dag_id = f"dxctechnology_workday_user_import_us_csc_add_timeoff_assignment_child_{instance}_{version}"
usa_csc_update_user_dag_id = f"dxctechnology_workday_user_import_us_csc_update_user_child_{instance}_{version}"
usa_csc_update_user_timeoff_assignment_dag_id = f"dxctechnology_workday_user_import_us_csc_update_timeoff_assignment_child_{instance}_{version}"
usa_csc_us_puerto_rico_user_timeoff_assignment_dag_id = f"dxctechnology_workday_user_import_us_csc_puerto_rico_timeoff_assignment_child_{instance}_{version}"
usa_csc_rehire_timeoff_assignment = f"dxctechnology_workday_user_import_usa_csc_rehire_timeoff_assignment_child_{instance}_{version}"
usa_csc_us_holiday_user_timeoff_assignment_dag_id = f"dxctechnology_workday_user_import_us_csc_holiday_timeoff_assignment_child_{instance}_{version}"
usa_csc_us_sick_leave_california_user_timeoff_assignment_dag_id = f"dxctechnology_workday_user_import_us_csc_cal_sick_timeoff_assignment_child_{instance}_{version}"
usa_csc_us_sick_leave_non_california_user_timeoff_assignment_dag_id = f"dxctechnology_workday_user_import_us_csc_non_cal_sick_timeoff_assignment_child_{instance}_{version}"

can_run_batch_task_var_name_us_csc = f"dxctechnology_workday_user_import_us_csc_can_run_batch_task_{instance}_{version}"

# whenever there is version upgrade in us_les, will need to update below dag_ids
usa_lse_add_user_timeoff_assignment_dag_id = f"dxctechnology_workday_user_import_process_usa_les_add_user_timeoff_child_dag_{instance}_{version}"
usa_lse_update_user_timeoff_assignment_dag_id = f"dxctechnology_workday_user_import_process_usa_les_update_user_timeoff_child_dag_{instance}_{version}"


workday_user_import_ia_zero_timeoff_assignment_child_dag = f"dxctechnology_workday_user_import_ia_zero_timeoff_assignment_child_{instance}_{version}"
workday_user_import_ia_one_timeoff_assignment_child_dag = f"dxctechnology_workday_user_import_ia_one_timeoff_assignment_child_{instance}_{version}"

# Cleanup child DAG ID for disabled users
delete_future_entries_child_dag_id = f"dxctechnology_workday_user_sync_delete_future_entries_child_{instance}"
