import rail
import hashlib
from datetime import datetime

from airflow.models import Variable
from procore_ce_integration.initial_setup_sync.config import (
    PROCORE_SELF_APP_ID_PREFIX_HASHES,
    PROCORE_SELF_APP_ID_PREFIX_LEN,
)
from procore_ce_integration.job_structure_sync.utils.constants import WBSType

COST_CODE_SEPARATOR = '-'


def extract_ce_code(origin_id):
    """Extract CE code from origin_id by stripping the 'CE_' prefix."""
    if origin_id and str(origin_id).startswith('CE_'):
        return str(origin_id)[3:]
    return None


def normalize_ce_identifier(value):
    """Uppercase an identifier for case-insensitive matching against ComputerEase.

    ComputerEase canonicalizes unique identifiers (vendor/job/phase/category codes,
    cost-type references, etc.) to UPPERCASE on import and searches them
    case-sensitively. Procore preserves the original casing, so any Procore-derived
    value used to look up, filter, compare, or build a CE_<code> origin_id against a
    CE record must be normalized through this helper first - otherwise a casing
    difference yields "not found when it exists" and duplicate creation.
    Returns the value unchanged when it is falsy (None/empty).
    """
    if not value:
        return value
    return str(value).upper()


def is_self_originated_event(webhook_data):
    """Return True if the webhook was generated by our own integration (skip to avoid loops)"""
    
    source_app_id = (webhook_data.get('metadata') or {}).get('source_application_id')
    if not source_app_id:
        return False
    prefix = str(source_app_id)[:PROCORE_SELF_APP_ID_PREFIX_LEN]
    if len(prefix) < PROCORE_SELF_APP_ID_PREFIX_LEN:
        return False
    prefix_hash = hashlib.sha256(prefix.encode()).hexdigest()
    return prefix_hash in PROCORE_SELF_APP_ID_PREFIX_HASHES

def parse_date(date_value, date_format='%Y-%m-%d'):
    """Parse a date string and return it in date_format (default YYYY-MM-DD)."""
    if not date_value:
        return None
    s = str(date_value).strip()
    if not s:
        return None
    for fmt in ['%Y-%m-%d', '%Y-%m-%dT%H:%M:%SZ', '%Y-%m-%dT%H:%M:%S.%fZ',
                '%Y-%m-%dT%H:%M:%S', '%Y-%m-%d %H:%M:%S']:
        try:
            return datetime.strptime(s, fmt).strftime(date_format)
        except ValueError:
            continue
    return None


def parse_wbs_flat_code(flat_code, cost_code, wbs_type=None):
    if not flat_code:
        return '', '', ''

    cost_type = ''
    if '.' in flat_code:
        full_cost_code, cost_type = flat_code.rsplit('.', 1)
    else:
        full_cost_code = flat_code

    # If cost_code is None, we cantt determine the phase and category code, so we return empty strings for them
    if cost_code is None:
        return '', '', cost_type

    if cost_code.get('parent', {}).get('id') is not None: # multi level cost code
        category_code = cost_code.get('code', '')
        phase_code = full_cost_code.removesuffix(f'{COST_CODE_SEPARATOR}{category_code}') if category_code else ''
    else: # single level cost code
        if wbs_type == WBSType.JOB_PHASE_CAT:
            phase_code = full_cost_code
            category_code = ''
        else:
            phase_code = ''
            category_code = full_cost_code

    return phase_code, category_code, cost_type

def build_import_file_description(resource_type, identifier):
    """Build the standard CE import-file description used for dedup.
    The shape of the prefix is relied on by the deduplication task
    group (``rail.computerease_import_sync``) which matches existing
    imports via ``startswith("<resource_type> Sync: <identifier>")``.
    """
    ecid = rail.render_template('{{ dag_run_ecid() }}')
    return f"{resource_type} Sync: {identifier} - ecid:{ecid}"


def get_tenant_email(config):
    """Resolve tenant notification email from instance config, Airflow Variable, or internal_email.

    Resolution order:
    1. config.tenant_email — hand-authored instance files; existing deployments unchanged.
    2. Airflow Variable ``ce_procore_{customer_id}_{deployment_slug}_customer_email`` —
       set by the self-service UI when the user provides an email address.
    3. config.internal_email — last-resort fallback so the internal team is always notified.
    4. Empty list
    """
    email = getattr(config, 'tenant_email', None)
    if email:
        return [email] if isinstance(email, str) else email
    customer = getattr(config, 'customer_id', None)
    deployment = getattr(config, 'deployment_slug', None)
    if customer and deployment:
        val = Variable.get(f"ce_procore_{customer}_{deployment}_customer_email", default_var=None)
        if val:
            return [addr.strip() for addr in val.split(',') if addr.strip()]
    internal = getattr(config, 'internal_email', None)
    if internal:
        return [internal] if isinstance(internal, str) else internal
    return []
