FRANCE_USER_MAPPER = [
    {
        "country": "France",
        "location": "ALL",
        "worker_type": "Employee",
        "compensation_grade": "Salary",
        "contract_type": "Full_time",
        "employee_type": [
            "Regular",
            "Fixed Term",
            "Partner",
            "Intern"
        ],
        "job_category": "Functional",
        "management_level": [
            "CEO",
            "Partner",
            "Executive Vice President",
            "Senior Vice President",
            "Vice President",
            "Director",
            "Senior Manager",
            "Manager",
            "Senior Associate",
            "Specialist",
            "Specialist 2",
            "Associate",
            "Trainee/Apprentice",
            "Administrative",
            "Administrative 2"
        ],
        "additional_job_classification": "FRA_OT_Policy_A",
        "company_code": "NA",
        "schedule_type": "Office Schedule (Assigned to user via another automation)",
        "work_week": "Sunday to Saturday",
        "timesheet_template": "France TSD Agile Emp OT",
        "time_entry_approval_path": "Automatic Approval",
        "timesheet_approval": "Supervisor",
        "timesheet_period": "Weekly without crossing months",
        "time_off_template": "Time Off",
        "time_off_approval": "System",
        "time_off_types": [
            "FRA_TOIL",
            "Holiday",
            "Leave of Absence"
        ],
        "payrule": "France FT_SAL_Policy_A",
        "time_zone": "(UTC+1:00) Central European Standard Time",
        "holiday_calendar": "France Holiday Calendar",
        "authentication_type": "SSO"
    },
    {
        "country": "France",
        "location": "ALL",
        "worker_type": "Employee",
        "compensation_grade": "Salary",
        "contract_type": "Full_time",
        "employee_type": [
            "Non-Salaried / Self-Employed",
            "Non-Salaried / Self-Employed (Fixed Term)"
        ],
        "job_category": "Functional",
        "management_level": [
            "CEO",
            "Partner",
            "Executive Vice President",
            "Senior Vice President",
            "Vice President",
            "Director",
            "Senior Manager",
            "Manager",
            "Senior Associate",
            "Specialist",
            "Specialist 2",
            "Associate",
            "Trainee/Apprentice",
            "Administrative",
            "Administrative 2"
        ],
        "additional_job_classification": "FRA_OT_Policy_A",
        "company_code": "NA",
        "schedule_type": "Office Schedule (Assigned to user via another automation)",
        "work_week": "Sunday to Saturday",
        "timesheet_template": "France TSD Agile Emp OT",
        "time_entry_approval_path": "Automatic Approval",
        "timesheet_approval": "Supervisor",
        "timesheet_period": "Weekly without crossing months",
        "time_off_template": "Time Off",
        "time_off_approval": "Non-Salaried/Self-Employed TO Approval",
        "time_off_types": [
            "FRA_TOIL",
            "Holiday",
            "Leave of Absence"
        ],
        "payrule": "France FT_SAL_Policy_A",
        "time_zone": "(UTC+1:00) Central European Standard Time",
        "holiday_calendar": "France Holiday Calendar",
        "authentication_type": "SSO"
    },
    {
        "country": "France",
        "location": "ALL",
        "worker_type": "Employee",
        "compensation_grade": "Salary",
        "contract_type": "Part_time",
        "employee_type": [
            "Regular",
            "Fixed Term",
            "Partner",
            "Intern"
        ],
        "job_category": "Functional",
        "management_level": [
            "CEO",
            "Partner",
            "Executive Vice President",
            "Senior Vice President",
            "Vice President",
            "Director",
            "Senior Manager",
            "Manager",
            "Senior Associate",
            "Specialist",
            "Specialist 2",
            "Associate",
            "Trainee/Apprentice",
            "Administrative",
            "Administrative 2"
        ],
        "additional_job_classification": "FRA_OT_Policy_A",
        "company_code": "NA",
        "schedule_type": "Office Schedule (Assigned to user via another automation)",
        "work_week": "Sunday to Saturday",
        "timesheet_template": "France TSD Agile Emp OT",
        "time_entry_approval_path": "Automatic Approval",
        "timesheet_approval": "Supervisor",
        "timesheet_period": "Weekly without crossing months",
        "time_off_template": "Time Off",
        "time_off_approval": "System",
        "time_off_types": [
            "FRA_TOIL",
            "Holiday",
            "Leave of Absence"
        ],
        "payrule": "France PT_SAL_Policy_A",
        "time_zone": "(UTC+1:00) Central European Standard Time",
        "holiday_calendar": "France Holiday Calendar",
        "authentication_type": "SSO"
    },
    {
        "country": "France",
        "location": "ALL",
        "worker_type": "Employee",
        "compensation_grade": "Salary",
        "contract_type": "Part_time",
        "employee_type": [
            "Non-Salaried / Self-Employed",
            "Non-Salaried / Self-Employed (Fixed Term)"
        ],
        "job_category": "Functional",
        "management_level": [
            "CEO",
            "Partner",
            "Executive Vice President",
            "Senior Vice President",
            "Vice President",
            "Director",
            "Senior Manager",
            "Manager",
            "Senior Associate",
            "Specialist",
            "Specialist 2",
            "Associate",
            "Trainee/Apprentice",
            "Administrative",
            "Administrative 2"
        ],
        "additional_job_classification": "FRA_OT_Policy_A",
        "company_code": "NA",
        "schedule_type": "Office Schedule (Assigned to user via another automation)",
        "work_week": "Sunday to Saturday",
        "timesheet_template": "France TSD Agile Emp OT",
        "time_entry_approval_path": "Automatic Approval",
        "timesheet_approval": "Supervisor",
        "timesheet_period": "Weekly without crossing months",
        "time_off_template": "Time Off",
        "time_off_approval": "Non-Salaried/Self-Employed TO Approval",
        "time_off_types": [
            "FRA_TOIL",
            "Holiday",
            "Leave of Absence"
        ],
        "payrule": "France PT_SAL_Policy_A",
        "time_zone": "(UTC+1:00) Central European Standard Time",
        "holiday_calendar": "France Holiday Calendar",
        "authentication_type": "SSO"
    },
    {
        "country": "France",
        "location": "ALL",
        "worker_type": "Employee",
        "compensation_grade": "Salary",
        "contract_type": "Full_time",
        "employee_type": [
            "Regular",
            "Fixed Term",
            "Partner",
            "Intern"
        ],
        "job_category": "Functional",
        "management_level": [
            "CEO",
            "Partner",
            "Executive Vice President",
            "Senior Vice President",
            "Vice President",
            "Director",
            "Senior Manager",
            "Manager",
            "Senior Associate",
            "Specialist",
            "Specialist 2",
            "Associate",
            "Trainee/Apprentice",
            "Administrative",
            "Administrative 2"
        ],
        "additional_job_classification": "FRA_OT_Policy_B",
        "company_code": "NA",
        "schedule_type": "Office Schedule (Assigned to user via another automation)",
        "work_week": "Sunday to Saturday",
        "timesheet_template": "France TSD Agile Emp OT",
        "time_entry_approval_path": "Automatic Approval",
        "timesheet_approval": "Supervisor",
        "timesheet_period": "Weekly without crossing months",
        "time_off_template": "Time Off",
        "time_off_approval": "System",
        "time_off_types": [
            "FRA_TOIL",
            "Holiday",
            "Leave of Absence"
        ],
        "payrule": "France FT_SAL_Policy_B",
        "time_zone": "(UTC+1:00) Central European Standard Time",
        "holiday_calendar": "France Holiday Calendar",
        "authentication_type": "SSO"
    },
    {
        "country": "France",
        "location": "ALL",
        "worker_type": "Employee",
        "compensation_grade": "Salary",
        "contract_type": "Full_time",
        "employee_type": [
            "Non-Salaried / Self-Employed",
            "Non-Salaried / Self-Employed (Fixed Term)"
        ],
        "job_category": "Functional",
        "management_level": [
            "CEO",
            "Partner",
            "Executive Vice President",
            "Senior Vice President",
            "Vice President",
            "Director",
            "Senior Manager",
            "Manager",
            "Senior Associate",
            "Specialist",
            "Specialist 2",
            "Associate",
            "Trainee/Apprentice",
            "Administrative",
            "Administrative 2"
        ],
        "additional_job_classification": "FRA_OT_Policy_B",
        "company_code": "NA",
        "schedule_type": "Office Schedule (Assigned to user via another automation)",
        "work_week": "Sunday to Saturday",
        "timesheet_template": "France TSD Agile Emp OT",
        "time_entry_approval_path": "Automatic Approval",
        "timesheet_approval": "Supervisor",
        "timesheet_period": "Weekly without crossing months",
        "time_off_template": "Time Off",
        "time_off_approval": "Non-Salaried/Self-Employed TO Approval",
        "time_off_types": [
            "FRA_TOIL",
            "Holiday",
            "Leave of Absence"
        ],
        "payrule": "France FT_SAL_Policy_B",
        "time_zone": "(UTC+1:00) Central European Standard Time",
        "holiday_calendar": "France Holiday Calendar",
        "authentication_type": "SSO"
    },
    {
        "country": "France",
        "location": "ALL",
        "worker_type": "Employee",
        "compensation_grade": "Salary",
        "contract_type": "Part_time",
        "employee_type": [
            "Regular",
            "Fixed Term",
            "Partner",
            "Intern"
        ],
        "job_category": "Functional",
        "management_level": [
            "CEO",
            "Partner",
            "Executive Vice President",
            "Senior Vice President",
            "Vice President",
            "Director",
            "Senior Manager",
            "Manager",
            "Senior Associate",
            "Specialist",
            "Specialist 2",
            "Associate",
            "Trainee/Apprentice",
            "Administrative",
            "Administrative 2"
        ],
        "additional_job_classification": "FRA_OT_Policy_B",
        "company_code": "NA",
        "schedule_type": "Office Schedule (Assigned to user via another automation)",
        "work_week": "Sunday to Saturday",
        "timesheet_template": "France TSD Agile Emp OT",
        "time_entry_approval_path": "Automatic Approval",
        "timesheet_approval": "Supervisor",
        "timesheet_period": "Weekly without crossing months",
        "time_off_template": "Time Off",
        "time_off_approval": "System",
        "time_off_types": [
            "FRA_TOIL",
            "Holiday",
            "Leave of Absence"
        ],
        "payrule": "France PT_SAL_Policy_B ",
        "time_zone": "(UTC+1:00) Central European Standard Time",
        "holiday_calendar": "France Holiday Calendar",
        "authentication_type": "SSO"
    },
    {
        "country": "France",
        "location": "ALL",
        "worker_type": "Employee",
        "compensation_grade": "Salary",
        "contract_type": "Part_time",
        "employee_type": [
            "Non-Salaried / Self-Employed",
            "Non-Salaried / Self-Employed (Fixed Term)"
        ],
        "job_category": "Functional",
        "management_level": [
            "CEO",
            "Partner",
            "Executive Vice President",
            "Senior Vice President",
            "Vice President",
            "Director",
            "Senior Manager",
            "Manager",
            "Senior Associate",
            "Specialist",
            "Specialist 2",
            "Associate",
            "Trainee/Apprentice",
            "Administrative",
            "Administrative 2"
        ],
        "additional_job_classification": "FRA_OT_Policy_B",
        "company_code": "NA",
        "schedule_type": "Office Schedule (Assigned to user via another automation)",
        "work_week": "Sunday to Saturday",
        "timesheet_template": "France TSD Agile Emp OT",
        "time_entry_approval_path": "Automatic Approval",
        "timesheet_approval": "Supervisor",
        "timesheet_period": "Weekly without crossing months",
        "time_off_template": "Time Off",
        "time_off_approval": "Non-Salaried/Self-Employed TO Approval",
        "time_off_types": [
            "FRA_TOIL",
            "Holiday",
            "Leave of Absence"
        ],
        "payrule": "France PT_SAL_Policy_B ",
        "time_zone": "(UTC+1:00) Central European Standard Time",
        "holiday_calendar": "France Holiday Calendar",
        "authentication_type": "SSO"
    },
    {
        "country": "France",
        "location": "ALL",
        "worker_type": "Employee",
        "compensation_grade": "Salary",
        "contract_type": [
            "Full_time",
            "Part_time"
        ],
        "employee_type": [
            "Non-Salaried / Self-Employed",
            "Non-Salaried / Self-Employed (Fixed Term)"
        ],
        "job_category": "Functional",
        "management_level": [
            "CEO",
            "Partner",
            "Executive Vice President",
            "Senior Vice President",
            "Vice President",
            "Director",
            "Senior Manager",
            "Manager",
            "Senior Associate",
            "Specialist",
            "Specialist 2",
            "Associate",
            "Trainee/Apprentice",
            "Administrative",
            "Administrative 2"
        ],
        "additional_job_classification": "Null",
        "company_code": "NA",
        "schedule_type": "Office Schedule (Assigned to user via another automation)",
        "work_week": "Sunday to Saturday",
        "timesheet_template": "France TSD Agile Emp NON-OT",
        "time_entry_approval_path": "Automatic Approval",
        "timesheet_approval": "Supervisor",
        "timesheet_period": "Weekly without crossing months",
        "time_off_template": "Time Off",
        "time_off_approval": "Non-Salaried/Self-Employed TO Approval",
        "time_off_types": [
            "Holiday",
            "Leave of Absence"
        ],
        "payrule": "France NON-OT",
        "time_zone": "(UTC+1:00) Central European Standard Time",
        "holiday_calendar": "France Holiday Calendar",
        "authentication_type": "SSO"
    },
    {
        "country": "France",
        "location": "ALL",
        "worker_type": "Employee",
        "compensation_grade": "Salary",
        "contract_type": [
            "Full_time",
            "Part_time"
        ],
        "employee_type": [
            "Non-Salaried / Self-Employed",
            "Non-Salaried / Self-Employed (Fixed Term)"
        ],
        "job_category": "Functional",
        "management_level": [
            "CEO",
            "Partner",
            "Executive Vice President",
            "Senior Vice President",
            "Vice President",
            "Director",
            "Senior Manager",
            "Manager",
            "Senior Associate",
            "Specialist",
            "Specialist 2",
            "Associate",
            "Trainee/Apprentice",
            "Administrative",
            "Administrative 2"
        ],
        "additional_job_classification": "Null",
        "company_code": "NA",
        "schedule_type": "Office Schedule (Assigned to user via another automation)",
        "work_week": "Sunday to Saturday",
        "timesheet_template": "France TSD Agile Emp NON-OT",
        "time_entry_approval_path": "Automatic Approval",
        "timesheet_approval": "Supervisor",
        "timesheet_period": "Weekly without crossing months",
        "time_off_template": "Time Off",
        "time_off_approval": "Non-Salaried/Self-Employed TO Approval",
        "time_off_types": [
            "Holiday",
            "Leave of Absence"
        ],
        "payrule": "France NON-OT",
        "time_zone": "(UTC+1:00) Central European Standard Time",
        "holiday_calendar": "France Holiday Calendar",
        "authentication_type": "SSO"
    },
    {
        "country": "France",
        "location": "ALL",
        "worker_type": "Employee",
        "compensation_grade": "Hourly",
        "contract_type": [
            "Full_time",
            "Part_time"
        ],
        "employee_type": [
            "Regular",
            "Fixed Term",
            "Partner",
            "Intern"
        ],
        "job_category": "Functional",
        "management_level": [
            "CEO",
            "Partner",
            "Executive Vice President",
            "Senior Vice President",
            "Vice President",
            "Director",
            "Senior Manager",
            "Manager",
            "Senior Associate",
            "Specialist",
            "Specialist 2",
            "Associate",
            "Trainee/Apprentice",
            "Administrative",
            "Administrative 2"
        ],
        "additional_job_classification": "Null",
        "company_code": "NA",
        "schedule_type": "Office Schedule (Assigned to user via another automation)",
        "work_week": "Sunday to Saturday",
        "timesheet_template": "France TSD Agile Emp OT",
        "time_entry_approval_path": "Automatic Approval",
        "timesheet_approval": "Hourly/Cont TS Approval Path",
        "timesheet_period": "Weekly without crossing months",
        "time_off_template": "Time Off",
        "time_off_approval": "Hourly TO Approval Path",
        "time_off_types": [
            "Holiday",
            "Leave of Absence"
        ],
        "payrule": "France Hourly OT",
        "time_zone": "(UTC+1:00) Central European Standard Time",
        "holiday_calendar": "France Holiday Calendar",
        "authentication_type": "SSO"
    },
    {
        "country": "France",
        "location": "ALL",
        "worker_type": "Employee",
        "compensation_grade": "Hourly",
        "contract_type": [
            "Full_time",
            "Part_time"
        ],
        "employee_type": [
            "Non-Salaried / Self-Employed",
            "Non-Salaried / Self-Employed (Fixed Term)"
        ],
        "job_category": "Functional",
        "management_level": [
            "CEO",
            "Partner",
            "Executive Vice President",
            "Senior Vice President",
            "Vice President",
            "Director",
            "Senior Manager",
            "Manager",
            "Senior Associate",
            "Specialist",
            "Specialist 2",
            "Associate",
            "Trainee/Apprentice",
            "Administrative",
            "Administrative 2"
        ],
        "additional_job_classification": "Null",
        "company_code": "NA",
        "schedule_type": "Office Schedule (Assigned to user via another automation)",
        "work_week": "Sunday to Saturday",
        "timesheet_template": "France TSD Agile Emp OT",
        "time_entry_approval_path": "Automatic Approval",
        "timesheet_approval": "Hourly/Cont TS Approval Path",
        "timesheet_period": "Weekly without crossing months",
        "time_off_template": "Time Off",
        "time_off_approval": "Non-Salaried/Self-Employed TO Approval",
        "time_off_types": [
            "Holiday",
            "Leave of Absence"
        ],
        "payrule": "France Hourly OT",
        "time_zone": "(UTC+1:00) Central European Standard Time",
        "holiday_calendar": "France Holiday Calendar",
        "authentication_type": "SSO"
    },
    {
        "country": "France",
        "location": "ALL",
        "worker_type": "Employee",
        "compensation_grade": "Salary",
        "contract_type": "Full_time",
        "employee_type": [
            "Regular",
            "Fixed Term",
            "Partner",
            "Intern"
        ],
        "job_category": "Client Services",
        "management_level": [
            "CEO",
            "Partner",
            "Executive Vice President",
            "Senior Vice President",
            "Vice President",
            "Director",
            "Senior Manager",
            "Manager",
            "Senior Associate",
            "Specialist",
            "Specialist 2",
            "Associate",
            "Trainee/Apprentice",
            "Administrative",
            "Administrative 2"
        ],
        "additional_job_classification": "FRA_OT_Policy_A",
        "company_code": "NA",
        "schedule_type": "Office Schedule (Assigned to user via another automation)",
        "work_week": "Sunday to Saturday",
        "timesheet_template": "France TSD Agile Emp OT",
        "time_entry_approval_path": "Automatic Approval",
        "timesheet_approval": "Supervisor",
        "timesheet_period": "Weekly without crossing months",
        "time_off_template": "Time Off",
        "time_off_approval": "System",
        "time_off_types": [
            "FRA_TOIL",
            "Holiday",
            "Leave of Absence"
        ],
        "payrule": "France FT_SAL_Policy_A",
        "time_zone": "(UTC+1:00) Central European Standard Time",
        "holiday_calendar": "France Holiday Calendar",
        "authentication_type": "SSO"
    },
    {
        "country": "France",
        "location": "ALL",
        "worker_type": "Employee",
        "compensation_grade": "Salary",
        "contract_type": "Full_time",
        "employee_type": [
            "Non-Salaried / Self-Employed",
            "Non-Salaried / Self-Employed (Fixed Term)"
        ],
        "job_category": "Client Services",
        "management_level": [
            "CEO",
            "Partner",
            "Executive Vice President",
            "Senior Vice President",
            "Vice President",
            "Director",
            "Senior Manager",
            "Manager",
            "Senior Associate",
            "Specialist",
            "Specialist 2",
            "Associate",
            "Trainee/Apprentice",
            "Administrative",
            "Administrative 2"
        ],
        "additional_job_classification": "FRA_OT_Policy_A",
        "company_code": "NA",
        "schedule_type": "Office Schedule (Assigned to user via another automation)",
        "work_week": "Sunday to Saturday",
        "timesheet_template": "France TSD Agile Emp OT",
        "time_entry_approval_path": "Automatic Approval",
        "timesheet_approval": "Supervisor",
        "timesheet_period": "Weekly without crossing months",
        "time_off_template": "Time Off",
        "time_off_approval": "Non-Salaried/Self-Employed TO Approval",
        "time_off_types": [
            "FRA_TOIL",
            "Holiday",
            "Leave of Absence"
        ],
        "payrule": "France FT_SAL_Policy_A",
        "time_zone": "(UTC+1:00) Central European Standard Time",
        "holiday_calendar": "France Holiday Calendar",
        "authentication_type": "SSO"
    },
    {
        "country": "France",
        "location": "ALL",
        "worker_type": "Employee",
        "compensation_grade": "Salary",
        "contract_type": "Part_time",
        "employee_type": [
            "Regular",
            "Fixed Term",
            "Partner",
            "Intern"
        ],
        "job_category": "Client Services",
        "management_level": [
            "CEO",
            "Partner",
            "Executive Vice President",
            "Senior Vice President",
            "Vice President",
            "Director",
            "Senior Manager",
            "Manager",
            "Senior Associate",
            "Specialist",
            "Specialist 2",
            "Associate",
            "Trainee/Apprentice",
            "Administrative",
            "Administrative 2"
        ],
        "additional_job_classification": "FRA_OT_Policy_A",
        "company_code": "NA",
        "schedule_type": "Office Schedule (Assigned to user via another automation)",
        "work_week": "Sunday to Saturday",
        "timesheet_template": "France TSD Agile Emp OT",
        "time_entry_approval_path": "Automatic Approval",
        "timesheet_approval": "Supervisor",
        "timesheet_period": "Weekly without crossing months",
        "time_off_template": "Time Off",
        "time_off_approval": "System",
        "time_off_types": [
            "FRA_TOIL",
            "Holiday",
            "Leave of Absence"
        ],
        "payrule": "France PT_SAL_Policy_A",
        "time_zone": "(UTC+1:00) Central European Standard Time",
        "holiday_calendar": "France Holiday Calendar",
        "authentication_type": "SSO"
    },
    {
        "country": "France",
        "location": "ALL",
        "worker_type": "Employee",
        "compensation_grade": "Salary",
        "contract_type": "Part_time",
        "employee_type": [
            "Non-Salaried / Self-Employed",
            "Non-Salaried / Self-Employed (Fixed Term)"
        ],
        "job_category": "Client Services",
        "management_level": [
            "CEO",
            "Partner",
            "Executive Vice President",
            "Senior Vice President",
            "Vice President",
            "Director",
            "Senior Manager",
            "Manager",
            "Senior Associate",
            "Specialist",
            "Specialist 2",
            "Associate",
            "Trainee/Apprentice",
            "Administrative",
            "Administrative 2"
        ],
        "additional_job_classification": "FRA_OT_Policy_A",
        "company_code": "NA",
        "schedule_type": "Office Schedule (Assigned to user via another automation)",
        "work_week": "Sunday to Saturday",
        "timesheet_template": "France TSD Agile Emp OT",
        "time_entry_approval_path": "Automatic Approval",
        "timesheet_approval": "Supervisor",
        "timesheet_period": "Weekly without crossing months",
        "time_off_template": "Time Off",
        "time_off_approval": "Non-Salaried/Self-Employed TO Approval",
        "time_off_types": [
            "FRA_TOIL",
            "Holiday",
            "Leave of Absence"
        ],
        "payrule": "France PT_SAL_Policy_A",
        "time_zone": "(UTC+1:00) Central European Standard Time",
        "holiday_calendar": "France Holiday Calendar",
        "authentication_type": "SSO"
    },
    {
        "country": "France",
        "location": "ALL",
        "worker_type": "Employee",
        "compensation_grade": "Salary",
        "contract_type": "Full_time",
        "employee_type": [
            "Regular",
            "Fixed Term",
            "Partner",
            "Intern"
        ],
        "job_category": "Client Services",
        "management_level": [
            "CEO",
            "Partner",
            "Executive Vice President",
            "Senior Vice President",
            "Vice President",
            "Director",
            "Senior Manager",
            "Manager",
            "Senior Associate",
            "Specialist",
            "Specialist 2",
            "Associate",
            "Trainee/Apprentice",
            "Administrative",
            "Administrative 2"
        ],
        "additional_job_classification": "FRA_OT_Policy_B",
        "company_code": "NA",
        "schedule_type": "Office Schedule (Assigned to user via another automation)",
        "work_week": "Sunday to Saturday",
        "timesheet_template": "France TSD Agile Emp OT",
        "time_entry_approval_path": "Automatic Approval",
        "timesheet_approval": "Supervisor",
        "timesheet_period": "Weekly without crossing months",
        "time_off_template": "Time Off",
        "time_off_approval": "System",
        "time_off_types": [
            "FRA_TOIL",
            "Holiday",
            "Leave of Absence"
        ],
        "payrule": "France FT_SAL_Policy_B",
        "time_zone": "(UTC+1:00) Central European Standard Time",
        "holiday_calendar": "France Holiday Calendar",
        "authentication_type": "SSO"
    },
    {
        "country": "France",
        "location": "ALL",
        "worker_type": "Employee",
        "compensation_grade": "Salary",
        "contract_type": "Full_time",
        "employee_type": [
            "Non-Salaried / Self-Employed",
            "Non-Salaried / Self-Employed (Fixed Term)"
        ],
        "job_category": "Client Services",
        "management_level": [
            "CEO",
            "Partner",
            "Executive Vice President",
            "Senior Vice President",
            "Vice President",
            "Director",
            "Senior Manager",
            "Manager",
            "Senior Associate",
            "Specialist",
            "Specialist 2",
            "Associate",
            "Trainee/Apprentice",
            "Administrative",
            "Administrative 2"
        ],
        "additional_job_classification": "FRA_OT_Policy_B",
        "company_code": "NA",
        "schedule_type": "Office Schedule (Assigned to user via another automation)",
        "work_week": "Sunday to Saturday",
        "timesheet_template": "France TSD Agile Emp OT",
        "time_entry_approval_path": "Automatic Approval",
        "timesheet_approval": "Supervisor",
        "timesheet_period": "Weekly without crossing months",
        "time_off_template": "Time Off",
        "time_off_approval": "Non-Salaried/Self-Employed TO Approval",
        "time_off_types": [
            "FRA_TOIL",
            "Holiday",
            "Leave of Absence"
        ],
        "payrule": "France FT_SAL_Policy_B",
        "time_zone": "(UTC+1:00) Central European Standard Time",
        "holiday_calendar": "France Holiday Calendar",
        "authentication_type": "SSO"
    },
    {
        "country": "France",
        "location": "ALL",
        "worker_type": "Employee",
        "compensation_grade": "Salary",
        "contract_type": "Part_time",
        "employee_type": [
            "Regular",
            "Fixed Term",
            "Partner",
            "Intern"
        ],
        "job_category": "Client Services",
        "management_level": [
            "CEO",
            "Partner",
            "Executive Vice President",
            "Senior Vice President",
            "Vice President",
            "Director",
            "Senior Manager",
            "Manager",
            "Senior Associate",
            "Specialist",
            "Specialist 2",
            "Associate",
            "Trainee/Apprentice",
            "Administrative",
            "Administrative 2"
        ],
        "additional_job_classification": "FRA_OT_Policy_B",
        "company_code": "NA",
        "schedule_type": "Office Schedule (Assigned to user via another automation)",
        "work_week": "Sunday to Saturday",
        "timesheet_template": "France TSD Agile Emp OT",
        "time_entry_approval_path": "Automatic Approval",
        "timesheet_approval": "Supervisor",
        "timesheet_period": "Weekly without crossing months",
        "time_off_template": "Time Off",
        "time_off_approval": "System",
        "time_off_types": [
            "FRA_TOIL",
            "Holiday",
            "Leave of Absence"
        ],
        "payrule": "France PT_SAL_Policy_B ",
        "time_zone": "(UTC+1:00) Central European Standard Time",
        "holiday_calendar": "France Holiday Calendar",
        "authentication_type": "SSO"
    },
    {
        "country": "France",
        "location": "ALL",
        "worker_type": "Employee",
        "compensation_grade": "Salary",
        "contract_type": "Part_time",
        "employee_type": [
            "Non-Salaried / Self-Employed",
            "Non-Salaried / Self-Employed (Fixed Term)"
        ],
        "job_category": "Client Services",
        "management_level": [
            "CEO",
            "Partner",
            "Executive Vice President",
            "Senior Vice President",
            "Vice President",
            "Director",
            "Senior Manager",
            "Manager",
            "Senior Associate",
            "Specialist",
            "Specialist 2",
            "Associate",
            "Trainee/Apprentice",
            "Administrative",
            "Administrative 2"
        ],
        "additional_job_classification": "FRA_OT_Policy_B",
        "company_code": "NA",
        "schedule_type": "Office Schedule (Assigned to user via another automation)",
        "work_week": "Sunday to Saturday",
        "timesheet_template": "France TSD Agile Emp OT",
        "time_entry_approval_path": "Automatic Approval",
        "timesheet_approval": "Supervisor",
        "timesheet_period": "Weekly without crossing months",
        "time_off_template": "Time Off",
        "time_off_approval": "Non-Salaried/Self-Employed TO Approval",
        "time_off_types": [
            "FRA_TOIL",
            "Holiday",
            "Leave of Absence"
        ],
        "payrule": "France PT_SAL_Policy_B ",
        "time_zone": "(UTC+1:00) Central European Standard Time",
        "holiday_calendar": "France Holiday Calendar",
        "authentication_type": "SSO"
    },
    {
        "country": "France",
        "location": "ALL",
        "worker_type": "Employee",
        "compensation_grade": "Salary",
        "contract_type": [
            "Full_time",
            "Part_time"
        ],
        "employee_type": [
            "Regular",
            "Fixed Term",
            "Partner",
            "Intern"
        ],
        "job_category": "Client Services",
        "management_level": [
            "CEO",
            "Partner",
            "Executive Vice President",
            "Senior Vice President",
            "Vice President",
            "Director",
            "Senior Manager",
            "Manager",
            "Senior Associate",
            "Specialist",
            "Specialist 2",
            "Associate",
            "Trainee/Apprentice",
            "Administrative",
            "Administrative 2"
        ],
        "additional_job_classification": "Null",
        "company_code": "NA",
        "schedule_type": "Office Schedule (Assigned to user via another automation)",
        "work_week": "Sunday to Saturday",
        "timesheet_template": "France TSD Agile Emp NON-OT",
        "time_entry_approval_path": "Automatic Approval",
        "timesheet_approval": "Supervisor",
        "timesheet_period": "Weekly without crossing months",
        "time_off_template": "Time Off",
        "time_off_approval": "System",
        "time_off_types": [
            "Holiday",
            "Leave of Absence"
        ],
        "payrule": "France NON-OT",
        "time_zone": "(UTC+1:00) Central European Standard Time",
        "holiday_calendar": "France Holiday Calendar",
        "authentication_type": "SSO"
    },
    {
        "country": "France",
        "location": "ALL",
        "worker_type": "Employee",
        "compensation_grade": "Salary",
        "contract_type": [
            "Full_time",
            "Part_time"
        ],
        "employee_type": [
            "Non-Salaried / Self-Employed",
            "Non-Salaried / Self-Employed (Fixed Term)"
        ],
        "job_category": "Client Services",
        "management_level": [
            "CEO",
            "Partner",
            "Executive Vice President",
            "Senior Vice President",
            "Vice President",
            "Director",
            "Senior Manager",
            "Manager",
            "Senior Associate",
            "Specialist",
            "Specialist 2",
            "Associate",
            "Trainee/Apprentice",
            "Administrative",
            "Administrative 2"
        ],
        "additional_job_classification": "Null",
        "company_code": "NA",
        "schedule_type": "Office Schedule (Assigned to user via another automation)",
        "work_week": "Sunday to Saturday",
        "timesheet_template": "France TSD Agile Emp NON-OT",
        "time_entry_approval_path": "Automatic Approval",
        "timesheet_approval": "Supervisor",
        "timesheet_period": "Weekly without crossing months",
        "time_off_template": "Time Off",
        "time_off_approval": "Non-Salaried/Self-Employed TO Approval",
        "time_off_types": [
            "Holiday",
            "Leave of Absence"
        ],
        "payrule": "France NON-OT",
        "time_zone": "(UTC+1:00) Central European Standard Time",
        "holiday_calendar": "France Holiday Calendar",
        "authentication_type": "SSO"
    },
    {
        "country": "France",
        "location": "ALL",
        "worker_type": "Employee",
        "compensation_grade": "Hourly",
        "contract_type": [
            "Full_time",
            "Part_time"
        ],
        "employee_type": [
            "Regular",
            "Fixed Term",
            "Partner",
            "Intern"
        ],
        "job_category": "Client Services",
        "management_level": [
            "CEO",
            "Partner",
            "Executive Vice President",
            "Senior Vice President",
            "Vice President",
            "Director",
            "Senior Manager",
            "Manager",
            "Senior Associate",
            "Specialist",
            "Specialist 2",
            "Associate",
            "Trainee/Apprentice",
            "Administrative",
            "Administrative 2"
        ],
        "additional_job_classification": "Null",
        "company_code": "NA",
        "schedule_type": "Office Schedule (Assigned to user via another automation)",
        "work_week": "Sunday to Saturday",
        "timesheet_template": "France TSD Agile Emp OT",
        "time_entry_approval_path": "Automatic Approval",
        "timesheet_approval": "Hourly/Cont TS Approval Path",
        "timesheet_period": "Weekly without crossing months",
        "time_off_template": "Time Off",
        "time_off_approval": "Hourly TO Approval Path",
        "time_off_types": [
            "Holiday",
            "Leave of Absence"
        ],
        "payrule": "France Hourly OT",
        "time_zone": "(UTC+1:00) Central European Standard Time",
        "holiday_calendar": "France Holiday Calendar",
        "authentication_type": "SSO"
    },
    {
        "country": "France",
        "location": "ALL",
        "worker_type": "Employee",
        "compensation_grade": "Hourly",
        "contract_type": [
            "Full_time",
            "Part_time"
        ],
        "employee_type": [
            "Non-Salaried / Self-Employed",
            "Non-Salaried / Self-Employed (Fixed Term)"
        ],
        "job_category": "Client Services",
        "management_level": [
            "CEO",
            "Partner",
            "Executive Vice President",
            "Senior Vice President",
            "Vice President",
            "Director",
            "Senior Manager",
            "Manager",
            "Senior Associate",
            "Specialist",
            "Specialist 2",
            "Associate",
            "Trainee/Apprentice",
            "Administrative",
            "Administrative 2"
        ],
        "additional_job_classification": "Null",
        "company_code": "NA",
        "schedule_type": "Office Schedule (Assigned to user via another automation)",
        "work_week": "Sunday to Saturday",
        "timesheet_template": "France TSD Agile Emp OT",
        "time_entry_approval_path": "Automatic Approval",
        "timesheet_approval": "Hourly/Cont TS Approval Path",
        "timesheet_period": "Weekly without crossing months",
        "time_off_template": "Time Off",
        "time_off_approval": "Non-Salaried/Self-Employed TO Approval",
        "time_off_types": [
            "Holiday",
            "Leave of Absence"
        ],
        "payrule": "France Hourly OT",
        "time_zone": "(UTC+1:00) Central European Standard Time",
        "holiday_calendar": "France Holiday Calendar",
        "authentication_type": "SSO"
    },
    {
        "country": "France",
        "location": "ALL",
        "worker_type": "Contingent Worker",
        "compensation_grade": "NA",
        "contract_type": [
            "Full_time",
            "Part_time"
        ],
        "employee_type": [
            "Agency Contractor",
            "Alliance/Perimeter Worker",
            "Direct Contractor",
            "Vendor",
            "Intern"
        ],
        "job_category": "Indirect_Labor",
        "management_level": [
            "CEO",
            "Partner",
            "Executive Vice President",
            "Senior Vice President",
            "Vice President",
            "Director",
            "Senior Manager",
            "Manager",
            "Senior Associate",
            "Specialist",
            "Specialist 2",
            "Associate",
            "Trainee/Apprentice",
            "Administrative",
            "Administrative 2"
        ],
        "additional_job_classification": "NA",
        "company_code": "NA",
        "schedule_type": "Office Schedule (Assigned to user via another automation)",
        "work_week": "Sunday to Saturday",
        "timesheet_template": "Vialto TSD Agile Contingent",
        "time_entry_approval_path": "Automatic Approval",
        "timesheet_approval": "Hourly/Cont TS Approval Path",
        "timesheet_period": "Weekly without crossing months",
        "time_off_template": "NA",
        "time_off_approval": "NA",
        "time_off_types": "NA",
        "payrule": "Vialto Dummy Pay Rule",
        "time_zone": "(UTC+1:00) Central European Standard Time",
        "holiday_calendar": "NA",
        "authentication_type": "SSO"
    }
]
