region = 'us-east-1'
environment = 'pre-production'
instance = "JJMaintenanceIncSB"
company_key = 'JJMaintenanceIncSB'
replicon_conn_id = f'replicon_{company_key}'
deltek_cospoint_conn_id = f'deltek_costpoint_{company_key}'
last_run_date_var_name = f'{company_key}_deltek_costpoint_timesheet_sync_last_run_date'
time_zone = 'US/Eastern'
execution_timeout_days = 14
child_dag_max_active_runs = 2
can_run_batch_task_var_name = f'cospoint_timesheet_export_can_run_batch_task_{instance}'
group_by_project_var_name = f'cospoint_timesheet_export_group_by_project_{instance}'
pay_type_oef_var_name = f'cospoint_timesheet_export_pay_type_oef_name_{instance}'
tenant_email = 'MPTeamReplicon@deltek.com'
internal_email = 'MPTeamReplicon@deltek.com'
line_type = 'A'
regular_pay_type = 'R'
mo_line_type = 'M'
activity_type = 'Activity Type'
work_center = 'Work Center'
cp_rep_webhook_secret = "cp_rep_jjmaintenanceincsb_webhook_secret"
proj_mo_project_flag = 'Is MO Project ?'
proj_referance_project_id = 'Build Project'