momentive_thailand_mapper = [
    {
        'type': 'Schedule',
        'workertype': 'Employee',
        'location': 'TH Bangkok',
        'exemptstatus': 'Yes',
        'shift': 'Null',
        'gender': 'Male',
        'cost_center': 'Any',
        'value': 'M-F 8 hours',
    },
    {
        'type': 'Schedule',
        'workertype': 'Employee',
        'location': 'TH Bangkok',
        'exemptstatus': 'Yes',
        'shift': 'Day Shift',
        'gender': 'Male',
        'cost_center': 'Any',
        'value': 'M-F 8 hours',
    },
    {
        'type': 'Schedule',
        'workertype': 'Employee',
        'location': 'TH Bangkok',
        'exemptstatus': 'No',
        'shift': 'Shift A',
        'gender': 'Male',
        'cost_center': 'Any',
        'value': 'Shift',
    },
    {
        'type': 'Schedule',
        'workertype': 'Employee',
        'location': 'TH Bangkok',
        'exemptstatus': 'No',
        'shift': 'Shift B',
        'gender': 'Male',
        'cost_center': 'Any',
        'value': 'Shift',
    },
    {
        'type': 'Schedule',
        'workertype': 'Employee',
        'location': 'TH Bangkok',
        'exemptstatus': 'No',
        'shift': 'Shift C',
        'gender': 'Male',
        'cost_center': 'Any',
        'value': 'Shift',
    },
    {
        'type': 'Schedule',
        'workertype': 'Employee',
        'location': 'TH Bangkok',
        'exemptstatus': 'No',
        'shift': 'Shift D',
        'gender': 'Male',
        'cost_center': 'Any',
        'value': 'Shift',
    },
    {
        'type': 'Schedule',
        'workertype': 'Employee',
        'location': 'TH Bangkok',
        'exemptstatus': 'No',
        'shift': 'Day Shift',
        'gender': 'Male',
        'cost_center': 'Any',
        'value': 'M-F 8 hours',
    },
    {
        'type': 'Schedule',
        'workertype': 'Employee',
        'location': 'TH Bangkok',
        'exemptstatus': 'No',
        'shift': 'Null',
        'gender': 'Male',
        'cost_center': 'Any',
        'value': 'M-F 8 hours',
    },
    {
        'type': 'Schedule',
        'workertype': 'Employee',
        'location': 'TH Bangkok',
        'exemptstatus': 'No',
        'shift': 'Day Shift',
        'gender': 'Male',
        'cost_center': 'T30930',
        'value': 'M-F 8 hours',
    },
    {
        'type': 'Schedule',
        'workertype': 'Employee',
        'location': 'TH Bangkok',
        'exemptstatus': 'No',
        'shift': 'Null',
        'gender': 'Male',
        'cost_center': 'T30930',
        'value': 'M-F 8 hours',
    },
    {
        'type': 'Schedule',
        'workertype': 'Contingent Worker',
        'location': 'TH Bangkok',
        'exemptstatus': 'No',
        'shift': 'Day Shift',
        'gender': 'Any',
        'cost_center': 'Any',
        'value': 'M-F 8 hours',
    },
    {
        'type': 'Schedule',
        'workertype': 'Contingent Worker',
        'location': 'TH Bangkok',
        'exemptstatus': 'No',
        'shift': 'Null',
        'gender': 'Any',
        'cost_center': 'Any',
        'value': 'M-F 8 hours',
    },
    {
        'type': 'Schedule',
        'workertype': 'Employee',
        'location': 'TH Bangkok',
        'exemptstatus': 'Yes',
        'shift': 'Null',
        'gender': 'Female',
        'cost_center': 'Any',
        'value': 'M-F 8 hours',
    },
    {
        'type': 'Schedule',
        'workertype': 'Employee',
        'location': 'TH Bangkok',
        'exemptstatus': 'Yes',
        'shift': 'Day Shift',
        'gender': 'Female',
        'cost_center': 'Any',
        'value': 'M-F 8 hours',
    },
    {
        'type': 'Schedule',
        'workertype': 'Employee',
        'location': 'TH Bangkok',
        'exemptstatus': 'No',
        'shift': 'Shift A',
        'gender': 'Female',
        'cost_center': 'Any',
        'value': 'Shift',
    },
    {
        'type': 'Schedule',
        'workertype': 'Employee',
        'location': 'TH Bangkok',
        'exemptstatus': 'No',
        'shift': 'Shift B',
        'gender': 'Female',
        'cost_center': 'Any',
        'value': 'Shift',
    },
    {
        'type': 'Schedule',
        'workertype': 'Employee',
        'location': 'TH Bangkok',
        'exemptstatus': 'No',
        'shift': 'Shift C',
        'gender': 'Female',
        'cost_center': 'Any',
        'value': 'Shift',
    },
    {
        'type': 'Schedule',
        'workertype': 'Employee',
        'location': 'TH Bangkok',
        'exemptstatus': 'No',
        'shift': 'Shift D',
        'gender': 'Female',
        'cost_center': 'Any',
        'value': 'Shift',
    },
    {
        'type': 'Schedule',
        'workertype': 'Employee',
        'location': 'TH Bangkok',
        'exemptstatus': 'No',
        'shift': 'Day Shift',
        'gender': 'Female',
        'cost_center': 'Any',
        'value': 'M-F 8 hours',
    },
    {
        'type': 'Schedule',
        'workertype': 'Employee',
        'location': 'TH Bangkok',
        'exemptstatus': 'No',
        'shift': 'Null',
        'gender': 'Female',
        'cost_center': 'Any',
        'value': 'M-F 8 hours',
    },
    {
        'type': 'Schedule',
        'workertype': 'Employee',
        'location': 'TH Bangkok',
        'exemptstatus': 'No',
        'shift': 'Day Shift',
        'gender': 'Female',
        'cost_center': 'T30930',
        'value': 'M-F 8 hours',
    },
    {
        'type': 'Schedule',
        'workertype': 'Employee',
        'location': 'TH Bangkok',
        'exemptstatus': 'No',
        'shift': 'Null',
        'gender': 'Female',
        'cost_center': 'T30930',
        'value': 'M-F 8 hours',
    },
    {
        'type': 'Schedule',
        'workertype': 'Contingent Worker',
        'location': 'TH Bangkok',
        'exemptstatus': 'No',
        'shift': 'Day Shift',
        'gender': 'Any',
        'cost_center': 'Any',
        'value': 'M-F 8 hours',
    },
    {
        'type': 'Schedule',
        'workertype': 'Contingent Worker',
        'location': 'TH Bangkok',
        'exemptstatus': 'No',
        'shift': 'Null',
        'gender': 'Any',
        'cost_center': 'Any',
        'value': 'M-F 8 hours',
    },
    {
        'type': 'Schedule',
        'workertype': 'Employee',
        'location': 'TH Rayong',
        'exemptstatus': 'Yes',
        'shift': 'Null',
        'gender': 'Female',
        'cost_center': 'Any',
        'value': 'M-F 8 hours',
    },
    {
        'type': 'Schedule',
        'workertype': 'Employee',
        'location': 'TH Rayong',
        'exemptstatus': 'Yes',
        'shift': 'Day Shift',
        'gender': 'Female',
        'cost_center': 'Any',
        'value': 'M-F 8 hours',
    },
    {
        'type': 'Schedule',
        'workertype': 'Employee',
        'location': 'TH Rayong',
        'exemptstatus': 'No',
        'shift': 'Shift A',
        'gender': 'Female',
        'cost_center': 'Any',
        'value': 'Shift',
    },
    {
        'type': 'Schedule',
        'workertype': 'Employee',
        'location': 'TH Rayong',
        'exemptstatus': 'No',
        'shift': 'Shift B',
        'gender': 'Female',
        'cost_center': 'Any',
        'value': 'Shift',
    },
    {
        'type': 'Schedule',
        'workertype': 'Employee',
        'location': 'TH Rayong',
        'exemptstatus': 'No',
        'shift': 'Shift C',
        'gender': 'Female',
        'cost_center': 'Any',
        'value': 'Shift',
    },
    {
        'type': 'Schedule',
        'workertype': 'Employee',
        'location': 'TH Rayong',
        'exemptstatus': 'No',
        'shift': 'Shift D',
        'gender': 'Female',
        'cost_center': 'Any',
        'value': 'Shift',
    },
    {
        'type': 'Schedule',
        'workertype': 'Employee',
        'location': 'TH Rayong',
        'exemptstatus': 'No',
        'shift': 'Day Shift',
        'gender': 'Female',
        'cost_center': 'Any',
        'value': 'M-F 8 hours',
    },
    {
        'type': 'Schedule',
        'workertype': 'Employee',
        'location': 'TH Rayong',
        'exemptstatus': 'No',
        'shift': 'Null',
        'gender': 'Female',
        'cost_center': 'Any',
        'value': 'M-F 8 hours',
    },
    {
        'type': 'Schedule',
        'workertype': 'Employee',
        'location': 'TH Rayong',
        'exemptstatus': 'No',
        'shift': 'Day Shift',
        'gender': 'Female',
        'cost_center': 'T30930',
        'value': 'M-F 8 hours',
    },
    {
        'type': 'Schedule',
        'workertype': 'Employee',
        'location': 'TH Rayong',
        'exemptstatus': 'No',
        'shift': 'Null',
        'gender': 'Female',
        'cost_center': 'T30930',
        'value': 'M-F 8 hours',
    },
    {
        'type': 'Schedule',
        'workertype': 'Contingent Worker',
        'location': 'TH Rayong',
        'exemptstatus': 'No',
        'shift': 'Day Shift',
        'gender': 'Any',
        'cost_center': 'Any',
        'value': 'M-F 8 hours',
    },
    {
        'type': 'Schedule',
        'workertype': 'Contingent Worker',
        'location': 'TH Rayong',
        'exemptstatus': 'No',
        'shift': 'Null',
        'gender': 'Any',
        'cost_center': 'Any',
        'value': 'M-F 8 hours',
    },
    {
        'type': 'Schedule',
        'workertype': 'Employee',
        'location': 'TH Rayong',
        'exemptstatus': 'Yes',
        'shift': 'Null',
        'gender': 'Male',
        'cost_center': 'Any',
        'value': 'M-F 8 hours',
    },
    {
        'type': 'Schedule',
        'workertype': 'Employee',
        'location': 'TH Rayong',
        'exemptstatus': 'Yes',
        'shift': 'Day Shift',
        'gender': 'Male',
        'cost_center': 'Any',
        'value': 'M-F 8 hours',
    },
    {
        'type': 'Schedule',
        'workertype': 'Employee',
        'location': 'TH Rayong',
        'exemptstatus': 'No',
        'shift': 'Shift A',
        'gender': 'Male',
        'cost_center': 'Any',
        'value': 'Shift',
    },
    {
        'type': 'Schedule',
        'workertype': 'Employee',
        'location': 'TH Rayong',
        'exemptstatus': 'No',
        'shift': 'Shift B',
        'gender': 'Male',
        'cost_center': 'Any',
        'value': 'Shift',
    },
    {
        'type': 'Schedule',
        'workertype': 'Employee',
        'location': 'TH Rayong',
        'exemptstatus': 'No',
        'shift': 'Shift C',
        'gender': 'Male',
        'cost_center': 'Any',
        'value': 'Shift',
    },
    {
        'type': 'Schedule',
        'workertype': 'Employee',
        'location': 'TH Rayong',
        'exemptstatus': 'No',
        'shift': 'Shift D',
        'gender': 'Male',
        'cost_center': 'Any',
        'value': 'Shift',
    },
    {
        'type': 'Schedule',
        'workertype': 'Employee',
        'location': 'TH Rayong',
        'exemptstatus': 'No',
        'shift': 'Day Shift',
        'gender': 'Male',
        'cost_center': 'Any',
        'value': 'M-F 8 hours',
    },
    {
        'type': 'Schedule',
        'workertype': 'Employee',
        'location': 'TH Rayong',
        'exemptstatus': 'No',
        'shift': 'Null',
        'gender': 'Male',
        'cost_center': 'Any',
        'value': 'M-F 8 hours',
    },
    {
        'type': 'Schedule',
        'workertype': 'Employee',
        'location': 'TH Rayong',
        'exemptstatus': 'No',
        'shift': 'Day Shift',
        'gender': 'Male',
        'cost_center': 'T30930',
        'value': 'M-F 8 hours',
    },
    {
        'type': 'Schedule',
        'workertype': 'Employee',
        'location': 'TH Rayong',
        'exemptstatus': 'No',
        'shift': 'Null',
        'gender': 'Male',
        'cost_center': 'T30930',
        'value': 'M-F 8 hours',
    },
    {
        'type': 'Schedule',
        'workertype': 'Contingent Worker',
        'location': 'TH Rayong',
        'exemptstatus': 'No',
        'shift': 'Day Shift',
        'gender': 'Any',
        'cost_center': 'Any',
        'value': 'M-F 8 hours',
    },
    {
        'type': 'Schedule',
        'workertype': 'Contingent Worker',
        'location': 'TH Rayong',
        'exemptstatus': 'No',
        'shift': 'Null',
        'gender': 'Any',
        'cost_center': 'Any',
        'value': 'M-F 8 hours',
    },
    {
        'type': 'Payrule',
        'workertype': 'Employee',
        'location': 'TH Bangkok',
        'exemptstatus': 'Yes',
        'shift': 'Null',
        'gender': 'Male',
        'cost_center': 'Any',
        'value': 'No Payrule',
    },
    {
        'type': 'Payrule',
        'workertype': 'Employee',
        'location': 'TH Bangkok',
        'exemptstatus': 'Yes',
        'shift': 'Day Shift',
        'gender': 'Male',
        'cost_center': 'Any',
        'value': 'No Payrule',
    },
    {
        'type': 'Payrule',
        'workertype': 'Employee',
        'location': 'TH Bangkok',
        'exemptstatus': 'No',
        'shift': 'Shift A',
        'gender': 'Male',
        'cost_center': 'Any',
        'value': 'No Payrule',
    },
    {
        'type': 'Payrule',
        'workertype': 'Employee',
        'location': 'TH Bangkok',
        'exemptstatus': 'No',
        'shift': 'Shift B',
        'gender': 'Male',
        'cost_center': 'Any',
        'value': 'No Payrule',
    },
    {
        'type': 'Payrule',
        'workertype': 'Employee',
        'location': 'TH Bangkok',
        'exemptstatus': 'No',
        'shift': 'Shift C',
        'gender': 'Male',
        'cost_center': 'Any',
        'value': 'No Payrule',
    },
    {
        'type': 'Payrule',
        'workertype': 'Employee',
        'location': 'TH Bangkok',
        'exemptstatus': 'No',
        'shift': 'Shift D',
        'gender': 'Male',
        'cost_center': 'Any',
        'value': 'No Payrule',
    },
    {
        'type': 'Payrule',
        'workertype': 'Employee',
        'location': 'TH Bangkok',
        'exemptstatus': 'No',
        'shift': 'Day Shift',
        'gender': 'Male',
        'cost_center': 'Any',
        'value': 'No Payrule',
    },
    {
        'type': 'Payrule',
        'workertype': 'Employee',
        'location': 'TH Bangkok',
        'exemptstatus': 'No',
        'shift': 'Null',
        'gender': 'Male',
        'cost_center': 'Any',
        'value': 'No Payrule',
    },
    {
        'type': 'Payrule',
        'workertype': 'Employee',
        'location': 'TH Bangkok',
        'exemptstatus': 'No',
        'shift': 'Day Shift',
        'gender': 'Male',
        'cost_center': 'T30930',
        'value': 'No Payrule',
    },
    {
        'type': 'Payrule',
        'workertype': 'Employee',
        'location': 'TH Bangkok',
        'exemptstatus': 'No',
        'shift': 'Null',
        'gender': 'Male',
        'cost_center': 'T30930',
        'value': 'No Payrule',
    },
    {
        'type': 'Payrule',
        'workertype': 'Contingent Worker',
        'location': 'TH Bangkok',
        'exemptstatus': 'No',
        'shift': 'Day Shift',
        'gender': 'Any',
        'cost_center': 'Any',
        'value': 'No Payrule',
    },
    {
        'type': 'Payrule',
        'workertype': 'Contingent Worker',
        'location': 'TH Bangkok',
        'exemptstatus': 'No',
        'shift': 'Null',
        'gender': 'Any',
        'cost_center': 'Any',
        'value': 'No Payrule',
    },
    {
        'type': 'Payrule',
        'workertype': 'Employee',
        'location': 'TH Bangkok',
        'exemptstatus': 'Yes',
        'shift': 'Null',
        'gender': 'Female',
        'cost_center': 'Any',
        'value': 'No Payrule',
    },
    {
        'type': 'Payrule',
        'workertype': 'Employee',
        'location': 'TH Bangkok',
        'exemptstatus': 'Yes',
        'shift': 'Day Shift',
        'gender': 'Female',
        'cost_center': 'Any',
        'value': 'No Payrule',
    },
    {
        'type': 'Payrule',
        'workertype': 'Employee',
        'location': 'TH Bangkok',
        'exemptstatus': 'No',
        'shift': 'Shift A',
        'gender': 'Female',
        'cost_center': 'Any',
        'value': 'No Payrule',
    },
    {
        'type': 'Payrule',
        'workertype': 'Employee',
        'location': 'TH Bangkok',
        'exemptstatus': 'No',
        'shift': 'Shift B',
        'gender': 'Female',
        'cost_center': 'Any',
        'value': 'No Payrule',
    },
    {
        'type': 'Payrule',
        'workertype': 'Employee',
        'location': 'TH Bangkok',
        'exemptstatus': 'No',
        'shift': 'Shift C',
        'gender': 'Female',
        'cost_center': 'Any',
        'value': 'No Payrule',
    },
    {
        'type': 'Payrule',
        'workertype': 'Employee',
        'location': 'TH Bangkok',
        'exemptstatus': 'No',
        'shift': 'Shift D',
        'gender': 'Female',
        'cost_center': 'Any',
        'value': 'No Payrule',
    },
    {
        'type': 'Payrule',
        'workertype': 'Employee',
        'location': 'TH Bangkok',
        'exemptstatus': 'No',
        'shift': 'Day Shift',
        'gender': 'Female',
        'cost_center': 'Any',
        'value': 'No Payrule',
    },
    {
        'type': 'Payrule',
        'workertype': 'Employee',
        'location': 'TH Bangkok',
        'exemptstatus': 'No',
        'shift': 'Null',
        'gender': 'Female',
        'cost_center': 'Any',
        'value': 'No Payrule',
    },
    {
        'type': 'Payrule',
        'workertype': 'Employee',
        'location': 'TH Bangkok',
        'exemptstatus': 'No',
        'shift': 'Day Shift',
        'gender': 'Female',
        'cost_center': 'T30930',
        'value': 'No Payrule',
    },
    {
        'type': 'Payrule',
        'workertype': 'Employee',
        'location': 'TH Bangkok',
        'exemptstatus': 'No',
        'shift': 'Null',
        'gender': 'Female',
        'cost_center': 'T30930',
        'value': 'No Payrule',
    },
    {
        'type': 'Payrule',
        'workertype': 'Contingent Worker',
        'location': 'TH Bangkok',
        'exemptstatus': 'No',
        'shift': 'Day Shift',
        'gender': 'Any',
        'cost_center': 'Any',
        'value': 'No Payrule',
    },
    {
        'type': 'Payrule',
        'workertype': 'Contingent Worker',
        'location': 'TH Bangkok',
        'exemptstatus': 'No',
        'shift': 'Null',
        'gender': 'Any',
        'cost_center': 'Any',
        'value': 'No Payrule',
    },
    {
        'type': 'Payrule',
        'workertype': 'Employee',
        'location': 'TH Rayong',
        'exemptstatus': 'Yes',
        'shift': 'Null',
        'gender': 'Female',
        'cost_center': 'Any',
        'value': 'No Payrule',
    },
    {
        'type': 'Payrule',
        'workertype': 'Employee',
        'location': 'TH Rayong',
        'exemptstatus': 'Yes',
        'shift': 'Day Shift',
        'gender': 'Female',
        'cost_center': 'Any',
        'value': 'No Payrule',
    },
    {
        'type': 'Payrule',
        'workertype': 'Employee',
        'location': 'TH Rayong',
        'exemptstatus': 'No',
        'shift': 'Shift A',
        'gender': 'Female',
        'cost_center': 'Any',
        'value': 'Thai_Non-Exempt - Shift Staff',
    },
    {
        'type': 'Payrule',
        'workertype': 'Employee',
        'location': 'TH Rayong',
        'exemptstatus': 'No',
        'shift': 'Shift B',
        'gender': 'Female',
        'cost_center': 'Any',
        'value': 'Thai_Non-Exempt - Shift Staff',
    },
    {
        'type': 'Payrule',
        'workertype': 'Employee',
        'location': 'TH Rayong',
        'exemptstatus': 'No',
        'shift': 'Shift C',
        'gender': 'Female',
        'cost_center': 'Any',
        'value': 'Thai_Non-Exempt - Shift Staff',
    },
    {
        'type': 'Payrule',
        'workertype': 'Employee',
        'location': 'TH Rayong',
        'exemptstatus': 'No',
        'shift': 'Shift D',
        'gender': 'Female',
        'cost_center': 'Any',
        'value': 'Thai_Non-Exempt - Shift Staff',
    },
    {
        'type': 'Payrule',
        'workertype': 'Employee',
        'location': 'TH Rayong',
        'exemptstatus': 'No',
        'shift': 'Day Shift',
        'gender': 'Female',
        'cost_center': 'Any',
        'value': 'Thai Non-Exempt Day Staff (Aug 5)',
    },
    {
        'type': 'Payrule',
        'workertype': 'Employee',
        'location': 'TH Rayong',
        'exemptstatus': 'No',
        'shift': 'Null',
        'gender': 'Female',
        'cost_center': 'Any',
        'value': 'Thai Non-Exempt Day Staff (Aug 5)',
    },
    {
        'type': 'Payrule',
        'workertype': 'Employee',
        'location': 'TH Rayong',
        'exemptstatus': 'No',
        'shift': 'Day Shift',
        'gender': 'Female',
        'cost_center': 'T30930',
        'value': 'Thai_Weekly Overtime - T30930',
    },
    {
        'type': 'Payrule',
        'workertype': 'Employee',
        'location': 'TH Rayong',
        'exemptstatus': 'No',
        'shift': 'Null',
        'gender': 'Female',
        'cost_center': 'T30930',
        'value': 'Thai_Weekly Overtime - T30930',
    },
    {
        'type': 'Payrule',
        'workertype': 'Contingent Worker',
        'location': 'TH Rayong',
        'exemptstatus': 'No',
        'shift': 'Day Shift',
        'gender': 'Any',
        'cost_center': 'Any',
        'value': 'Thai_Contingent Worker Day Staff',
    },
    {
        'type': 'Payrule',
        'workertype': 'Contingent Worker',
        'location': 'TH Rayong',
        'exemptstatus': 'No',
        'shift': 'Null',
        'gender': 'Any',
        'cost_center': 'Any',
        'value': 'Thai_Contingent Worker Day Staff',
    },
    {
        'type': 'Payrule',
        'workertype': 'Employee',
        'location': 'TH Rayong',
        'exemptstatus': 'Yes',
        'shift': 'Null',
        'gender': 'Male',
        'cost_center': 'Any',
        'value': 'No Payrule',
    },
    {
        'type': 'Payrule',
        'workertype': 'Employee',
        'location': 'TH Rayong',
        'exemptstatus': 'Yes',
        'shift': 'Day Shift',
        'gender': 'Male',
        'cost_center': 'Any',
        'value': 'No Payrule',
    },
    {
        'type': 'Payrule',
        'workertype': 'Employee',
        'location': 'TH Rayong',
        'exemptstatus': 'No',
        'shift': 'Shift A',
        'gender': 'Male',
        'cost_center': 'Any',
        'value': 'Thai_Non-Exempt - Shift Staff',
    },
    {
        'type': 'Payrule',
        'workertype': 'Employee',
        'location': 'TH Rayong',
        'exemptstatus': 'No',
        'shift': 'Shift B',
        'gender': 'Male',
        'cost_center': 'Any',
        'value': 'Thai_Non-Exempt - Shift Staff',
    },
    {
        'type': 'Payrule',
        'workertype': 'Employee',
        'location': 'TH Rayong',
        'exemptstatus': 'No',
        'shift': 'Shift C',
        'gender': 'Male',
        'cost_center': 'Any',
        'value': 'Thai_Non-Exempt - Shift Staff',
    },
    {
        'type': 'Payrule',
        'workertype': 'Employee',
        'location': 'TH Rayong',
        'exemptstatus': 'No',
        'shift': 'Shift D',
        'gender': 'Male',
        'cost_center': 'Any',
        'value': 'Thai_Non-Exempt - Shift Staff',
    },
    {
        'type': 'Payrule',
        'workertype': 'Employee',
        'location': 'TH Rayong',
        'exemptstatus': 'No',
        'shift': 'Day Shift',
        'gender': 'Male',
        'cost_center': 'Any',
        'value': 'Thai Non-Exempt Day Staff (Aug 5)',
    },
    {
        'type': 'Payrule',
        'workertype': 'Employee',
        'location': 'TH Rayong',
        'exemptstatus': 'No',
        'shift': 'Null',
        'gender': 'Male',
        'cost_center': 'Any',
        'value': 'Thai Non-Exempt Day Staff (Aug 5)',
    },
    {
        'type': 'Payrule',
        'workertype': 'Employee',
        'location': 'TH Rayong',
        'exemptstatus': 'No',
        'shift': 'Day Shift',
        'gender': 'Male',
        'cost_center': 'T30930',
        'value': 'Thai_Weekly Overtime - T30930',
    },
    {
        'type': 'Payrule',
        'workertype': 'Employee',
        'location': 'TH Rayong',
        'exemptstatus': 'No',
        'shift': 'Null',
        'gender': 'Male',
        'cost_center': 'T30930',
        'value': 'Thai_Weekly Overtime - T30930',
    },
    {
        'type': 'Payrule',
        'workertype': 'Contingent Worker',
        'location': 'TH Rayong',
        'exemptstatus': 'No',
        'shift': 'Day Shift',
        'gender': 'Any',
        'cost_center': 'Any',
        'value': 'Thai_Contingent Worker Day Staff',
    },
    {
        'type': 'Payrule',
        'workertype': 'Contingent Worker',
        'location': 'TH Rayong',
        'exemptstatus': 'No',
        'shift': 'Null',
        'gender': 'Any',
        'cost_center': 'Any',
        'value': 'Thai_Contingent Worker Day Staff',
    },
    {
        'type': 'Timesheet Template',
        'workertype': 'Employee',
        'location': 'TH Bangkok',
        'exemptstatus': 'Yes',
        'shift': 'Null',
        'gender': 'Male',
        'cost_center': 'Any',
        'value': 'NA',
    },
    {
        'type': 'Timesheet Template',
        'workertype': 'Employee',
        'location': 'TH Bangkok',
        'exemptstatus': 'Yes',
        'shift': 'Day Shift',
        'gender': 'Male',
        'cost_center': 'Any',
        'value': 'NA',
    },
    {
        'type': 'Timesheet Template',
        'workertype': 'Employee',
        'location': 'TH Bangkok',
        'exemptstatus': 'No',
        'shift': 'Shift A',
        'gender': 'Male',
        'cost_center': 'Any',
        'value': 'NA',
    },
    {
        'type': 'Timesheet Template',
        'workertype': 'Employee',
        'location': 'TH Bangkok',
        'exemptstatus': 'No',
        'shift': 'Shift B',
        'gender': 'Male',
        'cost_center': 'Any',
        'value': 'NA',
    },
    {
        'type': 'Timesheet Template',
        'workertype': 'Employee',
        'location': 'TH Bangkok',
        'exemptstatus': 'No',
        'shift': 'Shift C',
        'gender': 'Male',
        'cost_center': 'Any',
        'value': 'NA',
    },
    {
        'type': 'Timesheet Template',
        'workertype': 'Employee',
        'location': 'TH Bangkok',
        'exemptstatus': 'No',
        'shift': 'Shift D',
        'gender': 'Male',
        'cost_center': 'Any',
        'value': 'NA',
    },
    {
        'type': 'Timesheet Template',
        'workertype': 'Employee',
        'location': 'TH Bangkok',
        'exemptstatus': 'No',
        'shift': 'Day Shift',
        'gender': 'Male',
        'cost_center': 'Any',
        'value': 'NA',
    },
    {
        'type': 'Timesheet Template',
        'workertype': 'Employee',
        'location': 'TH Bangkok',
        'exemptstatus': 'No',
        'shift': 'Null',
        'gender': 'Male',
        'cost_center': 'Any',
        'value': 'NA',
    },
    {
        'type': 'Timesheet Template',
        'workertype': 'Employee',
        'location': 'TH Bangkok',
        'exemptstatus': 'No',
        'shift': 'Day Shift',
        'gender': 'Male',
        'cost_center': 'T30930',
        'value': 'NA',
    },
    {
        'type': 'Timesheet Template',
        'workertype': 'Employee',
        'location': 'TH Bangkok',
        'exemptstatus': 'No',
        'shift': 'Null',
        'gender': 'Male',
        'cost_center': 'T30930',
        'value': 'NA',
    },
    {
        'type': 'Timesheet Template',
        'workertype': 'Contingent Worker',
        'location': 'TH Bangkok',
        'exemptstatus': 'No',
        'shift': 'Day Shift',
        'gender': 'Any',
        'cost_center': 'Any',
        'value': 'NA',
    },
    {
        'type': 'Timesheet Template',
        'workertype': 'Contingent Worker',
        'location': 'TH Bangkok',
        'exemptstatus': 'No',
        'shift': 'Null',
        'gender': 'Any',
        'cost_center': 'Any',
        'value': 'NA',
    },
    {
        'type': 'Timesheet Template',
        'workertype': 'Employee',
        'location': 'TH Bangkok',
        'exemptstatus': 'Yes',
        'shift': 'Null',
        'gender': 'Female',
        'cost_center': 'Any',
        'value': 'NA',
    },
    {
        'type': 'Timesheet Template',
        'workertype': 'Employee',
        'location': 'TH Bangkok',
        'exemptstatus': 'Yes',
        'shift': 'Day Shift',
        'gender': 'Female',
        'cost_center': 'Any',
        'value': 'NA',
    },
    {
        'type': 'Timesheet Template',
        'workertype': 'Employee',
        'location': 'TH Bangkok',
        'exemptstatus': 'No',
        'shift': 'Shift A',
        'gender': 'Female',
        'cost_center': 'Any',
        'value': 'NA',
    },
    {
        'type': 'Timesheet Template',
        'workertype': 'Employee',
        'location': 'TH Bangkok',
        'exemptstatus': 'No',
        'shift': 'Shift B',
        'gender': 'Female',
        'cost_center': 'Any',
        'value': 'NA',
    },
    {
        'type': 'Timesheet Template',
        'workertype': 'Employee',
        'location': 'TH Bangkok',
        'exemptstatus': 'No',
        'shift': 'Shift C',
        'gender': 'Female',
        'cost_center': 'Any',
        'value': 'NA',
    },
    {
        'type': 'Timesheet Template',
        'workertype': 'Employee',
        'location': 'TH Bangkok',
        'exemptstatus': 'No',
        'shift': 'Shift D',
        'gender': 'Female',
        'cost_center': 'Any',
        'value': 'NA',
    },
    {
        'type': 'Timesheet Template',
        'workertype': 'Employee',
        'location': 'TH Bangkok',
        'exemptstatus': 'No',
        'shift': 'Day Shift',
        'gender': 'Female',
        'cost_center': 'Any',
        'value': 'NA',
    },
    {
        'type': 'Timesheet Template',
        'workertype': 'Employee',
        'location': 'TH Bangkok',
        'exemptstatus': 'No',
        'shift': 'Null',
        'gender': 'Female',
        'cost_center': 'Any',
        'value': 'NA',
    },
    {
        'type': 'Timesheet Template',
        'workertype': 'Employee',
        'location': 'TH Bangkok',
        'exemptstatus': 'No',
        'shift': 'Day Shift',
        'gender': 'Female',
        'cost_center': 'T30930',
        'value': 'NA',
    },
    {
        'type': 'Timesheet Template',
        'workertype': 'Employee',
        'location': 'TH Bangkok',
        'exemptstatus': 'No',
        'shift': 'Null',
        'gender': 'Female',
        'cost_center': 'T30930',
        'value': 'NA',
    },
    {
        'type': 'Timesheet Template',
        'workertype': 'Contingent Worker',
        'location': 'TH Bangkok',
        'exemptstatus': 'No',
        'shift': 'Day Shift',
        'gender': 'Any',
        'cost_center': 'Any',
        'value': 'NA',
    },
    {
        'type': 'Timesheet Template',
        'workertype': 'Contingent Worker',
        'location': 'TH Bangkok',
        'exemptstatus': 'No',
        'shift': 'Null',
        'gender': 'Any',
        'cost_center': 'Any',
        'value': 'NA',
    },
    {
        'type': 'Timesheet Template',
        'workertype': 'Employee',
        'location': 'TH Rayong',
        'exemptstatus': 'Yes',
        'shift': 'Null',
        'gender': 'Male',
        'cost_center': 'Any',
        'value': 'Thai_General',
    },
    {
        'type': 'Timesheet Template',
        'workertype': 'Employee',
        'location': 'TH Rayong',
        'exemptstatus': 'Yes',
        'shift': 'Day Shift',
        'gender': 'Male',
        'cost_center': 'Any',
        'value': 'Thai_General',
    },
    {
        'type': 'Timesheet Template',
        'workertype': 'Employee',
        'location': 'TH Rayong',
        'exemptstatus': 'No',
        'shift': 'Shift A',
        'gender': 'Male',
        'cost_center': 'Any',
        'value': 'Thai_Non Exempt Shift Staff',
    },
    {
        'type': 'Timesheet Template',
        'workertype': 'Employee',
        'location': 'TH Rayong',
        'exemptstatus': 'No',
        'shift': 'Shift B',
        'gender': 'Male',
        'cost_center': 'Any',
        'value': 'Thai_Non Exempt Shift Staff',
    },
    {
        'type': 'Timesheet Template',
        'workertype': 'Employee',
        'location': 'TH Rayong',
        'exemptstatus': 'No',
        'shift': 'Shift C',
        'gender': 'Male',
        'cost_center': 'Any',
        'value': 'Thai_Non Exempt Shift Staff',
    },
    {
        'type': 'Timesheet Template',
        'workertype': 'Employee',
        'location': 'TH Rayong',
        'exemptstatus': 'No',
        'shift': 'Shift D',
        'gender': 'Male',
        'cost_center': 'Any',
        'value': 'Thai_Non Exempt Shift Staff',
    },
    {
        'type': 'Timesheet Template',
        'workertype': 'Employee',
        'location': 'TH Rayong',
        'exemptstatus': 'No',
        'shift': 'Day Shift',
        'gender': 'Male',
        'cost_center': 'Any',
        'value': 'Thai_General',
    },
    {
        'type': 'Timesheet Template',
        'workertype': 'Employee',
        'location': 'TH Rayong',
        'exemptstatus': 'No',
        'shift': 'Null',
        'gender': 'Male',
        'cost_center': 'Any',
        'value': 'Thai_General',
    },
    {
        'type': 'Timesheet Template',
        'workertype': 'Employee',
        'location': 'TH Rayong',
        'exemptstatus': 'No',
        'shift': 'Day Shift',
        'gender': 'Male',
        'cost_center': 'T30930',
        'value': 'Thai_Non Exempt_T30930',
    },
    {
        'type': 'Timesheet Template',
        'workertype': 'Employee',
        'location': 'TH Rayong',
        'exemptstatus': 'No',
        'shift': 'Null',
        'gender': 'Male',
        'cost_center': 'T30930',
        'value': 'Thai_Non Exempt_T30930',
    },
    {
        'type': 'Timesheet Template',
        'workertype': 'Contingent Worker',
        'location': 'TH Rayong',
        'exemptstatus': 'No',
        'shift': 'Day Shift',
        'gender': 'Any',
        'cost_center': 'Any',
        'value': 'Thai_General',
    },
    {
        'type': 'Timesheet Template',
        'workertype': 'Contingent Worker',
        'location': 'TH Rayong',
        'exemptstatus': 'No',
        'shift': 'Null',
        'gender': 'Any',
        'cost_center': 'Any',
        'value': 'Thai_General',
    },
    {
        'type': 'Timesheet Template',
        'workertype': 'Employee',
        'location': 'TH Rayong',
        'exemptstatus': 'Yes',
        'shift': 'Null',
        'gender': 'Female',
        'cost_center': 'Any',
        'value': 'Thai_General',
    },
    {
        'type': 'Timesheet Template',
        'workertype': 'Employee',
        'location': 'TH Rayong',
        'exemptstatus': 'Yes',
        'shift': 'Day Shift',
        'gender': 'Female',
        'cost_center': 'Any',
        'value': 'Thai_General',
    },
    {
        'type': 'Timesheet Template',
        'workertype': 'Employee',
        'location': 'TH Rayong',
        'exemptstatus': 'No',
        'shift': 'Shift A',
        'gender': 'Female',
        'cost_center': 'Any',
        'value': 'Thai_Non Exempt Shift Staff',
    },
    {
        'type': 'Timesheet Template',
        'workertype': 'Employee',
        'location': 'TH Rayong',
        'exemptstatus': 'No',
        'shift': 'Shift B',
        'gender': 'Female',
        'cost_center': 'Any',
        'value': 'Thai_Non Exempt Shift Staff',
    },
    {
        'type': 'Timesheet Template',
        'workertype': 'Employee',
        'location': 'TH Rayong',
        'exemptstatus': 'No',
        'shift': 'Shift C',
        'gender': 'Female',
        'cost_center': 'Any',
        'value': 'Thai_Non Exempt Shift Staff',
    },
    {
        'type': 'Timesheet Template',
        'workertype': 'Employee',
        'location': 'TH Rayong',
        'exemptstatus': 'No',
        'shift': 'Shift D',
        'gender': 'Female',
        'cost_center': 'Any',
        'value': 'Thai_Non Exempt Shift Staff',
    },
    {
        'type': 'Timesheet Template',
        'workertype': 'Employee',
        'location': 'TH Rayong',
        'exemptstatus': 'No',
        'shift': 'Day Shift',
        'gender': 'Female',
        'cost_center': 'Any',
        'value': 'Thai_General',
    },
    {
        'type': 'Timesheet Template',
        'workertype': 'Employee',
        'location': 'TH Rayong',
        'exemptstatus': 'No',
        'shift': 'Null',
        'gender': 'Female',
        'cost_center': 'Any',
        'value': 'Thai_General',
    },
    {
        'type': 'Timesheet Template',
        'workertype': 'Employee',
        'location': 'TH Rayong',
        'exemptstatus': 'No',
        'shift': 'Day Shift',
        'gender': 'Female',
        'cost_center': 'T30930',
        'value': 'Thai_Non Exempt_T30930',
    },
    {
        'type': 'Timesheet Template',
        'workertype': 'Employee',
        'location': 'TH Rayong',
        'exemptstatus': 'No',
        'shift': 'Null',
        'gender': 'Female',
        'cost_center': 'T30930',
        'value': 'Thai_Non Exempt_T30930',
    },
    {
        'type': 'Timesheet Template',
        'workertype': 'Contingent Worker',
        'location': 'TH Rayong',
        'exemptstatus': 'No',
        'shift': 'Day Shift',
        'gender': 'Any',
        'cost_center': 'Any',
        'value': 'Thai_General',
    },
    {
        'type': 'Timesheet Template',
        'workertype': 'Contingent Worker',
        'location': 'TH Rayong',
        'exemptstatus': 'No',
        'shift': 'Null',
        'gender': 'Any',
        'cost_center': 'Any',
        'value': 'Thai_General',
    },
    {
        'type': 'Time Zone',
        'workertype': 'Employee',
        'location': 'TH Rayong',
        'exemptstatus': 'Any',
        'shift': 'Any',
        'gender': 'Any',
        'cost_center': 'Any',
        'value': 'UTC+7:00 SE Asia Standard Time',
    },
    {
        'type': 'Time Zone',
        'workertype': 'Contingent Worker',
        'location': 'TH Rayong',
        'exemptstatus': 'Any',
        'shift': 'Any',
        'gender': 'Any',
        'cost_center': 'Any',
        'value': 'UTC+7:00 SE Asia Standard Time',
    },
    {
        'type': 'Time Zone',
        'workertype': 'Employee',
        'location': 'TH Bangkok',
        'exemptstatus': 'Any',
        'shift': 'Any',
        'gender': 'Any',
        'cost_center': 'Any',
        'value': 'UTC+7:00 SE Asia Standard Time',
    },
    {
        'type': 'Time Zone',
        'workertype': 'Contingent Worker',
        'location': 'TH Bangkok',
        'exemptstatus': 'Any',
        'shift': 'Any',
        'gender': 'Any',
        'cost_center': 'Any',
        'value': 'UTC+7:00 SE Asia Standard Time',
    },
    {
        'type': 'Work week',
        'workertype': 'Employee',
        'location': 'TH Bangkok',
        'exemptstatus': 'Any',
        'shift': 'Any',
        'gender': 'Any',
        'cost_center': 'Any',
        'value': 'Sunday to Saturday',
    },
    {
        'type': 'Work week',
        'workertype': 'Contingent Worker',
        'location': 'TH Bangkok',
        'exemptstatus': 'Any',
        'shift': 'Any',
        'gender': 'Any',
        'cost_center': 'Any',
        'value': 'Sunday to Saturday',
    },
    {
        'type': 'Work week',
        'workertype': 'Employee',
        'location': 'TH Rayong',
        'exemptstatus': 'Any',
        'shift': 'Any',
        'gender': 'Any',
        'cost_center': 'Any',
        'value': 'Sunday to Saturday',
    },
    {
        'type': 'Work week',
        'workertype': 'Contingent Worker',
        'location': 'TH Rayong',
        'exemptstatus': 'Any',
        'shift': 'Any',
        'gender': 'Any',
        'cost_center': 'Any',
        'value': 'Sunday to Saturday',
    },
    {
        'type': 'Holiday Calendar',
        'workertype': 'Any',
        'location': 'TH Bangkok',
        'exemptstatus': 'Any',
        'shift': 'Null',
        'gender': 'Any',
        'cost_center': 'Any',
        'value': 'Thai_Holiday Calendar',
    },
    {
        'type': 'Holiday Calendar',
        'workertype': 'Any',
        'location': 'TH Bangkok',
        'exemptstatus': 'Any',
        'shift': 'Day Shift',
        'gender': 'Any',
        'cost_center': 'Any',
        'value': 'Thai_Holiday Calendar',
    },
    {
        'type': 'Holiday Calendar',
        'workertype': 'Any',
        'location': 'TH Bangkok',
        'exemptstatus': 'Any',
        'shift': 'Shift A',
        'gender': 'Any',
        'cost_center': 'Any',
        'value': 'Thai_Shift A&B',
    },
    {
        'type': 'Activity',
        'workertype': 'Employee',
        'location': 'TH Rayong',
        'exemptstatus': 'No',
        'shift': 'Day Shift',
        'gender': 'Female',
        'cost_center': 'T30930',
        'value': 'Oncall Support_Thailand',
    },
    {
        'type': 'Activity',
        'workertype': 'Employee',
        'location': 'TH Rayong',
        'exemptstatus': 'No',
        'shift': 'Null',
        'gender': 'Female',
        'cost_center': 'T30930',
        'value': 'Oncall Support_Thailand',
    },
    {
        'type': 'Activity',
        'workertype': 'Employee',
        'location': 'TH Bangkok',
        'exemptstatus': 'No',
        'shift': 'Day Shift',
        'gender': 'Female',
        'cost_center': 'T30930',
        'value': 'Oncall Support_Thailand',
    },
    {
        'type': 'Activity',
        'workertype': 'Employee',
        'location': 'TH Bangkok',
        'exemptstatus': 'No',
        'shift': 'Null',
        'gender': 'Female',
        'cost_center': 'T30930',
        'value': 'Oncall Support_Thailand',
    },
    {
        'type': 'Activity',
        'workertype': 'Employee',
        'location': 'TH Rayong',
        'exemptstatus': 'No',
        'shift': 'Day Shift',
        'gender': 'Male',
        'cost_center': 'T30930',
        'value': 'Oncall Support_Thailand',
    },
    {
        'type': 'Activity',
        'workertype': 'Employee',
        'location': 'TH Rayong',
        'exemptstatus': 'No',
        'shift': 'Null',
        'gender': 'Male',
        'cost_center': 'T30930',
        'value': 'Oncall Support_Thailand',
    },
    {
        'type': 'Activity',
        'workertype': 'Employee',
        'location': 'TH Bangkok',
        'exemptstatus': 'No',
        'shift': 'Day Shift',
        'gender': 'Male',
        'cost_center': 'T30930',
        'value': 'Oncall Support_Thailand',
    },
    {
        'type': 'Activity',
        'workertype': 'Employee',
        'location': 'TH Bangkok',
        'exemptstatus': 'No',
        'shift': 'Null',
        'gender': 'Male',
        'cost_center': 'T30930',
        'value': 'Oncall Support_Thailand',
    },
    {
        'type': 'Time off types',
        'workertype': 'Employee',
        'location': 'TH Bangkok',
        'exemptstatus': 'Yes',
        'shift': 'Null',
        'gender': 'Male',
        'cost_center': 'Any',
        'value': '01. Thai_Annual Leave - Exempt | 02. Thai_Sick Leave | 05. Thai_Paternity | 06. Thai_Military Service Leave | 07. Thai_Sterilization Leave | 08. Thai_Training Leave (Unpaid) | 09. Thai_Monk-Hood Leave | 11. Thai_Leave without pay | 12. Thai_Other Leave (Paid) | 13.Thai_Unpaid Leave | 14. Thai_ Marriage Leave|10.1 Thai_Compassionate Parent Leave|10.2 Thai_Compassionate Relative Leave',
    },
    {
        'type': 'Time off types',
        'workertype': 'Employee',
        'location': 'TH Bangkok',
        'exemptstatus': 'Yes',
        'shift': 'Day Shift',
        'gender': 'Male',
        'cost_center': 'Any',
        'value': '01. Thai_Annual Leave - Exempt | 02. Thai_Sick Leave | 05. Thai_Paternity | 06. Thai_Military Service Leave | 07. Thai_Sterilization Leave | 08. Thai_Training Leave (Unpaid) | 09. Thai_Monk-Hood Leave | 11. Thai_Leave without pay | 12. Thai_Other Leave (Paid) | 13.Thai_Unpaid Leave | 14. Thai_ Marriage Leave|10.1 Thai_Compassionate Parent Leave|10.2 Thai_Compassionate Relative Leave',
    },
    {
        'type': 'Time off types',
        'workertype': 'Employee',
        'location': 'TH Bangkok',
        'exemptstatus': 'No',
        'shift': 'Shift A',
        'gender': 'Male',
        'cost_center': 'Any',
        'value': '01. Thai_ Annual Leave - Non Exempt | 02. Thai_Sick Leave | 05. Thai_Paternity | 06. Thai_Military Service Leave | 07. Thai_Sterilization Leave | 08. Thai_Training Leave (Unpaid) | 09. Thai_Monk-Hood Leave | 11. Thai_Leave without pay | 12. Thai_Other Leave (Paid) | 13.Thai_Unpaid Leave | 14. Thai_ Marriage Leave | 15. Thai_OT Pre-approval|10.1 Thai_Compassionate Parent Leave|10.2 Thai_Compassionate Relative Leave| 16. Thai_Out of Office for Business',
    },
    {
        'type': 'Time off types',
        'workertype': 'Employee',
        'location': 'TH Bangkok',
        'exemptstatus': 'No',
        'shift': 'Shift B',
        'gender': 'Male',
        'cost_center': 'Any',
        'value': '01. Thai_ Annual Leave - Non Exempt | 02. Thai_Sick Leave | 05. Thai_Paternity | 06. Thai_Military Service Leave | 07. Thai_Sterilization Leave | 08. Thai_Training Leave (Unpaid) | 09. Thai_Monk-Hood Leave | 11. Thai_Leave without pay | 12. Thai_Other Leave (Paid) | 13.Thai_Unpaid Leave | 14. Thai_ Marriage Leave | 15. Thai_OT Pre-approval|10.1 Thai_Compassionate Parent Leave|10.2 Thai_Compassionate Relative Leave| 16. Thai_Out of Office for Business',
    },
    {
        'type': 'Time off types',
        'workertype': 'Employee',
        'location': 'TH Bangkok',
        'exemptstatus': 'No',
        'shift': 'Shift C',
        'gender': 'Male',
        'cost_center': 'Any',
        'value': '01. Thai_ Annual Leave - Non Exempt | 02. Thai_Sick Leave | 05. Thai_Paternity | 06. Thai_Military Service Leave | 07. Thai_Sterilization Leave | 08. Thai_Training Leave (Unpaid) | 09. Thai_Monk-Hood Leave | 11. Thai_Leave without pay | 12. Thai_Other Leave (Paid) | 13.Thai_Unpaid Leave | 14. Thai_ Marriage Leave | 15. Thai_OT Pre-approval|10.1 Thai_Compassionate Parent Leave|10.2 Thai_Compassionate Relative Leave| 16. Thai_Out of Office for Business',
    },
    {
        'type': 'Time off types',
        'workertype': 'Employee',
        'location': 'TH Bangkok',
        'exemptstatus': 'No',
        'shift': 'Shift D',
        'gender': 'Male',
        'cost_center': 'Any',
        'value': '01. Thai_ Annual Leave - Non Exempt | 02. Thai_Sick Leave | 05. Thai_Paternity | 06. Thai_Military Service Leave | 07. Thai_Sterilization Leave | 08. Thai_Training Leave (Unpaid) | 09. Thai_Monk-Hood Leave | 11. Thai_Leave without pay | 12. Thai_Other Leave (Paid) | 13.Thai_Unpaid Leave | 14. Thai_ Marriage Leave | 15. Thai_OT Pre-approval|10.1 Thai_Compassionate Parent Leave|10.2 Thai_Compassionate Relative Leave| 16. Thai_Out of Office for Business',
    },
    {
        'type': 'Time off types',
        'workertype': 'Employee',
        'location': 'TH Bangkok',
        'exemptstatus': 'No',
        'shift': 'Day Shift',
        'gender': 'Male',
        'cost_center': 'Any',
        'value': '01. Thai_ Annual Leave - Non Exempt | 02. Thai_Sick Leave | 05. Thai_Paternity | 06. Thai_Military Service Leave | 07. Thai_Sterilization Leave | 08. Thai_Training Leave (Unpaid) | 09. Thai_Monk-Hood Leave | 11. Thai_Leave without pay | 12. Thai_Other Leave (Paid) | 13.Thai_Unpaid Leave | 14. Thai_ Marriage Leave | 15. Thai_OT Pre-approval|10.1 Thai_Compassionate Parent Leave|10.2 Thai_Compassionate Relative Leave| 16. Thai_Out of Office for Business',
    },
    {
        'type': 'Time off types',
        'workertype': 'Employee',
        'location': 'TH Bangkok',
        'exemptstatus': 'No',
        'shift': 'Null',
        'gender': 'Male',
        'cost_center': 'Any',
        'value': '01. Thai_ Annual Leave - Non Exempt | 02. Thai_Sick Leave | 05. Thai_Paternity | 06. Thai_Military Service Leave | 07. Thai_Sterilization Leave | 08. Thai_Training Leave (Unpaid) | 09. Thai_Monk-Hood Leave | 11. Thai_Leave without pay | 12. Thai_Other Leave (Paid) | 13.Thai_Unpaid Leave | 14. Thai_ Marriage Leave | 15. Thai_OT Pre-approval|10.1 Thai_Compassionate Parent Leave|10.2 Thai_Compassionate Relative Leave| 16. Thai_Out of Office for Business',
    },
    {
        'type': 'Time off types',
        'workertype': 'Employee',
        'location': 'TH Bangkok',
        'exemptstatus': 'No',
        'shift': 'Day Shift',
        'gender': 'Male',
        'cost_center': 'T30930',
        'value': '01. Thai_ Annual Leave - Non Exempt | 02. Thai_Sick Leave | 05. Thai_Paternity | 06. Thai_Military Service Leave | 07. Thai_Sterilization Leave | 08. Thai_Training Leave (Unpaid) | 09. Thai_Monk-Hood Leave | 11. Thai_Leave without pay | 12. Thai_Other Leave (Paid) | 13.Thai_Unpaid Leave | 14. Thai_ Marriage Leave | 15. Thai_OT Pre-approval|10.1 Thai_Compassionate Parent Leave|10.2 Thai_Compassionate Relative Leave| 16. Thai_Out of Office for Business',
    },
    {
        'type': 'Time off types',
        'workertype': 'Employee',
        'location': 'TH Bangkok',
        'exemptstatus': 'No',
        'shift': 'Null',
        'gender': 'Male',
        'cost_center': 'T30930',
        'value': '01. Thai_ Annual Leave - Non Exempt | 02. Thai_Sick Leave | 05. Thai_Paternity | 06. Thai_Military Service Leave | 07. Thai_Sterilization Leave | 08. Thai_Training Leave (Unpaid) | 09. Thai_Monk-Hood Leave | 11. Thai_Leave without pay | 12. Thai_Other Leave (Paid) | 13.Thai_Unpaid Leave | 14. Thai_ Marriage Leave | 15. Thai_OT Pre-approval|10.1 Thai_Compassionate Parent Leave|10.2 Thai_Compassionate Relative Leave| 16. Thai_Out of Office for Business',
    },
    {
        'type': 'Time off types',
        'workertype': 'Contingent Worker',
        'location': 'TH Bangkok',
        'exemptstatus': 'No',
        'shift': 'Day Shift',
        'gender': 'Any',
        'cost_center': 'Any',
        'value': '02. Thai_Sick Leave | 06. Thai_Military Service Leave | 07. Thai_Sterilization Leave | 08. Thai_Training Leave (Unpaid) | 09. Thai_Monk-Hood Leave | 11. Thai_Leave without pay | 12. Thai_Other Leave (Paid) | 13.Thai_Unpaid Leave | 14. Thai_ Marriage Leave | 15. Thai_OT Pre-approval|10.1 Thai_Compassionate Parent Leave|10.2 Thai_Compassionate Relative Leave',
    },
    {
        'type': 'Time off types',
        'workertype': 'Contingent Worker',
        'location': 'TH Bangkok',
        'exemptstatus': 'No',
        'shift': 'Null',
        'gender': 'Any',
        'cost_center': 'Any',
        'value': '02. Thai_Sick Leave | 06. Thai_Military Service Leave | 07. Thai_Sterilization Leave | 08. Thai_Training Leave (Unpaid) | 09. Thai_Monk-Hood Leave | 11. Thai_Leave without pay | 12. Thai_Other Leave (Paid) | 13.Thai_Unpaid Leave | 14. Thai_ Marriage Leave | 15. Thai_OT Pre-approval|10.1 Thai_Compassionate Parent Leave|10.2 Thai_Compassionate Relative Leave',
    },
    {
        'type': 'Time off types',
        'workertype': 'Employee',
        'location': 'TH Bangkok',
        'exemptstatus': 'Yes',
        'shift': 'Null',
        'gender': 'Female',
        'cost_center': 'Any',
        'value': '01. Thai_Annual Leave - Exempt | 02. Thai_Sick Leave | 03. Thai_Maternity Leave | 04. Thai_Maternity Leave (Unpaid) | 06. Thai_Military Service Leave |07. Thai_Sterilization Leave | 08. Thai_Training Leave (Unpaid) | 09. Thai_Monk-Hood Leave | 11. Thai_Leave without pay | 12. Thai_Other Leave (Paid) | 13.Thai_Unpaid Leave | 14. Thai_ Marriage Leave|10.1 Thai_Compassionate Parent Leave|10.2 Thai_Compassionate Relative Leave',
    },
    {
        'type': 'Time off types',
        'workertype': 'Employee',
        'location': 'TH Bangkok',
        'exemptstatus': 'Yes',
        'shift': 'Day Shift',
        'gender': 'Female',
        'cost_center': 'Any',
        'value': '01. Thai_Annual Leave - Exempt | 02. Thai_Sick Leave | 03. Thai_Maternity Leave | 04. Thai_Maternity Leave (Unpaid) | 06. Thai_Military Service Leave |07. Thai_Sterilization Leave | 08. Thai_Training Leave (Unpaid) | 09. Thai_Monk-Hood Leave | 11. Thai_Leave without pay | 12. Thai_Other Leave (Paid) | 13.Thai_Unpaid Leave | 14. Thai_ Marriage Leave|10.1 Thai_Compassionate Parent Leave|10.2 Thai_Compassionate Relative Leave',
    },
    {
        'type': 'Time off types',
        'workertype': 'Employee',
        'location': 'TH Bangkok',
        'exemptstatus': 'No',
        'shift': 'Shift A',
        'gender': 'Female',
        'cost_center': 'Any',
        'value': '01. Thai_ Annual Leave - Non Exempt | 02. Thai_Sick Leave | 03. Thai_Maternity Leave | 04. Thai_Maternity Leave (Unpaid) | 06. Thai_Military Service Leave | 07. Thai_Sterilization Leave | 08. Thai_Training Leave (Unpaid) | 09. Thai_Monk-Hood Leave | 11. Thai_Leave without pay | 12. Thai_Other Leave (Paid) | 13.Thai_Unpaid Leave | 14. Thai_ Marriage Leave | 15. Thai_OT Pre-approval|10.1 Thai_Compassionate Parent Leave|10.2 Thai_Compassionate Relative Leave| 16. Thai_Out of Office for Business',
    },
    {
        'type': 'Time off types',
        'workertype': 'Employee',
        'location': 'TH Bangkok',
        'exemptstatus': 'No',
        'shift': 'Shift B',
        'gender': 'Female',
        'cost_center': 'Any',
        'value': '01. Thai_ Annual Leave - Non Exempt | 02. Thai_Sick Leave | 03. Thai_Maternity Leave | 04. Thai_Maternity Leave (Unpaid) | 06. Thai_Military Service Leave | 07. Thai_Sterilization Leave | 08. Thai_Training Leave (Unpaid) | 09. Thai_Monk-Hood Leave | 11. Thai_Leave without pay | 12. Thai_Other Leave (Paid) | 13.Thai_Unpaid Leave | 14. Thai_ Marriage Leave | 15. Thai_OT Pre-approval|10.1 Thai_Compassionate Parent Leave|10.2 Thai_Compassionate Relative Leave| 16. Thai_Out of Office for Business',
    },
    {
        'type': 'Time off types',
        'workertype': 'Employee',
        'location': 'TH Bangkok',
        'exemptstatus': 'No',
        'shift': 'Shift C',
        'gender': 'Female',
        'cost_center': 'Any',
        'value': '01. Thai_ Annual Leave - Non Exempt | 02. Thai_Sick Leave | 03. Thai_Maternity Leave | 04. Thai_Maternity Leave (Unpaid) | 06. Thai_Military Service Leave | 07. Thai_Sterilization Leave | 08. Thai_Training Leave (Unpaid) | 09. Thai_Monk-Hood Leave | 11. Thai_Leave without pay | 12. Thai_Other Leave (Paid) | 13.Thai_Unpaid Leave | 14. Thai_ Marriage Leave | 15. Thai_OT Pre-approval|10.1 Thai_Compassionate Parent Leave|10.2 Thai_Compassionate Relative Leave| 16. Thai_Out of Office for Business',
    },
    {
        'type': 'Time off types',
        'workertype': 'Employee',
        'location': 'TH Bangkok',
        'exemptstatus': 'No',
        'shift': 'Shift D',
        'gender': 'Female',
        'cost_center': 'Any',
        'value': '01. Thai_ Annual Leave - Non Exempt | 02. Thai_Sick Leave | 03. Thai_Maternity Leave | 04. Thai_Maternity Leave (Unpaid) | 06. Thai_Military Service Leave | 07. Thai_Sterilization Leave | 08. Thai_Training Leave (Unpaid) | 09. Thai_Monk-Hood Leave | 11. Thai_Leave without pay | 12. Thai_Other Leave (Paid) | 13.Thai_Unpaid Leave | 14. Thai_ Marriage Leave | 15. Thai_OT Pre-approval|10.1 Thai_Compassionate Parent Leave|10.2 Thai_Compassionate Relative Leave| 16. Thai_Out of Office for Business',
    },
    {
        'type': 'Time off types',
        'workertype': 'Employee',
        'location': 'TH Bangkok',
        'exemptstatus': 'No',
        'shift': 'Day Shift',
        'gender': 'Female',
        'cost_center': 'Any',
        'value': '01. Thai_ Annual Leave - Non Exempt | 02. Thai_Sick Leave | 03. Thai_Maternity Leave | 04. Thai_Maternity Leave (Unpaid) | 06. Thai_Military Service Leave | 07. Thai_Sterilization Leave | 08. Thai_Training Leave (Unpaid) | 09. Thai_Monk-Hood Leave | 11. Thai_Leave without pay | 12. Thai_Other Leave (Paid) | 13.Thai_Unpaid Leave | 14. Thai_ Marriage Leave | 15. Thai_OT Pre-approval|10.1 Thai_Compassionate Parent Leave|10.2 Thai_Compassionate Relative Leave| 16. Thai_Out of Office for Business',
    },
    {
        'type': 'Time off types',
        'workertype': 'Employee',
        'location': 'TH Bangkok',
        'exemptstatus': 'No',
        'shift': 'Null',
        'gender': 'Female',
        'cost_center': 'Any',
        'value': '01. Thai_ Annual Leave - Non Exempt | 02. Thai_Sick Leave | 03. Thai_Maternity Leave | 04. Thai_Maternity Leave (Unpaid) | 06. Thai_Military Service Leave | 07. Thai_Sterilization Leave | 08. Thai_Training Leave (Unpaid) | 09. Thai_Monk-Hood Leave | 11. Thai_Leave without pay | 12. Thai_Other Leave (Paid) | 13.Thai_Unpaid Leave | 14. Thai_ Marriage Leave | 15. Thai_OT Pre-approval|10.1 Thai_Compassionate Parent Leave|10.2 Thai_Compassionate Relative Leave| 16. Thai_Out of Office for Business',
    },
    {
        'type': 'Time off types',
        'workertype': 'Employee',
        'location': 'TH Bangkok',
        'exemptstatus': 'No',
        'shift': 'Day Shift',
        'gender': 'Female',
        'cost_center': 'T30930',
        'value': '01. Thai_ Annual Leave - Non Exempt | 02. Thai_Sick Leave | 03. Thai_Maternity Leave | 04. Thai_Maternity Leave (Unpaid) | 06. Thai_Military Service Leave | 07. Thai_Sterilization Leave | 08. Thai_Training Leave (Unpaid) | 09. Thai_Monk-Hood Leave | 11. Thai_Leave without pay | 12. Thai_Other Leave (Paid) | 13.Thai_Unpaid Leave | 14. Thai_ Marriage Leave | 15. Thai_OT Pre-approval|10.1 Thai_Compassionate Parent Leave|10.2 Thai_Compassionate Relative Leave| 16. Thai_Out of Office for Business',
    },
    {
        'type': 'Time off types',
        'workertype': 'Employee',
        'location': 'TH Bangkok',
        'exemptstatus': 'No',
        'shift': 'Null',
        'gender': 'Female',
        'cost_center': 'T30930',
        'value': '01. Thai_ Annual Leave - Non Exempt | 02. Thai_Sick Leave | 03. Thai_Maternity Leave | 04. Thai_Maternity Leave (Unpaid) | 06. Thai_Military Service Leave | 07. Thai_Sterilization Leave | 08. Thai_Training Leave (Unpaid) | 09. Thai_Monk-Hood Leave | 11. Thai_Leave without pay | 12. Thai_Other Leave (Paid) | 13.Thai_Unpaid Leave | 14. Thai_ Marriage Leave | 15. Thai_OT Pre-approval|10.1 Thai_Compassionate Parent Leave|10.2 Thai_Compassionate Relative Leave| 16. Thai_Out of Office for Business',
    },
    {
        'type': 'Time off types',
        'workertype': 'Contingent Worker',
        'location': 'TH Bangkok',
        'exemptstatus': 'No',
        'shift': 'Day Shift',
        'gender': 'Any',
        'cost_center': 'Any',
        'value': '02. Thai_Sick Leave | 06. Thai_Military Service Leave | 07. Thai_Sterilization Leave | 08. Thai_Training Leave (Unpaid) | 09. Thai_Monk-Hood Leave | 11. Thai_Leave without pay | 12. Thai_Other Leave (Paid) | 13.Thai_Unpaid Leave | 14. Thai_ Marriage Leave | 15. Thai_OT Pre-approval|10.1 Thai_Compassionate Parent Leave|10.2 Thai_Compassionate Relative Leave',
    },
    {
        'type': 'Time off types',
        'workertype': 'Contingent Worker',
        'location': 'TH Bangkok',
        'exemptstatus': 'No',
        'shift': 'Null',
        'gender': 'Any',
        'cost_center': 'Any',
        'value': '02. Thai_Sick Leave | 06. Thai_Military Service Leave | 07. Thai_Sterilization Leave | 08. Thai_Training Leave (Unpaid) | 09. Thai_Monk-Hood Leave | 11. Thai_Leave without pay | 12. Thai_Other Leave (Paid) | 13.Thai_Unpaid Leave | 14. Thai_ Marriage Leave | 15. Thai_OT Pre-approval|10.1 Thai_Compassionate Parent Leave|10.2 Thai_Compassionate Relative Leave',
    },
    {
        'type': 'Time off types',
        'workertype': 'Employee',
        'location': 'TH Rayong',
        'exemptstatus': 'Yes',
        'shift': 'Null',
        'gender': 'Female',
        'cost_center': 'Any',
        'value': '01. Thai_Annual Leave - Exempt | 02. Thai_Sick Leave | 03. Thai_Maternity Leave | 04. Thai_Maternity Leave (Unpaid) | 06. Thai_Military Service Leave |07. Thai_Sterilization Leave | 08. Thai_Training Leave (Unpaid) | 09. Thai_Monk-Hood Leave | 11. Thai_Leave without pay | 12. Thai_Other Leave (Paid) | 13.Thai_Unpaid Leave | 14. Thai_ Marriage Leave|10.1 Thai_Compassionate Parent Leave|10.2 Thai_Compassionate Relative Leave',
    },
    {
        'type': 'Time off types',
        'workertype': 'Employee',
        'location': 'TH Rayong',
        'exemptstatus': 'Yes',
        'shift': 'Day Shift',
        'gender': 'Female',
        'cost_center': 'Any',
        'value': '01. Thai_Annual Leave - Exempt | 02. Thai_Sick Leave | 03. Thai_Maternity Leave | 04. Thai_Maternity Leave (Unpaid) | 06. Thai_Military Service Leave |07. Thai_Sterilization Leave | 08. Thai_Training Leave (Unpaid) | 09. Thai_Monk-Hood Leave | 11. Thai_Leave without pay | 12. Thai_Other Leave (Paid) | 13.Thai_Unpaid Leave | 14. Thai_ Marriage Leave|10.1 Thai_Compassionate Parent Leave|10.2 Thai_Compassionate Relative Leave',
    },
    {
        'type': 'Time off types',
        'workertype': 'Employee',
        'location': 'TH Rayong',
        'exemptstatus': 'No',
        'shift': 'Shift A',
        'gender': 'Female',
        'cost_center': 'Any',
        'value': '01. Thai_ Annual Leave - Non Exempt | 02. Thai_Sick Leave | 03. Thai_Maternity Leave | 04. Thai_Maternity Leave (Unpaid) | 06. Thai_Military Service Leave | 07. Thai_Sterilization Leave | 08. Thai_Training Leave (Unpaid) | 09. Thai_Monk-Hood Leave | 11. Thai_Leave without pay | 12. Thai_Other Leave (Paid) | 13.Thai_Unpaid Leave | 14. Thai_ Marriage Leave | 15. Thai_OT Pre-approval|10.1 Thai_Compassionate Parent Leave|10.2 Thai_Compassionate Relative Leave| 16. Thai_Out of Office for Business',
    },
    {
        'type': 'Time off types',
        'workertype': 'Employee',
        'location': 'TH Rayong',
        'exemptstatus': 'No',
        'shift': 'Shift B',
        'gender': 'Female',
        'cost_center': 'Any',
        'value': '01. Thai_ Annual Leave - Non Exempt | 02. Thai_Sick Leave | 03. Thai_Maternity Leave | 04. Thai_Maternity Leave (Unpaid) | 06. Thai_Military Service Leave | 07. Thai_Sterilization Leave | 08. Thai_Training Leave (Unpaid) | 09. Thai_Monk-Hood Leave | 11. Thai_Leave without pay | 12. Thai_Other Leave (Paid) | 13.Thai_Unpaid Leave | 14. Thai_ Marriage Leave | 15. Thai_OT Pre-approval|10.1 Thai_Compassionate Parent Leave|10.2 Thai_Compassionate Relative Leave| 16. Thai_Out of Office for Business',
    },
    {
        'type': 'Time off types',
        'workertype': 'Employee',
        'location': 'TH Rayong',
        'exemptstatus': 'No',
        'shift': 'Shift C',
        'gender': 'Female',
        'cost_center': 'Any',
        'value': '01. Thai_ Annual Leave - Non Exempt | 02. Thai_Sick Leave | 03. Thai_Maternity Leave | 04. Thai_Maternity Leave (Unpaid) | 06. Thai_Military Service Leave | 07. Thai_Sterilization Leave | 08. Thai_Training Leave (Unpaid) | 09. Thai_Monk-Hood Leave | 11. Thai_Leave without pay | 12. Thai_Other Leave (Paid) | 13.Thai_Unpaid Leave | 14. Thai_ Marriage Leave | 15. Thai_OT Pre-approval|10.1 Thai_Compassionate Parent Leave|10.2 Thai_Compassionate Relative Leave| 16. Thai_Out of Office for Business',
    },
    {
        'type': 'Time off types',
        'workertype': 'Employee',
        'location': 'TH Rayong',
        'exemptstatus': 'No',
        'shift': 'Shift D',
        'gender': 'Female',
        'cost_center': 'Any',
        'value': '01. Thai_ Annual Leave - Non Exempt | 02. Thai_Sick Leave | 03. Thai_Maternity Leave | 04. Thai_Maternity Leave (Unpaid) | 06. Thai_Military Service Leave | 07. Thai_Sterilization Leave | 08. Thai_Training Leave (Unpaid) | 09. Thai_Monk-Hood Leave | 11. Thai_Leave without pay | 12. Thai_Other Leave (Paid) | 13.Thai_Unpaid Leave | 14. Thai_ Marriage Leave | 15. Thai_OT Pre-approval|10.1 Thai_Compassionate Parent Leave|10.2 Thai_Compassionate Relative Leave| 16. Thai_Out of Office for Business',
    },
    {
        'type': 'Time off types',
        'workertype': 'Employee',
        'location': 'TH Rayong',
        'exemptstatus': 'No',
        'shift': 'Day Shift',
        'gender': 'Female',
        'cost_center': 'Any',
        'value': '01. Thai_ Annual Leave - Non Exempt | 02. Thai_Sick Leave | 03. Thai_Maternity Leave | 04. Thai_Maternity Leave (Unpaid) | 06. Thai_Military Service Leave | 07. Thai_Sterilization Leave | 08. Thai_Training Leave (Unpaid) | 09. Thai_Monk-Hood Leave | 11. Thai_Leave without pay | 12. Thai_Other Leave (Paid) | 13.Thai_Unpaid Leave | 14. Thai_ Marriage Leave | 15. Thai_OT Pre-approval|10.1 Thai_Compassionate Parent Leave|10.2 Thai_Compassionate Relative Leave| 16. Thai_Out of Office for Business',
    },
    {
        'type': 'Time off types',
        'workertype': 'Employee',
        'location': 'TH Rayong',
        'exemptstatus': 'No',
        'shift': 'Null',
        'gender': 'Female',
        'cost_center': 'Any',
        'value': '01. Thai_ Annual Leave - Non Exempt | 02. Thai_Sick Leave | 03. Thai_Maternity Leave | 04. Thai_Maternity Leave (Unpaid) | 06. Thai_Military Service Leave | 07. Thai_Sterilization Leave | 08. Thai_Training Leave (Unpaid) | 09. Thai_Monk-Hood Leave | 11. Thai_Leave without pay | 12. Thai_Other Leave (Paid) | 13.Thai_Unpaid Leave | 14. Thai_ Marriage Leave | 15. Thai_OT Pre-approval|10.1 Thai_Compassionate Parent Leave|10.2 Thai_Compassionate Relative Leave| 16. Thai_Out of Office for Business',
    },
    {
        'type': 'Time off types',
        'workertype': 'Employee',
        'location': 'TH Rayong',
        'exemptstatus': 'No',
        'shift': 'Day Shift',
        'gender': 'Female',
        'cost_center': 'T30930',
        'value': '01. Thai_ Annual Leave - Non Exempt | 02. Thai_Sick Leave | 03. Thai_Maternity Leave | 04. Thai_Maternity Leave (Unpaid) | 06. Thai_Military Service Leave | 07. Thai_Sterilization Leave | 08. Thai_Training Leave (Unpaid) | 09. Thai_Monk-Hood Leave | 11. Thai_Leave without pay | 12. Thai_Other Leave (Paid) | 13.Thai_Unpaid Leave | 14. Thai_ Marriage Leave | 15. Thai_OT Pre-approval|10.1 Thai_Compassionate Parent Leave|10.2 Thai_Compassionate Relative Leave| 16. Thai_Out of Office for Business',
    },
    {
        'type': 'Time off types',
        'workertype': 'Employee',
        'location': 'TH Rayong',
        'exemptstatus': 'No',
        'shift': 'Null',
        'gender': 'Female',
        'cost_center': 'T30930',
        'value': '01. Thai_ Annual Leave - Non Exempt | 02. Thai_Sick Leave | 03. Thai_Maternity Leave | 04. Thai_Maternity Leave (Unpaid) | 06. Thai_Military Service Leave | 07. Thai_Sterilization Leave | 08. Thai_Training Leave (Unpaid) | 09. Thai_Monk-Hood Leave | 11. Thai_Leave without pay | 12. Thai_Other Leave (Paid) | 13.Thai_Unpaid Leave | 14. Thai_ Marriage Leave | 15. Thai_OT Pre-approval|10.1 Thai_Compassionate Parent Leave|10.2 Thai_Compassionate Relative Leave| 16. Thai_Out of Office for Business',
    },
    {
        'type': 'Time off types',
        'workertype': 'Contingent Worker',
        'location': 'TH Rayong',
        'exemptstatus': 'No',
        'shift': 'Day Shift',
        'gender': 'Any',
        'cost_center': 'Any',
        'value': '02. Thai_Sick Leave | 06. Thai_Military Service Leave | 07. Thai_Sterilization Leave | 08. Thai_Training Leave (Unpaid) | 09. Thai_Monk-Hood Leave |11. Thai_Leave without pay | 12. Thai_Other Leave (Paid) | 13.Thai_Unpaid Leave | 14. Thai_ Marriage Leave | 15. Thai_OT Pre-approval|10.1 Thai_Compassionate Parent Leave|10.2 Thai_Compassionate Relative Leave',
    },
    {
        'type': 'Time off types',
        'workertype': 'Contingent Worker',
        'location': 'TH Rayong',
        'exemptstatus': 'No',
        'shift': 'Null',
        'gender': 'Any',
        'cost_center': 'Any',
        'value': '02. Thai_Sick Leave | 06. Thai_Military Service Leave | 07. Thai_Sterilization Leave | 08. Thai_Training Leave (Unpaid) | 09. Thai_Monk-Hood Leave |11. Thai_Leave without pay | 12. Thai_Other Leave (Paid) | 13.Thai_Unpaid Leave | 14. Thai_ Marriage Leave | 15. Thai_OT Pre-approval|10.1 Thai_Compassionate Parent Leave|10.2 Thai_Compassionate Relative Leave',
    },
    {
        'type': 'Time off types',
        'workertype': 'Employee',
        'location': 'TH Rayong',
        'exemptstatus': 'Yes',
        'shift': 'Null',
        'gender': 'Male',
        'cost_center': 'Any',
        'value': '01. Thai_Annual Leave - Exempt | 02. Thai_Sick Leave | 05. Thai_Paternity | 06. Thai_Military Service Leave | 07. Thai_Sterilization Leave | 08. Thai_Training Leave (Unpaid) | 09. Thai_Monk-Hood Leave | 11. Thai_Leave without pay | 12. Thai_Other Leave (Paid) | 13.Thai_Unpaid Leave | 14. Thai_ Marriage Leave|10.1 Thai_Compassionate Parent Leave|10.2 Thai_Compassionate Relative Leave',
    },
    {
        'type': 'Time off types',
        'workertype': 'Employee',
        'location': 'TH Rayong',
        'exemptstatus': 'Yes',
        'shift': 'Day Shift',
        'gender': 'Male',
        'cost_center': 'Any',
        'value': '01. Thai_Annual Leave - Exempt | 02. Thai_Sick Leave | 05. Thai_Paternity | 06. Thai_Military Service Leave | 07. Thai_Sterilization Leave | 08. Thai_Training Leave (Unpaid) | 09. Thai_Monk-Hood Leave | 11. Thai_Leave without pay | 12. Thai_Other Leave (Paid) | 13.Thai_Unpaid Leave | 14. Thai_ Marriage Leave|10.1 Thai_Compassionate Parent Leave|10.2 Thai_Compassionate Relative Leave',
    },
    {
        'type': 'Time off types',
        'workertype': 'Employee',
        'location': 'TH Rayong',
        'exemptstatus': 'No',
        'shift': 'Shift A',
        'gender': 'Male',
        'cost_center': 'Any',
        'value': '01. Thai_ Annual Leave - Non Exempt | 02. Thai_Sick Leave | 05. Thai_Paternity | 06. Thai_Military Service Leave | 07. Thai_Sterilization Leave | 08. Thai_Training Leave (Unpaid) | 09. Thai_Monk-Hood Leave |11. Thai_Leave without pay | 12. Thai_Other Leave (Paid) | 13.Thai_Unpaid Leave | 14. Thai_ Marriage Leave | 15. Thai_OT Pre-approval|10.1 Thai_Compassionate Parent Leave|10.2 Thai_Compassionate Relative Leave| 16. Thai_Out of Office for Business',
    },
    {
        'type': 'Time off types',
        'workertype': 'Employee',
        'location': 'TH Rayong',
        'exemptstatus': 'No',
        'shift': 'Shift B',
        'gender': 'Male',
        'cost_center': 'Any',
        'value': '01. Thai_ Annual Leave - Non Exempt | 02. Thai_Sick Leave | 05. Thai_Paternity | 06. Thai_Military Service Leave | 07. Thai_Sterilization Leave | 08. Thai_Training Leave (Unpaid) | 09. Thai_Monk-Hood Leave |11. Thai_Leave without pay | 12. Thai_Other Leave (Paid) | 13.Thai_Unpaid Leave | 14. Thai_ Marriage Leave | 15. Thai_OT Pre-approval|10.1 Thai_Compassionate Parent Leave|10.2 Thai_Compassionate Relative Leave| 16. Thai_Out of Office for Business',
    },
    {
        'type': 'Time off types',
        'workertype': 'Employee',
        'location': 'TH Rayong',
        'exemptstatus': 'No',
        'shift': 'Shift C',
        'gender': 'Male',
        'cost_center': 'Any',
        'value': '01. Thai_ Annual Leave - Non Exempt | 02. Thai_Sick Leave | 05. Thai_Paternity | 06. Thai_Military Service Leave | 07. Thai_Sterilization Leave | 08. Thai_Training Leave (Unpaid) | 09. Thai_Monk-Hood Leave |11. Thai_Leave without pay | 12. Thai_Other Leave (Paid) | 13.Thai_Unpaid Leave | 14. Thai_ Marriage Leave | 15. Thai_OT Pre-approval|10.1 Thai_Compassionate Parent Leave|10.2 Thai_Compassionate Relative Leave| 16. Thai_Out of Office for Business',
    },
    {
        'type': 'Time off types',
        'workertype': 'Employee',
        'location': 'TH Rayong',
        'exemptstatus': 'No',
        'shift': 'Shift D',
        'gender': 'Male',
        'cost_center': 'Any',
        'value': '01. Thai_ Annual Leave - Non Exempt | 02. Thai_Sick Leave | 05. Thai_Paternity | 06. Thai_Military Service Leave | 07. Thai_Sterilization Leave | 08. Thai_Training Leave (Unpaid) | 09. Thai_Monk-Hood Leave |11. Thai_Leave without pay | 12. Thai_Other Leave (Paid) | 13.Thai_Unpaid Leave | 14. Thai_ Marriage Leave | 15. Thai_OT Pre-approval|10.1 Thai_Compassionate Parent Leave|10.2 Thai_Compassionate Relative Leave| 16. Thai_Out of Office for Business',
    },
    {
        'type': 'Time off types',
        'workertype': 'Employee',
        'location': 'TH Rayong',
        'exemptstatus': 'No',
        'shift': 'Day Shift',
        'gender': 'Male',
        'cost_center': 'Any',
        'value': '01. Thai_ Annual Leave - Non Exempt | 02. Thai_Sick Leave | 05. Thai_Paternity | 06. Thai_Military Service Leave | 07. Thai_Sterilization Leave | 08. Thai_Training Leave (Unpaid) | 09. Thai_Monk-Hood Leave |11. Thai_Leave without pay | 12. Thai_Other Leave (Paid) | 13.Thai_Unpaid Leave | 14. Thai_ Marriage Leave | 15. Thai_OT Pre-approval|10.1 Thai_Compassionate Parent Leave|10.2 Thai_Compassionate Relative Leave| 16. Thai_Out of Office for Business',
    },
    {
        'type': 'Time off types',
        'workertype': 'Employee',
        'location': 'TH Rayong',
        'exemptstatus': 'No',
        'shift': 'Null',
        'gender': 'Male',
        'cost_center': 'Any',
        'value': '01. Thai_ Annual Leave - Non Exempt | 02. Thai_Sick Leave | 05. Thai_Paternity | 06. Thai_Military Service Leave | 07. Thai_Sterilization Leave | 08. Thai_Training Leave (Unpaid) | 09. Thai_Monk-Hood Leave |11. Thai_Leave without pay | 12. Thai_Other Leave (Paid) | 13.Thai_Unpaid Leave | 14. Thai_ Marriage Leave | 15. Thai_OT Pre-approval|10.1 Thai_Compassionate Parent Leave|10.2 Thai_Compassionate Relative Leave| 16. Thai_Out of Office for Business',
    },
    {
        'type': 'Time off types',
        'workertype': 'Employee',
        'location': 'TH Rayong',
        'exemptstatus': 'No',
        'shift': 'Day Shift',
        'gender': 'Male',
        'cost_center': 'T30930',
        'value': '01. Thai_ Annual Leave - Non Exempt | 02. Thai_Sick Leave | 05. Thai_Paternity | 06. Thai_Military Service Leave | 07. Thai_Sterilization Leave | 08. Thai_Training Leave (Unpaid) | 09. Thai_Monk-Hood Leave |11. Thai_Leave without pay | 12. Thai_Other Leave (Paid) | 13.Thai_Unpaid Leave | 14. Thai_ Marriage Leave | 15. Thai_OT Pre-approval|10.1 Thai_Compassionate Parent Leave|10.2 Thai_Compassionate Relative Leave| 16. Thai_Out of Office for Business',
    },
    {
        'type': 'Time off types',
        'workertype': 'Employee',
        'location': 'TH Rayong',
        'exemptstatus': 'No',
        'shift': 'Null',
        'gender': 'Male',
        'cost_center': 'T30930',
        'value': '01. Thai_ Annual Leave - Non Exempt | 02. Thai_Sick Leave | 05. Thai_Paternity | 06. Thai_Military Service Leave | 07. Thai_Sterilization Leave | 08. Thai_Training Leave (Unpaid) | 09. Thai_Monk-Hood Leave |11. Thai_Leave without pay | 12. Thai_Other Leave (Paid) | 13.Thai_Unpaid Leave | 14. Thai_ Marriage Leave | 15. Thai_OT Pre-approval|10.1 Thai_Compassionate Parent Leave|10.2 Thai_Compassionate Relative Leave| 16. Thai_Out of Office for Business',
    },
    {
        'type': 'Time off types',
        'workertype': 'Contingent Worker',
        'location': 'TH Rayong',
        'exemptstatus': 'No',
        'shift': 'Day Shift',
        'gender': 'Any',
        'cost_center': 'Any',
        'value': '02. Thai_Sick Leave | 06. Thai_Military Service Leave | 07. Thai_Sterilization Leave | 08. Thai_Training Leave (Unpaid) | 09. Thai_Monk-Hood Leave |11. Thai_Leave without pay | 12. Thai_Other Leave (Paid) | 13.Thai_Unpaid Leave | 14. Thai_ Marriage Leave | 15. Thai_OT Pre-approval|10.1 Thai_Compassionate Parent Leave|10.2 Thai_Compassionate Relative Leave',
    },
    {
        'type': 'Time off types',
        'workertype': 'Contingent Worker',
        'location': 'TH Rayong',
        'exemptstatus': 'No',
        'shift': 'Null',
        'gender': 'Any',
        'cost_center': 'Any',
        'value': '02. Thai_Sick Leave | 06. Thai_Military Service Leave | 07. Thai_Sterilization Leave | 08. Thai_Training Leave (Unpaid) | 09. Thai_Monk-Hood Leave |10.1 Thai_Compassionate Parent Leave|10.2 Thai_Compassionate Relative Leave| 11. Thai_Leave without pay | 12. Thai_Other Leave (Paid) | 13.Thai_Unpaid Leave | 14. Thai_ Marriage Leave | 15. Thai_OT Pre-approval',
    },
    {
        'type': 'Employee Type',
        'workertype': 'Employee',
        'location': 'Null',
        'exemptstatus': 'Yes',
        'shift': 'Null',
        'gender': 'Any',
        'cost_center': 'Any',
        'value': 'Exempt',
    },
    {
        'type': 'Employee Type',
        'workertype': 'Employee',
        'location': 'Null',
        'exemptstatus': 'Yes',
        'shift': 'Day Shift',
        'gender': 'Any',
        'cost_center': 'Any',
        'value': 'Exempt',
    },
    {
        'type': 'Employee Type',
        'workertype': 'Employee',
        'location': 'Null',
        'exemptstatus': 'No',
        'shift': 'Shift A',
        'gender': 'Any',
        'cost_center': 'Any',
        'value': 'Non-Exempt - Shift',
    },
    {
        'type': 'Employee Type',
        'workertype': 'Employee',
        'location': 'Null',
        'exemptstatus': 'No',
        'shift': 'Shift B',
        'gender': 'Any',
        'cost_center': 'Any',
        'value': 'Non-Exempt - Shift',
    },
    {
        'type': 'Employee Type',
        'workertype': 'Employee',
        'location': 'Null',
        'exemptstatus': 'No',
        'shift': 'Shift C',
        'gender': 'Any',
        'cost_center': 'Any',
        'value': 'Non-Exempt - Shift',
    },
    {
        'type': 'Employee Type',
        'workertype': 'Employee',
        'location': 'Null',
        'exemptstatus': 'No',
        'shift': 'Shift D',
        'gender': 'Any',
        'cost_center': 'Any',
        'value': 'Non-Exempt - Shift',
    },
    {
        'type': 'Employee Type',
        'workertype': 'Employee',
        'location': 'Null',
        'exemptstatus': 'No',
        'shift': 'Null',
        'gender': 'Any',
        'cost_center': 'Any',
        'value': 'Non-Exempt',
    },
    {
        'type': 'Employee Type',
        'workertype': 'Employee',
        'location': 'Null',
        'exemptstatus': 'No',
        'shift': 'Day Shift',
        'gender': 'Any',
        'cost_center': 'Any',
        'value': 'Non-Exempt',
    },
    {
        'type': 'Employee Type',
        'workertype': 'Contingent Worker',
        'location': 'Null',
        'exemptstatus': 'No',
        'shift': 'Null',
        'gender': 'Any',
        'cost_center': 'Any',
        'value': 'Contingent Worker',
    },
    {
        'type': 'Employee Type',
        'workertype': 'Contingent Worker',
        'location': 'Null',
        'exemptstatus': 'No',
        'shift': 'Day Shift',
        'gender': 'Any',
        'cost_center': 'Any',
        'value': 'Contingent Worker',
    },
    {
        'type': 'Punch Entry Policy',
        'workertype': 'Employee',
        'location': 'TH Bangkok',
        'exemptstatus': 'Yes',
        'shift': 'Null',
        'gender': 'Male',
        'cost_center': 'Any',
        'value': 'NA',
    },
    {
        'type': 'Punch Entry Policy',
        'workertype': 'Employee',
        'location': 'TH Bangkok',
        'exemptstatus': 'Yes',
        'shift': 'Day Shift',
        'gender': 'Male',
        'cost_center': 'Any',
        'value': 'NA',
    },
    {
        'type': 'Punch Entry Policy',
        'workertype': 'Employee',
        'location': 'TH Bangkok',
        'exemptstatus': 'No',
        'shift': 'Shift A',
        'gender': 'Male',
        'cost_center': 'Any',
        'value': 'NA',
    },
    {
        'type': 'Punch Entry Policy',
        'workertype': 'Employee',
        'location': 'TH Bangkok',
        'exemptstatus': 'No',
        'shift': 'Shift B',
        'gender': 'Male',
        'cost_center': 'Any',
        'value': 'NA',
    },
    {
        'type': 'Punch Entry Policy',
        'workertype': 'Employee',
        'location': 'TH Bangkok',
        'exemptstatus': 'No',
        'shift': 'Shift C',
        'gender': 'Male',
        'cost_center': 'Any',
        'value': 'NA',
    },
    {
        'type': 'Punch Entry Policy',
        'workertype': 'Employee',
        'location': 'TH Bangkok',
        'exemptstatus': 'No',
        'shift': 'Shift D',
        'gender': 'Male',
        'cost_center': 'Any',
        'value': 'NA',
    },
    {
        'type': 'Punch Entry Policy',
        'workertype': 'Employee',
        'location': 'TH Bangkok',
        'exemptstatus': 'No',
        'shift': 'Day Shift',
        'gender': 'Male',
        'cost_center': 'Any',
        'value': 'NA',
    },
    {
        'type': 'Punch Entry Policy',
        'workertype': 'Employee',
        'location': 'TH Bangkok',
        'exemptstatus': 'No',
        'shift': 'Null',
        'gender': 'Male',
        'cost_center': 'Any',
        'value': 'NA',
    },
    {
        'type': 'Punch Entry Policy',
        'workertype': 'Employee',
        'location': 'TH Bangkok',
        'exemptstatus': 'No',
        'shift': 'Day Shift',
        'gender': 'Male',
        'cost_center': 'T30930',
        'value': 'NA',
    },
    {
        'type': 'Punch Entry Policy',
        'workertype': 'Employee',
        'location': 'TH Bangkok',
        'exemptstatus': 'No',
        'shift': 'Null',
        'gender': 'Male',
        'cost_center': 'T30930',
        'value': 'NA',
    },
    {
        'type': 'Punch Entry Policy',
        'workertype': 'Contingent Worker',
        'location': 'TH Bangkok',
        'exemptstatus': 'No',
        'shift': 'Day Shift',
        'gender': 'Any',
        'cost_center': 'Any',
        'value': 'NA',
    },
    {
        'type': 'Punch Entry Policy',
        'workertype': 'Contingent Worker',
        'location': 'TH Bangkok',
        'exemptstatus': 'No',
        'shift': 'Null',
        'gender': 'Any',
        'cost_center': 'Any',
        'value': 'NA',
    },
    {
        'type': 'Punch Entry Policy',
        'workertype': 'Employee',
        'location': 'TH Bangkok',
        'exemptstatus': 'Yes',
        'shift': 'Null',
        'gender': 'Female',
        'cost_center': 'Any',
        'value': 'NA',
    },
    {
        'type': 'Punch Entry Policy',
        'workertype': 'Employee',
        'location': 'TH Bangkok',
        'exemptstatus': 'Yes',
        'shift': 'Day Shift',
        'gender': 'Female',
        'cost_center': 'Any',
        'value': 'NA',
    },
    {
        'type': 'Punch Entry Policy',
        'workertype': 'Employee',
        'location': 'TH Bangkok',
        'exemptstatus': 'No',
        'shift': 'Shift A',
        'gender': 'Female',
        'cost_center': 'Any',
        'value': 'NA',
    },
    {
        'type': 'Punch Entry Policy',
        'workertype': 'Employee',
        'location': 'TH Bangkok',
        'exemptstatus': 'No',
        'shift': 'Shift B',
        'gender': 'Female',
        'cost_center': 'Any',
        'value': 'NA',
    },
    {
        'type': 'Punch Entry Policy',
        'workertype': 'Employee',
        'location': 'TH Bangkok',
        'exemptstatus': 'No',
        'shift': 'Shift C',
        'gender': 'Female',
        'cost_center': 'Any',
        'value': 'NA',
    },
    {
        'type': 'Punch Entry Policy',
        'workertype': 'Employee',
        'location': 'TH Bangkok',
        'exemptstatus': 'No',
        'shift': 'Shift D',
        'gender': 'Female',
        'cost_center': 'Any',
        'value': 'NA',
    },
    {
        'type': 'Punch Entry Policy',
        'workertype': 'Employee',
        'location': 'TH Bangkok',
        'exemptstatus': 'No',
        'shift': 'Day Shift',
        'gender': 'Female',
        'cost_center': 'Any',
        'value': 'NA',
    },
    {
        'type': 'Punch Entry Policy',
        'workertype': 'Employee',
        'location': 'TH Bangkok',
        'exemptstatus': 'No',
        'shift': 'Null',
        'gender': 'Female',
        'cost_center': 'Any',
        'value': 'NA',
    },
    {
        'type': 'Punch Entry Policy',
        'workertype': 'Employee',
        'location': 'TH Bangkok',
        'exemptstatus': 'No',
        'shift': 'Day Shift',
        'gender': 'Female',
        'cost_center': 'T30930',
        'value': 'NA',
    },
    {
        'type': 'Punch Entry Policy',
        'workertype': 'Employee',
        'location': 'TH Bangkok',
        'exemptstatus': 'No',
        'shift': 'Null',
        'gender': 'Female',
        'cost_center': 'T30930',
        'value': 'NA',
    },
    {
        'type': 'Punch Entry Policy',
        'workertype': 'Contingent Worker',
        'location': 'TH Bangkok',
        'exemptstatus': 'No',
        'shift': 'Day Shift',
        'gender': 'Any',
        'cost_center': 'Any',
        'value': 'NA',
    },
    {
        'type': 'Punch Entry Policy',
        'workertype': 'Contingent Worker',
        'location': 'TH Bangkok',
        'exemptstatus': 'No',
        'shift': 'Null',
        'gender': 'Any',
        'cost_center': 'Any',
        'value': 'NA',
    },
    {
        'type': 'Punch Entry Policy',
        'workertype': 'Employee',
        'location': 'TH Rayong',
        'exemptstatus': 'Yes',
        'shift': 'Null',
        'gender': 'Male',
        'cost_center': 'Any',
        'value': 'Thai_Exempt',
    },
    {
        'type': 'Punch Entry Policy',
        'workertype': 'Employee',
        'location': 'TH Rayong',
        'exemptstatus': 'Yes',
        'shift': 'Day Shift',
        'gender': 'Male',
        'cost_center': 'Any',
        'value': 'Thai_Exempt',
    },
    {
        'type': 'Punch Entry Policy',
        'workertype': 'Employee',
        'location': 'TH Rayong',
        'exemptstatus': 'No',
        'shift': 'Shift A',
        'gender': 'Male',
        'cost_center': 'Any',
        'value': 'Thai_Non Exempt/Contingent',
    },
    {
        'type': 'Punch Entry Policy',
        'workertype': 'Employee',
        'location': 'TH Rayong',
        'exemptstatus': 'No',
        'shift': 'Shift B',
        'gender': 'Male',
        'cost_center': 'Any',
        'value': 'Thai_Non Exempt/Contingent',
    },
    {
        'type': 'Punch Entry Policy',
        'workertype': 'Employee',
        'location': 'TH Rayong',
        'exemptstatus': 'No',
        'shift': 'Shift C',
        'gender': 'Male',
        'cost_center': 'Any',
        'value': 'Thai_Non Exempt/Contingent',
    },
    {
        'type': 'Punch Entry Policy',
        'workertype': 'Employee',
        'location': 'TH Rayong',
        'exemptstatus': 'No',
        'shift': 'Shift D',
        'gender': 'Male',
        'cost_center': 'Any',
        'value': 'Thai_Non Exempt/Contingent',
    },
    {
        'type': 'Punch Entry Policy',
        'workertype': 'Employee',
        'location': 'TH Rayong',
        'exemptstatus': 'No',
        'shift': 'Day Shift',
        'gender': 'Male',
        'cost_center': 'Any',
        'value': 'Thai_Non Exempt/Contingent',
    },
    {
        'type': 'Punch Entry Policy',
        'workertype': 'Employee',
        'location': 'TH Rayong',
        'exemptstatus': 'No',
        'shift': 'Null',
        'gender': 'Male',
        'cost_center': 'Any',
        'value': 'Thai_Non Exempt/Contingent',
    },
    {
        'type': 'Punch Entry Policy',
        'workertype': 'Employee',
        'location': 'TH Rayong',
        'exemptstatus': 'No',
        'shift': 'Day Shift',
        'gender': 'Male',
        'cost_center': 'T30930',
        'value': 'Thai_Non Exempt Centre T30930',
    },
    {
        'type': 'Punch Entry Policy',
        'workertype': 'Employee',
        'location': 'TH Rayong',
        'exemptstatus': 'No',
        'shift': 'Null',
        'gender': 'Male',
        'cost_center': 'T30930',
        'value': 'Thai_Non Exempt Centre T30930',
    },
    {
        'type': 'Punch Entry Policy',
        'workertype': 'Contingent Worker',
        'location': 'TH Rayong',
        'exemptstatus': 'No',
        'shift': 'Day Shift',
        'gender': 'Any',
        'cost_center': 'Any',
        'value': 'Thai_Non Exempt/Contingent',
    },
    {
        'type': 'Punch Entry Policy',
        'workertype': 'Contingent Worker',
        'location': 'TH Rayong',
        'exemptstatus': 'No',
        'shift': 'Null',
        'gender': 'Any',
        'cost_center': 'Any',
        'value': 'Thai_Non Exempt/Contingent',
    },
    {
        'type': 'Punch Entry Policy',
        'workertype': 'Employee',
        'location': 'TH Rayong',
        'exemptstatus': 'Yes',
        'shift': 'Null',
        'gender': 'Female',
        'cost_center': 'Any',
        'value': 'Thai_Exempt',
    },
    {
        'type': 'Punch Entry Policy',
        'workertype': 'Employee',
        'location': 'TH Rayong',
        'exemptstatus': 'Yes',
        'shift': 'Day Shift',
        'gender': 'Female',
        'cost_center': 'Any',
        'value': 'Thai_Exempt',
    },
    {
        'type': 'Punch Entry Policy',
        'workertype': 'Employee',
        'location': 'TH Rayong',
        'exemptstatus': 'No',
        'shift': 'Shift A',
        'gender': 'Female',
        'cost_center': 'Any',
        'value': 'Thai_Non Exempt/Contingent',
    },
    {
        'type': 'Punch Entry Policy',
        'workertype': 'Employee',
        'location': 'TH Rayong',
        'exemptstatus': 'No',
        'shift': 'Shift B',
        'gender': 'Female',
        'cost_center': 'Any',
        'value': 'Thai_Non Exempt/Contingent',
    },
    {
        'type': 'Punch Entry Policy',
        'workertype': 'Employee',
        'location': 'TH Rayong',
        'exemptstatus': 'No',
        'shift': 'Shift C',
        'gender': 'Female',
        'cost_center': 'Any',
        'value': 'Thai_Non Exempt/Contingent',
    },
    {
        'type': 'Punch Entry Policy',
        'workertype': 'Employee',
        'location': 'TH Rayong',
        'exemptstatus': 'No',
        'shift': 'Shift D',
        'gender': 'Female',
        'cost_center': 'Any',
        'value': 'Thai_Non Exempt/Contingent',
    },
    {
        'type': 'Punch Entry Policy',
        'workertype': 'Employee',
        'location': 'TH Rayong',
        'exemptstatus': 'No',
        'shift': 'Day Shift',
        'gender': 'Female',
        'cost_center': 'Any',
        'value': 'Thai_Non Exempt/Contingent',
    },
    {
        'type': 'Punch Entry Policy',
        'workertype': 'Employee',
        'location': 'TH Rayong',
        'exemptstatus': 'No',
        'shift': 'Null',
        'gender': 'Female',
        'cost_center': 'Any',
        'value': 'Thai_Non Exempt/Contingent',
    },
    {
        'type': 'Punch Entry Policy',
        'workertype': 'Employee',
        'location': 'TH Rayong',
        'exemptstatus': 'No',
        'shift': 'Day Shift',
        'gender': 'Female',
        'cost_center': 'T30930',
        'value': 'Thai_Non Exempt Centre T30930',
    },
    {
        'type': 'Punch Entry Policy',
        'workertype': 'Employee',
        'location': 'TH Rayong',
        'exemptstatus': 'No',
        'shift': 'Null',
        'gender': 'Female',
        'cost_center': 'T30930',
        'value': 'Thai_Non Exempt Centre T30930',
    },
    {
        'type': 'Punch Entry Policy',
        'workertype': 'Contingent Worker',
        'location': 'TH Rayong',
        'exemptstatus': 'No',
        'shift': 'Day Shift',
        'gender': 'Any',
        'cost_center': 'Any',
        'value': 'Thai_Non Exempt/Contingent',
    },
    {
        'type': 'Punch Entry Policy',
        'workertype': 'Contingent Worker',
        'location': 'TH Rayong',
        'exemptstatus': 'No',
        'shift': 'Null',
        'gender': 'Any',
        'cost_center': 'Any',
        'value': 'Thai_Non Exempt/Contingent',
    },
    {
        'type': 'Holiday Calendar',
        'workertype': 'Any',
        'location': 'TH Bangkok',
        'exemptstatus': 'Any',
        'shift': 'Shift B',
        'gender': 'Any',
        'cost_center': 'Any',
        'value': 'Thai_Shift A&B',
    },
    {
        'type': 'Holiday Calendar',
        'workertype': 'Any',
        'location': 'TH Bangkok',
        'exemptstatus': 'Any',
        'shift': 'Shift C',
        'gender': 'Any',
        'cost_center': 'Any',
        'value': 'Thai_Shift C&D',
    },
    {
        'type': 'Holiday Calendar',
        'workertype': 'Any',
        'location': 'TH Bangkok',
        'exemptstatus': 'Any',
        'shift': 'Shift D',
        'gender': 'Any',
        'cost_center': 'Any',
        'value': 'Thai_Shift C&D',
    },
    {
        'type': 'Holiday Calendar',
        'workertype': 'Any',
        'location': 'TH Rayong',
        'exemptstatus': 'Any',
        'shift': 'Null',
        'gender': 'Any',
        'cost_center': 'Any',
        'value': 'Thai_Holiday Calendar',
    },
    {
        'type': 'Holiday Calendar',
        'workertype': 'Any',
        'location': 'TH Rayong',
        'exemptstatus': 'Any',
        'shift': 'Day Shift',
        'gender': 'Any',
        'cost_center': 'Any',
        'value': 'Thai_Holiday Calendar',
    },
    {
        'type': 'Holiday Calendar',
        'workertype': 'Any',
        'location': 'TH Rayong',
        'exemptstatus': 'Any',
        'shift': 'Shift A',
        'gender': 'Any',
        'cost_center': 'Any',
        'value': 'Thai_Shift A&B',
    },
    {
        'type': 'Holiday Calendar',
        'workertype': 'Any',
        'location': 'TH Rayong',
        'exemptstatus': 'Any',
        'shift': 'Shift B',
        'gender': 'Any',
        'cost_center': 'Any',
        'value': 'Thai_Shift A&B',
    },
    {
        'type': 'Holiday Calendar',
        'workertype': 'Any',
        'location': 'TH Rayong',
        'exemptstatus': 'Any',
        'shift': 'Shift C',
        'gender': 'Any',
        'cost_center': 'Any',
        'value': 'Thai_Shift C&D',
    },
    {
        'type': 'Holiday Calendar',
        'workertype': 'Any',
        'location': 'TH Rayong',
        'exemptstatus': 'Any',
        'shift': 'Shift D',
        'gender': 'Any',
        'cost_center': 'Any',
        'value': 'Thai_Shift C&D',
    },
]


def mapper_value(category, **criteria):
    """Replicate the Workato lookup_table search on Momentive_Thailand_Mapper.

    Returns the first row's 'value' whose 'type' == category and whose columns
    exactly match the supplied criteria (Workato matches the literal stored
    values, including the "Any"/"Null" wildcards). Returns '' when nothing matches.
    """
    for row in momentive_thailand_mapper:
        if row['type'] != category:
            continue
        if all(row.get(col) == val for col, val in criteria.items()):
            return row['value']
    return ''
