time_zone_mapper = {
    'AF': '(UTC+4:30) Afghanistan Standard Time',
    'AL': '(UTC+1:00) Central European Standard Time',
    'DZ': '(UTC+1:00) Central European Standard Time',
    'AD': '(UTC+1:00) Central European Standard Time',
    'AO': '(UTC+1:00) Central European Standard Time',
    'AI': '(UTC-4:00) Atlantic Standard Time',
    'AQ': '(UTC-3:00) Montevideo Standard Time',
    'AG': '(UTC-4:00) Atlantic Standard Time',
    'AR': '(UTC-3:00) Montevideo Standard Time',
    'AM': '(UTC+4:00) Mauritius Standard Time',
    'AW': '(UTC-4:00) Atlantic Standard Time',
    'AU': '(UTC+10:00) AUS Eastern Standard Time',
    'AT': '(UTC+1:00) Central European Standard Time',
    'AZ': '(UTC+4:00) Mauritius Standard Time',
    'BS': '(UTC-5:00) Eastern Standard Time',
    'BH': '(UTC+3:00) Arabic Standard Time',
    'BD': '(UTC+6:00) Central Asia Standard Time',
    'BB': '(UTC-4:00) Atlantic Standard Time',
    'BY': '(UTC+3:00) Arabic Standard Time',
    'BE': '(UTC+1:00) Central European Standard Time',
    'BZ': '(UTC-6:00) Canada Central Standard Time',
    'BJ': '(UTC+1:00) Central European Standard Time',
    'BM': '(UTC-3:00) Montevideo Standard Time',
    'BT': '(UTC+6:00) Central Asia Standard Time',
    'BO': '(UTC-4:00) Atlantic Standard Time',
    'BQ': '(UTC-4:00) Atlantic Standard Time',
    'BA': '(UTC+1:00) Central European Standard Time',
    'BW': '(UTC+2:00) Middle East Standard Time',
    'BV': '(UTC+1:00) Central European Standard Time',
    'BR': '(UTC-3:00) Montevideo Standard Time',
    'IO': '(UTC+6:00) Central Asia Standard Time',
    'BN': '(UTC+8:00) Taipei Standard Time',
    'BG': '(UTC+2:00) Middle East Standard Time',
    'BF': '(UTC+0:00) Greenwich Standard Time',
    'BI': '(UTC+2:00) Middle East Standard Time',
    'CV': '(UTC-1:00) Azores Standard Time',
    'KH': '(UTC+7:00) North Asia Standard Time',
    'CM': '(UTC+1:00) Central European Standard Time',
    'CA': '(UTC-6:00) Canada Central Standard Time',
    'KY': '(UTC-5:00) Eastern Standard Time',
    'CF': '(UTC+1:00) Central European Standard Time',
    'TD': '(UTC+1:00) Central European Standard Time',
    'CL': '(UTC-3:00) Montevideo Standard Time',
    'CN': '(UTC+8:00) Taipei Standard Time',
    'CX': '(UTC+7:00) North Asia Standard Time',
    'CC': '(UTC+6:30) Myanmar Standard Time',
    'CO': '(UTC-5:00) Eastern Standard Time',
    'KM': '(UTC+3:00) Arabic Standard Time',
    'CD': '(UTC+1:00) Central European Standard Time',
    'CG': '(UTC+1:00) Central European Standard Time',
    'CK': '(UTC-10:00) Hawaiian Standard Time',
    'CR': '(UTC-6:00) Canada Central Standard Time',
    'HR': '(UTC+1:00) Central European Standard Time',
    'CU': '(UTC-5:00) Eastern Standard Time',
    'CW': '(UTC-4:00) Atlantic Standard Time',
    'CY': '(UTC+2:00) Middle East Standard Time',
    'CZ': '(UTC+1:00) Central European Standard Time',
    'CI': '(UTC+0:00) Greenwich Standard Time',
    'DK': '(UTC+1:00) Central European Standard Time',
    'DJ': '(UTC+3:00) Arabic Standard Time',
    'DM': '(UTC-4:00) Atlantic Standard Time',
    'DO': '(UTC-4:00) Atlantic Standard Time',
    'EC': '(UTC-5:00) Eastern Standard Time',
    'EG': '(UTC+2:00) Middle East Standard Time',
    'SV': '(UTC-6:00) Canada Central Standard Time',
    'GQ': '(UTC+1:00) Central European Standard Time',
    'ER': '(UTC+3:00) Arabic Standard Time',
    'EE': '(UTC+2:00) Middle East Standard Time',
    'SZ': '(UTC+2:00) Middle East Standard Time',
    'ET': '(UTC+3:00) Arabic Standard Time',
    'FK': '(UTC-3:00) Montevideo Standard Time',
    'FO': '(UTC+1:00) Central European Standard Time',
    'FJ': '(UTC+12:00) Kamchatka Standard Time',
    'FI': '(UTC+2:00) Middle East Standard Time',
    'FR': '(UTC+1:00) Central European Standard Time',
    'GF': '(UTC-3:00) Montevideo Standard Time',
    'PF': '(UTC-10:00) Hawaiian Standard Time',
    'TF': '(UTC+5:00) West Asia Standard Time',
    'GA': '(UTC+1:00) Central European Standard Time',
    'GM': '(UTC+0:00) Greenwich Standard Time',
    'GE': '(UTC+4:00) Mauritius Standard Time',
    'DE': '(UTC+1:00) Central European Standard Time',
    'GH': '(UTC+0:00) Greenwich Standard Time',
    'GI': '(UTC+2:00) Middle East Standard Time',
    'GR': '(UTC+2:00) Middle East Standard Time',
    'GL': '(UTC-3:00) Montevideo Standard Time',
    'GD': '(UTC-4:00) Atlantic Standard Time',
    'GP': '(UTC-4:00) Atlantic Standard Time',
    'GU': '(UTC+10:00) AUS Eastern Standard Time',
    'GT': '(UTC-6:00) Canada Central Standard Time',
    'GG': '(UTC+1:00) Central European Standard Time',
    'GN': '(UTC+0:00) Greenwich Standard Time',
    'GW': '(UTC+0:00) Greenwich Standard Time',
    'GY': '(UTC-4:00) Atlantic Standard Time',
    'HT': '(UTC-5:00) Eastern Standard Time',
    'HM': '(UTC+5:00) West Asia Standard Time',
    'VA': '(UTC+1:00) Central European Standard Time',
    'HN': '(UTC-6:00) Canada Central Standard Time',
    'HK': '(UTC+8:00) Taipei Standard Time',
    'HU': '(UTC+1:00) Central European Standard Time',
    'IS': '(UTC+0:00) Greenwich Standard Time',
    'IN': '(UTC+5:30) Sri Lanka Standard Time',
    'ID': '(UTC+9:00) Korea Standard Time',
    'IR': '(UTC+3:30) Iran Standard Time',
    'IQ': '(UTC+3:00) Arabic Standard Time',
    'IE': '(UTC+0:00) Greenwich Standard Time',
    'IM': '(UTC+1:00) Central European Standard Time',
    'IL': '(UTC+2:00) Middle East Standard Time',
    'IT': '(UTC+1:00) Central European Standard Time',
    'JM': '(UTC-5:00) Eastern Standard Time',
    'JP': '(UTC+9:00) Korea Standard Time',
    'JE': '(UTC+1:00) Central European Standard Time',
    'JO': '(UTC+3:00) Arabic Standard Time',
    'KZ': '(UTC+5:00) West Asia Standard Time',
    'KE': '(UTC+3:00) Arabic Standard Time',
    'KI': '(UTC+12:00) Kamchatka Standard Time',
    'KP': '(UTC+9:00) Korea Standard Time',
    'KR': '(UTC+9:00) Korea Standard Time',
    'KW': '(UTC+3:00) Arabic Standard Time',
    'KG': '(UTC+6:00) Central Asia Standard Time',
    'LA': '(UTC+7:00) North Asia Standard Time',
    'LV': '(UTC+2:00) Middle East Standard Time',
    'LB': '(UTC+3:00) Arabic Standard Time',
    'LS': '(UTC+2:00) Middle East Standard Time',
    'LR': '(UTC+0:00) Greenwich Standard Time',
    'LY': '(UTC+2:00) Middle East Standard Time',
    'LI': '(UTC+1:00) Central European Standard Time',
    'LT': '(UTC+2:00) Middle East Standard Time',
    'LU': '(UTC+1:00) Central European Standard Time',
    'MO': '(UTC+8:00) Taipei Standard Time',
    'MG': '(UTC+3:00) Arabic Standard Time',
    'MW': '(UTC+2:00) Middle East Standard Time',
    'MY': '(UTC+8:00) Taipei Standard Time',
    'MV': '(UTC+5:00) West Asia Standard Time',
    'ML': '(UTC+0:00) Greenwich Standard Time',
    'MT': '(UTC+1:00) Central European Standard Time',
    'MH': '(UTC+12:00) Kamchatka Standard Time',
    'MQ': '(UTC-4:00) Atlantic Standard Time',
    'MR': '(UTC+0:00) Greenwich Standard Time',
    'MU': '(UTC+4:00) Mauritius Standard Time',
    'YT': '(UTC+3:00) Arabic Standard Time',
    'MX': '(UTC-6:00) Canada Central Standard Time',
    'FM': '(UTC+10:00) AUS Eastern Standard Time',
    'MD': '(UTC+2:00) Middle East Standard Time',
    'MC': '(UTC+1:00) Central European Standard Time',
    'MN': '(UTC+7:00) North Asia Standard Time',
    'ME': '(UTC+1:00) Central European Standard Time',
    'MS': '(UTC-4:00) Atlantic Standard Time',
    'MA': '(UTC+0:00) Greenwich Standard Time',
    'MZ': '(UTC+2:00) Middle East Standard Time',
    'MM': '(UTC+6:30) Myanmar Standard Time',
    'NA': '(UTC+2:00) Middle East Standard Time',
    'NR': '(UTC+12:00) Kamchatka Standard Time',
    'NP': '(UTC+5:45) Nepal Standard Time',
    'NL': '(UTC+1:00) Central European Standard Time',
    'NC': '(UTC+11:00) Central Pacific Standard Time',
    'NZ': '(UTC+12:00) Kamchatka Standard Time',
    'NI': '(UTC-6:00) Canada Central Standard Time',
    'NE': '(UTC+0:00) Greenwich Standard Time',
    'NG': '(UTC+1:00) Central European Standard Time',
    'NF': '(UTC+11:00) Central Pacific Standard Time',
    'MP': '(UTC+10:00) AUS Eastern Standard Time',
    'NO': '(UTC+1:00) Central European Standard Time',
    'OM': '(UTC+4:00) Mauritius Standard Time',
    'PK': '(UTC+5:00) West Asia Standard Time',
    'PW': '(UTC+9:00) Korea Standard Time',
    'PS': '(UTC+2:00) Middle East Standard Time',
    'PA': '(UTC-5:00) Eastern Standard Time',
    'PG': '(UTC+10:00) AUS Eastern Standard Time',
    'PY': '(UTC-4:00) Atlantic Standard Time',
    'PE': '(UTC-5:00) Eastern Standard Time',
    'PH': '(UTC+8:00) Taipei Standard Time',
    'PN': '(UTC-8:00) Pacific Standard Time (Mexico)',
    'PL': '(UTC+1:00) Central European Standard Time',
    'PT': '(UTC+0:00) Greenwich Standard Time',
    'PR': '(UTC-4:00) Atlantic Standard Time',
    'QA': '(UTC+3:00) Arabic Standard Time',
    'MK': '(UTC+1:00) Central European Standard Time',
    'RO': '(UTC+2:00) Middle East Standard Time',
    'RU': '(UTC+3:00) Arabic Standard Time',
    'RW': '(UTC+2:00) Middle East Standard Time',
    'RE': '(UTC+4:00) Mauritius Standard Time',
    'BL': '(UTC-4:00) Atlantic Standard Time',
    'SH': '(UTC+0:00) Greenwich Standard Time',
    'KN': '(UTC-4:00) Atlantic Standard Time',
    'LC': '(UTC-4:00) Atlantic Standard Time',
    'MF': '(UTC-4:00) Atlantic Standard Time',
    'PM': '(UTC-3:00) Montevideo Standard Time',
    'VC': '(UTC-4:00) Atlantic Standard Time',
    'WS': '(UTC+13:00) Samoa Standard Time',
    'SM': '(UTC+1:00) Central European Standard Time',
    'ST': '(UTC+0:00) Greenwich Standard Time',
    'SA': '(UTC+3:00) Arabic Standard Time',
    'SN': '(UTC+0:00) Greenwich Standard Time',
    'RS': '(UTC+1:00) Central European Standard Time',
    'SC': '(UTC+4:00) Mauritius Standard Time',
    'SL': '(UTC+0:00) Greenwich Standard Time',
    'SG': '(UTC+8:00) Taipei Standard Time',
    'SX': '(UTC-4:00) Atlantic Standard Time',
    'SK': '(UTC+1:00) Central European Standard Time',
    'SI': '(UTC+1:00) Central European Standard Time',
    'SB': '(UTC+11:00) Central Pacific Standard Time',
    'SO': '(UTC+3:00) Arabic Standard Time',
    'ZA': '(UTC+2:00) Middle East Standard Time',
    'GS': '(UTC-2:00) Mid-Atlantic Standard Time',
    'SS': '(UTC+2:00) Middle East Standard Time',
    'ES': '(UTC+1:00) Central European Standard Time',
    'LK': '(UTC+5:30) Sri Lanka Standard Time',
    'SD': '(UTC+3:00) Arabic Standard Time',
    'SR': '(UTC-3:00) Montevideo Standard Time',
    'SJ': '(UTC+2:00) Middle East Standard Time',
    'SE': '(UTC+1:00) Central European Standard Time',
    'CH': '(UTC+1:00) Central European Standard Time',
    'SY': '(UTC+3:00) Arabic Standard Time',
    'TW': '(UTC+8:00) Taipei Standard Time',
    'TJ': '(UTC+5:00) West Asia Standard Time',
    'TZ': '(UTC+3:00) Arabic Standard Time',
    'TH': '(UTC+7:00) North Asia Standard Time',
    'TL': '(UTC+9:00) Korea Standard Time',
    'TG': '(UTC+0:00) Greenwich Standard Time',
    'TK': '(UTC+13:00) Samoa Standard Time',
    'TO': '(UTC+13:00) Samoa Standard Time',
    'TT': '(UTC-4:00) Atlantic Standard Time',
    'TN': '(UTC+1:00) Central European Standard Time',
    'TR': '(UTC+3:00) Arabic Standard Time',
    'TM': '(UTC+5:00) West Asia Standard Time',
    'TC': '(UTC-4:00) Atlantic Standard Time',
    'TV': '(UTC+12:00) Kamchatka Standard Time',
    'UG': '(UTC+3:00) Arabic Standard Time',
    'UA': '(UTC+2:00) Middle East Standard Time',
    'AE': '(UTC+4:00) Mauritius Standard Time',
    'GB': '(UTC+0:00) Greenwich Standard Time',
    'UM': '(UTC-12:00) Dateline Standard Time',
    'US': '(UTC-6:00) Canada Central Standard Time',
    'UY': '(UTC-3:00) Montevideo Standard Time',
    'UZ': '(UTC+5:00) West Asia Standard Time',
    'VU': '(UTC+11:00) Central Pacific Standard Time',
    'VE': '(UTC-4:00) Atlantic Standard Time',
    'VN': '(UTC+7:00) North Asia Standard Time',
    'VG': '(UTC-4:00) Atlantic Standard Time',
    'VI': '(UTC-4:00) Atlantic Standard Time',
    'WF': '(UTC+12:00) Kamchatka Standard Time',
    'EH': '(UTC+1:00) Central European Standard Time',
    'YE': '(UTC+3:00) Arabic Standard Time',
    'ZM': '(UTC+2:00) Middle East Standard Time',
    'ZW': '(UTC+2:00) Middle East Standard Time',
    'FI-01': '(UTC+3:00) Arabic Standard Time',
    'AS': '(UTC-11:00) American Samoa (Samoan)',
    'NU': '(UTC-11:00) Niue'
}