role_approval_path_mapper = {
    "timesheet_approval_path": 'Spain_Efforts_Approval',
    "timeoff_approval_path": "Spain Time Off Approval Path",
    "timeoff_system_approval_path":"Spain D1 and above Time Off Approval Path",
    "l1_manager": "Spain L1 Manager - Shift",
    "end_user_manager": "End User (Managers)",
    "project_manager": "Spain Project Manager",
    "hr_manager": "Spain - GEO HR",
    "default_user_permission": "Project Resource",
    "foreign_manager_emp_type": "Foreign Managers",
    "ot_request_template_spain": "Spain OT Pre-approval",
    "ot_request_template_rebadged": "Spain OT Pre-Approval - Rebadged",
    "ot_request_template_designit": "Spain OT Pre-Approval - DesignIT",
    "ot_request_approval_path": "Spain - Overtime Approval Path",
    "schedule_type": "urn:replicon:schedule-type:shift",
    "schedule_policy": "Spain Schedule Policy",
    "payrule_for_fulltime_spain": "Spain Custom Payrule",
    "payrule_for_fulltime_rebadged": "Spain custom Payrule _Rebadged",
    "payrule_for_fulltime_designit": "Spain custom Payrule _DesignIT",
    "payrule_for_parttime_spain": "Spain custom Payrule _Part Time",
    "payrule_for_parttime_rebadged": "Spain custom Payrule _Part Time_Rebadged",
    "payrule_for_parttime_designit": "Spain custom Payrule _Part Time_DesignIT",
    "time_zone": "(UTC+1:00) Central European Standard Time",
    "timesheet_system_approval_path": "System Approval",
    "timesheet_supervisor_approval_path": "Supervisor",
    "timesheet_period": "Spain - Weekly starting on Monday",
    "timesheet_for_fulltime_spain":"Spain Timesheet",
    "timesheet_for_parttime_spain":"Spain Timesheet_Part Time",
    "timesheet_for_fulltime_rebadged":"Spain Timesheet_Rebadged",
    "timesheet_for_parttime_rebadged":"Spain Timesheet_Part Time_Rebadged",
    "timesheet_for_fulltime_designit":"Spain Timesheet_DesignIT",
    "timesheet_for_parttime_designit":"Spain Timesheet_Part Time_DesignIT",
}
