Regular_Paycodes = [
    # overtime paycodes
    "OT Reg 125",
    "NDOT Reg 137.5",
    "RD 130",
    "ND RD 143",
    "OT RD 169",
    "NDOT RD 185.9",
    "OT LglHol 260",
    "NDOT LglHol 286",
    "LglHol RD 260",
    "ND LglHol RD 286",
    "OT LglHol RD 338",
    "NDOT LglHol RD 371.8",
    "OT SplD 169",
    "NDOT SplD 185.9",
    "SplD RD 150",
    "ND SplD RD 165",
    "OT SplD RD 195",
    "NDOT SplD RD 214.5",
    "OT DHol 390",
    "NDOT DHol 429",
    "DHol RD 390",
    "ND DHol RD 429",
    "OT DHol RD 507",
    "NDOT DHol RD 557.7",
    "OT DSplD 195",
    "NDOT DSplD 214.5",
    "DSplD RD 195",
    "ND DSplD RD 214.5",
    "OT DSplD RD 253.5",
    "NDOT DSplD RD 278.85",

    # standby_paycodes
    "Standby Allowance",
    "PHL Shift Allowance",
    "LglHol 200",
    "ND LglHol 220",
    "SplD 130",
    "ND SplD 143",
    "DHol 300",
    "ND DHol 330",
    "DSplD 150",
    "ND DSplD 165"
]

Timeoff_Paycodes = [
    "PHL - Annual Leave",
    "PHL - Annual Leave Grandfathered",
    "PHL - Sick Leave",
    "PHL - Sick Leave Grandfathered",
    "PHL - Paternity Leave",
    "PHL - Parental Leave for Solo Parents",
    "PHL - Family Leave (Leave for Victim of Violence against Women and their Children)",
    "PHL - Emergency Leave",
    "PHL - Compassionate Leave",
    "PHL - Volunteer Leave",
    "PHL - Examination Leave",
    "PHL - Shared Maternity Leave",
    "PHL - Leave without Pay",
    "PHL - Compensatory Day Off",
    "PHL - Maternity Leave",
    "PHL - Special Leave for Women (Magna Carta)",
    "PHL - Unpaid Leave of Absence",
    "PHL - Maternity Leave - Solo Parent",
    "PHL - Maternity Leave - Leave without Pay",
    "PHL - Paternity Leave Extended"
]
