from ast import literal_eval
import rail

null = None
false = False
true = True

def get_punch_history_daterange_data():
    return {
	"response": {
		"result": true,
		"data": [
			{
				"entrytype": 2,
				"punchtime": "2024-08-23T09:00:00.000000-05:00",
				"timeadded": "2024-08-13T00:59:15.000000-05:00",
				"punchtype": "HR",
				"punchdesc": "",
				"eecode": "A0W8",
				"deptcode": "SS&S-SL",
				"earncode": "PTM",
				"taxprofid": 0,
				"eebadge": "",
				"clocktype": "",
				"hours": "8.00",
				"dollaramount": "0.00",
				"units": "0.00",
				"isdeleted": 0,
				"clockseq": "",
				"clockid": "API",
				"cat1": "000",
				"cat1desc": "Unassigned",
				"cat2": "0UD09",
				"cat2desc": "MCI USA OPERATING CO",
				"cat3": "",
				"cat3desc": "",
				"cat4": "",
				"cat4desc": "",
				"cat5": "",
				"cat5desc": "",
				"cat6": "",
				"cat6desc": "",
				"cat7": "",
				"cat7desc": "",
				"cat8": "",
				"cat8desc": "",
				"cat9": "",
				"cat9desc": "",
				"cat10": "",
				"cat10desc": "",
				"cat11": "",
				"cat11desc": "",
				"cat12": "",
				"cat12desc": "",
				"cat13": "",
				"cat13desc": "",
				"cat14": "",
				"cat14desc": "",
				"cat15": "",
				"cat15desc": "",
				"cat16": "",
				"cat16desc": "",
				"cat17": "",
				"cat17desc": "",
				"cat18": "",
				"cat18desc": "",
				"cat19": "",
				"cat19desc": "",
				"cat20": "",
				"cat20desc": "",
				"punchid": 192391581,
				"is_archived": false
			}
		],
		"errors": [],
		"errorCount": 0,
		"records": 1
	}
}


def get_punch_history1():
    return {
        "result": false,
        "data": "",
        "errors": [
        "No Content Found"
        ],
        "errorCount": 1,
        "records": 0
}

def punch_import():
    return {
	"response": {
		"result": True,
		"data": [
			{
				"eebadge": null,
				"eecode": "A01I",
				"clocksequencenumber": null,
				"timezone": "PST",
				"punchtime": "1723881600",
				"deptcode": null,
				"cat1": null,
				"cat2": null,
				"cat3": null,
				"cat4": null,
				"cat5": null,
				"cat6": null,
				"cat7": null,
				"cat8": null,
				"cat9": null,
				"cat10": null,
				"cat11": null,
				"cat12": null,
				"cat13": null,
				"cat14": null,
				"cat15": null,
				"cat16": null,
				"cat17": null,
				"cat18": null,
				"cat19": null,
				"cat20": null,
				"punchdesc": null,
				"taxprofid": null,
				"hours": 3,
				"dollaramount": null,
				"earncode": "R",
				"earnrate": null,
				"fixedamount": 0,
				"fixedearncode": null,
				"makeUpTime": false,
				"clocktype": null,
				"entrytype": 2,
				"punchtype": "HR",
				"externalId": null,
				"units": null,
				"punchId": 192690797
			},
			{
				"eebadge": null,
				"eecode": "A01I",
				"clocksequencenumber": null,
				"timezone": "PST",
				"punchtime": "1723968000",
				"deptcode": null,
				"cat1": null,
				"cat2": null,
				"cat3": null,
				"cat4": null,
				"cat5": null,
				"cat6": null,
				"cat7": null,
				"cat8": null,
				"cat9": null,
				"cat10": null,
				"cat11": null,
				"cat12": null,
				"cat13": null,
				"cat14": null,
				"cat15": null,
				"cat16": null,
				"cat17": null,
				"cat18": null,
				"cat19": null,
				"cat20": null,
				"punchdesc": null,
				"taxprofid": null,
				"hours": 6.5,
				"dollaramount": null,
				"earncode": "R",
				"earnrate": null,
				"fixedamount": 0,
				"fixedearncode": null,
				"makeUpTime": false,
				"clocktype": null,
				"entrytype": 2,
				"punchtype": "HR",
				"externalId": null,
				"units": null,
				"punchId": 192690798
			},
			{
				"eebadge": null,
				"eecode": "A01I",
				"clocksequencenumber": null,
				"timezone": "PST",
				"punchtime": "1724054400",
				"deptcode": null,
				"cat1": null,
				"cat2": null,
				"cat3": null,
				"cat4": null,
				"cat5": null,
				"cat6": null,
				"cat7": null,
				"cat8": null,
				"cat9": null,
				"cat10": null,
				"cat11": null,
				"cat12": null,
				"cat13": null,
				"cat14": null,
				"cat15": null,
				"cat16": null,
				"cat17": null,
				"cat18": null,
				"cat19": null,
				"cat20": null,
				"punchdesc": null,
				"taxprofid": null,
				"hours": 10,
				"dollaramount": null,
				"earncode": "R",
				"earnrate": null,
				"fixedamount": 0,
				"fixedearncode": null,
				"makeUpTime": false,
				"clocktype": null,
				"entrytype": 2,
				"punchtype": "HR",
				"externalId": null,
				"units": null,
				"punchId": 192690799
			},
			{
				"eebadge": null,
				"eecode": "A01I",
				"clocksequencenumber": null,
				"timezone": "PST",
				"punchtime": "1724140800",
				"deptcode": null,
				"cat1": null,
				"cat2": null,
				"cat3": null,
				"cat4": null,
				"cat5": null,
				"cat6": null,
				"cat7": null,
				"cat8": null,
				"cat9": null,
				"cat10": null,
				"cat11": null,
				"cat12": null,
				"cat13": null,
				"cat14": null,
				"cat15": null,
				"cat16": null,
				"cat17": null,
				"cat18": null,
				"cat19": null,
				"cat20": null,
				"punchdesc": null,
				"taxprofid": null,
				"hours": 11.5,
				"dollaramount": null,
				"earncode": "R",
				"earnrate": null,
				"fixedamount": 0,
				"fixedearncode": null,
				"makeUpTime": false,
				"clocktype": null,
				"entrytype": 2,
				"punchtype": "HR",
				"externalId": null,
				"units": null,
				"punchId": 192690800
			},
			{
				"eebadge": null,
				"eecode": "A01I",
				"clocksequencenumber": null,
				"timezone": "PST",
				"punchtime": "1724227200",
				"deptcode": null,
				"cat1": null,
				"cat2": null,
				"cat3": null,
				"cat4": null,
				"cat5": null,
				"cat6": null,
				"cat7": null,
				"cat8": null,
				"cat9": null,
				"cat10": null,
				"cat11": null,
				"cat12": null,
				"cat13": null,
				"cat14": null,
				"cat15": null,
				"cat16": null,
				"cat17": null,
				"cat18": null,
				"cat19": null,
				"cat20": null,
				"punchdesc": null,
				"taxprofid": null,
				"hours": 8.5,
				"dollaramount": null,
				"earncode": "R",
				"earnrate": null,
				"fixedamount": 0,
				"fixedearncode": null,
				"makeUpTime": false,
				"clocktype": null,
				"entrytype": 2,
				"punchtype": "HR",
				"externalId": null,
				"units": null,
				"punchId": 192690801
			},
			{
				"eebadge": null,
				"eecode": "A01I",
				"clocksequencenumber": null,
				"timezone": "PST",
				"punchtime": "1724313600",
				"deptcode": null,
				"cat1": null,
				"cat2": null,
				"cat3": null,
				"cat4": null,
				"cat5": null,
				"cat6": null,
				"cat7": null,
				"cat8": null,
				"cat9": null,
				"cat10": null,
				"cat11": null,
				"cat12": null,
				"cat13": null,
				"cat14": null,
				"cat15": null,
				"cat16": null,
				"cat17": null,
				"cat18": null,
				"cat19": null,
				"cat20": null,
				"punchdesc": null,
				"taxprofid": null,
				"hours": 8,
				"dollaramount": null,
				"earncode": "R",
				"earnrate": null,
				"fixedamount": 0,
				"fixedearncode": null,
				"makeUpTime": false,
				"clocktype": null,
				"entrytype": 2,
				"punchtype": "HR",
				"externalId": null,
				"units": null,
				"punchId": 192690802
			},
			{
				"eebadge": null,
				"eecode": "A01I",
				"clocksequencenumber": null,
				"timezone": "PST",
				"punchtime": "1724400000",
				"deptcode": null,
				"cat1": null,
				"cat2": null,
				"cat3": null,
				"cat4": null,
				"cat5": null,
				"cat6": null,
				"cat7": null,
				"cat8": null,
				"cat9": null,
				"cat10": null,
				"cat11": null,
				"cat12": null,
				"cat13": null,
				"cat14": null,
				"cat15": null,
				"cat16": null,
				"cat17": null,
				"cat18": null,
				"cat19": null,
				"cat20": null,
				"punchdesc": null,
				"taxprofid": null,
				"hours": 7.5,
				"dollaramount": null,
				"earncode": "R",
				"earnrate": null,
				"fixedamount": 0,
				"fixedearncode": null,
				"makeUpTime": false,
				"clocktype": null,
				"entrytype": 2,
				"punchtype": "HR",
				"externalId": null,
				"units": null,
				"punchId": 192690803
			},
			{
				"eebadge": null,
				"eecode": "A01I",
				"clocksequencenumber": null,
				"timezone": "PST",
				"punchtime": "1724486400",
				"deptcode": null,
				"cat1": null,
				"cat2": null,
				"cat3": null,
				"cat4": null,
				"cat5": null,
				"cat6": null,
				"cat7": null,
				"cat8": null,
				"cat9": null,
				"cat10": null,
				"cat11": null,
				"cat12": null,
				"cat13": null,
				"cat14": null,
				"cat15": null,
				"cat16": null,
				"cat17": null,
				"cat18": null,
				"cat19": null,
				"cat20": null,
				"punchdesc": null,
				"taxprofid": null,
				"hours": 1.5,
				"dollaramount": null,
				"earncode": "R",
				"earnrate": null,
				"fixedamount": 0,
				"fixedearncode": null,
				"makeUpTime": false,
				"clocktype": null,
				"entrytype": 2,
				"punchtype": "HR",
				"externalId": null,
				"units": null,
				"punchId": 192690804
			},
			{
				"eebadge": null,
				"eecode": "A01I",
				"clocksequencenumber": null,
				"timezone": "PST",
				"punchtime": "1724659200",
				"deptcode": null,
				"cat1": null,
				"cat2": null,
				"cat3": null,
				"cat4": null,
				"cat5": null,
				"cat6": null,
				"cat7": null,
				"cat8": null,
				"cat9": null,
				"cat10": null,
				"cat11": null,
				"cat12": null,
				"cat13": null,
				"cat14": null,
				"cat15": null,
				"cat16": null,
				"cat17": null,
				"cat18": null,
				"cat19": null,
				"cat20": null,
				"punchdesc": null,
				"taxprofid": null,
				"hours": 8,
				"dollaramount": null,
				"earncode": "PTM",
				"earnrate": null,
				"fixedamount": 0,
				"fixedearncode": null,
				"makeUpTime": false,
				"clocktype": null,
				"entrytype": 2,
				"punchtype": "HR",
				"externalId": null,
				"units": null,
				"punchId": 192690805
			},
			{
				"eebadge": null,
				"eecode": "A01I",
				"clocksequencenumber": null,
				"timezone": "PST",
				"punchtime": "1724745600",
				"deptcode": null,
				"cat1": null,
				"cat2": null,
				"cat3": null,
				"cat4": null,
				"cat5": null,
				"cat6": null,
				"cat7": null,
				"cat8": null,
				"cat9": null,
				"cat10": null,
				"cat11": null,
				"cat12": null,
				"cat13": null,
				"cat14": null,
				"cat15": null,
				"cat16": null,
				"cat17": null,
				"cat18": null,
				"cat19": null,
				"cat20": null,
				"punchdesc": null,
				"taxprofid": null,
				"hours": 8,
				"dollaramount": null,
				"earncode": "PTM",
				"earnrate": null,
				"fixedamount": 0,
				"fixedearncode": null,
				"makeUpTime": false,
				"clocktype": null,
				"entrytype": 2,
				"punchtype": "HR",
				"externalId": null,
				"units": null,
				"punchId": 192690806
			},
			{
				"eebadge": null,
				"eecode": "A01I",
				"clocksequencenumber": null,
				"timezone": "PST",
				"punchtime": "1724832000",
				"deptcode": null,
				"cat1": null,
				"cat2": null,
				"cat3": null,
				"cat4": null,
				"cat5": null,
				"cat6": null,
				"cat7": null,
				"cat8": null,
				"cat9": null,
				"cat10": null,
				"cat11": null,
				"cat12": null,
				"cat13": null,
				"cat14": null,
				"cat15": null,
				"cat16": null,
				"cat17": null,
				"cat18": null,
				"cat19": null,
				"cat20": null,
				"punchdesc": null,
				"taxprofid": null,
				"hours": 8,
				"dollaramount": null,
				"earncode": "PTM",
				"earnrate": null,
				"fixedamount": 0,
				"fixedearncode": null,
				"makeUpTime": false,
				"clocktype": null,
				"entrytype": 2,
				"punchtype": "HR",
				"externalId": null,
				"units": null,
				"punchId": 192690807
			},
			{
				"eebadge": null,
				"eecode": "A01I",
				"clocksequencenumber": null,
				"timezone": "PST",
				"punchtime": "1724918400",
				"deptcode": null,
				"cat1": null,
				"cat2": null,
				"cat3": null,
				"cat4": null,
				"cat5": null,
				"cat6": null,
				"cat7": null,
				"cat8": null,
				"cat9": null,
				"cat10": null,
				"cat11": null,
				"cat12": null,
				"cat13": null,
				"cat14": null,
				"cat15": null,
				"cat16": null,
				"cat17": null,
				"cat18": null,
				"cat19": null,
				"cat20": null,
				"punchdesc": null,
				"taxprofid": null,
				"hours": 8,
				"dollaramount": null,
				"earncode": "PTM",
				"earnrate": null,
				"fixedamount": 0,
				"fixedearncode": null,
				"makeUpTime": false,
				"clocktype": null,
				"entrytype": 2,
				"punchtype": "HR",
				"externalId": null,
				"units": null,
				"punchId": 192690808
			},
			{
				"eebadge": null,
				"eecode": "A01I",
				"clocksequencenumber": null,
				"timezone": "PST",
				"punchtime": "1725004800",
				"deptcode": null,
				"cat1": null,
				"cat2": null,
				"cat3": null,
				"cat4": null,
				"cat5": null,
				"cat6": null,
				"cat7": null,
				"cat8": null,
				"cat9": null,
				"cat10": null,
				"cat11": null,
				"cat12": null,
				"cat13": null,
				"cat14": null,
				"cat15": null,
				"cat16": null,
				"cat17": null,
				"cat18": null,
				"cat19": null,
				"cat20": null,
				"punchdesc": null,
				"taxprofid": null,
				"hours": 8,
				"dollaramount": null,
				"earncode": "PTM",
				"earnrate": null,
				"fixedamount": 0,
				"fixedearncode": null,
				"makeUpTime": false,
				"clocktype": null,
				"entrytype": 2,
				"punchtype": "HR",
				"externalId": null,
				"units": null,
				"punchId": 192690809
			}
		],
		"errors": [],
		"errorCount": 0,
		"records": 13
	}
}


def load_records(log_artifact):
    return rail.load_all_records(log_artifact)

def get_status(item, logstatus):
    status = 'status' if item.get('status') else 'Status'
    return item[status].lower() == logstatus

def do_format_logs(dag_run):
    log_artifacts = []
    log_records = []

    entry_logs = dag_run.conf['entry_logs']
    otherlogs = dag_run.conf['otherlogs']

    if entry_logs:
        if isinstance(entry_logs, list):
            log_artifacts.extend(entry_logs)
        elif isinstance(entry_logs, str) and entry_logs[0] == '[':
            entry_logs = literal_eval(entry_logs)
            log_artifacts.extend(entry_logs)
        else:
            log_artifacts.append(entry_logs)

    if otherlogs:
        if isinstance(otherlogs, list):
            log_artifacts.extend(otherlogs)
        elif isinstance(otherlogs, str) and otherlogs[0] == '[':
            otherlogs = literal_eval(otherlogs)
            log_artifacts.extend(otherlogs)
        else:
            log_artifacts.append(otherlogs)

    if log_artifacts:
        for log in log_artifacts:
            each_log_records = load_records(log)
            if each_log_records:
                log_records.extend(each_log_records)

    final_log_records = list(map(lambda log: {
        **{"ecid": log['ecid']},
        **dict(log['properties'].items()),
    }, log_records))

    rail.set_result(key="error_record_count",val= len(list(filter(lambda x: get_status(x, 'error'), final_log_records ))))
    rail.set_result(key="success_record_count",val= len(list(filter(lambda x: get_status(x, 'success'), final_log_records ))))
    rail.set_result(key="exception_record_count",val= len(list(filter(lambda x: get_status(x, 'exception'), final_log_records ))))
    rail.set_result(key="skipped_record_count",val= len(list(filter(lambda x: get_status(x, 'skipped'), final_log_records ))))

    return  final_log_records
