level_2_tasks_mapper = [
                    {"task_level_2": "Ops Manager", "Allowed": "Yes"},
                    {"task_level_2": "Mentor Manager", "Allowed": "Yes"},
                    {"task_level_2": "Team Lead", "Allowed": "Yes"},
                    {"task_level_2": "Facilities Manager", "Allowed": "Yes"},
                    {"task_level_2": "Consumer Line", "Allowed": "Yes"},
                    {"task_level_2": "QA", "Allowed": "Yes"},
                    {"task_level_2": "Spanish", "Allowed": "Yes"},
                    {"task_level_2": "Customer Service", "Allowed": "Yes"},
                    {"task_level_2": "New Hire Trainer", "Allowed": "Yes"},
                    {"task_level_2": "Qualification Agent", "Allowed": "Yes"},
                    {"task_level_2": "Program Trainer", "Allowed": "Yes"},
                    {"task_level_2": "Agent", "Allowed": "Yes"},
                    {"task_level_2": "Non-billable QA", "Allowed": "Yes"},
                    {"task_level_2": "OB Agent", "Allowed": "Yes"},
                    {"task_level_2": "Voice Rep", "Allowed": "Yes"},
                    {"task_level_2": "IT Helpdesk", "Allowed": "Yes"},
                    {"task_level_2": "CC - Canada", "Allowed": "Yes"},
                    {"task_level_2": "Security", "Allowed": "Yes"},
                    {"task_level_2": "Maternity", "Allowed": "Yes"},
                    {"task_level_2": "Mediacom", "Allowed": "Yes"},
                    {"task_level_2": "Recruiting Manager", "Allowed": "Yes"},
                    {"task_level_2": "Client Assigner", "Allowed": "Yes"},
                    {"task_level_2": "Network Administrator", "Allowed": "Yes"},
                    {"task_level_2": "Claims Agent", "Allowed": "Yes"},
                    {"task_level_2": "Scheduling Agent", "Allowed": "Yes"},
                    {"task_level_2": "Assistant Recruiter", "Allowed": "Yes"},
                    {"task_level_2": "Mint Agent", "Allowed": "Yes"},
                    {"task_level_2": "SVP, Operations", "Allowed": "Yes"},
                    {"task_level_2": "Docs Agent", "Allowed": "Yes"},
                    {"task_level_2": "Printer", "Allowed": "Yes"},
                    {"task_level_2": "Dialer Admin", "Allowed": "Yes"},
                    {"task_level_2": "RCN-Grande-Wave", "Allowed": "Yes"},
                    {"task_level_2": "GJS Escalations", "Allowed": "Yes"},
                    {"task_level_2": "Tier 1", "Allowed": "Yes"},
                    {"task_level_2": "New Hire Training", "Allowed": "Yes"},
                    {"task_level_2": "TXMD - Inbound", "Allowed": "Yes"},
                    {"task_level_2": "Waste Management TL", "Allowed": "Yes"},
                    {"task_level_2": "PPS Agent", "Allowed": "Yes"},
                    {"task_level_2": "Assigner", "Allowed": "Yes"},
                    {"task_level_2": "Accounting Clerk", "Allowed": "Yes"},
                    {"task_level_2": "Transportation Manager", "Allowed": "Yes"},
                    {"task_level_2": "Books Escalations", "Allowed": "Yes"},
                    {"task_level_2": "Mediacom TL", "Allowed": "Yes"},
                    {"task_level_2": "Reports Analyst", "Allowed": "Yes"},
                    {"task_level_2": "Site Director", "Allowed": "Yes"},
                    {"task_level_2": "Cushions Agent", "Allowed": "Yes"},
                    {"task_level_2": "K&L Sales", "Allowed": "Yes"},
                    {"task_level_2": "PLUS", "Allowed": "Yes"},
                    {"task_level_2": "Journals", "Allowed": "Yes"},
                    {"task_level_2": "Consolidated Credit", "Allowed": "Yes"},
                    {"task_level_2": "Training Manager", "Allowed": "Yes"},
                    {"task_level_2": "Bilingual", "Allowed": "Yes"},
                    {"task_level_2": "Payroll Clerk", "Allowed": "Yes"},
                    {"task_level_2": "CS Americas Escalations", "Allowed": "Yes"},
                    {"task_level_2": "Waste Management", "Allowed": "Yes"},
                    {"task_level_2": "Porter", "Allowed": "Yes"},
                    {"task_level_2": "Comps", "Allowed": "Yes"},
                    {"task_level_2": "Returns", "Allowed": "Yes"},
                    {"task_level_2": "Inbound Reorder", "Allowed": "Yes"},
                    {"task_level_2": "Learning House", "Allowed": "Yes"},
                    {"task_level_2": "Billable SME", "Allowed": "Yes"},
                    {"task_level_2": "US Longevity Agent", "Allowed": "Yes"},
                    {"task_level_2": "IV-PARs Agent", "Allowed": "Yes"},
                    {"task_level_2": "SME-Non Billable", "Allowed": "Yes"},
                    {"task_level_2": "Corporate Hospitality Coordinator", "Allowed": "Yes"},
                    {"task_level_2": "Systems Administrator", "Allowed": "Yes"},
                    {"task_level_2": "HR Site Manager", "Allowed": "Yes"}
            ]