## JOB CODES based on last two characters (change v1.6 job code change) ###
# ALL = A1,A2,A3,A4,A5,M1,M2,M3,M4,M5,M6,S1,S2,S3,S4,S5,T1,T2,T3,T4,T5,T6,X9,OTHER
# TYPE 1 = In S1,S2,S3,S4,S5,X9
# TYPE 2 = Not In S1,S2,S3,S4,S5,X9

user_import_mapper = [
    {
        "location_level_1": "CAN",
        "location_level_2": "Quebec",
        "location_level_3": ["STCONSTANT"],
        "activity_type": "Blank",
        "reg_temp": "Regular",
        "job_code": "ALL",
        "pay_type": "Salaried",
        "timesheet_period": "Canada - Weekly starting on Monday",
        "timesheet_template": None,
        "punch_policy": None,
        "holiday_calendar": "St. Constant",
        "timesheet_approval_path": "Supervisor",
        "time_off_template": "Time Off",
        "time_off_approver": "Supervisor",
        "work_week": "Monday to Sunday",
        "payrule_name": "CAN_SALARIED",
        "timezone": "(UTC-5:00) Eastern Standard Time"
    },
    {
        "location_level_1": "CAN",
        "location_level_2": "Quebec",
        "location_level_3": ["STCONSTANT"],
        "activity_type": "Blank",
        "reg_temp": "Regular",
        "job_code": "ALL",
        "pay_type": "Exception Hourly",
        "timesheet_period": "Canada - Weekly starting on Monday",
        "timesheet_template": "CAN_SALOT_ELIGIBLE",
        "punch_policy": None,
        "holiday_calendar": "St. Constant",
        "timesheet_approval_path": "Supervisor - Exception time",
        "time_off_template": "Time Off",
        "time_off_approver": "Supervisor",
        "work_week": "Monday to Sunday",
        "payrule_name": "St. Constant - Salaried OT Eligible",
        "timezone": "(UTC-5:00) Eastern Standard Time"
    },
    {
        "location_level_1": "CAN",
        "location_level_2": "Quebec",
        "location_level_3": ["STCONSTANT"],
        "activity_type": "Blank",
        "reg_temp": "Regular",
        "job_code": "ALL",
        "pay_type": "Hourly",
        "timesheet_period": "Canada - Weekly starting on Monday",
        "timesheet_template": "CAN_HRLY_ StConstant_No Proj",
        "punch_policy": "St. Constant Hourly_No Proj",
        "holiday_calendar": "St. Constant",
        "timesheet_approval_path": "Supervisor",
        "time_off_template": "Time Off",
        "time_off_approver": "Supervisor",
        "work_week": "Monday to Sunday",
        "payrule_name": "St. Constant - Hourly",
        "timezone": "(UTC-5:00) Eastern Standard Time"
    },
    {
        "location_level_1": "CAN",
        "location_level_2": "Quebec",
        "location_level_3": ["STCONSTANT"],
        "activity_type": "Populated",
        "reg_temp": "Regular",
        "job_code": "ALL",
        "pay_type": "Salaried",
        "timesheet_period": "Canada - Weekly starting on Monday",
        "timesheet_template": "CAN_SAL_EMP_PROJ",
        "punch_policy": None,
        "holiday_calendar": "St. Constant",
        "timesheet_approval_path": "Supervisor",
        "time_off_template": "Time Off",
        "time_off_approver": "Supervisor",
        "work_week": "Monday to Sunday",
        "payrule_name": "CAN_SALARIED",
        "timezone": "(UTC-5:00) Eastern Standard Time"
    },
    {
        "location_level_1": "CAN",
        "location_level_2": "Quebec",
        "location_level_3": ["STCONSTANT"],
        "activity_type": "Populated",
        "reg_temp": "Regular",
        "job_code": "ALL",
        "pay_type": "Exception Hourly",
        "timesheet_period": "Canada - Weekly starting on Monday",
        "timesheet_template": "CAN_SALOT_ELIGIBLE_PROJ",
        "punch_policy": None,
        "holiday_calendar": "St. Constant",
        "timesheet_approval_path": "Supervisor - Exception time",
        "time_off_template": "Time Off",
        "time_off_approver": "Supervisor",
        "work_week": "Monday to Sunday",
        "payrule_name": "St. Constant - Salaried OT Eligible",
        "timezone": "(UTC-5:00) Eastern Standard Time"
    },
    {
        "location_level_1": "CAN",
        "location_level_2": "Quebec",
        "location_level_3": ["STCONSTANT"],
        "activity_type": "Populated",
        "reg_temp": "Regular",
        "job_code": "ALL",
        "pay_type": "Hourly",
        "timesheet_period": "Canada - Weekly starting on Monday",
        "timesheet_template": "CAN_St. Constant_HRLY_PROJ",
        "punch_policy": "St. Constant Hourly_Proj",
        "holiday_calendar": "St. Constant",
        "timesheet_approval_path": "Supervisor",
        "time_off_template": "Time Off",
        "time_off_approver": "Supervisor",
        "work_week": "Monday to Sunday",
        "payrule_name": "St. Constant - Hourly",
        "timezone": "(UTC-5:00) Eastern Standard Time"
    },
    {
        "location_level_1": "CAN",
        "location_level_2": "Quebec",
        "location_level_3": ["MONTREAL","SHERBROOKE"],
        "activity_type": "Blank",
        "reg_temp": "Regular",
        "job_code": "ALL",
        "pay_type": "Salaried",
        "timesheet_period": "Canada - Weekly starting on Monday",
        "timesheet_template": None,
        "punch_policy": None,
        "holiday_calendar": "Montreal and Sherbrooke",
        "timesheet_approval_path": "Supervisor",
        "time_off_template": "Time Off",
        "time_off_approver": "Supervisor",
        "work_week": "Monday to Sunday",
        "payrule_name": "CAN_SALARIED",
        "timezone": "(UTC-5:00) Eastern Standard Time"
    },
    {
        "location_level_1": "CAN",
        "location_level_2": "Quebec",
        "location_level_3": ["MONTREAL","SHERBROOKE"],
        "activity_type": "Blank",
        "reg_temp": "Regular",
        "job_code": "ALL",
        "pay_type": "Exception Hourly",
        "timesheet_period": "Canada - Weekly starting on Monday",
        "timesheet_template": "CAN_SALOT_ELIGIBLE",
        "punch_policy": None,
        "holiday_calendar": "Montreal and Sherbrooke",
        "timesheet_approval_path": "Supervisor - Exception time",
        "time_off_template": "Time Off",
        "time_off_approver": "Supervisor",
        "work_week": "Monday to Sunday",
        "payrule_name": "Montreal - Salaried OT Eligible",
        "timezone": "(UTC-5:00) Eastern Standard Time"
    },
    {
        "location_level_1": "CAN",
        "location_level_2": "Quebec",
        "location_level_3": ["MONTREAL","SHERBROOKE"],
        "activity_type": "Blank",
        "reg_temp": "Regular",
        "job_code": "TYPE 2",
        "pay_type": "Hourly",
        "timesheet_period": "Canada - Weekly starting on Monday",
        "timesheet_template": "CAN_HRLY_MONTREAL (No project)",
        "punch_policy": "Montreal HRLY With Proj No Prem",
        "holiday_calendar": "Montreal and Sherbrooke",
        "timesheet_approval_path": "Supervisor",
        "time_off_template": "Time Off",
        "time_off_approver": "Supervisor",
        "work_week": "Monday to Sunday",
        "payrule_name": "Montreal - HRLY - wo premiums",
        "timezone": "(UTC-5:00) Eastern Standard Time"
    },
    {
        "location_level_1": "CAN",
        "location_level_2": "Quebec",
        "location_level_3": ["MONTREAL","SHERBROOKE"],
        "activity_type": "Blank",
        "reg_temp": "Regular",
        "job_code": "TYPE 1",
        "pay_type": "Hourly",
        "timesheet_period": "Canada - Weekly starting on Monday",
        "timesheet_template": "CAN_HRLY_MONTREAL (No project) PREM",
        "punch_policy": "CAN_HRLY_MONTREAL With Prem",
        "holiday_calendar": "Montreal and Sherbrooke",
        "timesheet_approval_path": "Supervisor",
        "time_off_template": "Time Off",
        "time_off_approver": "Supervisor",
        "work_week": "Monday to Sunday",
        "payrule_name": "Montreal - HRLY - premiums",
        "timezone": "(UTC-5:00) Eastern Standard Time"
    },
    {
        "location_level_1": "CAN",
        "location_level_2": "Quebec",
        "location_level_3": ["MONTREAL","SHERBROOKE"],
        "activity_type": "Populated",
        "reg_temp": "Regular",
        "job_code": "NA",
        "pay_type": "Salaried",
        "timesheet_period": "Canada - Weekly starting on Monday",
        "timesheet_template": "CAN_SAL_EMP_PROJ",
        "punch_policy": None,
        "holiday_calendar": "Montreal and Sherbrooke",
        "timesheet_approval_path": "Supervisor",
        "time_off_template": "Time Off",
        "time_off_approver": "Supervisor",
        "work_week": "Monday to Sunday",
        "payrule_name": "CAN_SALARIED",
        "timezone": "(UTC-5:00) Eastern Standard Time"
    },
    {
        "location_level_1": "CAN",
        "location_level_2": "Quebec",
        "location_level_3": ["MONTREAL","SHERBROOKE"],
        "activity_type": "Populated",
        "reg_temp": "Regular",
        "job_code": "ALL",
        "pay_type": "Exception Hourly",
        "timesheet_period": "Canada - Weekly starting on Monday",
        "timesheet_template": "CAN_SALOT_ELIGIBLE_PROJ",
        "punch_policy": None,
        "holiday_calendar": "Montreal and Sherbrooke",
        "timesheet_approval_path": "Supervisor - Exception time",
        "time_off_template": "Time Off",
        "time_off_approver": "Supervisor",
        "work_week": "Monday to Sunday",
        "payrule_name": "Montreal - Salaried OT Eligible",
        "timezone": "(UTC-5:00) Eastern Standard Time"
    },
    {
        "location_level_1": "CAN",
        "location_level_2": "Quebec",
        "location_level_3": ["MONTREAL","SHERBROOKE"],
        "activity_type": "Populated",
        "reg_temp": "Regular",
        "job_code": "TYPE 2",
        "pay_type": "Hourly",
        "timesheet_period": "Canada - Weekly starting on Monday",
        "timesheet_template": "CAN_HRLY_MONTREAL_PROJ_NO PREM",
        "punch_policy": "Montreal HRLY With Proj No Prem",
        "holiday_calendar": "Montreal and Sherbrooke",
        "timesheet_approval_path": "Supervisor",
        "time_off_template": "Time Off",
        "time_off_approver": "Supervisor",
        "work_week": "Monday to Sunday",
        "payrule_name": "Montreal - HRLY - wo premiums",
        "timezone": "(UTC-5:00) Eastern Standard Time"
    },
    {
        "location_level_1": "CAN",
        "location_level_2": "Quebec",
        "location_level_3": ["MONTREAL","SHERBROOKE"],
        "activity_type": "Populated",
        "reg_temp": "Regular",
        "job_code": "TYPE 1",
        "pay_type": "Hourly",
        "timesheet_period": "Canada - Weekly starting on Monday",
        "timesheet_template": "CAN_HRLY_MONTREAL_PROJ",
        "punch_policy": "CAN_HRLY_MONTREAL With Prem",
        "holiday_calendar": "Montreal and Sherbrooke",
        "timesheet_approval_path": "Supervisor",
        "time_off_template": "Time Off",
        "time_off_approver": "Supervisor",
        "work_week": "Monday to Sunday",
        "payrule_name": "Montreal - HRLY - premiums",
        "timezone": "(UTC-5:00) Eastern Standard Time"
    },
    {
        "location_level_1": "CAN",
        "location_level_2": "Quebec",
        "location_level_3": ["LAVAL","LAVALQ","TERREBONNE","BOISBRIAND"],
        "activity_type": "Blank",
        "reg_temp": "Regular",
        "job_code": "ALL",
        "pay_type": "Exception Hourly",
        "timesheet_period": "Canada - Weekly starting on Monday",
        "timesheet_template": "CAN_SALOT_ELIGIBLE",
        "punch_policy": None,
        "holiday_calendar": "LAVAL, BBD, TBNE",
        "timesheet_approval_path": "Supervisor - Exception time",
        "time_off_template": "Time Off",
        "time_off_approver": "Supervisor",
        "work_week": "Monday to Sunday",
        "payrule_name": "Montreal - Salaried OT Eligible",
        "timezone": "(UTC-5:00) Eastern Standard Time"
    },
    {
        "location_level_1": "CAN",
        "location_level_2": "Quebec",
        "location_level_3": ["LAVAL","LAVALQ","TERREBONNE","BOISBRIAND"],
        "activity_type": "Populated",
        "reg_temp": "Regular",
        "job_code": "ALL",
        "pay_type": "Exception Hourly",
        "timesheet_period": "Canada - Weekly starting on Monday",
        "timesheet_template": "CAN_SALOT_ELIGIBLE_PROJ",
        "punch_policy": None,
        "holiday_calendar": "LAVAL, BBD, TBNE",
        "timesheet_approval_path": "Supervisor - Exception time",
        "time_off_template": "Time Off",
        "time_off_approver": "Supervisor",
        "work_week": "Monday to Sunday",
        "payrule_name": "Montreal - Salaried OT Eligible",
        "timezone": "(UTC-5:00) Eastern Standard Time"
    },
    {
        "location_level_1": "CAN",
        "location_level_2": "Quebec",
        "location_level_3": ["LAVAL","LAVALQ","TERREBONNE","BOISBRIAND"],
        "activity_type": "Blank",
        "reg_temp": "Regular",
        "job_code": "ALL",
        "pay_type": "Salaried",
        "timesheet_period": "Canada - Weekly starting on Monday",
        "timesheet_template": None,
        "punch_policy": None,
        "holiday_calendar": "LAVAL, BBD, TBNE",
        "timesheet_approval_path": "Supervisor",
        "time_off_template": "Time Off",
        "time_off_approver": "Supervisor",
        "work_week": "Monday to Sunday",
        "payrule_name": "CAN_SALARIED",
        "timezone": "(UTC-5:00) Eastern Standard Time"
    },
    {
        "location_level_1": "CAN",
        "location_level_2": "Quebec",
        "location_level_3": ["LAVAL","LAVALQ","TERREBONNE","BOISBRIAND"],
        "activity_type": "Populated",
        "reg_temp": "Regular",
        "job_code": "NA",
        "pay_type": "Salaried",
        "timesheet_period": "Canada - Weekly starting on Monday",
        "timesheet_template": "CAN_SAL_EMP_PROJ",
        "punch_policy": None,
        "holiday_calendar": "LAVAL, BBD, TBNE",
        "timesheet_approval_path": "Supervisor",
        "time_off_template": "Time Off",
        "time_off_approver": "Supervisor",
        "work_week": "Monday to Sunday",
        "payrule_name": "CAN_SALARIED",
        "timezone": "(UTC-5:00) Eastern Standard Time"
    },
    {
        "location_level_1": "CAN",
        "location_level_2": "Quebec",
        "location_level_3": ["LAVAL","LAVALQ","TERREBONNE","BOISBRIAND"],
        "activity_type": "Blank",
        "reg_temp": "Regular",
        "job_code": "TYPE 1",
        "pay_type": "Hourly",
        "timesheet_period": "Canada - Weekly starting on Monday",
        "timesheet_template": "CAN_HRLY_MONTREAL (No project) PREM",
        "punch_policy": "CAN_HRLY_MONTREAL With Prem",
        "holiday_calendar": "LAVAL, BBD, TBNE",
        "timesheet_approval_path": "Supervisor",
        "time_off_template": "Time Off",
        "time_off_approver": "Supervisor",
        "work_week": "Monday to Sunday",
        "payrule_name": "Montreal - HRLY - premiums",
        "timezone": "(UTC-5:00) Eastern Standard Time"
    },
    {
        "location_level_1": "CAN",
        "location_level_2": "Quebec",
        "location_level_3": ["LAVAL","LAVALQ","TERREBONNE","BOISBRIAND"],
        "activity_type": "Populated",
        "reg_temp": "Regular",
        "job_code": "TYPE 1",
        "pay_type": "Hourly",
        "timesheet_period": "Canada - Weekly starting on Monday",
        "timesheet_template": "CAN_HRLY_MONTREAL_PROJ",
        "punch_policy": "CAN_HRLY_MONTREAL With Prem",
        "holiday_calendar": "LAVAL, BBD, TBNE",
        "timesheet_approval_path": "Supervisor",
        "time_off_template": "Time Off",
        "time_off_approver": "Supervisor",
        "work_week": "Monday to Sunday",
        "payrule_name": "Montreal - HRLY - premiums",
        "timezone": "(UTC-5:00) Eastern Standard Time"
    },
    {
        "location_level_1": "CAN",
        "location_level_2": "Quebec",
        "location_level_3": "LAVAL|LAVALQ|TERREBONNE|BOISBRIAND",
        "activity_type": "Populated",
        "reg_temp": "Regular",
        "job_code": "TYPE 2",
        "pay_type": "Hourly",
        "timesheet_period": "Canada - Weekly starting on Monday",
        "timesheet_template": "CAN_HRLY_MONTREAL_PROJ_NO PREM",
        "punch_policy": "Montreal HRLY With Proj No Prem",
        "holiday_calendar": "LAVAL, BBD, TBNE",
        "timesheet_approval_path": "Supervisor",
        "time_off_template": "Time Off",
        "time_off_approver": "Supervisor",
        "work_week": "Monday to Sunday",
        "payrule_name": "Montreal - HRLY - wo premiums",
        "timezone": "(UTC-5:00) Eastern Standard Time"
    },
    {
        "location_level_1": "CAN",
        "location_level_2": "Quebec",
        "location_level_3": ["LAVAL","LAVALQ","TERREBONNE","BOISBRIAND"],
        "activity_type": "Blank",
        "reg_temp": "Regular",
        "job_code": "TYPE 2",
        "pay_type": "Hourly",
        "timesheet_period": "Canada - Weekly starting on Monday",
        "timesheet_template": "CAN_HRLY_MONTREAL (No project)",
        "punch_policy": "CAN_HRLY_MONTREAL (No project) PP",
        "holiday_calendar": "LAVAL, BBD, TBNE",
        "timesheet_approval_path": "Supervisor",
        "time_off_template": "Time Off",
        "time_off_approver": "Supervisor",
        "work_week": "Monday to Sunday",
        "payrule_name": "Montreal - HRLY - wo premiums",
        "timezone": "(UTC-5:00) Eastern Standard Time"
    },
    {
        "location_level_1": "CAN",
        "location_level_2": "Quebec",
        "location_level_3": ["STCONSTANT"],
        "activity_type": "Blank",
        "reg_temp": "Temporary",
        "job_code": "ALL",
        "pay_type": "Salaried",
        "timesheet_period": "Canada - Weekly starting on Monday",
        "timesheet_template": None,
        "punch_policy": None,
        "holiday_calendar": "St. Constant",
        "timesheet_approval_path": "Supervisor",
        "time_off_template": "Time Off",
        "time_off_approver": "Supervisor",
        "work_week": "Monday to Sunday",
        "payrule_name": "CAN_SALARIED",
        "timezone": "(UTC-5:00) Eastern Standard Time"
    },
    {
        "location_level_1": "CAN",
        "location_level_2": "Quebec",
        "location_level_3": ["STCONSTANT"],
        "activity_type": "Blank",
        "reg_temp": "Temporary",
        "job_code": "ALL",
        "pay_type": "Exception Hourly",
        "timesheet_period": "Canada - Weekly starting on Monday",
        "timesheet_template": "CAN_SALOT_ELIGIBLE",
        "punch_policy": None,
        "holiday_calendar": "St. Constant",
        "timesheet_approval_path": "Supervisor - Exception time",
        "time_off_template": "Time Off",
        "time_off_approver": "Supervisor",
        "work_week": "Monday to Sunday",
        "payrule_name": "St. Constant - Salaried OT Eligible",
        "timezone": "(UTC-5:00) Eastern Standard Time"
    },
    {
        "location_level_1": "CAN",
        "location_level_2": "Quebec",
        "location_level_3": ["STCONSTANT"],
        "activity_type": "Blank",
        "reg_temp": "Temporary",
        "job_code": "ALL",
        "pay_type": "Hourly",
        "timesheet_period": "Canada - Weekly starting on Monday",
        "timesheet_template": "CAN_HRLY_ StConstant_No Proj_Temp",
        "punch_policy": "St. Constant Hourly_No Proj",
        "holiday_calendar": "St. Constant",
        "timesheet_approval_path": "Supervisor",
        "time_off_template": "Time Off",
        "time_off_approver": "Supervisor",
        "work_week": "Monday to Sunday",
        "payrule_name": "St. Constant - Temp",
        "timezone": "(UTC-5:00) Eastern Standard Time"
    },
    {
        "location_level_1": "CAN",
        "location_level_2": "Quebec",
        "location_level_3": ["STCONSTANT"],
        "activity_type": "Populated",
        "reg_temp": "Temporary",
        "job_code": "ALL",
        "pay_type": "Salaried",
        "timesheet_period": "Canada - Weekly starting on Monday",
        "timesheet_template": "CAN_SAL_EMP_PROJ",
        "punch_policy": None,
        "holiday_calendar": "St. Constant",
        "timesheet_approval_path": "Supervisor",
        "time_off_template": "Time Off",
        "time_off_approver": "Supervisor",
        "work_week": "Monday to Sunday",
        "payrule_name": "CAN_SALARIED",
        "timezone": "(UTC-5:00) Eastern Standard Time"
    },
    {
        "location_level_1": "CAN",
        "location_level_2": "Quebec",
        "location_level_3": ["STCONSTANT"],
        "activity_type": "Populated",
        "reg_temp": "Temporary",
        "job_code": "ALL",
        "pay_type": "Exception Hourly",
        "timesheet_period": "Canada - Weekly starting on Monday",
        "timesheet_template": "CAN_SALOT_ELIGIBLE_PROJ",
        "punch_policy": None,
        "holiday_calendar": "St. Constant",
        "timesheet_approval_path": "Supervisor - Exception time",
        "time_off_template": "Time Off",
        "time_off_approver": "Supervisor",
        "work_week": "Monday to Sunday",
        "payrule_name": "St. Constant - Salaried OT Eligible",
        "timezone": "(UTC-5:00) Eastern Standard Time"
    },
    {
        "location_level_1": "CAN",
        "location_level_2": "Quebec",
        "location_level_3": ["STCONSTANT"],
        "activity_type": "Populated",
        "reg_temp": "Temporary",
        "job_code": "ALL",
        "pay_type": "Hourly",
        "timesheet_period": "Canada - Weekly starting on Monday",
        "timesheet_template": "CAN_St. Constant_HRLY_PROJ_Temp",
        "punch_policy": "St. Constant Hourly_Proj",
        "holiday_calendar": "St. Constant",
        "timesheet_approval_path": "Supervisor",
        "time_off_template": "Time Off",
        "time_off_approver": "Supervisor",
        "work_week": "Monday to Sunday",
        "payrule_name": "St. Constant - Temp",
        "timezone": "(UTC-5:00) Eastern Standard Time"
    },
    {
        "location_level_1": "CAN",
        "location_level_2": "Quebec",
        "location_level_3": ["MONTREAL","SHERBROOKE"],
        "activity_type": "Blank",
        "reg_temp": "Temporary",
        "job_code": "ALL",
        "pay_type": "Salaried",
        "timesheet_period": "Canada - Weekly starting on Monday",
        "timesheet_template": None,
        "punch_policy": None,
        "holiday_calendar": "Montreal and Sherbrooke",
        "timesheet_approval_path": "Supervisor",
        "time_off_template": "Time Off",
        "time_off_approver": "Supervisor",
        "work_week": "Monday to Sunday",
        "payrule_name": "CAN_SALARIED",
        "timezone": "(UTC-5:00) Eastern Standard Time"
    },
    {
        "location_level_1": "CAN",
        "location_level_2": "Quebec",
        "location_level_3": ["MONTREAL","SHERBROOKE"],
        "activity_type": "Blank",
        "reg_temp": "Temporary",
        "job_code": "ALL",
        "pay_type": "Exception Hourly",
        "timesheet_period": "Canada - Weekly starting on Monday",
        "timesheet_template": "CAN_SALOT_ELIGIBLE",
        "punch_policy": None,
        "holiday_calendar": "Montreal and Sherbrooke",
        "timesheet_approval_path": "Supervisor - Exception time",
        "time_off_template": "Time Off",
        "time_off_approver": "Supervisor",
        "work_week": "Monday to Sunday",
        "payrule_name": "Montreal - Salaried OT Eligible",
        "timezone": "(UTC-5:00) Eastern Standard Time"
    },
    {
        "location_level_1": "CAN",
        "location_level_2": "Quebec",
        "location_level_3": ["MONTREAL","SHERBROOKE"],
        "activity_type": "Blank",
        "reg_temp": "Temporary",
        "job_code": "TYPE 2",
        "pay_type": "Hourly",
        "timesheet_period": "Canada - Weekly starting on Monday",
        "timesheet_template": "CAN_HRLY_MONTREAL (No project)_Temp",
        "punch_policy": "CAN_HRLY_MONTREAL (No project) PP",
        "holiday_calendar": "Montreal and Sherbrooke",
        "timesheet_approval_path": "Supervisor",
        "time_off_template": "Time Off",
        "time_off_approver": "Supervisor",
        "work_week": "Monday to Sunday",
        "payrule_name": "Montreal - HRLY - wo premiums Temp",
        "timezone": "(UTC-5:00) Eastern Standard Time"
    },
    {
        "location_level_1": "CAN",
        "location_level_2": "Quebec",
        "location_level_3": ["MONTREAL","SHERBROOKE"],
        "activity_type": "Blank",
        "reg_temp": "Temporary",
        "job_code": "TYPE 1",
        "pay_type": "Hourly",
        "timesheet_period": "Canada - Weekly starting on Monday",
        "timesheet_template": "CAN_HRLY_MONTREAL (No project) PREM_Temp",
        "punch_policy": "CAN_HRLY_MONTREAL With Prem",
        "holiday_calendar": "Montreal and Sherbrooke",
        "timesheet_approval_path": "Supervisor",
        "time_off_template": "Time Off",
        "time_off_approver": "Supervisor",
        "work_week": "Monday to Sunday",
        "payrule_name": "Montreal - HRLY - premiums Temp",
        "timezone": "(UTC-5:00) Eastern Standard Time"
    },
    {
        "location_level_1": "CAN",
        "location_level_2": "Quebec",
        "location_level_3": ["MONTREAL","SHERBROOKE"],
        "activity_type": "Populated",
        "reg_temp": "Temporary",
        "job_code": "NA",
        "pay_type": "Salaried",
        "timesheet_period": "Canada - Weekly starting on Monday",
        "timesheet_template": "CAN_SAL_EMP_PROJ",
        "punch_policy": None,
        "holiday_calendar": "Montreal and Sherbrooke",
        "timesheet_approval_path": "Supervisor",
        "time_off_template": "Time Off",
        "time_off_approver": "Supervisor",
        "work_week": "Monday to Sunday",
        "payrule_name": "CAN_SALARIED",
        "timezone": "(UTC-5:00) Eastern Standard Time"
    },
    {
        "location_level_1": "CAN",
        "location_level_2": "Quebec",
        "location_level_3": ["MONTREAL","SHERBROOKE"],
        "activity_type": "Populated",
        "reg_temp": "Temporary",
        "job_code": "ALL",
        "pay_type": "Exception Hourly",
        "timesheet_period": "Canada - Weekly starting on Monday",
        "timesheet_template": "CAN_SALOT_ELIGIBLE_PROJ",
        "punch_policy": None,
        "holiday_calendar": "Montreal and Sherbrooke",
        "timesheet_approval_path": "Supervisor - Exception time",
        "time_off_template": "Time Off",
        "time_off_approver": "Supervisor",
        "work_week": "Monday to Sunday",
        "payrule_name": "Montreal - Salaried OT Eligible",
        "timezone": "(UTC-5:00) Eastern Standard Time"
    },
    {
        "location_level_1": "CAN",
        "location_level_2": "Quebec",
        "location_level_3": ["MONTREAL","SHERBROOKE"],
        "activity_type": "Populated",
        "reg_temp": "Temporary",
        "job_code": "TYPE 2",
        "pay_type": "Hourly",
        "timesheet_period": "Canada - Weekly starting on Monday",
        "timesheet_template": "CAN_HRLY_MONTREAL_PROJ_NO PREM_Temp",
        "punch_policy": "Montreal HRLY With Proj No Prem",
        "holiday_calendar": "Montreal and Sherbrooke",
        "timesheet_approval_path": "Supervisor",
        "time_off_template": "Time Off",
        "time_off_approver": "Supervisor",
        "work_week": "Monday to Sunday",
        "payrule_name": "Montreal - HRLY - wo premiums Temp",
        "timezone": "(UTC-5:00) Eastern Standard Time"
    },
    {
        "location_level_1": "CAN",
        "location_level_2": "Quebec",
        "location_level_3": ["MONTREAL","SHERBROOKE"],
        "activity_type": "Populated",
        "reg_temp": "Temporary",
        "job_code": "TYPE 1",
        "pay_type": "Hourly",
        "timesheet_period": "Canada - Weekly starting on Monday",
        "timesheet_template": "CAN_HRLY_MONTREAL_PROJ_Temp",
        "punch_policy": "CAN_HRLY_MONTREAL With Prem",
        "holiday_calendar": "Montreal and Sherbrooke",
        "timesheet_approval_path": "Supervisor",
        "time_off_template": "Time Off",
        "time_off_approver": "Supervisor",
        "work_week": "Monday to Sunday",
        "payrule_name": "Montreal - HRLY - premiums Temp",
        "timezone": "(UTC-5:00) Eastern Standard Time"
    },
    {
        "location_level_1": "CAN",
        "location_level_2": "Quebec",
        "location_level_3": ["LAVAL","LAVALQ","TERREBONNE","BOISBRIAND"],
        "activity_type": "Blank",
        "reg_temp": "Temporary",
        "job_code": "ALL",
        "pay_type": "Exception Hourly",
        "timesheet_period": "Canada - Weekly starting on Monday",
        "timesheet_template": "CAN_SALOT_ELIGIBLE",
        "punch_policy": None,
        "holiday_calendar": "LAVAL, BBD, TBNE",
        "timesheet_approval_path": "Supervisor - Exception time",
        "time_off_template": "Time Off",
        "time_off_approver": "Supervisor",
        "work_week": "Monday to Sunday",
        "payrule_name": "Montreal - Salaried OT Eligible",
        "timezone": "(UTC-5:00) Eastern Standard Time"
    },
    {
        "location_level_1": "CAN",
        "location_level_2": "Quebec",
        "location_level_3": ["LAVAL","LAVALQ","TERREBONNE","BOISBRIAND"],
        "activity_type": "Populated",
        "reg_temp": "Temporary",
        "job_code": "ALL",
        "pay_type": "Exception Hourly",
        "timesheet_period": "Canada - Weekly starting on Monday",
        "timesheet_template": "CAN_SALOT_ELIGIBLE_PROJ",
        "punch_policy": None,
        "holiday_calendar": "LAVAL, BBD, TBNE",
        "timesheet_approval_path": "Supervisor - Exception time",
        "time_off_template": "Time Off",
        "time_off_approver": "Supervisor",
        "work_week": "Monday to Sunday",
        "payrule_name": "Montreal - Salaried OT Eligible",
        "timezone": "(UTC-5:00) Eastern Standard Time"
    },
    {
        "location_level_1": "CAN",
        "location_level_2": "Quebec",
        "location_level_3": ["LAVAL","LAVALQ","TERREBONNE","BOISBRIAND"],
        "activity_type": "Blank",
        "reg_temp": "Temporary",
        "job_code": "ALL",
        "pay_type": "Salaried",
        "timesheet_period": "Canada - Weekly starting on Monday",
        "timesheet_template": None,
        "punch_policy": None,
        "holiday_calendar": "LAVAL, BBD, TBNE",
        "timesheet_approval_path": "Supervisor",
        "time_off_template": "Time Off",
        "time_off_approver": "Supervisor",
        "work_week": "Monday to Sunday",
        "payrule_name": "CAN_SALARIED",
        "timezone": "(UTC-5:00) Eastern Standard Time"
    },
    {
        "location_level_1": "CAN",
        "location_level_2": "Quebec",
        "location_level_3": ["LAVAL","LAVALQ","TERREBONNE","BOISBRIAND"],
        "activity_type": "Populated",
        "reg_temp": "Temporary",
        "job_code": "NA",
        "pay_type": "Salaried",
        "timesheet_period": "Canada - Weekly starting on Monday",
        "timesheet_template": "CAN_SAL_EMP_PROJ",
        "punch_policy": None,
        "holiday_calendar": "LAVAL, BBD, TBNE",
        "timesheet_approval_path": "Supervisor",
        "time_off_template": "Time Off",
        "time_off_approver": "Supervisor",
        "work_week": "Monday to Sunday",
        "payrule_name": "CAN_SALARIED",
        "timezone": "(UTC-5:00) Eastern Standard Time"
    },
    {
        "location_level_1": "CAN",
        "location_level_2": "Quebec",
        "location_level_3": ["LAVAL","LAVALQ","TERREBONNE","BOISBRIAND"],
        "activity_type": "Blank",
        "reg_temp": "Temporary",
        "job_code": "TYPE 1",
        "pay_type": "Hourly",
        "timesheet_period": "Canada - Weekly starting on Monday",
        "timesheet_template": "CAN_HRLY_MONTREAL (No project) PREM_Temp",
        "punch_policy": "CAN_HRLY_MONTREAL With Prem",
        "holiday_calendar": "LAVAL, BBD, TBNE",
        "timesheet_approval_path": "Supervisor",
        "time_off_template": "Time Off",
        "time_off_approver": "Supervisor",
        "work_week": "Monday to Sunday",
        "payrule_name": "Montreal - HRLY - premiums Temp",
        "timezone": "(UTC-5:00) Eastern Standard Time"
    },
    {
        "location_level_1": "CAN",
        "location_level_2": "Quebec",
        "location_level_3": ["LAVAL","LAVALQ","TERREBONNE","BOISBRIAND"],
        "activity_type": "Populated",
        "reg_temp": "Temporary",
        "job_code": "TYPE 1",
        "pay_type": "Hourly",
        "timesheet_period": "Canada - Weekly starting on Monday",
        "timesheet_template": "CAN_HRLY_MONTREAL_PROJ_Temp",
        "punch_policy": "CAN_HRLY_MONTREAL With Prem",
        "holiday_calendar": "LAVAL, BBD, TBNE",
        "timesheet_approval_path": "Supervisor",
        "time_off_template": "Time Off",
        "time_off_approver": "Supervisor",
        "work_week": "Monday to Sunday",
        "payrule_name": "Montreal - HRLY - premiums Temp",
        "timezone": "(UTC-5:00) Eastern Standard Time"
    },
    {
        "location_level_1": "CAN",
        "location_level_2": "Quebec",
        "location_level_3": ["LAVAL","LAVALQ","TERREBONNE","BOISBRIAND"],
        "activity_type": "Populated",
        "reg_temp": "Temporary",
        "job_code": "TYPE 2",
        "pay_type": "Hourly",
        "timesheet_period": "Canada - Weekly starting on Monday",
        "timesheet_template": "CAN_HRLY_MONTREAL_PROJ_NO PREM_Temp",
        "punch_policy": "Montreal HRLY With Proj No Prem",
        "holiday_calendar": "LAVAL, BBD, TBNE",
        "timesheet_approval_path": "Supervisor",
        "time_off_template": "Time Off",
        "time_off_approver": "Supervisor",
        "work_week": "Monday to Sunday",
        "payrule_name": "Montreal - HRLY - wo premiums Temp",
        "timezone": "(UTC-5:00) Eastern Standard Time"
    },
    {
        "location_level_1": "CAN",
        "location_level_2": "Quebec",
        "location_level_3": ["LAVAL","LAVALQ","TERREBONNE","BOISBRIAND"],
        "activity_type": "Blank",
        "reg_temp": "Temporary",
        "job_code": "TYPE 2",
        "pay_type": "Hourly",
        "timesheet_period": "Canada - Weekly starting on Monday",
        "timesheet_template": "CAN_HRLY_MONTREAL (No project)_Temp",
        "punch_policy": "CAN_HRLY_MONTREAL (No project) PP",
        "holiday_calendar": "LAVAL, BBD, TBNE",
        "timesheet_approval_path": "Supervisor",
        "time_off_template": "Time Off",
        "time_off_approver": "Supervisor",
        "work_week": "Monday to Sunday",
        "payrule_name": "Montreal - HRLY - wo premiums Temp",
        "timezone": "(UTC-5:00) Eastern Standard Time"
    }
]
