# Hungary Hun General Mapper - Extracted from Excel

MAPPER_DATA = [
  {
    "Company Code": "HU00",
    
    "FTE_PCT": "100",
    "Location": "Hungary",
    "Work Shift": "ES - No shift worker - zero premium (Hungary)",
    "Derived Employee Type": "Regulars",
    "Derived Schedule Type": "Hungary Office Schedule",
    "Schedule Policy": "Hungary Schedule Policy",
    "Timesheet Template": "Hungary Timesheet for Regulars",
    "Timesheet Approval": "Supervisor for OT",
    "Timesheet Period": "HUN_Weekly End of Month",
    "Time Off Template": "Hungary Time Off",
    "Time Off Approval": "Supervisor",
    "Payrule": "HUN_Regular_Payrule",
    "Time Off Types": "Refer to Leave Assignment",
    "Time Zone": "(UTC+1:00) Central Europe Standard Time",
    "Work Week": "Monday to Sunday",
    "Holiday Calendar": "[HUN] Holiday Calendar",
    "Authentication Type": "SSO",
    "Activities": "Refer to ES Activity List sheet",
    "Time Entry Approval Path": "System",
    "Punch Entry Policy": "Hungary - Regulars Punch Policy"
  },
  {
    "Company Code": "HU00",
    "FTE_PCT": "100",
    "Location": "Hungary",
    "Work Shift": "ES - Continuous Shift (Hungary)",
    "Derived Employee Type": "Shifters",
    "Derived Schedule Type": "Shift Schedule",
    "Schedule Policy": "Hungary Schedule Policy",
    "Timesheet Template": "Hungary Timesheet for Shifters",
    "Timesheet Approval": "Supervisor for OT",
    "Timesheet Period": "HUN_Weekly End of Month",
    "Time Off Template": "Hungary Time Off",
    "Time Off Approval": "Supervisor",
    "Payrule": "HUN_Shifter_Payrule",
    "Time Off Types": "Refer to Leave Assignment",
    "Time Zone": "(UTC+1:00) Central Europe Standard Time",
    "Work Week": "Monday to Sunday",
    "Holiday Calendar": "[HUN] Holiday Calendar",
    "Authentication Type": "SSO",
    "Activities": "Refer to ES Activity List sheet",
    "Time Entry Approval Path": "System",
    "Punch Entry Policy": "Hungary - Shift Punch Policy"
  },
  {
    "Company Code": "HU00",
    "FTE_PCT": "<100",
    "Location": "Hungary",
    "Work Shift": "ES - No shift worker - zero premium (Hungary)",
    "Derived Employee Type": "Part-time Regulars",
    "Derived Schedule Type": "Shift Schedule",
    "Schedule Policy": "Hungary Schedule Policy",
    "Timesheet Template": "Hungary Timesheet for Part-time Regulars",
    "Timesheet Approval": "Supervisor for OT",
    "Timesheet Period": "HUN_Weekly End of Month",
    "Time Off Template": "Hungary Time Off",
    "Time Off Approval": "Supervisor",
    "Payrule": "HUN_Part-time Regular_Payrule",
    "Time Off Types": "Refer to Leave Assignment",
    "Time Zone": "(UTC+1:00) Central Europe Standard Time",
    "Work Week": "Monday to Sunday",
    "Holiday Calendar": "[HUN] Holiday Calendar",
    "Authentication Type": "SSO",
    "Activities": "Refer to ES Activity List sheet",
    "Time Entry Approval Path": "System",
    "Punch Entry Policy": "Hungary -  Part-time Regulars Punch Policy"
  },
  {
    "Company Code": "HU00",
    "FTE_PCT": "<100",
    "Location": "Hungary",
    "Work Shift": "ES - Continuous Shift (Hungary)",
    "Derived Employee Type": "Part-time Shifters",
    "Derived Schedule Type": "Shift Schedule",
    "Schedule Policy": "Hungary Schedule Policy",
    "Timesheet Template": "Hungary Timesheet for Shifters",
    "Timesheet Approval": "Supervisor for OT",
    "Timesheet Period": "HUN_Weekly End of Month",
    "Time Off Template": "Hungary Time Off",
    "Time Off Approval": "Supervisor",
    "Payrule": "HUN_Shifter_Payrule",
    "Time Off Types": "Refer to Leave Assignment",
    "Time Zone": "(UTC+1:00) Central Europe Standard Time",
    "Work Week": "Monday to Sunday",
    "Holiday Calendar": "[HUN] Holiday Calendar",
    "Authentication Type": "SSO",
    "Activities": "Refer to ES Activity List sheet",
    "Time Entry Approval Path": "System",
    "Punch Entry Policy": "Hungary - Shift Punch Policy"
  }
]
