from dxctechnology.workday_user_import_v1.user_import.config import *
from dxctechnology.workday_user_import_v1.user_import.mappers.master_mapper import MAPPER

instance = "sandbox"

version = "v1"

environment = "pre-production"
can_run_batch_task_var_name_portugal = f"dxctechnology_workday_user_import_portugal_can_run_batch_task_variable_{instance}"

company_key = "dxcsandbox"
replicon_conn_id = "replicon_dxcsandbox_x.workday_4"
sftp_conn_id = "sftp_dxcsandbox_628172_Workday"

DXC_WORKDAY_USER_SYNC_USER_MAPPER = MAPPER

portugal_add_user_timeoff_assignment_dag_id = f"dxctechnology_workday_user_import_process_portugal_add_user_timeoff_child_dag_{instance}_{version}"
portugal_update_user_timeoff_assignment_dag_id = f"dxctechnology_workday_user_import_process_portugal_update_user_timeoff_child_dag_{instance}_{version}"
portugal_add_user_dag_id = f"dxctechnology_workday_user_import_process_portugal_add_user_child_dag_{instance}_{version}"
portugal_update_user_dag_id = f"dxctechnology_workday_user_import_process_portugal_update_user_child_dag_{instance}_{version}"
workday_user_import_process_portugal_users_child_dag = f"dxctechnology_workday_user_import_process_portugal_process_user_child_dag_{instance}_{version}"
workday_user_import_portugal_users_update_user_rehire_timeoff_process_child_dag = f"dxctechnology_workday_user_import_portugal_users_update_user_rehire_timeoff_assignment_process_child_{instance}_{version}"
process_time_off_accrual = f"dxctechnology_workday_user_sync_timeoff_assignment_policy_update_for_no_accrual_child_{instance}_{version}"
workday_user_import_global_users_update_user_timeoff_process_child_dag_disable = f"dxctechnology_workday_user_import_global_users_update_user_timeoff_process_child_for_disable_user_{instance}_{version}"

# USA LES
usa_les_process_users_child_dag_id = f"dxctechnology_workday_user_import_usa_les_process_users_child_{instance}_{version}"
usa_lse_add_user_dag_id = f"dxctechnology_workday_user_import_process_usa_les_add_user_child_dag_{instance}_{version}"
usa_lse_update_user_dag_id = f"dxctechnology_workday_user_import_process_usa_les_update_user_child_dag_{instance}_{version}"
usa_lse_update_user_timeoff_assignment_dag_id = f"dxctechnology_workday_user_import_process_usa_les_update_user_timeoff_child_dag_{instance}_{version}"
usa_lse_add_user_timeoff_assignment_dag_id = f"dxctechnology_workday_user_import_process_usa_les_add_user_timeoff_child_dag_{instance}_{version}"
usa_les_us_sick_leave_california_user_timeoff_assignment_dag_id = f"dxctechnology_workday_user_import_usa_les_us_sick_leave_timeoff_assignment_california_{instance}_{version}"
usa_les_us_sick_leave_non_california_user_timeoff_assignment_dag_id = f"dxctechnology_workday_user_import_usa_les_us_sick_leave_timeoff_assignment_non_california_{instance}_{version}"
usa_les_us_holiday_user_timeoff_assignment_dag_id = f"dxctechnology_workday_user_import_usa_les_us_holiday_timeoff_assignment_{instance}_{version}"
workday_user_import_usa_les_users_update_user_rehire_timeoff_process_child_dag =f"dxctechnology_workday_user_import_process_usa_les_rehire_user_timeoff_assignment_child_{instance}_{version}"

# COSTA RICA
costa_rica_process_users_child_dag_id = f"dxctechnology_workday_user_import_costa_rica_process_users_child_{instance}_{version}"
costa_rica_add_user_dag_id = f"dxctechnology_workday_user_import_costa_rica_process_add_user_child_{instance}_{version}"
costa_rica_add_user_timeoff_assignment_dag_id = f"dxctechnology_workday_user_import_costa_rica_process_add_user_timeoff_assignment_child_{instance}_{version}"
costa_rica_update_user_dag_id = f"dxctechnology_workday_user_import_costa_rica_process_update_user_child_dag_{instance}_{version}"
costa_rica_update_user_timeoff_assignment_dag_id = f"dxctechnology_workday_user_import_costa_rica_process_update_user_timeoff_assignment_child_{instance}_{version}"
costa_rica_rehire_user_timeoff_assignment_dag_id =f"dxctechnology_workday_user_import_costa_rica_process_rehire_user_timeoff_assignment_child_{instance}_{version}"
# from global-dag
costa_rica_process_time_off_no_accrual_dag_id = f"dxctechnology_workday_user_sync_timeoff_assignment_policy_update_for_no_accrual_child_{instance}_{version}"

# INDIA
india_process_users_child_dag_id = f"dxctechnology_workday_user_import_india_process_users_child_{instance}_{version}"
india_add_user_dag_id = f"dxctechnology_workday_user_import_india_process_add_user_child_{instance}_{version}"
india_add_user_timeoff_assignment_dag_id = f"dxctechnology_workday_user_import_india_process_add_user_timeoff_assignment_child_{instance}_{version}"
india_update_user_dag_id = f"dxctechnology_workday_user_import_india_process_update_user_child_dag_{instance}_{version}"
india_update_user_timeoff_assignment_dag_id = f"dxctechnology_workday_user_import_india_process_update_user_timeoff_assignment_child_{instance}_{version}"
india_rehire_user_timeoff_assignment_dag_id =f"dxctechnology_workday_user_import_india_process_rehire_user_timeoff_assignment_child_{instance}_{version}"

india_timeoff_assignment_ind_sick_casual_dag_id = f"dxctechnology_workday_user_import_india_process_sick_casual_timeoff_assignment_child_{instance}_{version}"
india_update_user_ia_0_timeoff_assignment_dag_id = f"dxctechnology_workday_user_import_india_process_ia_0_timeoff_assignment_child_{instance}_{version}"
india_update_user_ia_1_timeoff_assignment_dag_id = f"dxctechnology_workday_user_import_india_process_ia_1_timeoff_assignment_child_{instance}_{version}"

india_process_time_off_no_accrual_dag_id= f"dxctechnology_workday_user_sync_timeoff_assignment_policy_update_for_no_accrual_child_{instance}_{version}"

workday_user_import_ia_zero_timeoff_assignment_child_dag = f"dxctechnology_workday_user_import_ia_zero_timeoff_assignment_child_{instance}_{version}"
workday_user_import_ia_one_timeoff_assignment_child_dag = f"dxctechnology_workday_user_import_ia_one_timeoff_assignment_child_{instance}_{version}"

# Cleanup child DAG ID for disabled users
delete_future_entries_child_dag_id = f"dxctechnology_workday_user_sync_delete_future_entries_child_{instance}_v2"

# Overrides: bump max_active_runs to 10 for this environment (base defaults in config.py are unchanged, so production is not affected)
global_add_user_max_active_runs = 10
process_users_max_active_runs = 10
