timeoff_codes = {
	"[FRA] A - CET (UES Capgemini)": "CET",
	"[FRA] A - Congé payé d'ancienneté 2023 (UES Capgemini)": "CA9",
	"[FRA] A - Congé payé d'ancienneté 2024 (UES Capgemini)": "CA9",
	"[FRA] A - Congé payé d'ancienneté 2025 (UES Capgemini)": "CA9",
	"[FRA] A - Congé payé d'ancienneté 2026 (UES Capgemini)": "CA9",
	"[FRA] A - Congé payé d'ancienneté 2027 (UES Capgemini)": "CA9",
	"[FRA] A - Congé payé d'ancienneté 2028 (UES Capgemini)": "CA9",
	"[FRA] A - Congé payé d'ancienneté 2029 (UES Capgemini)": "CA9",
	"[FRA] A - Congé payé d'ancienneté 2030 (UES Capgemini)": "CA9",
	"[FRA] A - Congés payés 2023 (UES Capgemini)": "CL9",
	"[FRA] A - Congés payés 2024 (UES Capgemini)": "CL9",
	"[FRA] A - Congés payés 2025 (UES Capgemini)": "CL9",
	"[FRA] A - Congés payés 2026 (UES Capgemini)": "CL9",
	"[FRA] A - Congés payés 2027 (UES Capgemini)": "CL9",
	"[FRA] A - Congés payés 2028 (UES Capgemini)": "CL9",
	"[FRA] A - Congés payés 2029 (UES Capgemini)": "CL9",
	"[FRA] A - Congés payés 2030 (UES Capgemini)": "CL9",
	"[FRA] A - Récupération intervention astreinte (UES Capgemini)": "ASH",
	"[FRA] A - Récupération jour ou demi-journée avec compteur (UES Capgemini)": "ASH",
	"[FRA] A - Récupération TEA (UES Capgemini)": "TEC",
	"[FRA] A - Repos de nuit (UES Capgemini)": "REP",
	"[FRA] A - RTT Employeur (UES Capgemini)": "RTE",
	"[FRA] A - RTT Employeur 2025 (UES Capgemini)": "RTE",
	"[FRA] A - RTT Employeur 2026 (UES Capgemini)": "RTE",
	"[FRA] A - RTT Employeur 2027 (UES Capgemini)": "RTE",
	"[FRA] A - RTT Employeur 2028 (UES Capgemini)": "RTE",
	"[FRA] A - RTT Employeur 2029 (UES Capgemini)": "RTE",
	"[FRA] A - RTT Employeur 2030 (UES Capgemini)": "RTE",
	"[FRA] A - RTT Salarié (UES Capgemini)": "RTS",
	"[FRA] A - RTT Salarié 2025 (UES Capgemini)": "RTS",
	"[FRA] A - RTT Salarié 2026 (UES Capgemini)": "RTS",
	"[FRA] A - RTT Salarié 2027 (UES Capgemini)": "RTS",
	"[FRA] A - RTT Salarié 2028 (UES Capgemini)": "RTS",
	"[FRA] A - RTT Salarié 2029 (UES Capgemini)": "RTS",
	"[FRA] A - RTT Salarié 2030 (UES Capgemini)": "RTS",
	"[FRA] B - Congé décès (UES Altran)": "DEC",
	"[FRA] B - Congé décès (UES Capgemini)": "DEC",
	"[FRA] B - Congé déménagement (UES Capgemini)": "DEM",
	"[FRA] B - Congé enfant hospitalisé (UES Capgemini)": "ENH",
	"[FRA] B - Congé enfant malade (UES Capgemini)": "MEN",
	"[FRA] B - Congé mariage enfant": "MAR",
	"[FRA] B - Congé mariage/PACS salarié": "MAR",
	"[FRA] B - Congé naissance": "NAI",
	"[FRA] D - Absence Autorisée Payée": "ABR",
	"[FRA] D - Absence Non Autorisée Non Payée": "ANA",
	"[FRA] D - Absence non payée": "ANR",
	"[FRA] D - Congé catastrophe naturelle": "ANR",
	"[FRA] D - Congé enseignement et recherche": "ANR",
	"[FRA] D - Congé mandat parlementaire ou local": "AEL",
	"[FRA] D - Congé naturalisation française": "ANR",
	"[FRA] D - Congé participation formation professionnelle ou jury d'examen": "ABR",
	"[FRA] D - Congé proche aidant": "CPA",
	"[FRA] D - Congé recherche d'emploi": "ARE",
	"[FRA] D - Congé sans solde < 1 mois": "ANR",
	"[FRA] D - Congé solidarité familiale": "CSF",
	"[FRA] D - Congé tps partiel scolaire annualisé": "TPS",
	"[FRA] D - Congé transition professionnelle 1": "CIF",
	"[FRA] D - Congé transition professionnelle hors 1ère année": "CI2",
	"[FRA] D - Don de jours": "DJO",
	"[FRA] D - Formation animateurs/ associatifs/ mandats mutualistes et membres conseils de citoyens": "ANR",
	"[FRA] D - Formation école alternant": "CFA",
	"[FRA] D - Formation économique et sociale": "CFE",
	"[FRA] D - Grève": "GRV",
	"[FRA] D - Juré d'assises": "JUR",
	"[FRA] D - Mise à pied disciplinaire": "MAP",
	"[FRA] D - Préavis non effectué payé": "PNE",
	"[FRA] D - Réserve et service national": "PMR",
	"[FRA] H - Absence autorisée spécifique 8 jrs annuels (UES Capgemini)": "AAH",
	"[FRA] S - Congé création d'entreprise": "CCE",
	"[FRA] S - Congé mobilité sécurisée": "MOS",
	"[FRA] S - Congé parental d'éducation": "CP2",
	"[FRA] S - Congé présence parentale": "CPP",
	"[FRA] S - Congé respiration": "CRN",
	"[FRA] S - Congé sabbatique": "SAB",
	"[FRA] S - Congé sans solde > 1 mois": "CSS",
	"[FRA] S - Congé suspension autre": "CAU",
	"[FRA] S - Congé suspension expatriation": "EXP",
	"[FRA] S - Formation non payée": "FNP",
	"[FRA] A - CET (UES Altran)": "CE1",
	"[FRA] A - Congé payé d'ancienneté 2024 (UES Altran)": "CA6",
	"[FRA] A - Congé payé d'ancienneté 2025 (UES Altran)": "CA6",
	"[FRA] A - Congé payé d'ancienneté 2026 (UES Altran)": "CA6",
	"[FRA] A - Congé payé d'ancienneté 2027 (UES Altran)": "CA6",
	"[FRA] A - Congé payé d'ancienneté 2028 (UES Altran)": "CA6",
	"[FRA] A - Congé payé d'ancienneté 2029 (UES Altran)": "CA6",
	"[FRA] A - Congé payé d'ancienneté 2030 (UES Altran)": "CA6",
	"[FRA] A - Congés payés 2024 (UES Altran)": "CL6",
	"[FRA] A - Congés payés 2025 (UES Altran)": "CL6",
	"[FRA] A - Congés payés 2026 (UES Altran)": "CL6",
	"[FRA] A - Congés payés 2027 (UES Altran)": "CL6",
	"[FRA] A - Congés payés 2028 (UES Altran)": "CL6",
	"[FRA] A - Congés payés 2029 (UES Altran)": "CL6",
	"[FRA] A - Congés payés 2030 (UES Altran)": "CL6",
	"[FRA] A - RTT Employeur 2024 (UES Altran)": "RE6",
	"[FRA] A - RTT Employeur 2025 (UES Altran)": "RE6",
	"[FRA] A - RTT Employeur 2026 (UES Altran)": "RE6",
	"[FRA] A - RTT Employeur 2027 (UES Altran)": "RE6",
	"[FRA] A - RTT Employeur 2028 (UES Altran)": "RE6",
	"[FRA] A - RTT Employeur 2029 (UES Altran)": "RE6",
	"[FRA] A - RTT Employeur 2030 (UES Altran)": "RE6",
	"[FRA] A - RTT Salarié 2024 (UES Altran)": "RS6",
	"[FRA] A - RTT Salarié 2025 (UES Altran)": "RS6",
	"[FRA] A - RTT Salarié 2026 (UES Altran)": "RS6",
	"[FRA] A - RTT Salarié 2027 (UES Altran)": "RS6",
	"[FRA] A - RTT Salarié 2028 (UES Altran)": "RS6",
	"[FRA] A - RTT Salarié 2029 (UES Altran)": "RS6",
	"[FRA] A - RTT Salarié 2030 (UES Altran)": "RS6",
	"[FRA] A - Repos Compensateur Récupération avec compteur (UES Altran)": "RCR",
	"[FRA] A - Récupération jour ou demi-journée sans compteur (UES Altran)": "RE1",
	"[FRA] A - Repos Compensateur Nuit (UES Altran)": "RCN",
	"[FRA] A - JNT Employeur 2024 (UES Altran)": "JE6",
	"[FRA] A - JNT Employeur 2025 (UES Altran)": "JE6",
	"[FRA] A - JNT Employeur 2026 (UES Altran)": "JE6",
	"[FRA] A - JNT Employeur 2027 (UES Altran)": "JE6",
	"[FRA] A - JNT Employeur 2028 (UES Altran)": "JE6",
	"[FRA] A - JNT Employeur 2029 (UES Altran)": "JE6",
	"[FRA] A - JNT Employeur 2030 (UES Altran)": "JE6",
	"[FRA] A - JNT Salarié 2024 (UES Altran)": "JS6",
	"[FRA] A - JNT Salarié 2025 (UES Altran)": "JS6",
	"[FRA] A - JNT Salarié 2026 (UES Altran)": "JS6",
	"[FRA] A - JNT Salarié 2027 (UES Altran)": "JS6",
	"[FRA] A - JNT Salarié 2028 (UES Altran)": "JS6",
	"[FRA] A - JNT Salarié 2029 (UES Altran)": "JS6",
	"[FRA] A - JNT Salarié 2030 (UES Altran)": "JS6",
	"[FRA] B - Congé enfant hospitalisé (UES Altran)": "ENH",
	"[FRA] B - Congé enfant malade (UES Altran)": "MEN",
	"[FRA] B - Congé déménagement pour mobilité professionnel (UES Altran)": "DEM",
	"[FRA] D - Formation journée examen alternant": "CFA",
	"[FRA] H - Congé spécifique ponctuel enfant (UES Altran)": "AHE",
	"[FRA] H - Congés spécifiques enfants (UES Altran)": "CPE",
	"[FRA] H - Congé de solidarité familiale (UES Altran)": "SCS",
	"[FRA] H - Démarches administratives (UES Altran)": "ADA",
	"[FRA] H - Congé spécifique autorisé (UES Altran)": "AEH",
	"[FRA] H - Congés spécifiques enfants 3 jrs annuels (UES Capgemini)": "CEH",
	"[FRA] H - Absences pour démarche confidentielle liée à un accord (UES Capgemini)": "ADC",
	"[FRA] D - Congé présence parentale perlé": "CPP",
	"[FRA] A - Congés payés report Maladie 2025": "CPR",
	"[FRA] A - Congés payés report Maladie 2026": "CPR",
	"[FRA] A - Congés payés report Maladie 2027": "CPR",
	"[FRA] A - Congés payés report Maladie 2028": "CPR",
	"[FRA] A - Congés payés report Maladie 2029": "CPR",
	"[FRA] A - Congés payés report Maladie 2030": "CPR",
	"[FRA] A - CET ex-Nokia": "CE8",
	"[FRA] D - Congé tutelle (UES Capgemini)": "ABR",
	"[FRA] H - Absence autorisée spécifique 6 jrs (UES Capgemini)": "AAX",
	"[FRA] D - Congé tps partiel senior cumulé": "SNC",
	"[FRA] S - Mobilité": "CMO",
	"[FRA] S - Mobilité PAEC": "CMA",
	"[FRA] S - Suspension Mobilité PAEC": "CMS"
}
