<?xml version="1.0" encoding="utf-8"?>
<xs:schema attributeFormDefault="unqualified" targetNamespace="http://csc.com/IF9005/FromGSAPToReplicon/CostCenter" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="MT_CostCenter_Replicon">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Records" minOccurs="0" maxOccurs="unbounded">
            <xs:complexType>
                <xs:sequence>
                    <xs:element name="Cost_Center_Name" type="xs:string" />
                    <xs:element name="Cost_Center_Name_parent" type="xs:string" />
                </xs:sequence>
            </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>