CANADA_USER_MAPPER = [
    {
        "country": "Canada",
        "location": "Ontario",
        "worker_type": "Employee",
        "compensation_grade": "Salary",
        "contract_type": "Full_time",
        "employee_type": [
            "Regular",
            "Fixed Term",
            "Partner",
            "Intern",
            "Non-Salaried / Self-Employed",
            "Non-Salaried / Self-Employed (Fixed Term)"
        ],
        "job_category": [
            "Functional",
            "Client Services"
        ],
        "management_level": [
            "CEO",
            "Partner",
            "Executive Vice President",
            "Senior Vice President",
            "Vice President",
            "Director",
            "Senior Manager",
            "Manager",
            "Senior Associate",
            "Specialist",
            "Specialist 2",
            "Associate",
            "Trainee/Apprentice",
            "Administrative",
            "Administrative 2"
        ],
        "additional_job_classification": "CA_Policy_A",
        "company_code": "NA",
        "schedule_type": "Office Schedule (Assigned to user via another automation)",
        "work_week": "Sunday to Saturday",
        "timesheet_template": "Canada TSD Agile Salaried OT",
        "time_entry_approval_path": "Automatic Approval",
        "timesheet_approval": "Supervisor",
        "timesheet_period": "Weekly starting on Sunday",
        "time_off_template": "Time Off",
        "time_off_approval": "System",
        "time_off_types": [
            "CAN_TOIL",
            "Holiday",
            "Leave of Absence"
        ],
        "payrule": "Ontario_FT_SAL_PolicyA",
        "time_zone": "(UTC-4:00) Atlantic Standard Time",
        "holiday_calendar": "Canada Ontario Holiday Calendar",
        "authentication_type": "SSO"
    },
    {
        "country": "Canada",
        "location": "Ontario",
        "worker_type": "Employee",
        "compensation_grade": "Salary",
        "contract_type": "Part_time",
        "employee_type": [
            "Regular",
            "Fixed Term",
            "Partner",
            "Intern",
            "Non-Salaried / Self-Employed",
            "Non-Salaried / Self-Employed (Fixed Term)"
        ],
        "job_category": [
            "Functional",
            "Client Services"
        ],
        "management_level": [
            "CEO",
            "Partner",
            "Executive Vice President",
            "Senior Vice President",
            "Vice President",
            "Director",
            "Senior Manager",
            "Manager",
            "Senior Associate",
            "Specialist",
            "Specialist 2",
            "Associate",
            "Trainee/Apprentice",
            "Administrative",
            "Administrative 2"
        ],
        "additional_job_classification": "CA_Policy_A",
        "company_code": "NA",
        "schedule_type": "Office Schedule (Assigned to user via another automation)",
        "work_week": "Sunday to Saturday",
        "timesheet_template": "Canada TSD Agile Salaried OT",
        "time_entry_approval_path": "Automatic Approval",
        "timesheet_approval": "Supervisor",
        "timesheet_period": "Weekly starting on Sunday",
        "time_off_template": "Time Off",
        "time_off_approval": "System",
        "time_off_types": [
            "CAN_TOIL",
            "Holiday",
            "Leave of Absence"
        ],
        "payrule": "Ontario_PT_SAL_PolicyA",
        "time_zone": "(UTC-4:00) Atlantic Standard Time",
        "holiday_calendar": "Canada Ontario Holiday Calendar",
        "authentication_type": "SSO"
    },
    {
        "country": "Canada",
        "location": "Ontario",
        "worker_type": "Employee",
        "compensation_grade": "Hourly",
        "contract_type": [
            "Full_time",
            "Part_time"
        ],
        "employee_type": [
            "Regular",
            "Fixed Term",
            "Partner",
            "Intern",
            "Non-Salaried / Self-Employed",
            "Non-Salaried / Self-Employed (Fixed Term)"
        ],
        "job_category": [
            "Functional",
            "Client Services"
        ],
        "management_level": [
            "CEO",
            "Partner",
            "Executive Vice President",
            "Senior Vice President",
            "Vice President",
            "Director",
            "Senior Manager",
            "Manager",
            "Senior Associate",
            "Specialist",
            "Specialist 2",
            "Associate",
            "Trainee/Apprentice",
            "Administrative",
            "Administrative 2"
        ],
        "additional_job_classification": "CA_Policy_A",
        "company_code": "NA",
        "schedule_type": "Office Schedule (Assigned to user via another automation)",
        "work_week": "Sunday to Saturday",
        "timesheet_template": "Canada TSD Agile Salaried OT",
        "time_entry_approval_path": "Automatic Approval",
        "timesheet_approval": "Hourly/Cont TS Approval Path",
        "timesheet_period": "Weekly starting on Sunday",
        "time_off_template": "Time Off",
        "time_off_approval": "Hourly TO Approval Path",
        "time_off_types": [
            "Holiday",
            "Leave of Absence"
        ],
        "payrule": "Ontario_Hourly_PolicyA",
        "time_zone": "(UTC-4:00) Atlantic Standard Time",
        "holiday_calendar": "Canada Ontario Holiday Calendar",
        "authentication_type": "SSO"
    },
    {
        "country": "Canada",
        "location": "Ontario",
        "worker_type": "Employee",
        "compensation_grade": "Salary",
        "contract_type": "Full_time",
        "employee_type": [
            "Regular",
            "Fixed Term",
            "Partner",
            "Intern",
            "Non-Salaried / Self-Employed",
            "Non-Salaried / Self-Employed (Fixed Term)"
        ],
        "job_category": [
            "Functional",
            "Client Services"
        ],
        "management_level": [
            "CEO",
            "Partner",
            "Executive Vice President",
            "Senior Vice President",
            "Vice President",
            "Director",
            "Senior Manager",
            "Manager",
            "Senior Associate",
            "Specialist",
            "Specialist 2",
            "Associate",
            "Trainee/Apprentice",
            "Administrative",
            "Administrative 2"
        ],
        "additional_job_classification": "CA_Policy_B",
        "company_code": "NA",
        "schedule_type": "Office Schedule (Assigned to user via another automation)",
        "work_week": "Sunday to Saturday",
        "timesheet_template": "Canada TSD Agile Salaried OT",
        "time_entry_approval_path": "Automatic Approval",
        "timesheet_approval": "Supervisor",
        "timesheet_period": "Weekly starting on Sunday",
        "time_off_template": "Time Off",
        "time_off_approval": "System",
        "time_off_types": [
            "CAN_TOIL",
            "Holiday",
            "Leave of Absence"
        ],
        "payrule": "Ontario_FT_SAL_PolicyB",
        "time_zone": "(UTC-4:00) Atlantic Standard Time",
        "holiday_calendar": "Canada Ontario Holiday Calendar",
        "authentication_type": "SSO"
    },
    {
        "country": "Canada",
        "location": "Ontario",
        "worker_type": "Employee",
        "compensation_grade": "Salary",
        "contract_type": "Part_time",
        "employee_type": [
            "Regular",
            "Fixed Term",
            "Partner",
            "Intern",
            "Non-Salaried / Self-Employed",
            "Non-Salaried / Self-Employed (Fixed Term)"
        ],
        "job_category": [
            "Functional",
            "Client Services"
        ],
        "management_level": [
            "CEO",
            "Partner",
            "Executive Vice President",
            "Senior Vice President",
            "Vice President",
            "Director",
            "Senior Manager",
            "Manager",
            "Senior Associate",
            "Specialist",
            "Specialist 2",
            "Associate",
            "Trainee/Apprentice",
            "Administrative",
            "Administrative 2"
        ],
        "additional_job_classification": "CA_Policy_B",
        "company_code": "NA",
        "schedule_type": "Office Schedule (Assigned to user via another automation)",
        "work_week": "Sunday to Saturday",
        "timesheet_template": "Canada TSD Agile Salaried OT",
        "time_entry_approval_path": "Automatic Approval",
        "timesheet_approval": "Supervisor",
        "timesheet_period": "Weekly starting on Sunday",
        "time_off_template": "Time Off",
        "time_off_approval": "System",
        "time_off_types": [
            "CAN_TOIL",
            "Holiday",
            "Leave of Absence"
        ],
        "payrule": "Ontario_PT_SAL_PolicyB",
        "time_zone": "(UTC-4:00) Atlantic Standard Time",
        "holiday_calendar": "Canada Ontario Holiday Calendar",
        "authentication_type": "SSO"
    },
    {
        "country": "Canada",
        "location": "Ontario",
        "worker_type": "Employee",
        "compensation_grade": "Hourly",
        "contract_type": [
            "Full_time",
            "Part_time"
        ],
        "employee_type": [
            "Regular",
            "Fixed Term",
            "Partner",
            "Intern",
            "Non-Salaried / Self-Employed",
            "Non-Salaried / Self-Employed (Fixed Term)"
        ],
        "job_category": [
            "Functional",
            "Client Services"
        ],
        "management_level": [
            "CEO",
            "Partner",
            "Executive Vice President",
            "Senior Vice President",
            "Vice President",
            "Director",
            "Senior Manager",
            "Manager",
            "Senior Associate",
            "Specialist",
            "Specialist 2",
            "Associate",
            "Trainee/Apprentice",
            "Administrative",
            "Administrative 2"
        ],
        "additional_job_classification": "CA_Policy_B",
        "company_code": "NA",
        "schedule_type": "Office Schedule (Assigned to user via another automation)",
        "work_week": "Sunday to Saturday",
        "timesheet_template": "Canada TSD Agile Hourly OT/NON-OT",
        "time_entry_approval_path": "Automatic Approval",
        "timesheet_approval": "Hourly/Cont TS Approval Path",
        "timesheet_period": "Weekly starting on Sunday",
        "time_off_template": "Time Off",
        "time_off_approval": "Hourly TO Approval Path",
        "time_off_types": [
            "Holiday",
            "Leave of Absence"
        ],
        "payrule": "Ontario_Hourly_PolicyB",
        "time_zone": "(UTC-4:00) Atlantic Standard Time",
        "holiday_calendar": "Canada Ontario Holiday Calendar",
        "authentication_type": "SSO"
    },
    {
        "country": "Canada",
        "location": "Ontario",
        "worker_type": "Employee",
        "compensation_grade": "Salary",
        "contract_type": [
            "Full_time",
            "Part_time"
        ],
        "employee_type": [
            "Regular",
            "Fixed Term",
            "Partner",
            "Intern",
            "Non-Salaried / Self-Employed",
            "Non-Salaried / Self-Employed (Fixed Term)"
        ],
        "job_category": [
            "Functional",
            "Client Services"
        ],
        "management_level": [
            "CEO",
            "Partner",
            "Executive Vice President",
            "Senior Vice President",
            "Vice President",
            "Director",
            "Senior Manager",
            "Manager",
            "Senior Associate",
            "Specialist",
            "Specialist 2",
            "Associate",
            "Trainee/Apprentice",
            "Administrative",
            "Administrative 2"
        ],
        "additional_job_classification": "NA",
        "company_code": "NA",
        "schedule_type": "Office Schedule (Assigned to user via another automation)",
        "work_week": "Sunday to Saturday",
        "timesheet_template": "Canada TSD Agile Salaried NON-OT",
        "time_entry_approval_path": "Automatic Approval",
        "timesheet_approval": "Supervisor",
        "timesheet_period": "Weekly starting on Sunday",
        "time_off_template": "Time Off",
        "time_off_approval": "System",
        "time_off_types": [
            "CAN_TOIL",
            "Holiday",
            "Leave of Absence"
        ],
        "payrule": "Ontario_SAL_NO_AJC",
        "time_zone": "(UTC-4:00) Atlantic Standard Time",
        "holiday_calendar": "Canada Ontario Holiday Calendar",
        "authentication_type": "SSO"
    },
    {
        "country": "Canada",
        "location": "Ontario",
        "worker_type": "Employee",
        "compensation_grade": "Hourly",
        "contract_type": [
            "Full_time",
            "Part_time"
        ],
        "employee_type": [
            "Regular",
            "Fixed Term",
            "Partner",
            "Intern",
            "Non-Salaried / Self-Employed",
            "Non-Salaried / Self-Employed (Fixed Term)"
        ],
        "job_category": [
            "Functional",
            "Client Services"
        ],
        "management_level": [
            "CEO",
            "Partner",
            "Executive Vice President",
            "Senior Vice President",
            "Vice President",
            "Director",
            "Senior Manager",
            "Manager",
            "Senior Associate",
            "Specialist",
            "Specialist 2",
            "Associate",
            "Trainee/Apprentice",
            "Administrative",
            "Administrative 2"
        ],
        "additional_job_classification": "NA",
        "company_code": "NA",
        "schedule_type": "Office Schedule (Assigned to user via another automation)",
        "work_week": "Sunday to Saturday",
        "timesheet_template": "Canada TSD Agile Salaried OT",
        "time_entry_approval_path": "Automatic Approval",
        "timesheet_approval": "Hourly/Cont TS Approval Path",
        "timesheet_period": "Weekly starting on Sunday",
        "time_off_template": "Time Off",
        "time_off_approval": "Hourly TO Approval Path",
        "time_off_types": [
            "Holiday",
            "Leave of Absence"
        ],
        "payrule": "Ontario_Hourly_NO_AJC",
        "time_zone": "(UTC-4:00) Atlantic Standard Time",
        "holiday_calendar": "Canada Ontario Holiday Calendar",
        "authentication_type": "SSO"
    },
    {
        "country": "Canada",
        "location": "British Columbia",
        "worker_type": "Employee",
        "compensation_grade": "Salary",
        "contract_type": "Full_time",
        "employee_type": [
            "Regular",
            "Fixed Term",
            "Partner",
            "Intern",
            "Non-Salaried / Self-Employed",
            "Non-Salaried / Self-Employed (Fixed Term)"
        ],
        "job_category": [
            "Functional",
            "Client Services"
        ],
        "management_level": [
            "CEO",
            "Partner",
            "Executive Vice President",
            "Senior Vice President",
            "Vice President",
            "Director",
            "Senior Manager",
            "Manager",
            "Senior Associate",
            "Specialist",
            "Specialist 2",
            "Associate",
            "Trainee/Apprentice",
            "Administrative",
            "Administrative 2"
        ],
        "additional_job_classification": "CA_Policy_A",
        "company_code": "NA",
        "schedule_type": "Office Schedule (Assigned to user via another automation)",
        "work_week": "Sunday to Saturday",
        "timesheet_template": "Canada TSD Agile Salaried OT",
        "time_entry_approval_path": "Automatic Approval",
        "timesheet_approval": "Supervisor",
        "timesheet_period": "Weekly starting on Sunday",
        "time_off_template": "Time Off",
        "time_off_approval": "System",
        "time_off_types": [
            "CAN_TOIL",
            "Holiday",
            "Leave of Absence"
        ],
        "payrule": "BC_FT_SAL_PolicyA",
        "time_zone": "(UTC-4:00) Atlantic Standard Time",
        "holiday_calendar": "Canada BC Holiday Calendar",
        "authentication_type": "SSO"
    },
    {
        "country": "Canada",
        "location": "British Columbia",
        "worker_type": "Employee",
        "compensation_grade": "Salary",
        "contract_type": "Part_time",
        "employee_type": [
            "Regular",
            "Fixed Term",
            "Partner",
            "Intern",
            "Non-Salaried / Self-Employed",
            "Non-Salaried / Self-Employed (Fixed Term)"
        ],
        "job_category": [
            "Functional",
            "Client Services"
        ],
        "management_level": [
            "CEO",
            "Partner",
            "Executive Vice President",
            "Senior Vice President",
            "Vice President",
            "Director",
            "Senior Manager",
            "Manager",
            "Senior Associate",
            "Specialist",
            "Specialist 2",
            "Associate",
            "Trainee/Apprentice",
            "Administrative",
            "Administrative 2"
        ],
        "additional_job_classification": "CA_Policy_A",
        "company_code": "NA",
        "schedule_type": "Office Schedule (Assigned to user via another automation)",
        "work_week": "Sunday to Saturday",
        "timesheet_template": "Canada TSD Agile Salaried OT",
        "time_entry_approval_path": "Automatic Approval",
        "timesheet_approval": "Supervisor",
        "timesheet_period": "Weekly starting on Sunday",
        "time_off_template": "Time Off",
        "time_off_approval": "System",
        "time_off_types": [
            "CAN_TOIL",
            "Holiday",
            "Leave of Absence"
        ],
        "payrule": "BC_PT_SAL_PolicyA",
        "time_zone": "(UTC-4:00) Atlantic Standard Time",
        "holiday_calendar": "Canada BC Holiday Calendar",
        "authentication_type": "SSO"
    },
    {
        "country": "Canada",
        "location": "British Columbia",
        "worker_type": "Employee",
        "compensation_grade": "Hourly",
        "contract_type": [
            "Full_time",
            "Part_time"
        ],
        "employee_type": [
            "Regular",
            "Fixed Term",
            "Partner",
            "Intern",
            "Non-Salaried / Self-Employed",
            "Non-Salaried / Self-Employed (Fixed Term)"
        ],
        "job_category": [
            "Functional",
            "Client Services"
        ],
        "management_level": [
            "CEO",
            "Partner",
            "Executive Vice President",
            "Senior Vice President",
            "Vice President",
            "Director",
            "Senior Manager",
            "Manager",
            "Senior Associate",
            "Specialist",
            "Specialist 2",
            "Associate",
            "Trainee/Apprentice",
            "Administrative",
            "Administrative 2"
        ],
        "additional_job_classification": "CA_Policy_A",
        "company_code": "NA",
        "schedule_type": "Office Schedule (Assigned to user via another automation)",
        "work_week": "Sunday to Saturday",
        "timesheet_template": "Canada TSD Agile Salaried OT",
        "time_entry_approval_path": "Automatic Approval",
        "timesheet_approval": "Hourly/Cont TS Approval Path",
        "timesheet_period": "Weekly starting on Sunday",
        "time_off_template": "Time Off",
        "time_off_approval": "Hourly TO Approval Path",
        "time_off_types": [
            "Holiday",
            "Leave of Absence"
        ],
        "payrule": "BC_Hourly_PolicyA",
        "time_zone": "(UTC-4:00) Atlantic Standard Time",
        "holiday_calendar": "Canada BC Holiday Calendar",
        "authentication_type": "SSO"
    },
    {
        "country": "Canada",
        "location": "British Columbia",
        "worker_type": "Employee",
        "compensation_grade": "Salary",
        "contract_type": "Full_time",
        "employee_type": [
            "Regular",
            "Fixed Term",
            "Partner",
            "Intern",
            "Non-Salaried / Self-Employed",
            "Non-Salaried / Self-Employed (Fixed Term)"
        ],
        "job_category": [
            "Functional",
            "Client Services"
        ],
        "management_level": [
            "CEO",
            "Partner",
            "Executive Vice President",
            "Senior Vice President",
            "Vice President",
            "Director",
            "Senior Manager",
            "Manager",
            "Senior Associate",
            "Specialist",
            "Specialist 2",
            "Associate",
            "Trainee/Apprentice",
            "Administrative",
            "Administrative 2"
        ],
        "additional_job_classification": "CA_Policy_B",
        "company_code": "NA",
        "schedule_type": "Office Schedule (Assigned to user via another automation)",
        "work_week": "Sunday to Saturday",
        "timesheet_template": "Canada TSD Agile Salaried OT",
        "time_entry_approval_path": "Automatic Approval",
        "timesheet_approval": "Supervisor",
        "timesheet_period": "Weekly starting on Sunday",
        "time_off_template": "Time Off",
        "time_off_approval": "System",
        "time_off_types": [
            "CAN_TOIL",
            "Holiday",
            "Leave of Absence"
        ],
        "payrule": "BC_FT_SAL_PolicyB",
        "time_zone": "(UTC-4:00) Atlantic Standard Time",
        "holiday_calendar": "Canada BC Holiday Calendar",
        "authentication_type": "SSO"
    },
    {
        "country": "Canada",
        "location": "British Columbia",
        "worker_type": "Employee",
        "compensation_grade": "Salary",
        "contract_type": "Part_time",
        "employee_type": [
            "Regular",
            "Fixed Term",
            "Partner",
            "Intern",
            "Non-Salaried / Self-Employed",
            "Non-Salaried / Self-Employed (Fixed Term)"
        ],
        "job_category": [
            "Functional",
            "Client Services"
        ],
        "management_level": [
            "CEO",
            "Partner",
            "Executive Vice President",
            "Senior Vice President",
            "Vice President",
            "Director",
            "Senior Manager",
            "Manager",
            "Senior Associate",
            "Specialist",
            "Specialist 2",
            "Associate",
            "Trainee/Apprentice",
            "Administrative",
            "Administrative 2"
        ],
        "additional_job_classification": "CA_Policy_B",
        "company_code": "NA",
        "schedule_type": "Office Schedule (Assigned to user via another automation)",
        "work_week": "Sunday to Saturday",
        "timesheet_template": "Canada TSD Agile Salaried OT",
        "time_entry_approval_path": "Automatic Approval",
        "timesheet_approval": "Supervisor",
        "timesheet_period": "Weekly starting on Sunday",
        "time_off_template": "Time Off",
        "time_off_approval": "System",
        "time_off_types": [
            "CAN_TOIL",
            "Holiday",
            "Leave of Absence"
        ],
        "payrule": "BC_PT_SAL_PolicyB",
        "time_zone": "(UTC-4:00) Atlantic Standard Time",
        "holiday_calendar": "Canada BC Holiday Calendar",
        "authentication_type": "SSO"
    },
    {
        "country": "Canada",
        "location": "British Columbia",
        "worker_type": "Employee",
        "compensation_grade": "Hourly",
        "contract_type": [
            "Full_time",
            "Part_time"
        ],
        "employee_type": [
            "Regular",
            "Fixed Term",
            "Partner",
            "Intern",
            "Non-Salaried / Self-Employed",
            "Non-Salaried / Self-Employed (Fixed Term)"
        ],
        "job_category": [
            "Functional",
            "Client Services"
        ],
        "management_level": [
            "CEO",
            "Partner",
            "Executive Vice President",
            "Senior Vice President",
            "Vice President",
            "Director",
            "Senior Manager",
            "Manager",
            "Senior Associate",
            "Specialist",
            "Specialist 2",
            "Associate",
            "Trainee/Apprentice",
            "Administrative",
            "Administrative 2"
        ],
        "additional_job_classification": "CA_Policy_B",
        "company_code": "NA",
        "schedule_type": "Office Schedule (Assigned to user via another automation)",
        "work_week": "Sunday to Saturday",
        "timesheet_template": "Canada TSD Agile Hourly OT/NON-OT",
        "time_entry_approval_path": "Automatic Approval",
        "timesheet_approval": "Hourly/Cont TS Approval Path",
        "timesheet_period": "Weekly starting on Sunday",
        "time_off_template": "Time Off",
        "time_off_approval": "Hourly TO Approval Path",
        "time_off_types": [
            "Holiday",
            "Leave of Absence"
        ],
        "payrule": "BC_Hourly_PolicyB",
        "time_zone": "(UTC-4:00) Atlantic Standard Time",
        "holiday_calendar": "Canada BC Holiday Calendar",
        "authentication_type": "SSO"
    },
    {
        "country": "Canada",
        "location": "British Columbia",
        "worker_type": "Employee",
        "compensation_grade": "Salary",
        "contract_type": [
            "Full_time",
            "Part_time"
        ],
        "employee_type": [
            "Regular",
            "Fixed Term",
            "Partner",
            "Intern",
            "Non-Salaried / Self-Employed",
            "Non-Salaried / Self-Employed (Fixed Term)"
        ],
        "job_category": [
            "Functional",
            "Client Services"
        ],
        "management_level": [
            "CEO",
            "Partner",
            "Executive Vice President",
            "Senior Vice President",
            "Vice President",
            "Director",
            "Senior Manager",
            "Manager",
            "Senior Associate",
            "Specialist",
            "Specialist 2",
            "Associate",
            "Trainee/Apprentice",
            "Administrative",
            "Administrative 2"
        ],
        "additional_job_classification": "NA",
        "company_code": "NA",
        "schedule_type": "Office Schedule (Assigned to user via another automation)",
        "work_week": "Sunday to Saturday",
        "timesheet_template": "Canada TSD Agile Salaried NON-OT",
        "time_entry_approval_path": "Automatic Approval",
        "timesheet_approval": "Supervisor",
        "timesheet_period": "Weekly starting on Sunday",
        "time_off_template": "Time Off",
        "time_off_approval": "System",
        "time_off_types": [
            "CAN_TOIL",
            "Holiday",
            "Leave of Absence"
        ],
        "payrule": "BC_SAL_NO_AJC",
        "time_zone": "(UTC-4:00) Atlantic Standard Time",
        "holiday_calendar": "Canada BC Holiday Calendar",
        "authentication_type": "SSO"
    },
    {
        "country": "Canada",
        "location": "British Columbia",
        "worker_type": "Employee",
        "compensation_grade": "Hourly",
        "contract_type": [
            "Full_time",
            "Part_time"
        ],
        "employee_type": [
            "Regular",
            "Fixed Term",
            "Partner",
            "Intern",
            "Non-Salaried / Self-Employed",
            "Non-Salaried / Self-Employed (Fixed Term)"
        ],
        "job_category": [
            "Functional",
            "Client Services"
        ],
        "management_level": [
            "CEO",
            "Partner",
            "Executive Vice President",
            "Senior Vice President",
            "Vice President",
            "Director",
            "Senior Manager",
            "Manager",
            "Senior Associate",
            "Specialist",
            "Specialist 2",
            "Associate",
            "Trainee/Apprentice",
            "Administrative",
            "Administrative 2"
        ],
        "additional_job_classification": "NA",
        "company_code": "NA",
        "schedule_type": "Office Schedule (Assigned to user via another automation)",
        "work_week": "Sunday to Saturday",
        "timesheet_template": "Canada TSD Agile Salaried OT",
        "time_entry_approval_path": "Automatic Approval",
        "timesheet_approval": "Hourly/Cont TS Approval Path",
        "timesheet_period": "Weekly starting on Sunday",
        "time_off_template": "Time Off",
        "time_off_approval": "Hourly TO Approval Path",
        "time_off_types": [
            "Holiday",
            "Leave of Absence"
        ],
        "payrule": "BC_Hourly_NO_AJC",
        "time_zone": "(UTC-4:00) Atlantic Standard Time",
        "holiday_calendar": "Canada BC Holiday Calendar",
        "authentication_type": "SSO"
    },
    {
        "country": "Canada",
        "location": "Quebec",
        "worker_type": "Employee",
        "compensation_grade": "Salary",
        "contract_type": "Full_time",
        "employee_type": [
            "Regular",
            "Fixed Term",
            "Partner",
            "Intern",
            "Non-Salaried / Self-Employed",
            "Non-Salaried / Self-Employed (Fixed Term)"
        ],
        "job_category": [
            "Functional",
            "Client Services"
        ],
        "management_level": [
            "CEO",
            "Partner",
            "Executive Vice President",
            "Senior Vice President",
            "Vice President",
            "Director",
            "Senior Manager",
            "Manager",
            "Senior Associate",
            "Specialist",
            "Specialist 2",
            "Associate",
            "Trainee/Apprentice",
            "Administrative",
            "Administrative 2"
        ],
        "additional_job_classification": "CA_Policy_A",
        "company_code": "NA",
        "schedule_type": "Office Schedule (Assigned to user via another automation)",
        "work_week": "Sunday to Saturday",
        "timesheet_template": "Canada TSD Agile Salaried OT",
        "time_entry_approval_path": "Automatic Approval",
        "timesheet_approval": "Supervisor",
        "timesheet_period": "Weekly starting on Sunday",
        "time_off_template": "Time Off",
        "time_off_approval": "System",
        "time_off_types": [
            "CAN_TOIL",
            "Holiday",
            "Leave of Absence"
        ],
        "payrule": "Quebec_FT_SAL_PolicyA",
        "time_zone": "(UTC-4:00) Atlantic Standard Time",
        "holiday_calendar": "Canada Quebec Holiday Calendar",
        "authentication_type": "SSO"
    },
    {
        "country": "Canada",
        "location": "Quebec",
        "worker_type": "Employee",
        "compensation_grade": "Salary",
        "contract_type": "Part_time",
        "employee_type": [
            "Regular",
            "Fixed Term",
            "Partner",
            "Intern",
            "Non-Salaried / Self-Employed",
            "Non-Salaried / Self-Employed (Fixed Term)"
        ],
        "job_category": [
            "Functional",
            "Client Services"
        ],
        "management_level": [
            "CEO",
            "Partner",
            "Executive Vice President",
            "Senior Vice President",
            "Vice President",
            "Director",
            "Senior Manager",
            "Manager",
            "Senior Associate",
            "Specialist",
            "Specialist 2",
            "Associate",
            "Trainee/Apprentice",
            "Administrative",
            "Administrative 2"
        ],
        "additional_job_classification": "CA_Policy_A",
        "company_code": "NA",
        "schedule_type": "Office Schedule (Assigned to user via another automation)",
        "work_week": "Sunday to Saturday",
        "timesheet_template": "Canada TSD Agile Salaried OT",
        "time_entry_approval_path": "Automatic Approval",
        "timesheet_approval": "Supervisor",
        "timesheet_period": "Weekly starting on Sunday",
        "time_off_template": "Time Off",
        "time_off_approval": "System",
        "time_off_types": [
            "CAN_TOIL",
            "Holiday",
            "Leave of Absence"
        ],
        "payrule": "Quebec_PT_SAL_PolicyA",
        "time_zone": "(UTC-4:00) Atlantic Standard Time",
        "holiday_calendar": "Canada Quebec Holiday Calendar",
        "authentication_type": "SSO"
    },
    {
        "country": "Canada",
        "location": "Quebec",
        "worker_type": "Employee",
        "compensation_grade": "Hourly",
        "contract_type": [
            "Full_time",
            "Part_time"
        ],
        "employee_type": [
            "Regular",
            "Fixed Term",
            "Partner",
            "Intern",
            "Non-Salaried / Self-Employed",
            "Non-Salaried / Self-Employed (Fixed Term)"
        ],
        "job_category": [
            "Functional",
            "Client Services"
        ],
        "management_level": [
            "CEO",
            "Partner",
            "Executive Vice President",
            "Senior Vice President",
            "Vice President",
            "Director",
            "Senior Manager",
            "Manager",
            "Senior Associate",
            "Specialist",
            "Specialist 2",
            "Associate",
            "Trainee/Apprentice",
            "Administrative",
            "Administrative 2"
        ],
        "additional_job_classification": "CA_Policy_A",
        "company_code": "NA",
        "schedule_type": "Office Schedule (Assigned to user via another automation)",
        "work_week": "Sunday to Saturday",
        "timesheet_template": "Canada TSD Agile Salaried OT",
        "time_entry_approval_path": "Automatic Approval",
        "timesheet_approval": "Hourly/Cont TS Approval Path",
        "timesheet_period": "Weekly starting on Sunday",
        "time_off_template": "Time Off",
        "time_off_approval": "Hourly TO Approval Path",
        "time_off_types": [
            "Holiday",
            "Leave of Absence"
        ],
        "payrule": "Quebec_Hourly_PolicyA",
        "time_zone": "(UTC-4:00) Atlantic Standard Time",
        "holiday_calendar": "Canada Quebec Holiday Calendar",
        "authentication_type": "SSO"
    },
    {
        "country": "Canada",
        "location": "Quebec",
        "worker_type": "Employee",
        "compensation_grade": "Salary",
        "contract_type": "Full_time",
        "employee_type": [
            "Regular",
            "Fixed Term",
            "Partner",
            "Intern",
            "Non-Salaried / Self-Employed",
            "Non-Salaried / Self-Employed (Fixed Term)"
        ],
        "job_category": [
            "Functional",
            "Client Services"
        ],
        "management_level": [
            "CEO",
            "Partner",
            "Executive Vice President",
            "Senior Vice President",
            "Vice President",
            "Director",
            "Senior Manager",
            "Manager",
            "Senior Associate",
            "Specialist",
            "Specialist 2",
            "Associate",
            "Trainee/Apprentice",
            "Administrative",
            "Administrative 2"
        ],
        "additional_job_classification": "CA_Policy_B",
        "company_code": "NA",
        "schedule_type": "Office Schedule (Assigned to user via another automation)",
        "work_week": "Sunday to Saturday",
        "timesheet_template": "Canada TSD Agile Salaried OT",
        "time_entry_approval_path": "Automatic Approval",
        "timesheet_approval": "Supervisor",
        "timesheet_period": "Weekly starting on Sunday",
        "time_off_template": "Time Off",
        "time_off_approval": "System",
        "time_off_types": [
            "CAN_TOIL",
            "Holiday",
            "Leave of Absence"
        ],
        "payrule": "Quebec_FT_SAL_PolicyB",
        "time_zone": "(UTC-4:00) Atlantic Standard Time",
        "holiday_calendar": "Canada Quebec Holiday Calendar",
        "authentication_type": "SSO"
    },
    {
        "country": "Canada",
        "location": "Quebec",
        "worker_type": "Employee",
        "compensation_grade": "Salary",
        "contract_type": "Part_time",
        "employee_type": [
            "Regular",
            "Fixed Term",
            "Partner",
            "Intern",
            "Non-Salaried / Self-Employed",
            "Non-Salaried / Self-Employed (Fixed Term)"
        ],
        "job_category": [
            "Functional",
            "Client Services"
        ],
        "management_level": [
            "CEO",
            "Partner",
            "Executive Vice President",
            "Senior Vice President",
            "Vice President",
            "Director",
            "Senior Manager",
            "Manager",
            "Senior Associate",
            "Specialist",
            "Specialist 2",
            "Associate",
            "Trainee/Apprentice",
            "Administrative",
            "Administrative 2"
        ],
        "additional_job_classification": "CA_Policy_B",
        "company_code": "NA",
        "schedule_type": "Office Schedule (Assigned to user via another automation)",
        "work_week": "Sunday to Saturday",
        "timesheet_template": "Canada TSD Agile Salaried OT",
        "time_entry_approval_path": "Automatic Approval",
        "timesheet_approval": "Supervisor",
        "timesheet_period": "Weekly starting on Sunday",
        "time_off_template": "Time Off",
        "time_off_approval": "System",
        "time_off_types": [
            "CAN_TOIL",
            "Holiday",
            "Leave of Absence"
        ],
        "payrule": "Quebec_PT_SAL_PolicyB",
        "time_zone": "(UTC-4:00) Atlantic Standard Time",
        "holiday_calendar": "Canada Quebec Holiday Calendar",
        "authentication_type": "SSO"
    },
    {
        "country": "Canada",
        "location": "Quebec",
        "worker_type": "Employee",
        "compensation_grade": "Hourly",
        "contract_type": [
            "Full_time",
            "Part_time"
        ],
        "employee_type": [
            "Regular",
            "Fixed Term",
            "Partner",
            "Intern",
            "Non-Salaried / Self-Employed",
            "Non-Salaried / Self-Employed (Fixed Term)"
        ],
        "job_category": [
            "Functional",
            "Client Services"
        ],
        "management_level": [
            "CEO",
            "Partner",
            "Executive Vice President",
            "Senior Vice President",
            "Vice President",
            "Director",
            "Senior Manager",
            "Manager",
            "Senior Associate",
            "Specialist",
            "Specialist 2",
            "Associate",
            "Trainee/Apprentice",
            "Administrative",
            "Administrative 2"
        ],
        "additional_job_classification": "CA_Policy_B",
        "company_code": "NA",
        "schedule_type": "Office Schedule (Assigned to user via another automation)",
        "work_week": "Sunday to Saturday",
        "timesheet_template": "Canada TSD Agile Hourly OT/NON-OT",
        "time_entry_approval_path": "Automatic Approval",
        "timesheet_approval": "Hourly/Cont TS Approval Path",
        "timesheet_period": "Weekly starting on Sunday",
        "time_off_template": "Time Off",
        "time_off_approval": "Hourly TO Approval Path",
        "time_off_types": [
            "Holiday",
            "Leave of Absence"
        ],
        "payrule": "Quebec_Hourly_PolicyB",
        "time_zone": "(UTC-4:00) Atlantic Standard Time",
        "holiday_calendar": "Canada Quebec Holiday Calendar",
        "authentication_type": "SSO"
    },
    {
        "country": "Canada",
        "location": "Quebec",
        "worker_type": "Employee",
        "compensation_grade": "Salary",
        "contract_type": [
            "Full_time",
            "Part_time"
        ],
        "employee_type": [
            "Regular",
            "Fixed Term",
            "Partner",
            "Intern",
            "Non-Salaried / Self-Employed",
            "Non-Salaried / Self-Employed (Fixed Term)"
        ],
        "job_category": [
            "Functional",
            "Client Services"
        ],
        "management_level": [
            "CEO",
            "Partner",
            "Executive Vice President",
            "Senior Vice President",
            "Vice President",
            "Director",
            "Senior Manager",
            "Manager",
            "Senior Associate",
            "Specialist",
            "Specialist 2",
            "Associate",
            "Trainee/Apprentice",
            "Administrative",
            "Administrative 2"
        ],
        "additional_job_classification": "NA",
        "company_code": "NA",
        "schedule_type": "Office Schedule (Assigned to user via another automation)",
        "work_week": "Sunday to Saturday",
        "timesheet_template": "Canada TSD Agile Salaried NON-OT",
        "time_entry_approval_path": "Automatic Approval",
        "timesheet_approval": "Supervisor",
        "timesheet_period": "Weekly starting on Sunday",
        "time_off_template": "Time Off",
        "time_off_approval": "System",
        "time_off_types": [
            "CAN_TOIL",
            "Holiday",
            "Leave of Absence"
        ],
        "payrule": "Quebec_SAL_FT_NO_AJC",
        "time_zone": "(UTC-4:00) Atlantic Standard Time",
        "holiday_calendar": "Canada Quebec Holiday Calendar",
        "authentication_type": "SSO"
    },
    {
        "country": "Canada",
        "location": "Quebec",
        "worker_type": "Employee",
        "compensation_grade": "Salary",
        "contract_type": [
            "Full_time",
            "Part_time"
        ],
        "employee_type": [
            "Regular",
            "Fixed Term",
            "Partner",
            "Intern",
            "Non-Salaried / Self-Employed",
            "Non-Salaried / Self-Employed (Fixed Term)"
        ],
        "job_category": [
            "Functional",
            "Client Services"
        ],
        "management_level": [
            "CEO",
            "Partner",
            "Executive Vice President",
            "Senior Vice President",
            "Vice President",
            "Director",
            "Senior Manager",
            "Manager",
            "Senior Associate",
            "Specialist",
            "Specialist 2",
            "Associate",
            "Trainee/Apprentice",
            "Administrative",
            "Administrative 2"
        ],
        "additional_job_classification": "NA",
        "company_code": "NA",
        "schedule_type": "Office Schedule (Assigned to user via another automation)",
        "work_week": "Sunday to Saturday",
        "timesheet_template": "Canada TSD Agile Salaried NON-OT",
        "time_entry_approval_path": "Automatic Approval",
        "timesheet_approval": "Supervisor",
        "timesheet_period": "Weekly starting on Sunday",
        "time_off_template": "Time Off",
        "time_off_approval": "System",
        "time_off_types": [
            "CAN_TOIL",
            "Holiday",
            "Leave of Absence"
        ],
        "payrule": "Quebec_SAL_PT_NO_AJC",
        "time_zone": "(UTC-4:00) Atlantic Standard Time",
        "holiday_calendar": "Canada Quebec Holiday Calendar",
        "authentication_type": "SSO"
    },
    {
        "country": "Canada",
        "location": "Quebec",
        "worker_type": "Employee",
        "compensation_grade": "Hourly",
        "contract_type": [
            "Full_time",
            "Part_time"
        ],
        "employee_type": [
            "Regular",
            "Fixed Term",
            "Partner",
            "Intern",
            "Non-Salaried / Self-Employed",
            "Non-Salaried / Self-Employed (Fixed Term)"
        ],
        "job_category": [
            "Functional",
            "Client Services"
        ],
        "management_level": [
            "CEO",
            "Partner",
            "Executive Vice President",
            "Senior Vice President",
            "Vice President",
            "Director",
            "Senior Manager",
            "Manager",
            "Senior Associate",
            "Specialist",
            "Specialist 2",
            "Associate",
            "Trainee/Apprentice",
            "Administrative",
            "Administrative 2"
        ],
        "additional_job_classification": "NA",
        "company_code": "NA",
        "schedule_type": "Office Schedule (Assigned to user via another automation)",
        "work_week": "Sunday to Saturday",
        "timesheet_template": "Canada TSD Agile Salaried OT",
        "time_entry_approval_path": "Automatic Approval",
        "timesheet_approval": "Hourly/Cont TS Approval Path",
        "timesheet_period": "Weekly starting on Sunday",
        "time_off_template": "Time Off",
        "time_off_approval": "Hourly TO Approval Path",
        "time_off_types": [
            "Holiday",
            "Leave of Absence"
        ],
        "payrule": "Quebec_Hourly_NO_AJC",
        "time_zone": "(UTC-4:00) Atlantic Standard Time",
        "holiday_calendar": "Canada Quebec Holiday Calendar",
        "authentication_type": "SSO"
    },
    {
        "country": "Canada",
        "location": "Alberta",
        "worker_type": "Employee",
        "compensation_grade": "Salary",
        "contract_type": "Full_time",
        "employee_type": [
            "Regular",
            "Fixed Term",
            "Partner",
            "Intern",
            "Non-Salaried / Self-Employed",
            "Non-Salaried / Self-Employed (Fixed Term)"
        ],
        "job_category": [
            "Functional",
            "Client Services"
        ],
        "management_level": [
            "CEO",
            "Partner",
            "Executive Vice President",
            "Senior Vice President",
            "Vice President",
            "Director",
            "Senior Manager",
            "Manager",
            "Senior Associate",
            "Specialist",
            "Specialist 2",
            "Associate",
            "Trainee/Apprentice",
            "Administrative",
            "Administrative 2"
        ],
        "additional_job_classification": "CA_Policy_A",
        "company_code": "NA",
        "schedule_type": "Office Schedule (Assigned to user via another automation)",
        "work_week": "Sunday to Saturday",
        "timesheet_template": "Canada TSD Agile Salaried OT",
        "time_entry_approval_path": "Automatic Approval",
        "timesheet_approval": "Supervisor",
        "timesheet_period": "Weekly starting on Sunday",
        "time_off_template": "Time Off",
        "time_off_approval": "System",
        "time_off_types": [
            "CAN_TOIL",
            "Holiday",
            "Leave of Absence"
        ],
        "payrule": "Alberta_FT_SAL_PolicyA",
        "time_zone": "(UTC-4:00) Atlantic Standard Time",
        "holiday_calendar": "Canada Alberta Holiday Calendar",
        "authentication_type": "SSO"
    },
    {
        "country": "Canada",
        "location": "Alberta",
        "worker_type": "Employee",
        "compensation_grade": "Salary",
        "contract_type": "Part_time",
        "employee_type": [
            "Regular",
            "Fixed Term",
            "Partner",
            "Intern",
            "Non-Salaried / Self-Employed",
            "Non-Salaried / Self-Employed (Fixed Term)"
        ],
        "job_category": [
            "Functional",
            "Client Services"
        ],
        "management_level": [
            "CEO",
            "Partner",
            "Executive Vice President",
            "Senior Vice President",
            "Vice President",
            "Director",
            "Senior Manager",
            "Manager",
            "Senior Associate",
            "Specialist",
            "Specialist 2",
            "Associate",
            "Trainee/Apprentice",
            "Administrative",
            "Administrative 2"
        ],
        "additional_job_classification": "CA_Policy_A",
        "company_code": "NA",
        "schedule_type": "Office Schedule (Assigned to user via another automation)",
        "work_week": "Sunday to Saturday",
        "timesheet_template": "Canada TSD Agile Salaried OT",
        "time_entry_approval_path": "Automatic Approval",
        "timesheet_approval": "Supervisor",
        "timesheet_period": "Weekly starting on Sunday",
        "time_off_template": "Time Off",
        "time_off_approval": "System",
        "time_off_types": [
            "CAN_TOIL",
            "Holiday",
            "Leave of Absence"
        ],
        "payrule": "Alberta_PT_SAL_PolicyA",
        "time_zone": "(UTC-4:00) Atlantic Standard Time",
        "holiday_calendar": "Canada Alberta Holiday Calendar",
        "authentication_type": "SSO"
    },
    {
        "country": "Canada",
        "location": "Alberta",
        "worker_type": "Employee",
        "compensation_grade": "Hourly",
        "contract_type": [
            "Full_time",
            "Part_time"
        ],
        "employee_type": [
            "Regular",
            "Fixed Term",
            "Partner",
            "Intern",
            "Non-Salaried / Self-Employed",
            "Non-Salaried / Self-Employed (Fixed Term)"
        ],
        "job_category": [
            "Functional",
            "Client Services"
        ],
        "management_level": [
            "CEO",
            "Partner",
            "Executive Vice President",
            "Senior Vice President",
            "Vice President",
            "Director",
            "Senior Manager",
            "Manager",
            "Senior Associate",
            "Specialist",
            "Specialist 2",
            "Associate",
            "Trainee/Apprentice",
            "Administrative",
            "Administrative 2"
        ],
        "additional_job_classification": "CA_Policy_A",
        "company_code": "NA",
        "schedule_type": "Office Schedule (Assigned to user via another automation)",
        "work_week": "Sunday to Saturday",
        "timesheet_template": "Canada TSD Agile Salaried OT",
        "time_entry_approval_path": "Automatic Approval",
        "timesheet_approval": "Hourly/Cont TS Approval Path",
        "timesheet_period": "Weekly starting on Sunday",
        "time_off_template": "Time Off",
        "time_off_approval": "Hourly TO Approval Path",
        "time_off_types": [
            "Holiday",
            "Leave of Absence"
        ],
        "payrule": "Alberta_Hourly_PolicyA",
        "time_zone": "(UTC-4:00) Atlantic Standard Time",
        "holiday_calendar": "Canada Alberta Holiday Calendar",
        "authentication_type": "SSO"
    },
    {
        "country": "Canada",
        "location": "Alberta",
        "worker_type": "Employee",
        "compensation_grade": "Salary",
        "contract_type": "Full_time",
        "employee_type": [
            "Regular",
            "Fixed Term",
            "Partner",
            "Intern",
            "Non-Salaried / Self-Employed",
            "Non-Salaried / Self-Employed (Fixed Term)"
        ],
        "job_category": [
            "Functional",
            "Client Services"
        ],
        "management_level": [
            "CEO",
            "Partner",
            "Executive Vice President",
            "Senior Vice President",
            "Vice President",
            "Director",
            "Senior Manager",
            "Manager",
            "Senior Associate",
            "Specialist",
            "Specialist 2",
            "Associate",
            "Trainee/Apprentice",
            "Administrative",
            "Administrative 2"
        ],
        "additional_job_classification": "CA_Policy_B",
        "company_code": "NA",
        "schedule_type": "Office Schedule (Assigned to user via another automation)",
        "work_week": "Sunday to Saturday",
        "timesheet_template": "Canada TSD Agile Salaried OT",
        "time_entry_approval_path": "Automatic Approval",
        "timesheet_approval": "Supervisor",
        "timesheet_period": "Weekly starting on Sunday",
        "time_off_template": "Time Off",
        "time_off_approval": "System",
        "time_off_types": [
            "CAN_TOIL",
            "Holiday",
            "Leave of Absence"
        ],
        "payrule": "Alberta_FT_SAL_PolicyB",
        "time_zone": "(UTC-4:00) Atlantic Standard Time",
        "holiday_calendar": "Canada Alberta Holiday Calendar",
        "authentication_type": "SSO"
    },
    {
        "country": "Canada",
        "location": "Alberta",
        "worker_type": "Employee",
        "compensation_grade": "Salary",
        "contract_type": "Part_time",
        "employee_type": [
            "Regular",
            "Fixed Term",
            "Partner",
            "Intern",
            "Non-Salaried / Self-Employed",
            "Non-Salaried / Self-Employed (Fixed Term)"
        ],
        "job_category": [
            "Functional",
            "Client Services"
        ],
        "management_level": [
            "CEO",
            "Partner",
            "Executive Vice President",
            "Senior Vice President",
            "Vice President",
            "Director",
            "Senior Manager",
            "Manager",
            "Senior Associate",
            "Specialist",
            "Specialist 2",
            "Associate",
            "Trainee/Apprentice",
            "Administrative",
            "Administrative 2"
        ],
        "additional_job_classification": "CA_Policy_B",
        "company_code": "NA",
        "schedule_type": "Office Schedule (Assigned to user via another automation)",
        "work_week": "Sunday to Saturday",
        "timesheet_template": "Canada TSD Agile Salaried OT",
        "time_entry_approval_path": "Automatic Approval",
        "timesheet_approval": "Supervisor",
        "timesheet_period": "Weekly starting on Sunday",
        "time_off_template": "Time Off",
        "time_off_approval": "System",
        "time_off_types": [
            "CAN_TOIL",
            "Holiday",
            "Leave of Absence"
        ],
        "payrule": "Alberta_PT_SAL_PolicyB",
        "time_zone": "(UTC-4:00) Atlantic Standard Time",
        "holiday_calendar": "Canada Alberta Holiday Calendar",
        "authentication_type": "SSO"
    },
    {
        "country": "Canada",
        "location": "Alberta",
        "worker_type": "Employee",
        "compensation_grade": "Hourly",
        "contract_type": [
            "Full_time",
            "Part_time"
        ],
        "employee_type": [
            "Regular",
            "Fixed Term",
            "Partner",
            "Intern",
            "Non-Salaried / Self-Employed",
            "Non-Salaried / Self-Employed (Fixed Term)"
        ],
        "job_category": [
            "Functional",
            "Client Services"
        ],
        "management_level": [
            "CEO",
            "Partner",
            "Executive Vice President",
            "Senior Vice President",
            "Vice President",
            "Director",
            "Senior Manager",
            "Manager",
            "Senior Associate",
            "Specialist",
            "Specialist 2",
            "Associate",
            "Trainee/Apprentice",
            "Administrative",
            "Administrative 2"
        ],
        "additional_job_classification": "CA_Policy_B",
        "company_code": "NA",
        "schedule_type": "Office Schedule (Assigned to user via another automation)",
        "work_week": "Sunday to Saturday",
        "timesheet_template": "Canada TSD Agile Hourly OT/NON-OT",
        "time_entry_approval_path": "Automatic Approval",
        "timesheet_approval": "Hourly/Cont TS Approval Path",
        "timesheet_period": "Weekly starting on Sunday",
        "time_off_template": "Time Off",
        "time_off_approval": "Hourly TO Approval Path",
        "time_off_types": [
            "Holiday",
            "Leave of Absence"
        ],
        "payrule": "Alberta_Hourly_PolicyB",
        "time_zone": "(UTC-4:00) Atlantic Standard Time",
        "holiday_calendar": "Canada Alberta Holiday Calendar",
        "authentication_type": "SSO"
    },
    {
        "country": "Canada",
        "location": "Alberta",
        "worker_type": "Employee",
        "compensation_grade": "Salary",
        "contract_type": [
            "Full_time",
            "Part_time"
        ],
        "employee_type": [
            "Regular",
            "Fixed Term",
            "Partner",
            "Intern",
            "Non-Salaried / Self-Employed",
            "Non-Salaried / Self-Employed (Fixed Term)"
        ],
        "job_category": [
            "Functional",
            "Client Services"
        ],
        "management_level": [
            "CEO",
            "Partner",
            "Executive Vice President",
            "Senior Vice President",
            "Vice President",
            "Director",
            "Senior Manager",
            "Manager",
            "Senior Associate",
            "Specialist",
            "Specialist 2",
            "Associate",
            "Trainee/Apprentice",
            "Administrative",
            "Administrative 2"
        ],
        "additional_job_classification": "NA",
        "company_code": "NA",
        "schedule_type": "Office Schedule (Assigned to user via another automation)",
        "work_week": "Sunday to Saturday",
        "timesheet_template": "Canada TSD Agile Salaried NON-OT",
        "time_entry_approval_path": "Automatic Approval",
        "timesheet_approval": "Supervisor",
        "timesheet_period": "Weekly starting on Sunday",
        "time_off_template": "Time Off",
        "time_off_approval": "System",
        "time_off_types": [
            "CAN_TOIL",
            "Holiday",
            "Leave of Absence"
        ],
        "payrule": "Alberta_SAL_NO_AJC",
        "time_zone": "(UTC-4:00) Atlantic Standard Time",
        "holiday_calendar": "Canada Alberta Holiday Calendar",
        "authentication_type": "SSO"
    },
    {
        "country": "Canada",
        "location": "Alberta",
        "worker_type": "Employee",
        "compensation_grade": "Hourly",
        "contract_type": [
            "Full_time",
            "Part_time"
        ],
        "employee_type": [
            "Regular",
            "Fixed Term",
            "Partner",
            "Intern",
            "Non-Salaried / Self-Employed",
            "Non-Salaried / Self-Employed (Fixed Term)"
        ],
        "job_category": [
            "Functional",
            "Client Services"
        ],
        "management_level": [
            "CEO",
            "Partner",
            "Executive Vice President",
            "Senior Vice President",
            "Vice President",
            "Director",
            "Senior Manager",
            "Manager",
            "Senior Associate",
            "Specialist",
            "Specialist 2",
            "Associate",
            "Trainee/Apprentice",
            "Administrative",
            "Administrative 2"
        ],
        "additional_job_classification": "NA",
        "company_code": "NA",
        "schedule_type": "Office Schedule (Assigned to user via another automation)",
        "work_week": "Sunday to Saturday",
        "timesheet_template": "Canada TSD Agile Salaried OT",
        "time_entry_approval_path": "Automatic Approval",
        "timesheet_approval": "Hourly/Cont TS Approval Path",
        "timesheet_period": "Weekly starting on Sunday",
        "time_off_template": "Time Off",
        "time_off_approval": "Hourly TO Approval Path",
        "time_off_types": [
            "Holiday",
            "Leave of Absence"
        ],
        "payrule": "Alberta_Hourly_NO_AJC",
        "time_zone": "(UTC-4:00) Atlantic Standard Time",
        "holiday_calendar": "Canada Alberta Holiday Calendar",
        "authentication_type": "SSO"
    },
    {
        "country": "Canada",
        "location": "ALL",
        "worker_type": "Contingent Worker",
        "compensation_grade": "NA",
        "contract_type": [
            "Full_time",
            "Part_time"
        ],
        "employee_type": [
            "Agency Contractor",
            "Alliance/Perimeter Worker",
            "Direct Contractor",
            "Vendor",
            "Intern"
        ],
        "job_category": "Indirect_Labor",
        "management_level": [
            "CEO",
            "Partner",
            "Executive Vice President",
            "Senior Vice President",
            "Vice President",
            "Director",
            "Senior Manager",
            "Manager",
            "Senior Associate",
            "Specialist",
            "Specialist 2",
            "Associate",
            "Trainee/Apprentice",
            "Administrative",
            "Administrative 2"
        ],
        "additional_job_classification": "NA",
        "company_code": "NA",
        "schedule_type": "Office Schedule (Assigned to user via another automation)",
        "work_week": "Sunday to Saturday",
        "timesheet_template": "Vialto TSD Agile Contingent",
        "time_entry_approval_path": "Automatic Approval",
        "timesheet_approval": "Hourly/Cont TS Approval Path",
        "timesheet_period": "Weekly starting on Sunday",
        "time_off_template": "NA",
        "time_off_approval": "NA",
        "time_off_types": "NA",
        "payrule": "Vialto Dummy Pay Rule",
        "time_zone": "(UTC-6:00) Canada Central Standard Time",
        "holiday_calendar": "NA",
        "authentication_type": "SSO"
    }
]
