# Any Mapper Update - Create a new version file under mapper folder
# Update import statement appropriatly in the instance confiuguration file
# To get the changes applied direclty to a specific instance

user_sync_mapper = [
    {
        "location_code": "02032",
        "location_name": "TTEC-GRC-Athens, Syggrou St - Greece",
        "country": "Greece",
        "work_week_uri": "urn:replicon:day-of-week:monday",
        "timesheet_approval_path": "Supervisor",
        "timesheet_period": "Monthly",
        "timeoff_template": "Time Off",
        "timeoff_approval_path": "HC Approved",
        "payrule": "Greece",
        "timezone": "(UTC+2:00) FLE Standard Time",
        "holiday_calender": "Greece",
        "employee_type_1": "G&A|Agent",
        "employee_type_2": "FT|PT",
        "employee_type_3": "Regular|Temporary",
        "employee_type_full_path": ["G&A|FT|Regular",
                                    "G&A|FT|Temporary", "G&A|PT|Regular", "G&A|PT|Temporary",
                                    "Agent|PT|Regular", "Agent|PT|Temporary", "Agent|FT|Regular", "Agent|FT|Temporary"],
        "time_off_types": ["GR Additional Paid leave - Child's progress in school",
                        "GR Additional Paid leave - Single/Widowed parents",
                        "GR Annual Leave",
                        "GR_Blood Donation Leave",
                        "GR_Additional Parental Leave - Child/Family Sick",
                        "GR_Blood Transfusion Leave",
                        "GR Caregiver Leave",
                        "GR Child Hospitalization Leave",
                        "GR_Compassionate Care Leave" ,
                        "GR Election Day",
                        "GR Caregiver Force Majeure Leave",
                        "GR_Marriage Leave",
                        "GR Unpaid Leave",
                        "GR Unforseen events ( Unpaid)",
                        "GR_Study Leave - Postgraduate/ Doctoral",
                        "GR_Study Leave - Undergraduate Diploma",
                        "GR_Single-Parent Leave",
                        "GR_Sick Leave - Unpaid",
                        "GR Sick Leave",
                        "GR_Reduced working hours for parents of children with disabilities",
                        "GR_Protection for Motherhood Leave",
                        "GR_ Prenatal & Gynaecological examination Leave",
                        "GR Paternity Leave",
                        "GR Parental Child-rearing Leave",
                        "GR Medically Assisted Reproduction (IVF) Leave",
                        "GR_Maternity Leave",
                        "GR_Maternity Leave (Reduced working hours)",
                        "GR_Court Leave(D)",
                        "GR_Court Leave(W)",
                        "GR Isochronous Leave" ,
                        "GR Leave for Grave Disease of a child",
                        "GR_Military Leave",
                        "GR Paid not worked day(Manager booking)",
                        "GR_Strike Leave - Ad hoc",
                        "GR_Strike Leave - Ad hoc (U)",
                        "GR Annual Leave (Previous Year)"]
                            },
    {
        "location_code": "02031",
        "location_name": "TTEC-GRC-GREECE, AT HOME",
        "country": "Greece",
        "work_week_uri": "urn:replicon:day-of-week:monday",
        "timesheet_approval_path": "Supervisor",
        "timesheet_period": "Monthly",
        "timeoff_template": "Time Off",
        "timeoff_approval_path": "HC Approved",
        "payrule": "Greece",
        "timezone": "(UTC+2:00) FLE Standard Time",
        "holiday_calender": "Greece",
        "employee_type_1": "G&A|Agent",
        "employee_type_2": "FT|PT",
        "employee_type_3": "Regular|Temporary",
        "employee_type_full_path": ["G&A|FT|Regular",
                                    "G&A|FT|Temporary", "G&A|PT|Regular", "G&A|PT|Temporary",
                                    "Agent|PT|Regular", "Agent|PT|Temporary", "Agent|FT|Regular", "Agent|FT|Temporary"],
        "time_off_types": ["GR Additional Paid leave - Child's progress in school",
                        "GR Additional Paid leave - Single/Widowed parents",
                        "GR Annual Leave",
                        "GR_Blood Donation Leave",
                        "GR_Additional Parental Leave - Child/Family Sick",
                        "GR_Blood Transfusion Leave",
                        "GR Caregiver Leave",
                        "GR Child Hospitalization Leave",
                        "GR_Compassionate Care Leave" ,
                        "GR Election Day",
                        "GR Caregiver Force Majeure Leave",
                        "GR_Marriage Leave",
                        "GR Unpaid Leave",
                        "GR Unforseen events ( Unpaid)",
                        "GR_Study Leave - Postgraduate/ Doctoral",
                        "GR_Study Leave - Undergraduate Diploma",
                        "GR_Single-Parent Leave",
                        "GR_Sick Leave - Unpaid",
                        "GR Sick Leave",
                        "GR_Reduced working hours for parents of children with disabilities",
                        "GR_Protection for Motherhood Leave",
                        "GR_ Prenatal & Gynaecological examination Leave",
                        "GR Paternity Leave",
                        "GR Parental Child-rearing Leave",
                        "GR Medically Assisted Reproduction (IVF) Leave",
                        "GR_Maternity Leave",
                        "GR_Maternity Leave (Reduced working hours)",
                        "GR_Court Leave(D)",
                        "GR_Court Leave(W)",
                        "GR Isochronous Leave" ,
                        "GR Leave for Grave Disease of a child",
                        "GR_Military Leave",
                        "GR Paid not worked day(Manager booking)",
                        "GR_Strike Leave - Ad hoc",
                        "GR_Strike Leave - Ad hoc (U)",
                        "GR Annual Leave (Previous Year)"]
    },
]
