# Sheet: PHL Mapper Updated
# Rows: 62, Columns: 25
# CR_1.5 Change 2: Removed records where Work Shift='Others' and Job level in [1-7]
null = None
PHL_GENERAL_MAPPER = [
  {
    "Company Code": "PHES",
    "Personnel Sub Area Code": "Any",
    "SubGroup": "Any",
    "Industrial_Instrument_Classification": "Any",
    "Job level": 8,
    "Location": "Philippines",
    "Work Shift": "Others",
    "Gender": "Any",
    "Schedule Type (Office or Shift)": "Any",
    "Schedule Policy": "[PHL] Shift Schedule policy",
    "Overtime Requests": "Pre-approval extra time request",
    "Overtime Request Approval Paths": "PHL OT Approval",
    "Timesheet Template": "PHL In/Out JL 8-9",
    "Timesheet Approval": "Supervisor for OT",
    "Timesheet Period": "Weekly - Starting Monday - ES employees and Contractors",
    "Time Off Template": "Time Off",
    "Time Off Approval": "PHL Approval Path",
    "Payrule": "Custom Philippines",
    "Time Off Types": "Refer to Time off Mapping sheet",
    "Time Zone": "(UTC+8:00) North Asia East Standard Time",
    "Work Week": "Monday to Sunday",
    "Holiday Calendar": "refer to holiday calendar sheet",
    "Authentication Type": "SSO",
    "Activities": "Refer to ES activity list sheet",
    "Time Entry Approval Path": "System",
    "Product": "",
    "Product URI": ""
  },
  {
    "Company Code": "PHET",
    "Personnel Sub Area Code": "Any",
    "SubGroup": "Any",
    "Industrial_Instrument_Classification": "Any",
    "Job level": 8,
    "Location": "Philippines",
    "Work Shift": "Others",
    "Gender": "Any",
    "Schedule Type (Office or Shift)": "Any",
    "Schedule Policy": "[PHL] Shift Schedule policy",
    "Overtime Requests": "Pre-approval extra time request",
    "Overtime Request Approval Paths": "PHL OT Approval",
    "Timesheet Template": "PHL In/Out JL 8-9",
    "Timesheet Approval": "Supervisor for OT",
    "Timesheet Period": "Weekly - Starting Monday - ES employees and Contractors",
    "Time Off Template": "Time Off",
    "Time Off Approval": "PHL Approval Path",
    "Payrule": "Custom Philippines",
    "Time Off Types": "Refer to Time off Mapping sheet",
    "Time Zone": "(UTC+8:00) North Asia East Standard Time",
    "Work Week": "Monday to Sunday",
    "Holiday Calendar": "refer to holiday calendar sheet",
    "Authentication Type": "SSO",
    "Activities": "Refer to ES activity list sheet",
    "Time Entry Approval Path": "System",
    "Product": "",
    "Product URI": ""
  },
  {
    "Company Code": "PHES",
    "Personnel Sub Area Code": "Any",
    "SubGroup": "Any",
    "Industrial_Instrument_Classification": "Any",
    "Job level": 9,
    "Location": "Philippines",
    "Work Shift": "Others",
    "Gender": "Any",
    "Schedule Type (Office or Shift)": "Any",
    "Schedule Policy": "[PHL] Shift Schedule policy",
    "Overtime Requests": "Pre-approval extra time request",
    "Overtime Request Approval Paths": "PHL OT Approval",
    "Timesheet Template": "PHL In/Out JL 8-9",
    "Timesheet Approval": "Supervisor for OT",
    "Timesheet Period": "Weekly - Starting Monday - ES employees and Contractors",
    "Time Off Template": "Time Off",
    "Time Off Approval": "PHL Approval Path",
    "Payrule": "Custom Philippines",
    "Time Off Types": "Refer to Time off Mapping sheet",
    "Time Zone": "(UTC+8:00) North Asia East Standard Time",
    "Work Week": "Monday to Sunday",
    "Holiday Calendar": "refer to holiday calendar sheet",
    "Authentication Type": "SSO",
    "Activities": "Refer to ES activity list sheet",
    "Time Entry Approval Path": "System",
    "Product": "",
    "Product URI": ""
  },
  {
    "Company Code": "PHET",
    "Personnel Sub Area Code": "Any",
    "SubGroup": "Any",
    "Industrial_Instrument_Classification": "Any",
    "Job level": 9,
    "Location": "Philippines",
    "Work Shift": "Others",
    "Gender": "Any",
    "Schedule Type (Office or Shift)": "Any",
    "Schedule Policy": "[PHL] Shift Schedule policy",
    "Overtime Requests": "Pre-approval extra time request",
    "Overtime Request Approval Paths": "PHL OT Approval",
    "Timesheet Template": "PHL In/Out JL 8-9",
    "Timesheet Approval": "Supervisor for OT",
    "Timesheet Period": "Weekly - Starting Monday - ES employees and Contractors",
    "Time Off Template": "Time Off",
    "Time Off Approval": "PHL Approval Path",
    "Payrule": "Custom Philippines",
    "Time Off Types": "Refer to Time off Mapping sheet",
    "Time Zone": "(UTC+8:00) North Asia East Standard Time",
    "Work Week": "Monday to Sunday",
    "Holiday Calendar": "refer to holiday calendar sheet",
    "Authentication Type": "SSO",
    "Activities": "Refer to ES activity list sheet",
    "Time Entry Approval Path": "System",
    "Product": "",
    "Product URI": ""
  },
  {
    "Company Code": "PHES",
    "Personnel Sub Area Code": "Any",
    "SubGroup": "Any",
    "Industrial_Instrument_Classification": "Any",
    "Job level": 10,
    "Location": "Philippines",
    "Work Shift": "Others",
    "Gender": "Any",
    "Schedule Type (Office or Shift)": "Any",
    "Schedule Policy": "[PHL] Shift Schedule policy",
    "Overtime Requests": "Pre-approval OT Request",
    "Overtime Request Approval Paths": "PHL OT Approval",
    "Timesheet Template": "PHL In/Out JL 10 - 14",
    "Timesheet Approval": "Supervisor for OT",
    "Timesheet Period": "Weekly - Starting Monday - ES employees and Contractors",
    "Time Off Template": "Time Off",
    "Time Off Approval": "PHL Approval Path",
    "Payrule": "Custom Philippines",
    "Time Off Types": "Refer to Time off Mapping sheet",
    "Time Zone": "(UTC+8:00) North Asia East Standard Time",
    "Work Week": "Monday to Sunday",
    "Holiday Calendar": "refer to holiday calendar sheet",
    "Authentication Type": "SSO",
    "Activities": "Refer to ES activity list sheet",
    "Time Entry Approval Path": "System",
    "Product": "",
    "Product URI": ""
  },
  {
    "Company Code": "PHET",
    "Personnel Sub Area Code": "Any",
    "SubGroup": "Any",
    "Industrial_Instrument_Classification": "Any",
    "Job level": 10,
    "Location": "Philippines",
    "Work Shift": "Others",
    "Gender": "Any",
    "Schedule Type (Office or Shift)": "Any",
    "Schedule Policy": "[PHL] Shift Schedule policy",
    "Overtime Requests": "Pre-approval OT Request",
    "Overtime Request Approval Paths": "PHL OT Approval",
    "Timesheet Template": "PHL In/Out JL 10 - 14",
    "Timesheet Approval": "Supervisor for OT",
    "Timesheet Period": "Weekly - Starting Monday - ES employees and Contractors",
    "Time Off Template": "Time Off",
    "Time Off Approval": "PHL Approval Path",
    "Payrule": "Custom Philippines",
    "Time Off Types": "Refer to Time off Mapping sheet",
    "Time Zone": "(UTC+8:00) North Asia East Standard Time",
    "Work Week": "Monday to Sunday",
    "Holiday Calendar": "refer to holiday calendar sheet",
    "Authentication Type": "SSO",
    "Activities": "Refer to ES activity list sheet",
    "Time Entry Approval Path": "System",
    "Product": "",
    "Product URI": ""
  },
  {
    "Company Code": "PHES",
    "Personnel Sub Area Code": "Any",
    "SubGroup": "Any",
    "Industrial_Instrument_Classification": "Any",
    "Job level": 11,
    "Location": "Philippines",
    "Work Shift": "Others",
    "Gender": "Any",
    "Schedule Type (Office or Shift)": "Any",
    "Schedule Policy": "[PHL] Shift Schedule policy",
    "Overtime Requests": "Pre-approval OT Request",
    "Overtime Request Approval Paths": "PHL OT Approval",
    "Timesheet Template": "PHL In/Out JL 10 - 14",
    "Timesheet Approval": "Supervisor for OT",
    "Timesheet Period": "Weekly - Starting Monday - ES employees and Contractors",
    "Time Off Template": "Time Off",
    "Time Off Approval": "PHL Approval Path",
    "Payrule": "Custom Philippines",
    "Time Off Types": "Refer to Time off Mapping sheet",
    "Time Zone": "(UTC+8:00) North Asia East Standard Time",
    "Work Week": "Monday to Sunday",
    "Holiday Calendar": "refer to holiday calendar sheet",
    "Authentication Type": "SSO",
    "Activities": "Refer to ES activity list sheet",
    "Time Entry Approval Path": "System",
    "Product": "",
    "Product URI": ""
  },
  {
    "Company Code": "PHET",
    "Personnel Sub Area Code": "Any",
    "SubGroup": "Any",
    "Industrial_Instrument_Classification": "Any",
    "Job level": 11,
    "Location": "Philippines",
    "Work Shift": "Others",
    "Gender": "Any",
    "Schedule Type (Office or Shift)": "Any",
    "Schedule Policy": "[PHL] Shift Schedule policy",
    "Overtime Requests": "Pre-approval OT Request",
    "Overtime Request Approval Paths": "PHL OT Approval",
    "Timesheet Template": "PHL In/Out JL 10 - 14",
    "Timesheet Approval": "Supervisor for OT",
    "Timesheet Period": "Weekly - Starting Monday - ES employees and Contractors",
    "Time Off Template": "Time Off",
    "Time Off Approval": "PHL Approval Path",
    "Payrule": "Custom Philippines",
    "Time Off Types": "Refer to Time off Mapping sheet",
    "Time Zone": "(UTC+8:00) North Asia East Standard Time",
    "Work Week": "Monday to Sunday",
    "Holiday Calendar": "refer to holiday calendar sheet",
    "Authentication Type": "SSO",
    "Activities": "Refer to ES activity list sheet",
    "Time Entry Approval Path": "System",
    "Product": "",
    "Product URI": ""
  },
  {
    "Company Code": "PHES",
    "Personnel Sub Area Code": "Any",
    "SubGroup": "Any",
    "Industrial_Instrument_Classification": "Any",
    "Job level": 12,
    "Location": "Philippines",
    "Work Shift": "Others",
    "Gender": "Any",
    "Schedule Type (Office or Shift)": "Any",
    "Schedule Policy": "[PHL] Shift Schedule policy",
    "Overtime Requests": "Pre-approval OT Request",
    "Overtime Request Approval Paths": "PHL OT Approval",
    "Timesheet Template": "PHL In/Out JL 10 - 14",
    "Timesheet Approval": "Supervisor for OT",
    "Timesheet Period": "Weekly - Starting Monday - ES employees and Contractors",
    "Time Off Template": "Time Off",
    "Time Off Approval": "PHL Approval Path",
    "Payrule": "Custom Philippines",
    "Time Off Types": "Refer to Time off Mapping sheet",
    "Time Zone": "(UTC+8:00) North Asia East Standard Time",
    "Work Week": "Monday to Sunday",
    "Holiday Calendar": "refer to holiday calendar sheet",
    "Authentication Type": "SSO",
    "Activities": "Refer to ES activity list sheet",
    "Time Entry Approval Path": "System",
    "Product": "",
    "Product URI": ""
  },
  {
    "Company Code": "PHET",
    "Personnel Sub Area Code": "Any",
    "SubGroup": "Any",
    "Industrial_Instrument_Classification": "Any",
    "Job level": 12,
    "Location": "Philippines",
    "Work Shift": "Others",
    "Gender": "Any",
    "Schedule Type (Office or Shift)": "Any",
    "Schedule Policy": "[PHL] Shift Schedule policy",
    "Overtime Requests": "Pre-approval OT Request",
    "Overtime Request Approval Paths": "PHL OT Approval",
    "Timesheet Template": "PHL In/Out JL 10 - 14",
    "Timesheet Approval": "Supervisor for OT",
    "Timesheet Period": "Weekly - Starting Monday - ES employees and Contractors",
    "Time Off Template": "Time Off",
    "Time Off Approval": "PHL Approval Path",
    "Payrule": "Custom Philippines",
    "Time Off Types": "Refer to Time off Mapping sheet",
    "Time Zone": "(UTC+8:00) North Asia East Standard Time",
    "Work Week": "Monday to Sunday",
    "Holiday Calendar": "refer to holiday calendar sheet",
    "Authentication Type": "SSO",
    "Activities": "Refer to ES activity list sheet",
    "Time Entry Approval Path": "System",
    "Product": "",
    "Product URI": ""
  },
  {
    "Company Code": "PHES",
    "Personnel Sub Area Code": "Any",
    "SubGroup": "Any",
    "Industrial_Instrument_Classification": "Any",
    "Job level": 13,
    "Location": "Philippines",
    "Work Shift": "Others",
    "Gender": "Any",
    "Schedule Type (Office or Shift)": "Any",
    "Schedule Policy": "[PHL] Shift Schedule policy",
    "Overtime Requests": "Pre-approval OT Request",
    "Overtime Request Approval Paths": "PHL OT Approval",
    "Timesheet Template": "PHL In/Out JL 10 - 14",
    "Timesheet Approval": "Supervisor for OT",
    "Timesheet Period": "Weekly - Starting Monday - ES employees and Contractors",
    "Time Off Template": "Time Off",
    "Time Off Approval": "PHL Approval Path",
    "Payrule": "Custom Philippines",
    "Time Off Types": "Refer to Time off Mapping sheet",
    "Time Zone": "(UTC+8:00) North Asia East Standard Time",
    "Work Week": "Monday to Sunday",
    "Holiday Calendar": "refer to holiday calendar sheet",
    "Authentication Type": "SSO",
    "Activities": "Refer to ES activity list sheet",
    "Time Entry Approval Path": "System",
    "Product": "",
    "Product URI": ""
  },
  {
    "Company Code": "PHET",
    "Personnel Sub Area Code": "Any",
    "SubGroup": "Any",
    "Industrial_Instrument_Classification": "Any",
    "Job level": 13,
    "Location": "Philippines",
    "Work Shift": "Others",
    "Gender": "Any",
    "Schedule Type (Office or Shift)": "Any",
    "Schedule Policy": "[PHL] Shift Schedule policy",
    "Overtime Requests": "Pre-approval OT Request",
    "Overtime Request Approval Paths": "PHL OT Approval",
    "Timesheet Template": "PHL In/Out JL 10 - 14",
    "Timesheet Approval": "Supervisor for OT",
    "Timesheet Period": "Weekly - Starting Monday - ES employees and Contractors",
    "Time Off Template": "Time Off",
    "Time Off Approval": "PHL Approval Path",
    "Payrule": "Custom Philippines",
    "Time Off Types": "Refer to Time off Mapping sheet",
    "Time Zone": "(UTC+8:00) North Asia East Standard Time",
    "Work Week": "Monday to Sunday",
    "Holiday Calendar": "refer to holiday calendar sheet",
    "Authentication Type": "SSO",
    "Activities": "Refer to ES activity list sheet",
    "Time Entry Approval Path": "System",
    "Product": "",
    "Product URI": ""
  },
  {
    "Company Code": "PHES",
    "Personnel Sub Area Code": "Any",
    "SubGroup": "Any",
    "Industrial_Instrument_Classification": "Any",
    "Job level": 14,
    "Location": "Philippines",
    "Work Shift": "Others",
    "Gender": "Any",
    "Schedule Type (Office or Shift)": "Any",
    "Schedule Policy": "[PHL] Shift Schedule policy",
    "Overtime Requests": "Pre-approval OT Request",
    "Overtime Request Approval Paths": "PHL OT Approval",
    "Timesheet Template": "PHL In/Out JL 10 - 14",
    "Timesheet Approval": "Supervisor for OT",
    "Timesheet Period": "Weekly - Starting Monday - ES employees and Contractors",
    "Time Off Template": "Time Off",
    "Time Off Approval": "PHL Approval Path",
    "Payrule": "Custom Philippines",
    "Time Off Types": "Refer to Time off Mapping sheet",
    "Time Zone": "(UTC+8:00) North Asia East Standard Time",
    "Work Week": "Monday to Sunday",
    "Holiday Calendar": "refer to holiday calendar sheet",
    "Authentication Type": "SSO",
    "Activities": "Refer to ES activity list sheet",
    "Time Entry Approval Path": "System",
    "Product": "",
    "Product URI": ""
  },
  {
    "Company Code": "PHET",
    "Personnel Sub Area Code": "Any",
    "SubGroup": "Any",
    "Industrial_Instrument_Classification": "Any",
    "Job level": 14,
    "Location": "Philippines",
    "Work Shift": "Others",
    "Gender": "Any",
    "Schedule Type (Office or Shift)": "Any",
    "Schedule Policy": "[PHL] Shift Schedule policy",
    "Overtime Requests": "Pre-approval OT Request",
    "Overtime Request Approval Paths": "PHL OT Approval",
    "Timesheet Template": "PHL In/Out JL 10 - 14",
    "Timesheet Approval": "Supervisor for OT",
    "Timesheet Period": "Weekly - Starting Monday - ES employees and Contractors",
    "Time Off Template": "Time Off",
    "Time Off Approval": "PHL Approval Path",
    "Payrule": "Custom Philippines",
    "Time Off Types": "Refer to Time off Mapping sheet",
    "Time Zone": "(UTC+8:00) North Asia East Standard Time",
    "Work Week": "Monday to Sunday",
    "Holiday Calendar": "refer to holiday calendar sheet",
    "Authentication Type": "SSO",
    "Activities": "Refer to ES activity list sheet",
    "Time Entry Approval Path": "System",
    "Product": "",
    "Product URI": ""
  },
  {
    "Company Code": "PHES",
    "Personnel Sub Area Code": "Any",
    "SubGroup": "Any",
    "Industrial_Instrument_Classification": "Any",
    "Job level": 15,
    "Location": "Philippines",
    "Work Shift": "Others",
    "Gender": "Any",
    "Schedule Type (Office or Shift)": "Any",
    "Schedule Policy": "[PHL] Shift Schedule policy",
    "Overtime Requests": "Pre-approval OT Request",
    "Overtime Request Approval Paths": "PHL OT Approval",
    "Timesheet Template": "PHL In/Out JL 15",
    "Timesheet Approval": "Supervisor for OT",
    "Timesheet Period": "Weekly - Starting Monday - ES employees and Contractors",
    "Time Off Template": "Time Off",
    "Time Off Approval": "PHL Approval Path",
    "Payrule": "Custom Philippines",
    "Time Off Types": "Refer to Time off Mapping sheet",
    "Time Zone": "(UTC+8:00) North Asia East Standard Time",
    "Work Week": "Monday to Sunday",
    "Holiday Calendar": "refer to holiday calendar sheet",
    "Authentication Type": "SSO",
    "Activities": "Refer to ES activity list sheet",
    "Time Entry Approval Path": "System",
    "Product": "",
    "Product URI": ""
  },
  {
    "Company Code": "PHET",
    "Personnel Sub Area Code": "Any",
    "SubGroup": "Any",
    "Industrial_Instrument_Classification": "Any",
    "Job level": 15,
    "Location": "Philippines",
    "Work Shift": "Others",
    "Gender": "Any",
    "Schedule Type (Office or Shift)": "Any",
    "Schedule Policy": "[PHL] Shift Schedule policy",
    "Overtime Requests": "Pre-approval OT Request",
    "Overtime Request Approval Paths": "PHL OT Approval",
    "Timesheet Template": "PHL In/Out JL 15",
    "Timesheet Approval": "Supervisor for OT",
    "Timesheet Period": "Weekly - Starting Monday - ES employees and Contractors",
    "Time Off Template": "Time Off",
    "Time Off Approval": "PHL Approval Path",
    "Payrule": "Custom Philippines",
    "Time Off Types": "Refer to Time off Mapping sheet",
    "Time Zone": "(UTC+8:00) North Asia East Standard Time",
    "Work Week": "Monday to Sunday",
    "Holiday Calendar": "refer to holiday calendar sheet",
    "Authentication Type": "SSO",
    "Activities": "Refer to ES activity list sheet",
    "Time Entry Approval Path": "System",
    "Product": "",
    "Product URI": ""
  },
  {
    "Company Code": "PHES",
    "Personnel Sub Area Code": "Any",
    "SubGroup": "Any",
    "Industrial_Instrument_Classification": "Any",
    "Job level": 8,
    "Location": "Philippines",
    "Work Shift": "ES - BPS GSD Shift (Philippines)",
    "Gender": "Any",
    "Schedule Type (Office or Shift)": "Any",
    "Schedule Policy": "[PHL] Shift Schedule policy",
    "Overtime Requests": "Pre-approval extra time request",
    "Overtime Request Approval Paths": "PHL OT Approval",
    "Timesheet Template": "PHL In/Out JL 8-9 BPS GSD",
    "Timesheet Approval": "Supervisor for OT",
    "Timesheet Period": "Weekly - Starting Monday - ES employees and Contractors",
    "Time Off Template": "Time Off",
    "Time Off Approval": "PHL Approval Path",
    "Payrule": "Custom Philippines",
    "Time Off Types": "Refer to Time off Mapping sheet",
    "Time Zone": "(UTC+8:00) North Asia East Standard Time",
    "Work Week": "Monday to Sunday",
    "Holiday Calendar": "refer to holiday calendar sheet",
    "Authentication Type": "SSO",
    "Activities": "Refer to ES activity list sheet",
    "Time Entry Approval Path": "System",
    "Product": "",
    "Product URI": ""
  },
  {
    "Company Code": "PHET",
    "Personnel Sub Area Code": "Any",
    "SubGroup": "Any",
    "Industrial_Instrument_Classification": "Any",
    "Job level": 8,
    "Location": "Philippines",
    "Work Shift": "ES - BPS GSD Shift (Philippines)",
    "Gender": "Any",
    "Schedule Type (Office or Shift)": "Any",
    "Schedule Policy": "[PHL] Shift Schedule policy",
    "Overtime Requests": "Pre-approval extra time request",
    "Overtime Request Approval Paths": "PHL OT Approval",
    "Timesheet Template": "PHL In/Out JL 8-9 BPS GSD",
    "Timesheet Approval": "Supervisor for OT",
    "Timesheet Period": "Weekly - Starting Monday - ES employees and Contractors",
    "Time Off Template": "Time Off",
    "Time Off Approval": "PHL Approval Path",
    "Payrule": "Custom Philippines",
    "Time Off Types": "Refer to Time off Mapping sheet",
    "Time Zone": "(UTC+8:00) North Asia East Standard Time",
    "Work Week": "Monday to Sunday",
    "Holiday Calendar": "refer to holiday calendar sheet",
    "Authentication Type": "SSO",
    "Activities": "Refer to ES activity list sheet",
    "Time Entry Approval Path": "System",
    "Product": "",
    "Product URI": ""
  },
  {
    "Company Code": "PHES",
    "Personnel Sub Area Code": "Any",
    "SubGroup": "Any",
    "Industrial_Instrument_Classification": "Any",
    "Job level": 9,
    "Location": "Philippines",
    "Work Shift": "ES - BPS GSD Shift (Philippines)",
    "Gender": "Any",
    "Schedule Type (Office or Shift)": "Any",
    "Schedule Policy": "[PHL] Shift Schedule policy",
    "Overtime Requests": "Pre-approval extra time request",
    "Overtime Request Approval Paths": "PHL OT Approval",
    "Timesheet Template": "PHL In/Out JL 8-9 BPS GSD",
    "Timesheet Approval": "Supervisor for OT",
    "Timesheet Period": "Weekly - Starting Monday - ES employees and Contractors",
    "Time Off Template": "Time Off",
    "Time Off Approval": "PHL Approval Path",
    "Payrule": "Custom Philippines",
    "Time Off Types": "Refer to Time off Mapping sheet",
    "Time Zone": "(UTC+8:00) North Asia East Standard Time",
    "Work Week": "Monday to Sunday",
    "Holiday Calendar": "refer to holiday calendar sheet",
    "Authentication Type": "SSO",
    "Activities": "Refer to ES activity list sheet",
    "Time Entry Approval Path": "System",
    "Product": "",
    "Product URI": ""
  },
  {
    "Company Code": "PHET",
    "Personnel Sub Area Code": "Any",
    "SubGroup": "Any",
    "Industrial_Instrument_Classification": "Any",
    "Job level": 9,
    "Location": "Philippines",
    "Work Shift": "ES - BPS GSD Shift (Philippines)",
    "Gender": "Any",
    "Schedule Type (Office or Shift)": "Any",
    "Schedule Policy": "[PHL] Shift Schedule policy",
    "Overtime Requests": "Pre-approval extra time request",
    "Overtime Request Approval Paths": "PHL OT Approval",
    "Timesheet Template": "PHL In/Out JL 8-9 BPS GSD",
    "Timesheet Approval": "Supervisor for OT",
    "Timesheet Period": "Weekly - Starting Monday - ES employees and Contractors",
    "Time Off Template": "Time Off",
    "Time Off Approval": "PHL Approval Path",
    "Payrule": "Custom Philippines",
    "Time Off Types": "Refer to Time off Mapping sheet",
    "Time Zone": "(UTC+8:00) North Asia East Standard Time",
    "Work Week": "Monday to Sunday",
    "Holiday Calendar": "refer to holiday calendar sheet",
    "Authentication Type": "SSO",
    "Activities": "Refer to ES activity list sheet",
    "Time Entry Approval Path": "System",
    "Product": "",
    "Product URI": ""
  },
  {
    "Company Code": "PHES",
    "Personnel Sub Area Code": "Any",
    "SubGroup": "Any",
    "Industrial_Instrument_Classification": "Any",
    "Job level": 8,
    "Location": "Philippines",
    "Work Shift": "ES - BPS GSD Compressed Workweek (Philippines)",
    "Gender": "Any",
    "Schedule Type (Office or Shift)": "Any",
    "Schedule Policy": "[PHL] Shift Schedule policy",
    "Overtime Requests": "Pre-approval extra time request",
    "Overtime Request Approval Paths": "PHL OT Approval",
    "Timesheet Template": "PHL In/Out JL 8-9 BPS GSD",
    "Timesheet Approval": "Supervisor for OT",
    "Timesheet Period": "Weekly - Starting Monday - ES employees and Contractors",
    "Time Off Template": "Time Off",
    "Time Off Approval": "PHL Approval Path",
    "Payrule": "Custom Philippines",
    "Time Off Types": "Refer to Time off Mapping sheet",
    "Time Zone": "(UTC+8:00) North Asia East Standard Time",
    "Work Week": "Monday to Sunday",
    "Holiday Calendar": "refer to holiday calendar sheet",
    "Authentication Type": "SSO",
    "Activities": "Refer to ES activity list sheet",
    "Time Entry Approval Path": "System",
    "Product": "",
    "Product URI": ""
  },
  {
    "Company Code": "PHET",
    "Personnel Sub Area Code": "Any",
    "SubGroup": "Any",
    "Industrial_Instrument_Classification": "Any",
    "Job level": 8,
    "Location": "Philippines",
    "Work Shift": "ES - BPS GSD Compressed Workweek (Philippines)",
    "Gender": "Any",
    "Schedule Type (Office or Shift)": "Any",
    "Schedule Policy": "[PHL] Shift Schedule policy",
    "Overtime Requests": "Pre-approval extra time request",
    "Overtime Request Approval Paths": "PHL OT Approval",
    "Timesheet Template": "PHL In/Out JL 8-9 BPS GSD",
    "Timesheet Approval": "Supervisor for OT",
    "Timesheet Period": "Weekly - Starting Monday - ES employees and Contractors",
    "Time Off Template": "Time Off",
    "Time Off Approval": "PHL Approval Path",
    "Payrule": "Custom Philippines",
    "Time Off Types": "Refer to Time off Mapping sheet",
    "Time Zone": "(UTC+8:00) North Asia East Standard Time",
    "Work Week": "Monday to Sunday",
    "Holiday Calendar": "refer to holiday calendar sheet",
    "Authentication Type": "SSO",
    "Activities": "Refer to ES activity list sheet",
    "Time Entry Approval Path": "System",
    "Product": "",
    "Product URI": ""
  },
  {
    "Company Code": "PHES",
    "Personnel Sub Area Code": "Any",
    "SubGroup": "Any",
    "Industrial_Instrument_Classification": "Any",
    "Job level": 9,
    "Location": "Philippines",
    "Work Shift": "ES - BPS GSD Compressed Workweek (Philippines)",
    "Gender": "Any",
    "Schedule Type (Office or Shift)": "Any",
    "Schedule Policy": "[PHL] Shift Schedule policy",
    "Overtime Requests": "Pre-approval extra time request",
    "Overtime Request Approval Paths": "PHL OT Approval",
    "Timesheet Template": "PHL In/Out JL 8-9 BPS GSD",
    "Timesheet Approval": "Supervisor for OT",
    "Timesheet Period": "Weekly - Starting Monday - ES employees and Contractors",
    "Time Off Template": "Time Off",
    "Time Off Approval": "PHL Approval Path",
    "Payrule": "Custom Philippines",
    "Time Off Types": "Refer to Time off Mapping sheet",
    "Time Zone": "(UTC+8:00) North Asia East Standard Time",
    "Work Week": "Monday to Sunday",
    "Holiday Calendar": "refer to holiday calendar sheet",
    "Authentication Type": "SSO",
    "Activities": "Refer to ES activity list sheet",
    "Time Entry Approval Path": "System",
    "Product": "",
    "Product URI": ""
  },
  {
    "Company Code": "PHET",
    "Personnel Sub Area Code": "Any",
    "SubGroup": "Any",
    "Industrial_Instrument_Classification": "Any",
    "Job level": 9,
    "Location": "Philippines",
    "Work Shift": "ES - BPS GSD Compressed Workweek (Philippines)",
    "Gender": "Any",
    "Schedule Type (Office or Shift)": "Any",
    "Schedule Policy": "[PHL] Shift Schedule policy",
    "Overtime Requests": "Pre-approval extra time request",
    "Overtime Request Approval Paths": "PHL OT Approval",
    "Timesheet Template": "PHL In/Out JL 8-9 BPS GSD",
    "Timesheet Approval": "Supervisor for OT",
    "Timesheet Period": "Weekly - Starting Monday - ES employees and Contractors",
    "Time Off Template": "Time Off",
    "Time Off Approval": "PHL Approval Path",
    "Payrule": "Custom Philippines",
    "Time Off Types": "Refer to Time off Mapping sheet",
    "Time Zone": "(UTC+8:00) North Asia East Standard Time",
    "Work Week": "Monday to Sunday",
    "Holiday Calendar": "refer to holiday calendar sheet",
    "Authentication Type": "SSO",
    "Activities": "Refer to ES activity list sheet",
    "Time Entry Approval Path": "System",
    "Product": "",
    "Product URI": ""
  },
  {
    "Company Code": "PHES",
    "Personnel Sub Area Code": "Any",
    "SubGroup": "Any",
    "Industrial_Instrument_Classification": "Any",
    "Job level": 10,
    "Location": "Philippines",
    "Work Shift": "ES - BPS GSD Shift (Philippines)",
    "Gender": "Any",
    "Schedule Type (Office or Shift)": "Shift",
    "Schedule Policy": "[PHL] Shift Schedule policy",
    "Overtime Requests": "Pre-approval OT Request",
    "Overtime Request Approval Paths": "PHL OT Approval",
    "Timesheet Template": "PHL In/Out JL 10 - 14 BPS GSD",
    "Timesheet Approval": "Supervisor for OT",
    "Timesheet Period": "Weekly - Starting Monday - ES employees and Contractors",
    "Time Off Template": "Time Off",
    "Time Off Approval": "PHL Approval Path",
    "Payrule": "Custom Philippines",
    "Time Off Types": "Refer to Time off Mapping sheet",
    "Time Zone": "(UTC+8:00) North Asia East Standard Time",
    "Work Week": "Monday to Sunday",
    "Holiday Calendar": "refer to holiday calendar sheet",
    "Authentication Type": "SSO",
    "Activities": "Refer to ES activity list sheet",
    "Time Entry Approval Path": "System",
    "Product": "",
    "Product URI": ""
  },
  {
    "Company Code": "PHET",
    "Personnel Sub Area Code": "Any",
    "SubGroup": "Any",
    "Industrial_Instrument_Classification": "Any",
    "Job level": 10,
    "Location": "Philippines",
    "Work Shift": "ES - BPS GSD Shift (Philippines)",
    "Gender": "Any",
    "Schedule Type (Office or Shift)": "Shift",
    "Schedule Policy": "[PHL] Shift Schedule policy",
    "Overtime Requests": "Pre-approval OT Request",
    "Overtime Request Approval Paths": "PHL OT Approval",
    "Timesheet Template": "PHL In/Out JL 10 - 14 BPS GSD",
    "Timesheet Approval": "Supervisor for OT",
    "Timesheet Period": "Weekly - Starting Monday - ES employees and Contractors",
    "Time Off Template": "Time Off",
    "Time Off Approval": "PHL Approval Path",
    "Payrule": "Custom Philippines",
    "Time Off Types": "Refer to Time off Mapping sheet",
    "Time Zone": "(UTC+8:00) North Asia East Standard Time",
    "Work Week": "Monday to Sunday",
    "Holiday Calendar": "refer to holiday calendar sheet",
    "Authentication Type": "SSO",
    "Activities": "Refer to ES activity list sheet",
    "Time Entry Approval Path": "System",
    "Product": "",
    "Product URI": ""
  },
  {
    "Company Code": "PHES",
    "Personnel Sub Area Code": "Any",
    "SubGroup": "Any",
    "Industrial_Instrument_Classification": "Any",
    "Job level": 11,
    "Location": "Philippines",
    "Work Shift": "ES - BPS GSD Shift (Philippines)",
    "Gender": "Any",
    "Schedule Type (Office or Shift)": "Shift",
    "Schedule Policy": "[PHL] Shift Schedule policy",
    "Overtime Requests": "Pre-approval OT Request",
    "Overtime Request Approval Paths": "PHL OT Approval",
    "Timesheet Template": "PHL In/Out JL 10 - 14 BPS GSD",
    "Timesheet Approval": "Supervisor for OT",
    "Timesheet Period": "Weekly - Starting Monday - ES employees and Contractors",
    "Time Off Template": "Time Off",
    "Time Off Approval": "PHL Approval Path",
    "Payrule": "Custom Philippines",
    "Time Off Types": "Refer to Time off Mapping sheet",
    "Time Zone": "(UTC+8:00) North Asia East Standard Time",
    "Work Week": "Monday to Sunday",
    "Holiday Calendar": "refer to holiday calendar sheet",
    "Authentication Type": "SSO",
    "Activities": "Refer to ES activity list sheet",
    "Time Entry Approval Path": "System",
    "Product": "",
    "Product URI": ""
  },
  {
    "Company Code": "PHET",
    "Personnel Sub Area Code": "Any",
    "SubGroup": "Any",
    "Industrial_Instrument_Classification": "Any",
    "Job level": 11,
    "Location": "Philippines",
    "Work Shift": "ES - BPS GSD Shift (Philippines)",
    "Gender": "Any",
    "Schedule Type (Office or Shift)": "Shift",
    "Schedule Policy": "[PHL] Shift Schedule policy",
    "Overtime Requests": "Pre-approval OT Request",
    "Overtime Request Approval Paths": "PHL OT Approval",
    "Timesheet Template": "PHL In/Out JL 10 - 14 BPS GSD",
    "Timesheet Approval": "Supervisor for OT",
    "Timesheet Period": "Weekly - Starting Monday - ES employees and Contractors",
    "Time Off Template": "Time Off",
    "Time Off Approval": "PHL Approval Path",
    "Payrule": "Custom Philippines",
    "Time Off Types": "Refer to Time off Mapping sheet",
    "Time Zone": "(UTC+8:00) North Asia East Standard Time",
    "Work Week": "Monday to Sunday",
    "Holiday Calendar": "refer to holiday calendar sheet",
    "Authentication Type": "SSO",
    "Activities": "Refer to ES activity list sheet",
    "Time Entry Approval Path": "System",
    "Product": "",
    "Product URI": ""
  },
  {
    "Company Code": "PHES",
    "Personnel Sub Area Code": "Any",
    "SubGroup": "Any",
    "Industrial_Instrument_Classification": "Any",
    "Job level": 12,
    "Location": "Philippines",
    "Work Shift": "ES - BPS GSD Shift (Philippines)",
    "Gender": "Any",
    "Schedule Type (Office or Shift)": "Shift",
    "Schedule Policy": "[PHL] Shift Schedule policy",
    "Overtime Requests": "Pre-approval OT Request",
    "Overtime Request Approval Paths": "PHL OT Approval",
    "Timesheet Template": "PHL In/Out JL 10 - 14 BPS GSD",
    "Timesheet Approval": "Supervisor for OT",
    "Timesheet Period": "Weekly - Starting Monday - ES employees and Contractors",
    "Time Off Template": "Time Off",
    "Time Off Approval": "PHL Approval Path",
    "Payrule": "Custom Philippines",
    "Time Off Types": "Refer to Time off Mapping sheet",
    "Time Zone": "(UTC+8:00) North Asia East Standard Time",
    "Work Week": "Monday to Sunday",
    "Holiday Calendar": "refer to holiday calendar sheet",
    "Authentication Type": "SSO",
    "Activities": "Refer to ES activity list sheet",
    "Time Entry Approval Path": "System",
    "Product": "",
    "Product URI": ""
  },
  {
    "Company Code": "PHET",
    "Personnel Sub Area Code": "Any",
    "SubGroup": "Any",
    "Industrial_Instrument_Classification": "Any",
    "Job level": 12,
    "Location": "Philippines",
    "Work Shift": "ES - BPS GSD Shift (Philippines)",
    "Gender": "Any",
    "Schedule Type (Office or Shift)": "Shift",
    "Schedule Policy": "[PHL] Shift Schedule policy",
    "Overtime Requests": "Pre-approval OT Request",
    "Overtime Request Approval Paths": "PHL OT Approval",
    "Timesheet Template": "PHL In/Out JL 10 - 14 BPS GSD",
    "Timesheet Approval": "Supervisor for OT",
    "Timesheet Period": "Weekly - Starting Monday - ES employees and Contractors",
    "Time Off Template": "Time Off",
    "Time Off Approval": "PHL Approval Path",
    "Payrule": "Custom Philippines",
    "Time Off Types": "Refer to Time off Mapping sheet",
    "Time Zone": "(UTC+8:00) North Asia East Standard Time",
    "Work Week": "Monday to Sunday",
    "Holiday Calendar": "refer to holiday calendar sheet",
    "Authentication Type": "SSO",
    "Activities": "Refer to ES activity list sheet",
    "Time Entry Approval Path": "System",
    "Product": "",
    "Product URI": ""
  },
  {
    "Company Code": "PHES",
    "Personnel Sub Area Code": "Any",
    "SubGroup": "Any",
    "Industrial_Instrument_Classification": "Any",
    "Job level": 13,
    "Location": "Philippines",
    "Work Shift": "ES - BPS GSD Shift (Philippines)",
    "Gender": "Any",
    "Schedule Type (Office or Shift)": "Shift",
    "Schedule Policy": "[PHL] Shift Schedule policy",
    "Overtime Requests": "Pre-approval OT Request",
    "Overtime Request Approval Paths": "PHL OT Approval",
    "Timesheet Template": "PHL In/Out JL 10 - 14 BPS GSD",
    "Timesheet Approval": "Supervisor for OT",
    "Timesheet Period": "Weekly - Starting Monday - ES employees and Contractors",
    "Time Off Template": "Time Off",
    "Time Off Approval": "PHL Approval Path",
    "Payrule": "Custom Philippines",
    "Time Off Types": "Refer to Time off Mapping sheet",
    "Time Zone": "(UTC+8:00) North Asia East Standard Time",
    "Work Week": "Monday to Sunday",
    "Holiday Calendar": "refer to holiday calendar sheet",
    "Authentication Type": "SSO",
    "Activities": "Refer to ES activity list sheet",
    "Time Entry Approval Path": "System",
    "Product": "",
    "Product URI": ""
  },
  {
    "Company Code": "PHET",
    "Personnel Sub Area Code": "Any",
    "SubGroup": "Any",
    "Industrial_Instrument_Classification": "Any",
    "Job level": 13,
    "Location": "Philippines",
    "Work Shift": "ES - BPS GSD Shift (Philippines)",
    "Gender": "Any",
    "Schedule Type (Office or Shift)": "Shift",
    "Schedule Policy": "[PHL] Shift Schedule policy",
    "Overtime Requests": "Pre-approval OT Request",
    "Overtime Request Approval Paths": "PHL OT Approval",
    "Timesheet Template": "PHL In/Out JL 10 - 14 BPS GSD",
    "Timesheet Approval": "Supervisor for OT",
    "Timesheet Period": "Weekly - Starting Monday - ES employees and Contractors",
    "Time Off Template": "Time Off",
    "Time Off Approval": "PHL Approval Path",
    "Payrule": "Custom Philippines",
    "Time Off Types": "Refer to Time off Mapping sheet",
    "Time Zone": "(UTC+8:00) North Asia East Standard Time",
    "Work Week": "Monday to Sunday",
    "Holiday Calendar": "refer to holiday calendar sheet",
    "Authentication Type": "SSO",
    "Activities": "Refer to ES activity list sheet",
    "Time Entry Approval Path": "System",
    "Product": "",
    "Product URI": ""
  },
  {
    "Company Code": "PHES",
    "Personnel Sub Area Code": "Any",
    "SubGroup": "Any",
    "Industrial_Instrument_Classification": "Any",
    "Job level": 14,
    "Location": "Philippines",
    "Work Shift": "ES - BPS GSD Shift (Philippines)",
    "Gender": "Any",
    "Schedule Type (Office or Shift)": "Shift",
    "Schedule Policy": "[PHL] Shift Schedule policy",
    "Overtime Requests": "Pre-approval OT Request",
    "Overtime Request Approval Paths": "PHL OT Approval",
    "Timesheet Template": "PHL In/Out JL 10 - 14 BPS GSD",
    "Timesheet Approval": "Supervisor for OT",
    "Timesheet Period": "Weekly - Starting Monday - ES employees and Contractors",
    "Time Off Template": "Time Off",
    "Time Off Approval": "PHL Approval Path",
    "Payrule": "Custom Philippines",
    "Time Off Types": "Refer to Time off Mapping sheet",
    "Time Zone": "(UTC+8:00) North Asia East Standard Time",
    "Work Week": "Monday to Sunday",
    "Holiday Calendar": "refer to holiday calendar sheet",
    "Authentication Type": "SSO",
    "Activities": "Refer to ES activity list sheet",
    "Time Entry Approval Path": "System",
    "Product": "",
    "Product URI": ""
  },
  {
    "Company Code": "PHET",
    "Personnel Sub Area Code": "Any",
    "SubGroup": "Any",
    "Industrial_Instrument_Classification": "Any",
    "Job level": 14,
    "Location": "Philippines",
    "Work Shift": "ES - BPS GSD Shift (Philippines)",
    "Gender": "Any",
    "Schedule Type (Office or Shift)": "Shift",
    "Schedule Policy": "[PHL] Shift Schedule policy",
    "Overtime Requests": "Pre-approval OT Request",
    "Overtime Request Approval Paths": "PHL OT Approval",
    "Timesheet Template": "PHL In/Out JL 10 - 14 BPS GSD",
    "Timesheet Approval": "Supervisor for OT",
    "Timesheet Period": "Weekly - Starting Monday - ES employees and Contractors",
    "Time Off Template": "Time Off",
    "Time Off Approval": "PHL Approval Path",
    "Payrule": "Custom Philippines",
    "Time Off Types": "Refer to Time off Mapping sheet",
    "Time Zone": "(UTC+8:00) North Asia East Standard Time",
    "Work Week": "Monday to Sunday",
    "Holiday Calendar": "refer to holiday calendar sheet",
    "Authentication Type": "SSO",
    "Activities": "Refer to ES activity list sheet",
    "Time Entry Approval Path": "System",
    "Product": "",
    "Product URI": ""
  },
  {
    "Company Code": "PHES",
    "Personnel Sub Area Code": "Any",
    "SubGroup": "Any",
    "Industrial_Instrument_Classification": "Any",
    "Job level": 10,
    "Location": "Philippines",
    "Work Shift": "ES - BPS GSD Compressed Workweek (Philippines)",
    "Gender": "Any",
    "Schedule Type (Office or Shift)": "Shift",
    "Schedule Policy": "[PHL] Shift Schedule policy",
    "Overtime Requests": "Pre-approval OT Request",
    "Overtime Request Approval Paths": "PHL OT Approval",
    "Timesheet Template": "PHL In/Out JL 10 - 14 BPS GSD",
    "Timesheet Approval": "Supervisor for OT",
    "Timesheet Period": "Weekly - Starting Monday - ES employees and Contractors",
    "Time Off Template": "Time Off",
    "Time Off Approval": "PHL Approval Path",
    "Payrule": "Custom Philippines",
    "Time Off Types": "Refer to Time off Mapping sheet",
    "Time Zone": "(UTC+8:00) North Asia East Standard Time",
    "Work Week": "Monday to Sunday",
    "Holiday Calendar": "refer to holiday calendar sheet",
    "Authentication Type": "SSO",
    "Activities": "Refer to ES activity list sheet",
    "Time Entry Approval Path": "System",
    "Product": "",
    "Product URI": ""
  },
  {
    "Company Code": "PHET",
    "Personnel Sub Area Code": "Any",
    "SubGroup": "Any",
    "Industrial_Instrument_Classification": "Any",
    "Job level": 10,
    "Location": "Philippines",
    "Work Shift": "ES - BPS GSD Compressed Workweek (Philippines)",
    "Gender": "Any",
    "Schedule Type (Office or Shift)": "Shift",
    "Schedule Policy": "[PHL] Shift Schedule policy",
    "Overtime Requests": "Pre-approval OT Request",
    "Overtime Request Approval Paths": "PHL OT Approval",
    "Timesheet Template": "PHL In/Out JL 10 - 14 BPS GSD",
    "Timesheet Approval": "Supervisor for OT",
    "Timesheet Period": "Weekly - Starting Monday - ES employees and Contractors",
    "Time Off Template": "Time Off",
    "Time Off Approval": "PHL Approval Path",
    "Payrule": "Custom Philippines",
    "Time Off Types": "Refer to Time off Mapping sheet",
    "Time Zone": "(UTC+8:00) North Asia East Standard Time",
    "Work Week": "Monday to Sunday",
    "Holiday Calendar": "refer to holiday calendar sheet",
    "Authentication Type": "SSO",
    "Activities": "Refer to ES activity list sheet",
    "Time Entry Approval Path": "System",
    "Product": "",
    "Product URI": ""
  },
  {
    "Company Code": "PHES",
    "Personnel Sub Area Code": "Any",
    "SubGroup": "Any",
    "Industrial_Instrument_Classification": "Any",
    "Job level": 11,
    "Location": "Philippines",
    "Work Shift": "ES - BPS GSD Compressed Workweek (Philippines)",
    "Gender": "Any",
    "Schedule Type (Office or Shift)": "Shift",
    "Schedule Policy": "[PHL] Shift Schedule policy",
    "Overtime Requests": "Pre-approval OT Request",
    "Overtime Request Approval Paths": "PHL OT Approval",
    "Timesheet Template": "PHL In/Out JL 10 - 14 BPS GSD",
    "Timesheet Approval": "Supervisor for OT",
    "Timesheet Period": "Weekly - Starting Monday - ES employees and Contractors",
    "Time Off Template": "Time Off",
    "Time Off Approval": "PHL Approval Path",
    "Payrule": "Custom Philippines",
    "Time Off Types": "Refer to Time off Mapping sheet",
    "Time Zone": "(UTC+8:00) North Asia East Standard Time",
    "Work Week": "Monday to Sunday",
    "Holiday Calendar": "refer to holiday calendar sheet",
    "Authentication Type": "SSO",
    "Activities": "Refer to ES activity list sheet",
    "Time Entry Approval Path": "System",
    "Product": "",
    "Product URI": ""
  },
  {
    "Company Code": "PHET",
    "Personnel Sub Area Code": "Any",
    "SubGroup": "Any",
    "Industrial_Instrument_Classification": "Any",
    "Job level": 11,
    "Location": "Philippines",
    "Work Shift": "ES - BPS GSD Compressed Workweek (Philippines)",
    "Gender": "Any",
    "Schedule Type (Office or Shift)": "Shift",
    "Schedule Policy": "[PHL] Shift Schedule policy",
    "Overtime Requests": "Pre-approval OT Request",
    "Overtime Request Approval Paths": "PHL OT Approval",
    "Timesheet Template": "PHL In/Out JL 10 - 14 BPS GSD",
    "Timesheet Approval": "Supervisor for OT",
    "Timesheet Period": "Weekly - Starting Monday - ES employees and Contractors",
    "Time Off Template": "Time Off",
    "Time Off Approval": "PHL Approval Path",
    "Payrule": "Custom Philippines",
    "Time Off Types": "Refer to Time off Mapping sheet",
    "Time Zone": "(UTC+8:00) North Asia East Standard Time",
    "Work Week": "Monday to Sunday",
    "Holiday Calendar": "refer to holiday calendar sheet",
    "Authentication Type": "SSO",
    "Activities": "Refer to ES activity list sheet",
    "Time Entry Approval Path": "System",
    "Product": "",
    "Product URI": ""
  },
  {
    "Company Code": "PHES",
    "Personnel Sub Area Code": "Any",
    "SubGroup": "Any",
    "Industrial_Instrument_Classification": "Any",
    "Job level": 12,
    "Location": "Philippines",
    "Work Shift": "ES - BPS GSD Compressed Workweek (Philippines)",
    "Gender": "Any",
    "Schedule Type (Office or Shift)": "Shift",
    "Schedule Policy": "[PHL] Shift Schedule policy",
    "Overtime Requests": "Pre-approval OT Request",
    "Overtime Request Approval Paths": "PHL OT Approval",
    "Timesheet Template": "PHL In/Out JL 10 - 14 BPS GSD",
    "Timesheet Approval": "Supervisor for OT",
    "Timesheet Period": "Weekly - Starting Monday - ES employees and Contractors",
    "Time Off Template": "Time Off",
    "Time Off Approval": "PHL Approval Path",
    "Payrule": "Custom Philippines",
    "Time Off Types": "Refer to Time off Mapping sheet",
    "Time Zone": "(UTC+8:00) North Asia East Standard Time",
    "Work Week": "Monday to Sunday",
    "Holiday Calendar": "refer to holiday calendar sheet",
    "Authentication Type": "SSO",
    "Activities": "Refer to ES activity list sheet",
    "Time Entry Approval Path": "System",
    "Product": "",
    "Product URI": ""
  },
  {
    "Company Code": "PHET",
    "Personnel Sub Area Code": "Any",
    "SubGroup": "Any",
    "Industrial_Instrument_Classification": "Any",
    "Job level": 12,
    "Location": "Philippines",
    "Work Shift": "ES - BPS GSD Compressed Workweek (Philippines)",
    "Gender": "Any",
    "Schedule Type (Office or Shift)": "Shift",
    "Schedule Policy": "[PHL] Shift Schedule policy",
    "Overtime Requests": "Pre-approval OT Request",
    "Overtime Request Approval Paths": "PHL OT Approval",
    "Timesheet Template": "PHL In/Out JL 10 - 14 BPS GSD",
    "Timesheet Approval": "Supervisor for OT",
    "Timesheet Period": "Weekly - Starting Monday - ES employees and Contractors",
    "Time Off Template": "Time Off",
    "Time Off Approval": "PHL Approval Path",
    "Payrule": "Custom Philippines",
    "Time Off Types": "Refer to Time off Mapping sheet",
    "Time Zone": "(UTC+8:00) North Asia East Standard Time",
    "Work Week": "Monday to Sunday",
    "Holiday Calendar": "refer to holiday calendar sheet",
    "Authentication Type": "SSO",
    "Activities": "Refer to ES activity list sheet",
    "Time Entry Approval Path": "System",
    "Product": "",
    "Product URI": ""
  },
  {
    "Company Code": "PHES",
    "Personnel Sub Area Code": "Any",
    "SubGroup": "Any",
    "Industrial_Instrument_Classification": "Any",
    "Job level": 13,
    "Location": "Philippines",
    "Work Shift": "ES - BPS GSD Compressed Workweek (Philippines)",
    "Gender": "Any",
    "Schedule Type (Office or Shift)": "Shift",
    "Schedule Policy": "[PHL] Shift Schedule policy",
    "Overtime Requests": "Pre-approval OT Request",
    "Overtime Request Approval Paths": "PHL OT Approval",
    "Timesheet Template": "PHL In/Out JL 10 - 14 BPS GSD",
    "Timesheet Approval": "Supervisor for OT",
    "Timesheet Period": "Weekly - Starting Monday - ES employees and Contractors",
    "Time Off Template": "Time Off",
    "Time Off Approval": "PHL Approval Path",
    "Payrule": "Custom Philippines",
    "Time Off Types": "Refer to Time off Mapping sheet",
    "Time Zone": "(UTC+8:00) North Asia East Standard Time",
    "Work Week": "Monday to Sunday",
    "Holiday Calendar": "refer to holiday calendar sheet",
    "Authentication Type": "SSO",
    "Activities": "Refer to ES activity list sheet",
    "Time Entry Approval Path": "System",
    "Product": "",
    "Product URI": ""
  },
  {
    "Company Code": "PHET",
    "Personnel Sub Area Code": "Any",
    "SubGroup": "Any",
    "Industrial_Instrument_Classification": "Any",
    "Job level": 13,
    "Location": "Philippines",
    "Work Shift": "ES - BPS GSD Compressed Workweek (Philippines)",
    "Gender": "Any",
    "Schedule Type (Office or Shift)": "Shift",
    "Schedule Policy": "[PHL] Shift Schedule policy",
    "Overtime Requests": "Pre-approval OT Request",
    "Overtime Request Approval Paths": "PHL OT Approval",
    "Timesheet Template": "PHL In/Out JL 10 - 14 BPS GSD",
    "Timesheet Approval": "Supervisor for OT",
    "Timesheet Period": "Weekly - Starting Monday - ES employees and Contractors",
    "Time Off Template": "Time Off",
    "Time Off Approval": "PHL Approval Path",
    "Payrule": "Custom Philippines",
    "Time Off Types": "Refer to Time off Mapping sheet",
    "Time Zone": "(UTC+8:00) North Asia East Standard Time",
    "Work Week": "Monday to Sunday",
    "Holiday Calendar": "refer to holiday calendar sheet",
    "Authentication Type": "SSO",
    "Activities": "Refer to ES activity list sheet",
    "Time Entry Approval Path": "System",
    "Product": "",
    "Product URI": ""
  },
  {
    "Company Code": "PHES",
    "Personnel Sub Area Code": "Any",
    "SubGroup": "Any",
    "Industrial_Instrument_Classification": "Any",
    "Job level": 14,
    "Location": "Philippines",
    "Work Shift": "ES - BPS GSD Compressed Workweek (Philippines)",
    "Gender": "Any",
    "Schedule Type (Office or Shift)": "Shift",
    "Schedule Policy": "[PHL] Shift Schedule policy",
    "Overtime Requests": "Pre-approval OT Request",
    "Overtime Request Approval Paths": "PHL OT Approval",
    "Timesheet Template": "PHL In/Out JL 10 - 14 BPS GSD",
    "Timesheet Approval": "Supervisor for OT",
    "Timesheet Period": "Weekly - Starting Monday - ES employees and Contractors",
    "Time Off Template": "Time Off",
    "Time Off Approval": "PHL Approval Path",
    "Payrule": "Custom Philippines",
    "Time Off Types": "Refer to Time off Mapping sheet",
    "Time Zone": "(UTC+8:00) North Asia East Standard Time",
    "Work Week": "Monday to Sunday",
    "Holiday Calendar": "refer to holiday calendar sheet",
    "Authentication Type": "SSO",
    "Activities": "Refer to ES activity list sheet",
    "Time Entry Approval Path": "System",
    "Product": "",
    "Product URI": ""
  },
  {
    "Company Code": "PHET",
    "Personnel Sub Area Code": "Any",
    "SubGroup": "Any",
    "Industrial_Instrument_Classification": "Any",
    "Job level": 14,
    "Location": "Philippines",
    "Work Shift": "ES - BPS GSD Compressed Workweek (Philippines)",
    "Gender": "Any",
    "Schedule Type (Office or Shift)": "Shift",
    "Schedule Policy": "[PHL] Shift Schedule policy",
    "Overtime Requests": "Pre-approval OT Request",
    "Overtime Request Approval Paths": "PHL OT Approval",
    "Timesheet Template": "PHL In/Out JL 10 - 14 BPS GSD",
    "Timesheet Approval": "Supervisor for OT",
    "Timesheet Period": "Weekly - Starting Monday - ES employees and Contractors",
    "Time Off Template": "Time Off",
    "Time Off Approval": "PHL Approval Path",
    "Payrule": "Custom Philippines",
    "Time Off Types": "Refer to Time off Mapping sheet",
    "Time Zone": "(UTC+8:00) North Asia East Standard Time",
    "Work Week": "Monday to Sunday",
    "Holiday Calendar": "refer to holiday calendar sheet",
    "Authentication Type": "SSO",
    "Activities": "Refer to ES activity list sheet",
    "Time Entry Approval Path": "System",
    "Product": "",
    "Product URI": ""
  },
  {
    "Company Code": "PHES",
    "Personnel Sub Area Code": "Any",
    "SubGroup": "Any",
    "Industrial_Instrument_Classification": "Any",
    "Job level": 15,
    "Location": "Philippines",
    "Work Shift": "ES - BPS GSD Shift (Philippines)",
    "Gender": "Any",
    "Schedule Type (Office or Shift)": "Shift",
    "Schedule Policy": "[PHL] Shift Schedule policy",
    "Overtime Requests": "Pre-approval OT Request",
    "Overtime Request Approval Paths": "PHL OT Approval",
    "Timesheet Template": "PHL In/Out JL 15 BPS GSD",
    "Timesheet Approval": "Supervisor for OT",
    "Timesheet Period": "Weekly - Starting Monday - ES employees and Contractors",
    "Time Off Template": "Time Off",
    "Time Off Approval": "PHL Approval Path",
    "Payrule": "Custom Philippines",
    "Time Off Types": "Refer to Time off Mapping sheet",
    "Time Zone": "(UTC+8:00) North Asia East Standard Time",
    "Work Week": "Monday to Sunday",
    "Holiday Calendar": "refer to holiday calendar sheet",
    "Authentication Type": "SSO",
    "Activities": "Refer to ES activity list sheet",
    "Time Entry Approval Path": "System",
    "Product": "",
    "Product URI": ""
  },
  {
    "Company Code": "PHET",
    "Personnel Sub Area Code": "Any",
    "SubGroup": "Any",
    "Industrial_Instrument_Classification": "Any",
    "Job level": 15,
    "Location": "Philippines",
    "Work Shift": "ES - BPS GSD Shift (Philippines)",
    "Gender": "Any",
    "Schedule Type (Office or Shift)": "Shift",
    "Schedule Policy": "[PHL] Shift Schedule policy",
    "Overtime Requests": "Pre-approval OT Request",
    "Overtime Request Approval Paths": "PHL OT Approval",
    "Timesheet Template": "PHL In/Out JL 15 BPS GSD",
    "Timesheet Approval": "Supervisor for OT",
    "Timesheet Period": "Weekly - Starting Monday - ES employees and Contractors",
    "Time Off Template": "Time Off",
    "Time Off Approval": "PHL Approval Path",
    "Payrule": "Custom Philippines",
    "Time Off Types": "Refer to Time off Mapping sheet",
    "Time Zone": "(UTC+8:00) North Asia East Standard Time",
    "Work Week": "Monday to Sunday",
    "Holiday Calendar": "refer to holiday calendar sheet",
    "Authentication Type": "SSO",
    "Activities": "Refer to ES activity list sheet",
    "Time Entry Approval Path": "System",
    "Product": "",
    "Product URI": ""
  },
  {
    "Company Code": "PHES",
    "Personnel Sub Area Code": "Any",
    "SubGroup": "Any",
    "Industrial_Instrument_Classification": "Any",
    "Job level": 15,
    "Location": "Philippines",
    "Work Shift": "ES - BPS GSD Compressed Workweek (Philippines)",
    "Gender": "Any",
    "Schedule Type (Office or Shift)": "Shift",
    "Schedule Policy": "[PHL] Shift Schedule policy",
    "Overtime Requests": "Pre-approval OT Request",
    "Overtime Request Approval Paths": "PHL OT Approval",
    "Timesheet Template": "PHL In/Out JL 15 BPS GSD",
    "Timesheet Approval": "Supervisor for OT",
    "Timesheet Period": "Weekly - Starting Monday - ES employees and Contractors",
    "Time Off Template": "Time Off",
    "Time Off Approval": "PHL Approval Path",
    "Payrule": "Custom Philippines",
    "Time Off Types": "Refer to Time off Mapping sheet",
    "Time Zone": "(UTC+8:00) North Asia East Standard Time",
    "Work Week": "Monday to Sunday",
    "Holiday Calendar": "refer to holiday calendar sheet",
    "Authentication Type": "SSO",
    "Activities": "Refer to ES activity list sheet",
    "Time Entry Approval Path": "System",
    "Product": "",
    "Product URI": ""
  },
  {
    "Company Code": "PHET",
    "Personnel Sub Area Code": "Any",
    "SubGroup": "Any",
    "Industrial_Instrument_Classification": "Any",
    "Job level": 15,
    "Location": "Philippines",
    "Work Shift": "ES - BPS GSD Compressed Workweek (Philippines)",
    "Gender": "Any",
    "Schedule Type (Office or Shift)": "Shift",
    "Schedule Policy": "[PHL] Shift Schedule policy",
    "Overtime Requests": "Pre-approval OT Request",
    "Overtime Request Approval Paths": "PHL OT Approval",
    "Timesheet Template": "PHL In/Out JL 15 BPS GSD",
    "Timesheet Approval": "Supervisor for OT",
    "Timesheet Period": "Weekly - Starting Monday - ES employees and Contractors",
    "Time Off Template": "Time Off",
    "Time Off Approval": "PHL Approval Path",
    "Payrule": "Custom Philippines",
    "Time Off Types": "Refer to Time off Mapping sheet",
    "Time Zone": "(UTC+8:00) North Asia East Standard Time",
    "Work Week": "Monday to Sunday",
    "Holiday Calendar": "refer to holiday calendar sheet",
    "Authentication Type": "SSO",
    "Activities": "Refer to ES activity list sheet",
    "Time Entry Approval Path": "System",
    "Product": "",
    "Product URI": ""
  },
  {
    "Company Code": "PHES",
    "Personnel Sub Area Code": "Any",
    "SubGroup": "Any",
    "Industrial_Instrument_Classification": "Any",
    "Job level": 8,
    "Location": "Philippines",
    "Work Shift": "ES - No Shift premium (Philippines)",
    "Gender": "Any",
    "Schedule Type (Office or Shift)": "Office",
    "Schedule Policy": null,
    "Overtime Requests": "Pre-approval extra time request",
    "Overtime Request Approval Paths": "PHL OT Approval",
    "Timesheet Template": "PHL Agile 8-9",
    "Timesheet Approval": "Supervisor for OT",
    "Timesheet Period": "Weekly - Starting Monday - ES employees and Contractors",
    "Time Off Template": "Time Off",
    "Time Off Approval": "PHL Approval Path",
    "Payrule": "Custom Philippines",
    "Time Off Types": "Refer to Time off Mapping sheet",
    "Time Zone": "(UTC+8:00) North Asia East Standard Time",
    "Work Week": "Monday to Sunday",
    "Holiday Calendar": "refer to holiday calendar sheet",
    "Authentication Type": "SSO",
    "Activities": "Refer to ES activity list sheet",
    "Time Entry Approval Path": "System",
    "Product": "",
    "Product URI": ""
  },
  {
    "Company Code": "PHET",
    "Personnel Sub Area Code": "Any",
    "SubGroup": "Any",
    "Industrial_Instrument_Classification": "Any",
    "Job level": 8,
    "Location": "Philippines",
    "Work Shift": "ES - No Shift premium (Philippines)",
    "Gender": "Any",
    "Schedule Type (Office or Shift)": "Office",
    "Schedule Policy": null,
    "Overtime Requests": "Pre-approval extra time request",
    "Overtime Request Approval Paths": "PHL OT Approval",
    "Timesheet Template": "PHL Agile 8-9",
    "Timesheet Approval": "Supervisor for OT",
    "Timesheet Period": "Weekly - Starting Monday - ES employees and Contractors",
    "Time Off Template": "Time Off",
    "Time Off Approval": "PHL Approval Path",
    "Payrule": "Custom Philippines",
    "Time Off Types": "Refer to Time off Mapping sheet",
    "Time Zone": "(UTC+8:00) North Asia East Standard Time",
    "Work Week": "Monday to Sunday",
    "Holiday Calendar": "refer to holiday calendar sheet",
    "Authentication Type": "SSO",
    "Activities": "Refer to ES activity list sheet",
    "Time Entry Approval Path": "System",
    "Product": "",
    "Product URI": ""
  },
  {
    "Company Code": "PHES",
    "Personnel Sub Area Code": "Any",
    "SubGroup": "Any",
    "Industrial_Instrument_Classification": "Any",
    "Job level": 9,
    "Location": "Philippines",
    "Work Shift": "ES - No Shift premium (Philippines)",
    "Gender": "Any",
    "Schedule Type (Office or Shift)": "Office",
    "Schedule Policy": null,
    "Overtime Requests": "Pre-approval extra time request",
    "Overtime Request Approval Paths": "PHL OT Approval",
    "Timesheet Template": "PHL Agile 8-9",
    "Timesheet Approval": "Supervisor for OT",
    "Timesheet Period": "Weekly - Starting Monday - ES employees and Contractors",
    "Time Off Template": "Time Off",
    "Time Off Approval": "PHL Approval Path",
    "Payrule": "Custom Philippines",
    "Time Off Types": "Refer to Time off Mapping sheet",
    "Time Zone": "(UTC+8:00) North Asia East Standard Time",
    "Work Week": "Monday to Sunday",
    "Holiday Calendar": "refer to holiday calendar sheet",
    "Authentication Type": "SSO",
    "Activities": "Refer to ES activity list sheet",
    "Time Entry Approval Path": "System",
    "Product": "",
    "Product URI": ""
  },
  {
    "Company Code": "PHET",
    "Personnel Sub Area Code": "Any",
    "SubGroup": "Any",
    "Industrial_Instrument_Classification": "Any",
    "Job level": 9,
    "Location": "Philippines",
    "Work Shift": "ES - No Shift premium (Philippines)",
    "Gender": "Any",
    "Schedule Type (Office or Shift)": "Office",
    "Schedule Policy": null,
    "Overtime Requests": "Pre-approval extra time request",
    "Overtime Request Approval Paths": "PHL OT Approval",
    "Timesheet Template": "PHL Agile 8-9",
    "Timesheet Approval": "Supervisor for OT",
    "Timesheet Period": "Weekly - Starting Monday - ES employees and Contractors",
    "Time Off Template": "Time Off",
    "Time Off Approval": "PHL Approval Path",
    "Payrule": "Custom Philippines",
    "Time Off Types": "Refer to Time off Mapping sheet",
    "Time Zone": "(UTC+8:00) North Asia East Standard Time",
    "Work Week": "Monday to Sunday",
    "Holiday Calendar": "refer to holiday calendar sheet",
    "Authentication Type": "SSO",
    "Activities": "Refer to ES activity list sheet",
    "Time Entry Approval Path": "System",
    "Product": "",
    "Product URI": ""
  },
  {
    "Company Code": "PHES",
    "Personnel Sub Area Code": "Any",
    "SubGroup": "Any",
    "Industrial_Instrument_Classification": "Any",
    "Job level": 1,
    "Location": "Philippines",
    "Work Shift": "ES - No Shift premium (Philippines)",
    "Gender": "Any",
    "Schedule Type (Office or Shift)": "Office",
    "Schedule Policy": null,
    "Overtime Requests": null,
    "Overtime Request Approval Paths": null,
    "Timesheet Template": "PHL IN/Out JL 1-7 (Non Shifters)",
    "Timesheet Approval": "System",
    "Timesheet Period": "Weekly - Starting Monday - ES employees and Contractors",
    "Time Off Template": "Time Off",
    "Time Off Approval": "PHL Approval Path",
    "Payrule": "Custom Philippines",
    "Time Off Types": "Refer to Time off Mapping sheet",
    "Time Zone": "(UTC+8:00) North Asia East Standard Time",
    "Work Week": "Monday to Sunday",
    "Holiday Calendar": "refer to holiday calendar sheet",
    "Authentication Type": "SSO",
    "Activities": "Refer to ES activity list sheet",
    "Time Entry Approval Path": "System",
    "Product": "",
    "Product URI": ""
  },
  {
    "Company Code": "PHET",
    "Personnel Sub Area Code": "Any",
    "SubGroup": "Any",
    "Industrial_Instrument_Classification": "Any",
    "Job level": 1,
    "Location": "Philippines",
    "Work Shift": "ES - No Shift premium (Philippines)",
    "Gender": "Any",
    "Schedule Type (Office or Shift)": "Office",
    "Schedule Policy": null,
    "Overtime Requests": null,
    "Overtime Request Approval Paths": null,
    "Timesheet Template": "PHL IN/Out JL 1-7 (Non Shifters)",
    "Timesheet Approval": "System",
    "Timesheet Period": "Weekly - Starting Monday - ES employees and Contractors",
    "Time Off Template": "Time Off",
    "Time Off Approval": "PHL Approval Path",
    "Payrule": "Custom Philippines",
    "Time Off Types": "Refer to Time off Mapping sheet",
    "Time Zone": "(UTC+8:00) North Asia East Standard Time",
    "Work Week": "Monday to Sunday",
    "Holiday Calendar": "refer to holiday calendar sheet",
    "Authentication Type": "SSO",
    "Activities": "Refer to ES activity list sheet",
    "Time Entry Approval Path": "System",
    "Product": "",
    "Product URI": ""
  },
  {
    "Company Code": "PHES",
    "Personnel Sub Area Code": "Any",
    "SubGroup": "Any",
    "Industrial_Instrument_Classification": "Any",
    "Job level": 2,
    "Location": "Philippines",
    "Work Shift": "ES - No Shift premium (Philippines)",
    "Gender": "Any",
    "Schedule Type (Office or Shift)": "Office",
    "Schedule Policy": null,
    "Overtime Requests": null,
    "Overtime Request Approval Paths": null,
    "Timesheet Template": "PHL IN/Out JL 1-7 (Non Shifters)",
    "Timesheet Approval": "System",
    "Timesheet Period": "Weekly - Starting Monday - ES employees and Contractors",
    "Time Off Template": "Time Off",
    "Time Off Approval": "PHL Approval Path",
    "Payrule": "Custom Philippines",
    "Time Off Types": "Refer to Time off Mapping sheet",
    "Time Zone": "(UTC+8:00) North Asia East Standard Time",
    "Work Week": "Monday to Sunday",
    "Holiday Calendar": "refer to holiday calendar sheet",
    "Authentication Type": "SSO",
    "Activities": "Refer to ES activity list sheet",
    "Time Entry Approval Path": "System",
    "Product": "",
    "Product URI": ""
  },
  {
    "Company Code": "PHET",
    "Personnel Sub Area Code": "Any",
    "SubGroup": "Any",
    "Industrial_Instrument_Classification": "Any",
    "Job level": 2,
    "Location": "Philippines",
    "Work Shift": "ES - No Shift premium (Philippines)",
    "Gender": "Any",
    "Schedule Type (Office or Shift)": "Office",
    "Schedule Policy": null,
    "Overtime Requests": null,
    "Overtime Request Approval Paths": null,
    "Timesheet Template": "PHL IN/Out JL 1-7 (Non Shifters)",
    "Timesheet Approval": "System",
    "Timesheet Period": "Weekly - Starting Monday - ES employees and Contractors",
    "Time Off Template": "Time Off",
    "Time Off Approval": "PHL Approval Path",
    "Payrule": "Custom Philippines",
    "Time Off Types": "Refer to Time off Mapping sheet",
    "Time Zone": "(UTC+8:00) North Asia East Standard Time",
    "Work Week": "Monday to Sunday",
    "Holiday Calendar": "refer to holiday calendar sheet",
    "Authentication Type": "SSO",
    "Activities": "Refer to ES activity list sheet",
    "Time Entry Approval Path": "System",
    "Product": "",
    "Product URI": ""
  },
  {
    "Company Code": "PHES",
    "Personnel Sub Area Code": "Any",
    "SubGroup": "Any",
    "Industrial_Instrument_Classification": "Any",
    "Job level": 3,
    "Location": "Philippines",
    "Work Shift": "ES - No Shift premium (Philippines)",
    "Gender": "Any",
    "Schedule Type (Office or Shift)": "Office",
    "Schedule Policy": null,
    "Overtime Requests": null,
    "Overtime Request Approval Paths": null,
    "Timesheet Template": "PHL IN/Out JL 1-7 (Non Shifters)",
    "Timesheet Approval": "System",
    "Timesheet Period": "Weekly - Starting Monday - ES employees and Contractors",
    "Time Off Template": "Time Off",
    "Time Off Approval": "PHL Approval Path",
    "Payrule": "Custom Philippines",
    "Time Off Types": "Refer to Time off Mapping sheet",
    "Time Zone": "(UTC+8:00) North Asia East Standard Time",
    "Work Week": "Monday to Sunday",
    "Holiday Calendar": "refer to holiday calendar sheet",
    "Authentication Type": "SSO",
    "Activities": "Refer to ES activity list sheet",
    "Time Entry Approval Path": "System",
    "Product": "",
    "Product URI": ""
  },
  {
    "Company Code": "PHET",
    "Personnel Sub Area Code": "Any",
    "SubGroup": "Any",
    "Industrial_Instrument_Classification": "Any",
    "Job level": 3,
    "Location": "Philippines",
    "Work Shift": "ES - No Shift premium (Philippines)",
    "Gender": "Any",
    "Schedule Type (Office or Shift)": "Office",
    "Schedule Policy": null,
    "Overtime Requests": null,
    "Overtime Request Approval Paths": null,
    "Timesheet Template": "PHL IN/Out JL 1-7 (Non Shifters)",
    "Timesheet Approval": "System",
    "Timesheet Period": "Weekly - Starting Monday - ES employees and Contractors",
    "Time Off Template": "Time Off",
    "Time Off Approval": "PHL Approval Path",
    "Payrule": "Custom Philippines",
    "Time Off Types": "Refer to Time off Mapping sheet",
    "Time Zone": "(UTC+8:00) North Asia East Standard Time",
    "Work Week": "Monday to Sunday",
    "Holiday Calendar": "refer to holiday calendar sheet",
    "Authentication Type": "SSO",
    "Activities": "Refer to ES activity list sheet",
    "Time Entry Approval Path": "System",
    "Product": "",
    "Product URI": ""
  },
  {
    "Company Code": "PHES",
    "Personnel Sub Area Code": "Any",
    "SubGroup": "Any",
    "Industrial_Instrument_Classification": "Any",
    "Job level": 4,
    "Location": "Philippines",
    "Work Shift": "ES - No Shift premium (Philippines)",
    "Gender": "Any",
    "Schedule Type (Office or Shift)": "Office",
    "Schedule Policy": null,
    "Overtime Requests": null,
    "Overtime Request Approval Paths": null,
    "Timesheet Template": "PHL IN/Out JL 1-7 (Non Shifters)",
    "Timesheet Approval": "System",
    "Timesheet Period": "Weekly - Starting Monday - ES employees and Contractors",
    "Time Off Template": "Time Off",
    "Time Off Approval": "PHL Approval Path",
    "Payrule": "Custom Philippines",
    "Time Off Types": "Refer to Time off Mapping sheet",
    "Time Zone": "(UTC+8:00) North Asia East Standard Time",
    "Work Week": "Monday to Sunday",
    "Holiday Calendar": "refer to holiday calendar sheet",
    "Authentication Type": "SSO",
    "Activities": "Refer to ES activity list sheet",
    "Time Entry Approval Path": "System",
    "Product": "",
    "Product URI": ""
  },
  {
    "Company Code": "PHET",
    "Personnel Sub Area Code": "Any",
    "SubGroup": "Any",
    "Industrial_Instrument_Classification": "Any",
    "Job level": 4,
    "Location": "Philippines",
    "Work Shift": "ES - No Shift premium (Philippines)",
    "Gender": "Any",
    "Schedule Type (Office or Shift)": "Office",
    "Schedule Policy": null,
    "Overtime Requests": null,
    "Overtime Request Approval Paths": null,
    "Timesheet Template": "PHL IN/Out JL 1-7 (Non Shifters)",
    "Timesheet Approval": "System",
    "Timesheet Period": "Weekly - Starting Monday - ES employees and Contractors",
    "Time Off Template": "Time Off",
    "Time Off Approval": "PHL Approval Path",
    "Payrule": "Custom Philippines",
    "Time Off Types": "Refer to Time off Mapping sheet",
    "Time Zone": "(UTC+8:00) North Asia East Standard Time",
    "Work Week": "Monday to Sunday",
    "Holiday Calendar": "refer to holiday calendar sheet",
    "Authentication Type": "SSO",
    "Activities": "Refer to ES activity list sheet",
    "Time Entry Approval Path": "System",
    "Product": "",
    "Product URI": ""
  },
  {
    "Company Code": "PHES",
    "Personnel Sub Area Code": "Any",
    "SubGroup": "Any",
    "Industrial_Instrument_Classification": "Any",
    "Job level": 5,
    "Location": "Philippines",
    "Work Shift": "ES - No Shift premium (Philippines)",
    "Gender": "Any",
    "Schedule Type (Office or Shift)": "Office",
    "Schedule Policy": null,
    "Overtime Requests": null,
    "Overtime Request Approval Paths": null,
    "Timesheet Template": "PHL IN/Out JL 1-7 (Non Shifters)",
    "Timesheet Approval": "System",
    "Timesheet Period": "Weekly - Starting Monday - ES employees and Contractors",
    "Time Off Template": "Time Off",
    "Time Off Approval": "PHL Approval Path",
    "Payrule": "Custom Philippines",
    "Time Off Types": "Refer to Time off Mapping sheet",
    "Time Zone": "(UTC+8:00) North Asia East Standard Time",
    "Work Week": "Monday to Sunday",
    "Holiday Calendar": "refer to holiday calendar sheet",
    "Authentication Type": "SSO",
    "Activities": "Refer to ES activity list sheet",
    "Time Entry Approval Path": "System",
    "Product": "",
    "Product URI": ""
  },
  {
    "Company Code": "PHET",
    "Personnel Sub Area Code": "Any",
    "SubGroup": "Any",
    "Industrial_Instrument_Classification": "Any",
    "Job level": 5,
    "Location": "Philippines",
    "Work Shift": "ES - No Shift premium (Philippines)",
    "Gender": "Any",
    "Schedule Type (Office or Shift)": "Office",
    "Schedule Policy": null,
    "Overtime Requests": null,
    "Overtime Request Approval Paths": null,
    "Timesheet Template": "PHL IN/Out JL 1-7 (Non Shifters)",
    "Timesheet Approval": "System",
    "Timesheet Period": "Weekly - Starting Monday - ES employees and Contractors",
    "Time Off Template": "Time Off",
    "Time Off Approval": "PHL Approval Path",
    "Payrule": "Custom Philippines",
    "Time Off Types": "Refer to Time off Mapping sheet",
    "Time Zone": "(UTC+8:00) North Asia East Standard Time",
    "Work Week": "Monday to Sunday",
    "Holiday Calendar": "refer to holiday calendar sheet",
    "Authentication Type": "SSO",
    "Activities": "Refer to ES activity list sheet",
    "Time Entry Approval Path": "System",
    "Product": "",
    "Product URI": ""
  },
  {
    "Company Code": "PHES",
    "Personnel Sub Area Code": "Any",
    "SubGroup": "Any",
    "Industrial_Instrument_Classification": "Any",
    "Job level": 6,
    "Location": "Philippines",
    "Work Shift": "ES - No Shift premium (Philippines)",
    "Gender": "Any",
    "Schedule Type (Office or Shift)": "Office",
    "Schedule Policy": null,
    "Overtime Requests": null,
    "Overtime Request Approval Paths": null,
    "Timesheet Template": "PHL IN/Out JL 1-7 (Non Shifters)",
    "Timesheet Approval": "System",
    "Timesheet Period": "Weekly - Starting Monday - ES employees and Contractors",
    "Time Off Template": "Time Off",
    "Time Off Approval": "PHL Approval Path",
    "Payrule": "Custom Philippines",
    "Time Off Types": "Refer to Time off Mapping sheet",
    "Time Zone": "(UTC+8:00) North Asia East Standard Time",
    "Work Week": "Monday to Sunday",
    "Holiday Calendar": "refer to holiday calendar sheet",
    "Authentication Type": "SSO",
    "Activities": "Refer to ES activity list sheet",
    "Time Entry Approval Path": "System",
    "Product": "",
    "Product URI": ""
  },
  {
    "Company Code": "PHET",
    "Personnel Sub Area Code": "Any",
    "SubGroup": "Any",
    "Industrial_Instrument_Classification": "Any",
    "Job level": 6,
    "Location": "Philippines",
    "Work Shift": "ES - No Shift premium (Philippines)",
    "Gender": "Any",
    "Schedule Type (Office or Shift)": "Office",
    "Schedule Policy": null,
    "Overtime Requests": null,
    "Overtime Request Approval Paths": null,
    "Timesheet Template": "PHL IN/Out JL 1-7 (Non Shifters)",
    "Timesheet Approval": "System",
    "Timesheet Period": "Weekly - Starting Monday - ES employees and Contractors",
    "Time Off Template": "Time Off",
    "Time Off Approval": "PHL Approval Path",
    "Payrule": "Custom Philippines",
    "Time Off Types": "Refer to Time off Mapping sheet",
    "Time Zone": "(UTC+8:00) North Asia East Standard Time",
    "Work Week": "Monday to Sunday",
    "Holiday Calendar": "refer to holiday calendar sheet",
    "Authentication Type": "SSO",
    "Activities": "Refer to ES activity list sheet",
    "Time Entry Approval Path": "System",
    "Product": "",
    "Product URI": ""
  },
  {
    "Company Code": "PHES",
    "Personnel Sub Area Code": "Any",
    "SubGroup": "Any",
    "Industrial_Instrument_Classification": "Any",
    "Job level": 7,
    "Location": "Philippines",
    "Work Shift": "ES - No Shift premium (Philippines)",
    "Gender": "Any",
    "Schedule Type (Office or Shift)": "Office",
    "Schedule Policy": null,
    "Overtime Requests": null,
    "Overtime Request Approval Paths": null,
    "Timesheet Template": "PHL IN/Out JL 1-7 (Non Shifters)",
    "Timesheet Approval": "System",
    "Timesheet Period": "Weekly - Starting Monday - ES employees and Contractors",
    "Time Off Template": "Time Off",
    "Time Off Approval": "PHL Approval Path",
    "Payrule": "Custom Philippines",
    "Time Off Types": "Refer to Time off Mapping sheet",
    "Time Zone": "(UTC+8:00) North Asia East Standard Time",
    "Work Week": "Monday to Sunday",
    "Holiday Calendar": "refer to holiday calendar sheet",
    "Authentication Type": "SSO",
    "Activities": "Refer to ES activity list sheet",
    "Time Entry Approval Path": "System",
    "Product": "",
    "Product URI": ""
  },
  {
    "Company Code": "PHET",
    "Personnel Sub Area Code": "Any",
    "SubGroup": "Any",
    "Industrial_Instrument_Classification": "Any",
    "Job level": 7,
    "Location": "Philippines",
    "Work Shift": "ES - No Shift premium (Philippines)",
    "Gender": "Any",
    "Schedule Type (Office or Shift)": "Office",
    "Schedule Policy": null,
    "Overtime Requests": null,
    "Overtime Request Approval Paths": null,
    "Timesheet Template": "PHL IN/Out JL 1-7 (Non Shifters)",
    "Timesheet Approval": "System",
    "Timesheet Period": "Weekly - Starting Monday - ES employees and Contractors",
    "Time Off Template": "Time Off",
    "Time Off Approval": "PHL Approval Path",
    "Payrule": "Custom Philippines",
    "Time Off Types": "Refer to Time off Mapping sheet",
    "Time Zone": "(UTC+8:00) North Asia East Standard Time",
    "Work Week": "Monday to Sunday",
    "Holiday Calendar": "refer to holiday calendar sheet",
    "Authentication Type": "SSO",
    "Activities": "Refer to ES activity list sheet",
    "Time Entry Approval Path": "System",
    "Product": "",
    "Product URI": ""
  },
  {
    "Company Code": "PHES",
    "Personnel Sub Area Code": "Any",
    "SubGroup": "Any",
    "Industrial_Instrument_Classification": "Any",
    "Job level": 10,
    "Location": "Philippines",
    "Work Shift": "ES - No Shift premium (Philippines)",
    "Gender": "Any",
    "Schedule Type (Office or Shift)": "Office",
    "Schedule Policy": null,
    "Overtime Requests": null,
    "Overtime Request Approval Paths": null,
    "Timesheet Template": "PHL IN/Out JL 1-7 (Non Shifters)",
    "Timesheet Approval": "System",
    "Timesheet Period": "Weekly - Starting Monday - ES employees and Contractors",
    "Time Off Template": "Time Off",
    "Time Off Approval": "PHL Approval Path",
    "Payrule": "Custom Philippines",
    "Time Off Types": "Refer to Time off Mapping sheet",
    "Time Zone": "(UTC+8:00) North Asia East Standard Time",
    "Work Week": "Monday to Sunday",
    "Holiday Calendar": "refer to holiday calendar sheet",
    "Authentication Type": "SSO",
    "Activities": "Refer to ES activity list sheet",
    "Time Entry Approval Path": "System",
    "Product": "",
    "Product URI": ""
  },
  {
    "Company Code": "PHET",
    "Personnel Sub Area Code": "Any",
    "SubGroup": "Any",
    "Industrial_Instrument_Classification": "Any",
    "Job level": 10,
    "Location": "Philippines",
    "Work Shift": "ES - No Shift premium (Philippines)",
    "Gender": "Any",
    "Schedule Type (Office or Shift)": "Office",
    "Schedule Policy": null,
    "Overtime Requests": null,
    "Overtime Request Approval Paths": null,
    "Timesheet Template": "PHL IN/Out JL 1-7 (Non Shifters)",
    "Timesheet Approval": "System",
    "Timesheet Period": "Weekly - Starting Monday - ES employees and Contractors",
    "Time Off Template": "Time Off",
    "Time Off Approval": "PHL Approval Path",
    "Payrule": "Custom Philippines",
    "Time Off Types": "Refer to Time off Mapping sheet",
    "Time Zone": "(UTC+8:00) North Asia East Standard Time",
    "Work Week": "Monday to Sunday",
    "Holiday Calendar": "refer to holiday calendar sheet",
    "Authentication Type": "SSO",
    "Activities": "Refer to ES activity list sheet",
    "Time Entry Approval Path": "System",
    "Product": "",
    "Product URI": ""
  },
  {
    "Company Code": "PHES",
    "Personnel Sub Area Code": "Any",
    "SubGroup": "Any",
    "Industrial_Instrument_Classification": "Any",
    "Job level": 11,
    "Location": "Philippines",
    "Work Shift": "ES - No Shift premium (Philippines)",
    "Gender": "Any",
    "Schedule Type (Office or Shift)": "Office",
    "Schedule Policy": null,
    "Overtime Requests": null,
    "Overtime Request Approval Paths": null,
    "Timesheet Template": "PHL IN/Out JL 1-7 (Non Shifters)",
    "Timesheet Approval": "System",
    "Timesheet Period": "Weekly - Starting Monday - ES employees and Contractors",
    "Time Off Template": "Time Off",
    "Time Off Approval": "PHL Approval Path",
    "Payrule": "Custom Philippines",
    "Time Off Types": "Refer to Time off Mapping sheet",
    "Time Zone": "(UTC+8:00) North Asia East Standard Time",
    "Work Week": "Monday to Sunday",
    "Holiday Calendar": "refer to holiday calendar sheet",
    "Authentication Type": "SSO",
    "Activities": "Refer to ES activity list sheet",
    "Time Entry Approval Path": "System",
    "Product": "",
    "Product URI": ""
  },
  {
    "Company Code": "PHET",
    "Personnel Sub Area Code": "Any",
    "SubGroup": "Any",
    "Industrial_Instrument_Classification": "Any",
    "Job level": 11,
    "Location": "Philippines",
    "Work Shift": "ES - No Shift premium (Philippines)",
    "Gender": "Any",
    "Schedule Type (Office or Shift)": "Office",
    "Schedule Policy": null,
    "Overtime Requests": null,
    "Overtime Request Approval Paths": null,
    "Timesheet Template": "PHL IN/Out JL 1-7 (Non Shifters)",
    "Timesheet Approval": "System",
    "Timesheet Period": "Weekly - Starting Monday - ES employees and Contractors",
    "Time Off Template": "Time Off",
    "Time Off Approval": "PHL Approval Path",
    "Payrule": "Custom Philippines",
    "Time Off Types": "Refer to Time off Mapping sheet",
    "Time Zone": "(UTC+8:00) North Asia East Standard Time",
    "Work Week": "Monday to Sunday",
    "Holiday Calendar": "refer to holiday calendar sheet",
    "Authentication Type": "SSO",
    "Activities": "Refer to ES activity list sheet",
    "Time Entry Approval Path": "System",
    "Product": "",
    "Product URI": ""
  },
  {
    "Company Code": "PHES",
    "Personnel Sub Area Code": "Any",
    "SubGroup": "Any",
    "Industrial_Instrument_Classification": "Any",
    "Job level": 12,
    "Location": "Philippines",
    "Work Shift": "ES - No Shift premium (Philippines)",
    "Gender": "Any",
    "Schedule Type (Office or Shift)": "Office",
    "Schedule Policy": null,
    "Overtime Requests": null,
    "Overtime Request Approval Paths": null,
    "Timesheet Template": "PHL IN/Out JL 1-7 (Non Shifters)",
    "Timesheet Approval": "System",
    "Timesheet Period": "Weekly - Starting Monday - ES employees and Contractors",
    "Time Off Template": "Time Off",
    "Time Off Approval": "PHL Approval Path",
    "Payrule": "Custom Philippines",
    "Time Off Types": "Refer to Time off Mapping sheet",
    "Time Zone": "(UTC+8:00) North Asia East Standard Time",
    "Work Week": "Monday to Sunday",
    "Holiday Calendar": "refer to holiday calendar sheet",
    "Authentication Type": "SSO",
    "Activities": "Refer to ES activity list sheet",
    "Time Entry Approval Path": "System",
    "Product": "",
    "Product URI": ""
  },
  {
    "Company Code": "PHET",
    "Personnel Sub Area Code": "Any",
    "SubGroup": "Any",
    "Industrial_Instrument_Classification": "Any",
    "Job level": 12,
    "Location": "Philippines",
    "Work Shift": "ES - No Shift premium (Philippines)",
    "Gender": "Any",
    "Schedule Type (Office or Shift)": "Office",
    "Schedule Policy": null,
    "Overtime Requests": null,
    "Overtime Request Approval Paths": null,
    "Timesheet Template": "PHL IN/Out JL 1-7 (Non Shifters)",
    "Timesheet Approval": "System",
    "Timesheet Period": "Weekly - Starting Monday - ES employees and Contractors",
    "Time Off Template": "Time Off",
    "Time Off Approval": "PHL Approval Path",
    "Payrule": "Custom Philippines",
    "Time Off Types": "Refer to Time off Mapping sheet",
    "Time Zone": "(UTC+8:00) North Asia East Standard Time",
    "Work Week": "Monday to Sunday",
    "Holiday Calendar": "refer to holiday calendar sheet",
    "Authentication Type": "SSO",
    "Activities": "Refer to ES activity list sheet",
    "Time Entry Approval Path": "System",
    "Product": "",
    "Product URI": ""
  },
  {
    "Company Code": "PHES",
    "Personnel Sub Area Code": "Any",
    "SubGroup": "Any",
    "Industrial_Instrument_Classification": "Any",
    "Job level": 13,
    "Location": "Philippines",
    "Work Shift": "ES - No Shift premium (Philippines)",
    "Gender": "Any",
    "Schedule Type (Office or Shift)": "Office",
    "Schedule Policy": null,
    "Overtime Requests": null,
    "Overtime Request Approval Paths": null,
    "Timesheet Template": "PHL IN/Out JL 1-7 (Non Shifters)",
    "Timesheet Approval": "System",
    "Timesheet Period": "Weekly - Starting Monday - ES employees and Contractors",
    "Time Off Template": "Time Off",
    "Time Off Approval": "PHL Approval Path",
    "Payrule": "Custom Philippines",
    "Time Off Types": "Refer to Time off Mapping sheet",
    "Time Zone": "(UTC+8:00) North Asia East Standard Time",
    "Work Week": "Monday to Sunday",
    "Holiday Calendar": "refer to holiday calendar sheet",
    "Authentication Type": "SSO",
    "Activities": "Refer to ES activity list sheet",
    "Time Entry Approval Path": "System",
    "Product": "",
    "Product URI": ""
  },
  {
    "Company Code": "PHET",
    "Personnel Sub Area Code": "Any",
    "SubGroup": "Any",
    "Industrial_Instrument_Classification": "Any",
    "Job level": 13,
    "Location": "Philippines",
    "Work Shift": "ES - No Shift premium (Philippines)",
    "Gender": "Any",
    "Schedule Type (Office or Shift)": "Office",
    "Schedule Policy": null,
    "Overtime Requests": null,
    "Overtime Request Approval Paths": null,
    "Timesheet Template": "PHL IN/Out JL 1-7 (Non Shifters)",
    "Timesheet Approval": "System",
    "Timesheet Period": "Weekly - Starting Monday - ES employees and Contractors",
    "Time Off Template": "Time Off",
    "Time Off Approval": "PHL Approval Path",
    "Payrule": "Custom Philippines",
    "Time Off Types": "Refer to Time off Mapping sheet",
    "Time Zone": "(UTC+8:00) North Asia East Standard Time",
    "Work Week": "Monday to Sunday",
    "Holiday Calendar": "refer to holiday calendar sheet",
    "Authentication Type": "SSO",
    "Activities": "Refer to ES activity list sheet",
    "Time Entry Approval Path": "System",
    "Product": "",
    "Product URI": ""
  },
  {
    "Company Code": "PHES",
    "Personnel Sub Area Code": "Any",
    "SubGroup": "Any",
    "Industrial_Instrument_Classification": "Any",
    "Job level": 14,
    "Location": "Philippines",
    "Work Shift": "ES - No Shift premium (Philippines)",
    "Gender": "Any",
    "Schedule Type (Office or Shift)": "Office",
    "Schedule Policy": null,
    "Overtime Requests": null,
    "Overtime Request Approval Paths": null,
    "Timesheet Template": "PHL IN/Out JL 1-7 (Non Shifters)",
    "Timesheet Approval": "System",
    "Timesheet Period": "Weekly - Starting Monday - ES employees and Contractors",
    "Time Off Template": "Time Off",
    "Time Off Approval": "PHL Approval Path",
    "Payrule": "Custom Philippines",
    "Time Off Types": "Refer to Time off Mapping sheet",
    "Time Zone": "(UTC+8:00) North Asia East Standard Time",
    "Work Week": "Monday to Sunday",
    "Holiday Calendar": "refer to holiday calendar sheet",
    "Authentication Type": "SSO",
    "Activities": "Refer to ES activity list sheet",
    "Time Entry Approval Path": "System",
    "Product": "",
    "Product URI": ""
  },
  {
    "Company Code": "PHET",
    "Personnel Sub Area Code": "Any",
    "SubGroup": "Any",
    "Industrial_Instrument_Classification": "Any",
    "Job level": 14,
    "Location": "Philippines",
    "Work Shift": "ES - No Shift premium (Philippines)",
    "Gender": "Any",
    "Schedule Type (Office or Shift)": "Office",
    "Schedule Policy": null,
    "Overtime Requests": null,
    "Overtime Request Approval Paths": null,
    "Timesheet Template": "PHL IN/Out JL 1-7 (Non Shifters)",
    "Timesheet Approval": "System",
    "Timesheet Period": "Weekly - Starting Monday - ES employees and Contractors",
    "Time Off Template": "Time Off",
    "Time Off Approval": "PHL Approval Path",
    "Payrule": "Custom Philippines",
    "Time Off Types": "Refer to Time off Mapping sheet",
    "Time Zone": "(UTC+8:00) North Asia East Standard Time",
    "Work Week": "Monday to Sunday",
    "Holiday Calendar": "refer to holiday calendar sheet",
    "Authentication Type": "SSO",
    "Activities": "Refer to ES activity list sheet",
    "Time Entry Approval Path": "System",
    "Product": "",
    "Product URI": ""
  },
  {
    "Company Code": "PHES",
    "Personnel Sub Area Code": "Any",
    "SubGroup": "Any",
    "Industrial_Instrument_Classification": "Any",
    "Job level": 15,
    "Location": "Philippines",
    "Work Shift": "ES - No Shift premium (Philippines)",
    "Gender": "Any",
    "Schedule Type (Office or Shift)": "Office",
    "Schedule Policy": null,
    "Overtime Requests": null,
    "Overtime Request Approval Paths": null,
    "Timesheet Template": "PHL IN/Out JL 1-7 (Non Shifters)",
    "Timesheet Approval": "System",
    "Timesheet Period": "Weekly - Starting Monday - ES employees and Contractors",
    "Time Off Template": "Time Off",
    "Time Off Approval": "PHL Approval Path",
    "Payrule": "Custom Philippines",
    "Time Off Types": "Refer to Time off Mapping sheet",
    "Time Zone": "(UTC+8:00) North Asia East Standard Time",
    "Work Week": "Monday to Sunday",
    "Holiday Calendar": "refer to holiday calendar sheet",
    "Authentication Type": "SSO",
    "Activities": "Refer to ES activity list sheet",
    "Time Entry Approval Path": "System",
    "Product": "",
    "Product URI": ""
  },
  {
    "Company Code": "PHET",
    "Personnel Sub Area Code": "Any",
    "SubGroup": "Any",
    "Industrial_Instrument_Classification": "Any",
    "Job level": 15,
    "Location": "Philippines",
    "Work Shift": "ES - No Shift premium (Philippines)",
    "Gender": "Any",
    "Schedule Type (Office or Shift)": "Office",
    "Schedule Policy": null,
    "Overtime Requests": null,
    "Overtime Request Approval Paths": null,
    "Timesheet Template": "PHL IN/Out JL 1-7 (Non Shifters)",
    "Timesheet Approval": "System",
    "Timesheet Period": "Weekly - Starting Monday - ES employees and Contractors",
    "Time Off Template": "Time Off",
    "Time Off Approval": "PHL Approval Path",
    "Payrule": "Custom Philippines",
    "Time Off Types": "Refer to Time off Mapping sheet",
    "Time Zone": "(UTC+8:00) North Asia East Standard Time",
    "Work Week": "Monday to Sunday",
    "Holiday Calendar": "refer to holiday calendar sheet",
    "Authentication Type": "SSO",
    "Activities": "Refer to ES activity list sheet",
    "Time Entry Approval Path": "System",
    "Product": "",
    "Product URI": ""
  }
]
