role_approval_path_mapper = {
    "timesheet_approval_path": 'FR_Efforts_Approval',
    "timeoff_approval_path_group": "France - LT Approval Path",
    "timeoff_approval_path": "France - Approval Path",
    "l1_manager": "L1 Manager (FR)",
    "end_user_manager": "End User (Managers)",
    "project_manager": "France Project Manager",
    "hr_manager": "FR_Geo HR",
    "default_user_permission": "Project Resource",
    "foreign_manager_emp_type": "Foreign Managers",
    "ot_request_template": "France OT Pre-approval",
    "ot_request_template_37" : "France OT Pre-approval",
    "ot_request_template_fj" : "France Standby Pre-approval",
    "ot_request_approval_path": "FR-Preapproval Overtime",
    "ot_request_approval_path_fj_37": "FR-Preapproval Overtime",
    "schedule_type_for_fj": "38.5 Hours - Mon to Fri",
    "schedule_type": "37 Hours Weekly",
    "payrule_for_fj37": "France 37 Hour Payrule",
    "payrule": "France Forfait Payrule",
    "timesheet_template_for_fj": "France Forefait Jours",
    "timesheet_template": "French Timesheet",
    "time_off_template": "Time Off",
    "time_zone": "(UTC+1:00) Central European Standard Time",
    "timesheet_system_approval_path": "System Approval",
    "timesheet_period": "Weekly starting on Monday",
}