timetype_standby_units_to_exclude = {
  "Time Type UK - Callout": ["Standby Units"],
  "Time Type UK - CallOut|Standby|OT": ["Standby Units"],
  "Time Type UK - EON": ["Standby Units"],
  "Time Type UK - Olympus": ["Standby Units"],
  "Time Type UK - AT&T": ["Standby Units"],
  "Time Type UK - Paybands": ["Standby Units"],
  "Time Type IRL - CO|SD|OT": ["Standby Units"],
  "Time Type IRL - CO & SB": ["Standby Units"],
  "Time Type 1 - UK FDS": ["Standby Hours"],
  "Time Type 2 - UK FDS": ["Standby Hours"],
  "Time Type 3 - UK FDS": ["Standby Hours"],
  "Time Type 6- UK FDS": ["Standby Hours"],
  "Time Type 8- UK FDS": [
    "Standby Christmas/New Years",
    "Standby Holiday 00:00-08:00",
    "Standby Holiday 08:00-17:00",
    "Standby Holiday 17:00-24:00",
    "Standby Mon-Fri 00:00-08:00",
    "Standby Mon-Fri 17:00-24:00",
    "Standby Sat-Sun 00:00-08:00",
    "Standby Sat-Sun 08:00-17:00",
    "Standby Sat-Sun 17:00-24:00"
  ],
  "Time Type 9- UK FDS": ["Standby Hours"],
  "Time Type 11 - UK FDS": ["Standby Hours"],
  "Time Type 13 - UK FDS": ["Standby Hours"],
  "Time Type 18 - UK FDS": ["Standby Hours"],
  "Time Type 19 - UK FDS": ["Standby Hours"],
  "Time Type 1 - IRL FDS": ["Standby Hours"],
  "Time Type 2 - IRL FDS": ["Standby Hours"],
  "Time Type 3 - IRL FDS": ["Standby Hours"],
  "Time Type - UK FCA": ["Standby Hours"]
}
