role_approval_path_mapper = {
    "timesheet_approval_path": "Portugal_Efforts_Approval",
    "timeoff_approval_path_group": "Portugal D1 and above Time Off Approval Path",
    "timeoff_approval_path": "Portugal Time Off Approval Path",
    "l1_manager": "Portugal L1 Manager - Shift",
    "end_user_manager": "End User (Managers)",
    "project_manager": "Portugal Project Manager",
    "hr_manager": "Portugal - GEO HR",
    "default_user_permission": "Project Resource",
    "foreign_manager_emp_type": "Foreign Managers",
    "ot_request_template": "Portugal OT Pre-approval",
    "ot_request_approval_path": "Portugal Overtime Approval Path",
    "ot_request_approval_path_dop": "Portugal Overtime Approval Path - DOP",
    "schedule_type": "Shift Schedule",
    "payrule_for_portugal": "Portugal Custom Payrule",
    "payrule_for_clockin": "Portugal Clockin TS Payrule",
    "timesheet_for_portugal_travelport": "Portugal Travelport Timesheet",
    "timesheet_for_portugal": "Portugal Timesheet",
    "time_zone": "(UTC+1:00) Central European Standard Time",
    "timesheet_system_approval_path": "System Approval",
    "timesheet_period": "Weekly starting on Monday",
    "punch_entry_policy": "Portugal Punch Entry",
    "schedule_policy": "Portugal Schedule Policy"
}
