instance = 'production'
region = 'us-east-1'
environment = 'production'
company_key = f"airflow{region.replace('-', '')}"
execution_timeout_days = 14
child_dag_max_active_runs = 10
replicon_conn_id = 'airflow-replicon-admin'
airflow_connector_ui_connid = 'airflow_connector_ui_endpoint'
hmac_secret = 'airflow_connector_ui_hmac_secret'
can_run_batch_task_var_name = f'standard_bamboohr_disable_user_{instance}_can_run_batch_task'
provider = 'bamboohr'
workflow = 'disable_user'
