timesheet_template={
    # ── W139 Wipro IT Services SRL ────
    "W139|01|Permanent": {
        "timesheet_template": "RO_WIPRO_IT_SERVICES",
        "punch_policy": "Romania_Wipro_Punch_Policy",
        "time_off_template": "Time Off",
        "payrule": "Romania IT Services payrule",
        "schedule_policy": "Romania",
        "schedule": "Shift Schedule",
    },
    "W139|02|Permanent": {
        "timesheet_template": "RO_WIPRO_IT_SERVICES",
        "punch_policy": "Romania_Wipro_Punch_Policy",
        "time_off_template": "Time Off",
        "payrule": "Romania IT Services payrule",
        "schedule_policy": "Romania",
        "schedule": "Shift Schedule",
    },
    "W139|03|Permanent": {
        "timesheet_template": "RO_WIPRO_IT_SERVICES_Schedule",
        "punch_policy": "Romania Flexible Punch Policy",
        "time_off_template": "Time Off",
        "payrule": "Romania IT Services payrule",
        "schedule_policy": "Romania Flexible Shift",
        "schedule": "Shift Schedule",
    },
    "W139|04|Contract": {
        "timesheet_template": "RO WIPRO_IT_SERVICES Part Time",
        "punch_policy": "Romania_Wipro_Punch_Policy",
        "time_off_template": "Time Off",
        "payrule": "Romania IT Services payrule",
        "schedule_policy": "Romania",
        "schedule": "Shift Schedule",
    },
    "W139|05|Contract": {
        "timesheet_template": "RO WIPRO_IT_SERVICES Part Time",
        "punch_policy": "Romania_Wipro_Punch_Policy",
        "time_off_template": "Time Off",
        "payrule": "Romania IT Services payrule",
        "schedule_policy": "Romania",
        "schedule": "Shift Schedule",
    },
    "W139|06|Contract": {
        "timesheet_template": "RO WIPRO_IT_SERVICES Part Time",
        "punch_policy": "Romania_Wipro_Punch_Policy",
        "time_off_template": "Time Off",
        "payrule": "Romania IT Services payrule",
        "schedule_policy": "Romania",
        "schedule": "Shift Schedule",
    },
    "W139|07|Contract": {
        "timesheet_template": "RO WIPRO_IT_SERVICES Part Time",
        "punch_policy": "Romania_Wipro_Punch_Policy",
        "time_off_template": "Time Off",
        "payrule": "Romania IT Services payrule",
        "schedule_policy": "Romania",
        "schedule": "Shift Schedule",
    },
    "W139|08|Contract": {
        "timesheet_template": "RO WIPRO_IT_SERVICES Part Time",
        "punch_policy": "Romania_Wipro_Punch_Policy",
        "time_off_template": "Time Off",
        "payrule": "Romania IT Services payrule",
        "schedule_policy": "Romania",
        "schedule": "Shift Schedule",
    },
    "W139|09|Contract": {
        "timesheet_template": "RO WIPRO_IT_SERVICES Part Time",
        "punch_policy": "Romania_Wipro_Punch_Policy",
        "time_off_template": "Time Off",
        "payrule": "Romania IT Services payrule",
        "schedule_policy": "Romania",
        "schedule": "Shift Schedule",
    },
    "W139|10|Contract": {
        "timesheet_template": "RO WIPRO_IT_SERVICES Part Time",
        "punch_policy": "Romania_Wipro_Punch_Policy",
        "time_off_template": "Time Off",
        "payrule": "Romania IT Services payrule",
        "schedule_policy": "Romania",
        "schedule": "Shift Schedule",
    },
    "W139|11|Contract": {
        "timesheet_template": "RO WIPRO_IT_SERVICES Part Time",
        "punch_policy": "Romania_Wipro_Punch_Policy",
        "time_off_template": "Time Off",
        "payrule": "Romania IT Services payrule",
        "schedule_policy": "Romania",
        "schedule": "Shift Schedule",
    },
    "W139|12|Contract": {
        "timesheet_template": "RO WIPRO_IT_SERVICES Part Time",
        "punch_policy": "Romania_Wipro_Punch_Policy",
        "time_off_template": "Time Off",
        "payrule": "Romania IT Services payrule",
        "schedule_policy": "Romania",
        "schedule": "Shift Schedule",
    },
    "W139|13|Contract": {
        "timesheet_template": "RO WIPRO_IT_SERVICES Part Time",
        "punch_policy": "Romania_Wipro_Punch_Policy",
        "time_off_template": "Time Off",
        "payrule": "Romania IT Services payrule",
        "schedule_policy": "Romania",
        "schedule": "Shift Schedule",
    },
    "W139|14|Permanent": {
        "timesheet_template": "RO_WIPRO_IT_SERVICES",
        "punch_policy": "Romania_Wipro_Punch_Policy",
        "time_off_template": "Time Off",
        "payrule": "Romania IT Services payrule",
        "schedule_policy": "Romania",
        "schedule": "Shift Schedule",
    },
    "W139|15|Permanent": {
        "timesheet_template": "RO_WIPRO_IT_SERVICES",
        "punch_policy": "Romania_Wipro_Punch_Policy",
        "time_off_template": "Time Off",
        "payrule": "Romania IT Services payrule",
        "schedule_policy": "Romania",
        "schedule": "Shift Schedule",
    },
    "W139|16|Permanent": {
        "timesheet_template": "RO_WIPRO_IT_SERVICES",
        "punch_policy": "Romania_Wipro_Punch_Policy",
        "time_off_template": "Time Off",
        "payrule": "Romania IT Services payrule",
        "schedule_policy": "Romania",
        "schedule": "Shift Schedule",
    },
    # ── W204 Wipro Technologies SRL ───
    "W204|01|Permanent": {
        "timesheet_template": "RO_WIPRO_TECHNOLOGIES",
        "punch_policy": "Romania_Wipro_Punch_Policy",
        "time_off_template": "Time Off",
        "payrule": "Romania Technologies payrule",
        "schedule_policy": "Romania",
        "schedule": "Shift Schedule",
    },
    "W204|02|Permanent": {
        "timesheet_template": "RO_WIPRO_TECHNOLOGIES",
        "punch_policy": "Romania_Wipro_Punch_Policy",
        "time_off_template": "Time Off",
        "payrule": "Romania Technologies payrule",
        "schedule_policy": "Romania",
        "schedule": "Shift Schedule",
    },
    "W204|03|Permanent": {
        "timesheet_template": "RO_WIPRO_TECHNOLOGIES_Schedule",
        "punch_policy": "Romania Flexible Punch Policy",
        "time_off_template": "Time Off",
        "payrule": "Romania Technologies payrule",
        "schedule_policy": "Romania Flexible Shift",
        "schedule": "Shift Schedule",
    },
    "W204|04|Contract": {
        "timesheet_template": "RO_WIPRO_TECHNOLOGIES Part Time",
        "punch_policy": "Romania_Wipro_Punch_Policy",
        "time_off_template": "Time Off",
        "payrule": "Romania Technologies payrule",
        "schedule_policy": "Romania",
        "schedule": "Shift Schedule",
    },
    "W204|05|Contract": {
        "timesheet_template": "RO_WIPRO_TECHNOLOGIES Part Time",
        "punch_policy": "Romania_Wipro_Punch_Policy",
        "time_off_template": "Time Off",
        "payrule": "Romania Technologies payrule",
        "schedule_policy": "Romania",
        "schedule": "Shift Schedule",
    },
    "W204|06|Contract": {
        "timesheet_template": "RO_WIPRO_TECHNOLOGIES Part Time",
        "punch_policy": "Romania_Wipro_Punch_Policy",
        "time_off_template": "Time Off",
        "payrule": "Romania Technologies payrule",
        "schedule_policy": "Romania",
        "schedule": "Shift Schedule",
    },
    "W204|07|Contract": {
        "timesheet_template": "RO_WIPRO_TECHNOLOGIES Part Time",
        "punch_policy": "Romania_Wipro_Punch_Policy",
        "time_off_template": "Time Off",
        "payrule": "Romania Technologies payrule",
        "schedule_policy": "Romania",
        "schedule": "Shift Schedule",
    },
    "W204|08|Contract": {
        "timesheet_template": "RO_WIPRO_TECHNOLOGIES Part Time",
        "punch_policy": "Romania_Wipro_Punch_Policy",
        "time_off_template": "Time Off",
        "payrule": "Romania Technologies payrule",
        "schedule_policy": "Romania",
        "schedule": "Shift Schedule",
    },
    "W204|09|Contract": {
        "timesheet_template": "RO_WIPRO_TECHNOLOGIES Part Time",
        "punch_policy": "Romania_Wipro_Punch_Policy",
        "time_off_template": "Time Off",
        "payrule": "Romania Technologies payrule",
        "schedule_policy": "Romania",
        "schedule": "Shift Schedule",
    },
    "W204|10|Contract": {
        "timesheet_template": "RO_WIPRO_TECHNOLOGIES Part Time",
        "punch_policy": "Romania_Wipro_Punch_Policy",
        "time_off_template": "Time Off",
        "payrule": "Romania Technologies payrule",
        "schedule_policy": "Romania",
        "schedule": "Shift Schedule",
    },
    "W204|11|Contract": {
        "timesheet_template": "RO_WIPRO_TECHNOLOGIES Part Time",
        "punch_policy": "Romania_Wipro_Punch_Policy",
        "time_off_template": "Time Off",
        "payrule": "Romania Technologies payrule",
        "schedule_policy": "Romania",
        "schedule": "Shift Schedule",
    },
    "W204|12|Contract": {
        "timesheet_template": "RO_WIPRO_TECHNOLOGIES Part Time",
        "punch_policy": "Romania_Wipro_Punch_Policy",
        "time_off_template": "Time Off",
        "payrule": "Romania Technologies payrule",
        "schedule_policy": "Romania",
        "schedule": "Shift Schedule",
    },
    "W204|13|Contract": {
        "timesheet_template": "RO_WIPRO_TECHNOLOGIES Part Time",
        "punch_policy": "Romania_Wipro_Punch_Policy",
        "time_off_template": "Time Off",
        "payrule": "Romania Technologies payrule",
        "schedule_policy": "Romania",
        "schedule": "Shift Schedule",
    },
    "W204|14|Permanent": {
        "timesheet_template": "RO_WIPRO_TECHNOLOGIES",
        "punch_policy": "Romania_Wipro_Punch_Policy",
        "time_off_template": "Time Off",
        "payrule": "Romania Technologies payrule",
        "schedule_policy": "Romania",
        "schedule": "Shift Schedule",
    },
    "W204|15|Permanent": {
        "timesheet_template": "RO_WIPRO_TECHNOLOGIES",
        "punch_policy": "Romania_Wipro_Punch_Policy",
        "time_off_template": "Time Off",
        "payrule": "Romania Technologies payrule",
        "schedule_policy": "Romania",
        "schedule": "Shift Schedule",
    },
    "W204|16|Permanent": {
        "timesheet_template": "RO_WIPRO_TECHNOLOGIES",
        "punch_policy": "Romania_Wipro_Punch_Policy",
        "time_off_template": "Time Off",
        "payrule": "Romania Technologies payrule",
        "schedule_policy": "Romania",
        "schedule": "Shift Schedule",
    },
    # ── W163 Wipro Technology Solutions SRL ──
    "W163|01|Permanent": {
        "timesheet_template": "RO_TECHNOLOGY_SOLUTIONS",
        "punch_policy": "Romania_Sol_Wipro_Punch_Policy",
        "time_off_template": "Time Off",
        "payrule": "Romania Technology Solutions payrule",
        "schedule_policy": "Romania",
        "schedule": "Shift Schedule",
    },
    "W163|02|Permanent": {
        "timesheet_template": "RO_TECHNOLOGY_SOLUTIONS",
        "punch_policy": "Romania_Sol_Wipro_Punch_Policy",
        "time_off_template": "Time Off",
        "payrule": "Romania Technology Solutions payrule",
        "schedule_policy": "Romania",
        "schedule": "Shift Schedule",
    },
    "W163|03|Permanent": {
        "timesheet_template": "RO_SOLUTIONS_Schedule",
        "punch_policy": "Romania - SOL Flex Employees",
        "time_off_template": "Time Off",
        "payrule": "Romania Technology Solutions payrule",
        "schedule_policy": "Romania Flexible Shift",
        "schedule": "Shift Schedule",
    },
    "W163|04|Contract": {
        "timesheet_template": "RO_SOLUTIONS Part Time",
        "punch_policy": "Romania_Sol_Wipro_Punch_Policy",
        "time_off_template": "Time Off",
        "payrule": "Romania Technology Solutions payrule",
        "schedule_policy": "Romania",
        "schedule": "Shift Schedule",
    },
    "W163|05|Contract": {
        "timesheet_template": "RO_SOLUTIONS Part Time",
        "punch_policy": "Romania_Sol_Wipro_Punch_Policy",
        "time_off_template": "Time Off",
        "payrule": "Romania Technology Solutions payrule",
        "schedule_policy": "Romania",
        "schedule": "Shift Schedule",
    },
    "W163|06|Contract": {
        "timesheet_template": "RO_SOLUTIONS Part Time",
        "punch_policy": "Romania_Sol_Wipro_Punch_Policy",
        "time_off_template": "Time Off",
        "payrule": "Romania Technology Solutions payrule",
        "schedule_policy": "Romania",
        "schedule": "Shift Schedule",
    },
    "W163|07|Contract": {
        "timesheet_template": "RO_SOLUTIONS Part Time",
        "punch_policy": "Romania_Sol_Wipro_Punch_Policy",
        "time_off_template": "Time Off",
        "payrule": "Romania Technology Solutions payrule",
        "schedule_policy": "Romania",
        "schedule": "Shift Schedule",
    },
    "W163|08|Contract": {
        "timesheet_template": "RO_SOLUTIONS Part Time",
        "punch_policy": "Romania_Sol_Wipro_Punch_Policy",
        "time_off_template": "Time Off",
        "payrule": "Romania Technology Solutions payrule",
        "schedule_policy": "Romania",
        "schedule": "Shift Schedule",
    },
    "W163|09|Contract": {
        "timesheet_template": "RO_SOLUTIONS Part Time",
        "punch_policy": "Romania_Sol_Wipro_Punch_Policy",
        "time_off_template": "Time Off",
        "payrule": "Romania Technology Solutions payrule",
        "schedule_policy": "Romania",
        "schedule": "Shift Schedule",
    },
    "W163|10|Contract": {
        "timesheet_template": "RO_SOLUTIONS Part Time",
        "punch_policy": "Romania_Sol_Wipro_Punch_Policy",
        "time_off_template": "Time Off",
        "payrule": "Romania Technology Solutions payrule",
        "schedule_policy": "Romania",
        "schedule": "Shift Schedule",
    },
    "W163|11|Contract": {
        "timesheet_template": "RO_SOLUTIONS Part Time",
        "punch_policy": "Romania_Sol_Wipro_Punch_Policy",
        "time_off_template": "Time Off",
        "payrule": "Romania Technology Solutions payrule",
        "schedule_policy": "Romania",
        "schedule": "Shift Schedule",
    },
    "W163|12|Contract": {
        "timesheet_template": "RO_SOLUTIONS Part Time",
        "punch_policy": "Romania_Sol_Wipro_Punch_Policy",
        "time_off_template": "Time Off",
        "payrule": "Romania Technology Solutions payrule",
        "schedule_policy": "Romania",
        "schedule": "Shift Schedule",
    },
    "W163|13|Contract": {
        "timesheet_template": "RO_SOLUTIONS Part Time",
        "punch_policy": "Romania_Sol_Wipro_Punch_Policy",
        "time_off_template": "Time Off",
        "payrule": "Romania Technology Solutions payrule",
        "schedule_policy": "Romania",
        "schedule": "Shift Schedule",
    },
    "W163|14|Permanent": {
        "timesheet_template": "RO_SOLUTIONS 12/24",
        "punch_policy": "Romania - Solutions - 12 Hours Shift Employees",
        "time_off_template": "Time Off",
        "payrule": "Romania Technology Solutions payrule - 12 Hours",
        "schedule_policy": "ROM - SOL 12/24",
        "schedule": "Shift Schedule",
    },
    "W163|15|Permanent": {
        "timesheet_template": "RO_TECHNOLOGY_SOLUTIONS",
        "punch_policy": "Romania_Sol_Wipro_Punch_Policy",
        "time_off_template": "Time Off",
        "payrule": "Romania Technology Solutions payrule",
        "schedule_policy": "Romania",
        "schedule": "Shift Schedule",
    },
    "W163|16|Permanent": {
        "timesheet_template": "RO_TECHNOLOGY_SOLUTIONS",
        "punch_policy": "Romania_Sol_Wipro_Punch_Policy",
        "time_off_template": "Time Off",
        "payrule": "Romania Technology Solutions payrule",
        "schedule_policy": "Romania",
        "schedule": "Shift Schedule",
    },
}
