region = 'us-east-1'
environment = 'pre-production'
instance = "uat"
company_key = 'guidehouseincsb'
replicon_conn_id = 'polaris_guidehouseincsb'
deltek_cospoint_conn_id = 'deltek_costpoint_guidehouseincsb'
last_run_date_var_name = f'guidehouse_deltek_costpoint_timesheet_sync_last_run_date_{instance}'
time_zone = 'US/Eastern'
execution_timeout_days = 14
child_dag_max_active_runs = 2
can_run_batch_task_var_name = f'guidehouse_deltek_costpoint_timesheet_sync_can_run_batch_task_{instance}'
group_by_project_var_name = f'guidehouse_deltek_costpoint_timesheet_sync_group_by_project_{instance}'
pay_type_oef_var_name = f'guidehouse_deltek_costpoint_timesheet_sync_pay_type_oef_name_{instance}'
tenant_email = '{{ var.value.dagrun_internal_testing_email }},guidehousedeltekprojectteam@deltek.com,ghcostpoint@guidehouse.com,timekeeping@guidehouse.com'
internal_email = '{{ var.value.dagrun_internal_testing_email }}'
line_type = 'A'
regular_pay_type = 'R'
cp_rep_webhook_secret = f"cp_rep_webhook_secret_{instance}"
is_sync_time_off_bookings = 'true'
use_task_based_allocation = True #new task allocation
do_not_pass_polaris_plc = False
do_not_sync_time_if_other_source = True
project_source_custom_field_name = 'Source System'
project_source_custom_field_value = 'Costpoint'
user_source_oef_name = 'Source'
user_source_oef_value = 'Costpoint'
send_blank_plc_account_org = True
resolve_plc_from_task_user_pairs = True
sync_to_open_period = True
reversal_timesheet_type = 'C'

main_dag_id = f'guidehouse_deltek_costpoint_timesheet_sync_{instance}'
