sick_leave_placeholder_timeoff_types = [
  {
    "location_level_2": "All",
    "location_level_3": "All",
    "company_code": "All",
    "buisness_unit_level_1": "All",
    "functional_segment": "All",
    "functional_sub_segment": "All",
    "buisness_unit_level_2": "All",
    "cost_center": "All",
    "department": "All",
    "reg_temp": "All",
    "full_part": "All",
    "pay_type": "All",
    "activity_type": "All",
    "job_level": "All",
    "std_hrs": "37.5",
    "placeholder_policy": "[IRE] Sick Leave_37.5"
  },
  {
    "location_level_2": "All",
    "location_level_3": "All",
    "company_code": "All",
    "buisness_unit_level_1": "All",
    "functional_segment": "All",
    "functional_sub_segment": "All",
    "buisness_unit_level_2": "All",
    "cost_center": "All",
    "department": "All",
    "reg_temp": "All",
    "full_part": "All",
    "pay_type": "All",
    "activity_type": "All",
    "job_level": "All",
    "std_hrs": "30",
    "placeholder_policy": "[IRE] Sick Leave_30"
  },
  {
    "location_level_2": "All",
    "location_level_3": "All",
    "company_code": "All",
    "buisness_unit_level_1": "All",
    "functional_segment": "All",
    "functional_sub_segment": "All",
    "buisness_unit_level_2": "All",
    "cost_center": "All",
    "department": "All",
    "reg_temp": "All",
    "full_part": "All",
    "pay_type": "All",
    "activity_type": "All",
    "job_level": "All",
    "std_hrs": "25",
    "placeholder_policy": "[IRE] Sick Leave_25"
  },
  {
    "location_level_2": "All",
    "location_level_3": "All",
    "company_code": "All",
    "buisness_unit_level_1": "All",
    "functional_segment": "All",
    "functional_sub_segment": "All",
    "buisness_unit_level_2": "All",
    "cost_center": "All",
    "department": "All",
    "reg_temp": "All",
    "full_part": "All",
    "pay_type": "All",
    "activity_type": "All",
    "job_level": "All",
    "std_hrs": "24",
    "placeholder_policy": "[IRE] Sick Leave_24"
  },
  {
    "location_level_2": "All",
    "location_level_3": "All",
    "company_code": "All",
    "buisness_unit_level_1": "All",
    "functional_segment": "All",
    "functional_sub_segment": "All",
    "buisness_unit_level_2": "All",
    "cost_center": "All",
    "department": "All",
    "reg_temp": "All",
    "full_part": "All",
    "pay_type": "All",
    "activity_type": "All",
    "job_level": "All",
    "std_hrs": "21",
    "placeholder_policy": "[IRE] Sick Leave_21"
  },
  {
    "location_level_2": "All",
    "location_level_3": "All",
    "company_code": "All",
    "buisness_unit_level_1": "All",
    "functional_segment": "All",
    "functional_sub_segment": "All",
    "buisness_unit_level_2": "All",
    "cost_center": "All",
    "department": "All",
    "reg_temp": "All",
    "full_part": "All",
    "pay_type": "All",
    "activity_type": "All",
    "job_level": "All",
    "std_hrs": "16",
    "placeholder_policy": "[IRE] Sick Leave_16"
  }
]