holiday_entitlement_mapper = [
    {"loc1": "united states of america", "loc2": "all", "exclude_loc2": None, "loc3": None,          "max_hours": 88},
    {"loc1": "canada",                   "loc2": "all", "exclude_loc2": None,          "loc3": None,          "max_hours": 88},
    {"loc1": "germany",                  "loc2": "all", "exclude_loc2": None,          "loc3": "berlin",      "max_hours": 88},
    {"loc1": "germany",                  "loc2": "all", "exclude_loc2": None,          "loc3": "cologne",     "max_hours": 80},
    {"loc1": "france",                   "loc2": "all", "exclude_loc2": None,          "loc3": None,          "max_hours": 72},
    {"loc1": "lithuania",                "loc2": "all", "exclude_loc2": None,          "loc3": None,          "max_hours": 165},
    {"loc1": "united kingdom",           "loc2": "all", "exclude_loc2": None,          "loc3": None,          "max_hours": 64},
    {"loc1": "united arab emirates",                      "loc2": "all", "exclude_loc2": None,          "loc3": None,          "max_hours": 112},
    {"loc1": "india",                    "loc2": "all", "exclude_loc2": None,          "loc3": "chennai",     "max_hours": 72},
    {"loc1": "india",                    "loc2": "all", "exclude_loc2": None,          "loc3": "gurugram",     "max_hours": 64},
    {"loc1": "india",                    "loc2": "all", "exclude_loc2": None,          "loc3": "trivandrum",  "max_hours": 104},
    {"loc1": "india",                    "loc2": "all", "exclude_loc2": None,          "loc3": "nagarcoil",   "max_hours": 72},
    {"loc1": "netherlands",              "loc2": "all", "exclude_loc2": None,          "loc3": None,          "max_hours": 48},
]