null = None
# headers : ['mapper', 'type', 'employee_type', 'country_code', 'location', 'person_type', 'assignment_category', 'flsa', 'job_code', 'value_|_default_uri']
velaw_user_import_mapper = [
    {
        "mapper": "Yes",
        "type": "Timesheet Period",
        "employee_type": "",
        "country_code": "",
        "location": "",
        "person_type": "",
        "assignment_category": "",
        "flsa": "",
        "job_code": "",
        "value_|_default_uri": "Weekly starting on Sunday"
    },
    {
        "mapper": "Yes",
        "type": "Work Week",
        "employee_type": "",
        "country_code": "",
        "location": "",
        "person_type": "",
        "assignment_category": "",
        "flsa": "",
        "job_code": "",
        "value_|_default_uri": "Sunday - Saturday | urn:replicon:day-of-week:sunday"
    },
    {
        "mapper": "Yes",
        "type": "Timesheet Template",
        "employee_type": "Non-Exempt Full Time",
        "country_code": "",
        "location": "",
        "person_type": "",
        "assignment_category": "",
        "flsa": "",
        "job_code": "",
        "value_|_default_uri": "*V&E - Non-Exempt Full Time, 9/75 and 80"
    },
    {
        "mapper": "Yes",
        "type": "Timesheet Template",
        "employee_type": "Non-Exempt 80",
        "country_code": "",
        "location": "",
        "person_type": "",
        "assignment_category": "",
        "flsa": "",
        "job_code": "",
        "value_|_default_uri": "*V&E - Non-Exempt Full Time, 9/75 and 80"
    },
    {
        "mapper": "Yes",
        "type": "Timesheet Template",
        "employee_type": "Paralegal",
        "country_code": "",
        "location": "",
        "person_type": "",
        "assignment_category": "",
        "flsa": "",
        "job_code": "",
        "value_|_default_uri": "*V&E - Paralegal Full Time, 80 and Hourly"
    },
    {
        "mapper": "Yes",
        "type": "Timesheet Template",
        "employee_type": "Paralegal 80",
        "country_code": "",
        "location": "",
        "person_type": "",
        "assignment_category": "",
        "flsa": "",
        "job_code": "",
        "value_|_default_uri": "*V&E - Paralegal Full Time, 80 and Hourly"
    },
    {
        "mapper": "Yes",
        "type": "Timesheet Template",
        "employee_type": "California Non-Exempt Full Time",
        "country_code": "",
        "location": "",
        "person_type": "",
        "assignment_category": "",
        "flsa": "",
        "job_code": "",
        "value_|_default_uri": "*V&E - California Non-Exempt  Full Time and 80"
    },
    {
        "mapper": "Yes",
        "type": "Timesheet Template",
        "employee_type": "California Non-Exempt 80",
        "country_code": "",
        "location": "",
        "person_type": "",
        "assignment_category": "",
        "flsa": "",
        "job_code": "",
        "value_|_default_uri": "*V&E - California Non-Exempt  Full Time and 80"
    },
    {
        "mapper": "Yes",
        "type": "Timesheet Template",
        "employee_type": "Non Exempt Hourly",
        "country_code": "",
        "location": "",
        "person_type": "",
        "assignment_category": "",
        "flsa": "",
        "job_code": "",
        "value_|_default_uri": "*V&E - Non-Exempt Hourly"
    },
    {
        "mapper": "Yes",
        "type": "Timesheet Template",
        "employee_type": "California Hourly",
        "country_code": "",
        "location": "",
        "person_type": "",
        "assignment_category": "",
        "flsa": "",
        "job_code": "",
        "value_|_default_uri": "*V&E - California Hourly"
    },
    {
        "mapper": "Yes",
        "type": "Timesheet Template",
        "employee_type": "Paralegal Part-Time",
        "country_code": "",
        "location": "",
        "person_type": "",
        "assignment_category": "",
        "flsa": "",
        "job_code": "",
        "value_|_default_uri": "*V&E - Paralegal Full Time, 80 and Hourly"
    },
    {
        "mapper": "Yes",
        "type": "Timesheet Template",
        "employee_type": "UK Full Time and Part Time_NE",
        "country_code": "",
        "location": "",
        "person_type": "",
        "assignment_category": "",
        "flsa": "",
        "job_code": "",
        "value_|_default_uri": "*V&E - UK Full Time and Part Time"
    },
    {
        "mapper": "Yes",
        "type": "Payrule",
        "employee_type": "Non-Exempt Full Time",
        "country_code": "",
        "location": "",
        "person_type": "",
        "assignment_category": "",
        "flsa": "",
        "job_code": "",
        "value_|_default_uri": "*V&E - Non-Exempt 80% and 100% and 9_75"
    },
    {
        "mapper": "Yes",
        "type": "Payrule",
        "employee_type": "Non-Exempt 80",
        "country_code": "",
        "location": "",
        "person_type": "",
        "assignment_category": "",
        "flsa": "",
        "job_code": "",
        "value_|_default_uri": "*V&E - Non-Exempt 80% and 100% and 9_75"
    },
    {
        "mapper": "Yes",
        "type": "Payrule",
        "employee_type": "Paralegal",
        "country_code": "",
        "location": "",
        "person_type": "",
        "assignment_category": "",
        "flsa": "",
        "job_code": "",
        "value_|_default_uri": "*V&E - Paralegal"
    },
    {
        "mapper": "Yes",
        "type": "Payrule",
        "employee_type": "Paralegal 80",
        "country_code": "",
        "location": "",
        "person_type": "",
        "assignment_category": "",
        "flsa": "",
        "job_code": "",
        "value_|_default_uri": "*V&E - Paralegal"
    },
    {
        "mapper": "Yes",
        "type": "Payrule",
        "employee_type": "California Non-Exempt Full Time",
        "country_code": "",
        "location": "",
        "person_type": "",
        "assignment_category": "",
        "flsa": "",
        "job_code": "",
        "value_|_default_uri": "*V&E - California Pay-rule - Salaried"
    },
    {
        "mapper": "Yes",
        "type": "Payrule",
        "employee_type": "California Non-Exempt 80",
        "country_code": "",
        "location": "",
        "person_type": "",
        "assignment_category": "",
        "flsa": "",
        "job_code": "",
        "value_|_default_uri": "*V&E - California Pay-rule - Salaried"
    },
    {
        "mapper": "Yes",
        "type": "Payrule",
        "employee_type": "Non Exempt Hourly",
        "country_code": "",
        "location": "",
        "person_type": "",
        "assignment_category": "",
        "flsa": "",
        "job_code": "",
        "value_|_default_uri": "*V&E - Non Exempt Part-Time"
    },
    {
        "mapper": "Yes",
        "type": "Payrule",
        "employee_type": "California Hourly",
        "country_code": "",
        "location": "",
        "person_type": "",
        "assignment_category": "",
        "flsa": "",
        "job_code": "",
        "value_|_default_uri": "*V&E - California Hourly"
    },
    {
        "mapper": "Yes",
        "type": "Payrule",
        "employee_type": "Paralegal Part-Time",
        "country_code": "",
        "location": "",
        "person_type": "",
        "assignment_category": "",
        "flsa": "",
        "job_code": "",
        "value_|_default_uri": "*V&E - Paralegal Part-Time"
    },
    {
        "mapper": "Yes",
        "type": "Payrule",
        "employee_type": "UK Full Time and Part Time_NE",
        "country_code": "",
        "location": "",
        "person_type": "",
        "assignment_category": "",
        "flsa": "",
        "job_code": "",
        "value_|_default_uri": "*V&E - UK Full Time and Part Time"
    },
    {
        "mapper": "Yes",
        "type": "Payrule",
        "employee_type": "Exempt Full Time",
        "country_code": "",
        "location": "",
        "person_type": "",
        "assignment_category": "",
        "flsa": "",
        "job_code": "",
        "value_|_default_uri": "*V&E - Placeholder Pay-rule"
    },
    {
        "mapper": "Yes",
        "type": "Payrule",
        "employee_type": "Exempt 80",
        "country_code": "",
        "location": "",
        "person_type": "",
        "assignment_category": "",
        "flsa": "",
        "job_code": "",
        "value_|_default_uri": "*V&E - Placeholder Pay-rule"
    },
    {
        "mapper": "Yes",
        "type": "Payrule",
        "employee_type": "Attorney - California",
        "country_code": "",
        "location": "",
        "person_type": "",
        "assignment_category": "",
        "flsa": "",
        "job_code": "",
        "value_|_default_uri": "*V&E - Placeholder Pay-rule"
    },
    {
        "mapper": "Yes",
        "type": "Payrule",
        "employee_type": "Attorney - UK",
        "country_code": "",
        "location": "",
        "person_type": "",
        "assignment_category": "",
        "flsa": "",
        "job_code": "",
        "value_|_default_uri": "*V&E - Placeholder Pay-rule"
    },
    {
        "mapper": "Yes",
        "type": "Payrule",
        "employee_type": "Others",
        "country_code": "",
        "location": "",
        "person_type": "",
        "assignment_category": "",
        "flsa": "",
        "job_code": "",
        "value_|_default_uri": "*V&E - Placeholder Pay-rule"
    },
    {
        "mapper": "Yes",
        "type": "TimeZone",
        "employee_type": "",
        "country_code": "US",
        "location": "Austin",
        "person_type": "",
        "assignment_category": "",
        "flsa": "",
        "job_code": "",
        "value_|_default_uri": "(UTC-6:00) Central Standard Time | urn:replicon:time-zone:america-chicago"
    },
    {
        "mapper": "Yes",
        "type": "TimeZone",
        "employee_type": "",
        "country_code": "US",
        "location": "Dallas",
        "person_type": "",
        "assignment_category": "",
        "flsa": "",
        "job_code": "",
        "value_|_default_uri": "(UTC-6:00) Central Standard Time | urn:replicon:time-zone:america-chicago"
    },
    {
        "mapper": "Yes",
        "type": "TimeZone",
        "employee_type": "",
        "country_code": "US",
        "location": "Houston",
        "person_type": "",
        "assignment_category": "",
        "flsa": "",
        "job_code": "",
        "value_|_default_uri": "(UTC-6:00) Central Standard Time | urn:replicon:time-zone:america-chicago"
    },
    {
        "mapper": "Yes",
        "type": "TimeZone",
        "employee_type": "",
        "country_code": "US",
        "location": "New York",
        "person_type": "",
        "assignment_category": "",
        "flsa": "",
        "job_code": "",
        "value_|_default_uri": "(UTC-5:00) Eastern Standard Time | urn:replicon:time-zone:america-new-york"
    },
    {
        "mapper": "Yes",
        "type": "TimeZone",
        "employee_type": "",
        "country_code": "US",
        "location": "Washington",
        "person_type": "",
        "assignment_category": "",
        "flsa": "",
        "job_code": "",
        "value_|_default_uri": "(UTC-5:00) Eastern Standard Time | urn:replicon:time-zone:america-new-york"
    },
    {
        "mapper": "Yes",
        "type": "TimeZone",
        "employee_type": "",
        "country_code": "US",
        "location": "Richmond",
        "person_type": "",
        "assignment_category": "",
        "flsa": "",
        "job_code": "",
        "value_|_default_uri": "(UTC-5:00) Eastern Standard Time | urn:replicon:time-zone:america-new-york"
    },
    {
        "mapper": "Yes",
        "type": "TimeZone",
        "employee_type": "",
        "country_code": "US",
        "location": "San Francisco",
        "person_type": "",
        "assignment_category": "",
        "flsa": "",
        "job_code": "",
        "value_|_default_uri": "(UTC-8:00) Pacific Standard Time | urn:replicon:time-zone:america-los-angeles"
    },
    {
        "mapper": "Yes",
        "type": "TimeZone",
        "employee_type": "",
        "country_code": "GB",
        "location": "London",
        "person_type": "",
        "assignment_category": "",
        "flsa": "",
        "job_code": "",
        "value_|_default_uri": "(UTC+0:00) GMT Standard Time | urn:replicon:time-zone:europe-london"
    },
    {
        "mapper": "Yes",
        "type": "Holiday Calendar",
        "employee_type": "",
        "country_code": "US",
        "location": "Austin",
        "person_type": "",
        "assignment_category": "",
        "flsa": "",
        "job_code": "",
        "value_|_default_uri": "Holidays for Texas"
    },
    {
        "mapper": "Yes",
        "type": "Holiday Calendar",
        "employee_type": "",
        "country_code": "US",
        "location": "Dallas",
        "person_type": "",
        "assignment_category": "",
        "flsa": "",
        "job_code": "",
        "value_|_default_uri": "Holidays for Texas"
    },
    {
        "mapper": "Yes",
        "type": "Holiday Calendar",
        "employee_type": "",
        "country_code": "US",
        "location": "Houston",
        "person_type": "",
        "assignment_category": "",
        "flsa": "",
        "job_code": "",
        "value_|_default_uri": "Holidays for Texas"
    },
    {
        "mapper": "Yes",
        "type": "Holiday Calendar",
        "employee_type": "",
        "country_code": "US",
        "location": "New York",
        "person_type": "",
        "assignment_category": "",
        "flsa": "",
        "job_code": "",
        "value_|_default_uri": "Holidays for East/West Coast"
    },
    {
        "mapper": "Yes",
        "type": "Holiday Calendar",
        "employee_type": "",
        "country_code": "US",
        "location": "Washington",
        "person_type": "",
        "assignment_category": "",
        "flsa": "",
        "job_code": "",
        "value_|_default_uri": "Holidays for East/West Coast"
    },
    {
        "mapper": "Yes",
        "type": "Holiday Calendar",
        "employee_type": "",
        "country_code": "US",
        "location": "Richmond",
        "person_type": "",
        "assignment_category": "",
        "flsa": "",
        "job_code": "",
        "value_|_default_uri": "Holidays for East/West Coast"
    },
    {
        "mapper": "Yes",
        "type": "Holiday Calendar",
        "employee_type": "",
        "country_code": "US",
        "location": "San Francisco",
        "person_type": "",
        "assignment_category": "",
        "flsa": "",
        "job_code": "",
        "value_|_default_uri": "Holidays for East/West Coast"
    },
    {
        "mapper": "Yes",
        "type": "Holiday Calendar",
        "employee_type": "",
        "country_code": "GB",
        "location": "London",
        "person_type": "",
        "assignment_category": "",
        "flsa": "",
        "job_code": "",
        "value_|_default_uri": "Holidays for United Kingdom"
    },
    {
        "mapper": "Yes",
        "type": "Schedule",
        "employee_type": "",
        "country_code": "US",
        "location": "",
        "person_type": "",
        "assignment_category": "",
        "flsa": "Nonexempt",
        "job_code": "",
        "value_|_default_uri": "7.5 hours/day, Su, Sa off"
    },
    {
        "mapper": "Yes",
        "type": "Schedule",
        "employee_type": "",
        "country_code": "US",
        "location": "",
        "person_type": "",
        "assignment_category": "",
        "flsa": "Exempt",
        "job_code": "",
        "value_|_default_uri": "7.5 hours/day, Su, Sa off"
    },
    {
        "mapper": "Yes",
        "type": "Schedule",
        "employee_type": "",
        "country_code": "GB",
        "location": "",
        "person_type": "",
        "assignment_category": "",
        "flsa": "Nonexempt",
        "job_code": "",
        "value_|_default_uri": "7.5 hours/day, Su, Sa off"
    },
    {
        "mapper": "Yes",
        "type": "Schedule",
        "employee_type": "",
        "country_code": "GB",
        "location": "",
        "person_type": "",
        "assignment_category": "",
        "flsa": "Exempt",
        "job_code": "",
        "value_|_default_uri": "7.5 hours/day, Su, Sa off"
    },
    {
        "mapper": "Yes",
        "type": "Timeoff Type",
        "employee_type": "",
        "country_code": "US",
        "location": "All",
        "person_type": "Administrative",
        "assignment_category": "Full-Time Regular",
        "flsa": "Nonexempt",
        "job_code": "All",
        "value_|_default_uri": "Grace Period Hours"
    },
    {
        "mapper": "Yes",
        "type": "Timeoff Type",
        "employee_type": "",
        "country_code": "US",
        "location": "All",
        "person_type": "Administrative",
        "assignment_category": "Part Time 80",
        "flsa": "Nonexempt",
        "job_code": "All",
        "value_|_default_uri": "Grace Period Hours"
    },
    {
        "mapper": "Yes",
        "type": "Timeoff Type",
        "employee_type": "Yes",
        "country_code": "US",
        "location": "All",
        "person_type": "Administrative",
        "assignment_category": "Full-Time Regular",
        "flsa": "Exempt",
        "job_code": "All",
        "value_|_default_uri": "Bereavement"
    },
    {
        "mapper": "Yes",
        "type": "Timeoff Type",
        "employee_type": "Yes",
        "country_code": "US",
        "location": "All",
        "person_type": "Administrative",
        "assignment_category": "Full-Time Regular",
        "flsa": "Nonexempt",
        "job_code": "All",
        "value_|_default_uri": "Bereavement"
    },
    {
        "mapper": "Yes",
        "type": "Timeoff Type",
        "employee_type": "Yes",
        "country_code": "US",
        "location": "All",
        "person_type": "Administrative",
        "assignment_category": "Part Time 80",
        "flsa": "Exempt",
        "job_code": "All",
        "value_|_default_uri": "Bereavement"
    },
    {
        "mapper": "Yes",
        "type": "Timeoff Type",
        "employee_type": "Yes",
        "country_code": "US",
        "location": "All",
        "person_type": "Administrative",
        "assignment_category": "Part Time 80",
        "flsa": "Nonexempt",
        "job_code": "All",
        "value_|_default_uri": "Bereavement"
    },
    {
        "mapper": "Yes",
        "type": "Timeoff Type",
        "employee_type": "Yes",
        "country_code": "US",
        "location": "All",
        "person_type": "Administrative",
        "assignment_category": "Part time 60",
        "flsa": "Exempt",
        "job_code": "All",
        "value_|_default_uri": "Bereavement"
    },
    {
        "mapper": "Yes",
        "type": "Timeoff Type",
        "employee_type": "Yes",
        "country_code": "US",
        "location": "All",
        "person_type": "Administrative",
        "assignment_category": "Part time 60",
        "flsa": "Nonexempt",
        "job_code": "All",
        "value_|_default_uri": "Bereavement"
    },
    {
        "mapper": "Yes",
        "type": "Timeoff Type",
        "employee_type": "",
        "country_code": "US",
        "location": "San Francisco",
        "person_type": "Administrative",
        "assignment_category": "Full-Time Regular",
        "flsa": "Exempt",
        "job_code": "All",
        "value_|_default_uri": "California Exempt Vac"
    },
    {
        "mapper": "Yes",
        "type": "Timeoff Type",
        "employee_type": "",
        "country_code": "US",
        "location": "San Francisco",
        "person_type": "Administrative",
        "assignment_category": "Part Time 80",
        "flsa": "Exempt",
        "job_code": "All",
        "value_|_default_uri": "California Exempt 80%"
    },
    {
        "mapper": "Yes",
        "type": "Timeoff Type",
        "employee_type": "Yes",
        "country_code": "US",
        "location": "All",
        "person_type": "Administrative",
        "assignment_category": "Full-Time Regular",
        "flsa": "Exempt",
        "job_code": "All",
        "value_|_default_uri": "Exempt STD 100%"
    },
    {
        "mapper": "Yes",
        "type": "Timeoff Type",
        "employee_type": "Yes",
        "country_code": "US",
        "location": "All",
        "person_type": "Administrative",
        "assignment_category": "Full-Time Regular",
        "flsa": "Exempt",
        "job_code": "All",
        "value_|_default_uri": "Exempt STD 50%"
    },
    {
        "mapper": "Yes",
        "type": "Timeoff Type",
        "employee_type": "Yes",
        "country_code": "US",
        "location": "All",
        "person_type": "Administrative",
        "assignment_category": "Part Time 80",
        "flsa": "Exempt",
        "job_code": "All",
        "value_|_default_uri": "Exempt 80 STD 100%"
    },
    {
        "mapper": "Yes",
        "type": "Timeoff Type",
        "employee_type": "Yes",
        "country_code": "US",
        "location": "All",
        "person_type": "Administrative",
        "assignment_category": "Part Time 80",
        "flsa": "Exempt",
        "job_code": "All",
        "value_|_default_uri": "Exempt 80 STD 50%"
    },
    {
        "mapper": "Yes",
        "type": "Timeoff Type",
        "employee_type": "Yes",
        "country_code": "US",
        "location": "All",
        "person_type": "Administrative",
        "assignment_category": "Full-Time Regular",
        "flsa": "Nonexempt",
        "job_code": "All",
        "value_|_default_uri": "Non-Exempt STD 100%"
    },
    {
        "mapper": "Yes",
        "type": "Timeoff Type",
        "employee_type": "Yes",
        "country_code": "US",
        "location": "All",
        "person_type": "Administrative",
        "assignment_category": "Full-Time Regular",
        "flsa": "Nonexempt",
        "job_code": "All",
        "value_|_default_uri": "Non-Exempt STD 50%"
    },
    {
        "mapper": "Yes",
        "type": "Timeoff Type",
        "employee_type": "Yes",
        "country_code": "US",
        "location": "All",
        "person_type": "Administrative",
        "assignment_category": "Part Time 80",
        "flsa": "Nonexempt",
        "job_code": "All",
        "value_|_default_uri": "Non-Exempt 80 STD 100%"
    },
    {
        "mapper": "Yes",
        "type": "Timeoff Type",
        "employee_type": "Yes",
        "country_code": "US",
        "location": "All",
        "person_type": "Administrative",
        "assignment_category": "Part Time 80",
        "flsa": "Nonexempt",
        "job_code": "All",
        "value_|_default_uri": "Non-Exempt 80 STD 50%"
    },
    {
        "mapper": "Yes",
        "type": "Timeoff Type",
        "employee_type": "",
        "country_code": "US",
        "location": "Austin",
        "person_type": "Administrative",
        "assignment_category": "Full-Time Regular",
        "flsa": "Exempt",
        "job_code": "All",
        "value_|_default_uri": "Exempt Vacation FT"
    },
    {
        "mapper": "Yes",
        "type": "Timeoff Type",
        "employee_type": "",
        "country_code": "US",
        "location": "Dallas",
        "person_type": "Administrative",
        "assignment_category": "Full-Time Regular",
        "flsa": "Exempt",
        "job_code": "All",
        "value_|_default_uri": "Exempt Vacation FT"
    },
    {
        "mapper": "Yes",
        "type": "Timeoff Type",
        "employee_type": "",
        "country_code": "US",
        "location": "New York",
        "person_type": "Administrative",
        "assignment_category": "Full-Time Regular",
        "flsa": "Exempt",
        "job_code": "All",
        "value_|_default_uri": "Exempt Vacation FT"
    },
    {
        "mapper": "Yes",
        "type": "Timeoff Type",
        "employee_type": "",
        "country_code": "US",
        "location": "Richmond",
        "person_type": "Administrative",
        "assignment_category": "Full-Time Regular",
        "flsa": "Exempt",
        "job_code": "All",
        "value_|_default_uri": "Exempt Vacation FT"
    },
    {
        "mapper": "Yes",
        "type": "Timeoff Type",
        "employee_type": "",
        "country_code": "US",
        "location": "Washington",
        "person_type": "Administrative",
        "assignment_category": "Full-Time Regular",
        "flsa": "Exempt",
        "job_code": "All",
        "value_|_default_uri": "Exempt Vacation FT"
    },
    {
        "mapper": "Yes",
        "type": "Timeoff Type",
        "employee_type": "",
        "country_code": "US",
        "location": "Houston",
        "person_type": "Administrative",
        "assignment_category": "Full-Time Regular",
        "flsa": "Exempt",
        "job_code": "All",
        "value_|_default_uri": "Exempt Vacation FT"
    },
    {
        "mapper": "Yes",
        "type": "Timeoff Type",
        "employee_type": "",
        "country_code": "US",
        "location": "Austin",
        "person_type": "Administrative",
        "assignment_category": "Part Time 80",
        "flsa": "Exempt",
        "job_code": "All",
        "value_|_default_uri": "Exempt Vacation 80%"
    },
    {
        "mapper": "Yes",
        "type": "Timeoff Type",
        "employee_type": "",
        "country_code": "US",
        "location": "Dallas",
        "person_type": "Administrative",
        "assignment_category": "Part Time 80",
        "flsa": "Exempt",
        "job_code": "All",
        "value_|_default_uri": "Exempt Vacation 80%"
    },
    {
        "mapper": "Yes",
        "type": "Timeoff Type",
        "employee_type": "",
        "country_code": "US",
        "location": "New York",
        "person_type": "Administrative",
        "assignment_category": "Part Time 80",
        "flsa": "Exempt",
        "job_code": "All",
        "value_|_default_uri": "Exempt Vacation 80%"
    },
    {
        "mapper": "Yes",
        "type": "Timeoff Type",
        "employee_type": "",
        "country_code": "US",
        "location": "Richmond",
        "person_type": "Administrative",
        "assignment_category": "Part Time 80",
        "flsa": "Exempt",
        "job_code": "All",
        "value_|_default_uri": "Exempt Vacation 80%"
    },
    {
        "mapper": "Yes",
        "type": "Timeoff Type",
        "employee_type": "",
        "country_code": "US",
        "location": "Washington",
        "person_type": "Administrative",
        "assignment_category": "Part Time 80",
        "flsa": "Exempt",
        "job_code": "All",
        "value_|_default_uri": "Exempt Vacation 80%"
    },
    {
        "mapper": "Yes",
        "type": "Timeoff Type",
        "employee_type": "",
        "country_code": "US",
        "location": "Houston",
        "person_type": "Administrative",
        "assignment_category": "Part Time 80",
        "flsa": "Exempt",
        "job_code": "All",
        "value_|_default_uri": "Exempt Vacation 80%"
    },
    {
        "mapper": "Yes",
        "type": "Timeoff Type",
        "employee_type": "",
        "country_code": "US",
        "location": "All",
        "person_type": "Administrative",
        "assignment_category": "Full-Time Regular",
        "flsa": "Nonexempt",
        "job_code": "All",
        "value_|_default_uri": "Firm Holiday"
    },
    {
        "mapper": "Yes",
        "type": "Timeoff Type",
        "employee_type": "",
        "country_code": "US",
        "location": "All",
        "person_type": "Administrative",
        "assignment_category": "Part Time 80",
        "flsa": "Nonexempt",
        "job_code": "All",
        "value_|_default_uri": "Firm Holiday"
    },
    {
        "mapper": "Yes",
        "type": "Timeoff Type",
        "employee_type": "",
        "country_code": "US",
        "location": "All",
        "person_type": "Administrative",
        "assignment_category": "Student Intern",
        "flsa": "Nonexempt",
        "job_code": "All",
        "value_|_default_uri": "Firm Holiday"
    },
    {
        "mapper": "Yes",
        "type": "Timeoff Type",
        "employee_type": "",
        "country_code": "US",
        "location": "All",
        "person_type": "Administrative",
        "assignment_category": "Part Time 50",
        "flsa": "Nonexempt",
        "job_code": "All",
        "value_|_default_uri": "Firm Holiday"
    },
    {
        "mapper": "Yes",
        "type": "Timeoff Type",
        "employee_type": "",
        "country_code": "US",
        "location": "All",
        "person_type": "Administrative",
        "assignment_category": "Full-Time Regular",
        "flsa": "Exempt",
        "job_code": "All",
        "value_|_default_uri": "Firm Holiday"
    },
    {
        "mapper": "Yes",
        "type": "Timeoff Type",
        "employee_type": "",
        "country_code": "US",
        "location": "All",
        "person_type": "Administrative",
        "assignment_category": "Part Time 80",
        "flsa": "Exempt",
        "job_code": "All",
        "value_|_default_uri": "Firm Holiday"
    },
    {
        "mapper": "Yes",
        "type": "Timeoff Type",
        "employee_type": "",
        "country_code": "US",
        "location": "All",
        "person_type": "Administrative",
        "assignment_category": "Student Intern",
        "flsa": "Exempt",
        "job_code": "All",
        "value_|_default_uri": "Firm Holiday"
    },
    {
        "mapper": "Yes",
        "type": "Timeoff Type",
        "employee_type": "",
        "country_code": "US",
        "location": "All",
        "person_type": "Administrative",
        "assignment_category": "Part Time 50",
        "flsa": "Exempt",
        "job_code": "All",
        "value_|_default_uri": "Firm Holiday"
    },
    {
        "mapper": "Yes",
        "type": "Timeoff Type",
        "employee_type": "",
        "country_code": "GB",
        "location": "All",
        "person_type": "Administrative",
        "assignment_category": "Full-Time Regular",
        "flsa": "Nonexempt",
        "job_code": "All",
        "value_|_default_uri": "Firm Holiday"
    },
    {
        "mapper": "Yes",
        "type": "Timeoff Type",
        "employee_type": "",
        "country_code": "GB",
        "location": "All",
        "person_type": "Administrative",
        "assignment_category": "Part Time 80",
        "flsa": "Nonexempt",
        "job_code": "All",
        "value_|_default_uri": "Firm Holiday"
    },
    {
        "mapper": "Yes",
        "type": "Timeoff Type",
        "employee_type": "",
        "country_code": "GB",
        "location": "All",
        "person_type": "Administrative",
        "assignment_category": "Student Intern",
        "flsa": "Nonexempt",
        "job_code": "All",
        "value_|_default_uri": "Firm Holiday"
    },
    {
        "mapper": "Yes",
        "type": "Timeoff Type",
        "employee_type": "",
        "country_code": "GB",
        "location": "All",
        "person_type": "Administrative",
        "assignment_category": "Part Time 50",
        "flsa": "Nonexempt",
        "job_code": "All",
        "value_|_default_uri": "Firm Holiday"
    },
    {
        "mapper": "Yes",
        "type": "Timeoff Type",
        "employee_type": "",
        "country_code": "GB",
        "location": "All",
        "person_type": "Administrative",
        "assignment_category": "Full-Time Regular",
        "flsa": "Exempt",
        "job_code": "All",
        "value_|_default_uri": "Firm Holiday"
    },
    {
        "mapper": "Yes",
        "type": "Timeoff Type",
        "employee_type": "",
        "country_code": "GB",
        "location": "All",
        "person_type": "Administrative",
        "assignment_category": "Part Time 80",
        "flsa": "Exempt",
        "job_code": "All",
        "value_|_default_uri": "Firm Holiday"
    },
    {
        "mapper": "Yes",
        "type": "Timeoff Type",
        "employee_type": "",
        "country_code": "GB",
        "location": "All",
        "person_type": "Administrative",
        "assignment_category": "Student Intern",
        "flsa": "Exempt",
        "job_code": "All",
        "value_|_default_uri": "Firm Holiday"
    },
    {
        "mapper": "Yes",
        "type": "Timeoff Type",
        "employee_type": "",
        "country_code": "GB",
        "location": "All",
        "person_type": "Administrative",
        "assignment_category": "Part Time 50",
        "flsa": "Exempt",
        "job_code": "All",
        "value_|_default_uri": "Firm Holiday"
    },
    {
        "mapper": "Yes",
        "type": "Timeoff Type",
        "employee_type": "",
        "country_code": "US",
        "location": "All",
        "person_type": "Administrative",
        "assignment_category": "Full-Time Regular",
        "flsa": "Nonexempt",
        "job_code": "All",
        "value_|_default_uri": "Inclement Weather"
    },
    {
        "mapper": "Yes",
        "type": "Timeoff Type",
        "employee_type": "",
        "country_code": "US",
        "location": "All",
        "person_type": "Administrative",
        "assignment_category": "Part Time 80",
        "flsa": "Nonexempt",
        "job_code": "All",
        "value_|_default_uri": "Inclement Weather"
    },
    {
        "mapper": "Yes",
        "type": "Timeoff Type",
        "employee_type": "",
        "country_code": "US",
        "location": "All",
        "person_type": "Administrative",
        "assignment_category": "Student Intern",
        "flsa": "Nonexempt",
        "job_code": "All",
        "value_|_default_uri": "Inclement Weather"
    },
    {
        "mapper": "Yes",
        "type": "Timeoff Type",
        "employee_type": "",
        "country_code": "US",
        "location": "All",
        "person_type": "Administrative",
        "assignment_category": "Part Time 50",
        "flsa": "Nonexempt",
        "job_code": "All",
        "value_|_default_uri": "Inclement Weather"
    },
    {
        "mapper": "Yes",
        "type": "Timeoff Type",
        "employee_type": "",
        "country_code": "US",
        "location": "All",
        "person_type": "Administrative",
        "assignment_category": "Full-Time Regular",
        "flsa": "Nonexempt",
        "job_code": "All",
        "value_|_default_uri": "Jury Duty"
    },
    {
        "mapper": "Yes",
        "type": "Timeoff Type",
        "employee_type": "",
        "country_code": "US",
        "location": "All",
        "person_type": "Administrative",
        "assignment_category": "Part Time 80",
        "flsa": "Nonexempt",
        "job_code": "All",
        "value_|_default_uri": "Jury Duty"
    },
    {
        "mapper": "Yes",
        "type": "Timeoff Type",
        "employee_type": "",
        "country_code": "US",
        "location": "All",
        "person_type": "Administrative",
        "assignment_category": "Student Intern",
        "flsa": "Nonexempt",
        "job_code": "All",
        "value_|_default_uri": "Jury Duty"
    },
    {
        "mapper": "Yes",
        "type": "Timeoff Type",
        "employee_type": "",
        "country_code": "US",
        "location": "All",
        "person_type": "Administrative",
        "assignment_category": "Part Time 50",
        "flsa": "Nonexempt",
        "job_code": "All",
        "value_|_default_uri": "Jury Duty"
    },
    {
        "mapper": "Yes",
        "type": "Timeoff Type",
        "employee_type": "",
        "country_code": "US",
        "location": "All",
        "person_type": "Administrative",
        "assignment_category": "Full-Time Regular",
        "flsa": "Exempt",
        "job_code": "All",
        "value_|_default_uri": "Jury Duty"
    },
    {
        "mapper": "Yes",
        "type": "Timeoff Type",
        "employee_type": "",
        "country_code": "US",
        "location": "All",
        "person_type": "Administrative",
        "assignment_category": "Part Time 80",
        "flsa": "Exempt",
        "job_code": "All",
        "value_|_default_uri": "Jury Duty"
    },
    {
        "mapper": "Yes",
        "type": "Timeoff Type",
        "employee_type": "",
        "country_code": "US",
        "location": "All",
        "person_type": "Administrative",
        "assignment_category": "Student Intern",
        "flsa": "Exempt",
        "job_code": "All",
        "value_|_default_uri": "Jury Duty"
    },
    {
        "mapper": "Yes",
        "type": "Timeoff Type",
        "employee_type": "",
        "country_code": "US",
        "location": "All",
        "person_type": "Administrative",
        "assignment_category": "Part Time 50",
        "flsa": "Exempt",
        "job_code": "All",
        "value_|_default_uri": "Jury Duty"
    },
    {
        "mapper": "Yes",
        "type": "Timeoff Type",
        "employee_type": "",
        "country_code": "US",
        "location": "Austin",
        "person_type": "Administrative",
        "assignment_category": "Full-Time Regular",
        "flsa": "Exempt",
        "job_code": "All",
        "value_|_default_uri": "Optional Holiday"
    },
    {
        "mapper": "Yes",
        "type": "Timeoff Type",
        "employee_type": "",
        "country_code": "US",
        "location": "Austin",
        "person_type": "Administrative",
        "assignment_category": "Full-Time Regular",
        "flsa": "Nonexempt",
        "job_code": "All",
        "value_|_default_uri": "Optional Holiday"
    },
    {
        "mapper": "Yes",
        "type": "Timeoff Type",
        "employee_type": "",
        "country_code": "US",
        "location": "Dallas",
        "person_type": "Administrative",
        "assignment_category": "Full-Time Regular",
        "flsa": "Exempt",
        "job_code": "All",
        "value_|_default_uri": "Optional Holiday"
    },
    {
        "mapper": "Yes",
        "type": "Timeoff Type",
        "employee_type": "",
        "country_code": "US",
        "location": "Dallas",
        "person_type": "Administrative",
        "assignment_category": "Full-Time Regular",
        "flsa": "Nonexempt",
        "job_code": "All",
        "value_|_default_uri": "Optional Holiday"
    },
    {
        "mapper": "Yes",
        "type": "Timeoff Type",
        "employee_type": "",
        "country_code": "US",
        "location": "Houston",
        "person_type": "Administrative",
        "assignment_category": "Full-Time Regular",
        "flsa": "Exempt",
        "job_code": "All",
        "value_|_default_uri": "Optional Holiday"
    },
    {
        "mapper": "Yes",
        "type": "Timeoff Type",
        "employee_type": "",
        "country_code": "US",
        "location": "Houston",
        "person_type": "Administrative",
        "assignment_category": "Full-Time Regular",
        "flsa": "Nonexempt",
        "job_code": "All",
        "value_|_default_uri": "Optional Holiday"
    },
    {
        "mapper": "Yes",
        "type": "Timeoff Type",
        "employee_type": "",
        "country_code": "US",
        "location": "Austin",
        "person_type": "Administrative",
        "assignment_category": "Part Time 80",
        "flsa": "Exempt",
        "job_code": "All",
        "value_|_default_uri": "Optional Holiday 80%"
    },
    {
        "mapper": "Yes",
        "type": "Timeoff Type",
        "employee_type": "",
        "country_code": "US",
        "location": "Austin",
        "person_type": "Administrative",
        "assignment_category": "Part Time 80",
        "flsa": "Nonexempt",
        "job_code": "All",
        "value_|_default_uri": "Optional Holiday 80%"
    },
    {
        "mapper": "Yes",
        "type": "Timeoff Type",
        "employee_type": "",
        "country_code": "US",
        "location": "Dallas",
        "person_type": "Administrative",
        "assignment_category": "Part Time 80",
        "flsa": "Exempt",
        "job_code": "All",
        "value_|_default_uri": "Optional Holiday 80%"
    },
    {
        "mapper": "Yes",
        "type": "Timeoff Type",
        "employee_type": "",
        "country_code": "US",
        "location": "Dallas",
        "person_type": "Administrative",
        "assignment_category": "Part Time 80",
        "flsa": "Nonexempt",
        "job_code": "All",
        "value_|_default_uri": "Optional Holiday 80%"
    },
    {
        "mapper": "Yes",
        "type": "Timeoff Type",
        "employee_type": "",
        "country_code": "US",
        "location": "Houston",
        "person_type": "Administrative",
        "assignment_category": "Part Time 80",
        "flsa": "Exempt",
        "job_code": "All",
        "value_|_default_uri": "Optional Holiday 80%"
    },
    {
        "mapper": "Yes",
        "type": "Timeoff Type",
        "employee_type": "",
        "country_code": "US",
        "location": "Houston",
        "person_type": "Administrative",
        "assignment_category": "Part Time 80",
        "flsa": "Nonexempt",
        "job_code": "All",
        "value_|_default_uri": "Optional Holiday 80%"
    },
    {
        "mapper": "Yes",
        "type": "Timeoff Type",
        "employee_type": "",
        "country_code": "US",
        "location": "Austin",
        "person_type": "Administrative",
        "assignment_category": "Part Time 80",
        "flsa": "Nonexempt",
        "job_code": "All",
        "value_|_default_uri": "PTO 80%"
    },
    {
        "mapper": "Yes",
        "type": "Timeoff Type",
        "employee_type": "",
        "country_code": "US",
        "location": "Dallas",
        "person_type": "Administrative",
        "assignment_category": "Part Time 80",
        "flsa": "Nonexempt",
        "job_code": "All",
        "value_|_default_uri": "PTO 80%"
    },
    {
        "mapper": "Yes",
        "type": "Timeoff Type",
        "employee_type": "",
        "country_code": "US",
        "location": "New York",
        "person_type": "Administrative",
        "assignment_category": "Part Time 80",
        "flsa": "Nonexempt",
        "job_code": "All",
        "value_|_default_uri": "PTO 80%"
    },
    {
        "mapper": "Yes",
        "type": "Timeoff Type",
        "employee_type": "",
        "country_code": "US",
        "location": "Richmond",
        "person_type": "Administrative",
        "assignment_category": "Part Time 80",
        "flsa": "Nonexempt",
        "job_code": "All",
        "value_|_default_uri": "PTO 80%"
    },
    {
        "mapper": "Yes",
        "type": "Timeoff Type",
        "employee_type": "",
        "country_code": "US",
        "location": "Washington",
        "person_type": "Administrative",
        "assignment_category": "Part Time 80",
        "flsa": "Nonexempt",
        "job_code": "All",
        "value_|_default_uri": "PTO 80%"
    },
    {
        "mapper": "Yes",
        "type": "Timeoff Type",
        "employee_type": "",
        "country_code": "US",
        "location": "Houston",
        "person_type": "Administrative",
        "assignment_category": "Part Time 80",
        "flsa": "Nonexempt",
        "job_code": "All",
        "value_|_default_uri": "PTO 80%"
    },
    {
        "mapper": "Yes",
        "type": "Timeoff Type",
        "employee_type": "",
        "country_code": "US",
        "location": "San Francisco",
        "person_type": "Administrative",
        "assignment_category": "Part Time 50",
        "flsa": "Nonexempt",
        "job_code": "All",
        "value_|_default_uri": "SFHPTO"
    },
    {
        "mapper": "Yes",
        "type": "Timeoff Type",
        "employee_type": "",
        "country_code": "US",
        "location": "San Francisco",
        "person_type": "Attorney",
        "assignment_category": "Full-Time Regular",
        "flsa": "Exempt",
        "job_code": "Excluding PART and OFCO",
        "value_|_default_uri": "CA Attorneys Exempt Vacation"
    },
    {
        "mapper": "Yes",
        "type": "Timeoff Type",
        "employee_type": "Yes",
        "country_code": "US",
        "location": "All",
        "person_type": "Administrative",
        "assignment_category": "Part Time 80",
        "flsa": "Nonexempt",
        "job_code": "All",
        "value_|_default_uri": "Parental Leave- Primary Caregiver"
    },
    {
        "mapper": "Yes",
        "type": "Timeoff Type",
        "employee_type": "Yes",
        "country_code": "US",
        "location": "All",
        "person_type": "Administrative",
        "assignment_category": "Full-Time Regular",
        "flsa": "Nonexempt",
        "job_code": "All",
        "value_|_default_uri": "Parental Leave- Primary Caregiver"
    },
    {
        "mapper": "Yes",
        "type": "Timeoff Type",
        "employee_type": "Yes",
        "country_code": "US",
        "location": "All",
        "person_type": "Administrative",
        "assignment_category": "Part Time 80",
        "flsa": "Exempt",
        "job_code": "All",
        "value_|_default_uri": "Parental Leave- Primary Caregiver"
    },
    {
        "mapper": "Yes",
        "type": "Timeoff Type",
        "employee_type": "Yes",
        "country_code": "US",
        "location": "All",
        "person_type": "Administrative",
        "assignment_category": "Full-Time Regular",
        "flsa": "Exempt",
        "job_code": "All",
        "value_|_default_uri": "Parental Leave- Primary Caregiver"
    },
    {
        "mapper": "Yes",
        "type": "Timeoff Type",
        "employee_type": "Yes",
        "country_code": "US",
        "location": "All",
        "person_type": "Administrative",
        "assignment_category": "Part Time 80",
        "flsa": "Nonexempt",
        "job_code": "All",
        "value_|_default_uri": "Parental Leave- Secondary Caregiver"
    },
    {
        "mapper": "Yes",
        "type": "Timeoff Type",
        "employee_type": "Yes",
        "country_code": "US",
        "location": "All",
        "person_type": "Administrative",
        "assignment_category": "Full-Time Regular",
        "flsa": "Nonexempt",
        "job_code": "All",
        "value_|_default_uri": "Parental Leave- Secondary Caregiver"
    },
    {
        "mapper": "Yes",
        "type": "Timeoff Type",
        "employee_type": "Yes",
        "country_code": "US",
        "location": "All",
        "person_type": "Administrative",
        "assignment_category": "Part Time 80",
        "flsa": "Exempt",
        "job_code": "All",
        "value_|_default_uri": "Parental Leave- Secondary Caregiver"
    },
    {
        "mapper": "Yes",
        "type": "Timeoff Type",
        "employee_type": "Yes",
        "country_code": "US",
        "location": "All",
        "person_type": "Administrative",
        "assignment_category": "Full-Time Regular",
        "flsa": "Exempt",
        "job_code": "All",
        "value_|_default_uri": "Parental Leave- Secondary Caregiver"
    },
    {
        "mapper": "Yes",
        "type": "Timeoff Type",
        "employee_type": "Yes",
        "country_code": "US",
        "location": "All",
        "person_type": "Administrative",
        "assignment_category": "Part Time 80",
        "flsa": "Nonexempt",
        "job_code": "All",
        "value_|_default_uri": "Parental Leave- Equal Caregiver"
    },
    {
        "mapper": "Yes",
        "type": "Timeoff Type",
        "employee_type": "Yes",
        "country_code": "US",
        "location": "All",
        "person_type": "Administrative",
        "assignment_category": "Full-Time Regular",
        "flsa": "Nonexempt",
        "job_code": "All",
        "value_|_default_uri": "Parental Leave- Equal Caregiver"
    },
    {
        "mapper": "Yes",
        "type": "Timeoff Type",
        "employee_type": "Yes",
        "country_code": "US",
        "location": "All",
        "person_type": "Administrative",
        "assignment_category": "Part Time 80",
        "flsa": "Exempt",
        "job_code": "All",
        "value_|_default_uri": "Parental Leave- Equal Caregiver"
    },
    {
        "mapper": "Yes",
        "type": "Timeoff Type",
        "employee_type": "Yes",
        "country_code": "US",
        "location": "All",
        "person_type": "Administrative",
        "assignment_category": "Full-Time Regular",
        "flsa": "Exempt",
        "job_code": "All",
        "value_|_default_uri": "Parental Leave- Equal Caregiver"
    },
    {
        "mapper": "Yes",
        "type": "Timeoff Type",
        "employee_type": "",
        "country_code": "US",
        "location": "Austin",
        "person_type": "Administrative",
        "assignment_category": "Full-Time Regular",
        "flsa": "Nonexempt",
        "job_code": "PARA",
        "value_|_default_uri": "PL Vacation"
    },
    {
        "mapper": "Yes",
        "type": "Timeoff Type",
        "employee_type": "",
        "country_code": "US",
        "location": "Dallas",
        "person_type": "Administrative",
        "assignment_category": "Full-Time Regular",
        "flsa": "Nonexempt",
        "job_code": "PARA",
        "value_|_default_uri": "PL Vacation"
    },
    {
        "mapper": "Yes",
        "type": "Timeoff Type",
        "employee_type": "",
        "country_code": "US",
        "location": "New York",
        "person_type": "Administrative",
        "assignment_category": "Full-Time Regular",
        "flsa": "Nonexempt",
        "job_code": "PARA",
        "value_|_default_uri": "PL Vacation"
    },
    {
        "mapper": "Yes",
        "type": "Timeoff Type",
        "employee_type": "",
        "country_code": "US",
        "location": "Richmond",
        "person_type": "Administrative",
        "assignment_category": "Full-Time Regular",
        "flsa": "Nonexempt",
        "job_code": "PARA",
        "value_|_default_uri": "PL Vacation"
    },
    {
        "mapper": "Yes",
        "type": "Timeoff Type",
        "employee_type": "",
        "country_code": "US",
        "location": "Washington",
        "person_type": "Administrative",
        "assignment_category": "Full-Time Regular",
        "flsa": "Nonexempt",
        "job_code": "PARA",
        "value_|_default_uri": "PL Vacation"
    },
    {
        "mapper": "Yes",
        "type": "Timeoff Type",
        "employee_type": "",
        "country_code": "US",
        "location": "Houston",
        "person_type": "Administrative",
        "assignment_category": "Full-Time Regular",
        "flsa": "Nonexempt",
        "job_code": "PARA",
        "value_|_default_uri": "PL Vacation"
    },
    {
        "mapper": "Yes",
        "type": "Timeoff Type",
        "employee_type": "",
        "country_code": "US",
        "location": "Austin",
        "person_type": "Administrative",
        "assignment_category": "Part Time 80",
        "flsa": "Nonexempt",
        "job_code": "PARA",
        "value_|_default_uri": "PL Vacation 80%"
    },
    {
        "mapper": "Yes",
        "type": "Timeoff Type",
        "employee_type": "",
        "country_code": "US",
        "location": "Dallas",
        "person_type": "Administrative",
        "assignment_category": "Part Time 80",
        "flsa": "Nonexempt",
        "job_code": "PARA",
        "value_|_default_uri": "PL Vacation 80%"
    },
    {
        "mapper": "Yes",
        "type": "Timeoff Type",
        "employee_type": "",
        "country_code": "US",
        "location": "New York",
        "person_type": "Administrative",
        "assignment_category": "Part Time 80",
        "flsa": "Nonexempt",
        "job_code": "PARA",
        "value_|_default_uri": "PL Vacation 80%"
    },
    {
        "mapper": "Yes",
        "type": "Timeoff Type",
        "employee_type": "",
        "country_code": "US",
        "location": "Richmond",
        "person_type": "Administrative",
        "assignment_category": "Part Time 80",
        "flsa": "Nonexempt",
        "job_code": "PARA",
        "value_|_default_uri": "PL Vacation 80%"
    },
    {
        "mapper": "Yes",
        "type": "Timeoff Type",
        "employee_type": "",
        "country_code": "US",
        "location": "Washington",
        "person_type": "Administrative",
        "assignment_category": "Part Time 80",
        "flsa": "Nonexempt",
        "job_code": "PARA",
        "value_|_default_uri": "PL Vacation 80%"
    },
    {
        "mapper": "Yes",
        "type": "Timeoff Type",
        "employee_type": "",
        "country_code": "US",
        "location": "Houston",
        "person_type": "Administrative",
        "assignment_category": "Part Time 80",
        "flsa": "Nonexempt",
        "job_code": "PARA",
        "value_|_default_uri": "PL Vacation 80%"
    },
    {
        "mapper": "Yes",
        "type": "Timeoff Type",
        "employee_type": "Yes",
        "country_code": "US",
        "location": "All",
        "person_type": "Administrative",
        "assignment_category": "Full-Time Regular",
        "flsa": "Nonexempt",
        "job_code": "PARA",
        "value_|_default_uri": "PL STD 100%"
    },
    {
        "mapper": "Yes",
        "type": "Timeoff Type",
        "employee_type": "Yes",
        "country_code": "US",
        "location": "All",
        "person_type": "Administrative",
        "assignment_category": "Full-Time Regular",
        "flsa": "Nonexempt",
        "job_code": "PARA",
        "value_|_default_uri": "PL STD 50%"
    },
    {
        "mapper": "Yes",
        "type": "Timeoff Type",
        "employee_type": "Yes",
        "country_code": "US",
        "location": "All",
        "person_type": "Administrative",
        "assignment_category": "Part Time 80",
        "flsa": "Nonexempt",
        "job_code": "PARA",
        "value_|_default_uri": "PL 80% STD 100%"
    },
    {
        "mapper": "Yes",
        "type": "Timeoff Type",
        "employee_type": "Yes",
        "country_code": "US",
        "location": "All",
        "person_type": "Administrative",
        "assignment_category": "Part Time 80",
        "flsa": "Nonexempt",
        "job_code": "PARA",
        "value_|_default_uri": "PL 80% STD 50%"
    },
    {
        "mapper": "Yes",
        "type": "Timeoff Type",
        "employee_type": "",
        "country_code": "US",
        "location": "San Francisco",
        "person_type": "Administrative",
        "assignment_category": "Full-Time Regular",
        "flsa": "Nonexempt",
        "job_code": "PARA",
        "value_|_default_uri": "CA PL Vacation"
    },
    {
        "mapper": "Yes",
        "type": "Timeoff Type",
        "employee_type": "",
        "country_code": "US",
        "location": "San Francisco",
        "person_type": "Administrative",
        "assignment_category": "Part Time 80",
        "flsa": "Nonexempt",
        "job_code": "PARA",
        "value_|_default_uri": "CA PL Vacation 80%"
    },
    {
        "mapper": "Yes",
        "type": "Timeoff Type",
        "employee_type": "",
        "country_code": "US",
        "location": "All",
        "person_type": "Administrative",
        "assignment_category": "Full-Time Regular",
        "flsa": "Nonexempt",
        "job_code": "PARA",
        "value_|_default_uri": "Unpaid Time off_PARA"
    },
    {
        "mapper": "Yes",
        "type": "Timeoff Type",
        "employee_type": "",
        "country_code": "US",
        "location": "All",
        "person_type": "Administrative",
        "assignment_category": "Part Time 80",
        "flsa": "Nonexempt",
        "job_code": "PARA",
        "value_|_default_uri": "Unpaid Time off_PARA"
    },
    {
        "mapper": "Yes",
        "type": "Timeoff Type",
        "employee_type": "",
        "country_code": "US",
        "location": "All",
        "person_type": "Administrative",
        "assignment_category": "Full-Time Regular",
        "flsa": "Nonexempt",
        "job_code": "All excluding PARA",
        "value_|_default_uri": "Unpaid Time off_Non_Exempt"
    },
    {
        "mapper": "Yes",
        "type": "Timeoff Type",
        "employee_type": "",
        "country_code": "US",
        "location": "All",
        "person_type": "Administrative",
        "assignment_category": "Part Time 80",
        "flsa": "Nonexempt",
        "job_code": "All excluding PARA",
        "value_|_default_uri": "Unpaid Time off_Non_Exempt"
    },
    {
        "mapper": "Yes",
        "type": "Timeoff Type",
        "employee_type": "",
        "country_code": "US",
        "location": "All",
        "person_type": "Administrative",
        "assignment_category": "Full-Time Regular",
        "flsa": "Exempt",
        "job_code": "All",
        "value_|_default_uri": "Unpaid Time off_Exempt"
    },
    {
        "mapper": "Yes",
        "type": "Timeoff Type",
        "employee_type": "",
        "country_code": "US",
        "location": "All",
        "person_type": "Administrative",
        "assignment_category": "Part Time 80",
        "flsa": "Exempt",
        "job_code": "All",
        "value_|_default_uri": "Unpaid Time off_Exempt"
    },
    {
        "mapper": "Yes",
        "type": "Timeoff Type",
        "employee_type": "Yes",
        "country_code": "US",
        "location": "All",
        "person_type": "All",
        "assignment_category": "All",
        "flsa": "All",
        "job_code": "All",
        "value_|_default_uri": "PTO Pool"
    },
    {
        "mapper": "Yes",
        "type": "Timeoff Type",
        "employee_type": "Yes",
        "country_code": "GB",
        "location": "All",
        "person_type": "All",
        "assignment_category": "All",
        "flsa": "All",
        "job_code": "All",
        "value_|_default_uri": "Bereavement Leave"
    },
    {
        "mapper": "Yes",
        "type": "Timeoff Type",
        "employee_type": "Yes",
        "country_code": "GB",
        "location": "All",
        "person_type": "Attorney",
        "assignment_category": "All",
        "flsa": "All",
        "job_code": "All",
        "value_|_default_uri": "Exam Leave"
    },
    {
        "mapper": "Yes",
        "type": "Timeoff Type",
        "employee_type": "Yes",
        "country_code": "GB",
        "location": "All",
        "person_type": "Attorney",
        "assignment_category": "All",
        "flsa": "All",
        "job_code": "All",
        "value_|_default_uri": "Family Leave"
    },
    {
        "mapper": "Yes",
        "type": "Timeoff Type",
        "employee_type": "Yes",
        "country_code": "GB",
        "location": "All",
        "person_type": "All",
        "assignment_category": "All",
        "flsa": "All",
        "job_code": "All",
        "value_|_default_uri": "Funeral"
    },
    {
        "mapper": "Yes",
        "type": "Timeoff Type",
        "employee_type": "Yes",
        "country_code": "GB",
        "location": "All",
        "person_type": "Administrative",
        "assignment_category": "Full-Time Regular",
        "flsa": "Nonexempt",
        "job_code": "All",
        "value_|_default_uri": "Grace Period"
    },
    {
        "mapper": "Yes",
        "type": "Timeoff Type",
        "employee_type": "Yes",
        "country_code": "GB",
        "location": "All",
        "person_type": "Administrative",
        "assignment_category": "Part Time 80",
        "flsa": "Nonexempt",
        "job_code": "All",
        "value_|_default_uri": "Grace Period"
    },
    {
        "mapper": "Yes",
        "type": "Timeoff Type",
        "employee_type": "Yes",
        "country_code": "GB",
        "location": "All",
        "person_type": "All",
        "assignment_category": "All",
        "flsa": "All",
        "job_code": "All",
        "value_|_default_uri": "Jury Service"
    },
    {
        "mapper": "Yes",
        "type": "Timeoff Type",
        "employee_type": "Yes",
        "country_code": "GB",
        "location": "All",
        "person_type": "Attorney",
        "assignment_category": "All",
        "flsa": "All",
        "job_code": "All",
        "value_|_default_uri": "KIT Days"
    },
    {
        "mapper": "Yes",
        "type": "Timeoff Type",
        "employee_type": "Yes",
        "country_code": "GB",
        "location": "All",
        "person_type": "Attorney",
        "assignment_category": "All",
        "flsa": "All",
        "job_code": "All",
        "value_|_default_uri": "Lieu Day"
    },
    {
        "mapper": "Yes",
        "type": "Timeoff Type",
        "employee_type": "Yes",
        "country_code": "GB",
        "location": "All",
        "person_type": "All",
        "assignment_category": "All",
        "flsa": "All",
        "job_code": "All",
        "value_|_default_uri": "Maternity Leave"
    },
    {
        "mapper": "Yes",
        "type": "Timeoff Type",
        "employee_type": "Yes",
        "country_code": "GB",
        "location": "All",
        "person_type": "All",
        "assignment_category": "All",
        "flsa": "All",
        "job_code": "All",
        "value_|_default_uri": "Parental Leave"
    },
    {
        "mapper": "Yes",
        "type": "Timeoff Type",
        "employee_type": "Yes",
        "country_code": "GB",
        "location": "All",
        "person_type": "All",
        "assignment_category": "All",
        "flsa": "All",
        "job_code": "All",
        "value_|_default_uri": "Paternity Leave"
    },
    {
        "mapper": "Yes",
        "type": "Timeoff Type",
        "employee_type": "",
        "country_code": "GB",
        "location": "All",
        "person_type": "All",
        "assignment_category": "All",
        "flsa": "All",
        "job_code": "All",
        "value_|_default_uri": "Personal Leave"
    },
    {
        "mapper": "Yes",
        "type": "Timeoff Type",
        "employee_type": "Yes",
        "country_code": "GB",
        "location": "All",
        "person_type": "Attorney",
        "assignment_category": "All",
        "flsa": "All",
        "job_code": "All",
        "value_|_default_uri": "Relocation Day"
    },
    {
        "mapper": "Yes",
        "type": "Timeoff Type",
        "employee_type": "",
        "country_code": "GB",
        "location": "All",
        "person_type": "All",
        "assignment_category": "All",
        "flsa": "All",
        "job_code": "All",
        "value_|_default_uri": "Sickness"
    },
    {
        "mapper": "Yes",
        "type": "Timeoff Type",
        "employee_type": "Yes",
        "country_code": "GB",
        "location": "All",
        "person_type": "All",
        "assignment_category": "All",
        "flsa": "All",
        "job_code": "All",
        "value_|_default_uri": "SPLIT Days"
    },
    {
        "mapper": "Yes",
        "type": "Timeoff Type",
        "employee_type": "Yes",
        "country_code": "GB",
        "location": "All",
        "person_type": "All",
        "assignment_category": "All",
        "flsa": "All",
        "job_code": "All",
        "value_|_default_uri": "Unpaid Leave"
    },
    {
        "mapper": "Yes",
        "type": "Authentication",
        "employee_type": "",
        "country_code": "",
        "location": "",
        "person_type": "",
        "assignment_category": "",
        "flsa": "",
        "job_code": "",
        "value_|_default_uri": "SSO | urn:replicon:user-authentication-type:sso"
    },
    {
        "mapper": "Yes",
        "type": "TimeOff Template",
        "employee_type": "",
        "country_code": "",
        "location": "",
        "person_type": "",
        "assignment_category": "",
        "flsa": "",
        "job_code": "",
        "value_|_default_uri": "V&E - Time Off Template"
    },
    {
        "mapper": "Yes",
        "type": "Timesheet Template",
        "employee_type": "Exempt Full Time",
        "country_code": "",
        "location": "",
        "person_type": "",
        "assignment_category": "",
        "flsa": "",
        "job_code": "",
        "value_|_default_uri": "Do Not Assign"
    },
    {
        "mapper": "Yes",
        "type": "Timesheet Template",
        "employee_type": "Exempt 80",
        "country_code": "",
        "location": "",
        "person_type": "",
        "assignment_category": "",
        "flsa": "",
        "job_code": "",
        "value_|_default_uri": "Do Not Assign"
    },
    {
        "mapper": "Yes",
        "type": "Timesheet Template",
        "employee_type": "Attorney - California",
        "country_code": "",
        "location": "",
        "person_type": "",
        "assignment_category": "",
        "flsa": "",
        "job_code": "",
        "value_|_default_uri": "Do Not Assign"
    },
    {
        "mapper": "Yes",
        "type": "Timesheet Template",
        "employee_type": "Attorney - UK",
        "country_code": "",
        "location": "",
        "person_type": "",
        "assignment_category": "",
        "flsa": "",
        "job_code": "",
        "value_|_default_uri": "Do Not Assign"
    },
    {
        "mapper": "Yes",
        "type": "Timesheet Template",
        "employee_type": "Others",
        "country_code": "",
        "location": "",
        "person_type": "",
        "assignment_category": "",
        "flsa": "",
        "job_code": "",
        "value_|_default_uri": "Do Not Assign"
    },
    {
        "mapper": "Yes",
        "type": "Timeoff Type",
        "employee_type": "",
        "country_code": "GB",
        "location": "All",
        "person_type": "All",
        "assignment_category": "All",
        "flsa": "All",
        "job_code": "All",
        "value_|_default_uri": "Holiday"
    },
    {
        "mapper": "Yes",
        "type": "Timesheet Template",
        "employee_type": "Non-Exempt Hourly",
        "country_code": "",
        "location": "",
        "person_type": "",
        "assignment_category": "",
        "flsa": "",
        "job_code": "",
        "value_|_default_uri": "*V&E - Non-Exempt Hourly"
    },
    {
        "mapper": "Yes",
        "type": "Payrule",
        "employee_type": "Non-Exempt Hourly",
        "country_code": "",
        "location": "",
        "person_type": "",
        "assignment_category": "",
        "flsa": "",
        "job_code": "",
        "value_|_default_uri": "*V&E - Non-Exempt Hourly"
    },
    {
        "mapper": "Yes",
        "type": "Timeoff Type",
        "employee_type": "",
        "country_code": "US",
        "location": "Los Angeles",
        "person_type": "Administrative",
        "assignment_category": "Full-Time Regular",
        "flsa": "Exempt",
        "job_code": "All",
        "value_|_default_uri": "California Exempt Vac"
    },
    {
        "mapper": "Yes",
        "type": "Timeoff Type",
        "employee_type": "",
        "country_code": "US",
        "location": "Los Angeles",
        "person_type": "Administrative",
        "assignment_category": "Part Time 80",
        "flsa": "Exempt",
        "job_code": "All",
        "value_|_default_uri": "California Exempt 80%"
    },
    {
        "mapper": "Yes",
        "type": "Timeoff Type",
        "employee_type": "",
        "country_code": "US",
        "location": "Los Angeles",
        "person_type": "Administrative",
        "assignment_category": "Part Time 50",
        "flsa": "Nonexempt",
        "job_code": "All",
        "value_|_default_uri": "SFHPTO"
    },
    {
        "mapper": "Yes",
        "type": "Timeoff Type",
        "employee_type": "",
        "country_code": "US",
        "location": "Los Angeles",
        "person_type": "Attorney",
        "assignment_category": "Full-Time Regular",
        "flsa": "Exempt",
        "job_code": "Excluding PART and OFCO",
        "value_|_default_uri": "CA Attorneys Exempt Vacation"
    },
    {
        "mapper": "Yes",
        "type": "Timeoff Type",
        "employee_type": "",
        "country_code": "US",
        "location": "Los Angeles",
        "person_type": "Administrative",
        "assignment_category": "Full-Time Regular",
        "flsa": "Nonexempt",
        "job_code": "PARA",
        "value_|_default_uri": "CA PL Vacation"
    },
    {
        "mapper": "Yes",
        "type": "Timeoff Type",
        "employee_type": "",
        "country_code": "US",
        "location": "Los Angeles",
        "person_type": "Administrative",
        "assignment_category": "Part Time 80",
        "flsa": "Nonexempt",
        "job_code": "PARA",
        "value_|_default_uri": "CA PL Vacation 80%"
    },
    {
        "mapper": "Yes",
        "type": "TimeZone",
        "employee_type": "",
        "country_code": "US",
        "location": "Los Angeles",
        "person_type": "",
        "assignment_category": "",
        "flsa": "",
        "job_code": "",
        "value_|_default_uri": "(UTC-8:00) Pacific Standard Time | urn:replicon:time-zone:america-los-angeles"
    },
    {
        "mapper": "Yes",
        "type": "Holiday Calendar",
        "employee_type": "",
        "country_code": "US",
        "location": "Los Angeles",
        "person_type": "",
        "assignment_category": "",
        "flsa": "",
        "job_code": "",
        "value_|_default_uri": "Holidays for East/West Coast"
    },
    {
        "mapper": "Yes",
        "type": "Timesheet Template",
        "employee_type": "UK Full Time and Part Time_E",
        "country_code": "",
        "location": "",
        "person_type": "",
        "assignment_category": "",
        "flsa": "",
        "job_code": "",
        "value_|_default_uri": "Do Not Assign"
    },
    {
        "mapper": "Yes",
        "type": "Payrule",
        "employee_type": "UK Full Time and Part Time_E",
        "country_code": "",
        "location": "",
        "person_type": "",
        "assignment_category": "",
        "flsa": "",
        "job_code": "",
        "value_|_default_uri": "*V&E - Placeholder Pay-rule"
    },
    {
        "mapper": "Yes",
        "type": "Timeoff Type",
        "employee_type": "",
        "country_code": "US",
        "location": "Los Angeles",
        "person_type": "All",
        "assignment_category": "Full-Time Regular",
        "flsa": "All",
        "job_code": "All",
        "value_|_default_uri": "CA - Supplemental Paid Sick Leave"
    },
    {
        "mapper": "Yes",
        "type": "Timeoff Type",
        "employee_type": "",
        "country_code": "US",
        "location": "San Francisco",
        "person_type": "All",
        "assignment_category": "Full-Time Regular",
        "flsa": "All",
        "job_code": "All",
        "value_|_default_uri": "CA - Supplemental Paid Sick Leave"
    },
    {
        "mapper": "Yes",
        "type": "TimeOff Approval Path",
        "employee_type": "Vinson & Elkins|Vinson & Elkins LLP|Billing Coordinators",
        "country_code": "US",
        "location": "All",
        "person_type": "Administrative",
        "assignment_category": "",
        "flsa": "All",
        "job_code": "All excluding Paralegal",
        "value_|_default_uri": "Supervisor"
    },
    {
        "mapper": "Yes",
        "type": "TimeOff Approval Path",
        "employee_type": "All",
        "country_code": "US",
        "location": "Austin",
        "person_type": "Administrative",
        "assignment_category": "",
        "flsa": "Nonexempt",
        "job_code": "All excluding Paralegal",
        "value_|_default_uri": "US_Austin"
    },
    {
        "mapper": "Yes",
        "type": "TimeOff Approval Path",
        "employee_type": "All",
        "country_code": "US",
        "location": "San Francisco",
        "person_type": "Administrative",
        "assignment_category": "",
        "flsa": "Nonexempt",
        "job_code": "All excluding Paralegal",
        "value_|_default_uri": "US_San Francisco"
    },
    {
        "mapper": "Yes",
        "type": "TimeOff Approval Path",
        "employee_type": "All",
        "country_code": "US",
        "location": "Dallas",
        "person_type": "Administrative",
        "assignment_category": "",
        "flsa": "Nonexempt",
        "job_code": "All excluding Paralegal",
        "value_|_default_uri": "US_Dallas"
    },
    {
        "mapper": "Yes",
        "type": "TimeOff Approval Path",
        "employee_type": "All",
        "country_code": "US",
        "location": "New York",
        "person_type": "Administrative",
        "assignment_category": "",
        "flsa": "Nonexempt",
        "job_code": "All excluding Paralegal",
        "value_|_default_uri": "US_New York"
    },
    {
        "mapper": "Yes",
        "type": "TimeOff Approval Path",
        "employee_type": "All",
        "country_code": "US",
        "location": "Richmond",
        "person_type": "Administrative",
        "assignment_category": "",
        "flsa": "Nonexempt",
        "job_code": "All excluding Paralegal",
        "value_|_default_uri": "US_Richmond"
    },
    {
        "mapper": "Yes",
        "type": "TimeOff Approval Path",
        "employee_type": "All",
        "country_code": "US",
        "location": "Washington",
        "person_type": "Administrative",
        "assignment_category": "",
        "flsa": "Nonexempt",
        "job_code": "All excluding Paralegal",
        "value_|_default_uri": "US_Washington"
    },
    {
        "mapper": "Yes",
        "type": "TimeOff Approval Path",
        "employee_type": "All",
        "country_code": "US",
        "location": "Houston",
        "person_type": "Administrative",
        "assignment_category": "",
        "flsa": "Nonexempt",
        "job_code": "All excluding Paralegal",
        "value_|_default_uri": "US_Houston"
    },
    {
        "mapper": "Yes",
        "type": "TimeOff Approval Path",
        "employee_type": "All",
        "country_code": "US",
        "location": "Los Angeles",
        "person_type": "Administrative",
        "assignment_category": "",
        "flsa": "Nonexempt",
        "job_code": "All excluding Paralegal",
        "value_|_default_uri": "US_Los Angeles"
    },
    {
        "mapper": "Yes",
        "type": "TimeOff Approval Path",
        "employee_type": "All",
        "country_code": "US",
        "location": "San Francisco",
        "person_type": "Attorney",
        "assignment_category": "",
        "flsa": "Exempt",
        "job_code": "All excluding Paralegal",
        "value_|_default_uri": "US_San Francisco_Attorney"
    },
    {
        "mapper": "Yes",
        "type": "TimeOff Approval Path",
        "employee_type": "All",
        "country_code": "US",
        "location": "Los Angeles",
        "person_type": "Attorney",
        "assignment_category": "",
        "flsa": "Exempt",
        "job_code": "All excluding Paralegal",
        "value_|_default_uri": "US_Los Angeles_Attorney"
    },
    {
        "mapper": "Yes",
        "type": "TimeOff Approval Path",
        "employee_type": "All",
        "country_code": "US",
        "location": "All",
        "person_type": "Administrative",
        "assignment_category": "",
        "flsa": "Exempt",
        "job_code": "All excluding Paralegal",
        "value_|_default_uri": "Supervisor"
    },
    {
        "mapper": "Yes",
        "type": "TimeOff Approval Path",
        "employee_type": "All",
        "country_code": "US",
        "location": "All",
        "person_type": "Administrative",
        "assignment_category": "",
        "flsa": "All",
        "job_code": "Paralegal",
        "value_|_default_uri": "Supervisor"
    },
    {
        "mapper": "Yes",
        "type": "TimeOff Approval Path",
        "employee_type": "All",
        "country_code": "GB",
        "location": "London",
        "person_type": "Attorney",
        "assignment_category": "",
        "flsa": "Exempt",
        "job_code": "All",
        "value_|_default_uri": "GB_London_Attorney"
    },
    {
        "mapper": "Yes",
        "type": "TimeOff Approval Path",
        "employee_type": "All",
        "country_code": "GB",
        "location": "London",
        "person_type": "Administrative",
        "assignment_category": "",
        "flsa": "Nonexempt",
        "job_code": "All",
        "value_|_default_uri": "GB_London"
    },
    {
        "mapper": "Yes",
        "type": "Timesheet Approval Path",
        "employee_type": "Vinson & Elkins|Vinson & Elkins LLP|Global Document Specialists",
        "country_code": "US",
        "location": "All excluding Houston",
        "person_type": "",
        "assignment_category": "",
        "flsa": "Nonexempt",
        "job_code": "All excluding Paralegal",
        "value_|_default_uri": "Exception"
    },
    {
        "mapper": "Yes",
        "type": "Timesheet Approval Path",
        "employee_type": "All",
        "country_code": "US",
        "location": "Austin",
        "person_type": "",
        "assignment_category": "",
        "flsa": "Nonexempt",
        "job_code": "All excluding Paralegal",
        "value_|_default_uri": "US_Austin"
    },
    {
        "mapper": "Yes",
        "type": "Timesheet Approval Path",
        "employee_type": "All",
        "country_code": "US",
        "location": "Dallas",
        "person_type": "",
        "assignment_category": "",
        "flsa": "Nonexempt",
        "job_code": "All excluding Paralegal",
        "value_|_default_uri": "US_Dallas"
    },
    {
        "mapper": "Yes",
        "type": "Timesheet Approval Path",
        "employee_type": "All",
        "country_code": "US",
        "location": "San Francisco",
        "person_type": "",
        "assignment_category": "",
        "flsa": "Nonexempt",
        "job_code": "All excluding Paralegal",
        "value_|_default_uri": "US_San Francisco"
    },
    {
        "mapper": "Yes",
        "type": "Timesheet Approval Path",
        "employee_type": "All",
        "country_code": "US",
        "location": "Richmond",
        "person_type": "",
        "assignment_category": "",
        "flsa": "Nonexempt",
        "job_code": "All excluding Paralegal",
        "value_|_default_uri": "US_Richmond"
    },
    {
        "mapper": "Yes",
        "type": "Timesheet Approval Path",
        "employee_type": "All",
        "country_code": "US",
        "location": "New York",
        "person_type": "",
        "assignment_category": "",
        "flsa": "Nonexempt",
        "job_code": "All excluding Paralegal",
        "value_|_default_uri": "US_New York"
    },
    {
        "mapper": "Yes",
        "type": "Timesheet Approval Path",
        "employee_type": "All",
        "country_code": "US",
        "location": "Washington",
        "person_type": "",
        "assignment_category": "",
        "flsa": "Nonexempt",
        "job_code": "All excluding Paralegal",
        "value_|_default_uri": "US_Washington"
    },
    {
        "mapper": "Yes",
        "type": "Timesheet Approval Path",
        "employee_type": "All",
        "country_code": "US",
        "location": "Houston",
        "person_type": "",
        "assignment_category": "",
        "flsa": "Nonexempt",
        "job_code": "All excluding Paralegal",
        "value_|_default_uri": "US_Houston"
    },
    {
        "mapper": "Yes",
        "type": "Timesheet Approval Path",
        "employee_type": "All",
        "country_code": "US",
        "location": "Los Angeles",
        "person_type": "",
        "assignment_category": "",
        "flsa": "Nonexempt",
        "job_code": "All excluding Paralegal",
        "value_|_default_uri": "US_Los Angeles"
    },
    {
        "mapper": "Yes",
        "type": "Timesheet Approval Path",
        "employee_type": "All",
        "country_code": "US",
        "location": "All",
        "person_type": "",
        "assignment_category": "",
        "flsa": "Nonexempt",
        "job_code": "Paralegal",
        "value_|_default_uri": "Exception"
    },
    {
        "mapper": "Yes",
        "type": "Timesheet Approval Path",
        "employee_type": "All",
        "country_code": "GB",
        "location": "All excluding London",
        "person_type": "",
        "assignment_category": "",
        "flsa": "Nonexempt",
        "job_code": "Paralegal",
        "value_|_default_uri": "Exception"
    },
    {
        "mapper": "Yes",
        "type": "Timesheet Approval Path",
        "employee_type": "All",
        "country_code": "GB",
        "location": "London",
        "person_type": "",
        "assignment_category": "",
        "flsa": "Nonexempt",
        "job_code": "All excluding Paralegal",
        "value_|_default_uri": "GB_London"
    },
    {
        "mapper": "Yes",
        "type": "Timesheet Approval Path",
        "employee_type": "All",
        "country_code": "GB",
        "location": "London",
        "person_type": "",
        "assignment_category": "",
        "flsa": "Nonexempt",
        "job_code": "Paralegal",
        "value_|_default_uri": "GB_Admin"
    },
    {
        "mapper": "Yes",
        "type": "TimeOff Approval Path",
        "employee_type": "All",
        "country_code": "GB",
        "location": "London",
        "person_type": "Administrative",
        "assignment_category": "",
        "flsa": "Exempt",
        "job_code": "All",
        "value_|_default_uri": "GB_London"
    },
    {
        "mapper": "Yes",
        "type": "Timesheet Approval Path",
        "employee_type": "Vinson & Elkins|Vinson & Elkins LLP|Billing Coordinators",
        "country_code": "US",
        "location": "All excluding Houston",
        "person_type": "",
        "assignment_category": "",
        "flsa": "Nonexempt",
        "job_code": "All excluding Paralegal",
        "value_|_default_uri": "Exception"
    },
    {
        "mapper": "Yes",
        "type": "TimeOff Approval Path",
        "employee_type": "Vinson & Elkins|Vinson & Elkins LLP|Global Document Specialists",
        "country_code": "US",
        "location": "All",
        "person_type": "Administrative",
        "assignment_category": "",
        "flsa": "All",
        "job_code": "All excluding Paralegal",
        "value_|_default_uri": "Supervisor"
    },
    {
        "mapper": "Yes",
        "type": "Timesheet Approval Path",
        "employee_type": "All",
        "country_code": "GB",
        "location": "London",
        "person_type": "",
        "assignment_category": "",
        "flsa": "Exempt",
        "job_code": "All excluding Paralegal",
        "value_|_default_uri": "GB_London"
    },
    {
        "mapper": "Yes",
        "type": "Timesheet Approval Path",
        "employee_type": "All",
        "country_code": "GB",
        "location": "London",
        "person_type": "",
        "assignment_category": "",
        "flsa": "Exempt",
        "job_code": "Paralegal",
        "value_|_default_uri": "GB_London"
    },
    {
        "mapper": "Yes",
        "type": "Timesheet Approval Path",
        "employee_type": "Vinson & Elkins|Vinson & Elkins LLP|Global Document Specialists",
        "country_code": "US",
        "location": "All excluding Houston",
        "person_type": "",
        "assignment_category": "",
        "flsa": "Exempt",
        "job_code": "All excluding Paralegal",
        "value_|_default_uri": "Supervisor --> Administrator"
    },
    {
        "mapper": "Yes",
        "type": "Timesheet Approval Path",
        "employee_type": "All",
        "country_code": "US",
        "location": "Austin",
        "person_type": "",
        "assignment_category": "",
        "flsa": "Exempt",
        "job_code": "All excluding Paralegal",
        "value_|_default_uri": "Supervisor --> Administrator"
    },
    {
        "mapper": "Yes",
        "type": "Timesheet Approval Path",
        "employee_type": "All",
        "country_code": "US",
        "location": "Dallas",
        "person_type": "",
        "assignment_category": "",
        "flsa": "Exempt",
        "job_code": "All excluding Paralegal",
        "value_|_default_uri": "Supervisor --> Administrator"
    },
    {
        "mapper": "Yes",
        "type": "Timesheet Approval Path",
        "employee_type": "All",
        "country_code": "US",
        "location": "San Francisco",
        "person_type": "",
        "assignment_category": "",
        "flsa": "Exempt",
        "job_code": "All excluding Paralegal",
        "value_|_default_uri": "Supervisor --> Administrator"
    },
    {
        "mapper": "Yes",
        "type": "Timesheet Approval Path",
        "employee_type": "All",
        "country_code": "US",
        "location": "Richmond",
        "person_type": "",
        "assignment_category": "",
        "flsa": "Exempt",
        "job_code": "All excluding Paralegal",
        "value_|_default_uri": "Supervisor --> Administrator"
    },
    {
        "mapper": "Yes",
        "type": "Timesheet Approval Path",
        "employee_type": "All",
        "country_code": "US",
        "location": "New York",
        "person_type": "",
        "assignment_category": "",
        "flsa": "Exempt",
        "job_code": "All excluding Paralegal",
        "value_|_default_uri": "Supervisor --> Administrator"
    },
    {
        "mapper": "Yes",
        "type": "Timesheet Approval Path",
        "employee_type": "All",
        "country_code": "US",
        "location": "Washington",
        "person_type": "",
        "assignment_category": "",
        "flsa": "Exempt",
        "job_code": "All excluding Paralegal",
        "value_|_default_uri": "Supervisor --> Administrator"
    },
    {
        "mapper": "Yes",
        "type": "Timesheet Approval Path",
        "employee_type": "All",
        "country_code": "US",
        "location": "Houston",
        "person_type": "",
        "assignment_category": "",
        "flsa": "Exempt",
        "job_code": "All excluding Paralegal",
        "value_|_default_uri": "Supervisor --> Administrator"
    },
    {
        "mapper": "Yes",
        "type": "Timesheet Approval Path",
        "employee_type": "All",
        "country_code": "US",
        "location": "Los Angeles",
        "person_type": "",
        "assignment_category": "",
        "flsa": "Exempt",
        "job_code": "All excluding Paralegal",
        "value_|_default_uri": "Supervisor --> Administrator"
    },
    {
        "mapper": "Yes",
        "type": "Timesheet Approval Path",
        "employee_type": "All",
        "country_code": "US",
        "location": "All",
        "person_type": "",
        "assignment_category": "",
        "flsa": "Exempt",
        "job_code": "Paralegal",
        "value_|_default_uri": "Supervisor --> Administrator"
    },
    {
        "mapper": "Yes",
        "type": "Timesheet Approval Path",
        "employee_type": "Vinson & Elkins|Vinson & Elkins LLP|Billing Coordinators",
        "country_code": "US",
        "location": "All excluding Houston",
        "person_type": "",
        "assignment_category": "",
        "flsa": "Exempt",
        "job_code": "All excluding Paralegal",
        "value_|_default_uri": "Supervisor --> Administrator"
    },
    {
        "mapper": "Yes",
        "type": "Timesheet Approval Path",
        "employee_type": "Vinson & Elkins|Vinson & Elkins LLP|Global Document Specialists",
        "country_code": "US",
        "location": "Houston",
        "person_type": "",
        "assignment_category": "",
        "flsa": "Nonexempt",
        "job_code": "All excluding Paralegal",
        "value_|_default_uri": "US_Houston"
    },
    {
        "mapper": "Yes",
        "type": "Timesheet Approval Path",
        "employee_type": "Vinson & Elkins|Vinson & Elkins LLP|Billing Coordinators",
        "country_code": "US",
        "location": "Houston",
        "person_type": "",
        "assignment_category": "",
        "flsa": "Nonexempt",
        "job_code": "All excluding Paralegal",
        "value_|_default_uri": "US_Houston"
    },
    {
        "mapper": "Yes",
        "type": "Timeoff Type",
        "employee_type": "",
        "country_code": "US",
        "location": "Los Angeles",
        "person_type": "Administrative",
        "assignment_category": "Full-Time Regular",
        "flsa": "Nonexempt",
        "job_code": "All excluding PARA",
        "value_|_default_uri": "California PTO"
    },
    {
        "mapper": "Yes",
        "type": "Timeoff Type",
        "employee_type": "",
        "country_code": "US",
        "location": "San Francisco",
        "person_type": "Administrative",
        "assignment_category": "Full-Time Regular",
        "flsa": "Nonexempt",
        "job_code": "All excluding PARA",
        "value_|_default_uri": "California PTO"
    },
    {
        "mapper": "Yes",
        "type": "Timeoff Type",
        "employee_type": "",
        "country_code": "US",
        "location": "San Francisco",
        "person_type": "Administrative",
        "assignment_category": "Part Time 80",
        "flsa": "Nonexempt",
        "job_code": "All excluding PARA",
        "value_|_default_uri": "California PTO 80%"
    },
    {
        "mapper": "Yes",
        "type": "Timeoff Type",
        "employee_type": "",
        "country_code": "US",
        "location": "Los Angeles",
        "person_type": "Administrative",
        "assignment_category": "Part Time 80",
        "flsa": "Nonexempt",
        "job_code": "All excluding PARA",
        "value_|_default_uri": "California PTO 80%"
    },
    {
        "mapper": "Yes",
        "type": "Timeoff Type",
        "employee_type": "",
        "country_code": "US",
        "location": "Austin",
        "person_type": "Administrative",
        "assignment_category": "Full-Time Regular",
        "flsa": "Nonexempt",
        "job_code": "All excluding PARA",
        "value_|_default_uri": "PTO"
    },
    {
        "mapper": "Yes",
        "type": "Timeoff Type",
        "employee_type": "",
        "country_code": "US",
        "location": "Dallas",
        "person_type": "Administrative",
        "assignment_category": "Full-Time Regular",
        "flsa": "Nonexempt",
        "job_code": "All excluding PARA",
        "value_|_default_uri": "PTO"
    },
    {
        "mapper": "Yes",
        "type": "Timeoff Type",
        "employee_type": "",
        "country_code": "US",
        "location": "New York",
        "person_type": "Administrative",
        "assignment_category": "Full-Time Regular",
        "flsa": "Nonexempt",
        "job_code": "All excluding PARA",
        "value_|_default_uri": "PTO"
    },
    {
        "mapper": "Yes",
        "type": "Timeoff Type",
        "employee_type": "",
        "country_code": "US",
        "location": "Richmond",
        "person_type": "Administrative",
        "assignment_category": "Full-Time Regular",
        "flsa": "Nonexempt",
        "job_code": "All excluding PARA",
        "value_|_default_uri": "PTO"
    },
    {
        "mapper": "Yes",
        "type": "Timeoff Type",
        "employee_type": "",
        "country_code": "US",
        "location": "Washington",
        "person_type": "Administrative",
        "assignment_category": "Full-Time Regular",
        "flsa": "Nonexempt",
        "job_code": "All excluding PARA",
        "value_|_default_uri": "PTO"
    },
    {
        "mapper": "Yes",
        "type": "Timeoff Type",
        "employee_type": "",
        "country_code": "US",
        "location": "Houston",
        "person_type": "Administrative",
        "assignment_category": "Full-Time Regular",
        "flsa": "Nonexempt",
        "job_code": "All excluding PARA",
        "value_|_default_uri": "PTO"
    },
    {
        "mapper": "Yes",
        "type": "Timesheet Approval Path",
        "employee_type": "All",
        "country_code": "US",
        "location": "All",
        "person_type": "",
        "assignment_category": "",
        "flsa": "Exempt",
        "job_code": "All excluding Paralegal",
        "value_|_default_uri": "Supervisor --> Administrator"
    },
    {
        "mapper": "Yes",
        "type": "TimeOff Approval Path",
        "employee_type": "All",
        "country_code": "US",
        "location": "Los Angeles",
        "person_type": "Attorney",
        "assignment_category": "",
        "flsa": "Nonexempt",
        "job_code": "All excluding Paralegal",
        "value_|_default_uri": "US_Los Angeles_Attorney"
    },
    {
        "mapper": "Yes",
        "type": "TimeOff Approval Path",
        "employee_type": "All",
        "country_code": "US",
        "location": "San Francisco",
        "person_type": "Attorney",
        "assignment_category": "",
        "flsa": "Nonexempt",
        "job_code": "All excluding Paralegal\t",
        "value_|_default_uri": "US_San Francisco_Attorney"
    },
    {
        "mapper": "Yes",
        "type": "Timeoff Type",
        "employee_type": "",
        "country_code": "US",
        "location": "Denver",
        "person_type": "Attorney",
        "assignment_category": "Full-Time Regular",
        "flsa": "Exempt",
        "job_code": "Associate",
        "value_|_default_uri": "Denver Attorneys Exempt Vacation"
    },
    {
        "mapper": "Yes",
        "type": "Timeoff Type",
        "employee_type": "",
        "country_code": "US",
        "location": "Denver",
        "person_type": "Attorney",
        "assignment_category": "Full-Time Regular",
        "flsa": "Exempt",
        "job_code": "Senior Associate",
        "value_|_default_uri": "Denver Attorneys Exempt Vacation"
    },
    {
        "mapper": "Yes",
        "type": "Timeoff Type",
        "employee_type": "",
        "country_code": "US",
        "location": "Denver",
        "person_type": "Attorney",
        "assignment_category": "Full-Time Regular",
        "flsa": "Exempt",
        "job_code": "Counsel",
        "value_|_default_uri": "Denver Attorneys Exempt Vacation"
    },
    {
        "mapper": "Yes",
        "type": "Timeoff Type",
        "employee_type": "",
        "country_code": "US",
        "location": "Denver",
        "person_type": "Attorney",
        "assignment_category": "Part Time 80",
        "flsa": "Exempt",
        "job_code": "Associate",
        "value_|_default_uri": "Denver Attorneys Exempt Vacation"
    },
    {
        "mapper": "Yes",
        "type": "Timeoff Type",
        "employee_type": "",
        "country_code": "US",
        "location": "Denver",
        "person_type": "Attorney",
        "assignment_category": "Part Time 80",
        "flsa": "Exempt",
        "job_code": "Senior Associate",
        "value_|_default_uri": "Denver Attorneys Exempt Vacation"
    },
    {
        "mapper": "Yes",
        "type": "Timeoff Type",
        "employee_type": "",
        "country_code": "US",
        "location": "Denver",
        "person_type": "Attorney",
        "assignment_category": "Part Time 80",
        "flsa": "Exempt",
        "job_code": "Counsel",
        "value_|_default_uri": "Denver Attorneys Exempt Vacation"
    },
    {
        "mapper": "Yes",
        "type": "Timeoff Type",
        "employee_type": "",
        "country_code": "US",
        "location": "Denver",
        "person_type": "Administrative",
        "assignment_category": "Full-Time Regular",
        "flsa": "Nonexempt",
        "job_code": "All",
        "value_|_default_uri": "Denver PTO"
    },
    {
        "mapper": "Yes",
        "type": "Timeoff Type",
        "employee_type": "",
        "country_code": "US",
        "location": "Denver",
        "person_type": "Administrative",
        "assignment_category": "Part Time 80",
        "flsa": "Nonexempt",
        "job_code": "All",
        "value_|_default_uri": "Denver PTO"
    },
    {
        "mapper": "Yes",
        "type": "Timeoff Type",
        "employee_type": "",
        "country_code": "US",
        "location": "New York",
        "person_type": "Administrative",
        "assignment_category": "Full-Time Regular",
        "flsa": "Nonexempt",
        "job_code": "All",
        "value_|_default_uri": "NY Prenatal Leave"
    },
    {
        "mapper": "Yes",
        "type": "Timeoff Type",
        "employee_type": "",
        "country_code": "US",
        "location": "New York",
        "person_type": "Administrative",
        "assignment_category": "Part Time 80",
        "flsa": "Nonexempt",
        "job_code": "All",
        "value_|_default_uri": "NY Prenatal Leave"
    },
    {
        "mapper": "Yes",
        "type": "Timeoff Type",
        "employee_type": "",
        "country_code": "US",
        "location": "New York",
        "person_type": "Administrative",
        "assignment_category": "Part Time 50",
        "flsa": "Nonexempt",
        "job_code": "All",
        "value_|_default_uri": "NY Prenatal Leave"
    },
    {
        "mapper": "Yes",
        "type": "Timeoff Type",
        "employee_type": "",
        "country_code": "US",
        "location": "New York",
        "person_type": "Administrative",
        "assignment_category": "Full-Time Regular",
        "flsa": "Nonexempt",
        "job_code": "All",
        "value_|_default_uri": "Lactation Break"
    },
    {
        "mapper": "Yes",
        "type": "Timeoff Type",
        "employee_type": "",
        "country_code": "US",
        "location": "New York",
        "person_type": "Administrative",
        "assignment_category": "Part Time 80",
        "flsa": "Nonexempt",
        "job_code": "All",
        "value_|_default_uri": "Lactation Break"
    },
    {
        "mapper": "Yes",
        "type": "Timeoff Type",
        "employee_type": "",
        "country_code": "US",
        "location": "New York",
        "person_type": "Administrative",
        "assignment_category": "Part Time 50",
        "flsa": "Nonexempt",
        "job_code": "All",
        "value_|_default_uri": "Lactation Break"
    },
    {
        "mapper": "Yes",
        "type": "Timeoff Type",
        "employee_type": "Yes",
        "country_code": "US",
        "location": "New York",
        "person_type": "Administrative",
        "assignment_category": "Full-Time Regular",
        "flsa": "All",
        "job_code": "All",
        "value_|_default_uri": "NY Unpaid Sick & Safe Time"
    },
    {
        "mapper": "Yes",
        "type": "Timeoff Type",
        "employee_type": "Yes",
        "country_code": "US",
        "location": "New York",
        "person_type": "Administrative",
        "assignment_category": "Part Time 80",
        "flsa": "All",
        "job_code": "All",
        "value_|_default_uri": "NY Unpaid Sick & Safe Time"
    },
    {
        "mapper": "Yes",
        "type": "Timeoff Type",
        "employee_type": "Yes",
        "country_code": "US",
        "location": "New York",
        "person_type": "Administrative",
        "assignment_category": "Part Time 60",
        "flsa": "All",
        "job_code": "All",
        "value_|_default_uri": "NY Unpaid Sick & Safe Time"
    }
]