momentive_othercountries_mapper = [
    {
        'type': 'Schedule',
        'workertype': 'Employee',
        'location': 'Any',
        'exemptstatus': 'Yes',
        'shift': 'Any',
        'legalentity': 'MOMENTIVE PERFORMANCE MATERIALS KOREA CO., LTD.',
        'gender': 'Any',
        'country': 'South Korea',
        'value': 'M-F 8 hours',
    },
    {
        'type': 'Time off apporval path',
        'workertype': 'Employee',
        'location': 'Any',
        'exemptstatus': 'Yes',
        'shift': 'Any',
        'legalentity': 'MOMENTIVE PERFORMANCE MATERIALS KOREA CO., LTD.',
        'gender': 'Any',
        'country': 'South Korea',
        'value': 'Supervisor',
    },
    {
        'type': 'Time off apporval path',
        'workertype': 'Employee',
        'location': 'Any',
        'exemptstatus': 'No',
        'shift': 'Any',
        'legalentity': 'MOMENTIVE PERFORMANCE MATERIALS KOREA CO., LTD.',
        'gender': 'Any',
        'country': 'South Korea',
        'value': 'Supervisor',
    },
    {
        'type': 'Language',
        'workertype': 'Employee',
        'location': 'Any',
        'exemptstatus': 'Any',
        'shift': 'Any',
        'legalentity': 'MOMENTIVE PERFORMANCE MATERIALS KOREA CO., LTD.',
        'gender': 'Any',
        'country': 'South Korea',
        'value': 'urn:replicon:language:en',
    },
    {
        'type': 'Holiday Calendar',
        'workertype': 'Employee',
        'location': 'Any',
        'exemptstatus': 'Yes',
        'shift': 'Any',
        'legalentity': 'MOMENTIVE PERFORMANCE MATERIALS KOREA CO., LTD.',
        'gender': 'Any',
        'country': 'South Korea',
        'value': 'South Korea',
    },
    {
        'type': 'Holiday Calendar',
        'workertype': 'Employee',
        'location': 'Any',
        'exemptstatus': 'No',
        'shift': 'Any',
        'legalentity': 'MOMENTIVE PERFORMANCE MATERIALS KOREA CO., LTD.',
        'gender': 'Any',
        'country': 'South Korea',
        'value': 'South Korea',
    },
    {
        'type': 'Holiday Calendar',
        'workertype': 'Contingent Worker',
        'location': 'Any',
        'exemptstatus': 'No',
        'shift': 'Any',
        'legalentity': 'MOMENTIVE PERFORMANCE MATERIALS KOREA CO., LTD.',
        'gender': 'Any',
        'country': 'South Korea',
        'value': 'South Korea',
    },
    {
        'type': 'Time off types',
        'workertype': 'Employee',
        'location': 'Any',
        'exemptstatus': 'Yes',
        'shift': 'Any',
        'legalentity': 'MOMENTIVE PERFORMANCE MATERIALS KOREA CO., LTD.',
        'gender': 'Male',
        'country': 'South Korea',
        'value': "KOR_Annual Leave 연차휴가|KOR_Paternity Leave 배우자 출산휴가|KOR_Military & Training Leave - Reservists 예비군훈련|KOR_Military & Training Leave - Civil defense 민방위훈련|KOR_Child Care Leave 육아휴직|KOR_Family Care Leave 가족돌봄휴직|KOR_Sick Leave 병가|KOR_special Leave - Marriage employee 경조사휴가(결혼/본인)|KOR_Special Leave - Marriage Children 경조사휴가(결혼/자녀)|KOR_Special Leave - Marriage Brother/Sister 경조사휴가(결혼/형제자매)|KOR_Special Leave - Parents 60th Birthday 경조사휴가(회갑/본인부모)|KOR_Special Leave - Spouse Death 경조사휴가(장례/배우자)|KOR_Special Leave - Parents Death 경조사휴가(장례/본인부모)|KOR_Special Leave - Grandparents Death 경조사휴가(장례/본인조부모)|KOR_Special Leaves - Brother/Sister Death 경조사휴가(장례/형제자매)|KOR_Special Leave - Children Death 경조사휴가(장례/자녀)|KOR_ Special Leave - House-moving 이사지원 공가|KOR_Special Leave - Medical Check 건강검진 공가|KOR_Monthly Leave 월차휴가|KOR_Summer Vacation 여름휴가|KOR_Special Leave - Spouse's Parents 60th Birthday 경조사휴가(회갑/배우자부모)|KOR_Special Leave - Spouse's Parents Death 경조사휴가(장례/배우자부모)",
    },
    {
        'type': 'Time off types',
        'workertype': 'Employee',
        'location': 'Any',
        'exemptstatus': 'No',
        'shift': 'Any',
        'legalentity': 'MOMENTIVE PERFORMANCE MATERIALS KOREA CO., LTD.',
        'gender': 'Male',
        'country': 'South Korea',
        'value': "KOR_Annual Leave 연차휴가|KOR_Paternity Leave 배우자 출산휴가|KOR_Military & Training Leave - Reservists 예비군훈련|KOR_Military & Training Leave - Civil defense 민방위훈련|KOR_Child Care Leave 육아휴직|KOR_Family Care Leave 가족돌봄휴직|KOR_Sick Leave 병가|KOR_special Leave - Marriage employee 경조사휴가(결혼/본인)|KOR_Special Leave - Marriage Children 경조사휴가(결혼/자녀)|KOR_Special Leave - Marriage Brother/Sister 경조사휴가(결혼/형제자매)|KOR_Special Leave - Parents 60th Birthday 경조사휴가(회갑/본인부모)|KOR_Special Leave - Spouse Death 경조사휴가(장례/배우자)|KOR_Special Leave - Parents Death 경조사휴가(장례/본인부모)|KOR_Special Leave - Grandparents Death 경조사휴가(장례/본인조부모)|KOR_Special Leaves - Brother/Sister Death 경조사휴가(장례/형제자매)|KOR_Special Leave - Children Death 경조사휴가(장례/자녀)|KOR_ Special Leave - House-moving 이사지원 공가|KOR_Special Leave - Medical Check 건강검진 공가|KOR_Monthly Leave 월차휴가|KOR_Summer Vacation 여름휴가|KOR_Special Leave - Spouse's Parents 60th Birthday 경조사휴가(회갑/배우자부모)|KOR_Special Leave - Spouse's Parents Death 경조사휴가(장례/배우자부모)",
    },
    {
        'type': 'Employee Type',
        'workertype': 'Employee',
        'location': 'Any',
        'exemptstatus': 'Yes',
        'shift': 'Any',
        'legalentity': 'MOMENTIVE PERFORMANCE MATERIALS KOREA CO., LTD.',
        'gender': 'Any',
        'country': 'South Korea',
        'value': 'Exempt',
    },
    {
        'type': 'Employee Type',
        'workertype': 'Contingent Worker',
        'location': 'Any',
        'exemptstatus': 'No',
        'shift': 'Any',
        'legalentity': 'MOMENTIVE PERFORMANCE MATERIALS KOREA CO., LTD.',
        'gender': 'Any',
        'country': 'South Korea',
        'value': 'Contingent Worker',
    },
    {
        'type': 'Employee Type',
        'workertype': 'Employee',
        'location': 'Any',
        'exemptstatus': 'No',
        'shift': 'Any',
        'legalentity': 'MOMENTIVE PERFORMANCE MATERIALS KOREA CO., LTD.',
        'gender': 'Any',
        'country': 'South Korea',
        'value': 'Non-Exempt',
    },
    {
        'type': 'Time off types',
        'workertype': 'Employee',
        'location': 'Any',
        'exemptstatus': 'Yes',
        'shift': 'Any',
        'legalentity': 'MOMENTIVE PERFORMANCE MATERIALS KOREA CO., LTD.',
        'gender': 'Female',
        'country': 'South Korea',
        'value': "KOR_Annual Leave 연차휴가|KOR_Maternity leave 출산휴가|KOR_Maternity leave -Plural birth 출산휴가(다태아)|KOR_Child Care Leave 육아휴직|KOR_Family Care Leave 가족돌봄휴직|KOR_Sick Leave 병가|KOR_Fertility Treatment Leave 난임치료휴가|KOR_special Leave - Marriage employee 경조사휴가(결혼/본인)|KOR_Special Leave - Marriage Children 경조사휴가(결혼/자녀)|KOR_Special Leave - Marriage Brother/Sister 경조사휴가(결혼/형제자매)|KOR_Special Leave - Parents 60th Birthday 경조사휴가(회갑/본인부모)|KOR_Special Leave - Spouse Death 경조사휴가(장례/배우자)|KOR_Special Leave - Parents Death 경조사휴가(장례/본인부모)|KOR_Special Leave - Grandparents Death 경조사휴가(장례/본인조부모)|KOR_Special Leaves - Brother/Sister Death 경조사휴가(장례/형제자매)|KOR_Special Leave - Children Death 경조사휴가(장례/자녀)|KOR_ Special Leave - House-moving 이사지원 공가|KOR_Special Leave - Medical Check 건강검진 공가|KOR_Monthly Leave 월차휴가|KOR_Summer Vacation 여름휴가|KOR_Special Leave - Spouse's Parents 60th Birthday 경조사휴가(회갑/배우자부모)|KOR_Menstruation Leave 보건휴가|KOR_Special Leave - Spouse's Parents Death 경조사휴가(장례/배우자부모)",
    },
    {
        'type': 'Time off types',
        'workertype': 'Employee',
        'location': 'Any',
        'exemptstatus': 'No',
        'shift': 'Any',
        'legalentity': 'MOMENTIVE PERFORMANCE MATERIALS KOREA CO., LTD.',
        'gender': 'Female',
        'country': 'South Korea',
        'value': "KOR_Annual Leave 연차휴가|KOR_Maternity leave 출산휴가|KOR_Maternity leave -Plural birth 출산휴가(다태아)|KOR_Child Care Leave 육아휴직|KOR_Family Care Leave 가족돌봄휴직|KOR_Sick Leave 병가|KOR_Fertility Treatment Leave 난임치료휴가|KOR_special Leave - Marriage employee 경조사휴가(결혼/본인)|KOR_Special Leave - Marriage Children 경조사휴가(결혼/자녀)|KOR_Special Leave - Marriage Brother/Sister 경조사휴가(결혼/형제자매)|KOR_Special Leave - Parents 60th Birthday 경조사휴가(회갑/본인부모)|KOR_Special Leave - Spouse Death 경조사휴가(장례/배우자)|KOR_Special Leave - Parents Death 경조사휴가(장례/본인부모)|KOR_Special Leave - Grandparents Death 경조사휴가(장례/본인조부모)|KOR_Special Leaves - Brother/Sister Death 경조사휴가(장례/형제자매)|KOR_Special Leave - Children Death 경조사휴가(장례/자녀)|KOR_ Special Leave - House-moving 이사지원 공가|KOR_Special Leave - Medical Check 건강검진 공가|KOR_Monthly Leave 월차휴가|KOR_Summer Vacation 여름휴가|KOR_Special Leave - Spouse's Parents 60th Birthday 경조사휴가(회갑/배우자부모)|KOR_Menstruation Leave 보건휴가|KOR_Special Leave - Spouse's Parents Death 경조사휴가(장례/배우자부모)",
    },
    {
        'type': 'Schedule',
        'workertype': 'Employee',
        'location': 'Any',
        'exemptstatus': 'No',
        'shift': 'Any',
        'legalentity': 'MOMENTIVE PERFORMANCE MATERIALS KOREA CO., LTD.',
        'gender': 'Any',
        'country': 'South Korea',
        'value': 'M-F 8 hours',
    },
    {
        'type': 'Schedule',
        'workertype': 'Contingent Worker',
        'location': 'Any',
        'exemptstatus': 'No',
        'shift': 'Any',
        'legalentity': 'MOMENTIVE PERFORMANCE MATERIALS KOREA CO., LTD.',
        'gender': 'Any',
        'country': 'South Korea',
        'value': 'M-F 8 hours',
    },
    {
        'type': 'Time zone',
        'workertype': 'Employee',
        'location': 'Any',
        'exemptstatus': 'No',
        'shift': 'Any',
        'legalentity': 'MOMENTIVE PERFORMANCE MATERIALS KOREA CO., LTD.',
        'gender': 'Any',
        'country': 'South Korea',
        'value': 'Asia/Seoul',
    },
    {
        'type': 'Time zone',
        'workertype': 'Employee',
        'location': 'Any',
        'exemptstatus': 'Yes',
        'shift': 'Any',
        'legalentity': 'MOMENTIVE PERFORMANCE MATERIALS KOREA CO., LTD.',
        'gender': 'Any',
        'country': 'South Korea',
        'value': 'Asia/Seoul',
    },
    {
        'type': 'Time zone',
        'workertype': 'Contingent Worker',
        'location': 'Any',
        'exemptstatus': 'No',
        'shift': 'Any',
        'legalentity': 'MOMENTIVE PERFORMANCE MATERIALS KOREA CO., LTD.',
        'gender': 'Any',
        'country': 'South Korea',
        'value': 'Asia/Seoul',
    },
    {
        'type': 'Work week',
        'workertype': 'Employee',
        'location': 'Any',
        'exemptstatus': 'No',
        'shift': 'Any',
        'legalentity': 'MOMENTIVE PERFORMANCE MATERIALS KOREA CO., LTD.',
        'gender': 'Any',
        'country': 'South Korea',
        'value': 'urn:replicon:day-of-week:monday',
    },
    {
        'type': 'Work week',
        'workertype': 'Contingent Worker',
        'location': 'Any',
        'exemptstatus': 'No',
        'shift': 'Any',
        'legalentity': 'MOMENTIVE PERFORMANCE MATERIALS KOREA CO., LTD.',
        'gender': 'Any',
        'country': 'South Korea',
        'value': 'urn:replicon:day-of-week:monday',
    },
    {
        'type': 'Work week',
        'workertype': 'Employee',
        'location': 'Any',
        'exemptstatus': 'Yes',
        'shift': 'Any',
        'legalentity': 'MOMENTIVE PERFORMANCE MATERIALS KOREA CO., LTD.',
        'gender': 'Any',
        'country': 'South Korea',
        'value': 'urn:replicon:day-of-week:monday',
    },
    {
        'type': 'Payrule',
        'workertype': 'Employee',
        'location': 'Any',
        'exemptstatus': 'Yes',
        'shift': 'Any',
        'legalentity': 'MPM FZE',
        'gender': 'Any',
        'country': 'UAE',
        'value': 'UAE_Exempt',
    },
    {
        'type': 'Schedule',
        'workertype': 'Employee',
        'location': 'Any',
        'exemptstatus': 'Yes',
        'shift': 'Any',
        'legalentity': 'MPM FZE',
        'gender': 'Any',
        'country': 'UAE',
        'value': '8 hours/day; Mon-Fri',
    },
    {
        'type': 'Timesheet Template',
        'workertype': 'Employee',
        'location': 'Any',
        'exemptstatus': 'Yes',
        'shift': 'Any',
        'legalentity': 'MPM FZE',
        'gender': 'Any',
        'country': 'UAE',
        'value': 'UAE_Timesheet',
    },
    {
        'type': 'Time off apporval path',
        'workertype': 'Employee',
        'location': 'Any',
        'exemptstatus': 'Yes',
        'shift': 'Any',
        'legalentity': 'MPM FZE',
        'gender': 'Any',
        'country': 'UAE',
        'value': 'Supervisor',
    },
    {
        'type': 'Timesheet approval path',
        'workertype': 'Employee',
        'location': 'Any',
        'exemptstatus': 'Yes',
        'shift': 'Any',
        'legalentity': 'MPM FZE',
        'gender': 'Any',
        'country': 'UAE',
        'value': 'System Approval',
    },
    {
        'type': 'Punch entry policy',
        'workertype': 'Employee',
        'location': 'Any',
        'exemptstatus': 'Yes',
        'shift': 'Any',
        'legalentity': 'MPM FZE',
        'gender': 'Any',
        'country': 'UAE',
        'value': 'UAE_Exempt',
    },
    {
        'type': 'Language',
        'workertype': 'Employee',
        'location': 'Any',
        'exemptstatus': 'Any',
        'shift': 'Any',
        'legalentity': 'MPM FZE',
        'gender': 'Any',
        'country': 'UAE',
        'value': 'urn:replicon:language:en',
    },
    {
        'type': 'Holiday Calendar',
        'workertype': 'Employee',
        'location': 'Any',
        'exemptstatus': 'Yes',
        'shift': 'Any',
        'legalentity': 'MPM FZE',
        'gender': 'Any',
        'country': 'UAE',
        'value': 'UAE',
    },
    {
        'type': 'Time off types',
        'workertype': 'Employee',
        'location': 'Any',
        'exemptstatus': 'Yes',
        'shift': 'Any',
        'legalentity': 'MPM FZE',
        'gender': 'Male',
        'country': 'UAE',
        'value': 'UAE_Leave|UAE_Sick_Leave|UAE_Paternity Leave|UAE_Unpaid Leave|UAE_Work From Home|UAE_On Duty|UAE_Compensatory Off',
    },
    {
        'type': 'Time off types',
        'workertype': 'Employee',
        'location': 'Any',
        'exemptstatus': 'Yes',
        'shift': 'Any',
        'legalentity': 'MPM FZE',
        'gender': 'Female',
        'country': 'UAE',
        'value': 'UAE_Leave|UAE_Sick_Leave|UAE_Maternity Leave|UAE_Unpaid Leave|UAE_Work From Home|UAE_On Duty|UAE_Compensatory Off',
    },
    {
        'type': 'Time zone',
        'workertype': 'Employee',
        'location': 'Any',
        'exemptstatus': 'Yes',
        'shift': 'Any',
        'legalentity': 'MPM FZE',
        'gender': 'Any',
        'country': 'UAE',
        'value': 'Asia/Baghdad',
    },
    {
        'type': 'Employee Type',
        'workertype': 'Employee',
        'location': 'Any',
        'exemptstatus': 'Yes',
        'shift': 'Any',
        'legalentity': 'MPM FZE',
        'gender': 'Any',
        'country': 'UAE',
        'value': 'Exempt',
    },
    {
        'type': 'Work week',
        'workertype': 'Employee',
        'location': 'Any',
        'exemptstatus': 'Yes',
        'shift': 'Any',
        'legalentity': 'MPM FZE',
        'gender': 'Any',
        'country': 'UAE',
        'value': 'urn:replicon:day-of-week:sunday',
    },
    {
        'type': 'Schedule',
        'workertype': 'Employee',
        'location': 'Any',
        'exemptstatus': 'Yes',
        'shift': 'Any',
        'legalentity': 'MOMENTIVE PERFORMANCE MATERIALS BENELUX BV',
        'gender': 'Any',
        'country': 'Belgium',
        'value': '8 hours/day; Mon-Fri',
    },
    {
        'type': 'Timesheet Template',
        'workertype': 'Employee',
        'location': 'Any',
        'exemptstatus': 'Yes',
        'shift': 'Any',
        'legalentity': 'MOMENTIVE PERFORMANCE MATERIALS BENELUX BV',
        'gender': 'Any',
        'country': 'Belgium',
        'value': '[BEL] Timesheet Template',
    },
    {
        'type': 'Payrule',
        'workertype': 'Employee',
        'location': 'Any',
        'exemptstatus': 'Yes',
        'shift': 'Any',
        'legalentity': 'MOMENTIVE PERFORMANCE MATERIALS BENELUX BV',
        'gender': 'Any',
        'country': 'Belgium',
        'value': 'Meal Voucher Calc',
    },
    {
        'type': 'Timesheet approval path',
        'workertype': 'Employee',
        'location': 'Any',
        'exemptstatus': 'Yes',
        'shift': 'Any',
        'legalentity': 'MOMENTIVE PERFORMANCE MATERIALS BENELUX BV',
        'gender': 'Any',
        'country': 'Belgium',
        'value': 'System Approval',
    },
    {
        'type': 'Language',
        'workertype': 'Employee',
        'location': 'Any',
        'exemptstatus': 'Any',
        'shift': 'Any',
        'legalentity': 'MOMENTIVE PERFORMANCE MATERIALS BENELUX BV',
        'gender': 'Any',
        'country': 'Belgium',
        'value': 'urn:replicon:language:en',
    },
    {
        'type': 'Time off apporval path',
        'workertype': 'Employee',
        'location': 'Any',
        'exemptstatus': 'Yes',
        'shift': 'Any',
        'legalentity': 'MOMENTIVE PERFORMANCE MATERIALS BENELUX BV',
        'gender': 'Any',
        'country': 'Belgium',
        'value': 'Supervisor',
    },
    {
        'type': 'Holiday Calendar',
        'workertype': 'Employee',
        'location': 'Any',
        'exemptstatus': 'Yes',
        'shift': 'Any',
        'legalentity': 'MOMENTIVE PERFORMANCE MATERIALS BENELUX BV',
        'gender': 'Any',
        'country': 'Belgium',
        'value': '[BEL] Holiday Calendar',
    },
    {
        'type': 'Time zone',
        'workertype': 'Employee',
        'location': 'Any',
        'exemptstatus': 'Yes',
        'shift': 'Any',
        'legalentity': 'MOMENTIVE PERFORMANCE MATERIALS BENELUX BV',
        'gender': 'Any',
        'country': 'Belgium',
        'value': 'Europe/Warsaw',
    },
    {
        'type': 'Employee Type',
        'workertype': 'Employee',
        'location': 'Any',
        'exemptstatus': 'Yes',
        'shift': 'Any',
        'legalentity': 'MOMENTIVE PERFORMANCE MATERIALS BENELUX BV',
        'gender': 'Any',
        'country': 'Belgium',
        'value': 'Exempt',
    },
    {
        'type': 'Work week',
        'workertype': 'Employee',
        'location': 'Any',
        'exemptstatus': 'Yes',
        'shift': 'Any',
        'legalentity': 'MOMENTIVE PERFORMANCE MATERIALS BENELUX BV',
        'gender': 'Any',
        'country': 'Belgium',
        'value': 'urn:replicon:day-of-week:monday',
    },
    {
        'type': 'Time off types',
        'workertype': 'Employee',
        'location': 'Any',
        'exemptstatus': 'Yes',
        'shift': 'Any',
        'legalentity': 'MOMENTIVE PERFORMANCE MATERIALS BENELUX BV',
        'gender': 'Male',
        'country': 'Belgium',
        'value': '[Bel] Adoptieverlof / Adoption|[Bel] ADV|[Bel] Anciënniteitsdag / Seniority|[Bel] Fietsdagen / Biking Days|[Bel] Jaarlijkse vakantie / Annual leave|[Bel] Occasioneel Telewerk / Occasional Home office|[Bel] Omstandigheidsverlof (Klein Verlet) / Special leave|[Bel] Onbetaald verlof / Unpaid leave|[Bel] Opleidingsverlof / Educational|[Bel] Ouderschapsverlof / Parental|[Bel] Pleegouderverlof / Foster parent|[Bel] Tijdskrediet / Sabbatical leave|[Bel] Vaderschapsverlof / Paternity|[Bel] Verlof om dwingende redenen  / Leave for Compelling reasons = leave for Unforeseen events|[Bel] Verlof om dwingende redenen / Leave for Unforeseen events = leave for compelling reasons|[Bel] Zakenreis+Werken elders / Foreign travel+Work abroad|[Bel] Ziekte / Sick leave|[Bel] Zorgverlof / Family care leave|[Bel] Zwangerschapsrust / Maternity',
    },
    {
        'type': 'Time off types',
        'workertype': 'Employee',
        'location': 'Any',
        'exemptstatus': 'Yes',
        'shift': 'Any',
        'legalentity': 'MOMENTIVE PERFORMANCE MATERIALS BENELUX BV',
        'gender': 'Female',
        'country': 'Belgium',
        'value': '[Bel] Adoptieverlof / Adoption|[Bel] ADV|[Bel] Anciënniteitsdag / Seniority|[Bel] Fietsdagen / Biking Days|[Bel] Jaarlijkse vakantie / Annual leave|[Bel] Occasioneel Telewerk / Occasional Home office|[Bel] Omstandigheidsverlof (Klein Verlet) / Special leave|[Bel] Onbetaald verlof / Unpaid leave|[Bel] Opleidingsverlof / Educational|[Bel] Ouderschapsverlof / Parental|[Bel] Pleegouderverlof / Foster parent|[Bel] Tijdskrediet / Sabbatical leave|[Bel] Vaderschapsverlof / Paternity|[Bel] Verlof om dwingende redenen  / Leave for Compelling reasons = leave for Unforeseen events|[Bel] Verlof om dwingende redenen / Leave for Unforeseen events = leave for compelling reasons|[Bel] Zakenreis+Werken elders / Foreign travel+Work abroad|[Bel] Ziekte / Sick leave|[Bel] Zorgverlof / Family care leave|[Bel] Zwangerschapsrust / Maternity',
    },
    {
        'type': 'Holiday Calendar',
        'workertype': 'Employee',
        'location': 'Any',
        'exemptstatus': 'Yes',
        'shift': 'Any',
        'legalentity': 'MOMENTIVE PERFORMANCE MATERIALS FRANCE SARL',
        'gender': 'Any',
        'country': 'France',
        'value': 'France',
    },
    {
        'type': 'Schedule',
        'workertype': 'Employee',
        'location': 'Any',
        'exemptstatus': 'Yes',
        'shift': 'Any',
        'legalentity': 'MOMENTIVE PERFORMANCE MATERIALS FRANCE SARL',
        'gender': 'Any',
        'country': 'France',
        'value': '8 hours/day; Mon-Fri',
    },
    {
        'type': 'Time off apporval path',
        'workertype': 'Employee',
        'location': 'Any',
        'exemptstatus': 'Yes',
        'shift': 'Any',
        'legalentity': 'MOMENTIVE PERFORMANCE MATERIALS FRANCE SARL',
        'gender': 'Any',
        'country': 'France',
        'value': 'Supervisor',
    },
    {
        'type': 'Language',
        'workertype': 'Employee',
        'location': 'Any',
        'exemptstatus': 'Any',
        'shift': 'Any',
        'legalentity': 'MOMENTIVE PERFORMANCE MATERIALS FRANCE SARL',
        'gender': 'Any',
        'country': 'France',
        'value': 'urn:replicon:language:en',
    },
    {
        'type': 'Time off types',
        'workertype': 'Employee',
        'location': 'Any',
        'exemptstatus': 'Yes',
        'shift': 'Any',
        'legalentity': 'MOMENTIVE PERFORMANCE MATERIALS FRANCE SARL',
        'gender': 'Male',
        'country': 'France',
        'value': 'FRA_Vacation|FRA_RTT= Réduction du temps de travail|FRA_Sick paid|FRA_Sick paid eligible for reimbursement|FRA_Sick longterm unpaid|FRA_Parental Leav|FRA_Travel|FRA_Travel within EU|FRA_Other|FRA_Historical Leave balance|FRA_Advance Vacation Days',
    },
    {
        'type': 'Time off types',
        'workertype': 'Employee',
        'location': 'Any',
        'exemptstatus': 'Yes',
        'shift': 'Any',
        'legalentity': 'MOMENTIVE PERFORMANCE MATERIALS FRANCE SARL',
        'gender': 'Female',
        'country': 'France',
        'value': 'FRA_Vacation|FRA_RTT= Réduction du temps de travail|FRA_Sick paid|FRA_Sick paid eligible for reimbursement|FRA_Sick longterm unpaid|FRA_Parental Leave|FRA_Travel|FRA_Travel within EU|FRA_Other|FRA_Maternity|FRA_Historical Leave balance|FRA_Advance Vacation Days',
    },
    {
        'type': 'Employee Type',
        'workertype': 'Employee',
        'location': 'Any',
        'exemptstatus': 'Yes',
        'shift': 'Any',
        'legalentity': 'MOMENTIVE PERFORMANCE MATERIALS FRANCE SARL',
        'gender': 'Any',
        'country': 'France',
        'value': 'Exempt',
    },
    {
        'type': 'Work week',
        'workertype': 'Employee',
        'location': 'Any',
        'exemptstatus': 'Yes',
        'shift': 'Any',
        'legalentity': 'MOMENTIVE PERFORMANCE MATERIALS FRANCE SARL',
        'gender': 'Any',
        'country': 'France',
        'value': 'urn:replicon:day-of-week:monday',
    },
    {
        'type': 'Time zone',
        'workertype': 'Employee',
        'location': 'Any',
        'exemptstatus': 'Yes',
        'shift': 'Any',
        'legalentity': 'MOMENTIVE PERFORMANCE MATERIALS FRANCE SARL',
        'gender': 'Any',
        'country': 'France',
        'value': 'Europe/Warsaw',
    },
    {
        'type': 'Holiday Calendar',
        'workertype': 'Employee',
        'location': 'Any',
        'exemptstatus': 'Yes',
        'shift': 'Any',
        'legalentity': 'MOMENTIVE PERFORMANCE MATERIALS LTD',
        'gender': 'Any',
        'country': 'United Kingdom',
        'value': 'United Kingdom',
    },
    {
        'type': 'Holiday Calendar',
        'workertype': 'Contingent Worker',
        'location': 'Any',
        'exemptstatus': 'No',
        'shift': 'Any',
        'legalentity': 'MOMENTIVE PERFORMANCE MATERIALS LTD',
        'gender': 'Any',
        'country': 'United Kingdom',
        'value': 'United Kingdom',
    },
    {
        'type': 'Schedule',
        'workertype': 'Employee',
        'location': 'Any',
        'exemptstatus': 'Yes',
        'shift': 'Any',
        'legalentity': 'MOMENTIVE PERFORMANCE MATERIALS LTD',
        'gender': 'Any',
        'country': 'United Kingdom',
        'value': '8 hours/day; Mon-Fri',
    },
    {
        'type': 'Schedule',
        'workertype': 'Employee',
        'location': 'Any',
        'exemptstatus': 'No',
        'shift': 'Any',
        'legalentity': 'MOMENTIVE PERFORMANCE MATERIALS LTD',
        'gender': 'Any',
        'country': 'United Kingdom',
        'value': '8 hours/day; Mon-Fri',
    },
    {
        'type': 'Schedule',
        'workertype': 'Contingent Worker',
        'location': 'Any',
        'exemptstatus': 'Yes',
        'shift': 'Any',
        'legalentity': 'MOMENTIVE PERFORMANCE MATERIALS LTD',
        'gender': 'Any',
        'country': 'United Kingdom',
        'value': '8 hours/day; Mon-Fri',
    },
    {
        'type': 'Schedule',
        'workertype': 'Contingent Worker',
        'location': 'Any',
        'exemptstatus': 'No',
        'shift': 'Any',
        'legalentity': 'MOMENTIVE PERFORMANCE MATERIALS LTD',
        'gender': 'Any',
        'country': 'United Kingdom',
        'value': '8 hours/day; Mon-Fri',
    },
    {
        'type': 'Schedule',
        'workertype': 'Employee',
        'location': 'Any',
        'exemptstatus': 'Yes',
        'shift': 'PRODUCTION Rota',
        'legalentity': 'MOMENTIVE PERFORMANCE MATERIALS LTD',
        'gender': 'Any',
        'country': 'United Kingdom',
        'value': 'Shift',
    },
    {
        'type': 'Schedule',
        'workertype': 'Contingent Worker',
        'location': 'Any',
        'exemptstatus': 'No',
        'shift': 'PRODUCTION Rota',
        'legalentity': 'MOMENTIVE PERFORMANCE MATERIALS LTD',
        'gender': 'Any',
        'country': 'United Kingdom',
        'value': 'Shift',
    },
    {
        'type': 'Schedule',
        'workertype': 'Employee',
        'location': 'Any',
        'exemptstatus': 'No',
        'shift': 'PRODUCTION Rota',
        'legalentity': 'MOMENTIVE PERFORMANCE MATERIALS LTD',
        'gender': 'Any',
        'country': 'United Kingdom',
        'value': 'Shift',
    },
    {
        'type': 'Schedule',
        'workertype': 'Contingent Worker',
        'location': 'Any',
        'exemptstatus': 'Yes',
        'shift': 'PRODUCTION Rota',
        'legalentity': 'MOMENTIVE PERFORMANCE MATERIALS LTD',
        'gender': 'Any',
        'country': 'United Kingdom',
        'value': 'Shift',
    },
    {
        'type': 'Schedule',
        'workertype': 'Employee',
        'location': 'Any',
        'exemptstatus': 'Yes',
        'shift': 'PRODUCTION Non Rota',
        'legalentity': 'MOMENTIVE PERFORMANCE MATERIALS LTD',
        'gender': 'Any',
        'country': 'United Kingdom',
        'value': '8 hours/day; Mon-Fri',
    },
    {
        'type': 'Schedule',
        'workertype': 'Employee',
        'location': 'Any',
        'exemptstatus': 'No',
        'shift': 'PRODUCTION Non Rota',
        'legalentity': 'MOMENTIVE PERFORMANCE MATERIALS LTD',
        'gender': 'Any',
        'country': 'United Kingdom',
        'value': '8 hours/day; Mon-Fri',
    },
    {
        'type': 'Language',
        'workertype': 'Employee',
        'location': 'Any',
        'exemptstatus': 'Any',
        'shift': 'Any',
        'legalentity': 'MOMENTIVE PERFORMANCE MATERIALS LTD',
        'gender': 'Any',
        'country': 'United Kingdom',
        'value': 'urn:replicon:language:en',
    },
    {
        'type': 'Language',
        'workertype': 'Contingent Worker',
        'location': 'Any',
        'exemptstatus': 'Any',
        'shift': 'Any',
        'legalentity': 'MOMENTIVE PERFORMANCE MATERIALS LTD',
        'gender': 'Any',
        'country': 'United Kingdom',
        'value': 'urn:replicon:language:en',
    },
    {
        'type': 'Employee Type',
        'workertype': 'Employee',
        'location': 'Any',
        'exemptstatus': 'Yes',
        'shift': 'Any',
        'legalentity': 'MOMENTIVE PERFORMANCE MATERIALS LTD',
        'gender': 'Any',
        'country': 'United Kingdom',
        'value': 'Exempt',
    },
    {
        'type': 'Employee Type',
        'workertype': 'Contingent Worker',
        'location': 'Any',
        'exemptstatus': 'No',
        'shift': 'Any',
        'legalentity': 'MOMENTIVE PERFORMANCE MATERIALS LTD',
        'gender': 'Any',
        'country': 'United Kingdom',
        'value': 'Contingent Worker',
    },
    {
        'type': 'Time zone',
        'workertype': 'Employee',
        'location': 'Any',
        'exemptstatus': 'Yes',
        'shift': 'Any',
        'legalentity': 'MOMENTIVE PERFORMANCE MATERIALS LTD',
        'gender': 'Any',
        'country': 'United Kingdom',
        'value': 'Europe/London',
    },
    {
        'type': 'Time zone',
        'workertype': 'Employee',
        'location': 'Any',
        'exemptstatus': 'No',
        'shift': 'Any',
        'legalentity': 'MOMENTIVE PERFORMANCE MATERIALS LTD',
        'gender': 'Any',
        'country': 'United Kingdom',
        'value': 'Europe/London',
    },
    {
        'type': 'Time zone',
        'workertype': 'Contingent Worker',
        'location': 'Any',
        'exemptstatus': 'No',
        'shift': 'Any',
        'legalentity': 'MOMENTIVE PERFORMANCE MATERIALS LTD',
        'gender': 'Any',
        'country': 'United Kingdom',
        'value': 'Europe/London',
    },
    {
        'type': 'Work week',
        'workertype': 'Employee',
        'location': 'Any',
        'exemptstatus': 'Yes',
        'shift': 'Any',
        'legalentity': 'MOMENTIVE PERFORMANCE MATERIALS LTD',
        'gender': 'Any',
        'country': 'United Kingdom',
        'value': 'urn:replicon:day-of-week:monday',
    },
    {
        'type': 'Work week',
        'workertype': 'Contingent Worker',
        'location': 'Any',
        'exemptstatus': 'No',
        'shift': 'Any',
        'legalentity': 'MOMENTIVE PERFORMANCE MATERIALS LTD',
        'gender': 'Any',
        'country': 'United Kingdom',
        'value': 'urn:replicon:day-of-week:monday',
    },
    {
        'type': 'Payrule',
        'workertype': 'Employee',
        'location': 'Any',
        'exemptstatus': 'Yes',
        'shift': 'PRODUCTION Rota',
        'legalentity': 'MOMENTIVE PERFORMANCE MATERIALS LTD',
        'gender': 'Any',
        'country': 'United Kingdom',
        'value': 'UK Production Pay Rule',
    },
    {
        'type': 'Payrule',
        'workertype': 'Contingent Worker',
        'location': 'Any',
        'exemptstatus': 'No',
        'shift': 'PRODUCTION Rota',
        'legalentity': 'MOMENTIVE PERFORMANCE MATERIALS LTD',
        'gender': 'Any',
        'country': 'United Kingdom',
        'value': 'UK Production Pay Rule',
    },
    {
        'type': 'Punch entry policy',
        'workertype': 'Contingent Worker',
        'location': 'Any',
        'exemptstatus': 'No',
        'shift': 'PRODUCTION Rota',
        'legalentity': 'MOMENTIVE PERFORMANCE MATERIALS LTD',
        'gender': 'Any',
        'country': 'United Kingdom',
        'value': 'UK Punch Policy',
    },
    {
        'type': 'Punch entry policy',
        'workertype': 'Contingent Worker',
        'location': 'Any',
        'exemptstatus': 'Yes',
        'shift': 'PRODUCTION Rota',
        'legalentity': 'MOMENTIVE PERFORMANCE MATERIALS LTD',
        'gender': 'Any',
        'country': 'United Kingdom',
        'value': 'UK Punch Policy',
    },
    {
        'type': 'Time off types',
        'workertype': 'Employee',
        'location': 'Any',
        'exemptstatus': 'Yes',
        'shift': 'Any',
        'legalentity': 'MOMENTIVE PERFORMANCE MATERIALS LTD',
        'gender': 'Male',
        'country': 'United Kingdom',
        'value': 'UK_Holiday Paid|UK_Holiday Unpaid|UK_Sick Leave|UK_Sick Leave unpaid|UK_Compassionate Leave paid|UK_Medical Appointment|UK_Jury Service|UK_Training|UK_Business Trip|UK_Work from home|UK_Shared Parental Leave paid|UK_Paternity|UK_Paternity unpaid',
    },
    {
        'type': 'Time off types',
        'workertype': 'Employee',
        'location': 'Any',
        'exemptstatus': 'No',
        'shift': 'Any',
        'legalentity': 'MOMENTIVE PERFORMANCE MATERIALS LTD',
        'gender': 'Male',
        'country': 'United Kingdom',
        'value': 'UK_Holiday Paid|UK_Holiday Unpaid|UK_Sick Leave|UK_Sick Leave unpaid|UK_Compassionate Leave paid|UK_Medical Appointment|UK_Jury Service|UK_Training|UK_Business Trip|UK_Work from home|UK_Shared Parental Leave paid|UK_Paternity|UK_Paternity unpaid',
    },
    {
        'type': 'Employee Type',
        'workertype': 'Employee',
        'location': 'Any',
        'exemptstatus': 'No',
        'shift': 'Any',
        'legalentity': 'MOMENTIVE PERFORMANCE MATERIALS LTD',
        'gender': 'Any',
        'country': 'United Kingdom',
        'value': 'Non-Exempt',
    },
    {
        'type': 'Holiday Calendar',
        'workertype': 'Employee',
        'location': 'Any',
        'exemptstatus': 'No',
        'shift': 'Any',
        'legalentity': 'MOMENTIVE PERFORMANCE MATERIALS LTD',
        'gender': 'Any',
        'country': 'United Kingdom',
        'value': 'United Kingdom',
    },
    {
        'type': 'Payrule',
        'workertype': 'Employee',
        'location': 'Any',
        'exemptstatus': 'No',
        'shift': 'PRODUCTION Rota',
        'legalentity': 'MOMENTIVE PERFORMANCE MATERIALS LTD',
        'gender': 'Any',
        'country': 'United Kingdom',
        'value': 'UK Production Pay Rule',
    },
    {
        'type': 'Payrule',
        'workertype': 'Contingent Worker',
        'location': 'Any',
        'exemptstatus': 'Yes',
        'shift': 'PRODUCTION Rota',
        'legalentity': 'MOMENTIVE PERFORMANCE MATERIALS LTD',
        'gender': 'Any',
        'country': 'United Kingdom',
        'value': 'UK Production Pay Rule',
    },
    {
        'type': 'Payrule',
        'workertype': 'Employee',
        'location': 'Any',
        'exemptstatus': 'Yes',
        'shift': 'PRODUCTION Non Rota',
        'legalentity': 'MOMENTIVE PERFORMANCE MATERIALS LTD',
        'gender': 'Any',
        'country': 'United Kingdom',
        'value': 'UK Other Pay Rule',
    },
    {
        'type': 'Payrule',
        'workertype': 'Contingent Worker',
        'location': 'Any',
        'exemptstatus': 'No',
        'shift': 'PRODUCTION Non Rota',
        'legalentity': 'MOMENTIVE PERFORMANCE MATERIALS LTD',
        'gender': 'Any',
        'country': 'United Kingdom',
        'value': 'UK Other Pay Rule',
    },
    {
        'type': 'Payrule',
        'workertype': 'Employee',
        'location': 'Any',
        'exemptstatus': 'No',
        'shift': 'PRODUCTION Non Rota',
        'legalentity': 'MOMENTIVE PERFORMANCE MATERIALS LTD',
        'gender': 'Any',
        'country': 'United Kingdom',
        'value': 'UK Other Pay Rule',
    },
    {
        'type': 'Payrule',
        'workertype': 'Contingent Worker',
        'location': 'Any',
        'exemptstatus': 'Yes',
        'shift': 'PRODUCTION Non Rota',
        'legalentity': 'MOMENTIVE PERFORMANCE MATERIALS LTD',
        'gender': 'Any',
        'country': 'United Kingdom',
        'value': 'UK Other Pay Rule',
    },
    {
        'type': 'Punch entry policy',
        'workertype': 'Employee',
        'location': 'Any',
        'exemptstatus': 'Yes',
        'shift': 'PRODUCTION Rota',
        'legalentity': 'MOMENTIVE PERFORMANCE MATERIALS LTD',
        'gender': 'Any',
        'country': 'United Kingdom',
        'value': 'UK Punch Policy',
    },
    {
        'type': 'Punch entry policy',
        'workertype': 'Employee',
        'location': 'Any',
        'exemptstatus': 'No',
        'shift': 'PRODUCTION Rota',
        'legalentity': 'MOMENTIVE PERFORMANCE MATERIALS LTD',
        'gender': 'Any',
        'country': 'United Kingdom',
        'value': 'UK Punch Policy',
    },
    {
        'type': 'Punch entry policy',
        'workertype': 'Employee',
        'location': 'Any',
        'exemptstatus': 'No',
        'shift': 'PRODUCTION Non Rota',
        'legalentity': 'MOMENTIVE PERFORMANCE MATERIALS LTD',
        'gender': 'Any',
        'country': 'United Kingdom',
        'value': 'UK Punch Policy',
    },
    {
        'type': 'Punch entry policy',
        'workertype': 'Employee',
        'location': 'Any',
        'exemptstatus': 'Yes',
        'shift': 'PRODUCTION Non Rota',
        'legalentity': 'MOMENTIVE PERFORMANCE MATERIALS LTD',
        'gender': 'Any',
        'country': 'United Kingdom',
        'value': 'UK Punch Policy',
    },
    {
        'type': 'Punch entry policy',
        'workertype': 'Contingent Worker',
        'location': 'Any',
        'exemptstatus': 'No',
        'shift': 'PRODUCTION Non Rota',
        'legalentity': 'MOMENTIVE PERFORMANCE MATERIALS LTD',
        'gender': 'Any',
        'country': 'United Kingdom',
        'value': 'UK Punch Policy',
    },
    {
        'type': 'Punch entry policy',
        'workertype': 'Contingent Worker',
        'location': 'Any',
        'exemptstatus': 'Yes',
        'shift': 'PRODUCTION Non Rota',
        'legalentity': 'MOMENTIVE PERFORMANCE MATERIALS LTD',
        'gender': 'Any',
        'country': 'United Kingdom',
        'value': 'UK Punch Policy',
    },
    {
        'type': 'Schedule',
        'workertype': 'Contingent Worker',
        'location': 'Any',
        'exemptstatus': 'No',
        'shift': 'PRODUCTION Non Rota',
        'legalentity': 'MOMENTIVE PERFORMANCE MATERIALS LTD',
        'gender': 'Any',
        'country': 'United Kingdom',
        'value': '8 hours/day; Mon-Fri',
    },
    {
        'type': 'Schedule',
        'workertype': 'Contingent Worker',
        'location': 'Any',
        'exemptstatus': 'Yes',
        'shift': 'PRODUCTION Non Rota',
        'legalentity': 'MOMENTIVE PERFORMANCE MATERIALS LTD',
        'gender': 'Any',
        'country': 'United Kingdom',
        'value': '8 hours/day; Mon-Fri',
    },
    {
        'type': 'Time off apporval path',
        'workertype': 'Employee',
        'location': 'Any',
        'exemptstatus': 'Yes',
        'shift': 'Any',
        'legalentity': 'MOMENTIVE PERFORMANCE MATERIALS LTD',
        'gender': 'Any',
        'country': 'United Kingdom',
        'value': 'Supervisor',
    },
    {
        'type': 'Time off apporval path',
        'workertype': 'Employee',
        'location': 'Any',
        'exemptstatus': 'No',
        'shift': 'Any',
        'legalentity': 'MOMENTIVE PERFORMANCE MATERIALS LTD',
        'gender': 'Any',
        'country': 'United Kingdom',
        'value': 'Supervisor',
    },
    {
        'type': 'Time off apporval path',
        'workertype': 'Contingent Worker',
        'location': 'Any',
        'exemptstatus': 'Yes',
        'shift': 'Any',
        'legalentity': 'MOMENTIVE PERFORMANCE MATERIALS LTD',
        'gender': 'Any',
        'country': 'United Kingdom',
        'value': 'Supervisor',
    },
    {
        'type': 'Time off apporval path',
        'workertype': 'Contingent Worker',
        'location': 'Any',
        'exemptstatus': 'No',
        'shift': 'Any',
        'legalentity': 'MOMENTIVE PERFORMANCE MATERIALS LTD',
        'gender': 'Any',
        'country': 'United Kingdom',
        'value': 'Supervisor',
    },
    {
        'type': 'Time off apporval path',
        'workertype': 'Employee',
        'location': 'Any',
        'exemptstatus': 'Yes',
        'shift': 'PRODUCTION Rota',
        'legalentity': 'MOMENTIVE PERFORMANCE MATERIALS LTD',
        'gender': 'Any',
        'country': 'United Kingdom',
        'value': 'Supervisor',
    },
    {
        'type': 'Time off apporval path',
        'workertype': 'Contingent Worker',
        'location': 'Any',
        'exemptstatus': 'No',
        'shift': 'PRODUCTION Rota',
        'legalentity': 'MOMENTIVE PERFORMANCE MATERIALS LTD',
        'gender': 'Any',
        'country': 'United Kingdom',
        'value': 'Supervisor',
    },
    {
        'type': 'Time off apporval path',
        'workertype': 'Employee',
        'location': 'Any',
        'exemptstatus': 'No',
        'shift': 'PRODUCTION Rota',
        'legalentity': 'MOMENTIVE PERFORMANCE MATERIALS LTD',
        'gender': 'Any',
        'country': 'United Kingdom',
        'value': 'Supervisor',
    },
    {
        'type': 'Time off apporval path',
        'workertype': 'Contingent Worker',
        'location': 'Any',
        'exemptstatus': 'Yes',
        'shift': 'PRODUCTION Rota',
        'legalentity': 'MOMENTIVE PERFORMANCE MATERIALS LTD',
        'gender': 'Any',
        'country': 'United Kingdom',
        'value': 'Supervisor',
    },
    {
        'type': 'Time off apporval path',
        'workertype': 'Employee',
        'location': 'Any',
        'exemptstatus': 'Yes',
        'shift': 'PRODUCTION Non Rota',
        'legalentity': 'MOMENTIVE PERFORMANCE MATERIALS LTD',
        'gender': 'Any',
        'country': 'United Kingdom',
        'value': 'Supervisor',
    },
    {
        'type': 'Time off apporval path',
        'workertype': 'Employee',
        'location': 'Any',
        'exemptstatus': 'No',
        'shift': 'PRODUCTION Non Rota',
        'legalentity': 'MOMENTIVE PERFORMANCE MATERIALS LTD',
        'gender': 'Any',
        'country': 'United Kingdom',
        'value': 'Supervisor',
    },
    {
        'type': 'Time off apporval path',
        'workertype': 'Contingent Worker',
        'location': 'Any',
        'exemptstatus': 'No',
        'shift': 'PRODUCTION Non Rota',
        'legalentity': 'MOMENTIVE PERFORMANCE MATERIALS LTD',
        'gender': 'Any',
        'country': 'United Kingdom',
        'value': 'Supervisor',
    },
    {
        'type': 'Time off apporval path',
        'workertype': 'Contingent Worker',
        'location': 'Any',
        'exemptstatus': 'Yes',
        'shift': 'PRODUCTION Non Rota',
        'legalentity': 'MOMENTIVE PERFORMANCE MATERIALS LTD',
        'gender': 'Any',
        'country': 'United Kingdom',
        'value': 'Supervisor',
    },
    {
        'type': 'Timesheet approval path',
        'workertype': 'Employee',
        'location': 'Any',
        'exemptstatus': 'Yes',
        'shift': 'PRODUCTION Rota',
        'legalentity': 'MOMENTIVE PERFORMANCE MATERIALS LTD',
        'gender': 'Any',
        'country': 'United Kingdom',
        'value': 'Supervisor',
    },
    {
        'type': 'Timesheet approval path',
        'workertype': 'Contingent Worker',
        'location': 'Any',
        'exemptstatus': 'No',
        'shift': 'PRODUCTION Rota',
        'legalentity': 'MOMENTIVE PERFORMANCE MATERIALS LTD',
        'gender': 'Any',
        'country': 'United Kingdom',
        'value': 'Supervisor',
    },
    {
        'type': 'Timesheet approval path',
        'workertype': 'Employee',
        'location': 'Any',
        'exemptstatus': 'No',
        'shift': 'PRODUCTION Rota',
        'legalentity': 'MOMENTIVE PERFORMANCE MATERIALS LTD',
        'gender': 'Any',
        'country': 'United Kingdom',
        'value': 'Supervisor',
    },
    {
        'type': 'Timesheet approval path',
        'workertype': 'Contingent Worker',
        'location': 'Any',
        'exemptstatus': 'Yes',
        'shift': 'PRODUCTION Rota',
        'legalentity': 'MOMENTIVE PERFORMANCE MATERIALS LTD',
        'gender': 'Any',
        'country': 'United Kingdom',
        'value': 'Supervisor',
    },
    {
        'type': 'Timesheet approval path',
        'workertype': 'Employee',
        'location': 'Any',
        'exemptstatus': 'Yes',
        'shift': 'PRODUCTION Non Rota',
        'legalentity': 'MOMENTIVE PERFORMANCE MATERIALS LTD',
        'gender': 'Any',
        'country': 'United Kingdom',
        'value': 'Supervisor',
    },
    {
        'type': 'Timesheet approval path',
        'workertype': 'Employee',
        'location': 'Any',
        'exemptstatus': 'No',
        'shift': 'PRODUCTION Non Rota',
        'legalentity': 'MOMENTIVE PERFORMANCE MATERIALS LTD',
        'gender': 'Any',
        'country': 'United Kingdom',
        'value': 'Supervisor',
    },
    {
        'type': 'Timesheet approval path',
        'workertype': 'Contingent Worker',
        'location': 'Any',
        'exemptstatus': 'No',
        'shift': 'PRODUCTION Non Rota',
        'legalentity': 'MOMENTIVE PERFORMANCE MATERIALS LTD',
        'gender': 'Any',
        'country': 'United Kingdom',
        'value': 'Supervisor',
    },
    {
        'type': 'Timesheet approval path',
        'workertype': 'Contingent Worker',
        'location': 'Any',
        'exemptstatus': 'Yes',
        'shift': 'PRODUCTION Non Rota',
        'legalentity': 'MOMENTIVE PERFORMANCE MATERIALS LTD',
        'gender': 'Any',
        'country': 'United Kingdom',
        'value': 'Supervisor',
    },
    {
        'type': 'Timesheet Period',
        'workertype': 'Contingent Worker',
        'location': 'Any',
        'exemptstatus': 'Any',
        'shift': 'Any',
        'legalentity': 'MOMENTIVE PERFORMANCE MATERIALS LTD',
        'gender': 'Any',
        'country': 'United Kingdom',
        'value': 'Monthly',
    },
    {
        'type': 'Timesheet Period',
        'workertype': 'Employee',
        'location': 'Any',
        'exemptstatus': 'Any',
        'shift': 'Any',
        'legalentity': 'MOMENTIVE PERFORMANCE MATERIALS LTD',
        'gender': 'Any',
        'country': 'United Kingdom',
        'value': 'Monthly',
    },
    {
        'type': 'Timesheet Template',
        'workertype': 'Employee',
        'location': 'Any',
        'exemptstatus': 'Yes',
        'shift': 'PRODUCTION Rota',
        'legalentity': 'MOMENTIVE PERFORMANCE MATERIALS LTD',
        'gender': 'Any',
        'country': 'United Kingdom',
        'value': 'UK Timesheet',
    },
    {
        'type': 'Timesheet Template',
        'workertype': 'Contingent Worker',
        'location': 'Any',
        'exemptstatus': 'No',
        'shift': 'PRODUCTION Rota',
        'legalentity': 'MOMENTIVE PERFORMANCE MATERIALS LTD',
        'gender': 'Any',
        'country': 'United Kingdom',
        'value': 'UK Timesheet',
    },
    {
        'type': 'Timesheet Template',
        'workertype': 'Employee',
        'location': 'Any',
        'exemptstatus': 'No',
        'shift': 'PRODUCTION Rota',
        'legalentity': 'MOMENTIVE PERFORMANCE MATERIALS LTD',
        'gender': 'Any',
        'country': 'United Kingdom',
        'value': 'UK Timesheet',
    },
    {
        'type': 'Timesheet Template',
        'workertype': 'Contingent Worker',
        'location': 'Any',
        'exemptstatus': 'Yes',
        'shift': 'PRODUCTION Rota',
        'legalentity': 'MOMENTIVE PERFORMANCE MATERIALS LTD',
        'gender': 'Any',
        'country': 'United Kingdom',
        'value': 'UK Timesheet',
    },
    {
        'type': 'Timesheet Template',
        'workertype': 'Employee',
        'location': 'Any',
        'exemptstatus': 'Yes',
        'shift': 'PRODUCTION Non Rota',
        'legalentity': 'MOMENTIVE PERFORMANCE MATERIALS LTD',
        'gender': 'Any',
        'country': 'United Kingdom',
        'value': 'UK Timesheet',
    },
    {
        'type': 'Timesheet Template',
        'workertype': 'Employee',
        'location': 'Any',
        'exemptstatus': 'No',
        'shift': 'PRODUCTION Non Rota',
        'legalentity': 'MOMENTIVE PERFORMANCE MATERIALS LTD',
        'gender': 'Any',
        'country': 'United Kingdom',
        'value': 'UK Timesheet',
    },
    {
        'type': 'Timesheet Template',
        'workertype': 'Contingent Worker',
        'location': 'Any',
        'exemptstatus': 'No',
        'shift': 'PRODUCTION Non Rota',
        'legalentity': 'MOMENTIVE PERFORMANCE MATERIALS LTD',
        'gender': 'Any',
        'country': 'United Kingdom',
        'value': 'UK Timesheet',
    },
    {
        'type': 'Timesheet Template',
        'workertype': 'Contingent Worker',
        'location': 'Any',
        'exemptstatus': 'Yes',
        'shift': 'PRODUCTION Non Rota',
        'legalentity': 'MOMENTIVE PERFORMANCE MATERIALS LTD',
        'gender': 'Any',
        'country': 'United Kingdom',
        'value': 'UK Timesheet',
    },
    {
        'type': 'Work week',
        'workertype': 'Employee',
        'location': 'Any',
        'exemptstatus': 'No',
        'shift': 'Any',
        'legalentity': 'MOMENTIVE PERFORMANCE MATERIALS LTD',
        'gender': 'Any',
        'country': 'United Kingdom',
        'value': 'urn:replicon:day-of-week:monday',
    },
    {
        'type': 'Time off types',
        'workertype': 'Employee',
        'location': 'Any',
        'exemptstatus': 'Yes',
        'shift': 'Any',
        'legalentity': 'MOMENTIVE PERFORMANCE MATERIALS LTD',
        'gender': 'Female',
        'country': 'United Kingdom',
        'value': 'UK_Holiday Paid|UK_Holiday Unpaid|UK_Sick Leave|UK_Sick Leave unpaid|UK_Compassionate Leave paid|UK_Medical Appointment|UK_Jury Service|UK_Training|UK_Business Trip|UK_Work from home|UK_Maternity Leave paid|UK_Maternity unpaid|UK_KIT Days|UK_Shared Parental Leave paid',
    },
    {
        'type': 'Time off types',
        'workertype': 'Employee',
        'location': 'Any',
        'exemptstatus': 'No',
        'shift': 'Any',
        'legalentity': 'MOMENTIVE PERFORMANCE MATERIALS LTD',
        'gender': 'Female',
        'country': 'United Kingdom',
        'value': 'UK_Holiday Paid|UK_Holiday Unpaid|UK_Sick Leave|UK_Sick Leave unpaid|UK_Compassionate Leave paid|UK_Medical Appointment|UK_Jury Service|UK_Training|UK_Business Trip|UK_Work from home|UK_Maternity Leave paid|UK_Maternity unpaid|UK_KIT Days|UK_Shared Parental Leave paid',
    },
    {
        'type': 'Time off types',
        'workertype': 'Contingent Worker',
        'location': 'Any',
        'exemptstatus': 'Yes',
        'shift': 'Any',
        'legalentity': 'MOMENTIVE PERFORMANCE MATERIALS LTD',
        'gender': 'Male',
        'country': 'United Kingdom',
        'value': 'UK_Holiday Paid|UK_Holiday Unpaid|UK_Sick Leave|UK_Sick Leave unpaid|UK_Compassionate Leave paid|UK_Medical Appointment|UK_Jury Service|UK_Training|UK_Business Trip|UK_Work from home|UK_Shared Parental Leave paid|UK_Paternity|UK_Paternity unpaid',
    },
    {
        'type': 'Time off types',
        'workertype': 'Contingent Worker',
        'location': 'Any',
        'exemptstatus': 'No',
        'shift': 'Any',
        'legalentity': 'MOMENTIVE PERFORMANCE MATERIALS LTD',
        'gender': 'Male',
        'country': 'United Kingdom',
        'value': 'UK_Holiday Paid|UK_Holiday Unpaid|UK_Sick Leave|UK_Sick Leave unpaid|UK_Compassionate Leave paid|UK_Medical Appointment|UK_Jury Service|UK_Training|UK_Business Trip|UK_Work from home|UK_Shared Parental Leave paid|UK_Paternity|UK_Paternity unpaid',
    },
    {
        'type': 'Time off types',
        'workertype': 'Contingent Worker',
        'location': 'Any',
        'exemptstatus': 'Yes',
        'shift': 'Any',
        'legalentity': 'MOMENTIVE PERFORMANCE MATERIALS LTD',
        'gender': 'Female',
        'country': 'United Kingdom',
        'value': 'UK_Holiday Paid|UK_Holiday Unpaid|UK_Sick Leave|UK_Sick Leave unpaid|UK_Compassionate Leave paid|UK_Medical Appointment|UK_Jury Service|UK_Training|UK_Business Trip|UK_Work from home|UK_Maternity Leave paid|UK_Maternity unpaid|UK_KIT Days|UK_Shared Parental Leave paid',
    },
    {
        'type': 'Time off types',
        'workertype': 'Contingent Worker',
        'location': 'Any',
        'exemptstatus': 'No',
        'shift': 'Any',
        'legalentity': 'MOMENTIVE PERFORMANCE MATERIALS LTD',
        'gender': 'Female',
        'country': 'United Kingdom',
        'value': 'UK_Holiday Paid|UK_Holiday Unpaid|UK_Sick Leave|UK_Sick Leave unpaid|UK_Compassionate Leave paid|UK_Medical Appointment|UK_Jury Service|UK_Training|UK_Business Trip|UK_Work from home|UK_Maternity Leave paid|UK_Maternity unpaid|UK_KIT Days|UK_Shared Parental Leave paid',
    },
    {
        'type': 'Timesheet Template',
        'workertype': 'Employee',
        'location': 'Any',
        'exemptstatus': 'Yes',
        'shift': 'Any',
        'legalentity': 'MOMENTIVE PERFORMANCE MATERIALS KOREA CO., LTD.',
        'gender': 'Any',
        'country': 'South Korea',
        'value': 'South Korea',
    },
    {
        'type': 'Timesheet Template',
        'workertype': 'Contingent Worker',
        'location': 'Any',
        'exemptstatus': 'No',
        'shift': 'Any',
        'legalentity': 'MOMENTIVE PERFORMANCE MATERIALS KOREA CO., LTD.',
        'gender': 'Any',
        'country': 'South Korea',
        'value': 'South Korea',
    },
    {
        'type': 'Timesheet Template',
        'workertype': 'Employee',
        'location': 'Any',
        'exemptstatus': 'No',
        'shift': 'Any',
        'legalentity': 'MOMENTIVE PERFORMANCE MATERIALS KOREA CO., LTD.',
        'gender': 'Any',
        'country': 'South Korea',
        'value': 'South Korea',
    },
    {
        'type': 'Punch entry policy',
        'workertype': 'Employee',
        'location': 'Any',
        'exemptstatus': 'Yes',
        'shift': 'Any',
        'legalentity': 'MOMENTIVE PERFORMANCE MATERIALS KOREA CO., LTD.',
        'gender': 'Any',
        'country': 'South Korea',
        'value': 'SK_Exempt',
    },
    {
        'type': 'Punch entry policy',
        'workertype': 'Contingent Worker',
        'location': 'Any',
        'exemptstatus': 'No',
        'shift': 'Any',
        'legalentity': 'MOMENTIVE PERFORMANCE MATERIALS KOREA CO., LTD.',
        'gender': 'Any`',
        'country': 'South Korea',
        'value': 'SK_Non Exempt',
    },
    {
        'type': 'Punch entry policy',
        'workertype': 'Employee',
        'location': 'Any',
        'exemptstatus': 'No',
        'shift': 'Any',
        'legalentity': 'MOMENTIVE PERFORMANCE MATERIALS KOREA CO., LTD.',
        'gender': 'Any',
        'country': 'South Korea',
        'value': 'SK_Exempt',
    },
    {
        'type': 'Payrule',
        'workertype': 'Employee',
        'location': 'Any',
        'exemptstatus': 'Yes',
        'shift': 'Any',
        'legalentity': 'MOMENTIVE PERFORMANCE MATERIALS KOREA CO., LTD.',
        'gender': 'Any',
        'country': 'South Korea',
        'value': 'South Korea_Exempt',
    },
    {
        'type': 'Payrule',
        'workertype': 'Contingent Worker',
        'location': 'Any',
        'exemptstatus': 'No',
        'shift': 'Any',
        'legalentity': 'MOMENTIVE PERFORMANCE MATERIALS KOREA CO., LTD.',
        'gender': 'Any',
        'country': 'South Korea',
        'value': 'South Korea_Non Exempt',
    },
    {
        'type': 'Payrule',
        'workertype': 'Employee',
        'location': 'Any',
        'exemptstatus': 'No',
        'shift': 'Any',
        'legalentity': 'MOMENTIVE PERFORMANCE MATERIALS KOREA CO., LTD.',
        'gender': 'Any',
        'country': 'South Korea',
        'value': 'South Korea_Contingent Worker',
    },
    {
        'type': 'Timesheet approval path',
        'workertype': 'Employee',
        'location': 'Any',
        'exemptstatus': 'Yes',
        'shift': 'Any',
        'legalentity': 'MOMENTIVE PERFORMANCE MATERIALS KOREA CO., LTD.',
        'gender': 'Any',
        'country': 'South Korea',
        'value': 'System Approval',
    },
    {
        'type': 'Timesheet approval path',
        'workertype': 'Employee',
        'location': 'Any',
        'exemptstatus': 'No',
        'shift': 'Any',
        'legalentity': 'MOMENTIVE PERFORMANCE MATERIALS KOREA CO., LTD.',
        'gender': 'Any',
        'country': 'South Korea',
        'value': 'Supervisor --> HRM',
    },
    {
        'type': 'Timesheet approval path',
        'workertype': 'Contingent Worker',
        'location': 'Any',
        'exemptstatus': 'No',
        'shift': 'Any',
        'legalentity': 'MOMENTIVE PERFORMANCE MATERIALS KOREA CO., LTD.',
        'gender': 'Any',
        'country': 'South Korea',
        'value': 'System Approval',
    },
]


def mapper_value(category, **criteria):
    """Replicate the Workato lookup_table search on the common "other countries" mapper.

    Returns the first row's 'value' whose 'type' == category and whose columns
    exactly match the supplied criteria (Workato matches the literal stored values,
    including the "Any" wildcard). Returns '' when nothing matches.
    """
    for row in momentive_othercountries_mapper:
        if row['type'] != category:
            continue
        if all(row.get(col) == val for col, val in criteria.items()):
            return row['value']
    return ''
