null = None
# pylint: disable = line-too-long
user_mapper = [
    {
        "holiday_calendar": "United States",
        "office_schedule": "8 hours/day; Mon-Fri",
        "timesheet_approval_path": "Supervisor",
        "timeoff_approval_path": "Supervisor",
        "timeZone": "urn:replicon:time-zone:etc-gmt",
        "workweek": "urn:replicon:day-of-week:sunday",
        "timesheet_period_type": "urn:replicon:timesheet-period-type:system",
        "user_permission": "Project Resource with Reports",
        "supervisor_permission": "Supervisor",
        "timesheet_template": "Simpletime user Timesheet Template",
        "time_off_template": "Time Off",
        "authenticationtype": "replicon",
        "default_password": "Replicon@12",
        "payrule": "Alaska",
        "punchentrypolicy": "",
        "account": "",
        "country": "",
        "employee_type": "",
        "general_labor_category": "",
        "labor_location": "",
        "organizations": ""
    },
    {
        "holiday_calendar": "United States",
        "office_schedule": "8 hours/day; Mon-Fri",
        "timesheet_approval_path": "Supervisor",
        "timeoff_approval_path": "Supervisor",
        "timeZone": "urn:replicon:time-zone:etc-gmt",
        "workweek": "urn:replicon:day-of-week:sunday",
        "timesheet_period_type": "urn:replicon:timesheet-period-type:system",
        "user_permission": "Project Resource with Reports",
        "supervisor_permission": "Supervisor",
        "timesheet_template": "CAPunch User_California",
        "time_off_template": "Time Off",
        "authenticationtype": "replicon",
        "default_password": "Replicon@12",
        "payrule": "Alaska",
        "punchentrypolicy": "Simple Punch (from any device)",
        "account": "",
        "country": "",
        "employee_type": "",
        "general_labor_category": "",
        "labor_location": "",
        "organizations": ""
    },
    {
        "holiday_calendar": "United States",
        "office_schedule": "8 hours/day; Mon-Fri",
        "timesheet_approval_path": "Supervisor",
        "timeoff_approval_path": "Supervisor",
        "timeZone": "urn:replicon:time-zone:etc-gmt",
        "workweek": "urn:replicon:day-of-week:sunday",
        "timesheet_period_type": "urn:replicon:timesheet-period-type:system",
        "user_permission": "Project Resource with Reports",
        "supervisor_permission": "Supervisor",
        "timesheet_template": "Simpletime user Timesheet Template",
        "time_off_template": "Time Off",
        "authenticationtype": "replicon",
        "default_password": "Replicon@12",
        "payrule": "California",
        "punchentrypolicy": "",
        "account": "",
        "country": "",
        "employee_type": "",
        "general_labor_category": "",
        "labor_location": "",
        "organizations": ""
    },
    {
        "holiday_calendar": "United States",
        "office_schedule": "8 hours/day; Mon-Fri",
        "timesheet_approval_path": "Supervisor",
        "timeoff_approval_path": "Supervisor",
        "timeZone": "urn:replicon:time-zone:etc-gmt",
        "workweek": "urn:replicon:day-of-week:sunday",
        "timesheet_period_type": "urn:replicon:timesheet-period-type:system",
        "user_permission": "Project Resource with Reports",
        "supervisor_permission": "Supervisor",
        "timesheet_template": "CAPunch User_California",
        "time_off_template": "Time Off",
        "authenticationtype": "replicon",
        "default_password": "Replicon@12",
        "payrule": "California",
        "punchentrypolicy": "Simple Punch (from any device)",
        "account": "",
        "country": "",
        "employee_type": "",
        "general_labor_category": "",
        "labor_location": "",
        "organizations": ""
    },
    {
        "holiday_calendar": "United States",
        "office_schedule": "8 hours/day; Mon-Fri",
        "timesheet_approval_path": "Supervisor",
        "timeoff_approval_path": "Supervisor",
        "timeZone": "urn:replicon:time-zone:etc-gmt",
        "workweek": "urn:replicon:day-of-week:sunday",
        "timesheet_period_type": "urn:replicon:timesheet-period-type:system",
        "user_permission": "Project Resource with Reports",
        "supervisor_permission": "Supervisor",
        "timesheet_template": "Simpletime user Timesheet Template",
        "time_off_template": "Time Off",
        "authenticationtype": "replicon",
        "default_password": "Replicon@12",
        "payrule": "Colorado",
        "punchentrypolicy": "",
        "account": "",
        "country": "",
        "employee_type": "",
        "general_labor_category": "",
        "labor_location": "",
        "organizations": ""
    },
    {
        "holiday_calendar": "United States",
        "office_schedule": "8 hours/day; Mon-Fri",
        "timesheet_approval_path": "Supervisor",
        "timeoff_approval_path": "Supervisor",
        "timeZone": "urn:replicon:time-zone:etc-gmt",
        "workweek": "urn:replicon:day-of-week:sunday",
        "timesheet_period_type": "urn:replicon:timesheet-period-type:system",
        "user_permission": "Project Resource with Reports",
        "supervisor_permission": "Supervisor",
        "timesheet_template": "Simpletime user Timesheet Template",
        "time_off_template": "Time Off",
        "authenticationtype": "replicon",
        "default_password": "Replicon@12",
        "payrule": "Washington D.C.",
        "punchentrypolicy": "",
        "account": "",
        "country": "",
        "employee_type": "",
        "general_labor_category": "",
        "labor_location": "",
        "organizations": ""
    },
    {
        "holiday_calendar": "United States",
        "office_schedule": "8 hours/day; Mon-Fri",
        "timesheet_approval_path": "Supervisor",
        "timeoff_approval_path": "Supervisor",
        "timeZone": "urn:replicon:time-zone:etc-gmt",
        "workweek": "urn:replicon:day-of-week:sunday",
        "timesheet_period_type": "urn:replicon:timesheet-period-type:system",
        "user_permission": "Project Resource with Reports",
        "supervisor_permission": "Supervisor",
        "timesheet_template": "Simpletime user Timesheet Template",
        "time_off_template": "Time Off",
        "authenticationtype": "replicon",
        "default_password": "Replicon@12",
        "payrule": "Georgia (FLSA Coverage)",
        "punchentrypolicy": "",
        "account": "",
        "country": "",
        "employee_type": "",
        "general_labor_category": "",
        "labor_location": "",
        "organizations": ""
    },
    {
        "holiday_calendar": "United States",
        "office_schedule": "8 hours/day; Mon-Fri",
        "timesheet_approval_path": "Supervisor",
        "timeoff_approval_path": "Supervisor",
        "timeZone": "urn:replicon:time-zone:etc-gmt",
        "workweek": "urn:replicon:day-of-week:sunday",
        "timesheet_period_type": "urn:replicon:timesheet-period-type:system",
        "user_permission": "Project Resource with Reports",
        "supervisor_permission": "Supervisor",
        "timesheet_template": "Simpletime user Timesheet Template",
        "time_off_template": "Time Off",
        "authenticationtype": "replicon",
        "default_password": "Replicon@12",
        "payrule": "Maryland",
        "punchentrypolicy": "",
        "account": "",
        "country": "",
        "employee_type": "",
        "general_labor_category": "",
        "labor_location": "",
        "organizations": ""
    },
    {
        "holiday_calendar": "United States",
        "office_schedule": "8 hours/day; Mon-Fri",
        "timesheet_approval_path": "Supervisor",
        "timeoff_approval_path": "Supervisor",
        "timeZone": "urn:replicon:time-zone:etc-gmt",
        "workweek": "urn:replicon:day-of-week:sunday",
        "timesheet_period_type": "urn:replicon:timesheet-period-type:system",
        "user_permission": "Project Resource with Reports",
        "supervisor_permission": "Supervisor",
        "timesheet_template": "Simpletime user Timesheet Template",
        "time_off_template": "Time Off",
        "authenticationtype": "replicon",
        "default_password": "Replicon@12",
        "payrule": "New York",
        "punchentrypolicy": "",
        "account": "",
        "country": "",
        "employee_type": "",
        "general_labor_category": "",
        "labor_location": "",
        "organizations": ""
    },
    {
        "holiday_calendar": "United States",
        "office_schedule": "8 hours/day; Mon-Fri",
        "timesheet_approval_path": "Supervisor",
        "timeoff_approval_path": "Supervisor",
        "timeZone": "urn:replicon:time-zone:etc-gmt",
        "workweek": "urn:replicon:day-of-week:sunday",
        "timesheet_period_type": "urn:replicon:timesheet-period-type:system",
        "user_permission": "Project Resource with Reports",
        "supervisor_permission": "Supervisor",
        "timesheet_template": "Simpletime user Timesheet Template",
        "time_off_template": "Time Off",
        "authenticationtype": "replicon",
        "default_password": "Replicon@12",
        "payrule": "Virginia (FLSA Coverage)",
        "punchentrypolicy": "",
        "account": "",
        "country": "",
        "employee_type": "",
        "general_labor_category": "",
        "labor_location": "",
        "organizations": ""
    }
]
