# pylint: disable=wildcard-import unused-wildcard-import
from dxctechnology.workday_user_import_v1.user_import.config import *
from dxctechnology.workday_user_import_v1.user_import.mappers.master_mapper import MAPPER
instance = "trial"

version = "v3"
process_time_off_accrual_dag_version = "v1"
ia_version = "v1"
global_disable_timeoff_process_child_dag_version = "v2"

environment = "pre-production"
can_run_batch_task_var_name_australia = f"dxctechnology_workday_user_import_australia_can_run_batch_task_variable_{instance}"

company_key = "dxctrial01"
replicon_conn_id = "dxctrial01_replicon_x.replicon.workday1"
sftp_conn_id = "sftp_useast2"

pgp_conn_id = "dxctechnology_workday_user_import_pgp_connection"

input_file_path = "/WD/Input"
archive_file_path = "/WD/Archives"
log_file_path = "/WD/Logs"

tenant_email = '{{ var.value.dagrun_internal_testing_email }}'
internal_logs_email = '{{ var.value.dagrun_internal_testing_email }}'
alert_email = '{{ var.value.dagrun_failure_alert_email }}'
bcc_emails = "{{ var.value.dagrun_internal_testing_email }}"

can_decrypt_file_var_name = f'dxctechnology_workday_user_sync_can_decrypt_file_{instance}'

DXC_WORKDAY_USER_SYNC_USER_MAPPER = MAPPER

workday_user_import_australia_users_add_user_child_dag = f"dxctechnology_workday_user_import_australia_users_add_user_child_{instance}_{version}"
workday_user_import_australia_users_add_user_timeoff_process_child_dag = f"dxctechnology_workday_user_import_australia_users_add_user_timeoff_process_child_{instance}_{version}"
workday_user_import_australia_users_update_user_timeoff_process_child_dag = f"dxctechnology_workday_user_import_australia_users_update_user_timeoff_process_child_{instance}_{version}"

workday_user_import_australia_users_update_user_timeoff_process_child_dag_disable = f"dxctechnology_workday_user_import_australia_users_update_user_timeoff_process_child_for_disable_user_{instance}_{version}"
workday_user_import_australia_users_update_user_child_dag = f"dxctechnology_workday_user_import_australia_users_update_user_child_{instance}_{version}"

workday_user_import_australia_users_update_user_rehire_timeoff_process_child_dag = f"dxctechnology_workday_user_import_australia_users_update_user_rehire_timeoff_assignment_process_child_{instance}_{version}"
workday_user_import_australia_users_aus_personal_carers_leave_timeoff_assignment_child_dag = f"dxctechnology_workday_user_import_australia_users_aus_personal_carers_leave_timeoff_assignment_child_{instance}_{version}"
workday_user_import_australia_users_aus_annual_leave_parttime_timeoff_assignment_child_dag = f"dxctechnology_workday_user_import_australia_users_aus_annual_leave_parttime_timeoff_assignment_child_{instance}_{version}"
workday_user_import_australia_users_aus_long_service_leave_timeoff_assignment_child_dag = f"dxctechnology_workday_user_import_australia_users_aus_long_service_leave_timeoff_assignment_child_{instance}_{version}"
workday_user_import_australia_users_aus_lsl_protata_timeoff_assignment_child_dag = f"dxctechnology_workday_user_import_australia_users_aus_lsl_protata_timeoff_assignment_child_{instance}_{version}"
workday_user_import_australia_users_aus_annual_leave_timeoff_assignment_child_dag = f"dxctechnology_workday_user_import_australia_users_aus_annual_leave_timeoff_assignment_child_{instance}_{version}"

# Available in GBL setup
workday_user_import_global_v2_users_update_user_timeoff_process_child_dag_disable = f"dxctechnology_workday_user_import_global_users_update_user_timeoff_process_child_for_disable_user_{instance}_{global_disable_timeoff_process_child_dag_version}"

process_time_off_accrual = f"dxctechnology_workday_user_sync_timeoff_assignment_policy_update_for_no_accrual_child_{instance}_{process_time_off_accrual_dag_version}"

workday_user_import_ia_zero_timeoff_assignment_child_dag = f"dxctechnology_workday_user_import_ia_zero_timeoff_assignment_child_{instance}_{ia_version}"
workday_user_import_ia_one_timeoff_assignment_child_dag = f"dxctechnology_workday_user_import_ia_one_timeoff_assignment_child_{instance}_{ia_version}"

timeoff_process_max_active_run = 10
user_process_max_active_run = 10

# Cleanup child DAG ID for disabled users
delete_future_entries_child_dag_id = f"dxctechnology_workday_user_sync_delete_future_entries_child_{instance}_v2"
