BELGIUM_USER_MAPPER = [
    {
        "country": "Belgium",
        "location": "ALL",
        "worker_type": "Employee",
        "compensation_grade": "Salary",
        "contract_type": "Full_time",
        "employee_type": [
            "Regular",
            "Fixed Term",
            "Partner",
            "Intern",
            "Non-Salaried / Self-Employed",
            "Non-Salaried / Self-Employed (Fixed Term)"
        ],
        "job_category": [
            "Functional",
            "Client Services"
        ],
        "management_level": [
            "Partner",
            "Executive Vice President",
            "Senior Vice President",
            "Vice President",
            "Director",
            "Senior Manager",
            "Manager",
            "Senior Associate",
            "Specialist 1",
            "Specialist 2",
            "Associate",
            "Trainee/Apprentice",
            "Administrative 1",
            "Administrative 2"
        ],
        "additional_job_classification": "BEL_OT_Policy_A",
        "company_code": "NA",
        "schedule_type": "Office Schedule (Assigned to user via another automation)",
        "work_week": "Sunday to Saturday",
        "timesheet_template": "Belgium TSD Agile Emp OT",
        "time_entry_approval_path": "Automatic Approval",
        "timesheet_approval": "Supervisor",
        "timesheet_period": "Weekly without crossing months",
        "time_off_template": "Time Off",
        "time_off_approval": "System",
        "time_off_types": [
            "BEL_TOIL",
            "Holiday",
            "Leave of Absence"
        ],
        "payrule": "Belgium FT SAL Policy A",
        "time_zone": "(UTC+1:00) Central Europe Standard Time",
        "holiday_calendar": "Belgium Holiday Calendar",
        "authentication_type": "SSO"
    },
    {
        "country": "Belgium",
        "location": "ALL",
        "worker_type": "Employee",
        "compensation_grade": "Salary",
        "contract_type": "Part_time",
        "employee_type": [
            "Regular",
            "Fixed Term",
            "Partner",
            "Intern",
            "Non-Salaried / Self-Employed",
            "Non-Salaried / Self-Employed (Fixed Term)"
        ],
        "job_category": [
            "Functional",
            "Client Services"
        ],
        "management_level": [
            "Partner",
            "Executive Vice President",
            "Senior Vice President",
            "Vice President",
            "Director",
            "Senior Manager",
            "Manager",
            "Senior Associate",
            "Specialist 1",
            "Specialist 2",
            "Associate",
            "Trainee/Apprentice",
            "Administrative 1",
            "Administrative 2"
        ],
        "additional_job_classification": "BEL_OT_Policy_A",
        "company_code": "NA",
        "schedule_type": "Office Schedule (Assigned to user via another automation)",
        "work_week": "Sunday to Saturday",
        "timesheet_template": "Belgium TSD Agile Emp OT",
        "time_entry_approval_path": "Automatic Approval",
        "timesheet_approval": "Supervisor",
        "timesheet_period": "Weekly without crossing months",
        "time_off_template": "Time Off",
        "time_off_approval": "System",
        "time_off_types": [
            "BEL_TOIL",
            "Holiday",
            "Leave of Absence"
        ],
        "payrule": "Belgium PT SAL Policy A",
        "time_zone": "(UTC+1:00) Central Europe Standard Time",
        "holiday_calendar": "Belgium Holiday Calendar",
        "authentication_type": "SSO"
    },
    {
        "country": "Belgium",
        "location": "ALL",
        "worker_type": "Employee",
        "compensation_grade": "Salary",
        "contract_type": "Full_time",
        "employee_type": [
            "Regular",
            "Fixed Term",
            "Partner",
            "Intern",
            "Non-Salaried / Self-Employed",
            "Non-Salaried / Self-Employed (Fixed Term)"
        ],
        "job_category": [
            "Functional",
            "Client Services"
        ],
        "management_level": [
            "Partner",
            "Executive Vice President",
            "Senior Vice President",
            "Vice President",
            "Director",
            "Senior Manager",
            "Manager",
            "Senior Associate",
            "Specialist 1",
            "Specialist 2",
            "Associate",
            "Trainee/Apprentice",
            "Administrative 1",
            "Administrative 2"
        ],
        "additional_job_classification": "BEL_OT_Policy_B",
        "company_code": "NA",
        "schedule_type": "Office Schedule (Assigned to user via another automation)",
        "work_week": "Sunday to Saturday",
        "timesheet_template": "Belgium TSD Agile Emp OT",
        "time_entry_approval_path": "Automatic Approval",
        "timesheet_approval": "Supervisor",
        "timesheet_period": "Weekly without crossing months",
        "time_off_template": "Time Off",
        "time_off_approval": "System",
        "time_off_types": [
            "BEL_TOIL",
            "Holiday",
            "Leave of Absence"
        ],
        "payrule": "Belgium FT SAL Policy B",
        "time_zone": "(UTC+1:00) Central Europe Standard Time",
        "holiday_calendar": "Belgium Holiday Calendar",
        "authentication_type": "SSO"
    },
    {
        "country": "Belgium",
        "location": "ALL",
        "worker_type": "Employee",
        "compensation_grade": "Salary",
        "contract_type": "Part_time",
        "employee_type": [
            "Regular",
            "Fixed Term",
            "Partner",
            "Intern",
            "Non-Salaried / Self-Employed",
            "Non-Salaried / Self-Employed (Fixed Term)"
        ],
        "job_category": [
            "Functional",
            "Client Services"
        ],
        "management_level": [
            "Partner",
            "Executive Vice President",
            "Senior Vice President",
            "Vice President",
            "Director",
            "Senior Manager",
            "Manager",
            "Senior Associate",
            "Specialist 1",
            "Specialist 2",
            "Associate",
            "Trainee/Apprentice",
            "Administrative 1",
            "Administrative 2"
        ],
        "additional_job_classification": "BEL_OT_Policy_B",
        "company_code": "NA",
        "schedule_type": "Office Schedule (Assigned to user via another automation)",
        "work_week": "Sunday to Saturday",
        "timesheet_template": "Belgium TSD Agile Emp OT",
        "time_entry_approval_path": "Automatic Approval",
        "timesheet_approval": "Supervisor",
        "timesheet_period": "Weekly without crossing months",
        "time_off_template": "Time Off",
        "time_off_approval": "System",
        "time_off_types": [
            "BEL_TOIL",
            "Holiday",
            "Leave of Absence"
        ],
        "payrule": "Belgium PT SAL Policy B",
        "time_zone": "(UTC+1:00) Central Europe Standard Time",
        "holiday_calendar": "Belgium Holiday Calendar",
        "authentication_type": "SSO"
    },
    {
        "country": "Belgium",
        "location": "ALL",
        "worker_type": "Employee",
        "compensation_grade": "Salary",
        "contract_type": [
            "Full_time",
            "Part_time"
        ],
        "employee_type": [
            "Regular",
            "Fixed Term",
            "Partner",
            "Intern",
            "Non-Salaried / Self-Employed",
            "Non-Salaried / Self-Employed (Fixed Term)"
        ],
        "job_category": [
            "Functional",
            "Client Services"
        ],
        "management_level": [
            "Partner",
            "Executive Vice President",
            "Senior Vice President",
            "Vice President",
            "Director",
            "Senior Manager",
            "Manager",
            "Senior Associate",
            "Specialist 1",
            "Specialist 2",
            "Associate",
            "Trainee/Apprentice",
            "Administrative 1",
            "Administrative 2"
        ],
        "additional_job_classification": "NA",
        "company_code": "NA",
        "schedule_type": "Office Schedule (Assigned to user via another automation)",
        "work_week": "Sunday to Saturday",
        "timesheet_template": "Belgium TSD Agile Emp OT",
        "time_entry_approval_path": "Automatic Approval",
        "timesheet_approval": "Supervisor",
        "timesheet_period": "Weekly without crossing months",
        "time_off_template": "Time Off",
        "time_off_approval": "System",
        "time_off_types": [
            "BEL_TOIL",
            "Holiday",
            "Leave of Absence"
        ],
        "payrule": "Belgium SAL NO AJC",
        "time_zone": "(UTC+1:00) Central Europe Standard Time",
        "holiday_calendar": "Belgium Holiday Calendar",
        "authentication_type": "SSO"
    },
    {
        "country": "Belgium",
        "location": "ALL",
        "worker_type": "Employee",
        "compensation_grade": "Hourly",
        "contract_type": [
            "Full_time",
            "Part_time"
        ],
        "employee_type": [
            "Regular",
            "Fixed Term",
            "Partner",
            "Intern",
            "Non-Salaried / Self-Employed",
            "Non-Salaried / Self-Employed (Fixed Term)"
        ],
        "job_category": [
            "Functional",
            "Client Services"
        ],
        "management_level": [
            "Partner",
            "Executive Vice President",
            "Senior Vice President",
            "Vice President",
            "Director",
            "Senior Manager",
            "Manager",
            "Senior Associate",
            "Specialist 1",
            "Specialist 2",
            "Associate",
            "Trainee/Apprentice",
            "Administrative 1",
            "Administrative 2"
        ],
        "additional_job_classification": "NA",
        "company_code": "NA",
        "schedule_type": "Office Schedule (Assigned to user via another automation)",
        "work_week": "Sunday to Saturday",
        "timesheet_template": "Belgium TSD Agile Emp OT",
        "time_entry_approval_path": "Automatic Approval",
        "timesheet_approval": "Supervisor",
        "timesheet_period": "Weekly without crossing months",
        "time_off_template": "Time Off",
        "time_off_approval": "Hourly TO Approval Path",
        "time_off_types": [
            "Holiday",
            "Leave of Absence"
        ],
        "payrule": "Belgium Hourly OT",
        "time_zone": "(UTC+1:00) Central Europe Standard Time",
        "holiday_calendar": "Belgium Holiday Calendar",
        "authentication_type": "SSO"
    },
    {
        "country": "Belgium",
        "location": "ALL",
        "worker_type": "Contingent Worker",
        "compensation_grade": "NA",
        "contract_type": [
            "Full_time",
            "Part_time"
        ],
        "employee_type": [
            "Agency Contractor",
            "Alliance/Perimeter Worker",
            "Direct Contractor",
            "Vendor",
            "Intern"
        ],
        "job_category": "Indirect_Labor",
        "management_level": [
            "Partner",
            "Executive Vice President",
            "Senior Vice President",
            "Vice President",
            "Director",
            "Senior Manager",
            "Manager",
            "Senior Associate",
            "Specialist 1",
            "Specialist 2",
            "Associate",
            "Trainee/Apprentice",
            "Administrative 1",
            "Administrative 2"
        ],
        "additional_job_classification": "NA",
        "company_code": "NA",
        "schedule_type": "Office Schedule (Assigned to user via another automation)",
        "work_week": "Sunday to Saturday",
        "timesheet_template": "Vialto TSD Agile Contingent",
        "time_entry_approval_path": "Automatic Approval",
        "timesheet_approval": "Hourly/Cont TS Approval Path",
        "timesheet_period": "Weekly without crossing months",
        "time_off_template": "NA",
        "time_off_approval": "NA",
        "time_off_types": "NA",
        "payrule": "Vialto Dummy Pay Rule",
        "time_zone": "(UTC-3:00) Argentina Standard Time",
        "holiday_calendar": "NA",
        "authentication_type": "SSO"
    }
]
