region = 'eu-central-1'
environment = 'production'
instance = "GEHealthcare"
company_key = 'GEHealthcare'
replicon_conn_id = 'gehealthcare_replicon_admin'
pgp_conn_id = 'gehealthcare_pgp_replicon'
can_run_batch_task_var_name = f'GEHealthcare_user_import_can_run_batch_task_{instance}'
sftp_conn_id = "gehealthcare_sftp_NP700000577"
internal_sftp_conn_id = "gehealthcare_sftp_587719"
input_filepath = "/EUROPE/NETHERLANDS/WORKDAY/PROD/FROMGE"
archive_filepath = "/EUROPE/NETHERLANDS/WORKDAY/PROD/FROMGE/ARCHIVE"
internal_archive_filepath = "/User Sync/Netherlands/Daily Files/"
log_filepath = "/User Sync/Netherlands/Logs/"
execution_timeout_days = 14
child_dag_max_active_runs = 5
master_dag_interval = 30
tenant_email = "healthcare.l3.support@gehealthcare.com"
internal_logs_email = '{{ var.value.dagrun_internal_log_email }}'
alert_email = '{{ var.value.dagrun_failure_alert_email }}'
pacific_timezone = 'US/Pacific'
