"""
iPipeline User Import - Time Off Type Mapper (Updated)

Complete time off policies matrix from NEW Excel file.
All 42 policies with accrual conditions, location/level filtering, approval paths, and NEW fields.

CHANGES FROM OLD MAPPER:
========================
1. NEW KEYS ADDED:
   - uksick_category_to_include/exclude: Filter for UK Sick leave category
   - reference_logic_type: Type classification (Type1-A1, Type1-A2, Type1-B, Type2-A, Type2-B, Type3, Type4, Type5) {Type5 will not be asigned by Integration}
   - accrual_rate_daily: Daily accrual rate formula for new hires/terminations
   - max_calendar_year_accrual_limit: Maximum hours/days bookable in calendar year
   - time_off_selection: "Full Day", "Partial Day", or "Full Day, Partial Day"

2. REMOVED FROM NEW MAPPER (was in old):
   - Global_Early Office Closing

3. NEW ROWS (8 new, total 42):
   - USA_Vacation split into 2 rows (by employee level)
   - UK_Holiday split into 3 rows (25, 27, 28 days)
   - UK_Illness/Sick split into 3 rows (A, B, C)
   - Holiday, Z_UK_ Keep in Touch Day, Holiday Carry Over, Holidays Bought
   
CONTRACTOR EXCLUSION:
====================
- ALL time off types exclude "Contractor" via location_level_1_to_exclude
- Contractors receive NO time off types (as per client requirements)
"""

TIME_OFF_TYPE_MAPPER = [
    # 1 & 2 COMBINED TOGETHER via CRv14: USA Vacation - All Levels
    {
        "location_level_1": "United States",
        "location_level_1_to_exclude": ["Contractor"],
        "location_level_2_to_include": [],
        "location_level_2_to_exclude": ["Remote - CA"],
        "employee_levels_to_include": [],
        "employee_levels_to_exclude": [],
        "uksick_category_to_include": [],
        "uksick_category_to_exclude": [],
        "time_off_type": "USA _Vacation",
        "time_off_type_group": "Vacation/Holiday",
        "time_off_type_approval_path": "iPipeline US",
        "paycode": "VACPY",
        "note_to_be_displayed": "",
        "reference_logic_type": "Type1-A1",
        "visible_to_employees": True,
        "accrual_policy": "Prorated for anyone with scheduled hours less than FT hours. Needs to change if someones scheduled hours are updated in HRIS. Calculation to reduce based on full time should be Scheduled hours / FTE* Accrual Rate",
        "accrual_rate_daily": "Equal to: Accrual Rate (Days Monthly) /# working days in calendar year* Number of days active in calendar month",
        "max_calendar_year_accrual_limit": "Should not allow more time than will accrue for the calendar year. In no circumstance should someone be able to book more than 160",
        "carry_forward": "",
        "carry_forward_expiry": "",
        "time_off_reset": "1-Jan",
        "over_draw": "",
        "validation": "",
        "leave_type": "Hours",
    },

    # 3: USA California Vacation
    {
        "location_level_1": "United States",
        "location_level_1_to_exclude": ["Contractor"],
        "location_level_2_to_include": ["Remote - CA"],
        "location_level_2_to_exclude": [],
        "employee_levels_to_include": [],
        "employee_levels_to_exclude": [],
        "uksick_category_to_include": [],
        "uksick_category_to_exclude": [],
        "time_off_type": "USA_California _Vacation",
        "time_off_type_group": "Vacation/Holiday",
        "time_off_type_approval_path": "iPipeline US",
        "paycode": "VACPY",
        "note_to_be_displayed": "",
        "reference_logic_type": "Type4",
        "visible_to_employees": True,
        "accrual_policy": "Unlimited time off- does not accrue - should not deduct",
        "accrual_rate_daily": "Unlimited time off- does not accrue - should not deduct",
        "max_calendar_year_accrual_limit": "Unlimited time off- does not accrue - should not deduct",
        "carry_forward": "",
        "carry_forward_expiry": "",
        "time_off_reset": "",
        "over_draw": "",
        "validation": "",
        "leave_type": "Hours",
    },

    # 4: UK Holiday - 25 days
    {
        "location_level_1": "United Kingdom",
        "location_level_1_to_exclude": ["Contractor"],
        "location_level_2_to_include": [],
        "location_level_2_to_exclude": [],
        "employee_levels_to_include": [],
        "employee_levels_to_exclude": [],
        "uksick_category_to_include": [],
        "uksick_category_to_exclude": ["A-28", "A-27", "B-28"],
        "time_off_type": "UK _Holiday-25 days",
        "time_off_type_group": "Vacation/Holiday",
        "time_off_type_approval_path": "iPipeline UK",
        "paycode": "UKVAC",
        "note_to_be_displayed": "",
        "reference_logic_type": "Type1-B",
        "visible_to_employees": True,
        "accrual_policy": "Prorated for anyone with scheduled hours less than FT hours. Needs to change if someones scheduled hours are updated in HRIS. Calculation to reduce based on full time should be Scheduled hours / FTE* Accrual Rate",
        "accrual_rate_daily": "Equal to: Accrual Rate (Days Monthly) /# working days in calendar year* Number of days active in calendar month",
        "max_calendar_year_accrual_limit": "Should not allow more time than will accrue for the calendar year. In no circumstance should someone be able to book more than 187.50 hours",
        "carry_forward": "3",
        "carry_forward_expiry": "1-Apr",
        "time_off_reset": "1-Jan",
        "over_draw": "",
        "validation": "",
        "leave_type": "Hours",
    },

    # 5: UK Holiday - 27 days
    {
        "location_level_1": "United Kingdom",
        "location_level_1_to_exclude": ["Contractor"],
        "location_level_2_to_include": [],
        "location_level_2_to_exclude": [],
        "employee_levels_to_include": [],
        "employee_levels_to_exclude": [],
        "uksick_category_to_include": ["A-27"],
        "uksick_category_to_exclude": [],
        "time_off_type": "UK _Holiday-27 days",
        "time_off_type_group": "Vacation/Holiday",
        "time_off_type_approval_path": "iPipeline UK",
        "paycode": "UKVAC",
        "note_to_be_displayed": "",
        "reference_logic_type": "Type1-B",
        "visible_to_employees": True,
        "accrual_policy": "Prorated for anyone with scheduled hours less than FT hours. Needs to change if someones scheduled hours are updated in HRIS. Calculation to reduce based on full time should be Scheduled hours / FTE* Accrual Rate",
        "accrual_rate_daily": "Equal to: Accrual Rate (Days Monthly) /# working days in calendar year* Number of days active in calendar month",
        "max_calendar_year_accrual_limit": "Should not allow more time than will accrue for the calendar year. In no circumstance should someone be able to book more than 216 hours",
        "carry_forward": "3",
        "carry_forward_expiry": "1-Apr",
        "time_off_reset": "1-Jan",
        "over_draw": "",
        "validation": "",
        "leave_type": "Hours",
    },

    # 6: UK Holiday - 28 days
    {
        "location_level_1": "United Kingdom",
        "location_level_1_to_exclude": ["Contractor"],
        "location_level_2_to_include": [],
        "location_level_2_to_exclude": [],
        "employee_levels_to_include": [],
        "employee_levels_to_exclude": [],
        "uksick_category_to_include": ["A-28", "B-28"],
        "uksick_category_to_exclude": [],
        "time_off_type": "UK _Holiday-28 days",
        "time_off_type_group": "Vacation/Holiday",
        "time_off_type_approval_path": "iPipeline UK",
        "paycode": "UKVAC",
        "note_to_be_displayed": "",
        "reference_logic_type": "Type1-B",
        "visible_to_employees": True,
        "accrual_policy": "Prorated for anyone with scheduled hours less than FT hours. Needs to change if someones scheduled hours are updated in HRIS. Calculation to reduce based on full time should be Scheduled hours / FTE* Accrual Rate",
        "accrual_rate_daily": "Equal to: Accrual Rate (Days Monthly) /# working days in calendar year* Number of days active in calendar month",
        "max_calendar_year_accrual_limit": "Should not allow more time than will accrue for the calendar year. In no circumstance should someone be able to book more than 224 hours",
        "carry_forward": "3",
        "carry_forward_expiry": "1-Apr",
        "time_off_reset": "1-Jan",
        "over_draw": "",
        "validation": "",
        "leave_type": "Hours",
    },

    # 7: Canada Vacation
    {
        "location_level_1": "Canada",
        "location_level_1_to_exclude": ["Contractor"],
        "location_level_2_to_include": [],
        "location_level_2_to_exclude": [],
        "employee_levels_to_include": [],
        "employee_levels_to_exclude": [],
        "uksick_category_to_include": [],
        "uksick_category_to_exclude": [],
        "time_off_type": "Canada_Vacation",
        "time_off_type_group": "Vacation/Holiday",
        "time_off_type_approval_path": "iPipeline Canada",
        "paycode": "CAVAC",
        "note_to_be_displayed": "",
        "reference_logic_type": "Type1-A1",
        "visible_to_employees": True,
        "accrual_policy": "Prorated for anyone with scheduled hours less than FT hours. Needs to change if someones scheduled hours are updated in HRIS. Calculation to reduce based on full time should be Scheduled hours / FTE* Accrual Rate",
        "accrual_rate_daily": "Equal to: Accrual Rate (Days Monthly) /# working days in calendar year* Number of days active in calendar month",
        "max_calendar_year_accrual_limit": "<=2 years - 120, =3 years - 136, =4 years - 144, =5 years - 152, =6 years - 160, =7 years - 168, =8 years - 176, =9 years - 184, =10 years - 192, >=11 years - 200",
        "carry_forward": "",
        "carry_forward_expiry": "",
        "time_off_reset": "1-Jan",
        "over_draw": "",
        "validation": "",
        "leave_type": "Hours",
    },

    # 8: Japan Vacation
    {
        "location_level_1": "Japan",
        "location_level_1_to_exclude": ["Contractor"],
        "location_level_2_to_include": [],
        "location_level_2_to_exclude": [],
        "employee_levels_to_include": [],
        "employee_levels_to_exclude": [],
        "uksick_category_to_include": [],
        "uksick_category_to_exclude": [],
        "time_off_type": "Japan_Vacation",
        "time_off_type_group": "Vacation/Holiday",
        "time_off_type_approval_path": "iPipeline Japan",
        "paycode": "JPVAC",
        "note_to_be_displayed": "",
        "reference_logic_type": "Type1-A2",
        "visible_to_employees": True,
        "accrual_policy": "Prorated for anyone with scheduled hours less than FT hours. Needs to change if someones scheduled hours are updated in HRIS. Calculation to reduce based on full time should be Scheduled hours / FTE* Accrual Rate",
        "accrual_rate_daily": "Equal to: Accrual Rate (Days Monthly) /# working days in calendar year* Number of days active in calendar month",
        "max_calendar_year_accrual_limit": "160",
        "carry_forward": "",
        "carry_forward_expiry": "",
        "time_off_reset": "1-Jan",
        "over_draw": "",
        "validation": "",
        "leave_type": "Hours",
    },

    # 9: USA Illness/Sick
    {
        "location_level_1": "United States",
        "location_level_1_to_exclude": ["Contractor"],
        "location_level_2_to_include": [],
        "location_level_2_to_exclude": [],
        "employee_levels_to_include": [],
        "employee_levels_to_exclude": [],
        "uksick_category_to_include": [],
        "uksick_category_to_exclude": [],
        "time_off_type": "USA_Illness/Sick",
        "time_off_type_group": "Illness/Sick",
        "time_off_type_approval_path": "iPipeline US",
        "paycode": "SICK",
        "note_to_be_displayed": "",
        "reference_logic_type": "Type2-A",
        "visible_to_employees": True,
        "accrual_policy": "Prorated for anyone with scheduled hours less than FT hours. Needs to change if someones scheduled hours are updated in HRIS. Calculation to reduce based on full time should be Scheduled hours / FTE* Accrual Rate",
        "accrual_rate_daily": "Equal to: Accrual Rate (Days Monthly) /# working days in calendar year* Number of days active in calendar month",
        "max_calendar_year_accrual_limit": "Someone should not be able to book more time than they will be granted in the calendar year. <1 years - 40, >1 years - 48",
        "carry_forward": "",
        "carry_forward_expiry": "",
        "time_off_reset": "1-Jan",
        "over_draw": "",
        "validation": "",
        "leave_type": "Hours",
    },

    # 10: UK Illness/Sick - Category C
    {
        "location_level_1": "United Kingdom",
        "location_level_1_to_exclude": ["Contractor"],
        "location_level_2_to_include": [],
        "location_level_2_to_exclude": [],
        "employee_levels_to_include": [],
        "employee_levels_to_exclude": [],
        "uksick_category_to_include": ["C"],
        "uksick_category_to_exclude": [],
        "time_off_type": "UK_Illness/Sick-C",
        "time_off_type_group": "Illness/Sick",
        "time_off_type_approval_path": "iPipeline UK",
        "paycode": "UKSICK",
        "note_to_be_displayed": "",
        "reference_logic_type": "Type3",
        "visible_to_employees": True,
        "accrual_policy": "Prorated for anyone with scheduled hours less than FT hours. Needs to change if someones scheduled hours are updated in HRIS. Calculation to reduce based on full time should be Scheduled hours / FTE* Accrual Rate",
        "accrual_rate_daily": "Equal to: Accrual Rate (Days Monthly) /# working days in calendar year* Number of days active in calendar month",
        "max_calendar_year_accrual_limit": "Someone should not be able to book more time than they will be granted in the calendar year. <=1 years - 45 (6 days), =2 years - 90 (12 Days), >=3 years - 150 (20 days)",
        "carry_forward": "",
        "carry_forward_expiry": "",
        "time_off_reset": "1-Jan",
        "over_draw": "",
        "validation": "Probation 119 days",
        "leave_type": "Hours",
    },

    # 11: UK Illness/Sick - Category A
    {
        "location_level_1": "United Kingdom",
        "location_level_1_to_exclude": ["Contractor"],
        "location_level_2_to_include": [],
        "location_level_2_to_exclude": [],
        "employee_levels_to_include": [],
        "employee_levels_to_exclude": [],
        "uksick_category_to_include": ["A-27", "A-28", "A"],
        "uksick_category_to_exclude": [],
        "time_off_type": "UK_Illness/Sick-A",
        "time_off_type_group": "Illness/Sick",
        "time_off_type_approval_path": "iPipeline UK",
        "paycode": "UKSICK",
        "note_to_be_displayed": "",
        "reference_logic_type": "Type2-A",
        "visible_to_employees": True,
        "accrual_policy": "Prorated for anyone with scheduled hours less than FT hours. Needs to change if someones scheduled hours are updated in HRIS. Calculation to reduce based on full time should be Scheduled hours / FTE* Accrual Rate",
        "accrual_rate_daily": "Equal to: Accrual Rate (Days Monthly) /# working days in calendar year* Number of days active in calendar month",
        "max_calendar_year_accrual_limit": "Someone should not be able to book more time than they will be granted in the calendar year. >20 Years 130 days",
        "carry_forward": "",
        "carry_forward_expiry": "",
        "time_off_reset": "1-Jan",
        "over_draw": "",
        "validation": "Probation 119 days",
        "leave_type": "Hours",
    },

    # 12: UK Illness/Sick - Category B
    {
        "location_level_1": "United Kingdom",
        "location_level_1_to_exclude": ["Contractor"],
        "location_level_2_to_include": [],
        "location_level_2_to_exclude": [],
        "employee_levels_to_include": [],
        "employee_levels_to_exclude": [],
        "uksick_category_to_include": ["B-28", "B"],
        "uksick_category_to_exclude": [],
        "time_off_type": "UK_Illness/Sick-B",
        "time_off_type_group": "Illness/Sick",
        "time_off_type_approval_path": "iPipeline UK",
        "paycode": "UKSICK",
        "note_to_be_displayed": "",
        "reference_logic_type": "Type2-A",
        "visible_to_employees": True,
        "accrual_policy": "Prorated for anyone with scheduled hours less than FT hours. Needs to change if someones scheduled hours are updated in HRIS. Calculation to reduce based on full time should be Scheduled hours / FTE* Accrual Rate",
        "accrual_rate_daily": "Equal to: Accrual Rate (Days Monthly) /# working days in calendar year* Number of days active in calendar month",
        "max_calendar_year_accrual_limit": "Someone should not be able to book more time than they will be granted in the calendar year. 60 days",
        "carry_forward": "",
        "carry_forward_expiry": "",
        "time_off_reset": "1-Jan",
        "over_draw": "",
        "validation": "Probation 119 days",
        "leave_type": "Hours",
    },

    # 13: Global Volunteer
    {
        "location_level_1": "ALL",
        "location_level_1_to_exclude": ["Contractor"],
        "location_level_2_to_include": [],
        "location_level_2_to_exclude": [],
        "employee_levels_to_include": [],
        "employee_levels_to_exclude": [],
        "uksick_category_to_include": [],
        "uksick_category_to_exclude": [],
        "time_off_type": "Z_Global_Volunteer",
        "time_off_type_group": "Volunteer",
        "time_off_type_approval_path": "TS_SUPERVISOR_APPROVAL",
        "paycode": "VOLUN",
        "note_to_be_displayed": "",
        "reference_logic_type": "Type4",
        "visible_to_employees": True,
        "accrual_policy": "1 day equal to scheduled hours at the point in time of usage",
        "accrual_rate_daily": "DOES NOT ACCRUE",
        "max_calendar_year_accrual_limit": "1 day equal to scheduled hours at the point in time of usage",
        "carry_forward": "",
        "carry_forward_expiry": "",
        "time_off_reset": "1-Jan",
        "over_draw": "",
        "validation": "",
        "leave_type": "Day",
    },

    # 14: USA Personal
    {
        "location_level_1": "United States",
        "location_level_1_to_exclude": ["Contractor"],
        "location_level_2_to_include": [],
        "location_level_2_to_exclude": ["Remote - CA"],
        "employee_levels_to_include": [],
        "employee_levels_to_exclude": [],
        "uksick_category_to_include": [],
        "uksick_category_to_exclude": [],
        "time_off_type": "USA_Personal",
        "time_off_type_group": "Personal",
        "time_off_type_approval_path": "iPipeline US",
        "paycode": "PERSN",
        "note_to_be_displayed": "",
        "reference_logic_type": "Type2-A",
        "visible_to_employees": True,
        "accrual_policy": "2 days equal to scheduled hours at the point in time of usage",
        "accrual_rate_daily": "Does not accrue but needs to prorate for new hires only (Scheduled hours / FTE HOURS) * 2 / (# working days in calendar year * Number of days active in calendar year)",
        "max_calendar_year_accrual_limit": "Should be able to book up to 2 days equal to scheduled hours at the point in time of usage",
        "carry_forward": "",
        "carry_forward_expiry": "",
        "time_off_reset": "",
        "over_draw": "",
        "validation": "",
        "leave_type": "Hours",
    },

    # 15: Canada Personal
    {
        "location_level_1": "Canada",
        "location_level_1_to_exclude": ["Contractor"],
        "location_level_2_to_include": [],
        "location_level_2_to_exclude": [],
        "employee_levels_to_include": [],
        "employee_levels_to_exclude": [],
        "uksick_category_to_include": [],
        "uksick_category_to_exclude": [],
        "time_off_type": "Canada_Personal",
        "time_off_type_group": "Personal",
        "time_off_type_approval_path": "iPipeline Canada",
        "paycode": "CADPERSN",
        "note_to_be_displayed": "",
        "reference_logic_type": "Type2-A",
        "visible_to_employees": True,
        "accrual_policy": "10 days equal to scheduled hours at the point in time of usage",
        "accrual_rate_daily": "Does not accrue but needs to prorate for new hires only (Scheduled hours / FTE HOURS) * 10 / (# working days in calendar year * Number of days active in calendar year)",
        "max_calendar_year_accrual_limit": "Should be able to book up to 10 days equal to scheduled hours at the point in time of usage",
        "carry_forward": "",
        "carry_forward_expiry": "",
        "time_off_reset": "",
        "over_draw": "",
        "validation": "",
        "leave_type": "Hours",
    },

    # 16: Canada Bereavement
    {
        "location_level_1": "Canada",
        "location_level_1_to_exclude": ["Contractor"],
        "location_level_2_to_include": [],
        "location_level_2_to_exclude": [],
        "employee_levels_to_include": [],
        "employee_levels_to_exclude": [],
        "uksick_category_to_include": [],
        "uksick_category_to_exclude": [],
        "time_off_type": "Z_Canada_Bereavement",
        "time_off_type_group": "Berevement",
        "time_off_type_approval_path": "iPipeline Canada",
        "paycode": "CABER",
        "note_to_be_displayed": "",
        "reference_logic_type": "Type2-B",
        "visible_to_employees": True,
        "accrual_policy": "3 days equal to scheduled hours at the point in time of usage",
        "accrual_rate_daily": "Does not accrue but needs to prorate for new hires only (Scheduled hours / FTE HOURS) * 3 / (# working days in calendar year * Number of days active in calendar year)",
        "max_calendar_year_accrual_limit": "",
        "carry_forward": "No Carry over",
        "carry_forward_expiry": "",
        "time_off_reset": "",
        "over_draw": "",
        "validation": "",
        "leave_type": "Hours",
    },

    # 17: Global Jury Duty
    {
        "location_level_1": "ALL",
        "location_level_1_to_exclude": ["Contractor"],
        "location_level_2_to_include": [],
        "location_level_2_to_exclude": [],
        "employee_levels_to_include": [],
        "employee_levels_to_exclude": [],
        "uksick_category_to_include": [],
        "uksick_category_to_exclude": [],
        "time_off_type": "Z_Global_Jury Duty",
        "time_off_type_group": "Jury Duty",
        "time_off_type_approval_path": "TS_SUPERVISOR_APPROVAL",
        "paycode": "JURY",
        "note_to_be_displayed": "",
        "reference_logic_type": "Type4",
        "visible_to_employees": True,
        "accrual_policy": "Unlimited time off- does not accrue - should not deduct",
        "accrual_rate_daily": "Unlimited time off- does not accrue - should not deduct",
        "max_calendar_year_accrual_limit": "Unlimited time off- does not accrue - should not deduct",
        "carry_forward": "",
        "carry_forward_expiry": "",
        "time_off_reset": "",
        "over_draw": "",
        "validation": "",
        "leave_type": "Hours",
    },

    # 18: Japan Bereavement
    {
        "location_level_1": "Japan",
        "location_level_1_to_exclude": ["Contractor"],
        "location_level_2_to_include": [],
        "location_level_2_to_exclude": [],
        "employee_levels_to_include": [],
        "employee_levels_to_exclude": [],
        "uksick_category_to_include": [],
        "uksick_category_to_exclude": [],
        "time_off_type": "Z_Japan_Bereavement",
        "time_off_type_group": "Berevement",
        "time_off_type_approval_path": "iPipeline Japan",
        "paycode": "JPBER",
        "note_to_be_displayed": "",
        "reference_logic_type": "Type2-B",
        "visible_to_employees": True,
        "accrual_policy": "3 days equal to scheduled hours at the point in time of usage",
        "accrual_rate_daily": "Does not accrue but needs to prorate for new hires only (Scheduled hours / FTE HOURS) * 3 / (# working days in calendar year * Number of days active in calendar year)",
        "max_calendar_year_accrual_limit": "SHOULD NOT SHOW AVAILABLE BALANCE",
        "carry_forward": "No Carry over",
        "carry_forward_expiry": "",
        "time_off_reset": "",
        "over_draw": "",
        "validation": "",
        "leave_type": "Hours",
    },

    # 19: USA Bereavement
    {
        "location_level_1": "United States",
        "location_level_1_to_exclude": ["Contractor"],
        "location_level_2_to_include": [],
        "location_level_2_to_exclude": [],
        "employee_levels_to_include": [],
        "employee_levels_to_exclude": [],
        "uksick_category_to_include": [],
        "uksick_category_to_exclude": [],
        "time_off_type": "Z_USA_Bereavement",
        "time_off_type_group": "Berevement",
        "time_off_type_approval_path": "iPipeline US",
        "paycode": "BEREA",
        "note_to_be_displayed": "",
        "reference_logic_type": "Type2-B",
        "visible_to_employees": True,
        "accrual_policy": "3 days equal to scheduled hours at the point in time of usage",
        "accrual_rate_daily": "Does not accrue but needs to prorate for new hires only (Scheduled hours / FTE HOURS) * 3 / (# working days in calendar year * Number of days active in calendar year)",
        "max_calendar_year_accrual_limit": "SHOULD NOT SHOW AVAILABLE BALANCE",
        "carry_forward": "No Carry over",
        "carry_forward_expiry": "",
        "time_off_reset": "",
        "over_draw": "",
        "validation": "",
        "leave_type": "Hours",
    },

    # 20: UK Bank Holidays Owed
    {
        "location_level_1": "United Kingdom",
        "location_level_1_to_exclude": ["Contractor"],
        "location_level_2_to_include": [],
        "location_level_2_to_exclude": [],
        "employee_levels_to_include": [],
        "employee_levels_to_exclude": [],
        "uksick_category_to_include": [],
        "uksick_category_to_exclude": [],
        "time_off_type": "Z_UK_Bank Holidays Owed",
        "time_off_type_group": "Bank Holidays Owed",
        "time_off_type_approval_path": "iPipeline UK",
        "paycode": "UKHOL",
        "note_to_be_displayed": "",
        "reference_logic_type": "Type4",
        "visible_to_employees": False,
        "accrual_policy": "Unlimited time off- does not accrue - should not deduct",
        "accrual_rate_daily": "Unlimited time off- does not accrue - should not deduct",
        "max_calendar_year_accrual_limit": "Unlimited time off- does not accrue - should not deduct",
        "carry_forward": "",
        "carry_forward_expiry": "",
        "time_off_reset": "",
        "over_draw": "",
        "validation": "",
        "leave_type": "Hours",
    },

    # 21: UK Compassionate leave
    {
        "location_level_1": "United Kingdom",
        "location_level_1_to_exclude": ["Contractor"],
        "location_level_2_to_include": [],
        "location_level_2_to_exclude": [],
        "employee_levels_to_include": [],
        "employee_levels_to_exclude": [],
        "uksick_category_to_include": [],
        "uksick_category_to_exclude": [],
        "time_off_type": "Z_UK_Compassionate leave",
        "time_off_type_group": "Compassionate leave",
        "time_off_type_approval_path": "iPipeline UK",
        "paycode": "UKCOMP",
        "note_to_be_displayed": "",
        "reference_logic_type": "Type2-B",
        "visible_to_employees": True,
        "accrual_policy": "5 days based on scheduled hours at the point in time of usage",
        "accrual_rate_daily": "Does not accrue but needs to prorate for new hires only (Scheduled hours / FTE HOURS) * 5 / (# working days in calendar year * Number of days active in calendar year)",
        "max_calendar_year_accrual_limit": "SHOULD NOT SHOW AVAILABLE BALANCE",
        "carry_forward": "No Carry over",
        "carry_forward_expiry": "",
        "time_off_reset": "",
        "over_draw": "",
        "validation": "",
        "leave_type": "Hours",
    },

    # 22: Canada Summer Hours
    #Type5 timeoff type need not be assigned by Intgration

    # 23: UK Flexible Time Off
    {
        "location_level_1": "United Kingdom",
        "location_level_1_to_exclude": ["Contractor"],
        "location_level_2_to_include": [],
        "location_level_2_to_exclude": [],
        "employee_levels_to_include": [],
        "employee_levels_to_exclude": [],
        "uksick_category_to_include": [],
        "uksick_category_to_exclude": [],
        "time_off_type": "Z_UK_Flexible Time Off",
        "time_off_type_group": "Flexible Time Off",
        "time_off_type_approval_path": "iPipeline UK",
        "paycode": "UKFLEX",
        "note_to_be_displayed": "",
        "reference_logic_type": "Type4",
        "visible_to_employees": True,
        "accrual_policy": "",
        "accrual_rate_daily": "SHOULD NOT REDUCE TIME CARD",
        "max_calendar_year_accrual_limit": "SHOULD NOT SHOW AVAILABLE BALANCE",
        "carry_forward": "",
        "carry_forward_expiry": "",
        "time_off_reset": "",
        "over_draw": "",
        "validation": "",
        "leave_type": "Hours",
    },

    # 24: UK Time off for Dependants
    {
        "location_level_1": "United Kingdom",
        "location_level_1_to_exclude": ["Contractor"],
        "location_level_2_to_include": [],
        "location_level_2_to_exclude": [],
        "employee_levels_to_include": [],
        "employee_levels_to_exclude": [],
        "uksick_category_to_include": [],
        "uksick_category_to_exclude": [],
        "time_off_type": "Z_UK_Time off for Dependants",
        "time_off_type_group": "Time off for Dependants",
        "time_off_type_approval_path": "iPipeline UK",
        "paycode": "UKDEP",
        "note_to_be_displayed": "",
        "reference_logic_type": "Type2-B",
        "visible_to_employees": True,
        "accrual_policy": "3 days based on scheduled hours at point in time of usage",
        "accrual_rate_daily": "Does not accrue but needs to prorate for new hires only (Scheduled hours / FTE HOURS) * 3 / (# working days in calendar year * Number of days active in calendar year)",
        "max_calendar_year_accrual_limit": "3 days based on scheduled hours",
        "carry_forward": "No Carry over",
        "carry_forward_expiry": "",
        "time_off_reset": "",
        "over_draw": "",
        "validation": "",
        "leave_type": "Hours",
    },

    # 25: USA Unpaid Hourly
    {
        "location_level_1": "United States",
        "location_level_1_to_exclude": ["Contractor"],
        "location_level_2_to_include": [],
        "location_level_2_to_exclude": [],
        "employee_levels_to_include": [],
        "employee_levels_to_exclude": [],
        "uksick_category_to_include": [],
        "uksick_category_to_exclude": [],
        "time_off_type": "Z_USA_Unpaid_Hourly",
        "time_off_type_group": "Unpaid",
        "time_off_type_approval_path": "TS_SUPERVISOR_APPROVAL",
        "paycode": "UNPTO-H",
        "note_to_be_displayed": "",
        "reference_logic_type": "Type4",
        "visible_to_employees": True,
        "accrual_policy": "Unlimited time off- does not accrue - should not deduct",
        "accrual_rate_daily": "Unlimited time off- does not accrue - should not deduct",
        "max_calendar_year_accrual_limit": "Unlimited time off- does not accrue - should not deduct",
        "carry_forward": "",
        "carry_forward_expiry": "",
        "time_off_reset": "",
        "over_draw": "",
        "validation": "",
        "leave_type": "Hours",
    },

    # 26: Z_USA_Unpaid Leave
    {
        "location_level_1": "United States",
        "location_level_1_to_exclude": ["Contractor"],
        "location_level_2_to_include": [],
        "location_level_2_to_exclude": [],
        "employee_levels_to_include": [],
        "employee_levels_to_exclude": [],
        "uksick_category_to_include": [],
        "uksick_category_to_exclude": [],
        "time_off_type": "Z_USA_Unpaid Leave",
        "time_off_type_group": "Unpaid",
        "time_off_type_approval_path": "iPipeline US - approved by leave Manager",
        "paycode": "UNPTO",
        "note_to_be_displayed": "All leave requests must receive prior approval from Human Resources",
        "reference_logic_type": "Type4",
        "visible_to_employees": True,
        "accrual_policy": "Unlimited time off- does not accrue - should not deduct",
        "accrual_rate_daily": "Unlimited time off- does not accrue - should not deduct",
        "max_calendar_year_accrual_limit": "Unlimited time off- does not accrue - should not deduct",
        "carry_forward": "",
        "carry_forward_expiry": "",
        "time_off_reset": "",
        "over_draw": "",
        "validation": "",
        "leave_type": "Hours",
    },

    # 27: Z_USA_Short Term Disability
    {
        "location_level_1": "United States",
        "location_level_1_to_exclude": ["Contractor"],
        "location_level_2_to_include": [],
        "location_level_2_to_exclude": [],
        "employee_levels_to_include": [],
        "employee_levels_to_exclude": [],
        "uksick_category_to_include": [],
        "uksick_category_to_exclude": [],
        "time_off_type": "Z_USA_Short Term Disability",
        "time_off_type_group": "Short Term Disability",
        "time_off_type_approval_path": "iPipeline US - approved by leave Manager",
        "paycode": "STD",
        "note_to_be_displayed": "All leave requests must receive prior approval from Human Resources",
        "reference_logic_type": "Type4",
        "visible_to_employees": True,
        "accrual_policy": "Unlimited time off- does not accrue - should not deduct",
        "accrual_rate_daily": "Unlimited time off- does not accrue - should not deduct",
        "max_calendar_year_accrual_limit": "Unlimited time off- does not accrue - should not deduct",
        "carry_forward": "",
        "carry_forward_expiry": "",
        "time_off_reset": "",
        "over_draw": "",
        "validation": "",
        "leave_type": "Hours",
    },

    # 28: Z_UK_Parental Leave
    {
        "location_level_1": "United Kingdom",
        "location_level_1_to_exclude": ["Contractor"],
        "location_level_2_to_include": [],
        "location_level_2_to_exclude": [],
        "employee_levels_to_include": [],
        "employee_levels_to_exclude": [],
        "uksick_category_to_include": [],
        "uksick_category_to_exclude": [],
        "time_off_type": "Z_UK_Parental Leave",
        "time_off_type_group": "Parental Leave",
        "time_off_type_approval_path": "iPipeline UK - approved by Leave Manager",
        "paycode": "SMP",
        "note_to_be_displayed": "All leave requests must receive prior approval from Human Resources",
        "reference_logic_type": "Type4",
        "visible_to_employees": True,
        "accrual_policy": "Unlimited time off- does not accrue - should not deduct",
        "accrual_rate_daily": "Unlimited time off- does not accrue - should not deduct",
        "max_calendar_year_accrual_limit": "Unlimited time off- does not accrue - should not deduct",
        "carry_forward": "",
        "carry_forward_expiry": "",
        "time_off_reset": "",
        "over_draw": "",
        "validation": "",
        "leave_type": "Hours",
    },

    # 29: Z_USA_Bonding Leave
    {
        "location_level_1": "United States",
        "location_level_1_to_exclude": ["Contractor"],
        "location_level_2_to_include": [],
        "location_level_2_to_exclude": [],
        "employee_levels_to_include": [],
        "employee_levels_to_exclude": [],
        "uksick_category_to_include": [],
        "uksick_category_to_exclude": [],
        "time_off_type": "Z_USA_Bonding Leave",
        "time_off_type_group": "Bonding Leave",
        "time_off_type_approval_path": "iPipeline US - approved by leave Manager",
        "paycode": "BOND",
        "note_to_be_displayed": "All leave requests must receive prior approval from Human Resources",
        "reference_logic_type": "Type4",
        "visible_to_employees": True,
        "accrual_policy": "Unlimited time off- does not accrue - should not deduct",
        "accrual_rate_daily": "Unlimited time off- does not accrue - should not deduct",
        "max_calendar_year_accrual_limit": "Unlimited time off- does not accrue - should not deduct",
        "carry_forward": "",
        "carry_forward_expiry": "",
        "time_off_reset": "",
        "over_draw": "",
        "validation": "",
        "leave_type": "Hours",
    },

    # 30: Z_UK_Adoptive Leave
    {
        "location_level_1": "United Kingdom",
        "location_level_1_to_exclude": ["Contractor"],
        "location_level_2_to_include": [],
        "location_level_2_to_exclude": [],
        "employee_levels_to_include": [],
        "employee_levels_to_exclude": [],
        "uksick_category_to_include": [],
        "uksick_category_to_exclude": [],
        "time_off_type": "Z_UK_Adoptive Leave",
        "time_off_type_group": "Adoptive Leave",
        "time_off_type_approval_path": "iPipeline UK - approved by Leave Manager",
        "paycode": "UKADOPT",
        "note_to_be_displayed": "All leave requests must receive prior approval from Human Resources",
        "reference_logic_type": "Type4",
        "visible_to_employees": True,
        "accrual_policy": "Unlimited time off- does not accrue - should not deduct",
        "accrual_rate_daily": "Unlimited time off- does not accrue - should not deduct",
        "max_calendar_year_accrual_limit": "Unlimited time off- does not accrue - should not deduct",
        "carry_forward": "",
        "carry_forward_expiry": "",
        "time_off_reset": "",
        "over_draw": "",
        "validation": "",
        "leave_type": "Hours",
    },

    # 31: Z_UK_Antenatal
    {
        "location_level_1": "United Kingdom",
        "location_level_1_to_exclude": ["Contractor"],
        "location_level_2_to_include": [],
        "location_level_2_to_exclude": [],
        "employee_levels_to_include": [],
        "employee_levels_to_exclude": [],
        "uksick_category_to_include": [],
        "uksick_category_to_exclude": [],
        "time_off_type": "Z_UK_Antenatal",
        "time_off_type_group": "Antenatal",
        "time_off_type_approval_path": "iPipeline UK - approved by Leave Manager",
        "paycode": "UKANT",
        "note_to_be_displayed": "All leave requests must receive prior approval from Human Resources",
        "reference_logic_type": "Type4",
        "visible_to_employees": True,
        "accrual_policy": "Unlimited time off- does not accrue - should not deduct",
        "accrual_rate_daily": "Unlimited time off- does not accrue - should not deduct",
        "max_calendar_year_accrual_limit": "Unlimited time off- does not accrue - should not deduct",
        "carry_forward": "",
        "carry_forward_expiry": "",
        "time_off_reset": "",
        "over_draw": "",
        "validation": "",
        "leave_type": "Hours",
    },

    # 32: UK Appointment
    {
        "location_level_1": "United Kingdom",
        "location_level_1_to_exclude": ["Contractor"],
        "location_level_2_to_include": [],
        "location_level_2_to_exclude": [],
        "employee_levels_to_include": [],
        "employee_levels_to_exclude": [],
        "uksick_category_to_include": [],
        "uksick_category_to_exclude": [],
        "time_off_type": "UK_Appointment",
        "time_off_type_group": "Appointment",
        "time_off_type_approval_path": "iPipeline UK",
        "paycode": "UKAPPT",
        "note_to_be_displayed": "",
        "reference_logic_type": "Type4",
        "visible_to_employees": True,
        "accrual_policy": "Unlimited time off- does not accrue - should not deduct",
        "accrual_rate_daily": "Unlimited time off- does not accrue - should not deduct",
        "max_calendar_year_accrual_limit": "Unlimited time off- does not accrue - should not deduct",
        "carry_forward": "",
        "carry_forward_expiry": "",
        "time_off_reset": "",
        "over_draw": "",
        "validation": "",
        "leave_type": "Hours",
    },

    # 33: Z_UK_Career Break
    {
        "location_level_1": "United Kingdom",
        "location_level_1_to_exclude": ["Contractor"],
        "location_level_2_to_include": [],
        "location_level_2_to_exclude": [],
        "employee_levels_to_include": [],
        "employee_levels_to_exclude": [],
        "uksick_category_to_include": [],
        "uksick_category_to_exclude": [],
        "time_off_type": "Z_UK_Career Break",
        "time_off_type_group": "Career Break",
        "time_off_type_approval_path": "iPipeline UK - approved by Leave Manager",
        "paycode": "UKCAREER",
        "note_to_be_displayed": "All leave requests must receive prior approval from Human Resources",
        "reference_logic_type": "Type4",
        "visible_to_employees": True,
        "accrual_policy": "Unlimited time off- does not accrue - should not deduct",
        "accrual_rate_daily": "Unlimited time off- does not accrue - should not deduct",
        "max_calendar_year_accrual_limit": "Unlimited time off- does not accrue - should not deduct",
        "carry_forward": "",
        "carry_forward_expiry": "",
        "time_off_reset": "",
        "over_draw": "",
        "validation": "",
        "leave_type": "Hours",
    },

    # 34: Z_UK_Paternity Leave
    {
        "location_level_1": "United Kingdom",
        "location_level_1_to_exclude": ["Contractor"],
        "location_level_2_to_include": [],
        "location_level_2_to_exclude": [],
        "employee_levels_to_include": [],
        "employee_levels_to_exclude": [],
        "uksick_category_to_include": [],
        "uksick_category_to_exclude": [],
        "time_off_type": "Z_UK_Paternity Leave",
        "time_off_type_group": "Paternity Leave",
        "time_off_type_approval_path": "iPipeline UK - approved by Leave Manager",
        "paycode": "UPAT",
        "note_to_be_displayed": "All leave requests must receive prior approval from Human Resources",
        "reference_logic_type": "Type4",
        "visible_to_employees": True,
        "accrual_policy": "Unlimited time off- does not accrue - should not deduct",
        "accrual_rate_daily": "Unlimited time off- does not accrue - should not deduct",
        "max_calendar_year_accrual_limit": "Unlimited time off- does not accrue - should not deduct",
        "carry_forward": "",
        "carry_forward_expiry": "",
        "time_off_reset": "",
        "over_draw": "",
        "validation": "",
        "leave_type": "Hours",
    },

    # 35: Z_USA_Maternity Leave
    {
        "location_level_1": "United States",
        "location_level_1_to_exclude": ["Contractor"],
        "location_level_2_to_include": [],
        "location_level_2_to_exclude": [],
        "employee_levels_to_include": [],
        "employee_levels_to_exclude": [],
        "uksick_category_to_include": [],
        "uksick_category_to_exclude": [],
        "time_off_type": "Z_USA_Maternity Leave",
        "time_off_type_group": "Maternity Leave",
        "time_off_type_approval_path": "iPipeline US - approved by leave Manager",
        "paycode": "MAT",
        "note_to_be_displayed": "All leave requests must receive prior approval from Human Resources",
        "reference_logic_type": "Type4",
        "visible_to_employees": True,
        "accrual_policy": "Unlimited time off- does not accrue - should not deduct",
        "accrual_rate_daily": "Unlimited time off- does not accrue - should not deduct",
        "max_calendar_year_accrual_limit": "Unlimited time off- does not accrue - should not deduct",
        "carry_forward": "",
        "carry_forward_expiry": "",
        "time_off_reset": "",
        "over_draw": "",
        "validation": "",
        "leave_type": "Hours",
    },

    # 36: USA Summer Hours
    #No time off assignment for Type5 according to spec

    # 37: Z_Canada_Pregnancy/Parental/Maternity Leave
    {
        "location_level_1": "Canada",
        "location_level_1_to_exclude": ["Contractor"],
        "location_level_2_to_include": [],
        "location_level_2_to_exclude": [],
        "employee_levels_to_include": [],
        "employee_levels_to_exclude": [],
        "uksick_category_to_include": [],
        "uksick_category_to_exclude": [],
        "time_off_type": "Z_Canada_Pregnancy/Parental/Maternity Leave",
        "time_off_type_group": "",
        "time_off_type_approval_path": "iPipeline CAN - approved by leave Manager",
        "paycode": "OFFPAYROLL",
        "note_to_be_displayed": "All leave requests must receive prior approval from Human Resources",
        "reference_logic_type": "Type4",
        "visible_to_employees": True,
        "accrual_policy": "Unlimited time off- does not accrue - should not deduct",
        "accrual_rate_daily": "Unlimited time off- does not accrue - should not deduct",
        "max_calendar_year_accrual_limit": "Unlimited time off- does not accrue - should not deduct",
        "carry_forward": "",
        "carry_forward_expiry": "",
        "time_off_reset": "",
        "over_draw": "",
        "validation": "",
        "leave_type": "Hours",
    },

    # 38: Z_Canada_Leave Other
    {
        "location_level_1": "Canada",
        "location_level_1_to_exclude": ["Contractor"],
        "location_level_2_to_include": [],
        "location_level_2_to_exclude": [],
        "employee_levels_to_include": [],
        "employee_levels_to_exclude": [],
        "uksick_category_to_include": [],
        "uksick_category_to_exclude": [],
        "time_off_type": "Z_Canada_Leave Other",
        "time_off_type_group": "",
        "time_off_type_approval_path": "iPipeline CAN - approved by leave Manager",
        "paycode": "OFFPAYROLL",
        "note_to_be_displayed": "All leave requests must receive prior approval from Human Resources",
        "reference_logic_type": "Type4",
        "visible_to_employees": True,
        "accrual_policy": "Unlimited time off- does not accrue - should not deduct",
        "accrual_rate_daily": "Unlimited time off- does not accrue - should not deduct",
        "max_calendar_year_accrual_limit": "Unlimited time off- does not accrue - should not deduct",
        "carry_forward": "",
        "carry_forward_expiry": "",
        "time_off_reset": "",
        "over_draw": "",
        "validation": "",
        "leave_type": "Hours",
    },

    # 39: Holiday
    {
        "location_level_1": "ALL",
        "location_level_1_to_exclude": ["Contractor"],
        "location_level_2_to_include": [],
        "location_level_2_to_exclude": [],
        "employee_levels_to_include": [],
        "employee_levels_to_exclude": [],
        "uksick_category_to_include": [],
        "uksick_category_to_exclude": [],
        "time_off_type": "Holiday",
        "time_off_type_group": "",
        "time_off_type_approval_path": "",
        "paycode": "",
        "note_to_be_displayed": "This for all the state Holidays",
        "reference_logic_type": "Type4",
        "visible_to_employees": True,
        "accrual_policy": "",
        "accrual_rate_daily": "",
        "max_calendar_year_accrual_limit": "",
        "carry_forward": "",
        "carry_forward_expiry": "",
        "time_off_reset": "",
        "over_draw": "",
        "validation": "",
        "leave_type": "",
    },

    # 40: Z_UK_ Keep in Touch Day
    {
        "location_level_1": "United Kingdom",
        "location_level_1_to_exclude": ["Contractor"],
        "location_level_2_to_include": [],
        "location_level_2_to_exclude": [],
        "employee_levels_to_include": [],
        "employee_levels_to_exclude": [],
        "uksick_category_to_include": [],
        "uksick_category_to_exclude": [],
        "time_off_type": "Z_UK_ Keep in Touch Day",
        "time_off_type_group": "Keep in Touch Day",
        "time_off_type_approval_path": "iPipeline UK - approved by Leave Manager",
        "paycode": "UKKIT",
        "note_to_be_displayed": "All leave requests must receive prior approval from Human Resources",
        "reference_logic_type": "Type4",
        "visible_to_employees": True,
        "accrual_policy": "Unlimited time off- does not accrue - should not deduct",
        "accrual_rate_daily": "Unlimited time off- does not accrue - should not deduct",
        "max_calendar_year_accrual_limit": "Unlimited time off- does not accrue - should not deduct",
        "carry_forward": "",
        "carry_forward_expiry": "",
        "time_off_reset": "",
        "over_draw": "",
        "validation": "",
        "leave_type": "Hours",
    }
]