# pylint: disable=wildcard-import unused-wildcard-import
from dxctechnology.timesheet_autosubmission.config import *

instance = 'dxctrial01'
region = 'us-east-2'
environment = 'pre-production'
company_key = 'dxctrial01'
replicon_conn_id = 'dxctrial01-replicon-RepliconIntC1'
sumo_conn_id = 'sumologic-exportlogger'
sftp_conn_id = 'sftp_dxctechnology_timesheetautosubmission'
# pylint: disable=line-too-long
tenant_email = '{{ var.value.dagrun_internal_testing_email }}'
sftp_upload_path = '/timesheetautosubmission/logs/'
extract_report_name = 'Timesheets for Auto Submission - Hungary - Compass'
report_filter_timesheetperiod = 'TimesheetPeriodFilter'
report_filter_approvalstatus = 'ApprovalStatusFilter'
report_filter_currentdivision = 'CurrentDivisionFilter'
report_filter_employeetype = None
dag_max_active_runs = 10
dag_max_active_tasks = 128
execution_timeout_days = 14
batch_size = 50
country = 'Hungary'
entity = 'Compass'
identifier_filename = 'Compass'
employee_type = None
timesheet_status_value = '0' # Not Approved status
schedule = '30 23 * * SUN'
identifier_dagname = ''
