role_approval_path_mapper = {
    "timesheet_approval_path": 'Supervisor',
    "timeoff_approval_path": "Germany - Approval Path",
    "l1_manager_wbs": "L1 Manager (DE)",
    "l1_manager_non_wbs": "DE_Project Resource With Reports",
    "end_user_manager": "End User (Managers)",
    "project_manager": "Germany Project Manager",
    "hr_manager": "DE_GPO",
    "default_user_permission": "Project Resource with Reports",
    "foreign_manager_emp_type": "Foreign Managers",
    "ot_request_template": "DE OT Request",
    "ot_request_approval_path": "Supervisor",
    "schedule_type": "urn:replicon:schedule-type:office-schedule",
    "payrule_for_non_wbs_eon": "DE_EON_PayRule_0.1",
    "payrule_for_non_wbs_rwe": "DE_RWE_PayRule_0.1",
    "payrule_fo_wbs": "DE_WBS_Payrule_0.3",
    "payrule_for_non_wbs": "DE_Non_WBS_Payrule_0.2",
    "timesheet_for_non_wbs_eon": "Germany Non WBS E.ON",
    "timesheet_for_non_wbs_rwe": "Germany Non WBS RWE",
    "timesheet_for_wbs": "Germany WBS Timesheet",
    "timesheet_for_non_wbs": "Germany Non WBS Timesheet",
    "time_zone": "(UTC+1:00) Central European Standard Time",
    "timesheet_system_approval_path": "System Approval",
    "timesheet_period": "Weekly starting on Monday",
    "activity": "Mobile Working,Office Working,Passive Travel /Passiv-Reisen",
    "legal_entity_wbs": "W162",
    "legal_entity_non_wbs": "W024",
    "wc_tag_eon": "E.ON Application WC",
    "wc_tag_rwe": "WC RR",
    "schedule_policy": "Germany Schedule Policy"
}