holiday_calendar = {
    'Aachen': 'North Rhine-Wesphalia',
    'Augsburg': 'Bavaria Augsburg',
    'Baunatal': 'Hesse',
    'Bayreuth': 'Bavaria Non Catholic Town',
    'Berlin': 'Berlin',
    'Bochum': 'North Rhine-Wesphalia',
    'Boeblingen': 'Baden-Württemberg',
    'Bonn': 'North Rhine-Wesphalia',
    'Bremerhaven': 'Bremen',
    'Darmstadt': 'Hesse',
    'Dorsten': 'North Rhine-Wesphalia',
    'Dortmund': 'North Rhine-Wesphalia',
    'Dresden': 'Saxony',
    'Düsseldorf': 'North Rhine-Wesphalia',
    'Duesseldorf': 'North Rhine-Wesphalia',
    'Erlangen': 'Bavaria Non Catholic Town',
    'Essen': 'North Rhine-Wesphalia',
    'Fellbach': 'Baden-Württemberg',
    'Frankfurt/M': 'Hesse',
    'Frankfurt am Main': 'Hesse',
    'Freiburg': 'Baden-Württemberg',
    'Geilenkirchen': 'North Rhine-Wesphalia',
    'Grevenbroich-Neurath': 'North Rhine-Wesphalia',
    'Halle': 'Saxony-Anhalt',
    'Hamburg': 'Hamburg',
    'Hannover': 'Lower Saxony',
    'Hanover': 'Lower Saxony',
    'Heidelberg': 'Baden-Württemberg',
    'Holzgerlingen': 'Baden-Württemberg',
    'Husum': 'Schleswig-Holstein',
    'Karlsbad': 'Baden-Württemberg',
    'Karlsruhe': 'Baden-Württemberg',
    'Kiel': 'Schleswig-Holstein',
    'Köln': 'North Rhine-Wesphalia',
    'Cologne': 'North Rhine-Wesphalia',
    'Konstanz': 'Baden-Württemberg',
    'Krefeld': 'North Rhine-Wesphalia',
    'Landshut': 'Bavaria Catholic Town',
    'Langen': 'Hesse',
    'Lauchhammer': 'Brandenburg',
    'Luetjensee': 'Schleswig-Holstein',
    'Mannheim': 'Baden-Württemberg',
    'Meerbusch': 'North Rhine-Wesphalia',
    'Moenchengladbach': 'North Rhine-Wesphalia',
    'München': 'Bavaria Catholic Town',
    'Munich': 'Bavaria Catholic Town',
    'Neubiberg': 'Bavaria Catholic Town',
    'Nürnberg': 'Bavaria Non Catholic Town',
    'Nuremberg': 'Bavaria Non Catholic Town',
    'Offenbach': 'Hesse',
    'Östringen': 'Baden-Württemberg',
    'Oestringen': 'Baden-Württemberg',
    'Potsdam': 'Brandenburg',
    'Reutlingen': 'Baden-Württemberg',
    'Salzgitter': 'Lower Saxony',
    'Schaidt': 'Rhineland-Palatine',
    'Schwäbisch-Hall': 'Baden-Württemberg',
    'Schwabisch Hall': 'Baden-Württemberg',
    'Sindelfingen': 'Baden-Württemberg',
    'Straubing': 'Bavaria Catholic Town',
    'Stuttgart': 'Baden-Württemberg',
    'Travemuende': 'Schleswig-Holstein',
    'Troisdorf': 'North Rhine-Wesphalia',
    'Ulm': 'Baden-Württemberg',
    'Unknown Location': 'Berlin',
    'Various': 'Berlin',
    'Verl': 'North Rhine-Wesphalia',
    'Walldorf': 'Hesse',
    'Weilburg': 'Hesse',
    'Wiesbaden': 'Hesse',
    'Wolfsburg': 'Lower Saxony',
    'Würzburg': 'Bavaria Catholic Town',
    'Wuerzburg': 'Bavaria Catholic Town'
}
