user_import_mapper = [
    {
        "location_level_1": "Mauritius",
        "location_level_2": "St Felix",
        "location_level_3": ["CHAMOUNY","PORTLOUISLTL"],
        "staff_category": "Staff",
        "functional_sub_segment": "NA",
        "employee_type": "Staff",
        "reg_temp": "Regular",
        "pay_type": "Salaried",
        "timesheet_period": "MUR - Weekly starting on Monday",
        "timesheet_template": "MUR_Staff",
        "punch_policy": "MUR_Staff_punch",
        "holiday_calendar": "MUR-Staff",
        "timesheet_approval_path": "Supervisor",
        "time_off_template": "Time Off",
        "time_off_approver": "Supervisor",
        "work_week": "Monday to Sunday",
        "payrule_name": "MUR_Staff_Payrule",
        "timezone": "(UTC+4:00) Mauritius Standard Time"
    },
    {
        "location_level_1": "Mauritius",
        "location_level_2": "St Felix",
        "location_level_3": ["CHAMOUNY","PORTLOUISLTL"],
        "staff_category": "Field Staff",
        "functional_sub_segment": "ADM",
        "employee_type": "Field Staff – Regular",
        "reg_temp": "Regular",
        "pay_type": "Salaried",
        "timesheet_period": "MUR - Weekly starting on Monday",
        "timesheet_template": "MUR_Field Staff_Regular",
        "punch_policy": "MUR_Field-Staff_Regular_Punch",
        "holiday_calendar": "MUR-Field Staff Regular & Maintenance",
        "timesheet_approval_path": "Supervisor",
        "time_off_template": "Time Off",
        "time_off_approver": "Supervisor",
        "work_week": "Monday to Sunday",
        "payrule_name": "MUR_Field Staff_Regular",
        "timezone": "(UTC+4:00) Mauritius Standard Time"
    },
    {
        "location_level_1": "Mauritius",
        "location_level_2": "St Felix",
        "location_level_3": ["CHAMOUNY","PORTLOUISLTL"],
        "staff_category": "Field Staff",
        "functional_sub_segment": "BU_0",
        "employee_type": "Field Staff – Regular",
        "reg_temp": "Regular",
        "pay_type": "Salaried",
        "timesheet_period": "MUR - Weekly starting on Monday",
        "timesheet_template": "MUR_Field Staff_Regular",
        "punch_policy": "MUR_Field-Staff_Regular_Punch",
        "holiday_calendar": "MUR-Field Staff Regular & Maintenance",
        "timesheet_approval_path": "Supervisor",
        "time_off_template": "Time Off",
        "time_off_approver": "Supervisor",
        "work_week": "Monday to Sunday",
        "payrule_name": "MUR_Field Staff_Regular",
        "timezone": "(UTC+4:00) Mauritius Standard Time"
    },
    {
        "location_level_1": "Mauritius",
        "location_level_2": "St Felix",
        "location_level_3": ["CHAMOUNY","PORTLOUISLTL"],
        "staff_category": "Field Staff",
        "functional_sub_segment": "BU_1",
        "employee_type": "Field Staff – Regular",
        "reg_temp": "Regular",
        "pay_type": "Salaried",
        "timesheet_period": "MUR - Weekly starting on Monday",
        "timesheet_template": "MUR_Field Staff_Regular",
        "punch_policy": "MUR_Field-Staff_Regular_Punch",
        "holiday_calendar": "MUR-Field Staff Regular & Maintenance",
        "timesheet_approval_path": "Supervisor",
        "time_off_template": "Time Off",
        "time_off_approver": "Supervisor",
        "work_week": "Monday to Sunday",
        "payrule_name": "MUR_Field Staff_Regular",
        "timezone": "(UTC+4:00) Mauritius Standard Time"
    },
    {
        "location_level_1": "Mauritius",
        "location_level_2": "St Felix",
        "location_level_3": ["CHAMOUNY","PORTLOUISLTL"],
        "staff_category": "Field Staff",
        "functional_sub_segment": "BU_2",
        "employee_type": "Field Staff – Regular",
        "reg_temp": "Regular",
        "pay_type": "Salaried",
        "timesheet_period": "MUR - Weekly starting on Monday",
        "timesheet_template": "MUR_Field Staff_Regular",
        "punch_policy": "MUR_Field-Staff_Regular_Punch",
        "holiday_calendar": "MUR-Field Staff Regular & Maintenance",
        "timesheet_approval_path": "Supervisor",
        "time_off_template": "Time Off",
        "time_off_approver": "Supervisor",
        "work_week": "Monday to Sunday",
        "payrule_name": "MUR_Field Staff_Regular",
        "timezone": "(UTC+4:00) Mauritius Standard Time"
    },
    {
        "location_level_1": "Mauritius",
        "location_level_2": "St Felix",
        "location_level_3": ["CHAMOUNY","PORTLOUISLTL"],
        "staff_category": "Field Staff",
        "functional_sub_segment": "BU_3",
        "employee_type": "Field Staff – Regular",
        "reg_temp": "Regular",
        "pay_type": "Salaried",
        "timesheet_period": "MUR - Weekly starting on Monday",
        "timesheet_template": "MUR_Field Staff_Regular",
        "punch_policy": "MUR_Field-Staff_Regular_Punch",
        "holiday_calendar": "MUR-Field Staff Regular & Maintenance",
        "timesheet_approval_path": "Supervisor",
        "time_off_template": "Time Off",
        "time_off_approver": "Supervisor",
        "work_week": "Monday to Sunday",
        "payrule_name": "MUR_Field Staff_Regular",
        "timezone": "(UTC+4:00) Mauritius Standard Time"
    },
    {
        "location_level_1": "Mauritius",
        "location_level_2": "St Felix",
        "location_level_3": ["CHAMOUNY","PORTLOUISLTL"],
        "staff_category": "Field Staff",
        "functional_sub_segment": "BU_4",
        "employee_type": "Field Staff – Regular",
        "reg_temp": "Regular",
        "pay_type": "Salaried",
        "timesheet_period": "MUR - Weekly starting on Monday",
        "timesheet_template": "MUR_Field Staff_Regular",
        "punch_policy": "MUR_Field-Staff_Regular_Punch",
        "holiday_calendar": "MUR-Field Staff Regular & Maintenance",
        "timesheet_approval_path": "Supervisor",
        "time_off_template": "Time Off",
        "time_off_approver": "Supervisor",
        "work_week": "Monday to Sunday",
        "payrule_name": "MUR_Field Staff_Regular",
        "timezone": "(UTC+4:00) Mauritius Standard Time"
    },
    {
        "location_level_1": "Mauritius",
        "location_level_2": "St Felix",
        "location_level_3": ["CHAMOUNY","PORTLOUISLTL"],
        "staff_category": "Field Staff",
        "functional_sub_segment": "BU_5",
        "employee_type": "Field Staff – Regular",
        "reg_temp": "Regular",
        "pay_type": "Salaried",
        "timesheet_period": "MUR - Weekly starting on Monday",
        "timesheet_template": "MUR_Field Staff_Regular",
        "punch_policy": "MUR_Field-Staff_Regular_Punch",
        "holiday_calendar": "MUR-Field Staff Regular & Maintenance",
        "timesheet_approval_path": "Supervisor",
        "time_off_template": "Time Off",
        "time_off_approver": "Supervisor",
        "work_week": "Monday to Sunday",
        "payrule_name": "MUR_Field Staff_Regular",
        "timezone": "(UTC+4:00) Mauritius Standard Time"
    },
    {
        "location_level_1": "Mauritius",
        "location_level_2": "St Felix",
        "location_level_3": ["CHAMOUNY","PORTLOUISLTL"],
        "staff_category": "Field Staff",
        "functional_sub_segment": "BU_6",
        "employee_type": "Field Staff – Regular",
        "reg_temp": "Regular",
        "pay_type": "Salaried",
        "timesheet_period": "MUR - Weekly starting on Monday",
        "timesheet_template": "MUR_Field Staff_Regular",
        "punch_policy": "MUR_Field-Staff_Regular_Punch",
        "holiday_calendar": "MUR-Field Staff Regular & Maintenance",
        "timesheet_approval_path": "Supervisor",
        "time_off_template": "Time Off",
        "time_off_approver": "Supervisor",
        "work_week": "Monday to Sunday",
        "payrule_name": "MUR_Field Staff_Regular",
        "timezone": "(UTC+4:00) Mauritius Standard Time"
    },
    {
        "location_level_1": "Mauritius",
        "location_level_2": "St Felix",
        "location_level_3": ["CHAMOUNY","PORTLOUISLTL"],
        "staff_category": "Field Staff",
        "functional_sub_segment": "BU_7",
        "employee_type": "Field Staff – Regular",
        "reg_temp": "Regular",
        "pay_type": "Salaried",
        "timesheet_period": "MUR - Weekly starting on Monday",
        "timesheet_template": "MUR_Field Staff_Regular",
        "punch_policy": "MUR_Field-Staff_Regular_Punch",
        "holiday_calendar": "MUR-Field Staff Regular & Maintenance",
        "timesheet_approval_path": "Supervisor",
        "time_off_template": "Time Off",
        "time_off_approver": "Supervisor",
        "work_week": "Monday to Sunday",
        "payrule_name": "MUR_Field Staff_Regular",
        "timezone": "(UTC+4:00) Mauritius Standard Time"
    },
    {
        "location_level_1": "Mauritius",
        "location_level_2": "St Felix",
        "location_level_3": ["CHAMOUNY","PORTLOUISLTL"],
        "staff_category": "Field Staff",
        "functional_sub_segment": "BU_8",
        "employee_type": "Field Staff – Regular",
        "reg_temp": "Regular",
        "pay_type": "Salaried",
        "timesheet_period": "MUR - Weekly starting on Monday",
        "timesheet_template": "MUR_Field Staff_Regular",
        "punch_policy": "MUR_Field-Staff_Regular_Punch",
        "holiday_calendar": "MUR-Field Staff Regular & Maintenance",
        "timesheet_approval_path": "Supervisor",
        "time_off_template": "Time Off",
        "time_off_approver": "Supervisor",
        "work_week": "Monday to Sunday",
        "payrule_name": "MUR_Field Staff_Regular",
        "timezone": "(UTC+4:00) Mauritius Standard Time"
    },
    {
        "location_level_1": "Mauritius",
        "location_level_2": "St Felix",
        "location_level_3": ["CHAMOUNY","PORTLOUISLTL"],
        "staff_category": "Field Staff",
        "functional_sub_segment": "BU_9",
        "employee_type": "Field Staff – Regular",
        "reg_temp": "Regular",
        "pay_type": "Salaried",
        "timesheet_period": "MUR - Weekly starting on Monday",
        "timesheet_template": "MUR_Field Staff_Regular",
        "punch_policy": "MUR_Field-Staff_Regular_Punch",
        "holiday_calendar": "MUR-Field Staff Regular & Maintenance",
        "timesheet_approval_path": "Supervisor",
        "time_off_template": "Time Off",
        "time_off_approver": "Supervisor",
        "work_week": "Monday to Sunday",
        "payrule_name": "MUR_Field Staff_Regular",
        "timezone": "(UTC+4:00) Mauritius Standard Time"
    },
    {
        "location_level_1": "Mauritius",
        "location_level_2": "St Felix",
        "location_level_3": ["CHAMOUNY","PORTLOUISLTL"],
        "staff_category": "Field Staff",
        "functional_sub_segment": "BU_10",
        "employee_type": "Field Staff – Regular",
        "reg_temp": "Regular",
        "pay_type": "Salaried",
        "timesheet_period": "MUR - Weekly starting on Monday",
        "timesheet_template": "MUR_Field Staff_Regular",
        "punch_policy": "MUR_Field-Staff_Regular_Punch",
        "holiday_calendar": "MUR-Field Staff Regular & Maintenance",
        "timesheet_approval_path": "Supervisor",
        "time_off_template": "Time Off",
        "time_off_approver": "Supervisor",
        "work_week": "Monday to Sunday",
        "payrule_name": "MUR_Field Staff_Regular",
        "timezone": "(UTC+4:00) Mauritius Standard Time"
    },
    {
        "location_level_1": "Mauritius",
        "location_level_2": "St Felix",
        "location_level_3": ["CHAMOUNY","PORTLOUISLTL"],
        "staff_category": "Field Staff",
        "functional_sub_segment": "BU_11",
        "employee_type": "Field Staff – Regular",
        "reg_temp": "Regular",
        "pay_type": "Salaried",
        "timesheet_period": "MUR - Weekly starting on Monday",
        "timesheet_template": "MUR_Field Staff_Regular",
        "punch_policy": "MUR_Field-Staff_Regular_Punch",
        "holiday_calendar": "MUR-Field Staff Regular & Maintenance",
        "timesheet_approval_path": "Supervisor",
        "time_off_template": "Time Off",
        "time_off_approver": "Supervisor",
        "work_week": "Monday to Sunday",
        "payrule_name": "MUR_Field Staff_Regular",
        "timezone": "(UTC+4:00) Mauritius Standard Time"
    },
    {
        "location_level_1": "Mauritius",
        "location_level_2": "St Felix",
        "location_level_3": ["CHAMOUNY","PORTLOUISLTL"],
        "staff_category": "Field Staff",
        "functional_sub_segment": "BU_12",
        "employee_type": "Field Staff – Regular",
        "reg_temp": "Regular",
        "pay_type": "Salaried",
        "timesheet_period": "MUR - Weekly starting on Monday",
        "timesheet_template": "MUR_Field Staff_Regular",
        "punch_policy": "MUR_Field-Staff_Regular_Punch",
        "holiday_calendar": "MUR-Field Staff Regular & Maintenance",
        "timesheet_approval_path": "Supervisor",
        "time_off_template": "Time Off",
        "time_off_approver": "Supervisor",
        "work_week": "Monday to Sunday",
        "payrule_name": "MUR_Field Staff_Regular",
        "timezone": "(UTC+4:00) Mauritius Standard Time"
    },
    {
        "location_level_1": "Mauritius",
        "location_level_2": "St Felix",
        "location_level_3": ["CHAMOUNY","PORTLOUISLTL"],
        "staff_category": "Field Staff",
        "functional_sub_segment": "BU_13",
        "employee_type": "Field Staff – Regular",
        "reg_temp": "Regular",
        "pay_type": "Salaried",
        "timesheet_period": "MUR - Weekly starting on Monday",
        "timesheet_template": "MUR_Field Staff_Regular",
        "punch_policy": "MUR_Field-Staff_Regular_Punch",
        "holiday_calendar": "MUR-Field Staff Regular & Maintenance",
        "timesheet_approval_path": "Supervisor",
        "time_off_template": "Time Off",
        "time_off_approver": "Supervisor",
        "work_week": "Monday to Sunday",
        "payrule_name": "MUR_Field Staff_Regular",
        "timezone": "(UTC+4:00) Mauritius Standard Time"
    },
    {
        "location_level_1": "Mauritius",
        "location_level_2": "St Felix",
        "location_level_3": ["CHAMOUNY","PORTLOUISLTL"],
        "staff_category": "Field Staff",
        "functional_sub_segment": "BU_14",
        "employee_type": "Field Staff – Regular",
        "reg_temp": "Regular",
        "pay_type": "Salaried",
        "timesheet_period": "MUR - Weekly starting on Monday",
        "timesheet_template": "MUR_Field Staff_Regular",
        "punch_policy": "MUR_Field-Staff_Regular_Punch",
        "holiday_calendar": "MUR-Field Staff Regular & Maintenance",
        "timesheet_approval_path": "Supervisor",
        "time_off_template": "Time Off",
        "time_off_approver": "Supervisor",
        "work_week": "Monday to Sunday",
        "payrule_name": "MUR_Field Staff_Regular",
        "timezone": "(UTC+4:00) Mauritius Standard Time"
    },
    {
        "location_level_1": "Mauritius",
        "location_level_2": "St Felix",
        "location_level_3": ["CHAMOUNY","PORTLOUISLTL"],
        "staff_category": "Field Staff",
        "functional_sub_segment": "BU_15",
        "employee_type": "Field Staff – Regular",
        "reg_temp": "Regular",
        "pay_type": "Salaried",
        "timesheet_period": "MUR - Weekly starting on Monday",
        "timesheet_template": "MUR_Field Staff_Regular",
        "punch_policy": "MUR_Field-Staff_Regular_Punch",
        "holiday_calendar": "MUR-Field Staff Regular & Maintenance",
        "timesheet_approval_path": "Supervisor",
        "time_off_template": "Time Off",
        "time_off_approver": "Supervisor",
        "work_week": "Monday to Sunday",
        "payrule_name": "MUR_Field Staff_Regular",
        "timezone": "(UTC+4:00) Mauritius Standard Time"
    },
    {
        "location_level_1": "Mauritius",
        "location_level_2": "St Felix",
        "location_level_3": ["CHAMOUNY","PORTLOUISLTL"],
        "staff_category": "Field Staff",
        "functional_sub_segment": "Civil",
        "employee_type": "Field Staff – Maintenance",
        "reg_temp": "Regular",
        "pay_type": "Salaried",
        "timesheet_period": "MUR - Weekly starting on Monday",
        "timesheet_template": "MUR_Field Staff_Maintenance",
        "punch_policy": "MUR_Field-Staff_Maintanance_Punch",
        "holiday_calendar": "MUR-Field Staff Regular & Maintenance",
        "timesheet_approval_path": "Supervisor",
        "time_off_template": "Time Off",
        "time_off_approver": "Supervisor",
        "work_week": "Monday to Sunday",
        "payrule_name": "MUR_Field Staff_Maintenance",
        "timezone": "(UTC+4:00) Mauritius Standard Time"
    },
    {
        "location_level_1": "Mauritius",
        "location_level_2": "St Felix",
        "location_level_3": ["CHAMOUNY","PORTLOUISLTL"],
        "staff_category": "Field Staff",
        "functional_sub_segment": "Elec",
        "employee_type": "Field Staff – Maintenance",
        "reg_temp": "Regular",
        "pay_type": "Salaried",
        "timesheet_period": "MUR - Weekly starting on Monday",
        "timesheet_template": "MUR_Field Staff_Maintenance",
        "punch_policy": "MUR_Field-Staff_Maintanance_Punch",
        "holiday_calendar": "MUR-Field Staff Regular & Maintenance",
        "timesheet_approval_path": "Supervisor",
        "time_off_template": "Time Off",
        "time_off_approver": "Supervisor",
        "work_week": "Monday to Sunday",
        "payrule_name": "MUR_Field Staff_Maintenance",
        "timezone": "(UTC+4:00) Mauritius Standard Time"
    },
    {
        "location_level_1": "Mauritius",
        "location_level_2": "St Felix",
        "location_level_3": ["CHAMOUNY","PORTLOUISLTL"],
        "staff_category": "Field Staff",
        "functional_sub_segment": "Exp",
        "employee_type": "Field Staff – Regular",
        "reg_temp": "Regular",
        "pay_type": "Salaried",
        "timesheet_period": "MUR - Weekly starting on Monday",
        "timesheet_template": "MUR_Field Staff_Regular",
        "punch_policy": "MUR_Field-Staff_Regular_Punch",
        "holiday_calendar": "MUR-Field Staff Regular & Maintenance",
        "timesheet_approval_path": "Supervisor",
        "time_off_template": "Time Off",
        "time_off_approver": "Supervisor",
        "work_week": "Monday to Sunday",
        "payrule_name": "MUR_Field Staff_Regular",
        "timezone": "(UTC+4:00) Mauritius Standard Time"
    },
    {
        "location_level_1": "Mauritius",
        "location_level_2": "St Felix",
        "location_level_3": ["CHAMOUNY","PORTLOUISLTL"],
        "staff_category": "Field Staff",
        "functional_sub_segment": "LVS",
        "employee_type": "Field Staff – Regular",
        "reg_temp": "Regular",
        "pay_type": "Salaried",
        "timesheet_period": "MUR - Weekly starting on Monday",
        "timesheet_template": "MUR_Field Staff_Regular",
        "punch_policy": "MUR_Field-Staff_Regular_Punch",
        "holiday_calendar": "MUR-Field Staff Regular & Maintenance",
        "timesheet_approval_path": "Supervisor",
        "time_off_template": "Time Off",
        "time_off_approver": "Supervisor",
        "work_week": "Monday to Sunday",
        "payrule_name": "MUR_Field Staff_Regular",
        "timezone": "(UTC+4:00) Mauritius Standard Time"
    },
    {
        "location_level_1": "Mauritius",
        "location_level_2": "St Felix",
        "location_level_3": ["CHAMOUNY","PORTLOUISLTL"],
        "staff_category": "Field Staff",
        "functional_sub_segment": "NTS",
        "employee_type": "Field Staff – Regular",
        "reg_temp": "Regular",
        "pay_type": "Salaried",
        "timesheet_period": "MUR - Weekly starting on Monday",
        "timesheet_template": "MUR_Field Staff_Regular",
        "punch_policy": "MUR_Field-Staff_Regular_Punch",
        "holiday_calendar": "MUR-Field Staff Regular & Maintenance",
        "timesheet_approval_path": "Supervisor",
        "time_off_template": "Time Off",
        "time_off_approver": "Supervisor",
        "work_week": "Monday to Sunday",
        "payrule_name": "MUR_Field Staff_Regular",
        "timezone": "(UTC+4:00) Mauritius Standard Time"
    },
    {
        "location_level_1": "Mauritius",
        "location_level_2": "St Felix",
        "location_level_3": ["CHAMOUNY","PORTLOUISLTL"],
        "staff_category": "Field Staff",
        "functional_sub_segment": "RS_1",
        "employee_type": "Field Staff – Regular",
        "reg_temp": "Regular",
        "pay_type": "Salaried",
        "timesheet_period": "MUR - Weekly starting on Monday",
        "timesheet_template": "MUR_Field Staff_Regular",
        "punch_policy": "MUR_Field-Staff_Regular_Punch",
        "holiday_calendar": "MUR-Field Staff Regular & Maintenance",
        "timesheet_approval_path": "Supervisor",
        "time_off_template": "Time Off",
        "time_off_approver": "Supervisor",
        "work_week": "Monday to Sunday",
        "payrule_name": "MUR_Field Staff_Regular",
        "timezone": "(UTC+4:00) Mauritius Standard Time"
    },
    {
        "location_level_1": "Mauritius",
        "location_level_2": "St Felix",
        "location_level_3": ["CHAMOUNY","PORTLOUISLTL"],
        "staff_category": "Field Staff",
        "functional_sub_segment": "RS_2",
        "employee_type": "Field Staff – Regular",
        "reg_temp": "Regular",
        "pay_type": "Salaried",
        "timesheet_period": "MUR - Weekly starting on Monday",
        "timesheet_template": "MUR_Field Staff_Regular",
        "punch_policy": "MUR_Field-Staff_Regular_Punch",
        "holiday_calendar": "MUR-Field Staff Regular & Maintenance",
        "timesheet_approval_path": "Supervisor",
        "time_off_template": "Time Off",
        "time_off_approver": "Supervisor",
        "work_week": "Monday to Sunday",
        "payrule_name": "MUR_Field Staff_Regular",
        "timezone": "(UTC+4:00) Mauritius Standard Time"
    },
    {
        "location_level_1": "Mauritius",
        "location_level_2": "St Felix",
        "location_level_3": ["CHAMOUNY","PORTLOUISLTL"],
        "staff_category": "Field Staff",
        "functional_sub_segment": "Sec",
        "employee_type": "Field Staff – Security",
        "reg_temp": "Regular",
        "pay_type": "Salaried",
        "timesheet_period": "MUR - Weekly starting on Monday",
        "timesheet_template": "MUR_Field Staff_Security",
        "punch_policy": "MUR_Field-Staff_Security_Punch",
        "holiday_calendar": "MUR-Security",
        "timesheet_approval_path": "Supervisor",
        "time_off_template": "Time Off",
        "time_off_approver": "Supervisor",
        "work_week": "Monday to Sunday",
        "payrule_name": "MUR_Field Staff_Security",
        "timezone": "(UTC+4:00) Mauritius Standard Time"
    },
    {
        "location_level_1": "Mauritius",
        "location_level_2": "St Felix",
        "location_level_3": ["CHAMOUNY","PORTLOUISLTL"],
        "staff_category": "Field Staff",
        "functional_sub_segment": "Trans",
        "employee_type": "Field Staff – Regular",
        "reg_temp": "Regular",
        "pay_type": "Salaried",
        "timesheet_period": "MUR - Weekly starting on Monday",
        "timesheet_template": "MUR_Field Staff_Regular",
        "punch_policy": "MUR_Field-Staff_Regular_Punch",
        "holiday_calendar": "MUR-Field Staff Regular & Maintenance",
        "timesheet_approval_path": "Supervisor",
        "time_off_template": "Time Off",
        "time_off_approver": "Supervisor",
        "work_week": "Monday to Sunday",
        "payrule_name": "MUR_Field Staff_Regular",
        "timezone": "(UTC+4:00) Mauritius Standard Time"
    },
    {
        "location_level_1": "Mauritius",
        "location_level_2": "St Felix",
        "location_level_3": ["CHAMOUNY","PORTLOUISLTL"],
        "staff_category": "Field Staff",
        "functional_sub_segment": "Vet",
        "employee_type": "Field Staff – Regular",
        "reg_temp": "Regular",
        "pay_type": "Salaried",
        "timesheet_period": "MUR - Weekly starting on Monday",
        "timesheet_template": "MUR_Field Staff_Regular",
        "punch_policy": "MUR_Field-Staff_Regular_Punch",
        "holiday_calendar": "MUR-Field Staff Regular & Maintenance",
        "timesheet_approval_path": "Supervisor",
        "time_off_template": "Time Off",
        "time_off_approver": "Supervisor",
        "work_week": "Monday to Sunday",
        "payrule_name": "MUR_Field Staff_Regular",
        "timezone": "(UTC+4:00) Mauritius Standard Time"
    },
    {
        "location_level_1": "Mauritius",
        "location_level_2": "St Felix",
        "location_level_3": ["CHAMOUNY","PORTLOUISLTL"],
        "staff_category": "Field Staff",
        "functional_sub_segment": "Trap",
        "employee_type": "Field Staff – Regular",
        "reg_temp": "Regular",
        "pay_type": "Salaried",
        "timesheet_period": "MUR - Weekly starting on Monday",
        "timesheet_template": "MUR_Field Staff_Regular",
        "punch_policy": "MUR_Field-Staff_Regular_Punch",
        "holiday_calendar": "MUR-Field Staff Regular & Maintenance",
        "timesheet_approval_path": "Supervisor",
        "time_off_template": "Time Off",
        "time_off_approver": "Supervisor",
        "work_week": "Monday to Sunday",
        "payrule_name": "MUR_Field Staff_Regular",
        "timezone": "(UTC+4:00) Mauritius Standard Time"
    },
    {
        "location_level_1": "Mauritius",
        "location_level_2": "Le Vallon",
        "location_level_3": ["LEVALLON","NOUVELLETERRE","RAFFIA1","RAFFIA2"],
        "staff_category": "Staff",
        "functional_sub_segment": "NA",
        "employee_type": "Staff",
        "reg_temp": "Regular",
        "pay_type": "Salaried",
        "timesheet_period": "MUR - Weekly starting on Monday",
        "timesheet_template": "MUR_Staff",
        "punch_policy": "MUR_Staff_punch",
        "holiday_calendar": "MUR-Staff",
        "timesheet_approval_path": "Supervisor",
        "time_off_template": "Time Off",
        "time_off_approver": "Supervisor",
        "work_week": "Monday to Sunday",
        "payrule_name": "MUR_Staff_Payrule",
        "timezone": "(UTC+4:00) Mauritius Standard Time"
    },
    {
        "location_level_1": "Mauritius",
        "location_level_2": "Le Vallon",
        "location_level_3": ["LEVALLON","NOUVELLETERRE","RAFFIA1","RAFFIA2"],
        "staff_category": "Field Staff",
        "functional_sub_segment": "ADM",
        "employee_type": "Field Staff – Regular",
        "reg_temp": "Regular",
        "pay_type": "Salaried",
        "timesheet_period": "MUR - Weekly starting on Monday",
        "timesheet_template": "MUR_Field Staff_Regular",
        "punch_policy": "MUR_Field-Staff_Regular_Punch",
        "holiday_calendar": "MUR-Field Staff Regular & Maintenance",
        "timesheet_approval_path": "Supervisor",
        "time_off_template": "Time Off",
        "time_off_approver": "Supervisor",
        "work_week": "Monday to Sunday",
        "payrule_name": "MUR_Field Staff_Regular",
        "timezone": "(UTC+4:00) Mauritius Standard Time"
    },
    {
        "location_level_1": "Mauritius",
        "location_level_2": "Le Vallon",
        "location_level_3": ["LEVALLON","NOUVELLETERRE","RAFFIA1","RAFFIA2"],
        "staff_category": "Field Staff",
        "functional_sub_segment": "BU_0",
        "employee_type": "Field Staff – Regular",
        "reg_temp": "Regular",
        "pay_type": "Salaried",
        "timesheet_period": "MUR - Weekly starting on Monday",
        "timesheet_template": "MUR_Field Staff_Regular",
        "punch_policy": "MUR_Field-Staff_Regular_Punch",
        "holiday_calendar": "MUR-Field Staff Regular & Maintenance",
        "timesheet_approval_path": "Supervisor",
        "time_off_template": "Time Off",
        "time_off_approver": "Supervisor",
        "work_week": "Monday to Sunday",
        "payrule_name": "MUR_Field Staff_Regular",
        "timezone": "(UTC+4:00) Mauritius Standard Time"
    },
    {
        "location_level_1": "Mauritius",
        "location_level_2": "Le Vallon",
        "location_level_3": ["LEVALLON","NOUVELLETERRE","RAFFIA1","RAFFIA2"],
        "staff_category": "Field Staff",
        "functional_sub_segment": "BU_1",
        "employee_type": "Field Staff – Regular",
        "reg_temp": "Regular",
        "pay_type": "Salaried",
        "timesheet_period": "MUR - Weekly starting on Monday",
        "timesheet_template": "MUR_Field Staff_Regular",
        "punch_policy": "MUR_Field-Staff_Regular_Punch",
        "holiday_calendar": "MUR-Field Staff Regular & Maintenance",
        "timesheet_approval_path": "Supervisor",
        "time_off_template": "Time Off",
        "time_off_approver": "Supervisor",
        "work_week": "Monday to Sunday",
        "payrule_name": "MUR_Field Staff_Regular",
        "timezone": "(UTC+4:00) Mauritius Standard Time"
    },
    {
        "location_level_1": "Mauritius",
        "location_level_2": "Le Vallon",
        "location_level_3": ["LEVALLON","NOUVELLETERRE","RAFFIA1","RAFFIA2"],
        "staff_category": "Field Staff",
        "functional_sub_segment": "BU_2",
        "employee_type": "Field Staff – Regular",
        "reg_temp": "Regular",
        "pay_type": "Salaried",
        "timesheet_period": "MUR - Weekly starting on Monday",
        "timesheet_template": "MUR_Field Staff_Regular",
        "punch_policy": "MUR_Field-Staff_Regular_Punch",
        "holiday_calendar": "MUR-Field Staff Regular & Maintenance",
        "timesheet_approval_path": "Supervisor",
        "time_off_template": "Time Off",
        "time_off_approver": "Supervisor",
        "work_week": "Monday to Sunday",
        "payrule_name": "MUR_Field Staff_Regular",
        "timezone": "(UTC+4:00) Mauritius Standard Time"
    },
    {
        "location_level_1": "Mauritius",
        "location_level_2": "Le Vallon",
        "location_level_3": ["LEVALLON","NOUVELLETERRE","RAFFIA1","RAFFIA2"],
        "staff_category": "Field Staff",
        "functional_sub_segment": "BU_3",
        "employee_type": "Field Staff – Regular",
        "reg_temp": "Regular",
        "pay_type": "Salaried",
        "timesheet_period": "MUR - Weekly starting on Monday",
        "timesheet_template": "MUR_Field Staff_Regular",
        "punch_policy": "MUR_Field-Staff_Regular_Punch",
        "holiday_calendar": "MUR-Field Staff Regular & Maintenance",
        "timesheet_approval_path": "Supervisor",
        "time_off_template": "Time Off",
        "time_off_approver": "Supervisor",
        "work_week": "Monday to Sunday",
        "payrule_name": "MUR_Field Staff_Regular",
        "timezone": "(UTC+4:00) Mauritius Standard Time"
    },
    {
        "location_level_1": "Mauritius",
        "location_level_2": "Le Vallon",
        "location_level_3": ["LEVALLON","NOUVELLETERRE","RAFFIA1","RAFFIA2"],
        "staff_category": "Field Staff",
        "functional_sub_segment": "BU_4",
        "employee_type": "Field Staff – Regular",
        "reg_temp": "Regular",
        "pay_type": "Salaried",
        "timesheet_period": "MUR - Weekly starting on Monday",
        "timesheet_template": "MUR_Field Staff_Regular",
        "punch_policy": "MUR_Field-Staff_Regular_Punch",
        "holiday_calendar": "MUR-Field Staff Regular & Maintenance",
        "timesheet_approval_path": "Supervisor",
        "time_off_template": "Time Off",
        "time_off_approver": "Supervisor",
        "work_week": "Monday to Sunday",
        "payrule_name": "MUR_Field Staff_Regular",
        "timezone": "(UTC+4:00) Mauritius Standard Time"
    },
    {
        "location_level_1": "Mauritius",
        "location_level_2": "Le Vallon",
        "location_level_3": ["LEVALLON","NOUVELLETERRE","RAFFIA1","RAFFIA2"],
        "staff_category": "Field Staff",
        "functional_sub_segment": "BU_5",
        "employee_type": "Field Staff – Regular",
        "reg_temp": "Regular",
        "pay_type": "Salaried",
        "timesheet_period": "MUR - Weekly starting on Monday",
        "timesheet_template": "MUR_Field Staff_Regular",
        "punch_policy": "MUR_Field-Staff_Regular_Punch",
        "holiday_calendar": "MUR-Field Staff Regular & Maintenance",
        "timesheet_approval_path": "Supervisor",
        "time_off_template": "Time Off",
        "time_off_approver": "Supervisor",
        "work_week": "Monday to Sunday",
        "payrule_name": "MUR_Field Staff_Regular",
        "timezone": "(UTC+4:00) Mauritius Standard Time"
    },
    {
        "location_level_1": "Mauritius",
        "location_level_2": "Le Vallon",
        "location_level_3": ["LEVALLON","NOUVELLETERRE","RAFFIA1","RAFFIA2"],
        "staff_category": "Field Staff",
        "functional_sub_segment": "BU_6",
        "employee_type": "Field Staff – Regular",
        "reg_temp": "Regular",
        "pay_type": "Salaried",
        "timesheet_period": "MUR - Weekly starting on Monday",
        "timesheet_template": "MUR_Field Staff_Regular",
        "punch_policy": "MUR_Field-Staff_Regular_Punch",
        "holiday_calendar": "MUR-Field Staff Regular & Maintenance",
        "timesheet_approval_path": "Supervisor",
        "time_off_template": "Time Off",
        "time_off_approver": "Supervisor",
        "work_week": "Monday to Sunday",
        "payrule_name": "MUR_Field Staff_Regular",
        "timezone": "(UTC+4:00) Mauritius Standard Time"
    },
    {
        "location_level_1": "Mauritius",
        "location_level_2": "Le Vallon",
        "location_level_3": ["LEVALLON","NOUVELLETERRE","RAFFIA1","RAFFIA2"],
        "staff_category": "Field Staff",
        "functional_sub_segment": "BU_7",
        "employee_type": "Field Staff – Regular",
        "reg_temp": "Regular",
        "pay_type": "Salaried",
        "timesheet_period": "MUR - Weekly starting on Monday",
        "timesheet_template": "MUR_Field Staff_Regular",
        "punch_policy": "MUR_Field-Staff_Regular_Punch",
        "holiday_calendar": "MUR-Field Staff Regular & Maintenance",
        "timesheet_approval_path": "Supervisor",
        "time_off_template": "Time Off",
        "time_off_approver": "Supervisor",
        "work_week": "Monday to Sunday",
        "payrule_name": "MUR_Field Staff_Regular",
        "timezone": "(UTC+4:00) Mauritius Standard Time"
    },
    {
        "location_level_1": "Mauritius",
        "location_level_2": "Le Vallon",
        "location_level_3": ["LEVALLON","NOUVELLETERRE","RAFFIA1","RAFFIA2"],
        "staff_category": "Field Staff",
        "functional_sub_segment": "BU_8",
        "employee_type": "Field Staff – Regular",
        "reg_temp": "Regular",
        "pay_type": "Salaried",
        "timesheet_period": "MUR - Weekly starting on Monday",
        "timesheet_template": "MUR_Field Staff_Regular",
        "punch_policy": "MUR_Field-Staff_Regular_Punch",
        "holiday_calendar": "MUR-Field Staff Regular & Maintenance",
        "timesheet_approval_path": "Supervisor",
        "time_off_template": "Time Off",
        "time_off_approver": "Supervisor",
        "work_week": "Monday to Sunday",
        "payrule_name": "MUR_Field Staff_Regular",
        "timezone": "(UTC+4:00) Mauritius Standard Time"
    },
    {
        "location_level_1": "Mauritius",
        "location_level_2": "Le Vallon",
        "location_level_3": ["LEVALLON","NOUVELLETERRE","RAFFIA1","RAFFIA2"],
        "staff_category": "Field Staff",
        "functional_sub_segment": "BU_9",
        "employee_type": "Field Staff – Regular",
        "reg_temp": "Regular",
        "pay_type": "Salaried",
        "timesheet_period": "MUR - Weekly starting on Monday",
        "timesheet_template": "MUR_Field Staff_Regular",
        "punch_policy": "MUR_Field-Staff_Regular_Punch",
        "holiday_calendar": "MUR-Field Staff Regular & Maintenance",
        "timesheet_approval_path": "Supervisor",
        "time_off_template": "Time Off",
        "time_off_approver": "Supervisor",
        "work_week": "Monday to Sunday",
        "payrule_name": "MUR_Field Staff_Regular",
        "timezone": "(UTC+4:00) Mauritius Standard Time"
    },
    {
        "location_level_1": "Mauritius",
        "location_level_2": "Le Vallon",
        "location_level_3": ["LEVALLON","NOUVELLETERRE","RAFFIA1","RAFFIA2"],
        "staff_category": "Field Staff",
        "functional_sub_segment": "BU_10",
        "employee_type": "Field Staff – Regular",
        "reg_temp": "Regular",
        "pay_type": "Salaried",
        "timesheet_period": "MUR - Weekly starting on Monday",
        "timesheet_template": "MUR_Field Staff_Regular",
        "punch_policy": "MUR_Field-Staff_Regular_Punch",
        "holiday_calendar": "MUR-Field Staff Regular & Maintenance",
        "timesheet_approval_path": "Supervisor",
        "time_off_template": "Time Off",
        "time_off_approver": "Supervisor",
        "work_week": "Monday to Sunday",
        "payrule_name": "MUR_Field Staff_Regular",
        "timezone": "(UTC+4:00) Mauritius Standard Time"
    },
    {
        "location_level_1": "Mauritius",
        "location_level_2": "Le Vallon",
        "location_level_3": ["LEVALLON","NOUVELLETERRE","RAFFIA1","RAFFIA2"],
        "staff_category": "Field Staff",
        "functional_sub_segment": "BU_11",
        "employee_type": "Field Staff – Regular",
        "reg_temp": "Regular",
        "pay_type": "Salaried",
        "timesheet_period": "MUR - Weekly starting on Monday",
        "timesheet_template": "MUR_Field Staff_Regular",
        "punch_policy": "MUR_Field-Staff_Regular_Punch",
        "holiday_calendar": "MUR-Field Staff Regular & Maintenance",
        "timesheet_approval_path": "Supervisor",
        "time_off_template": "Time Off",
        "time_off_approver": "Supervisor",
        "work_week": "Monday to Sunday",
        "payrule_name": "MUR_Field Staff_Regular",
        "timezone": "(UTC+4:00) Mauritius Standard Time"
    },
    {
        "location_level_1": "Mauritius",
        "location_level_2": "Le Vallon",
        "location_level_3": ["LEVALLON","NOUVELLETERRE","RAFFIA1","RAFFIA2"],
        "staff_category": "Field Staff",
        "functional_sub_segment": "BU_12",
        "employee_type": "Field Staff – Regular",
        "reg_temp": "Regular",
        "pay_type": "Salaried",
        "timesheet_period": "MUR - Weekly starting on Monday",
        "timesheet_template": "MUR_Field Staff_Regular",
        "punch_policy": "MUR_Field-Staff_Regular_Punch",
        "holiday_calendar": "MUR-Field Staff Regular & Maintenance",
        "timesheet_approval_path": "Supervisor",
        "time_off_template": "Time Off",
        "time_off_approver": "Supervisor",
        "work_week": "Monday to Sunday",
        "payrule_name": "MUR_Field Staff_Regular",
        "timezone": "(UTC+4:00) Mauritius Standard Time"
    },
    {
        "location_level_1": "Mauritius",
        "location_level_2": "Le Vallon",
        "location_level_3": ["LEVALLON","NOUVELLETERRE","RAFFIA1","RAFFIA2"],
        "staff_category": "Field Staff",
        "functional_sub_segment": "BU_13",
        "employee_type": "Field Staff – Regular",
        "reg_temp": "Regular",
        "pay_type": "Salaried",
        "timesheet_period": "MUR - Weekly starting on Monday",
        "timesheet_template": "MUR_Field Staff_Regular",
        "punch_policy": "MUR_Field-Staff_Regular_Punch",
        "holiday_calendar": "MUR-Field Staff Regular & Maintenance",
        "timesheet_approval_path": "Supervisor",
        "time_off_template": "Time Off",
        "time_off_approver": "Supervisor",
        "work_week": "Monday to Sunday",
        "payrule_name": "MUR_Field Staff_Regular",
        "timezone": "(UTC+4:00) Mauritius Standard Time"
    },
    {
        "location_level_1": "Mauritius",
        "location_level_2": "Le Vallon",
        "location_level_3": ["LEVALLON","NOUVELLETERRE","RAFFIA1","RAFFIA2"],
        "staff_category": "Field Staff",
        "functional_sub_segment": "BU_14",
        "employee_type": "Field Staff – Regular",
        "reg_temp": "Regular",
        "pay_type": "Salaried",
        "timesheet_period": "MUR - Weekly starting on Monday",
        "timesheet_template": "MUR_Field Staff_Regular",
        "punch_policy": "MUR_Field-Staff_Regular_Punch",
        "holiday_calendar": "MUR-Field Staff Regular & Maintenance",
        "timesheet_approval_path": "Supervisor",
        "time_off_template": "Time Off",
        "time_off_approver": "Supervisor",
        "work_week": "Monday to Sunday",
        "payrule_name": "MUR_Field Staff_Regular",
        "timezone": "(UTC+4:00) Mauritius Standard Time"
    },
    {
        "location_level_1": "Mauritius",
        "location_level_2": "Le Vallon",
        "location_level_3": ["LEVALLON","NOUVELLETERRE","RAFFIA1","RAFFIA2"],
        "staff_category": "Field Staff",
        "functional_sub_segment": "BU_15",
        "employee_type": "Field Staff – Regular",
        "reg_temp": "Regular",
        "pay_type": "Salaried",
        "timesheet_period": "MUR - Weekly starting on Monday",
        "timesheet_template": "MUR_Field Staff_Regular",
        "punch_policy": "MUR_Field-Staff_Regular_Punch",
        "holiday_calendar": "MUR-Field Staff Regular & Maintenance",
        "timesheet_approval_path": "Supervisor",
        "time_off_template": "Time Off",
        "time_off_approver": "Supervisor",
        "work_week": "Monday to Sunday",
        "payrule_name": "MUR_Field Staff_Regular",
        "timezone": "(UTC+4:00) Mauritius Standard Time"
    },
    {
        "location_level_1": "Mauritius",
        "location_level_2": "Le Vallon",
        "location_level_3": ["LEVALLON","NOUVELLETERRE","RAFFIA1","RAFFIA2"],
        "staff_category": "Field Staff",
        "functional_sub_segment": "Civil",
        "employee_type": "Field Staff – Maintenance",
        "reg_temp": "Regular",
        "pay_type": "Salaried",
        "timesheet_period": "MUR - Weekly starting on Monday",
        "timesheet_template": "MUR_Field Staff_Maintenance",
        "punch_policy": "MUR_Field-Staff_Maintanance_Punch",
        "holiday_calendar": "MUR-Field Staff Regular & Maintenance",
        "timesheet_approval_path": "Supervisor",
        "time_off_template": "Time Off",
        "time_off_approver": "Supervisor",
        "work_week": "Monday to Sunday",
        "payrule_name": "MUR_Field Staff_Maintenance",
        "timezone": "(UTC+4:00) Mauritius Standard Time"
    },
    {
        "location_level_1": "Mauritius",
        "location_level_2": "Le Vallon",
        "location_level_3": ["LEVALLON","NOUVELLETERRE","RAFFIA1","RAFFIA2"],
        "staff_category": "Field Staff",
        "functional_sub_segment": "Elec",
        "employee_type": "Field Staff – Maintenance",
        "reg_temp": "Regular",
        "pay_type": "Salaried",
        "timesheet_period": "MUR - Weekly starting on Monday",
        "timesheet_template": "MUR_Field Staff_Maintenance",
        "punch_policy": "MUR_Field-Staff_Maintanance_Punch",
        "holiday_calendar": "MUR-Field Staff Regular & Maintenance",
        "timesheet_approval_path": "Supervisor",
        "time_off_template": "Time Off",
        "time_off_approver": "Supervisor",
        "work_week": "Monday to Sunday",
        "payrule_name": "MUR_Field Staff_Maintenance",
        "timezone": "(UTC+4:00) Mauritius Standard Time"
    },
    {
        "location_level_1": "Mauritius",
        "location_level_2": "Le Vallon",
        "location_level_3": ["LEVALLON","NOUVELLETERRE","RAFFIA1","RAFFIA2"],
        "staff_category": "Field Staff",
        "functional_sub_segment": "Exp",
        "employee_type": "Field Staff – Regular",
        "reg_temp": "Regular",
        "pay_type": "Salaried",
        "timesheet_period": "MUR - Weekly starting on Monday",
        "timesheet_template": "MUR_Field Staff_Regular",
        "punch_policy": "MUR_Field-Staff_Regular_Punch",
        "holiday_calendar": "MUR-Field Staff Regular & Maintenance",
        "timesheet_approval_path": "Supervisor",
        "time_off_template": "Time Off",
        "time_off_approver": "Supervisor",
        "work_week": "Monday to Sunday",
        "payrule_name": "MUR_Field Staff_Regular",
        "timezone": "(UTC+4:00) Mauritius Standard Time"
    },
    {
        "location_level_1": "Mauritius",
        "location_level_2": "Le Vallon",
        "location_level_3": ["LEVALLON","NOUVELLETERRE","RAFFIA1","RAFFIA2"],
        "staff_category": "Field Staff",
        "functional_sub_segment": "LVS",
        "employee_type": "Field Staff – Regular",
        "reg_temp": "Regular",
        "pay_type": "Salaried",
        "timesheet_period": "MUR - Weekly starting on Monday",
        "timesheet_template": "MUR_Field Staff_Regular",
        "punch_policy": "MUR_Field-Staff_Regular_Punch",
        "holiday_calendar": "MUR-Field Staff Regular & Maintenance",
        "timesheet_approval_path": "Supervisor",
        "time_off_template": "Time Off",
        "time_off_approver": "Supervisor",
        "work_week": "Monday to Sunday",
        "payrule_name": "MUR_Field Staff_Regular",
        "timezone": "(UTC+4:00) Mauritius Standard Time"
    },
    {
        "location_level_1": "Mauritius",
        "location_level_2": "Le Vallon",
        "location_level_3": ["LEVALLON","NOUVELLETERRE","RAFFIA1","RAFFIA2"],
        "staff_category": "Field Staff",
        "functional_sub_segment": "NTS",
        "employee_type": "Field Staff – Regular",
        "reg_temp": "Regular",
        "pay_type": "Salaried",
        "timesheet_period": "MUR - Weekly starting on Monday",
        "timesheet_template": "MUR_Field Staff_Regular",
        "punch_policy": "MUR_Field-Staff_Regular_Punch",
        "holiday_calendar": "MUR-Field Staff Regular & Maintenance",
        "timesheet_approval_path": "Supervisor",
        "time_off_template": "Time Off",
        "time_off_approver": "Supervisor",
        "work_week": "Monday to Sunday",
        "payrule_name": "MUR_Field Staff_Regular",
        "timezone": "(UTC+4:00) Mauritius Standard Time"
    },
    {
        "location_level_1": "Mauritius",
        "location_level_2": "Le Vallon",
        "location_level_3": ["LEVALLON","NOUVELLETERRE","RAFFIA1","RAFFIA2"],
        "staff_category": "Field Staff",
        "functional_sub_segment": "RS_1",
        "employee_type": "Field Staff – Regular",
        "reg_temp": "Regular",
        "pay_type": "Salaried",
        "timesheet_period": "MUR - Weekly starting on Monday",
        "timesheet_template": "MUR_Field Staff_Regular",
        "punch_policy": "MUR_Field-Staff_Regular_Punch",
        "holiday_calendar": "MUR-Field Staff Regular & Maintenance",
        "timesheet_approval_path": "Supervisor",
        "time_off_template": "Time Off",
        "time_off_approver": "Supervisor",
        "work_week": "Monday to Sunday",
        "payrule_name": "MUR_Field Staff_Regular",
        "timezone": "(UTC+4:00) Mauritius Standard Time"
    },
    {
        "location_level_1": "Mauritius",
        "location_level_2": "Le Vallon",
        "location_level_3": ["LEVALLON","NOUVELLETERRE","RAFFIA1","RAFFIA2"],
        "staff_category": "Field Staff",
        "functional_sub_segment": "RS_2",
        "employee_type": "Field Staff – Regular",
        "reg_temp": "Regular",
        "pay_type": "Salaried",
        "timesheet_period": "MUR - Weekly starting on Monday",
        "timesheet_template": "MUR_Field Staff_Regular",
        "punch_policy": "MUR_Field-Staff_Regular_Punch",
        "holiday_calendar": "MUR-Field Staff Regular & Maintenance",
        "timesheet_approval_path": "Supervisor",
        "time_off_template": "Time Off",
        "time_off_approver": "Supervisor",
        "work_week": "Monday to Sunday",
        "payrule_name": "MUR_Field Staff_Regular",
        "timezone": "(UTC+4:00) Mauritius Standard Time"
    },
    {
        "location_level_1": "Mauritius",
        "location_level_2": "Le Vallon",
        "location_level_3": ["LEVALLON","NOUVELLETERRE","RAFFIA1","RAFFIA2"],
        "staff_category": "Field Staff",
        "functional_sub_segment": "Sec",
        "employee_type": "Field Staff – Security",
        "reg_temp": "Regular",
        "pay_type": "Salaried",
        "timesheet_period": "MUR - Weekly starting on Monday",
        "timesheet_template": "MUR_Field Staff_Security",
        "punch_policy": "MUR_Field-Staff_Security_Punch",
        "holiday_calendar": "MUR-Security",
        "timesheet_approval_path": "Supervisor",
        "time_off_template": "Time Off",
        "time_off_approver": "Supervisor",
        "work_week": "Monday to Sunday",
        "payrule_name": "MUR_Field Staff_Security",
        "timezone": "(UTC+4:00) Mauritius Standard Time"
    },
    {
        "location_level_1": "Mauritius",
        "location_level_2": "Le Vallon",
        "location_level_3": ["LEVALLON","NOUVELLETERRE","RAFFIA1","RAFFIA2"],
        "staff_category": "Field Staff",
        "functional_sub_segment": "Trans",
        "employee_type": "Field Staff – Regular",
        "reg_temp": "Regular",
        "pay_type": "Salaried",
        "timesheet_period": "MUR - Weekly starting on Monday",
        "timesheet_template": "MUR_Field Staff_Regular",
        "punch_policy": "MUR_Field-Staff_Regular_Punch",
        "holiday_calendar": "MUR-Field Staff Regular & Maintenance",
        "timesheet_approval_path": "Supervisor",
        "time_off_template": "Time Off",
        "time_off_approver": "Supervisor",
        "work_week": "Monday to Sunday",
        "payrule_name": "MUR_Field Staff_Regular",
        "timezone": "(UTC+4:00) Mauritius Standard Time"
    },
    {
        "location_level_1": "Mauritius",
        "location_level_2": "Le Vallon",
        "location_level_3": ["LEVALLON","NOUVELLETERRE","RAFFIA1","RAFFIA2"],
        "staff_category": "Field Staff",
        "functional_sub_segment": "Vet",
        "employee_type": "Field Staff – Regular",
        "reg_temp": "Regular",
        "pay_type": "Salaried",
        "timesheet_period": "MUR - Weekly starting on Monday",
        "timesheet_template": "MUR_Field Staff_Regular",
        "punch_policy": "MUR_Field-Staff_Regular_Punch",
        "holiday_calendar": "MUR-Field Staff Regular & Maintenance",
        "timesheet_approval_path": "Supervisor",
        "time_off_template": "Time Off",
        "time_off_approver": "Supervisor",
        "work_week": "Monday to Sunday",
        "payrule_name": "MUR_Field Staff_Regular",
        "timezone": "(UTC+4:00) Mauritius Standard Time"
    },
    {
        "location_level_1": "Mauritius",
        "location_level_2": "Le Vallon",
        "location_level_3": ["LEVALLON","NOUVELLETERRE","RAFFIA1","RAFFIA2"],
        "staff_category": "Field Staff",
        "functional_sub_segment": "Trap",
        "employee_type": "Field Staff – Regular",
        "reg_temp": "Regular",
        "pay_type": "Salaried",
        "timesheet_period": "MUR - Weekly starting on Monday",
        "timesheet_template": "MUR_Field Staff_Regular",
        "punch_policy": "MUR_Field-Staff_Regular_Punch",
        "holiday_calendar": "MUR-Field Staff Regular & Maintenance",
        "timesheet_approval_path": "Supervisor",
        "time_off_template": "Time Off",
        "time_off_approver": "Supervisor",
        "work_week": "Monday to Sunday",
        "payrule_name": "MUR_Field Staff_Regular",
        "timezone": "(UTC+4:00) Mauritius Standard Time"
    }
]
