region = 'eu-central-1'
environment = 'production'
instance = "GE"
company_key = 'GE'
replicon_conn_id = 'ge_replicon_admin'
pgp_conn_id = 'ge_pgp_replicon'
can_run_batch_task_var_name = f'GE_user_import_can_run_batch_task_{instance}'
sftp_conn_id = "ge_sftp_lg790231sd"
internal_sftp_conn_id = "ge_sftp_587719"
input_filepath = "/EUROPE/NETHERLANDS/WORKDAY/PROD/FROMGE"
archive_filepath = "/EUROPE/NETHERLANDS/WORKDAY/PROD/FROMGE/ARCHIVE"
internal_archive_filepath = "/User Sync/Netherlands/Daily Files"
log_filepath = "/User Sync/Netherlands/Logs"
execution_timeout_days = 14
child_dag_max_active_runs = 5
master_dag_interval = 30
tenant_email = '{{ var.value.dagrun_internal_log_email }}'
internal_logs_email = '{{ var.value.dagrun_internal_log_email }}'
alert_email = '{{ var.value.dagrun_failure_alert_email }}'
pacific_timezone = 'US/Pacific'
