company_key = 'dxctrial01'
replicon_conn_id = 'dxctrial01'
sftp_conn_id = 'repliconsftp'
input_filepath = '/Production/Inbound/C1IWOLeanstaff/FilesToProcess'
tenant_email = '{{ var.value.dagrun_internal_testing_email }}'
internal_logs_email = '{{ var.value.dagrun_internal_testing_email }}'
alert_email = '{{ var.value.dagrun_internal_testing_email }}'
archive_filepath = '/Production/Inbound/C1IWOLeanstaff/Archive'
child_dag_id_create_billing_rates = "dxctechnology_c1_iwo_leanstaffing_child_create_billing_rate"
child_dag_create_billing_rate_max_active_runs = 10
child_dag_leanstaffing_automation_child_runs = 10
child_dag_leanstaffing_process_each_record_runs = 10
extract_report_name = '**C1 Lean staffing Import base report'
log_filepath = '/Production/Inbound/C1IWOLeanstaff/Logs'
region = 'us-east-2'
environment = 'pre-production'
execution_timeout_days = 14
max_active_parallel_runs_child = 10
