null = None
timeoff_project_task_mapper = {
    "Bereavement": {
        "ps_project_code": "911405",
        "ps_task_code": "001",
        "cp_project_code": "LEAVE1",
        "cp_task_code": "LEAVE1.00.0000.BERV",
        "fmla_ps_project_code": null,
        "fmla_ps_task_code": null,
        "fmla_cp_project_code": null,
        "fmla_cp_task_code": null,
        "replicon_pay_code": "BER",
    },
    "Caregiver Leave": {
        "ps_project_code": "913110",
        "ps_task_code": "006",
        "cp_project_code": "LEAVE1",
        "cp_task_code": "LEAVE1.00.0000.CARE",
        "fmla_ps_project_code": null,
        "fmla_ps_task_code": null,
        "fmla_cp_project_code": null,
        "fmla_cp_task_code": null,
        "replicon_pay_code": "CAR",
    },
    "Holiday": {
        "ps_project_code": "911310",
        "ps_task_code": "001",
        "cp_project_code": "LEAVE1",
        "cp_task_code": "LEAVE1.00.0000.HOLI",
        "fmla_ps_project_code": null,
        "fmla_ps_task_code": null,
        "fmla_cp_project_code": null,
        "fmla_cp_task_code": null,
        "replicon_pay_code": "HOL",
    },
    "Jury Duty": {
        "ps_project_code": "911400",
        "ps_task_code": "002",
        "cp_project_code": "LEAVE1",
        "cp_task_code": "LEAVE1.00.0000.JURY",
        "fmla_ps_project_code": null,
        "fmla_ps_task_code": null,
        "fmla_cp_project_code": null,
        "fmla_cp_task_code": null,
        "replicon_pay_code": "JUR",
    },
    "Lost Time - Weather/NAT disaster": {
        "ps_project_code": "913100",
        "ps_task_code": "001",
        "cp_project_code": "LEAVE1",
        "cp_task_code": "LEAVE1.00.0000.LOST",
        "fmla_ps_project_code": null,
        "fmla_ps_task_code": null,
        "fmla_cp_project_code": null,
        "fmla_cp_task_code": null,
        "replicon_pay_code": "LOS",
    },
    "Lost Time - Internet/Electricity Outage": {
        "ps_project_code": "913100",
        "ps_task_code": "002",
        "cp_project_code": "LEAVE1",
        "cp_task_code": "LEAVE1.00.0000.LOST",
        "fmla_ps_project_code": null,
        "fmla_ps_task_code": null,
        "fmla_cp_project_code": null,
        "fmla_cp_task_code": null,
        "replicon_pay_code": "LOS",
    },
    "Parental Leave": {
        "ps_project_code": "911500",
        "ps_task_code": "002",
        "cp_project_code": "LEAVE1",
        "cp_task_code": "LEAVE1.00.0000.MATN",
        "fmla_ps_project_code": null,
        "fmla_ps_task_code": null,
        "fmla_cp_project_code": null,
        "fmla_cp_task_code": null,
        "replicon_pay_code": "MAT",
    },
    "Voting Leave": {
        "ps_project_code": "911400",
        "ps_task_code": "005",
        "cp_project_code": "LEAVE1",
        "cp_task_code": "LEAVE1.00.0000.VOTE",
        "fmla_ps_project_code": null,
        "fmla_ps_task_code": null,
        "fmla_cp_project_code": null,
        "fmla_cp_task_code": null,
        "replicon_pay_code": "VOT",
    },
    "Military Leave": {
        "ps_project_code": "911400",
        "ps_task_code": "003",
        "cp_project_code": "LEAVE1",
        "cp_task_code": "LEAVE1.00.0000.MILI",
        "fmla_ps_project_code": null,
        "fmla_ps_task_code": null,
        "fmla_cp_project_code": null,
        "fmla_cp_task_code": null,
        "replicon_pay_code": "MIL",
    },
    "Unpaid Administrative Leave": {
        "ps_project_code": "913000",
        "ps_task_code": "006",
        "cp_project_code": "LEAVE1",
        "cp_task_code": "LEAVE1.00.0000.ADUP",
        "fmla_ps_project_code": null,
        "fmla_ps_task_code": null,
        "fmla_cp_project_code": null,
        "fmla_cp_task_code": null,
        "replicon_pay_code": "GTO",
    },
    "Unpaid Leave": {
        "ps_project_code": "912000",
        "ps_task_code": "004",
        "cp_project_code": "LEAVE1",
        "cp_task_code": "LEAVE1.00.0000.LWOP",
        "fmla_ps_project_code": null,
        "fmla_ps_task_code": null,
        "fmla_cp_project_code": null,
        "fmla_cp_task_code": null,
        "replicon_pay_code": "LWP",
    },
    "Administrative Leave (paid)": {
        "ps_project_code": "913100",
        "ps_task_code": "001",
        "cp_project_code": "LEAVE1",
        "cp_task_code": "LEAVE1.00.0000.ADMN",
        "fmla_ps_project_code": null,
        "fmla_ps_task_code": null,
        "fmla_cp_project_code": null,
        "fmla_cp_task_code": null,
        "replicon_pay_code": "GTO",
    },
    "[CAN] Sick": {
        "ps_project_code": "ONLTIL",
        "ps_task_code": "003",
        "cp_project_code": null,
        "cp_task_code": null,
        "fmla_ps_project_code": null,
        "fmla_ps_task_code": null,
        "fmla_cp_project_code": null,
        "fmla_cp_task_code": null,
        "replicon_pay_code": "SIC",
    },
    "[CAN] STD": {
        "ps_project_code": "ONLTIL",
        "ps_task_code": "002",
        "cp_project_code": null,
        "cp_task_code": null,
        "fmla_ps_project_code": null,
        "fmla_ps_task_code": null,
        "fmla_cp_project_code": null,
        "fmla_cp_task_code": null,
        "replicon_pay_code": "STD",
    },
    "[CAN] Unpaid": {
        "ps_project_code": "ONLTIL",
        "ps_task_code": "001",
        "cp_project_code": null,
        "cp_task_code": null,
        "fmla_ps_project_code": null,
        "fmla_ps_task_code": null,
        "fmla_cp_project_code": null,
        "fmla_cp_task_code": null,
        "replicon_pay_code": "LWP",
    },
    "[USA] STD": {
        "ps_project_code": "911500",
        "ps_task_code": "001",
        "cp_project_code": "LEAVE1",
        "cp_task_code": "LEAVE1.00.0000.STDY",
        "fmla_ps_project_code": null,
        "fmla_ps_task_code": null,
        "fmla_cp_project_code": null,
        "fmla_cp_task_code": null,
        "replicon_pay_code": "STD",
    },
    "[USA] Sick SCA": {
        "ps_project_code": "911200",
        "ps_task_code": "997",
        "cp_project_code": "LEAVE1",
        "cp_task_code": "LEAVE1.00.0000.SICK",
        "fmla_ps_project_code": "913110",
        "fmla_ps_task_code": "004",
        "fmla_cp_project_code": "LEAVE1",
        "fmla_cp_task_code": "LEAVE1.00.0000.FML1",
        "replicon_pay_code": "SIC",
    },
    "[USA] Sick Intern": {
        "ps_project_code": "911200",
        "ps_task_code": "997",
        "cp_project_code": "LEAVE1",
        "cp_task_code": "LEAVE1.00.0000.SICK",
        "fmla_ps_project_code": "913110",
        "fmla_ps_task_code": "004",
        "fmla_cp_project_code": "LEAVE1",
        "fmla_cp_task_code": "LEAVE1.00.0000.FML1",
        "replicon_pay_code": "SIC",
    },
    "DTO": {
        "ps_project_code": "911100",
        "ps_task_code": "002",
        "cp_project_code": "LEAVE1",
        "cp_task_code": "LEAVE1.00.0000.DTOO",
        "fmla_ps_project_code": null,
        "fmla_ps_task_code": null,
        "fmla_cp_project_code": null,
        "fmla_cp_task_code": null,
        "replicon_pay_code": "DTO",
    },
    "[USA] PTO": {
        "ps_project_code": "911100",
        "ps_task_code": "001",
        "cp_project_code": "LEAVE1",
        "cp_task_code": "LEAVE1.00.0000.PTOO",
        "fmla_ps_project_code": "913110",
        "fmla_ps_task_code": "004",
        "fmla_cp_project_code": "LEAVE1",
        "fmla_cp_task_code": "LEAVE1.00.0000.FML2",
        "replicon_pay_code": "PTO",
    },
    "[USA] PTO Intern": {
        "ps_project_code": "911100",
        "ps_task_code": "001",
        "cp_project_code": "LEAVE1",
        "cp_task_code": "LEAVE1.00.0000.PTOO",
        "fmla_ps_project_code": null,
        "fmla_ps_task_code": null,
        "fmla_cp_project_code": null,
        "fmla_cp_task_code": null,
        "replicon_pay_code": "PTO",
    },
    "[USA] SCA Vacation": {
        "ps_project_code": "911100",
        "ps_task_code": "001",
        "cp_project_code": "LEAVE1",
        "cp_task_code": "LEAVE1.00.0000.PTOO",
        "fmla_ps_project_code": "913110",
        "fmla_ps_task_code": "004",
        "fmla_cp_project_code": "LEAVE1",
        "fmla_cp_task_code": "LEAVE1.00.0000.FML2",
        "replicon_pay_code": "PTO",
    },
    "[USA] Sick": {
        "ps_project_code": "911200",
        "ps_task_code": "997",
        "cp_project_code": "LEAVE1",
        "cp_task_code": "LEAVE1.00.0000.SICK",
        "fmla_ps_project_code": "913110",
        "fmla_ps_task_code": "004",
        "fmla_cp_project_code": "LEAVE1",
        "fmla_cp_task_code": "LEAVE1.00.0000.FML1",
        "replicon_pay_code": "SIC",
    },
    "[USA] Sick NE": {
        "ps_project_code": "911200",
        "ps_task_code": "997",
        "cp_project_code": "LEAVE1",
        "cp_task_code": "LEAVE1.00.0000.SICK",
        "fmla_ps_project_code": null,
        "fmla_ps_task_code": null,
        "fmla_cp_project_code": null,
        "fmla_cp_task_code": null,
        "replicon_pay_code": "SIC",
    },
    "[USA] Floating Holiday": {
        "ps_project_code": "911300",
        "ps_task_code": "002",
        "cp_project_code": "LEAVE1",
        "cp_task_code": "LEAVE1.00.0000.FHOL",
        "fmla_ps_project_code": null,
        "fmla_ps_task_code": null,
        "fmla_cp_project_code": null,
        "fmla_cp_task_code": null,
        "replicon_pay_code": "FHO",
    },
    "[IND] Privilege Leave": {
        "ps_project_code": "911100",
        "ps_task_code": "001",
        "cp_project_code": null,
        "cp_task_code": null,
        "fmla_ps_project_code": null,
        "fmla_ps_task_code": null,
        "fmla_cp_project_code": null,
        "fmla_cp_task_code": null,
        "replicon_pay_code": "PTO",
    },
    "[IND] Sick": {
        "ps_project_code": "911200",
        "ps_task_code": "997",
        "cp_project_code": null,
        "cp_task_code": null,
        "fmla_ps_project_code": null,
        "fmla_ps_task_code": null,
        "fmla_cp_project_code": null,
        "fmla_cp_task_code": null,
        "replicon_pay_code": "SIC",
    },
    "[NLD] Vacation": {
        "ps_project_code": "911100",
        "ps_task_code": "001",
        "cp_project_code": null,
        "cp_task_code": null,
        "fmla_ps_project_code": null,
        "fmla_ps_task_code": null,
        "fmla_cp_project_code": null,
        "fmla_cp_task_code": null,
        "replicon_pay_code": "PTO",
    },
    "[NLD] Vacation Non-Stat": {
        "ps_project_code": "911100",
        "ps_task_code": "001",
        "cp_project_code": null,
        "cp_task_code": null,
        "fmla_ps_project_code": null,
        "fmla_ps_task_code": null,
        "fmla_cp_project_code": null,
        "fmla_cp_task_code": null,
        "replicon_pay_code": "PTO",
    },
    "[LTU] Vacation": {
        "ps_project_code": "911100",
        "ps_task_code": "001",
        "cp_project_code": null,
        "cp_task_code": null,
        "fmla_ps_project_code": null,
        "fmla_ps_task_code": null,
        "fmla_cp_project_code": null,
        "fmla_cp_task_code": null,
        "replicon_pay_code": "PTO",
    },
    "[GBR] Annual Leave": {
        "ps_project_code": "911100",
        "ps_task_code": "001",
        "cp_project_code": null,
        "cp_task_code": null,
        "fmla_ps_project_code": null,
        "fmla_ps_task_code": null,
        "fmla_cp_project_code": null,
        "fmla_cp_task_code": null,
        "replicon_pay_code": "PTO",
    },
    "[GER] Annual Leave": {
        "ps_project_code": "911100",
        "ps_task_code": "001",
        "cp_project_code": null,
        "cp_task_code": null,
        "fmla_ps_project_code": null,
        "fmla_ps_task_code": null,
        "fmla_cp_project_code": null,
        "fmla_cp_task_code": null,
        "replicon_pay_code": "PTO",
    },
    "[GBR] Annual Leave Student": {
        "ps_project_code": "911100",
        "ps_task_code": "001",
        "cp_project_code": null,
        "cp_task_code": null,
        "fmla_ps_project_code": null,
        "fmla_ps_task_code": null,
        "fmla_cp_project_code": null,
        "fmla_cp_task_code": null,
        "replicon_pay_code": "PTO",
    },
    "[FRA] Annual Leave": {
        "ps_project_code": "911100",
        "ps_task_code": "001",
        "cp_project_code": null,
        "cp_task_code": null,
        "fmla_ps_project_code": null,
        "fmla_ps_task_code": null,
        "fmla_cp_project_code": null,
        "fmla_cp_task_code": null,
        "replicon_pay_code": "PTO",
    },
    "[FRA] RTT": {
        "ps_project_code": "911510",
        "ps_task_code": "004",
        "cp_project_code": null,
        "cp_task_code": null,
        "fmla_ps_project_code": null,
        "fmla_ps_task_code": null,
        "fmla_cp_project_code": null,
        "fmla_cp_task_code": null,
        "replicon_pay_code": "PTO",
    },
    "[EMEA] Parental Leave": {
        "ps_project_code": "911525",
        "ps_task_code": "001",
        "cp_project_code": null,
        "cp_task_code": null,
        "fmla_ps_project_code": null,
        "fmla_ps_task_code": null,
        "fmla_cp_project_code": null,
        "fmla_cp_task_code": null,
        "replicon_pay_code": "MAT",
    },
    "[EMEA] Maternity Leave": {
        "ps_project_code": "911520",
        "ps_task_code": "001",
        "cp_project_code": null,
        "cp_task_code": null,
        "fmla_ps_project_code": null,
        "fmla_ps_task_code": null,
        "fmla_cp_project_code": null,
        "fmla_cp_task_code": null,
        "replicon_pay_code": "MAT",
    },
    "[EMEA] Special Leave": {
        "ps_project_code": "911510",
        "ps_task_code": "002",
        "cp_project_code": null,
        "cp_task_code": null,
        "fmla_ps_project_code": null,
        "fmla_ps_task_code": null,
        "fmla_cp_project_code": null,
        "fmla_cp_task_code": null,
        "replicon_pay_code": null,
    },
    "[GER] Pay in lieu": {
        "ps_project_code": "911600",
        "ps_task_code": "997",
        "cp_project_code": null,
        "cp_task_code": null,
        "fmla_ps_project_code": null,
        "fmla_ps_task_code": null,
        "fmla_cp_project_code": null,
        "fmla_cp_task_code": null,
        "replicon_pay_code": null,
    },
     "[CAN] Floating Holiday": {
        "ps_project_code": "911300",
        "ps_task_code": "002",
        "cp_project_code": "LEAVE1",
        "cp_task_code": "LEAVE1.00.0000.FHOL",
        "fmla_ps_project_code": null,
        "fmla_ps_task_code": null,
        "fmla_cp_project_code": null,
        "fmla_cp_task_code": null,
        "replicon_pay_code": "FHO",
    },
     "[GBR] Floating Holiday": {
        "ps_project_code": "911300",
        "ps_task_code": "002",
        "cp_project_code": "LEAVE1",
        "cp_task_code": "LEAVE1.00.0000.FHOL",
        "fmla_ps_project_code": null,
        "fmla_ps_task_code": null,
        "fmla_cp_project_code": null,
        "fmla_cp_task_code": null,
        "replicon_pay_code": "FHO",
    },
}
