from datetime import datetime as dt

null = None

def get_compose_item_payout_data_row(items):
    return [
        "P2010",
        items['empid'],
        "US",
        "000",
        "INS",
        "2010",
        items['paycode'],
        dt.strptime(items['user_start_date'], "%b %d, %Y").strftime("%Y%m%d") if items['user_start_date'] else "",
        dt.strptime(items['user_end_date'], "%b %d, %Y").strftime("%Y%m%d") if items['user_end_date'] else "",
        "",
        "",
        "000",
        "",
        items['paycode'],
        "",
        "",
        "",
        "",
        "USD",
        items['timeoff_balance'],
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
    ]
