# pylint: disable=wildcard-import unused-wildcard-import
from assuredpartnersinc.user_import_v3.config import *
from assuredpartnersinc.user_import_v3.mappers.assuredpartners_user_sync_master_mapper import assuredpartners_user_sync_master_mapper
from assuredpartnersinc.user_import_v3.mappers.assuredpartners_time_off_policy_mapper_for_sick_pay_p import assuredpartners_time_off_policy_mapper_for_sick_pay_p
from assuredpartnersinc.user_import_v3.mappers.assuredpartners_time_off_policy_mapper import assuredpartners_time_off_policy_mapper
from assuredpartnersinc.user_import_v3.mappers.assuredpartners_pto_1_time_off_mapper import assured_partners_pto_1_time_off_mapper

instance = 'trial'
environment = 'pre-production'

version = 'v3'

company_key = 'AssuredPartnersinctrial03'

replicon_conn_id = 'assuredpartnersinctrial03_radmin'
sftp_conn_id = 'sftp_useast2'

deltavariance_percentage = f"assuredpartners_user_import_deltavariance_percentage_{instance}"

sftp_input_filepath = '/assuredpartners/user_import/input'
sftp_input_override_filepath = '/assuredpartners/user_import/Override'
sftp_reference_filepath = '/assuredpartners/user_import/reference'
sftp_archive_filepath = '/assuredpartners/user_import/archive'
sftp_logs_filepath = '/assuredpartners/user_import/logs'
sftp_change_filepath = '/assuredpartners/user_import/changefile'

tenant_email = '{{ var.value.dagrun_internal_testing_email }}'
internal_logs_email = '{{ var.value.dagrun_internal_testing_email }}'
alert_email = '{{ var.value.dagrun_failure_alert_email }}'

MASTER_MAPPER = assuredpartners_user_sync_master_mapper
TO_POLICY_MAPPER = assuredpartners_time_off_policy_mapper
TO_SICK_PAY_P_MAPPER = assuredpartners_time_off_policy_mapper_for_sick_pay_p
TO_PTO1_MAPPER = assured_partners_pto_1_time_off_mapper

can_run_batch_task_var_name = f"assuredpartners_user_import_can_run_batch_task_{instance}"

master_dag_id = f'assuredpartnersinc_user_import_master_{instance}_{version}'
master_override_dag_id = f'assuredpartnersinc_user_import_master_override_{instance}_{version}'
process_each_user_dag_id = f'assuredpartnersinc_user_import_process_each_user_{instance}_{version}'
child_groups_update_dag_id = f'assuredpartnersinc_user_import_groups_update_child_{instance}_{version}'
child_cost_center_add_dag_id = f'assuredpartnersinc_user_import_cost_center_add_child_{instance}_{version}'
child_department_add_dag_id = f'assuredpartnersinc_user_import_department_add_child_{instance}_{version}'
child_location_add_dag_id = f'assuredpartnersinc_user_import_location_add_child_{instance}_{version}'
child_employee_type_add_dag_id = f'assuredpartnersinc_user_import_employee_type_add_child_{instance}_{version}'
child_division_add_dag_id = f'assuredpartnersinc_user_import_division_add_child_{instance}_{version}'
child_service_center_add_dag_id = f'assuredpartnersinc_user_import_service_center_add_child_{instance}_{version}'
child_office_schedule_add_dag_id = f'assuredpartnersinc_user_import_office_schedule_add_child_{instance}_{version}'
child_update_user_dag_id = f'assuredpartnersinc_user_import_update_user_child_{instance}_{version}'
child_add_user_dag_id = f'assuredpartnersinc_user_import_add_user_child_{instance}_{version}'

child_add_supervisor_dag_id = f'assuredpartnersinc_user_import_add_supervisor_child_{instance}_{version}'
child_payroll_and_admin_permission_add_update_dag_id = f'assuredpartnersinc_user_import_payroll_and_admin_permission_add_update_child_{instance}_{version}'
child_workflow_to_add_timeoff_type_for_new_user_dag_id = f'assuredpartnersinc_user_import_workflow_to_add_timeoff_type_for_new_user_child_{instance}_{version}'
child_activity_assignment_dag_id = f'assuredpartnersinc_user_import_activity_assignment_child_{instance}_{version}'
child_new_user_sick_pay_h_policy_assignment_dag_id = f'assuredpartnersinc_user_import_new_user_sick_pay_h_policy_assignment_child_{instance}_{version}'
child_new_user_timeoff_type_default_assignment_dag_id = f'assuredpartnersinc_user_import_new_user_timeoff_type_default_assignment_child_{instance}_{version}'
child_new_user_timeoff_type_proration_assignment_ap_pto_h_and_ahm_plan_h_and_seattle_plan_h_dag_id = f'assuredpartnersinc_user_import_new_user_ap_pto_and_ahm_plan_and_seattle_plan_assignment_child_{instance}_{version}'
child_new_user_timeoff_type_proration_assignment_keenan_non_ca_h_keenan_non_ca_ex_dag_id = f'assuredpartnersinc_user_import_new_user_keenan_non_ca_assignment_child_{instance}_{version}'
child_new_user_timeoff_type_proration_assignment_keennan_h_neace_special_h_and_ap_ca_plan_h_dag_id = f'assuredpartnersinc_user_import_new_user_keennan_neace_and_ap_ca_plan_assignment_child_{instance}_{version}'
child_new_user_timeoff_type_proration_assignment_sick_pay_p_dag_id = f'assuredpartnersinc_user_import_new_user_sick_pay_p_assignment_child_{instance}_{version}'

child_loa_logic_dag_id = f'assuredpartnersinc_user_import_loa_logic_child_{instance}_{version}'

child_update_timeoff_type_for_seniority_date_dag_id = f'assuredpartnersinc_user_import_update_timeoff_type_for_seniority_date_child_{instance}_{version}'
child_rehire_transfer_user_timeoff_type_proration_assignment_ap_pto_h_and_ahm_plan_h_and_seattle_plan_h_dag_id = f'assuredpartnersinc_user_import_rehire_transfer_user_ap_pto_and_ahm_plan_and_seattle_plan_assignment_child_{instance}_{version}'
child_rehire_transfer_user_timeoff_type_proration_assignment_keennan_h_neace_special_h_and_ap_ca_plan_h_dag_id = f'assuredpartnersinc_user_import_rehire_transfer_user_keennan_neace_and_ap_ca_plan_assignment_child_{instance}_{version}'
child_user_timeoff_policy_update_for_start_date_update_time_off_types_dag_id = f'assuredpartnersinc_user_import_user_timeoff_policy_update_for_start_date_update_time_off_types_child_{instance}_{version}'

child_workflow_timeoff_type_for_disable_user_dag_id = f'assuredpartnersinc_user_import_timeoff_type_for_disable_user_child_{instance}_{version}'
child_remove_future_timeoff_policies_transfer_termination_dag_id = f'assuredpartnersinc_user_import_remove_future_timeoff_policies_transfer_termination_child_{instance}_{version}'
child_transfer_pto_balance_to_pto_payout_termination_dag_id = f'assuredpartnersinc_user_import_transfer_pto_balance_to_pto_payout_termination_child_{instance}_{version}'

child_workflow_to_add_timeoff_type_for_rehire_dag_id = f'assuredpartnersinc_user_import_add_timeoff_type_for_rehire_child_{instance}_{version}'
child_rehire_transfer_user_timeoff_policy_assignment_for_non_pto1_time_off_types_dag_id = f'assuredpartnersinc_user_import_rehire_transfer_user_for_non_pto1_time_off_types_assignment_child_{instance}_{version}'
child_rehire_transfer_user_timeoff_type_proration_assignment_keenan_non_ca_h_keenan_non_ca_ex_dag_id = f'assuredpartnersinc_user_import_rehire_transfer_user_keenan_non_ca_assignment_child_{instance}_{version}'
child_update_rehire_user_timeoff_type_proration_assignment_sick_pay_p_dag_id = f'assuredpartnersinc_user_import_update_rehire_user_sick_pay_p_assignment_child_{instance}_{version}'

child_workflow_to_add_timeoff_type_for_transfer_dag_id = f'assuredpartnersinc_user_import_add_timeoff_type_for_transfer_child_{instance}_{version}'
child_update_sick_pay_h_policy_on_ineligibity_dag_id = f'assuredpartnersinc_user_import_update_sick_pay_h_policy_on_ineligibity_child_{instance}_{version}'
child_update_pto_policy_on_loa_dag_id = f'assuredpartnersinc_user_import_update_pto_policy_on_loa_child_{instance}_{version}'
child_update_sick_pay_h_policy_on_loa_dag_id = f'assuredpartnersinc_user_import_update_sick_pay_h_policy_on_loa_child_{instance}_{version}'
child_user_sick_pay_h_policy_update_dag_id = f'assuredpartnersinc_user_import_user_sick_pay_h_policy_update_child_{instance}_{version}'
child_workflow_for_change_in_schedule_and_pto_1_policy_update_dag_id = f'assuredpartnersinc_user_import_workflow_for_change_in_schedule_and_pto_1_policy_update_child_{instance}_{version}'

disabled = True
