region = 'eu-central-1'
environment = 'pre-production'
instance = "GEtrial02"
company_key = 'GEtrial02'
replicon_conn_id = 'GEtrial02_User_Import'
pgp_conn_id = 'GEtrial02_User_Import_PGP'
can_run_batch_task_var_name = f'GEtrial02_user_import_can_run_batch_task_{instance}'
sftp_conn_id = "GEtrial02_sftp_lg790231sd"
internal_sftp_conn_id = "GEtrial02_sftp_587719"
input_filepath = "/EUROPE/PORTUGAL/WORKDAY/TEST/FROMGE"
archive_filepath = "/EUROPE/PORTUGAL/WORKDAY/TEST/FROMGE/ARCHIVE"
internal_archive_filepath = "/TRIAL/User Sync/Portugal/Daily Files/"
log_filepath = "/TRIAL/User Sync/Portugal/Logs/"
execution_timeout_days = 14
child_dag_max_active_runs = 2
master_dag_interval = 600
tenant_email = 'mark.mcdonagh@ge.com'
internal_logs_email = '{{ var.value.dagrun_internal_testing_email }}'
alert_email = '{{ var.value.dagrun_failure_alert_email }}'
pacific_timezone = 'US/Pacific'
