"""
iPipeline User Import - Assignment Rules Mapper

Complete assignment rules matrix from Excel file with proper include/exclude list handling.
All 30 rules with activities stored as Python lists and exact Excel values preserved.

INCLUDE/EXCLUDE LIST LOGIC:
==========================

Field Structure:
- location_level_1: Exact match required (US, UK, Canada, Japan)
- location_level_2_to_include: List of locations to include (empty = match all)
- location_level_2_to_exclude: List of locations to exclude (empty = exclude "")
- department_1_to_include: List of departments to include (empty = match all)
- department_1_to_exclude: List of departments to exclude (empty = exclude "")  
- employee_category_to_include: List of categories to include (empty = match all)
- employee_category_to_exclude: List of categories to exclude (empty = exclude "")
- activities: Always stored as Python list (never strings with newlines)

Matching Logic:
- Empty include list = "match all values"
- Empty exclude list = "exclude nothing" 
- If include list has values, actual value MUST be in include list
- If exclude list has values, actual value must NOT be in exclude list
- Both lists can be used together for complex matching scenarios
"""

# Complete Assignment Rules Matrix - ALL 30 rules with exact Excel values
ASSIGNMENT_RULES_MAPPER = [
    {
        "location_level_1": "United States",
        "location_level_2_to_include": [],
        "location_level_2_to_exclude": [],
        "department_1_to_include": ["Pro Services"],
        "department_1_to_exclude": [],
        "employee_category_to_include": [],
        "employee_category_to_exclude": [],
        "payrule": "US Payrule",
        "timesheet_period": "Weekly without crossing months",
        "schedule_type": "Office Schedule",
        "work_week": "Monday-Sunday",
        "timesheet_template": "Standard Billable Template",
        "time_entry_approval_path": "iPipeline B Project Manager",
        "timesheet_approval_path": "iPipeline B Supervisor",
        "time_off_template": "iPipeline US",
        "time_off_approval": "iPipeline US",
        "holiday_calendar": "Holiday US",
        "activities": [],
        "timesheet_and_time_entry_notification": "Enable"
    },
    {
        "location_level_1": "United States",
        "location_level_2_to_include": [],
        "location_level_2_to_exclude": [],
        "department_1_to_include": [],
        "department_1_to_exclude": ["Pro Services", "Support", "R&D", "Network Operations"],
        "employee_category_to_include": ["Hourly"],
        "employee_category_to_exclude": [],
        "payrule": "US Payrule",
        "timesheet_period": "Weekly without crossing months",
        "schedule_type": "Office Schedule",
        "work_week": "Monday-Sunday",
        "timesheet_template": "Standard Billable Template",
        "time_entry_approval_path": "iPipeline B Project Manager",
        "timesheet_approval_path": "iPipeline B Supervisor",
        "time_off_template": "iPipeline US",
        "time_off_approval": "iPipeline US",
        "holiday_calendar": "Holiday US",
        "activities": [],
        "timesheet_and_time_entry_notification": "Enable"
    },
    {
        "location_level_1": "United States",
        "location_level_2_to_include": [],
        "location_level_2_to_exclude": [],
        "department_1_to_include": [],
        "department_1_to_exclude": ["Pro Services", "Support", "R&D", "Network Operations"],
        "employee_category_to_include": ["Salaried"],
        "employee_category_to_exclude": [],
        "payrule": "US Payrule",
        "timesheet_period": "Weekly without crossing months",
        "schedule_type": "Office Schedule",
        "work_week": "Monday-Sunday",
        "timesheet_template": "Standard Non-Billable Template",
        "time_entry_approval_path": "iPipeline NB Project Manager",
        "timesheet_approval_path": "iPipeline NB Supervisor",
        "time_off_template": "iPipeline US",
        "time_off_approval": "iPipeline US",
        "holiday_calendar": "Holiday US",
        "activities": [],
        "timesheet_and_time_entry_notification": "Disable"
    },
    {
        "location_level_1": "United States",
        "location_level_2_to_include": [],
        "location_level_2_to_exclude": [],
        "department_1_to_include": ["Support"],
        "department_1_to_exclude": [],
        "employee_category_to_include": ["Hourly"],
        "employee_category_to_exclude": [],
        "payrule": "US Payrule",
        "timesheet_period": "Weekly without crossing months",
        "schedule_type": "Shift Schedule",
        "work_week": "Monday-Sunday",
        "timesheet_template": "On Call Billable Template US",
        "time_entry_approval_path": "iPipeline B Project Manager",
        "timesheet_approval_path": "iPipeline B Supervisor",
        "time_off_template": "iPipeline US",
        "time_off_approval": "iPipeline US",
        "holiday_calendar": "Holiday US",
        "activities": ["Support - Flex On-call (01)", "Support - Other On Call (02)", "Support - Rotation On-call (04)", "Network Operations On Call (07)"],
        "timesheet_and_time_entry_notification": "Enable"
    },
    {
        "location_level_1": "United States",
        "location_level_2_to_include": [],
        "location_level_2_to_exclude": [],
        "department_1_to_include": ["Support"],
        "department_1_to_exclude": [],
        "employee_category_to_include": ["Salaried"],
        "employee_category_to_exclude": [],
        "payrule": "US Payrule",
        "timesheet_period": "Weekly without crossing months",
        "schedule_type": "Shift Schedule",
        "work_week": "Monday-Sunday",
        "timesheet_template": "On Call Non-Billable Template US",
        "time_entry_approval_path": "iPipeline NB Project Manager",
        "timesheet_approval_path": "iPipeline NB Supervisor",
        "time_off_template": "iPipeline US",
        "time_off_approval": "iPipeline US",
        "holiday_calendar": "Holiday US",
        "activities": ["Support - Flex On-call (01)", "Support - Other On Call (02)", "Support - Rotation On-call (04)", "Network Operations On Call (07)"],
        "timesheet_and_time_entry_notification": "Disable"
    },
    {
        "location_level_1": "United States",
        "location_level_2_to_include": [],
        "location_level_2_to_exclude": [],
        "department_1_to_include": ["Research & Development"],
        "department_1_to_exclude": [],
        "employee_category_to_include": ["Hourly"],
        "employee_category_to_exclude": [],
        "payrule": "US Payrule",
        "timesheet_period": "Weekly without crossing months",
        "schedule_type": "Shift Schedule",
        "work_week": "Monday-Sunday",
        "timesheet_template": "On Call Billable Template US",
        "time_entry_approval_path": "iPipeline B Project Manager",
        "timesheet_approval_path": "iPipeline B Supervisor",
        "time_off_template": "iPipeline US",
        "time_off_approval": "iPipeline US",
        "holiday_calendar": "Holiday US",
        "activities": ["Support - Flex On-call (01)", "Support - Other On Call (02)", "Support - Rotation On-call (04)", "Network Operations On Call (07)"],
        "timesheet_and_time_entry_notification": "Enable"
    },
    {
        "location_level_1": "United States",
        "location_level_2_to_include": [],
        "location_level_2_to_exclude": [],
        "department_1_to_include": ["Research & Development"],
        "department_1_to_exclude": [],
        "employee_category_to_include": ["Salaried"],
        "employee_category_to_exclude": [],
        "payrule": "US Payrule",
        "timesheet_period": "Weekly without crossing months",
        "schedule_type": "Shift Schedule",
        "work_week": "Monday-Sunday",
        "timesheet_template": "On Call Non-Billable Template US",
        "time_entry_approval_path": "iPipeline NB Project Manager",
        "timesheet_approval_path": "iPipeline NB Supervisor",
        "time_off_template": "iPipeline US",
        "time_off_approval": "iPipeline US",
        "holiday_calendar": "Holiday US",
        "activities": ["Support - Flex On-call (01)", "Support - Other On Call (02)", "Support - Rotation On-call (04)", "Network Operations On Call (07)"],
        "timesheet_and_time_entry_notification": "Disable"
    },
    {
        "location_level_1": "United States",
        "location_level_2_to_include": [],
        "location_level_2_to_exclude": [],
        "department_1_to_include": ["Network Operations"],
        "department_1_to_exclude": [],
        "employee_category_to_include": ["Hourly"],
        "employee_category_to_exclude": [],
        "payrule": "US Payrule",
        "timesheet_period": "Weekly without crossing months",
        "schedule_type": "Shift Schedule",
        "work_week": "Monday-Sunday",
        "timesheet_template": "On Call Billable Template US",
        "time_entry_approval_path": "iPipeline B Project Manager",
        "timesheet_approval_path": "iPipeline B Supervisor",
        "time_off_template": "iPipeline US",
        "time_off_approval": "iPipeline US",
        "holiday_calendar": "Holiday US",
        "activities": ["Support - Flex On-call (01)", "Support - Other On Call (02)", "Support - Rotation On-call (04)", "Network Operations On Call (07)"],
        "timesheet_and_time_entry_notification": "Enable"
    },
    {
        "location_level_1": "United States",
        "location_level_2_to_include": [],
        "location_level_2_to_exclude": [],
        "department_1_to_include": ["Network Operations"],
        "department_1_to_exclude": [],
        "employee_category_to_include": ["Salaried"],
        "employee_category_to_exclude": [],
        "payrule": "US Payrule",
        "timesheet_period": "Weekly without crossing months",
        "schedule_type": "Shift Schedule",
        "work_week": "Monday-Sunday",
        "timesheet_template": "On Call Non-Billable Template US",
        "time_entry_approval_path": "iPipeline NB Project Manager",
        "timesheet_approval_path": "iPipeline NB Supervisor",
        "time_off_template": "iPipeline US",
        "time_off_approval": "iPipeline US",
        "holiday_calendar": "Holiday US",
        "activities": ["Support - Flex On-call (01)", "Support - Other On Call (02)", "Support - Rotation On-call (04)", "Network Operations On Call (07)"],
        "timesheet_and_time_entry_notification": "Disable"
    },
    {
        "location_level_1": "United Kingdom",
        "location_level_2_to_include": [],
        "location_level_2_to_exclude": [],
        "department_1_to_include": ["Pro Services"],
        "department_1_to_exclude": [],
        "employee_category_to_include": [],
        "employee_category_to_exclude": [],
        "payrule": "UK Payrule",
        "timesheet_period": "Weekly without crossing months",
        "schedule_type": "Shift Schedule",
        "work_week": "Monday-Sunday",
        "timesheet_template": "On Call Billable Template UK",
        "time_entry_approval_path": "iPipeline B Project Manager",
        "timesheet_approval_path": "iPipeline B Supervisor",
        "time_off_template": "iPipeline UK",
        "time_off_approval": "iPipeline UK",
        "holiday_calendar": "Holiday UK",
        "activities": ["UK After Hours Release", "UK IT Ops / DBA On Call", "UK On Call"],
        "timesheet_and_time_entry_notification": "Enable"
    },
    {
        "location_level_1": "United Kingdom",
        "location_level_2_to_include": [],
        "location_level_2_to_exclude": [],
        "department_1_to_include": [],
        "department_1_to_exclude": ["Pro Services"],
        "employee_category_to_include": ["Hourly"],
        "employee_category_to_exclude": [],
        "payrule": "UK Payrule",
        "timesheet_period": "Weekly without crossing months",
        "schedule_type": "Shift Schedule",
        "work_week": "Monday-Sunday",
        "timesheet_template": "On Call Billable Template UK",
        "time_entry_approval_path": "iPipeline B Project Manager",
        "timesheet_approval_path": "iPipeline B Supervisor",
        "time_off_template": "iPipeline UK",
        "time_off_approval": "iPipeline UK",
        "holiday_calendar": "Holiday UK",
        "activities": ["UK After Hours Release", "UK IT Ops / DBA On Call", "UK On Call"],
        "timesheet_and_time_entry_notification": "Enable"
    },
    {
        "location_level_1": "United Kingdom",
        "location_level_2_to_include": [],
        "location_level_2_to_exclude": [],
        "department_1_to_include": [],
        "department_1_to_exclude": ["Pro Services"],
        "employee_category_to_include": ["Salaried"],
        "employee_category_to_exclude": [],
        "payrule": "UK Payrule",
        "timesheet_period": "Weekly without crossing months",
        "schedule_type": "Shift Schedule",
        "work_week": "Monday-Sunday",
        "timesheet_template": "On Call Non-Billable Template UK",
        "time_entry_approval_path": "iPipeline NB Project Manager",
        "timesheet_approval_path": "iPipeline NB Supervisor",
        "time_off_template": "iPipeline UK",
        "time_off_approval": "iPipeline UK",
        "holiday_calendar": "Holiday UK",
        "activities": ["UK After Hours Release", "UK IT Ops / DBA On Call", "UK On Call"],
        "timesheet_and_time_entry_notification": "Disable"
    },
    {
        "location_level_1": "Canada",
        "location_level_2_to_include": ["Ontario"],
        "location_level_2_to_exclude": [],
        "department_1_to_include": ["Pro Services"],
        "department_1_to_exclude": [],
        "employee_category_to_include": [],
        "employee_category_to_exclude": [],
        "payrule": "Canada Payrule",
        "timesheet_period": "Weekly without crossing months",
        "schedule_type": "Office Schedule",
        "work_week": "Monday-Sunday",
        "timesheet_template": "Standard Billable Template",
        "time_entry_approval_path": "iPipeline B Project Manager",
        "timesheet_approval_path": "iPipeline B Supervisor",
        "time_off_template": "iPipeline Canada",
        "time_off_approval": "iPipeline Canada",
        "holiday_calendar": "Holiday Ontario",
        "activities": [],
        "timesheet_and_time_entry_notification": "Enable"
    },
    {
        "location_level_1": "Canada",
        "location_level_2_to_include": ["Ontario"],
        "location_level_2_to_exclude": [],
        "department_1_to_include": ["Network Operations"],
        "department_1_to_exclude": [],
        "employee_category_to_include": ["Hourly"],
        "employee_category_to_exclude": [],
        "payrule": "Canada Payrule",
        "timesheet_period": "Weekly without crossing months",
        "schedule_type": "Shift Schedule",
        "work_week": "Monday-Sunday",
        "timesheet_template": "On Call Billable Template Canada",
        "time_entry_approval_path": "iPipeline B Project Manager",
        "timesheet_approval_path": "iPipeline B Supervisor",
        "time_off_template": "iPipeline Canada",
        "time_off_approval": "iPipeline Canada",
        "holiday_calendar": "Holiday Ontario",
        "activities": ["Canada - On Call No Calls (05)", "Canada - On Call - Took Calls 0-2 hrs (06)", "Canada - On Call - Took Calls  Addtl Hourly (06)", "Network Operations On Call (07)"],
        "timesheet_and_time_entry_notification": "Enable"
    },
    {
        "location_level_1": "Canada",
        "location_level_2_to_include": ["Ontario"],
        "location_level_2_to_exclude": [],
        "department_1_to_include": ["Network Operations"],
        "department_1_to_exclude": [],
        "employee_category_to_include": ["Salaried"],
        "employee_category_to_exclude": [],
        "payrule": "Canada Payrule",
        "timesheet_period": "Weekly without crossing months",
        "schedule_type": "Shift Schedule",
        "work_week": "Monday-Sunday",
        "timesheet_template": "On Call Non-Billable Template Canada",
        "time_entry_approval_path": "iPipeline NB Project Manager",
        "timesheet_approval_path": "iPipeline NB Supervisor",
        "time_off_template": "iPipeline Canada",
        "time_off_approval": "iPipeline Canada",
        "holiday_calendar": "Holiday Ontario",
        "activities": ["Canada - On Call No Calls (05)", "Canada - On Call - Took Calls 0-2 hrs (06)", "Canada - On Call - Took Calls  Addtl Hourly (06)", "Network Operations On Call (07)"],
        "timesheet_and_time_entry_notification": "Disable"
    },
    {
        "location_level_1": "Canada",
        "location_level_2_to_include": ["Ontario"],
        "location_level_2_to_exclude": [],
        "department_1_to_include": [],
        "department_1_to_exclude": ["Pro Services", "Network Operations"],
        "employee_category_to_include": ["Hourly"],
        "employee_category_to_exclude": [],
        "payrule": "Canada Payrule",
        "timesheet_period": "Weekly without crossing months",
        "schedule_type": "Office Schedule",
        "work_week": "Monday-Sunday",
        "timesheet_template": "Standard Billable Template",
        "time_entry_approval_path": "iPipeline B Project Manager",
        "timesheet_approval_path": "iPipeline B Supervisor",
        "time_off_template": "iPipeline Canada",
        "time_off_approval": "iPipeline Canada",
        "holiday_calendar": "Holiday Ontario",
        "activities": [],
        "timesheet_and_time_entry_notification": "Enable"
    },
    {
        "location_level_1": "Canada",
        "location_level_2_to_include": ["Ontario"],
        "location_level_2_to_exclude": [],
        "department_1_to_include": [],
        "department_1_to_exclude": ["Pro Services", "Network Operations"],
        "employee_category_to_include": ["Salaried"],
        "employee_category_to_exclude": [],
        "payrule": "Canada Payrule",
        "timesheet_period": "Weekly without crossing months",
        "schedule_type": "Office Schedule",
        "work_week": "Monday-Sunday",
        "timesheet_template": "Standard Non-Billable Template",
        "time_entry_approval_path": "iPipeline NB Project Manager",
        "timesheet_approval_path": "iPipeline NB Supervisor",
        "time_off_template": "iPipeline Canada",
        "time_off_approval": "iPipeline Canada",
        "holiday_calendar": "Holiday Ontario",
        "activities": [],
        "timesheet_and_time_entry_notification": "Disable"
    },
    {
        "location_level_1": "Canada",
        "location_level_2_to_include": ["Vancuver"],
        "location_level_2_to_exclude": [],
        "department_1_to_include": ["Pro Services"],
        "department_1_to_exclude": [],
        "employee_category_to_include": [],
        "employee_category_to_exclude": [],
        "payrule": "Canada Payrule",
        "timesheet_period": "Weekly without crossing months",
        "schedule_type": "Office Schedule",
        "work_week": "Monday-Sunday",
        "timesheet_template": "Standard Billable Template",
        "time_entry_approval_path": "iPipeline B Project Manager",
        "timesheet_approval_path": "iPipeline B Supervisor",
        "time_off_template": "iPipeline Canada",
        "time_off_approval": "iPipeline Canada",
        "holiday_calendar": "Holiday Vancuver",
        "activities": [],
        "timesheet_and_time_entry_notification": "Enable"
    },
    {
        "location_level_1": "Canada",
        "location_level_2_to_include": ["Vancuver"],
        "location_level_2_to_exclude": [],
        "department_1_to_include": ["Network Operations"],
        "department_1_to_exclude": [],
        "employee_category_to_include": ["Hourly"],
        "employee_category_to_exclude": [],
        "payrule": "Canada Payrule",
        "timesheet_period": "Weekly without crossing months",
        "schedule_type": "Shift Schedule",
        "work_week": "Monday-Sunday",
        "timesheet_template": "On Call Billable Template Canada",
        "time_entry_approval_path": "iPipeline B Project Manager",
        "timesheet_approval_path": "iPipeline B Supervisor",
        "time_off_template": "iPipeline Canada",
        "time_off_approval": "iPipeline Canada",
        "holiday_calendar": "Holiday Vancuver",
        "activities": ["Canada - On Call No Calls (05)", "Canada - On Call - Took Calls 0-2 hrs (06)", "Canada - On Call - Took Calls  Addtl Hourly (06)", "Network Operations On Call (07)"],
        "timesheet_and_time_entry_notification": "Enable"
    },
    {
        "location_level_1": "Canada",
        "location_level_2_to_include": ["Vancuver"],
        "location_level_2_to_exclude": [],
        "department_1_to_include": ["Network Operations"],
        "department_1_to_exclude": [],
        "employee_category_to_include": ["Salaried"],
        "employee_category_to_exclude": [],
        "payrule": "Canada Payrule",
        "timesheet_period": "Weekly without crossing months",
        "schedule_type": "Shift Schedule",
        "work_week": "Monday-Sunday",
        "timesheet_template": "On Call Non-Billable Template Canada",
        "time_entry_approval_path": "iPipeline NB Project Manager",
        "timesheet_approval_path": "iPipeline NB Supervisor",
        "time_off_template": "iPipeline Canada",
        "time_off_approval": "iPipeline Canada",
        "holiday_calendar": "Holiday Vancuver",
        "activities": ["Canada - On Call No Calls (05)", "Canada - On Call - Took Calls 0-2 hrs (06)", "Canada - On Call - Took Calls  Addtl Hourly (06)", "Network Operations On Call (07)"],
        "timesheet_and_time_entry_notification": "Disable"
    },
    {
        "location_level_1": "Canada",
        "location_level_2_to_include": ["Vancuver"],
        "location_level_2_to_exclude": [],
        "department_1_to_include": [],
        "department_1_to_exclude": ["Pro Services", "Network Operations"],
        "employee_category_to_include": ["Hourly"],
        "employee_category_to_exclude": [],
        "payrule": "Canada Payrule",
        "timesheet_period": "Weekly without crossing months",
        "schedule_type": "Office Schedule",
        "work_week": "Monday-Sunday",
        "timesheet_template": "Standard Billable Template",
        "time_entry_approval_path": "iPipeline B Project Manager",
        "timesheet_approval_path": "iPipeline B Supervisor",
        "time_off_template": "iPipeline Canada",
        "time_off_approval": "iPipeline Canada",
        "holiday_calendar": "Holiday Vancuver",
        "activities": [],
        "timesheet_and_time_entry_notification": "Enable"
    },
    {
        "location_level_1": "Canada",
        "location_level_2_to_include": ["Vancuver"],
        "location_level_2_to_exclude": [],
        "department_1_to_include": [],
        "department_1_to_exclude": ["Pro Services", "Network Operations"],
        "employee_category_to_include": ["Salaried"],
        "employee_category_to_exclude": [],
        "payrule": "Canada Payrule",
        "timesheet_period": "Weekly without crossing months",
        "schedule_type": "Office Schedule",
        "work_week": "Monday-Sunday",
        "timesheet_template": "Standard Non-Billable Template",
        "time_entry_approval_path": "iPipeline NB Project Manager",
        "timesheet_approval_path": "iPipeline NB Supervisor",
        "time_off_template": "iPipeline Canada",
        "time_off_approval": "iPipeline Canada",
        "holiday_calendar": "Holiday Vancuver",
        "activities": [],
        "timesheet_and_time_entry_notification": "Disable"
    },
    {
        "location_level_1": "Canada",
        "location_level_2_to_include": [],
        "location_level_2_to_exclude": ["Ontario", "Vancuver"],
        "department_1_to_include": ["Pro Services"],
        "department_1_to_exclude": [],
        "employee_category_to_include": [],
        "employee_category_to_exclude": [],
        "payrule": "Canada Payrule",
        "timesheet_period": "Weekly without crossing months",
        "schedule_type": "Office Schedule",
        "work_week": "Monday-Sunday",
        "timesheet_template": "Standard Billable Template",
        "time_entry_approval_path": "iPipeline B Project Manager",
        "timesheet_approval_path": "iPipeline B Supervisor",
        "time_off_template": "iPipeline Canada",
        "time_off_approval": "iPipeline Canada",
        "holiday_calendar": "Holiday CA",
        "activities": [],
        "timesheet_and_time_entry_notification": "Enable"
    },
    {
        "location_level_1": "Canada",
        "location_level_2_to_include": [],
        "location_level_2_to_exclude": ["Ontario", "Vancuver"],
        "department_1_to_include": ["Network Operations"],
        "department_1_to_exclude": [],
        "employee_category_to_include": ["Hourly"],
        "employee_category_to_exclude": [],
        "payrule": "Canada Payrule",
        "timesheet_period": "Weekly without crossing months",
        "schedule_type": "Shift Schedule",
        "work_week": "Monday-Sunday",
        "timesheet_template": "On Call Billable Template Canada",
        "time_entry_approval_path": "iPipeline B Project Manager",
        "timesheet_approval_path": "iPipeline B Supervisor",
        "time_off_template": "iPipeline Canada",
        "time_off_approval": "iPipeline Canada",
        "holiday_calendar": "Holiday CA",
        "activities": ["Canada - On Call No Calls (05)", "Canada - On Call - Took Calls 0-2 hrs (06)", "Canada - On Call - Took Calls  Addtl Hourly (06)", "Network Operations On Call (07)"],
        "timesheet_and_time_entry_notification": "Enable"
    },
    {
        "location_level_1": "Canada",
        "location_level_2_to_include": [],
        "location_level_2_to_exclude": ["Ontario", "Vancuver"],
        "department_1_to_include": ["Network Operations"],
        "department_1_to_exclude": [],
        "employee_category_to_include": ["Salaried"],
        "employee_category_to_exclude": [],
        "payrule": "Canada Payrule",
        "timesheet_period": "Weekly without crossing months",
        "schedule_type": "Shift Schedule",
        "work_week": "Monday-Sunday",
        "timesheet_template": "On Call Non-Billable Template Canada",
        "time_entry_approval_path": "iPipeline NB Project Manager",
        "timesheet_approval_path": "iPipeline NB Supervisor",
        "time_off_template": "iPipeline Canada",
        "time_off_approval": "iPipeline Canada",
        "holiday_calendar": "Holiday CA",
        "activities": ["Canada - On Call No Calls (05)", "Canada - On Call - Took Calls 0-2 hrs (06)", "Canada - On Call - Took Calls  Addtl Hourly (06)", "Network Operations On Call (07)"],
        "timesheet_and_time_entry_notification": "Disable"
    },
    {
        "location_level_1": "Canada",
        "location_level_2_to_include": [],
        "location_level_2_to_exclude": ["Ontario", "Vancuver"],
        "department_1_to_include": [],
        "department_1_to_exclude": ["Pro Services", "Network Operations"],
        "employee_category_to_include": ["Hourly"],
        "employee_category_to_exclude": [],
        "payrule": "Canada Payrule",
        "timesheet_period": "Weekly without crossing months",
        "schedule_type": "Office Schedule",
        "work_week": "Monday-Sunday",
        "timesheet_template": "Standard Billable Template",
        "time_entry_approval_path": "iPipeline B Project Manager",
        "timesheet_approval_path": "iPipeline B Supervisor",
        "time_off_template": "iPipeline Canada",
        "time_off_approval": "iPipeline Canada",
        "holiday_calendar": "Holiday CA",
        "activities": [],
        "timesheet_and_time_entry_notification": "Enable"
    },
    {
        "location_level_1": "Canada",
        "location_level_2_to_include": [],
        "location_level_2_to_exclude": ["Ontario", "Vancuver"],
        "department_1_to_include": [],
        "department_1_to_exclude": ["Pro Services", "Network Operations"],
        "employee_category_to_include": ["Salaried"],
        "employee_category_to_exclude": [],
        "payrule": "Canada Payrule",
        "timesheet_period": "Weekly without crossing months",
        "schedule_type": "Office Schedule",
        "work_week": "Monday-Sunday",
        "timesheet_template": "Standard Non-Billable Template",
        "time_entry_approval_path": "iPipeline NB Project Manager",
        "timesheet_approval_path": "iPipeline NB Supervisor",
        "time_off_template": "iPipeline Canada",
        "time_off_approval": "iPipeline Canada",
        "holiday_calendar": "Holiday CA",
        "activities": [],
        "timesheet_and_time_entry_notification": "Disable"
    },
    {
        "location_level_1": "Japan",
        "location_level_2_to_include": [],
        "location_level_2_to_exclude": [],
        "department_1_to_include": ["Pro Services"],
        "department_1_to_exclude": [],
        "employee_category_to_include": [],
        "employee_category_to_exclude": [],
        "payrule": "Japan Payrule",
        "timesheet_period": "Weekly without crossing months",
        "schedule_type": "Office Schedule",
        "work_week": "Monday-Sunday",
        "timesheet_template": "Standard Billable Template",
        "time_entry_approval_path": "iPipeline B Project Manager",
        "timesheet_approval_path": "iPipeline B Supervisor",
        "time_off_template": "iPipeline Japan",
        "time_off_approval": "iPipeline Japan",
        "holiday_calendar": "Holiday Japan",
        "activities": [],
        "timesheet_and_time_entry_notification": "Enable"
    },
    {
        "location_level_1": "Japan",
        "location_level_2_to_include": [],
        "location_level_2_to_exclude": [],
        "department_1_to_include": [],
        "department_1_to_exclude": ["Pro Services", "Network Operations"],
        "employee_category_to_include": ["Hourly"],
        "employee_category_to_exclude": [],
        "payrule": "Japan Payrule",
        "timesheet_period": "Weekly without crossing months",
        "schedule_type": "Office Schedule",
        "work_week": "Monday-Sunday",
        "timesheet_template": "Standard Billable Template",
        "time_entry_approval_path": "iPipeline B Project Manager",
        "timesheet_approval_path": "iPipeline B Supervisor",
        "time_off_template": "iPipeline Japan",
        "time_off_approval": "iPipeline Japan",
        "holiday_calendar": "Holiday Japan",
        "activities": [],
        "timesheet_and_time_entry_notification": "Enable"
    },
    {
        "location_level_1": "Japan",
        "location_level_2_to_include": [],
        "location_level_2_to_exclude": [],
        "department_1_to_include": [],
        "department_1_to_exclude": ["Pro Services", "Network Operations"],
        "employee_category_to_include": ["Salaried"],
        "employee_category_to_exclude": [],
        "payrule": "Japan Payrule",
        "timesheet_period": "Weekly without crossing months",
        "schedule_type": "Office Schedule",
        "work_week": "Monday-Sunday",
        "timesheet_template": "Standard Non-Billable Template",
        "time_entry_approval_path": "iPipeline NB Project Manager",
        "timesheet_approval_path": "iPipeline NB Supervisor",
        "time_off_template": "iPipeline Japan",
        "time_off_approval": "iPipeline Japan",
        "holiday_calendar": "Holiday Japan",
        "activities": [],
        "timesheet_and_time_entry_notification": "Disable"
    }
]