class CE_Fields:
    """CSV column names from Computerease purchase order export"""
    Due_Date = 'Due Date'
    Description = 'Description'
    PO_Number = 'PO Number'
    Invoice_Number = 'Invoice Number'
    Status = 'Status'
    Invoice_Date = 'Invoice Date'
    Invoice_Period = 'Invoice Period'
    Amount = 'Amount'
    Job = 'Job'
    Job_Name = 'Job Name'
    Phase = 'Phase'
    Category = 'Category'
    Cost_Type = 'Cost Type'
    Retention_Pct = 'Retention Pct'
    Retention_Amount = 'Retention Amount'
    Balance_Payable = 'Balance Payable'
    Quantity = 'Quantity'
    Item_Number = 'Item Number'
    Item_Name = 'Item Name'
    Distribution_Description = 'Distribution Description'
