# pylint: disable=line-too-long
mapper_othercountries = [
    {
        "type": "Schedule",
        "Workertype": "Employee",
        "Location": "Any",
        "Exemptstatus": "Yes",
        "Shift": "Any",
        "Workersubtype_legalentity": "MOMENTIVE PERFORMANCE MATERIALS KOREA CO., LTD.",
        "Gender": "Any",
        "Country": "South Korea",
        "Value": "M-F 8 hours"
    },
    {
        "type": "Time off apporval path",
        "Workertype": "Employee",
        "Location": "Any",
        "Exemptstatus": "Yes",
        "Shift": "Any",
        "Workersubtype_legalentity": "MOMENTIVE PERFORMANCE MATERIALS KOREA CO., LTD.",
        "Gender": "Any",
        "Country": "South Korea",
        "Value": "Supervisor"
    },
    {
        "type": "Time off apporval path",
        "Workertype": "Employee",
        "Location": "Any",
        "Exemptstatus": "No",
        "Shift": "Any",
        "Workersubtype_legalentity": "MOMENTIVE PERFORMANCE MATERIALS KOREA CO., LTD.",
        "Gender": "Any",
        "Country": "South Korea",
        "Value": "Supervisor"
    },
    {
        "type": "Language",
        "Workertype": "Employee",
        "Location": "Any",
        "Exemptstatus": "Any",
        "Shift": "Any",
        "Workersubtype_legalentity": "MOMENTIVE PERFORMANCE MATERIALS KOREA CO., LTD.",
        "Gender": "Any",
        "Country": "South Korea",
        "Value": "urn:replicon:language:en"
    },
    {
        "type": "Holiday Calendar",
        "Workertype": "Employee",
        "Location": "Any",
        "Exemptstatus": "Yes",
        "Shift": "Any",
        "Workersubtype_legalentity": "MOMENTIVE PERFORMANCE MATERIALS KOREA CO., LTD.",
        "Gender": "Any",
        "Country": "South Korea",
        "Value": "South Korea"
    },
    {
        "type": "Holiday Calendar",
        "Workertype": "Employee",
        "Location": "Any",
        "Exemptstatus": "No",
        "Shift": "Any",
        "Workersubtype_legalentity": "MOMENTIVE PERFORMANCE MATERIALS KOREA CO., LTD.",
        "Gender": "Any",
        "Country": "South Korea",
        "Value": "South Korea"
    },
    {
        "type": "Holiday Calendar",
        "Workertype": "Contingent Worker",
        "Location": "Any",
        "Exemptstatus": "No",
        "Shift": "Any",
        "Workersubtype_legalentity": "MOMENTIVE PERFORMANCE MATERIALS KOREA CO., LTD.",
        "Gender": "Any",
        "Country": "South Korea",
        "Value": "South Korea"
    },
    {
        "type": "Time off types",
        "Workertype": "Employee",
        "Location": "Any",
        "Exemptstatus": "Yes",
        "Shift": "Any",
        "Workersubtype_legalentity": "MOMENTIVE PERFORMANCE MATERIALS KOREA CO., LTD.",
        "Gender": "Male",
        "Country": "South Korea",
        "Value": "KOR_Annual Leave 연차휴가|KOR_Paternity Leave 배우자 출산휴가|KOR_Military & Training Leave - Reservists 예비군훈련|KOR_Military & Training Leave - Civil defense  민방위훈련|KOR_Child Care Leave 육아휴직|KOR_Family Care Leave 가족돌봄휴직|KOR_Sick Leave 병가|KOR_special Leave - Marriage employee 경조사휴가(결혼/본인)|KOR_Special Leave - Marriage Children 경조사휴가(결혼/자녀)|KOR_Special Leave - Marriage Brother/Sister 경조사휴가(결혼/형제자매)|KOR_Special Leave - Parents 60th Birthday 경조사휴가(회갑/본인부모)|KOR_Special Leave - Spouse Death 경조사휴가(장례/배우자)|KOR_Special Leave - Parents Death 경조사휴가(장례/본인부모)|KOR_Special Leave - Grandparents Death 경조사휴가(장례/본인조부모)|KOR_Special Leaves - Brother/Sister Death 경조사휴가(장례/형제자매)|KOR_Special Leave - Children Death 경조사휴가(장례/자녀)|KOR_Special Leave - House-moving 이사지원 공가|KOR_Special Leave - Medical Check 건강검진 공가|KOR_Monthly Leave 월차휴가|KOR_Summer Vacation 여름휴가|KOR_Special Leave - Spouse's Parents 60th Birthday 경조사휴가(회갑/배우자부모)|KOR_Special Leave - Spouse's Parents Death 경조사휴가(장례/배우자부모)"
    },
    {
        "type": "Time off types",
        "Workertype": "Employee",
        "Location": "Any",
        "Exemptstatus": "No",
        "Shift": "Any",
        "Workersubtype_legalentity": "MOMENTIVE PERFORMANCE MATERIALS KOREA CO., LTD.",
        "Gender": "Male",
        "Country": "South Korea",
        "Value": """KOR_Annual Leave 연차휴가|KOR_Paternity Leave 배우자 출산휴가|KOR_Military & Training Leave - Reservists 예비군훈련|KOR_Military & Training Leave - Civil defense  민방위훈련|KOR_Child Care Leave 육아휴직|KOR_Family Care Leave 가족돌봄휴직|KOR_Sick Leave 병가|KOR_special Leave - Marriage employee 경조사휴가(결혼/본인)|KOR_Special Leave - Marriage Children 경조사휴가(결혼/자녀)|KOR_Special Leave - Marriage Brother/Sister 경조사휴가(결혼/형제자매)|KOR_Special Leave - Parents 60th Birthday 경조사휴가(회갑/본인부모)|KOR_Special Leave - Spouse Death 경조사휴가(장례/배우자)|KOR_Special Leave - Parents Death 경조사휴가(장례/본인부모)|KOR_Special Leave - Grandparents Death 경조사휴가(장례/본인조부모)|KOR_Special Leaves - Brother/Sister Death 경조사휴가(장례/형제자매)|KOR_Special Leave - Children Death 경조사휴가(장례/자녀)|KOR_Special Leave - House-moving 이사지원 공가|KOR_Special Leave - Medical Check 건강검진 공가|KOR_Monthly Leave 월차휴가|KOR_Summer Vacation 여름휴가|KOR_Special Leave - Spouse's Parents 60th Birthday 경조사휴가(회갑/배우자부모)|KOR_Special Leave - Spouse's Parents Death 경조사휴가(장례/배우자부모)"""
    },
    {
        "type": "Employee Type",
        "Workertype": "Employee",
        "Location": "Any",
        "Exemptstatus": "Yes",
        "Shift": "Any",
        "Workersubtype_legalentity": "MOMENTIVE PERFORMANCE MATERIALS KOREA CO., LTD.",
        "Gender": "Any",
        "Country": "South Korea",
        "Value": "Exempt"
    },
    {
        "type": "Employee Type",
        "Workertype": "Contingent Worker",
        "Location": "Any",
        "Exemptstatus": "No",
        "Shift": "Any",
        "Workersubtype_legalentity": "MOMENTIVE PERFORMANCE MATERIALS KOREA CO., LTD.",
        "Gender": "Any",
        "Country": "South Korea",
        "Value": "Contingent Worker"
    },
    {
        "type": "Employee Type",
        "Workertype": "Employee",
        "Location": "Any",
        "Exemptstatus": "No",
        "Shift": "Any",
        "Workersubtype_legalentity": "MOMENTIVE PERFORMANCE MATERIALS KOREA CO., LTD.",
        "Gender": "Any",
        "Country": "South Korea",
        "Value": "Non-Exempt"
    },
    {
        "type": "Time off types",
        "Workertype": "Employee",
        "Location": "Any",
        "Exemptstatus": "Yes",
        "Shift": "Any",
        "Workersubtype_legalentity": "MOMENTIVE PERFORMANCE MATERIALS KOREA CO., LTD.",
        "Gender": "Female",
        "Country": "South Korea",
        "Value": "KOR_Annual Leave 연차휴가|KOR_Maternity leave 출산휴가|KOR_Maternity leave -Plural birth 출산휴가(다태아)|KOR_Child Care Leave 육아휴직|KOR_Family Care Leave 가족돌봄휴직|KOR_Sick Leave 병가|KOR_Fertility Treatment Leave 난임치료휴가|KOR_special Leave - Marriage employee 경조사휴가(결혼/본인)|KOR_Special Leave - Marriage Children 경조사휴가(결혼/자녀)|KOR_Special Leave - Marriage Brother/Sister 경조사휴가(결혼/형제자매)|KOR_Special Leave - Parents 60th Birthday 경조사휴가(회갑/본인부모)|KOR_Special Leave - Spouse Death 경조사휴가(장례/배우자)|KOR_Special Leave - Parents Death 경조사휴가(장례/본인부모)|KOR_Special Leave - Grandparents Death 경조사휴가(장례/본인조부모)|KOR_Special Leaves - Brother/Sister Death 경조사휴가(장례/형제자매)|KOR_Special Leave - Children Death 경조사휴가(장례/자녀)|KOR_Special Leave - House-moving 이사지원 공가|KOR_Special Leave - Medical Check 건강검진 공가|KOR_Monthly Leave 월차휴가|KOR_Summer Vacation 여름휴가|KOR_Special Leave - Spouse's Parents 60th Birthday 경조사휴가(회갑/배우자부모)|KOR_Menstruation Leave 보건휴가|KOR_Special Leave - Spouse's Parents Death 경조사휴가(장례/배우자부모)"
    },
    {
        "type": "Time off types",
        "Workertype": "Employee",
        "Location": "Any",
        "Exemptstatus": "No",
        "Shift": "Any",
        "Workersubtype_legalentity": "MOMENTIVE PERFORMANCE MATERIALS KOREA CO., LTD.",
        "Gender": "Female",
        "Country": "South Korea",
        "Value": "KOR_Annual Leave 연차휴가|KOR_Maternity leave 출산휴가|KOR_Maternity leave -Plural birth 출산휴가(다태아)|KOR_Child Care Leave 육아휴직|KOR_Family Care Leave 가족돌봄휴직|KOR_Sick Leave 병가|KOR_Fertility Treatment Leave 난임치료휴가|KOR_special Leave - Marriage employee 경조사휴가(결혼/본인)|KOR_Special Leave - Marriage Children 경조사휴가(결혼/자녀)|KOR_Special Leave - Marriage Brother/Sister 경조사휴가(결혼/형제자매)|KOR_Special Leave - Parents 60th Birthday 경조사휴가(회갑/본인부모)|KOR_Special Leave - Spouse Death 경조사휴가(장례/배우자)|KOR_Special Leave - Parents Death 경조사휴가(장례/본인부모)|KOR_Special Leave - Grandparents Death 경조사휴가(장례/본인조부모)|KOR_Special Leaves - Brother/Sister Death 경조사휴가(장례/형제자매)|KOR_Special Leave - Children Death 경조사휴가(장례/자녀)|KOR_Special Leave - House-moving 이사지원 공가|KOR_Special Leave - Medical Check 건강검진 공가|KOR_Monthly Leave 월차휴가|KOR_Summer Vacation 여름휴가|KOR_Special Leave - Spouse's Parents 60th Birthday 경조사휴가(회갑/배우자부모)|KOR_Menstruation Leave 보건휴가|KOR_Special Leave - Spouse's Parents Death 경조사휴가(장례/배우자부모)"
    },
    {
        "type": "Schedule",
        "Workertype": "Employee",
        "Location": "Any",
        "Exemptstatus": "No",
        "Shift": "Any",
        "Workersubtype_legalentity": "MOMENTIVE PERFORMANCE MATERIALS KOREA CO., LTD.",
        "Gender": "Any",
        "Country": "South Korea",
        "Value": "M-F 8 hours"
    },
    {
        "type": "Schedule",
        "Workertype": "Contingent Worker",
        "Location": "Any",
        "Exemptstatus": "No",
        "Shift": "Any",
        "Workersubtype_legalentity": "MOMENTIVE PERFORMANCE MATERIALS KOREA CO., LTD.",
        "Gender": "Any",
        "Country": "South Korea",
        "Value": "M-F 8 hours"
    },
    {
        "type": "Time zone",
        "Workertype": "Employee",
        "Location": "Any",
        "Exemptstatus": "No",
        "Shift": "Any",
        "Workersubtype_legalentity": "MOMENTIVE PERFORMANCE MATERIALS KOREA CO., LTD.",
        "Gender": "Any",
        "Country": "South Korea",
        "Value": "Asia/Seoul"
    },
    {
        "type": "Time zone",
        "Workertype": "Employee",
        "Location": "Any",
        "Exemptstatus": "Yes",
        "Shift": "Any",
        "Workersubtype_legalentity": "MOMENTIVE PERFORMANCE MATERIALS KOREA CO., LTD.",
        "Gender": "Any",
        "Country": "South Korea",
        "Value": "Asia/Seoul"
    },
    {
        "type": "Time zone",
        "Workertype": "Contingent Worker",
        "Location": "Any",
        "Exemptstatus": "No",
        "Shift": "Any",
        "Workersubtype_legalentity": "MOMENTIVE PERFORMANCE MATERIALS KOREA CO., LTD.",
        "Gender": "Any",
        "Country": "South Korea",
        "Value": "Asia/Seoul"
    },
    {
        "type": "Work week",
        "Workertype": "Employee",
        "Location": "Any",
        "Exemptstatus": "No",
        "Shift": "Any",
        "Workersubtype_legalentity": "MOMENTIVE PERFORMANCE MATERIALS KOREA CO., LTD.",
        "Gender": "Any",
        "Country": "South Korea",
        "Value": "urn:replicon:day-of-week:monday"
    },
    {
        "type": "Work week",
        "Workertype": "Contingent Worker",
        "Location": "Any",
        "Exemptstatus": "No",
        "Shift": "Any",
        "Workersubtype_legalentity": "MOMENTIVE PERFORMANCE MATERIALS KOREA CO., LTD.",
        "Gender": "Any",
        "Country": "South Korea",
        "Value": "urn:replicon:day-of-week:monday"
    },
    {
        "type": "Work week",
        "Workertype": "Employee",
        "Location": "Any",
        "Exemptstatus": "Yes",
        "Shift": "Any",
        "Workersubtype_legalentity": "MOMENTIVE PERFORMANCE MATERIALS KOREA CO., LTD.",
        "Gender": "Any",
        "Country": "South Korea",
        "Value": "urn:replicon:day-of-week:monday"
    },
    {
        "type": "Payrule",
        "Workertype": "Employee",
        "Location": "Any",
        "Exemptstatus": "Yes",
        "Shift": "Any",
        "Workersubtype_legalentity": "MPM FZE",
        "Gender": "Any",
        "Country": "UAE",
        "Value": "UAE_Exempt"
    },
    {
        "type": "Schedule",
        "Workertype": "Employee",
        "Location": "Any",
        "Exemptstatus": "Yes",
        "Shift": "Any",
        "Workersubtype_legalentity": "MPM FZE",
        "Gender": "Any",
        "Country": "UAE",
        "Value": "8 hours/day; Mon-Fri"
    },
    {
        "type": "Timesheet Template",
        "Workertype": "Employee",
        "Location": "Any",
        "Exemptstatus": "Yes",
        "Shift": "Any",
        "Workersubtype_legalentity": "MPM FZE",
        "Gender": "Any",
        "Country": "UAE",
        "Value": "UAE_Timesheet"
    },
    {
        "type": "Time off apporval path",
        "Workertype": "Employee",
        "Location": "Any",
        "Exemptstatus": "Yes",
        "Shift": "Any",
        "Workersubtype_legalentity": "MPM FZE",
        "Gender": "Any",
        "Country": "UAE",
        "Value": "Supervisor"
    },
    {
        "type": "Timesheet approval path",
        "Workertype": "Employee",
        "Location": "Any",
        "Exemptstatus": "Yes",
        "Shift": "Any",
        "Workersubtype_legalentity": "MPM FZE",
        "Gender": "Any",
        "Country": "UAE",
        "Value": "System Approval"
    },
    {
        "type": "Punch entry policy",
        "Workertype": "Employee",
        "Location": "Any",
        "Exemptstatus": "Yes",
        "Shift": "Any",
        "Workersubtype_legalentity": "MPM FZE",
        "Gender": "Any",
        "Country": "UAE",
        "Value": "UAE_Exempt"
    },
    {
        "type": "Language",
        "Workertype": "Employee",
        "Location": "Any",
        "Exemptstatus": "Any",
        "Shift": "Any",
        "Workersubtype_legalentity": "MPM FZE",
        "Gender": "Any",
        "Country": "UAE",
        "Value": "urn:replicon:language:en"
    },
    {
        "type": "Holiday Calendar",
        "Workertype": "Employee",
        "Location": "Any",
        "Exemptstatus": "Yes",
        "Shift": "Any",
        "Workersubtype_legalentity": "MPM FZE",
        "Gender": "Any",
        "Country": "UAE",
        "Value": "UAE"
    },
    {
        "type": "Time off types",
        "Workertype": "Employee",
        "Location": "Any",
        "Exemptstatus": "Yes",
        "Shift": "Any",
        "Workersubtype_legalentity": "MPM FZE",
        "Gender": "Male",
        "Country": "UAE",
        "Value": "UAE_Leave|UAE_Sick_Leave|UAE_Paternity Leave|UAE_Unpaid Leave|UAE_Work From Home|UAE_On Duty|UAE_Compensatory Off"
    },
    {
        "type": "Time off types",
        "Workertype": "Employee",
        "Location": "Any",
        "Exemptstatus": "Yes",
        "Shift": "Any",
        "Workersubtype_legalentity": "MPM FZE",
        "Gender": "Female",
        "Country": "UAE",
        "Value": "UAE_Leave|UAE_Sick_Leave|UAE_Maternity Leave|UAE_Unpaid Leave|UAE_Work From Home|UAE_On Duty|UAE_Compensatory Off"
    },
    {
        "type": "Time zone",
        "Workertype": "Employee",
        "Location": "Any",
        "Exemptstatus": "Yes",
        "Shift": "Any",
        "Workersubtype_legalentity": "MPM FZE",
        "Gender": "Any",
        "Country": "UAE",
        "Value": "Asia/Baghdad"
    },
    {
        "type": "Employee Type",
        "Workertype": "Employee",
        "Location": "Any",
        "Exemptstatus": "Yes",
        "Shift": "Any",
        "Workersubtype_legalentity": "MPM FZE",
        "Gender": "Any",
        "Country": "UAE",
        "Value": "Exempt"
    },
    {
        "type": "Work week",
        "Workertype": "Employee",
        "Location": "Any",
        "Exemptstatus": "Yes",
        "Shift": "Any",
        "Workersubtype_legalentity": "MPM FZE",
        "Gender": "Any",
        "Country": "UAE",
        "Value": "urn:replicon:day-of-week:sunday"
    },
    {
        "type": "Schedule",
        "Workertype": "Employee",
        "Location": "Any",
        "Exemptstatus": "Yes",
        "Shift": "Any",
        "Workersubtype_legalentity": "MOMENTIVE PERFORMANCE MATERIALS BENELUX BV",
        "Gender": "Any",
        "Country": "Belgium",
        "Value": "8 hours/day; Mon-Fri"
    },
    {
        "type": "Timesheet Template",
        "Workertype": "Employee",
        "Location": "Any",
        "Exemptstatus": "Yes",
        "Shift": "Any",
        "Workersubtype_legalentity": "MOMENTIVE PERFORMANCE MATERIALS BENELUX BV",
        "Gender": "Any",
        "Country": "Belgium",
        "Value": "[BEL] Timesheet Template"
    },
    {
        "type": "Payrule",
        "Workertype": "Employee",
        "Location": "Any",
        "Exemptstatus": "Yes",
        "Shift": "Any",
        "Workersubtype_legalentity": "MOMENTIVE PERFORMANCE MATERIALS BENELUX BV",
        "Gender": "Any",
        "Country": "Belgium",
        "Value": "Meal Voucher Calc"
    },
    {
        "type": "Timesheet approval path",
        "Workertype": "Employee",
        "Location": "Any",
        "Exemptstatus": "Yes",
        "Shift": "Any",
        "Workersubtype_legalentity": "MOMENTIVE PERFORMANCE MATERIALS BENELUX BV",
        "Gender": "Any",
        "Country": "Belgium",
        "Value": "System Approval"
    },
    {
        "type": "Language",
        "Workertype": "Employee",
        "Location": "Any",
        "Exemptstatus": "Any",
        "Shift": "Any",
        "Workersubtype_legalentity": "MOMENTIVE PERFORMANCE MATERIALS BENELUX BV",
        "Gender": "Any",
        "Country": "Belgium",
        "Value": "urn:replicon:language:en"
    },
    {
        "type": "Time off apporval path",
        "Workertype": "Employee",
        "Location": "Any",
        "Exemptstatus": "Yes",
        "Shift": "Any",
        "Workersubtype_legalentity": "MOMENTIVE PERFORMANCE MATERIALS BENELUX BV",
        "Gender": "Any",
        "Country": "Belgium",
        "Value": "Supervisor"
    },
    {
        "type": "Holiday Calendar",
        "Workertype": "Employee",
        "Location": "Any",
        "Exemptstatus": "Yes",
        "Shift": "Any",
        "Workersubtype_legalentity": "MOMENTIVE PERFORMANCE MATERIALS BENELUX BV",
        "Gender": "Any",
        "Country": "Belgium",
        "Value": "[BEL] Holiday Calendar"
    },
    {
        "type": "Time zone",
        "Workertype": "Employee",
        "Location": "Any",
        "Exemptstatus": "Yes",
        "Shift": "Any",
        "Workersubtype_legalentity": "MOMENTIVE PERFORMANCE MATERIALS BENELUX BV",
        "Gender": "Any",
        "Country": "Belgium",
        "Value": "Europe/Warsaw"
    },
    {
        "type": "Employee Type",
        "Workertype": "Employee",
        "Location": "Any",
        "Exemptstatus": "Yes",
        "Shift": "Any",
        "Workersubtype_legalentity": "MOMENTIVE PERFORMANCE MATERIALS BENELUX BV",
        "Gender": "Any",
        "Country": "Belgium",
        "Value": "Exempt"
    },
    {
        "type": "Work week",
        "Workertype": "Employee",
        "Location": "Any",
        "Exemptstatus": "Yes",
        "Shift": "Any",
        "Workersubtype_legalentity": "MOMENTIVE PERFORMANCE MATERIALS BENELUX BV",
        "Gender": "Any",
        "Country": "Belgium",
        "Value": "urn:replicon:day-of-week:monday"
    },
    {
        "type": "Time off types",
        "Workertype": "Employee",
        "Location": "Any",
        "Exemptstatus": "Yes",
        "Shift": "Any",
        "Workersubtype_legalentity": "MOMENTIVE PERFORMANCE MATERIALS BENELUX BV",
        "Gender": "Male",
        "Country": "Belgium",
        "Value": "[Bel] Adoptieverlof / Adoption|[Bel] ADV|[Bel] Anciënniteitsdag / Seniority|[Bel] Fietsdagen / Biking Days|[Bel] Jaarlijkse vakantie / Annual leave|[Bel] Occasioneel Telewerk / Occasional Home office|[Bel] Omstandigheidsverlof (Klein Verlet) / Special leave|[Bel] Onbetaald verlof / Unpaid leave|[Bel] Opleidingsverlof / Educational|[Bel] Ouderschapsverlof / Parental|[Bel] Pleegouderverlof / Foster parent|[Bel] Tijdskrediet / Sabbatical leave|[Bel] Vaderschapsverlof / Paternity|[Bel] Verlof om dwingende redenen  / Leave for Compelling reasons = leave for Unforeseen events|[Bel] Verlof om dwingende redenen / Leave for Unforeseen events = leave for compelling reasons|[Bel] Zakenreis+Werken elders / Foreign travel+Work abroad|[Bel] Ziekte / Sick leave|[Bel] Zorgverlof / Family care leave|[Bel] Zwangerschapsrust / Maternity"
    },
    {
        "type": "Time off types",
        "Workertype": "Employee",
        "Location": "Any",
        "Exemptstatus": "Yes",
        "Shift": "Any",
        "Workersubtype_legalentity": "MOMENTIVE PERFORMANCE MATERIALS BENELUX BV",
        "Gender": "Female",
        "Country": "Belgium",
        "Value": "[Bel] Adoptieverlof / Adoption|[Bel] ADV|[Bel] Anciënniteitsdag / Seniority|[Bel] Fietsdagen / Biking Days|[Bel] Jaarlijkse vakantie / Annual leave|[Bel] Occasioneel Telewerk / Occasional Home office|[Bel] Omstandigheidsverlof (Klein Verlet) / Special leave|[Bel] Onbetaald verlof / Unpaid leave|[Bel] Opleidingsverlof / Educational|[Bel] Ouderschapsverlof / Parental|[Bel] Pleegouderverlof / Foster parent|[Bel] Tijdskrediet / Sabbatical leave|[Bel] Vaderschapsverlof / Paternity|[Bel] Verlof om dwingende redenen  / Leave for Compelling reasons = leave for Unforeseen events|[Bel] Verlof om dwingende redenen / Leave for Unforeseen events = leave for compelling reasons|[Bel] Zakenreis+Werken elders / Foreign travel+Work abroad|[Bel] Ziekte / Sick leave|[Bel] Zorgverlof / Family care leave|[Bel] Zwangerschapsrust / Maternity"
    },
    {
        "type": "Holiday Calendar",
        "Workertype": "Employee",
        "Location": "Any",
        "Exemptstatus": "Yes",
        "Shift": "Any",
        "Workersubtype_legalentity": "MOMENTIVE PERFORMANCE MATERIALS FRANCE SARL",
        "Gender": "Any",
        "Country": "France",
        "Value": "France"
    },
    {
        "type": "Schedule",
        "Workertype": "Employee",
        "Location": "Any",
        "Exemptstatus": "Yes",
        "Shift": "Any",
        "Workersubtype_legalentity": "MOMENTIVE PERFORMANCE MATERIALS FRANCE SARL",
        "Gender": "Any",
        "Country": "France",
        "Value": "8 hours/day; Mon-Fri"
    },
    {
        "type": "Time off apporval path",
        "Workertype": "Employee",
        "Location": "Any",
        "Exemptstatus": "Yes",
        "Shift": "Any",
        "Workersubtype_legalentity": "MOMENTIVE PERFORMANCE MATERIALS FRANCE SARL",
        "Gender": "Any",
        "Country": "France",
        "Value": "Supervisor"
    },
    {
        "type": "Language",
        "Workertype": "Employee",
        "Location": "Any",
        "Exemptstatus": "Any",
        "Shift": "Any",
        "Workersubtype_legalentity": "MOMENTIVE PERFORMANCE MATERIALS FRANCE SARL",
        "Gender": "Any",
        "Country": "France",
        "Value": "urn:replicon:language:en"
    },
    {
        "type": "Time off types",
        "Workertype": "Employee",
        "Location": "Any",
        "Exemptstatus": "Yes",
        "Shift": "Any",
        "Workersubtype_legalentity": "MOMENTIVE PERFORMANCE MATERIALS FRANCE SARL",
        "Gender": "Male",
        "Country": "France",
        "Value": "FRA_Vacation|FRA_RTT= Réduction du temps de travail|FRA_Sick paid|FRA_Sick paid eligible for reimbursement|FRA_Sick longterm unpaid|FRA_Parental Leav|FRA_Travel|FRA_Travel within EU|FRA_Other|FRA_Historical Leave balance|FRA_Advance Vacation Days"
    },
    {
        "type": "Time off types",
        "Workertype": "Employee",
        "Location": "Any",
        "Exemptstatus": "Yes",
        "Shift": "Any",
        "Workersubtype_legalentity": "MOMENTIVE PERFORMANCE MATERIALS FRANCE SARL",
        "Gender": "Female",
        "Country": "France",
        "Value": "FRA_Vacation|FRA_RTT= Réduction du temps de travail|FRA_Sick paid|FRA_Sick paid eligible for reimbursement|FRA_Sick longterm unpaid|FRA_Parental Leave|FRA_Travel|FRA_Travel within EU|FRA_Other|FRA_Maternity|FRA_Historical Leave balance|FRA_Advance Vacation Days"
    },
    {
        "type": "Employee Type",
        "Workertype": "Employee",
        "Location": "Any",
        "Exemptstatus": "Yes",
        "Shift": "Any",
        "Workersubtype_legalentity": "MOMENTIVE PERFORMANCE MATERIALS FRANCE SARL",
        "Gender": "Any",
        "Country": "France",
        "Value": "Exempt"
    },
    {
        "type": "Work week",
        "Workertype": "Employee",
        "Location": "Any",
        "Exemptstatus": "Yes",
        "Shift": "Any",
        "Workersubtype_legalentity": "MOMENTIVE PERFORMANCE MATERIALS FRANCE SARL",
        "Gender": "Any",
        "Country": "France",
        "Value": "urn:replicon:day-of-week:monday"
    },
    {
        "type": "Time zone",
        "Workertype": "Employee",
        "Location": "Any",
        "Exemptstatus": "Yes",
        "Shift": "Any",
        "Workersubtype_legalentity": "MOMENTIVE PERFORMANCE MATERIALS FRANCE SARL",
        "Gender": "Any",
        "Country": "France",
        "Value": "Europe/Warsaw"
    },
    {
        "type": "Holiday Calendar",
        "Workertype": "Employee",
        "Location": "Any",
        "Exemptstatus": "Yes",
        "Shift": "Any",
        "Workersubtype_legalentity": "MOMENTIVE PERFORMANCE MATERIALS LTD",
        "Gender": "Any",
        "Country": "United Kingdom",
        "Value": "United Kingdom"
    },
    {
        "type": "Holiday Calendar",
        "Workertype": "Contingent Worker",
        "Location": "Any",
        "Exemptstatus": "No",
        "Shift": "Any",
        "Workersubtype_legalentity": "MOMENTIVE PERFORMANCE MATERIALS LTD",
        "Gender": "Any",
        "Country": "United Kingdom",
        "Value": "United Kingdom"
    },
    {
        "type": "Schedule",
        "Workertype": "Employee",
        "Location": "Any",
        "Exemptstatus": "Yes",
        "Shift": "Any",
        "Workersubtype_legalentity": "MOMENTIVE PERFORMANCE MATERIALS LTD",
        "Gender": "Any",
        "Country": "United Kingdom",
        "Value": "8 hours/day; Mon-Fri"
    },
    {
        "type": "Schedule",
        "Workertype": "Employee",
        "Location": "Any",
        "Exemptstatus": "No",
        "Shift": "Any",
        "Workersubtype_legalentity": "MOMENTIVE PERFORMANCE MATERIALS LTD",
        "Gender": "Any",
        "Country": "United Kingdom",
        "Value": "8 hours/day; Mon-Fri"
    },
    {
        "type": "Schedule",
        "Workertype": "Contingent Worker",
        "Location": "Any",
        "Exemptstatus": "Yes",
        "Shift": "Any",
        "Workersubtype_legalentity": "MOMENTIVE PERFORMANCE MATERIALS LTD",
        "Gender": "Any",
        "Country": "United Kingdom",
        "Value": "8 hours/day; Mon-Fri"
    },
    {
        "type": "Schedule",
        "Workertype": "Contingent Worker",
        "Location": "Any",
        "Exemptstatus": "No",
        "Shift": "Any",
        "Workersubtype_legalentity": "MOMENTIVE PERFORMANCE MATERIALS LTD",
        "Gender": "Any",
        "Country": "United Kingdom",
        "Value": "8 hours/day; Mon-Fri"
    },
    {
        "type": "Schedule",
        "Workertype": "Employee",
        "Location": "Any",
        "Exemptstatus": "Yes",
        "Shift": "PRODUCTION Rota",
        "Workersubtype_legalentity": "MOMENTIVE PERFORMANCE MATERIALS LTD",
        "Gender": "Any",
        "Country": "United Kingdom",
        "Value": "Shift"
    },
    {
        "type": "Schedule",
        "Workertype": "Contingent Worker",
        "Location": "Any",
        "Exemptstatus": "No",
        "Shift": "PRODUCTION Rota",
        "Workersubtype_legalentity": "MOMENTIVE PERFORMANCE MATERIALS LTD",
        "Gender": "Any",
        "Country": "United Kingdom",
        "Value": "Shift"
    },
    {
        "type": "Schedule",
        "Workertype": "Employee",
        "Location": "Any",
        "Exemptstatus": "No",
        "Shift": "PRODUCTION Rota",
        "Workersubtype_legalentity": "MOMENTIVE PERFORMANCE MATERIALS LTD",
        "Gender": "Any",
        "Country": "United Kingdom",
        "Value": "Shift"
    },
    {
        "type": "Schedule",
        "Workertype": "Contingent Worker",
        "Location": "Any",
        "Exemptstatus": "Yes",
        "Shift": "PRODUCTION Rota",
        "Workersubtype_legalentity": "MOMENTIVE PERFORMANCE MATERIALS LTD",
        "Gender": "Any",
        "Country": "United Kingdom",
        "Value": "Shift"
    },
    {
        "type": "Schedule",
        "Workertype": "Employee",
        "Location": "Any",
        "Exemptstatus": "Yes",
        "Shift": "PRODUCTION Non Rota",
        "Workersubtype_legalentity": "MOMENTIVE PERFORMANCE MATERIALS LTD",
        "Gender": "Any",
        "Country": "United Kingdom",
        "Value": "8 hours/day; Mon-Fri"
    },
    {
        "type": "Schedule",
        "Workertype": "Employee",
        "Location": "Any",
        "Exemptstatus": "No",
        "Shift": "PRODUCTION Non Rota",
        "Workersubtype_legalentity": "MOMENTIVE PERFORMANCE MATERIALS LTD",
        "Gender": "Any",
        "Country": "United Kingdom",
        "Value": "8 hours/day; Mon-Fri"
    },
    {
        "type": "Language",
        "Workertype": "Employee",
        "Location": "Any",
        "Exemptstatus": "Any",
        "Shift": "Any",
        "Workersubtype_legalentity": "MOMENTIVE PERFORMANCE MATERIALS LTD",
        "Gender": "Any",
        "Country": "United Kingdom",
        "Value": "urn:replicon:language:en"
    },
    {
        "type": "Language",
        "Workertype": "Contingent Worker",
        "Location": "Any",
        "Exemptstatus": "Any",
        "Shift": "Any",
        "Workersubtype_legalentity": "MOMENTIVE PERFORMANCE MATERIALS LTD",
        "Gender": "Any",
        "Country": "United Kingdom",
        "Value": "urn:replicon:language:en"
    },
    {
        "type": "Employee Type",
        "Workertype": "Employee",
        "Location": "Any",
        "Exemptstatus": "Yes",
        "Shift": "Any",
        "Workersubtype_legalentity": "MOMENTIVE PERFORMANCE MATERIALS LTD",
        "Gender": "Any",
        "Country": "United Kingdom",
        "Value": "Exempt"
    },
    {
        "type": "Employee Type",
        "Workertype": "Contingent Worker",
        "Location": "Any",
        "Exemptstatus": "No",
        "Shift": "Any",
        "Workersubtype_legalentity": "MOMENTIVE PERFORMANCE MATERIALS LTD",
        "Gender": "Any",
        "Country": "United Kingdom",
        "Value": "Contingent Worker"
    },
    {
        "type": "Time zone",
        "Workertype": "Employee",
        "Location": "Any",
        "Exemptstatus": "Yes",
        "Shift": "Any",
        "Workersubtype_legalentity": "MOMENTIVE PERFORMANCE MATERIALS LTD",
        "Gender": "Any",
        "Country": "United Kingdom",
        "Value": "Europe/London"
    },
    {
        "type": "Time zone",
        "Workertype": "Employee",
        "Location": "Any",
        "Exemptstatus": "No",
        "Shift": "Any",
        "Workersubtype_legalentity": "MOMENTIVE PERFORMANCE MATERIALS LTD",
        "Gender": "Any",
        "Country": "United Kingdom",
        "Value": "Europe/London"
    },
    {
        "type": "Time zone",
        "Workertype": "Contingent Worker",
        "Location": "Any",
        "Exemptstatus": "No",
        "Shift": "Any",
        "Workersubtype_legalentity": "MOMENTIVE PERFORMANCE MATERIALS LTD",
        "Gender": "Any",
        "Country": "United Kingdom",
        "Value": "Europe/London"
    },
    {
        "type": "Work week",
        "Workertype": "Employee",
        "Location": "Any",
        "Exemptstatus": "Yes",
        "Shift": "Any",
        "Workersubtype_legalentity": "MOMENTIVE PERFORMANCE MATERIALS LTD",
        "Gender": "Any",
        "Country": "United Kingdom",
        "Value": "urn:replicon:day-of-week:monday"
    },
    {
        "type": "Work week",
        "Workertype": "Contingent Worker",
        "Location": "Any",
        "Exemptstatus": "No",
        "Shift": "Any",
        "Workersubtype_legalentity": "MOMENTIVE PERFORMANCE MATERIALS LTD",
        "Gender": "Any",
        "Country": "United Kingdom",
        "Value": "urn:replicon:day-of-week:monday"
    },
    {
        "type": "Payrule",
        "Workertype": "Employee",
        "Location": "Any",
        "Exemptstatus": "Yes",
        "Shift": "PRODUCTION Rota",
        "Workersubtype_legalentity": "MOMENTIVE PERFORMANCE MATERIALS LTD",
        "Gender": "Any",
        "Country": "United Kingdom",
        "Value": "UK Production Pay Rule"
    },
    {
        "type": "Payrule",
        "Workertype": "Contingent Worker",
        "Location": "Any",
        "Exemptstatus": "No",
        "Shift": "PRODUCTION Rota",
        "Workersubtype_legalentity": "MOMENTIVE PERFORMANCE MATERIALS LTD",
        "Gender": "Any",
        "Country": "United Kingdom",
        "Value": "UK Production Pay Rule"
    },
    {
        "type": "Punch entry policy",
        "Workertype": "Contingent Worker",
        "Location": "Any",
        "Exemptstatus": "No",
        "Shift": "PRODUCTION Rota",
        "Workersubtype_legalentity": "MOMENTIVE PERFORMANCE MATERIALS LTD",
        "Gender": "Any",
        "Country": "United Kingdom",
        "Value": "UK Punch Policy"
    },
    {
        "type": "Punch entry policy",
        "Workertype": "Contingent Worker",
        "Location": "Any",
        "Exemptstatus": "Yes",
        "Shift": "PRODUCTION Rota",
        "Workersubtype_legalentity": "MOMENTIVE PERFORMANCE MATERIALS LTD",
        "Gender": "Any",
        "Country": "United Kingdom",
        "Value": "UK Punch Policy"
    },
    {
        "type": "Time off types",
        "Workertype": "Employee",
        "Location": "Any",
        "Exemptstatus": "Yes",
        "Shift": "Any",
        "Workersubtype_legalentity": "MOMENTIVE PERFORMANCE MATERIALS LTD",
        "Gender": "Male",
        "Country": "United Kingdom",
        "Value": "UK_Holiday Paid|UK_Holiday Unpaid|UK_Sick Leave|UK_Sick Leave unpaid|UK_Compassionate Leave paid|UK_Medical Appointment|UK_Jury Service|UK_Training|UK_Business Trip|UK_Work from home|UK_Shared Parental Leave paid|UK_Paternity|UK_Paternity unpaid"
    },
    {
        "type": "Time off types",
        "Workertype": "Employee",
        "Location": "Any",
        "Exemptstatus": "No",
        "Shift": "Any",
        "Workersubtype_legalentity": "MOMENTIVE PERFORMANCE MATERIALS LTD",
        "Gender": "Male",
        "Country": "United Kingdom",
        "Value": "UK_Holiday Paid|UK_Holiday Unpaid|UK_Sick Leave|UK_Sick Leave unpaid|UK_Compassionate Leave paid|UK_Medical Appointment|UK_Jury Service|UK_Training|UK_Business Trip|UK_Work from home|UK_Shared Parental Leave paid|UK_Paternity|UK_Paternity unpaid"
    },
    {
        "type": "Employee Type",
        "Workertype": "Employee",
        "Location": "Any",
        "Exemptstatus": "No",
        "Shift": "Any",
        "Workersubtype_legalentity": "MOMENTIVE PERFORMANCE MATERIALS LTD",
        "Gender": "Any",
        "Country": "United Kingdom",
        "Value": "Non-Exempt"
    },
    {
        "type": "Holiday Calendar",
        "Workertype": "Employee",
        "Location": "Any",
        "Exemptstatus": "No",
        "Shift": "Any",
        "Workersubtype_legalentity": "MOMENTIVE PERFORMANCE MATERIALS LTD",
        "Gender": "Any",
        "Country": "United Kingdom",
        "Value": "United Kingdom"
    },
    {
        "type": "Payrule",
        "Workertype": "Employee",
        "Location": "Any",
        "Exemptstatus": "No",
        "Shift": "PRODUCTION Rota",
        "Workersubtype_legalentity": "MOMENTIVE PERFORMANCE MATERIALS LTD",
        "Gender": "Any",
        "Country": "United Kingdom",
        "Value": "UK Production Pay Rule"
    },
    {
        "type": "Payrule",
        "Workertype": "Contingent Worker",
        "Location": "Any",
        "Exemptstatus": "Yes",
        "Shift": "PRODUCTION Rota",
        "Workersubtype_legalentity": "MOMENTIVE PERFORMANCE MATERIALS LTD",
        "Gender": "Any",
        "Country": "United Kingdom",
        "Value": "UK Production Pay Rule"
    },
    {
        "type": "Payrule",
        "Workertype": "Employee",
        "Location": "Any",
        "Exemptstatus": "Yes",
        "Shift": "PRODUCTION Non Rota",
        "Workersubtype_legalentity": "MOMENTIVE PERFORMANCE MATERIALS LTD",
        "Gender": "Any",
        "Country": "United Kingdom",
        "Value": "UK Other Pay Rule"
    },
    {
        "type": "Payrule",
        "Workertype": "Contingent Worker",
        "Location": "Any",
        "Exemptstatus": "No",
        "Shift": "PRODUCTION Non Rota",
        "Workersubtype_legalentity": "MOMENTIVE PERFORMANCE MATERIALS LTD",
        "Gender": "Any",
        "Country": "United Kingdom",
        "Value": "UK Other Pay Rule"
    },
    {
        "type": "Payrule",
        "Workertype": "Employee",
        "Location": "Any",
        "Exemptstatus": "No",
        "Shift": "PRODUCTION Non Rota",
        "Workersubtype_legalentity": "MOMENTIVE PERFORMANCE MATERIALS LTD",
        "Gender": "Any",
        "Country": "United Kingdom",
        "Value": "UK Other Pay Rule"
    },
    {
        "type": "Payrule",
        "Workertype": "Contingent Worker",
        "Location": "Any",
        "Exemptstatus": "Yes",
        "Shift": "PRODUCTION Non Rota",
        "Workersubtype_legalentity": "MOMENTIVE PERFORMANCE MATERIALS LTD",
        "Gender": "Any",
        "Country": "United Kingdom",
        "Value": "UK Other Pay Rule"
    },
    {
        "type": "Punch entry policy",
        "Workertype": "Employee",
        "Location": "Any",
        "Exemptstatus": "Yes",
        "Shift": "PRODUCTION Rota",
        "Workersubtype_legalentity": "MOMENTIVE PERFORMANCE MATERIALS LTD",
        "Gender": "Any",
        "Country": "United Kingdom",
        "Value": "UK Punch Policy"
    },
    {
        "type": "Punch entry policy",
        "Workertype": "Employee",
        "Location": "Any",
        "Exemptstatus": "No",
        "Shift": "PRODUCTION Rota",
        "Workersubtype_legalentity": "MOMENTIVE PERFORMANCE MATERIALS LTD",
        "Gender": "Any",
        "Country": "United Kingdom",
        "Value": "UK Punch Policy"
    },
    {
        "type": "Punch entry policy",
        "Workertype": "Employee",
        "Location": "Any",
        "Exemptstatus": "No",
        "Shift": "PRODUCTION Non Rota",
        "Workersubtype_legalentity": "MOMENTIVE PERFORMANCE MATERIALS LTD",
        "Gender": "Any",
        "Country": "United Kingdom",
        "Value": "UK Punch Policy"
    },
    {
        "type": "Punch entry policy",
        "Workertype": "Employee",
        "Location": "Any",
        "Exemptstatus": "Yes",
        "Shift": "PRODUCTION Non Rota",
        "Workersubtype_legalentity": "MOMENTIVE PERFORMANCE MATERIALS LTD",
        "Gender": "Any",
        "Country": "United Kingdom",
        "Value": "UK Punch Policy"
    },
    {
        "type": "Punch entry policy",
        "Workertype": "Contingent Worker",
        "Location": "Any",
        "Exemptstatus": "No",
        "Shift": "PRODUCTION Non Rota",
        "Workersubtype_legalentity": "MOMENTIVE PERFORMANCE MATERIALS LTD",
        "Gender": "Any",
        "Country": "United Kingdom",
        "Value": "UK Punch Policy"
    },
    {
        "type": "Punch entry policy",
        "Workertype": "Contingent Worker",
        "Location": "Any",
        "Exemptstatus": "Yes",
        "Shift": "PRODUCTION Non Rota",
        "Workersubtype_legalentity": "MOMENTIVE PERFORMANCE MATERIALS LTD",
        "Gender": "Any",
        "Country": "United Kingdom",
        "Value": "UK Punch Policy"
    },
    {
        "type": "Schedule",
        "Workertype": "Contingent Worker",
        "Location": "Any",
        "Exemptstatus": "No",
        "Shift": "PRODUCTION Non Rota",
        "Workersubtype_legalentity": "MOMENTIVE PERFORMANCE MATERIALS LTD",
        "Gender": "Any",
        "Country": "United Kingdom",
        "Value": "8 hours/day; Mon-Fri"
    },
    {
        "type": "Schedule",
        "Workertype": "Contingent Worker",
        "Location": "Any",
        "Exemptstatus": "Yes",
        "Shift": "PRODUCTION Non Rota",
        "Workersubtype_legalentity": "MOMENTIVE PERFORMANCE MATERIALS LTD",
        "Gender": "Any",
        "Country": "United Kingdom",
        "Value": "8 hours/day; Mon-Fri"
    },
    {
        "type": "Time off apporval path",
        "Workertype": "Employee",
        "Location": "Any",
        "Exemptstatus": "Yes",
        "Shift": "Any",
        "Workersubtype_legalentity": "MOMENTIVE PERFORMANCE MATERIALS LTD",
        "Gender": "Any",
        "Country": "United Kingdom",
        "Value": "Supervisor"
    },
    {
        "type": "Time off apporval path",
        "Workertype": "Employee",
        "Location": "Any",
        "Exemptstatus": "No",
        "Shift": "Any",
        "Workersubtype_legalentity": "MOMENTIVE PERFORMANCE MATERIALS LTD",
        "Gender": "Any",
        "Country": "United Kingdom",
        "Value": "Supervisor"
    },
    {
        "type": "Time off apporval path",
        "Workertype": "Contingent Worker",
        "Location": "Any",
        "Exemptstatus": "Yes",
        "Shift": "Any",
        "Workersubtype_legalentity": "MOMENTIVE PERFORMANCE MATERIALS LTD",
        "Gender": "Any",
        "Country": "United Kingdom",
        "Value": "Supervisor"
    },
    {
        "type": "Time off apporval path",
        "Workertype": "Contingent Worker",
        "Location": "Any",
        "Exemptstatus": "No",
        "Shift": "Any",
        "Workersubtype_legalentity": "MOMENTIVE PERFORMANCE MATERIALS LTD",
        "Gender": "Any",
        "Country": "United Kingdom",
        "Value": "Supervisor"
    },
    {
        "type": "Time off apporval path",
        "Workertype": "Employee",
        "Location": "Any",
        "Exemptstatus": "Yes",
        "Shift": "PRODUCTION Rota",
        "Workersubtype_legalentity": "MOMENTIVE PERFORMANCE MATERIALS LTD",
        "Gender": "Any",
        "Country": "United Kingdom",
        "Value": "Supervisor"
    },
    {
        "type": "Time off apporval path",
        "Workertype": "Contingent Worker",
        "Location": "Any",
        "Exemptstatus": "No",
        "Shift": "PRODUCTION Rota",
        "Workersubtype_legalentity": "MOMENTIVE PERFORMANCE MATERIALS LTD",
        "Gender": "Any",
        "Country": "United Kingdom",
        "Value": "Supervisor"
    },
    {
        "type": "Time off apporval path",
        "Workertype": "Employee",
        "Location": "Any",
        "Exemptstatus": "No",
        "Shift": "PRODUCTION Rota",
        "Workersubtype_legalentity": "MOMENTIVE PERFORMANCE MATERIALS LTD",
        "Gender": "Any",
        "Country": "United Kingdom",
        "Value": "Supervisor"
    },
    {
        "type": "Time off apporval path",
        "Workertype": "Contingent Worker",
        "Location": "Any",
        "Exemptstatus": "Yes",
        "Shift": "PRODUCTION Rota",
        "Workersubtype_legalentity": "MOMENTIVE PERFORMANCE MATERIALS LTD",
        "Gender": "Any",
        "Country": "United Kingdom",
        "Value": "Supervisor"
    },
    {
        "type": "Time off apporval path",
        "Workertype": "Employee",
        "Location": "Any",
        "Exemptstatus": "Yes",
        "Shift": "PRODUCTION Non Rota",
        "Workersubtype_legalentity": "MOMENTIVE PERFORMANCE MATERIALS LTD",
        "Gender": "Any",
        "Country": "United Kingdom",
        "Value": "Supervisor"
    },
    {
        "type": "Time off apporval path",
        "Workertype": "Employee",
        "Location": "Any",
        "Exemptstatus": "No",
        "Shift": "PRODUCTION Non Rota",
        "Workersubtype_legalentity": "MOMENTIVE PERFORMANCE MATERIALS LTD",
        "Gender": "Any",
        "Country": "United Kingdom",
        "Value": "Supervisor"
    },
    {
        "type": "Time off apporval path",
        "Workertype": "Contingent Worker",
        "Location": "Any",
        "Exemptstatus": "No",
        "Shift": "PRODUCTION Non Rota",
        "Workersubtype_legalentity": "MOMENTIVE PERFORMANCE MATERIALS LTD",
        "Gender": "Any",
        "Country": "United Kingdom",
        "Value": "Supervisor"
    },
    {
        "type": "Time off apporval path",
        "Workertype": "Contingent Worker",
        "Location": "Any",
        "Exemptstatus": "Yes",
        "Shift": "PRODUCTION Non Rota",
        "Workersubtype_legalentity": "MOMENTIVE PERFORMANCE MATERIALS LTD",
        "Gender": "Any",
        "Country": "United Kingdom",
        "Value": "Supervisor"
    },
    {
        "type": "Timesheet approval path",
        "Workertype": "Employee",
        "Location": "Any",
        "Exemptstatus": "Yes",
        "Shift": "PRODUCTION Rota",
        "Workersubtype_legalentity": "MOMENTIVE PERFORMANCE MATERIALS LTD",
        "Gender": "Any",
        "Country": "United Kingdom",
        "Value": "Supervisor"
    },
    {
        "type": "Timesheet approval path",
        "Workertype": "Contingent Worker",
        "Location": "Any",
        "Exemptstatus": "No",
        "Shift": "PRODUCTION Rota",
        "Workersubtype_legalentity": "MOMENTIVE PERFORMANCE MATERIALS LTD",
        "Gender": "Any",
        "Country": "United Kingdom",
        "Value": "Supervisor"
    },
    {
        "type": "Timesheet approval path",
        "Workertype": "Employee",
        "Location": "Any",
        "Exemptstatus": "No",
        "Shift": "PRODUCTION Rota",
        "Workersubtype_legalentity": "MOMENTIVE PERFORMANCE MATERIALS LTD",
        "Gender": "Any",
        "Country": "United Kingdom",
        "Value": "Supervisor"
    },
    {
        "type": "Timesheet approval path",
        "Workertype": "Contingent Worker",
        "Location": "Any",
        "Exemptstatus": "Yes",
        "Shift": "PRODUCTION Rota",
        "Workersubtype_legalentity": "MOMENTIVE PERFORMANCE MATERIALS LTD",
        "Gender": "Any",
        "Country": "United Kingdom",
        "Value": "Supervisor"
    },
    {
        "type": "Timesheet approval path",
        "Workertype": "Employee",
        "Location": "Any",
        "Exemptstatus": "Yes",
        "Shift": "PRODUCTION Non Rota",
        "Workersubtype_legalentity": "MOMENTIVE PERFORMANCE MATERIALS LTD",
        "Gender": "Any",
        "Country": "United Kingdom",
        "Value": "Supervisor"
    },
    {
        "type": "Timesheet approval path",
        "Workertype": "Employee",
        "Location": "Any",
        "Exemptstatus": "No",
        "Shift": "PRODUCTION Non Rota",
        "Workersubtype_legalentity": "MOMENTIVE PERFORMANCE MATERIALS LTD",
        "Gender": "Any",
        "Country": "United Kingdom",
        "Value": "Supervisor"
    },
    {
        "type": "Timesheet approval path",
        "Workertype": "Contingent Worker",
        "Location": "Any",
        "Exemptstatus": "No",
        "Shift": "PRODUCTION Non Rota",
        "Workersubtype_legalentity": "MOMENTIVE PERFORMANCE MATERIALS LTD",
        "Gender": "Any",
        "Country": "United Kingdom",
        "Value": "Supervisor"
    },
    {
        "type": "Timesheet approval path",
        "Workertype": "Contingent Worker",
        "Location": "Any",
        "Exemptstatus": "Yes",
        "Shift": "PRODUCTION Non Rota",
        "Workersubtype_legalentity": "MOMENTIVE PERFORMANCE MATERIALS LTD",
        "Gender": "Any",
        "Country": "United Kingdom",
        "Value": "Supervisor"
    },
    {
        "type": "Timesheet Period",
        "Workertype": "Contingent Worker",
        "Location": "Any",
        "Exemptstatus": "Any",
        "Shift": "Any",
        "Workersubtype_legalentity": "MOMENTIVE PERFORMANCE MATERIALS LTD",
        "Gender": "Any",
        "Country": "United Kingdom",
        "Value": "Monthly"
    },
    {
        "type": "Timesheet Period",
        "Workertype": "Employee",
        "Location": "Any",
        "Exemptstatus": "Any",
        "Shift": "Any",
        "Workersubtype_legalentity": "MOMENTIVE PERFORMANCE MATERIALS LTD",
        "Gender": "Any",
        "Country": "United Kingdom",
        "Value": "Monthly"
    },
    {
        "type": "Timesheet Template",
        "Workertype": "Employee",
        "Location": "Any",
        "Exemptstatus": "Yes",
        "Shift": "PRODUCTION Rota",
        "Workersubtype_legalentity": "MOMENTIVE PERFORMANCE MATERIALS LTD",
        "Gender": "Any",
        "Country": "United Kingdom",
        "Value": "UK Timesheet"
    },
    {
        "type": "Timesheet Template",
        "Workertype": "Contingent Worker",
        "Location": "Any",
        "Exemptstatus": "No",
        "Shift": "PRODUCTION Rota",
        "Workersubtype_legalentity": "MOMENTIVE PERFORMANCE MATERIALS LTD",
        "Gender": "Any",
        "Country": "United Kingdom",
        "Value": "UK Timesheet"
    },
    {
        "type": "Timesheet Template",
        "Workertype": "Employee",
        "Location": "Any",
        "Exemptstatus": "No",
        "Shift": "PRODUCTION Rota",
        "Workersubtype_legalentity": "MOMENTIVE PERFORMANCE MATERIALS LTD",
        "Gender": "Any",
        "Country": "United Kingdom",
        "Value": "UK Timesheet"
    },
    {
        "type": "Timesheet Template",
        "Workertype": "Contingent Worker",
        "Location": "Any",
        "Exemptstatus": "Yes",
        "Shift": "PRODUCTION Rota",
        "Workersubtype_legalentity": "MOMENTIVE PERFORMANCE MATERIALS LTD",
        "Gender": "Any",
        "Country": "United Kingdom",
        "Value": "UK Timesheet"
    },
    {
        "type": "Timesheet Template",
        "Workertype": "Employee",
        "Location": "Any",
        "Exemptstatus": "Yes",
        "Shift": "PRODUCTION Non Rota",
        "Workersubtype_legalentity": "MOMENTIVE PERFORMANCE MATERIALS LTD",
        "Gender": "Any",
        "Country": "United Kingdom",
        "Value": "UK Timesheet"
    },
    {
        "type": "Timesheet Template",
        "Workertype": "Employee",
        "Location": "Any",
        "Exemptstatus": "No",
        "Shift": "PRODUCTION Non Rota",
        "Workersubtype_legalentity": "MOMENTIVE PERFORMANCE MATERIALS LTD",
        "Gender": "Any",
        "Country": "United Kingdom",
        "Value": "UK Timesheet"
    },
    {
        "type": "Timesheet Template",
        "Workertype": "Contingent Worker",
        "Location": "Any",
        "Exemptstatus": "No",
        "Shift": "PRODUCTION Non Rota",
        "Workersubtype_legalentity": "MOMENTIVE PERFORMANCE MATERIALS LTD",
        "Gender": "Any",
        "Country": "United Kingdom",
        "Value": "UK Timesheet"
    },
    {
        "type": "Timesheet Template",
        "Workertype": "Contingent Worker",
        "Location": "Any",
        "Exemptstatus": "Yes",
        "Shift": "PRODUCTION Non Rota",
        "Workersubtype_legalentity": "MOMENTIVE PERFORMANCE MATERIALS LTD",
        "Gender": "Any",
        "Country": "United Kingdom",
        "Value": "UK Timesheet"
    },
    {
        "type": "Work week",
        "Workertype": "Employee",
        "Location": "Any",
        "Exemptstatus": "No",
        "Shift": "Any",
        "Workersubtype_legalentity": "MOMENTIVE PERFORMANCE MATERIALS LTD",
        "Gender": "Any",
        "Country": "United Kingdom",
        "Value": "urn:replicon:day-of-week:monday"
    },
    {
        "type": "Time off types",
        "Workertype": "Employee",
        "Location": "Any",
        "Exemptstatus": "Yes",
        "Shift": "Any",
        "Workersubtype_legalentity": "MOMENTIVE PERFORMANCE MATERIALS LTD",
        "Gender": "Female",
        "Country": "United Kingdom",
        "Value": "UK_Holiday Paid|UK_Holiday Unpaid|UK_Sick Leave|UK_Sick Leave unpaid|UK_Compassionate Leave paid|UK_Medical Appointment|UK_Jury Service|UK_Training|UK_Business Trip|UK_Work from home|UK_Maternity Leave paid|UK_Maternity unpaid|UK_KIT Days|UK_Shared Parental Leave paid"
    },
    {
        "type": "Time off types",
        "Workertype": "Employee",
        "Location": "Any",
        "Exemptstatus": "No",
        "Shift": "Any",
        "Workersubtype_legalentity": "MOMENTIVE PERFORMANCE MATERIALS LTD",
        "Gender": "Female",
        "Country": "United Kingdom",
        "Value": "UK_Holiday Paid|UK_Holiday Unpaid|UK_Sick Leave|UK_Sick Leave unpaid|UK_Compassionate Leave paid|UK_Medical Appointment|UK_Jury Service|UK_Training|UK_Business Trip|UK_Work from home|UK_Maternity Leave paid|UK_Maternity unpaid|UK_KIT Days|UK_Shared Parental Leave paid"
    },
    {
        "type": "Time off types",
        "Workertype": "Contingent Worker",
        "Location": "Any",
        "Exemptstatus": "Yes",
        "Shift": "Any",
        "Workersubtype_legalentity": "MOMENTIVE PERFORMANCE MATERIALS LTD",
        "Gender": "Male",
        "Country": "United Kingdom",
        "Value": "UK_Holiday Paid|UK_Holiday Unpaid|UK_Sick Leave|UK_Sick Leave unpaid|UK_Compassionate Leave paid|UK_Medical Appointment|UK_Jury Service|UK_Training|UK_Business Trip|UK_Work from home|UK_Shared Parental Leave paid|UK_Paternity|UK_Paternity unpaid"
    },
    {
        "type": "Time off types",
        "Workertype": "Contingent Worker",
        "Location": "Any",
        "Exemptstatus": "No",
        "Shift": "Any",
        "Workersubtype_legalentity": "MOMENTIVE PERFORMANCE MATERIALS LTD",
        "Gender": "Male",
        "Country": "United Kingdom",
        "Value": "UK_Holiday Paid|UK_Holiday Unpaid|UK_Sick Leave|UK_Sick Leave unpaid|UK_Compassionate Leave paid|UK_Medical Appointment|UK_Jury Service|UK_Training|UK_Business Trip|UK_Work from home|UK_Shared Parental Leave paid|UK_Paternity|UK_Paternity unpaid"
    },
    {
        "type": "Time off types",
        "Workertype": "Contingent Worker",
        "Location": "Any",
        "Exemptstatus": "Yes",
        "Shift": "Any",
        "Workersubtype_legalentity": "MOMENTIVE PERFORMANCE MATERIALS LTD",
        "Gender": "Female",
        "Country": "United Kingdom",
        "Value": "UK_Holiday Paid|UK_Holiday Unpaid|UK_Sick Leave|UK_Sick Leave unpaid|UK_Compassionate Leave paid|UK_Medical Appointment|UK_Jury Service|UK_Training|UK_Business Trip|UK_Work from home|UK_Maternity Leave paid|UK_Maternity unpaid|UK_KIT Days|UK_Shared Parental Leave paid"
    },
    {
        "type": "Time off types",
        "Workertype": "Contingent Worker",
        "Location": "Any",
        "Exemptstatus": "No",
        "Shift": "Any",
        "Workersubtype_legalentity": "MOMENTIVE PERFORMANCE MATERIALS LTD",
        "Gender": "Female",
        "Country": "United Kingdom",
        "Value": "UK_Holiday Paid|UK_Holiday Unpaid|UK_Sick Leave|UK_Sick Leave unpaid|UK_Compassionate Leave paid|UK_Medical Appointment|UK_Jury Service|UK_Training|UK_Business Trip|UK_Work from home|UK_Maternity Leave paid|UK_Maternity unpaid|UK_KIT Days|UK_Shared Parental Leave paid"
    },
    {
        "type": "Timesheet Template",
        "Workertype": "Employee",
        "Location": "Any",
        "Exemptstatus": "Yes",
        "Shift": "Any",
        "Workersubtype_legalentity": "MOMENTIVE PERFORMANCE MATERIALS KOREA CO., LTD.",
        "Gender": "Any",
        "Country": "South Korea",
        "Value": "South Korea"
    },
    {
        "type": "Timesheet Template",
        "Workertype": "Contingent Worker",
        "Location": "Any",
        "Exemptstatus": "No",
        "Shift": "Any",
        "Workersubtype_legalentity": "MOMENTIVE PERFORMANCE MATERIALS KOREA CO., LTD.",
        "Gender": "Any",
        "Country": "South Korea",
        "Value": "South Korea"
    },
    {
        "type": "Timesheet Template",
        "Workertype": "Employee",
        "Location": "Any",
        "Exemptstatus": "No",
        "Shift": "Any",
        "Workersubtype_legalentity": "MOMENTIVE PERFORMANCE MATERIALS KOREA CO., LTD.",
        "Gender": "Any",
        "Country": "South Korea",
        "Value": "South Korea"
    },
    {
        "type": "Punch entry policy",
        "Workertype": "Employee",
        "Location": "Any",
        "Exemptstatus": "Yes",
        "Shift": "Any",
        "Workersubtype_legalentity": "MOMENTIVE PERFORMANCE MATERIALS KOREA CO., LTD.",
        "Gender": "Any",
        "Country": "South Korea",
        "Value": "SK_Exempt"
    },
    {
        "type": "Punch entry policy",
        "Workertype": "Contingent Worker",
        "Location": "Any",
        "Exemptstatus": "No",
        "Shift": "Any",
        "Workersubtype_legalentity": "MOMENTIVE PERFORMANCE MATERIALS KOREA CO., LTD.",
        "Gender": "Any`",
        "Country": "South Korea",
        "Value": "SK_Non Exempt"
    },
    {
        "type": "Punch entry policy",
        "Workertype": "Employee",
        "Location": "Any",
        "Exemptstatus": "No",
        "Shift": "Any",
        "Workersubtype_legalentity": "MOMENTIVE PERFORMANCE MATERIALS KOREA CO., LTD.",
        "Gender": "Any",
        "Country": "South Korea",
        "Value": "SK_Exempt"
    },
    {
        "type": "Payrule",
        "Workertype": "Employee",
        "Location": "Any",
        "Exemptstatus": "Yes",
        "Shift": "Any",
        "Workersubtype_legalentity": "MOMENTIVE PERFORMANCE MATERIALS KOREA CO., LTD.",
        "Gender": "Any",
        "Country": "South Korea",
        "Value": "South Korea_Exempt"
    },
    {
        "type": "Payrule",
        "Workertype": "Contingent Worker",
        "Location": "Any",
        "Exemptstatus": "No",
        "Shift": "Any",
        "Workersubtype_legalentity": "MOMENTIVE PERFORMANCE MATERIALS KOREA CO., LTD.",
        "Gender": "Any",
        "Country": "South Korea",
        "Value": "South Korea_Non Exempt"
    },
    {
        "type": "Payrule",
        "Workertype": "Employee",
        "Location": "Any",
        "Exemptstatus": "No",
        "Shift": "Any",
        "Workersubtype_legalentity": "MOMENTIVE PERFORMANCE MATERIALS KOREA CO., LTD.",
        "Gender": "Any",
        "Country": "South Korea",
        "Value": "South Korea_Contingent Worker"
    },
    {
        "type": "Timesheet approval path",
        "Workertype": "Employee",
        "Location": "Any",
        "Exemptstatus": "Yes",
        "Shift": "Any",
        "Workersubtype_legalentity": "MOMENTIVE PERFORMANCE MATERIALS KOREA CO., LTD.",
        "Gender": "Any",
        "Country": "South Korea",
        "Value": "System Approval"
    },
    {
        "type": "Timesheet approval path",
        "Workertype": "Employee",
        "Location": "Any",
        "Exemptstatus": "No",
        "Shift": "Any",
        "Workersubtype_legalentity": "MOMENTIVE PERFORMANCE MATERIALS KOREA CO., LTD.",
        "Gender": "Any",
        "Country": "South Korea",
        "Value": "Supervisor --> HRM"
    },
    {
        "type": "Timesheet approval path",
        "Workertype": "Contingent Worker",
        "Location": "Any",
        "Exemptstatus": "No",
        "Shift": "Any",
        "Workersubtype_legalentity": "MOMENTIVE PERFORMANCE MATERIALS KOREA CO., LTD.",
        "Gender": "Any",
        "Country": "South Korea",
        "Value": "System Approval"
    }
]
