instance = 'production'
region = 'us-east-1'
environment = 'production'
execution_timeout_days = 14
master_max_active_runs = 5
child_dag_max_active_runs = 3
company_key = f"airflow{region.replace('-', '')}"
hmac_secret = 'airflow_connector_ui_hmac_secret'
replicon_conn_id = 'airflow-replicon-admin'
can_run_batch_task_var_name = f'standard_jira_user_export_{instance}_can_run_batch_task'
airflow_connector_ui_connid = 'airflow_connector_ui_endpoint'
