country_list_trial={"Spain":"ES",
                    "Germany":"Germany",
                    "France":"France",
                    "Portugal":"PT",
                    "Netherlands":"NL",
                    "Romania":"RO",
                    "Saudi Arabia": "SA",
                    "Poland":"PL",
                    "Belgium": "BE",
                    "Ireland": "IE",
                    "Austria": "AT",
                    "Switzerland": "CH",
                    "United Kingdom": "GB",
                }
country_list_prod = {
    "Spain":"ES",
    "Germany":"Germany",
    "France":"France",
    "Portugal":"PT",
    "Netherlands":"NL",
    "Romania":"RO",
    "Saudi Arabia": "SA",
    "Poland":"PL",
    "Belgium": "BE",
    "Ireland": "IE",
    "Austria": "AT",
    "Switzerland": "CH",
    "United Kingdom": "GB",
}
