gfs_paycodes_list = (
	"Astreinte nuit semaine",
	"Astreinte jour samedi, dimanche, JF",
	"Astreinte nuit week-end (Vend soir/Sam soir/Dim soir)",
	"Astreinte nuit veille jour férié",
	"Astreinte WE complet vendredi à lundi",
	"Astreinte semaine complète",
	"Call Out Day Week Altran",
	"Call Out Night Week Altran",
	"Call Out Day Sunday/Holiday Altran",
	"Call Out Night Sunday/Holiday Altran",
	"Pr. astreinte isolée sem. <12h",
	"Pr. astreinte isolée samedi",
	"Pr. astreinte isolée dimanche",
	"Pr. astreinte isolée jour férié",
	"Pr. astreinte WE complet",
	"Pr. astreinte continue semaine <12h",
	"Pr. astreinte continue samedi",
	"Pr. astreinte continue dimanche",
	"Pr. astreinte continue Jours spéciaux",
	"H Inter.Astr. 125% (1607h)",
	"H Inter.Astr. 175% (1607h)",
	"H Inter.Astr. 200% (1607h)",
	"H Inter.Astr. 125% (1607h) recovery",
	"H Inter.Astr. 175% (1607h) recovery",
	"H Inter.Astr. 200% (1607h) recovery",
	"H Inter.Astr. 125% (218j)",
	"H Inter.Astr. 175% (218j)",
	"H Inter.Astr. 200% (218j)",
	"Maj.Astreinte 25% (218j)",
	"Maj.Astreinte 75% (218j)",
	"Maj.Astreinte 100% (218j)",
	"Prime shift (jour) Altran",
	"Prime shift (nuit) Altran",
	"Prime shift (forfait) Altran",
	"Prime d'équipes successives",
	"Prime d'horaires décalés",
	"Prime de repas",
	"TEA 175%",
	"TEA 125%",
	"TEA 200%",
	"TEA 175% recovery",
	"TEA 125% recovery",
	"TEA 200% recovery",
	"TEA 175% 218 j",
	"TEA 125% 218 j",
	"TEA 200% 218 j",
	"TEA 175% recovered / paid",
	"TEA 125% recovered / paid",
	"TEA 200% recovered / paid",
	"Prime de repas net",
	"HIRIS Indemnité de petit déjeuner"
)
