sopra_paycodes_list = (
	"Astreinte nuit semaine",
	"Astreinte jour samedi, dimanche, JF",
	"Astreinte nuit week-end (Vend soir/Sam soir/Dim soir)",
	"Astreinte nuit veille jour férié",
	"Astreinte WE complet vendredi à lundi",
	"Astreinte semaine complète",
	"Pr. astreinte isolée sem. <12h",
	"Pr. astreinte isolée samedi",
	"Pr. astreinte isolée dimanche",
	"Pr. astreinte isolée jour férié",
	"Pr. astreinte WE complet",
	"Pr. astreinte continue semaine <12h",
	"Pr. astreinte continue samedi",
	"Pr. astreinte continue dimanche",
	"Pr. astreinte continue Jours spéciaux",
	"H Inter.Astr. 125% (1607h)",
	"H Inter.Astr. 175% (1607h)",
	"H Inter.Astr. 200% (1607h)",
	"H Inter.Astr. 125% (218j)",
	"H Inter.Astr. 175% (218j)",
	"H Inter.Astr. 200% (218j)",
	"Maj.Astreinte 25% (218j)",
	"Maj.Astreinte 75% (218j)",
	"Maj.Astreinte 100% (218j)",
	"Prime shift (jour) Altran",
	"Prime shift (nuit) Altran",
	"Prime shift (forfait) Altran",
	"Prime d'équipes successives",
	"Prime d'horaires décalés",
	"Prime de repas",
	"HIRIS Indemnité de petit déjeuner",
	"TEA 175%",
	"TEA 125%",
	"TEA 200%",
	"TEA 175% 218 j",
	"TEA 125% 218 j",
	"TEA 200% 218 j",
	"TEA 175% recovered / paid",
	"TEA 125% recovered / paid",
	"TEA 200% recovered / paid",
	"Heures de récupération à 125%",
	"Majoration 1er mai Altran",
	"Majorations heures de nuit Altran",
	"Majorations heures dim. et jf Altran",
	"Heures normales à 100%",
	"Heures supplémentaires à 125%",
	"Heures supplémentaires à 150%",
	"Heures complémentaires",
	"Heures complémentaires 125%",
	"Heures complémentaires à 110%",
	"Majoration 1er mai",
	"Majorations heures de nuit",
	"Majorations heures dim. et jf"
)
