holiday_calendar ={
  "Aargau": "Switzerland - Aargau",
  "Appenzell Ausserrhoden": "Switzerland - Appenzell Ausserrhoden",
  "Appenzell Innerrhoden": "Switzerland - Appenzell Innerrhoden",
  "Basel-Landschaft": "Switzerland - Basel-Landschaft",
  "Basel-Stadt": "Switzerland - Basel-Stadt",
  "Bern": "Switzerland - Bern",
  "Fribourg": "Switzerland - Fribourg",
  "Geneva": "Switzerland - Geneva",
  "Glarus": "Switzerland - Glarus",
  "Graubunden": "Switzerland - Graubunden",
  "Jura": "Switzerland - Jura",
  "Luzern": "Switzerland - Luzern",
  "Neuchatel": "Switzerland - Neuchatel",
  "Nidwalden": "Switzerland - Nidwalden",
  "Obwalden": "Switzerland - Obwalden",
  "Schaffhausen": "Switzerland - Schaffhausen",
  "Schwyz": "Switzerland - Schwyz",
  "Solothurn": "Switzerland - Solothurn",
  "St. Gallen": "Switzerland - St. Gallen",
  "Switzerland": "Switzerland - Switzerland",
  "Thurgau": "Switzerland - Thurgau",
  "Ticino": "Switzerland - Ticino",
  "Uri": "Switzerland - Uri",
  "Valais": "Switzerland - Valais",
  "Vaud": "Switzerland - Vaud",
  "Zug": "Switzerland - Zug",
  "Zurich": "Switzerland - Zurich"
}