region = 'us-east-1'
environment = 'pre-production'
instance = "DaimlerTrucksafmig"
company_key = 'DaimlerTrucksafmig'
replicon_conn_id = 'DaimlerTrucksafmig_Project_Task_Import'
can_run_batch_task_var_name = f'daimlertrucks_project_task_import_can_run_batch_task_{instance}'
sftp_conn_id = "sftp_daimlertrucks_schedule_data_import"
input_filepath = "/DaimlerTrucksafmig/Engineering/Input"
referance_filepath = "/DaimlerTrucksafmig/Engineering/Reference"
archive_filepath = "/DaimlerTrucksafmig/Engineering/Archive"
execution_timeout_days = 14
child_dag_max_active_runs = 20
master_dag_interval = 30
log_filepath = "/DaimlerTrucksafmig/Engineering/Logs"
tenant_email = '{{ var.value.dagrun_internal_testing_email }}'
internal_logs_email = '{{ var.value.dagrun_internal_testing_email }}'
alert_email = '{{ var.value.dagrun_failure_alert_email }}'
disabled = True
