# pylint: disable=wildcard-import unused-wildcard-import
from dxctechnology.workday_user_import.user_import.config import *
from dxctechnology.workday_user_import.user_import.mappers.master_mapper_v2 import MAPPER
instance = "production"

version = "v0"

environment = "production"
can_run_batch_task_var_name = f"dxctechnology_workday_user_import_can_run_batch_task_variable_{instance}"

company_key = "dxctechnology"
replicon_conn_id = "dxctechnology_replicon_x.replicon.workday1"
sftp_conn_id = "sftp_dxctechnology_628172_Workday"

pgp_conn_id = "dxctechnology_workday_user_import_pgp_connection"

input_file_path = "/Production/Input"
archive_file_path = "/Production/Archives"
log_file_path = "/Production/Logs"

tenant_email = 'dxcintegrationlogsreplicon@deltek.com'
internal_logs_email = '{{ var.value.dagrun_internal_log_email }}'
alert_email = '{{ var.value.dagrun_failure_alert_email }}'
bcc_emails = '{{ var.value.dagrun_internal_log_email }}'

can_decrypt_file_var_name = f'dxctechnology_workday_user_sync_can_decrypt_file_{instance}'

DXC_WORKDAY_USER_SYNC_USER_MAPPER = MAPPER

workday_user_import_australia_users_add_user_child_dag = f"dxctechnology_workday_user_import_australia_users_add_user_child_{instance}_{version}"
workday_user_import_australia_users_add_user_timeoff_process_child_dag = f"dxctechnology_workday_user_import_australia_users_add_user_timeoff_process_child_{instance}_{version}"
workday_user_import_australia_users_update_user_timeoff_process_child_dag = f"dxctechnology_workday_user_import_australia_users_update_user_timeoff_process_child_{instance}_{version}"
workday_user_import_australia_users_add_user_timeoff_process_child_for_canada_dag = f"dxctechnology_workday_user_import_australia_users_add_user_timeoff_process_child_for_canada_{instance}_{version}"
workday_user_import_australia_users_update_user_timeoff_process_child_dag_disable = f"dxctechnology_workday_user_import_australia_users_update_user_timeoff_process_child_for_disable_user_{instance}_{version}"
workday_user_import_australia_users_update_user_child_dag = f"dxctechnology_workday_user_import_australia_users_update_user_child_{instance}_{version}"

workday_user_import_australia_users_update_user_rehire_timeoff_process_child_dag = f"dxctechnology_workday_user_import_australia_users_update_user_rehire_timeoff_assignment_process_child_{instance}_{version}"
workday_user_import_australia_users_aus_personal_carers_leave_timeoff_assignment_child_dag = f"dxctechnology_workday_user_import_australia_users_aus_personal_carers_leave_timeoff_assignment_child_{instance}_{version}"
workday_user_import_australia_users_aus_annual_leave_parttime_timeoff_assignment_child_dag = f"dxctechnology_workday_user_import_australia_users_aus_annual_leave_parttime_timeoff_assignment_child_{instance}_{version}"
workday_user_import_australia_users_aus_long_service_leave_timeoff_assignment_child_dag = f"dxctechnology_workday_user_import_australia_users_aus_long_service_leave_timeoff_assignment_child_{instance}_{version}"
workday_user_import_australia_users_aus_lsl_protata_timeoff_assignment_child_dag = f"dxctechnology_workday_user_import_australia_users_aus_lsl_protata_timeoff_assignment_child_{instance}_{version}"
workday_user_import_australia_users_aus_annual_leave_timeoff_assignment_child_dag = f"dxctechnology_workday_user_import_australia_users_aus_annual_leave_timeoff_assignment_child_{instance}_{version}"

# Available in GBL setup
workday_user_import_global_users_update_user_timeoff_process_child_dag_disable = f"dxctechnology_workday_user_import_global_users_update_user_timeoff_process_child_for_disable_user_{instance}_{version}"

process_time_off_accrual = f"dxctechnology_workday_user_sync_timeoff_assignment_policy_update_for_no_accrual_child_{instance}_{version}"

workday_user_import_ia_zero_timeoff_assignment_child_dag = f"dxctechnology_workday_user_import_ia_zero_timeoff_assignment_child_{instance}_{version}"
workday_user_import_ia_one_timeoff_assignment_child_dag = f"dxctechnology_workday_user_import_ia_one_timeoff_assignment_child_{instance}_{version}"

timeoff_process_max_active_run = 5
user_process_max_active_run = 5

# Cleanup child DAG ID for disabled users
delete_future_entries_child_dag_id = f"dxctechnology_workday_user_sync_delete_future_entries_child_{instance}"
